### ISSUE TITLE
[Bug]: the download and preview functionality in the file manage run error

### ISSUE THREAD

**Issue by zhanghaiqiangshigezhu** [infiniflow/ragflow#1000]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3333

### Actual behavior

the download and preview functionality in the file manage run error
![click_download](https://github.com/infiniflow/ragflow/assets/21963943/09164820-9495-4eea-a0e2-7f7565037342)

### Steps to reproduce

```Markdown
click the button of download and preview , the api has occurs.
```

**Comment by KevinHuSh** [comment]
It seems the file is missing. Is it locally depolyed?

**Comment by chinamerp** [comment]
the file can download but cann't preview. the preview error is: TypeError("The view function for 'file.get' did not return a valid response. The function either returned None or ended without a return statement.")

**Comment by surmount1** [comment]
I encountered the same problem, have you solved it？
