### ISSUE TITLE
got a dimension error when using age embedding model to get embedding and bulk (1024 but need 1025?)

### ISSUE THREAD

**Issue by 652994331** [infiniflow/ragflow#1003]
### Describe your problem

I got an error when I was trying to bulking my pdf files into es (my es is a docker service with version 8.11.2). the bug is: '“file_name.pdf_0:{\'type\': \'document_parsing_exception\', \'reason\': "[1:21978] failed to parse: The [dense_vector] field [vector] in doc [document with id \'“file_name.pdf_0\'] has a different number of dimensions [1024] than defined in the mapping [1025]", \'caused_by\': {\'type\': \'illegal_argument_exception\',

another question is about kin field when searching : elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: field [q_1024_vec] does not exist in the mapping') . I guess it might associate with my bulking problem?

**Comment by KevinHuSh** [comment]
The dimension changed between the time of defining the fields and the time of setting the value to the fields.

**Comment by 652994331** [comment]
@KevinHuSh  but I didnt define the field of knn , I also didnt define the dimension of doc. I tries to define my mapping, but it still not working... (same problem)
![Screen Shot 2024-05-31 at 18 40 36](https://github.com/infiniflow/ragflow/assets/51428350/89ac09b4-0bc5-44ee-9893-53c5505f4557)
