### ISSUE TITLE
[Bug]: "Can't access Redis. Please check the Redis' status."

### ISSUE THREAD

**Issue by liuman632** [infiniflow/ragflow#1010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

liuman632

### Actual behavior

点击解析数据集报错"Can't access Redis. Please check the Redis' status."

### Steps to reproduce

```Markdown
选择知识库-数据集，选择已经上传的文件，点击解析状态栏刷新或者启动图标，提示错误"Can't access Redis. Please check the Redis' status."
```

### Additional information

for t in tsks:
        assert REDIS_CONN.queue_product(SVR_QUEUE_NAME, message=t), "Can't access Redis. Please check the Redis' status."

assert的作用可以需要看一下

**Comment by guoyuhao2330** [comment]
You can check to see if the redis service in docker is working properly

**Comment by zzzer1** [comment]
你这个问题解决了吗

**Comment by tuoxiebushuijiao** [comment]
请问有解决吗？同样的问题，检查了redis 是正常的

**Comment by yuzhichang** [comment]
Please try latest v0.14.0

**Comment by hpx502766238** [comment]
> Please try latest v0.14.0

Same problem,It can't access redis if I didn't expose the redis service port to the host in "docker-compose-base.yml": 
ports:
      - ${REDIS_PORT}:6379

**Comment by xiaomeixw** [comment]
请问有解决吗？同样的问题，检查了redis 是正常的

**Comment by WiseMaterialismer** [comment]
刚刚我也遇到了，检查docker-compose-base.yml的配置文件，看了docker ps中ragflow的redis状态，发现没有运行，重新docker compose up -d了一下就好了

**Comment by WiseMaterialismer** [comment]
发现好像是docker有多个redis，启动被顶了
我先是完全关掉所有的容器，然后只启动了ragflow，然后启动dify的时候，发现redis受到了影响（因为dify也有redis）
目前来说，是因为后启动的dify也有redis，导致影响了ragflow的redis
如果只启动ragflow，就可以正常用了，或是也许可以修改一下配置文件让他们不互相影响，但不太清楚该怎么办，正在研究

**Comment by hugplz** [comment]
> ## 刚刚我也遇到了，检查docker-compose-base.yml的配置文件，查看docker ps中ragflow的redis状态，发现没有运行，重新docker compose up -d就好了
> ## 想要是docker有多个redis，启动被顶了
> 我先是关掉所有的容器，只启动了ragflow，启动dify的时候，发现redis被重启了（因为dify也有redis）
> 目前来说，是因为后启动的dify也有redis，导致影响了ragflow的redis
> 如果只启动ragflow，就可以正常用了，或者也许可以修改一下配置文件让他们互相不影响，但不太清楚该怎么办，正在研究
> 发现是dify的redis命名不规范导致顶掉了ragflow的redis 解决方法1： 启动时分别使用 docker compose -p dify up -d docker compose -p ragflow up -d 进行启动，这样就可以了 解决方法2： 修改dify中.env和docker-compose中redis的名字，修改方式自己问ai，不会死可以留言

端口冲突，但是怎么改都解决不了，怎么办

**Comment by xiaomeixw** [comment]
> > ## 刚刚我也遇到了，检查docker-compose-base.yml的配置文件，查看docker ps中ragflow的redis状态，发现没有运行，重新docker compose up -d就好了
> > ## 想要是docker有多个redis，启动被顶了
> > 我先是关掉所有的容器，只启动了ragflow，启动dify的时候，发现redis被重启了（因为dify也有redis）
> > 目前来说，是因为后启动的dify也有redis，导致影响了ragflow的redis
> > 如果只启动ragflow，就可以正常用了，或者也许可以修改一下配置文件让他们互相不影响，但不太清楚该怎么办，正在研究
> > 发现是dify的redis命名不规范导致顶掉了ragflow的redis 解决方法1： 启动时分别使用 docker compose -p dify up -d docker compose -p ragflow up -d 进行启动，这样就可以了 解决方法2： 修改dify中.env和docker-compose中redis的名字，修改方式自己问ai，不会死可以留言
> 
> 端口冲突，但是怎么改都解决不了，怎么办

名称也要改

**Comment by shingler** [comment]
我遇到的问题是没装dify，但是服务器本身有redis。一开始docker compose的时候报错，说6379端口被占用。然后发现服务器本身跑着一个redis的实例。于是修改.env，把ragflow-redis的端口改为6380。docker compose成功了之后上传文档，点击解析，出现相同的问题。已确认服务器本身的redis和ragflow-redis（docker托管的）都正常运行。

**Comment by 02210666lwj** [comment]
> ## 刚刚我也遇到了，检查docker-compose-base.yml的配置文件，看了docker ps中ragflow的redis状态，发现没有运行，重新docker compose up -d了一下就好了
> ## 发现好像是docker有多个redis，启动被顶了
> 我先是完全关掉所有的容器，然后只启动了ragflow，启动dify的时候，发现redis被重启了（因为dify也有redis）
> 目前来说，是因为后启动的dify也有redis，导致影响了ragflow的redis
> 如果只启动ragflow，就可以正常用了，或是也许可以修改一下配置文件让他们不互相影响，但不太清楚该怎么办，正在研究
> 发现是dify的redis命名不规范导致顶掉了ragflow的redis解决方法1： 启动时候分别使用 docker compose -p dify up -d docker compose -p ragflow up -d 进行启动，这样就可以了 解决方法2： 修改dify中.env和docker-compose中redis的名字，修改方式自己问ai，实在不会可以留言

您好，我也遇到同样的问题
咱们可以加个QQ吗
2995969075
具体如何操作，我还是有点不会

**Comment by WiseMaterialismer** [comment]
> > ## 刚刚我也遇到了，检查docker-compose-base.yml的配置文件，看了docker ps中ragflow的redis状态，发现没有运行，重新docker compose up -d了一下就好了
> > ## 发现好像是docker有多个redis，启动被顶了
> > 我先是完全关掉所有的容器，然后只启动了ragflow，启动dify的时候，发现redis被重启了（因为dify也有redis） 目前来说，是因为后启动的dify也有redis，导致影响了ragflow的redis如果只启动ragflow，就可以正常用了，或是也许可以修改一下配置文件让他们不互相影响，但不太清楚该怎么办，正在研究发现是dify的redis命名不规范导致顶掉了ragflow的redis解决方法1：启动时分别使用 docker compose -p dify up -d docker compose -p ragflow up -d 进行启动，这样就可以了解决方法2： 修改dify中.env和docker-compose中redis的名字，修改方式自己问ai，实在不会可以留言
> 
> 您好，我也遇到同样的问题 咱们可以加个QQ吗 2995969075 具体如何操作，我还是有点不会

你搜索一下如何修改docker项目启动的名字和端口,之所以出现这个情况一般就是多个docker服务,同名或同端口
