### ISSUE TITLE
[Question]: How to improve the parallelism of file parsing?

### ISSUE THREAD

**Issue by liweiyang2023** [infiniflow/ragflow#1012]
### Describe your problem

I found that when I am processing multiple files at the same time, the parsing block is serial. 
After checking the server.py file, I found that the number of workers is only 1, and the parameters are not exposed in the configuration file.
 Is there any other way to improve the efficiency of parsing documents besides improving workers

**Comment by CamusGao** [comment]
just see entrypoint.sh in docker folder and there is a variable WS. You could pass this variable to docker by using -e or writing into docker-compose.yml if you're using docker.

**Comment by liweiyang2023** [comment]
> just see entrypoint.sh in docker folder and there is a variable WS. You could pass this variable to docker by using -e or writing into docker-compose.yml if you're using docker.只需在 docker 文件夹中看到 entrypoint.sh，就会有一个变量 WS。如果使用的是 docker，则可以使用 -e 或写入 docker-compose.yml 将此变量传递给 docker。



感谢你的解答!我现在已经在yaml文件添加了参数,尝试启动2个workers,但docker的容器还是只有一个server,这已经生效了吗?

WS=2
for ((i=0;i<WS;i++))
do
  task_exe $i $WS &
done

$PY api/ragflow_server.py

wait;


yaml file:

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow:${RAGFLOW_VERSION}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - WS=2
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://huggingface.co
    networks:
      - ragflow
    restart: always

**Comment by liweiyang2023** [comment]
> just see entrypoint.sh in docker folder and there is a variable WS. You could pass this variable to docker by using -e or writing into docker-compose.yml if you're using docker.只需在 docker 文件夹中看到 entrypoint.sh，就会有一个变量 WS。如果使用的是 docker，则可以使用 -e 或写入 docker-compose.yml 将此变量传递给 docker。

Thank you for your answer! I have successfully improved the parsing using your method
