### ISSUE TITLE
[Question]: Description Failed to configure the local model xinference

### ISSUE THREAD

**Issue by Alchemistqqqq** [infiniflow/ragflow#1025]
### Describe your problem

The local xinference deployment is as follows：
![image](https://github.com/infiniflow/ragflow/assets/146717415/c4fd5b18-5b98-4c95-89ad-44d12ad01ead)
When I select the embedding according to the tutorial and enter the model name and url, the following error occurs：
![image](https://github.com/infiniflow/ragflow/assets/146717415/c7656afd-68bf-4f8e-ae43-b8b74bb89ffc)
![image](https://github.com/infiniflow/ragflow/assets/146717415/1910fd66-7366-43f8-9f22-3a886a26a726)
The second figure is your example, so I was wondering how to fill in this url

**Comment by KevinHuSh** [comment]
Use IP of the machine instead of 127.0.0.1.

**Comment by Alchemistqqqq** [comment]
> Use IP of the machine instead of 127.0.0.1.
![image](https://github.com/infiniflow/ragflow/assets/146717415/b7e43b98-b93e-4bb5-b2e0-f6784d748949)
The machine's ip http://10.105.94.29/ is my ragflow web page, and my xinference is 127.0.0.1. So this should be the ip? I'm confused.
