### ISSUE TITLE
[Bug]: Any file parse will stuck at 50%

### ISSUE THREAD

**Issue by vhikd** [infiniflow/ragflow#1026]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1de31ca

### Actual behavior

Any file parsing, the information shows that it has been completed, but the status is stuck at 50%
![Xnip2024-06-01_15-44-47](https://github.com/infiniflow/ragflow/assets/4554748/10bfc0bb-4025-4300-9f8e-2d2bf3433ba4)

I have checked the task table.
When I upload only one file, it will insert two tasks into the task table.
I can't get it out.
Is there any wrong or some work I should do to get it over?

### Steps to reproduce

```Markdown
1.Build from source 
2.Debug task_executor.py
3.Debug rag_server.py
4.cd web
5.npm run dev
6.Open http://localhost:9222
7.Create a knowledge
8.Upload any file
```

**Comment by KevinHuSh** [comment]
There must be problem with data insertion of ES.

**Comment by vhikd** [comment]
I have re-installed ES locally, the problem was solved.
But I don't know why.
The ES was installed by Docker before , I hadn't change anything, just update ragflow from 0.5 to 0.7, and the problem  occurred.
This is my hardware info, no GPU,
![image](https://github.com/infiniflow/ragflow/assets/4554748/b068a5ab-ccf2-4e9f-a71d-4a80a1e888b9)

cpu family	: 6
model		: 154
model name	: 12th Gen Intel(R) Core(TM) i5-1240P
stepping	: 3
microcode	: 0x430
cpu MHz		: 400.000
cache size	: 12288 KB

Could you please tell me the reason ? And how to avoid this happen again ?

**Comment by KevinHuSh** [comment]
Got no clue!
