### ISSUE TITLE
[Question]: cannot start ragflow-server

### ISSUE THREAD

**Issue by QQR1** [infiniflow/ragflow#1028]
### Describe your problem

(base) yumu@QLing:/mnt/d/QLing/llm_app/ragflow/docker$ sudo docker-compose -f docker-compose-CN.yml up -d
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                  docker:default
[+] Running 4/5
 ✔ Container ragflow-redis   Running                                                                               0.0s
 ✔ Container ragflow-mysql   Healthy                                                                               0.0s
 ✔ Container ragflow-es-01   Healthy                                                                               0.0s
 ✔ Container ragflow-minio   Running                                                                               0.0s
 ⠸ Container ragflow-server  Starting                                                                              1.3s
Error response from daemon: driver failed programming external connectivity on endpoint ragflow-server (d57d3bb0e3c77e349c26a4bc999be00cd66d916c0666f47b6733377c698aa95f): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
(base) yumu@QLing:/mnt/d/QLing/llm_app/ragflow/docker$ sudo lsof -i:443
(base) yumu@QLing:/mnt/d/QLing/llm_app/ragflow/docker$

**Comment by QQR1** [comment]
解决了，用的wsl，是windows系统占用了443端口

**Comment by ysf-gd** [comment]
想问一下wsl是不是除了安装docker子系统还要安装unbuntun子系统呀？我进入docker系统之后，运行chmod +x ./entrypoint.sh和docker compose up -d显示没有docker-compose
