### ISSUE TITLE
How should we deal with the error problem of Redis?[Question]: 

### ISSUE THREAD

**Issue by lovewaves** [infiniflow/ragflow#1029]
### Describe your problem

When I upgraded from v0.4 to v0.7, Redis appeared.Error no such key,And the chat reports an error ERROR: BadRequestError (400,'search _ phase _ execution _ exception', 'failed to create query: field [q_1536_vec] does not exist in the mapping')

**Comment by xxz196801** [comment]
我也出现同样问题，不过在6.0就出现Redis显示Error:
no such key不知道如何解决

**Comment by KevinHuSh** [comment]
Redis is used for task schedule, no such key is not a big deal if parsing works well.
For q_1536_vec, I'm afraid you need to redo parsing. The embedding model for parsing and chating is not the same model.

**Comment by xxz196801** [comment]
谢谢您的回复，我的问题解决了！
