### ISSUE TITLE
[Question]: How can I chat with the single document?

### ISSUE THREAD

**Issue by fan1jun** [infiniflow/ragflow#1032]
### Describe your problem

Is there a way to chat with the single document?

**Comment by KevinHuSh** [comment]
Use 'One' as the parsing method.

**Comment by fan1jun** [comment]
> Use 'One' as the parsing method.



> Use 'One' as the parsing method.

Do you mean I build a knowledge base with just only one document?

**Comment by fan1jun** [comment]
Do you mean I build a knowledge base with just only one document?

**Comment by Seaver-Zhu** [comment]
> Do you mean I build a knowledge base with just only one document?

you can try it.
