### ISSUE TITLE
[Question]: build docker image from tag-0.7.0 source code cannot startup container

### ISSUE THREAD

**Issue by maxisvest** [infiniflow/ragflow#1035]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/20422618/e05f1e5b-7da9-4f44-8020-881db5163bb7)
The dependency 'umap' and 'volcengine' is missing.

**Comment by KevinHuSh** [comment]
pip install the last three line in requirements.txt.

**Comment by maxisvest** [comment]
> pip install the last three line in requirements.txt.
<img width="643" alt="image" src="https://github.com/infiniflow/ragflow/assets/20422618/10246a58-6bbd-43dc-80b9-3373ad3b1c6d">
I'm build a docker image from source code, and there is no chance that I can use pip install cammand.

**Comment by maxisvest** [comment]
> pip install the last three line in requirements.txt.

Today I build it agian, It works. weird...
