### ISSUE TITLE
[Question]: ERROR: Account abnormal. Please ensure it's on good standing. 

### ISSUE THREAD

**Issue by wzikang** [infiniflow/ragflow#1040]
### Describe your problem

In tag 0.7.0 , when i ask a question,  ERROR: Account abnormal. Please ensure it's on good standing. 
but  when i callback to tag 0.6.0, all is well.

**Comment by KevinHuSh** [comment]
In version 0.7.0, the default embedding changed a bit, I'm afraid you need to redo parsing your documents using a valid embedding model.

**Comment by Romanzhang2024** [comment]
The LLM factory is ali:Tongyi-Qianwen, is there a problem with this LLM ? dont support?

**Comment by Romanzhang2024** [comment]
11/5000
Hope to solve the problem as soon as possible, thank you

**Comment by cauwulixuan** [comment]
meet the same issue. any solutions? cannot connect to 'dashscope.aliyuncs.com'

**Comment by raholly** [comment]
Tongyi-Qianwen, same issue.

**Comment by KevinHuSh** [comment]
Go to system setting > Model Providers > set a valid key of your selected models.
