### ISSUE TITLE
[Bug]: dotnet core 3.1 which Aspose depends on is incompatible with Ubuntu22.04

### ISSUE THREAD

**Issue by CamusGao** [infiniflow/ragflow#1045]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

83803a72ee16cfe72b190e7e4093a0aae5e811fe

### Other environment information

```Markdown
I am using docker image infiniflow/ragflow:v0.7.0
```

### Actual behavior

ragflow_server process aborted and restarted by entrypoint.sh, and `No usable version of libssl was found` was reported.

### Expected behavior

do not crash

### Steps to reproduce

```Markdown
create a knowledgebase and upload a pptx file.
```

**Comment by CamusGao** [comment]
A possible fix is download [[libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb)](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb) and install this deb by `dpkg -i` manually.
But this package comes from ubuntu20.04. I don't know if there are any other effects when installing this package in ubuntu 22.04.

**Comment by KevinHuSh** [comment]
Pull the dev version of docker images.
https://github.com/infiniflow/ragflow/blob/main/docs/references/faq.md#9-how-to-upgrade-ragflow

**Comment by CamusGao** [comment]
> Pull the dev version of docker images. https://github.com/infiniflow/ragflow/blob/main/docs/references/faq.md#9-how-to-upgrade-ragflow

Not all situations are suitable for simply executing docker run or docker compose up. Why can't you just give a solution direct to the problem, so that other people with the same problem in different environments can refer to it?

Is it true that except for the code, everything else is closed?

**Comment by KevinHuSh** [comment]
You need to install these package libcrypto.so.1.1  libssl.so.10 libgdiplus.
These packages are installed in the latest dev version of docker image.
