### ISSUE TITLE
[Bug]: Error code: 403 聊天页面出现

### ISSUE THREAD

**Issue by xxz196801** [infiniflow/ragflow#1048]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

主要

### Commit ID

8eb5c64c1e5811ef90140242ac120006

### Other environment information

```Markdown
intel i7 6700kcpu，32G ddr4内存，核显，系统Windows10，用的是wsl，ubuntu22.04
```

### Actual behavior

在聊天页面，发送问题后发聩的是Error code: 403 - {'error': {'message': 'Your account cosvfiqtnn0qt34mtkd0<ak-esfuisbuzk5111ekmhz1> is not active, current state: suspended, you may consider to check your account balance', 'type': 'exceeded_current_quota_error'}}，其他正常

### Expected behavior

希望能解决，能正常工作

### Steps to reproduce

```Markdown
打开聊天界面，输入问题，发送后就出现该问题
```

**Comment by KevinHuSh** [comment]
The LLM you use is out of quota. Go to settings to set up a valid API key.

**Comment by xxz196801** [comment]
我都已经重新申请了API，还是出现这种错误，昨天都还好好的，我的两台机子都出现这个问题，所有的API都是正常有效的

**Comment by xxz196801** [comment]
不管是通义千问、还是月之暗面、还是智谱清言都已申请新的API，都是有效的。不知道怎么还是出现这个问题

**Comment by xxz196801** [comment]
在知识库检索测试也都是好的，在聊天页面，我调用的模型API也都新换了，问题还是存在

**Comment by xxz196801** [comment]
![image](https://github.com/infiniflow/ragflow/assets/132810517/caea0b6f-ca39-49eb-a157-88ae1d2d599f)
几种模型我都测试过，还是显示错误，请明示，谢谢！

**Comment by xxz196801** [comment]
找到问题原因了，是由于知识库绑定了原来的模型没有更改造成的

**Comment by liuyuhang754** [comment]
Testing API access
