### ISSUE TITLE
[Feature Request]: Use multi stage dockerfile to build image.

### ISSUE THREAD

**Issue by CamusGao** [infiniflow/ragflow#1049]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
no
```

### Describe the feature you'd like

Use separated stage to install node_modules and build front end and copy the artifacts to final stage. This is can reduce size of the final image.

**Comment by yuzhichang** [comment]
Released in v0.12.0
