### ISSUE TITLE
[Bug]: could not parse txt file in demo

### ISSUE THREAD

**Issue by FreemanFeng** [infiniflow/ragflow#1060]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

b8eedbdd86ca966582645e429abb6f1488ee621c

### Actual behavior

[ERROR]Internal server error: Sorry! Cant get file paul_graham_essay.txt from minio. Could you delete this file and uploaded again.
[paul_graham_essay.txt](https://github.com/user-attachments/files/15572164/paul_graham_essay.txt)

### Steps to reproduce

```Markdown
upload the attached txt file in demo, try to parse it
```

**Comment by KevinHuSh** [comment]
I think you can delete it by youself. Press the trash button on the right.
