### ISSUE TITLE
[Question]: Problem with docker desktop

### ISSUE THREAD

**Issue by mehdimansouriut** [infiniflow/ragflow#1065]
### Describe your problem

Hello, When I try to lauch ragflow on docker desktop WSL 2 I have this error :  

request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddocker%22%3Atrue%7D%7D, check if the server supports the requested API version

Everything is up to date and I don't understand the error

Thanks :)

**Comment by KevinHuSh** [comment]
Is it macOS?
You could try to build it by [this](https://github.com/infiniflow/ragflow/blob/main/Dockerfile.arm)

**Comment by yuzhichang** [comment]
Close due to no response.
