### ISSUE TITLE
[Question]: Why choose the second best chunking result for stk during the fine_grained_tokenize

### ISSUE THREAD

**Issue by w8iknowu** [infiniflow/ragflow#1083]
### Describe your problem

For code in function **fine_grained_tokenize** of file <code>rag/nlp/rag_tokenizer.py</code> at line 340:
https://github.com/infiniflow/ragflow/blob/6399a4fde25e0fdc1e7512ae76f361ae68ce2bb9/rag/nlp/rag_tokenizer.py#L340

Here, why does <code>stk</code> take the second best chunking result instead of the best result as:
```python
stk = self.sortTks_(tkslist)[0][0]
```

**Comment by KevinHuSh** [comment]
You've caught the essence of this tokenizer.
The first one should be itself, I guess.
You could star this project to find it easily next time.

**Comment by w8iknowu** [comment]
Yep, the result is confirmed. The top result is indeed itself. Thanks for replying.
