### ISSUE TITLE
[Feature Request]: Support GLM-4

### ISSUE THREAD

**Issue by mobguang** [infiniflow/ragflow#1085]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

We hope ragflow support run GLM-4 LLM locally.

https://github.com/THUDM/GLM-4

**Comment by aopstudio** [comment]
If you can deploy GLM-4 locally by Xinference or any other backend which can offer OpenAI style's API, then you can integrate it into RAGFlow.
