### ISSUE TITLE
[Bug]: error with new version

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#1087]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

dbdae8e8

### Actual behavior

updated docker and code and now getting this error when starting:

ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 28, in <module>
ragflow-server  |     from api.db.services.file2document_service import File2DocumentService
ragflow-server  |   File "/ragflow/api/db/services/__init__.py", line 18, in <module>
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/api/ragflow_server.py", line 26, in <module>
ragflow-server  |     from .user_service import UserService
ragflow-server  |   File "/ragflow/api/db/services/user_service.py", line 22, in <module>
ragflow-server  |     from api.db.db_models import DB, UserTenant
ragflow-server  |   File "/ragflow/api/db/db_models.py", line 32, in <module>
ragflow-server  |     from api.apps import app
ragflow-server  |   File "/ragflow/api/apps/__init__.py", line 26, in <module>
ragflow-server  |     from api.settings import DATABASE, stat_logger, SECRET_KEY
ragflow-server  |   File "/ragflow/api/settings.py", line 35, in <module>
ragflow-server  |     from api.db.db_models import close_connection
ragflow-server  |   File "/ragflow/api/db/db_models.py", line 32, in <module>
ragflow-server  |     from rag.utils.es_conn import ELASTICSEARCH
ragflow-server  |   File "/ragflow/rag/utils/es_conn.py", line 460, in <module>
ragflow-server  |     from api.settings import DATABASE, stat_logger, SECRET_KEY
ragflow-server  |   File "/ragflow/api/settings.py", line 35, in <module>
ragflow-server  |     ELASTICSEARCH = ESConnection()
ragflow-server  |   File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
ragflow-server  |     from rag.utils.es_conn import ELASTICSEARCH
ragflow-server  |   File "/ragflow/rag/utils/es_conn.py", line 460, in <module>
ragflow-server  |     instances[key] = cls(*args, **kw)
ragflow-server  |   File "/ragflow/rag/utils/es_conn.py", line 24, in __init__
ragflow-server  |     raise Exception("Can't connect to ES cluster")
ragflow-server  | Exception: Can't connect to ES cluster
ragflow-server  |     ELASTICSEARCH = ESConnection()
ragflow-server  |   File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
ragflow-server  |     instances[key] = cls(*args, **kw)
ragflow-server  |   File "/ragflow/rag/utils/es_conn.py", line 24, in __init__
ragflow-server  |     raise Exception("Can't connect to ES cluster")
ragflow-server  | Exception: Can't connect to ES cluster

### Steps to reproduce

```Markdown
update pre-existing environment and run
```

**Comment by KevinHuSh** [comment]
Change RAGFLOW_VERSION to dev in docker/.env if you're using latest code.

**Comment by yuanpneg** [comment]
I’m facing the same issue, and it still hasn’t been resolved despite following your suggested settings.
