### ISSUE TITLE
[Question]: Change RAGFLOW_VERSION to dev in docker/.env if you're using latest code， Can't connect to ES cluster

### ISSUE THREAD

**Issue by yuanpneg** [infiniflow/ragflow#1094]
### Describe your problem

Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 28, in <module>
    from api.db.services.file2document_service import File2DocumentService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 32, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 35, in <module>
    from rag.utils.es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 460, in <module>
    ELASTICSEARCH = ESConnection()
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
  File "/ragflow/rag/utils/es_conn.py", line 24, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster

**Comment by Albedoww** [comment]
i have the same question too

**Comment by HaoGuo98** [comment]
i have the same question too

**Comment by wd-freehand** [comment]
修改es_conn.py ，加上鉴权     basic_auth=(settings.ES["username"], settings.ES["password"]) if "username" in settings.ES and "password" in settings.ES else None,

**Comment by Bachelorwangwei** [comment]
> 修改es_conn.py ，加上鉴权 basic_auth=(settings.ES["username"], settings.ES["password"]) if "username" in settings.ES and "password" in settings.ES else None,

你好，麻烦问下，这个ES basic_auth配置 在哪块修改，修改完怎样重启服务

**Comment by HaoGuo98** [comment]
i fix it by change /.env  ragflow-version from latest to dev.

**Comment by fire717** [comment]
> 修改es_conn.py ，加上鉴权 basic_auth=(settings.ES["username"], settings.ES["password"]) if "username" in settings.ES and "password" in settings.ES else None,

新版本自带就有这句。

我是跑dev没问题，但是解析很慢且报错index fail，然后想尝试固定版本，试了0.7.0和0.6.0都是Exception: Can't connect to ES cluster

**Comment by fire717** [comment]
> > 修改es_conn.py ，加上鉴权 basic_auth=(settings.ES["username"], settings.ES["password"]) if "username" in settings.ES and "password" in settings.ES else None,
> 
> 新版本自带就有这句。
> 
> 我是跑dev没问题，但是解析很慢且报错index fail，然后想尝试固定版本，试了0.7.0和0.6.0都是Exception: Can't connect to ES cluster

果然切换版本，也要切换相应代码，不是直接拉docker就行了，换了对于版本的代码就可以了。

**Comment by yangboz** [comment]
> > > 修改es_conn.py ，加上鉴权 basic_auth=(settings.ES["username"], settings.ES["password"]) if "username" in settings.ES and "password" in settings.ES else None,
> > 
> > 
> > 新版本自带就有这句。
> > 我是跑dev没问题，但是解析很慢且报错index fail，然后想尝试固定版本，试了0.7.0和0.6.0都是Exception: Can't connect to ES cluster
> 
> 果然切换版本，也要切换相应代码，不是直接拉docker就行了，换了对于版本的代码就可以了
我这是在内部测试服务器配置了0.7.0版本的一套代码，最后运行docker compose  服务后，改变本地ES的连接主机IP代码，才连接成功，
