### ISSUE TITLE
[Bug]: Build the code from source

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/ragflow#1096]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Actual behavior

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastembed 0.2.6 requires huggingface-hub<0.21,>=0.20, but you have huggingface-hub 0.23.3 which is incompatible.
fastembed 0.2.6 requires tokenizers<0.16.0,>=0.15.1, but you have tokenizers 0.19.1 which is incompatible.
```

### Expected behavior

No dependency error.

### Steps to reproduce

```Markdown
Use requirements.txt to install python package.
```

**Comment by http403** [comment]
This will be a non problem once #1052 is completed. I have a partial migration to Poetry and in the process to rewriting the deployment script to test it out.

**Comment by yuzhichang** [comment]
We've replaced pip with poetry. Poetry is much better on dependency management and download speed.
