### ISSUE TITLE
[Question]: can not add xinference

### ISSUE THREAD

**Issue by Renoshen** [infiniflow/ragflow#1103]
### Describe your problem

When I add model provider , web show me the error:
![image](https://github.com/infiniflow/ragflow/assets/4434566/82cb3f9b-14a4-47d2-972b-1b3dc187cb42)

**Comment by Simonqujian78** [comment]
hello, I encountered the  same bug. could you tell me  how to resolve it?

**Comment by Renoshen** [comment]
> hello, I encountered the same bug. could you tell me how to resolve it?

你提供一下截图看看？

**Comment by Simonqujian78** [comment]
![Image](https://github.com/user-attachments/assets/c3ff0b91-c9eb-4126-bb37-7c05e9f473b2)
