### ISSUE TITLE
[Question]: Can't see the 'Add file' button

### ISSUE THREAD

**Issue by Scoutink** [infiniflow/ragflow#1105]
I deployed the system, all seems fine, but I can't see the 'Add files' in my version, unlike yours (first image is from my server, the second one is your online demo)

In another note, when you delete a knowledgebase, that does not delete its directory.

![image](https://github.com/infiniflow/ragflow/assets/108686600/cccc125a-058d-439f-b1b7-776fc3a508f3)

![image](https://github.com/infiniflow/ragflow/assets/108686600/f5e79717-8873-47f4-9a68-ad763daf556b)

**Comment by JinHai-CN** [comment]
1. Check the running logs.
2. Yes, it's a BUG.

**Comment by Scoutink** [comment]
Thanks. I deployed on a better server and it worked fine. You can close this ticket if needed (I won't do so myself as you tagged it as a bug)
