### ISSUE TITLE
[Question]:  after i update version to 0.7.0 ，the chatbot stop  answering  in few line and do not reach the max token 

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#1121]
### Describe your problem

<img width="945" alt="image" src="https://github.com/infiniflow/ragflow/assets/42510628/576686e3-9bc6-4e49-9aa0-162104a89367">
after i update version to 0.7.0，when i ask question in kb，the answer is just part of search result and too short，others questions are fine.  Everything is fine in version 0.6.0.

**Comment by HaoGuo98** [comment]
the question only happen in QA， i think it might be a bug.

**Comment by KevinHuSh** [comment]
Please checkout the LLM you used and max_token in dialog setting. This is probably caused by capability of  LLM.

**Comment by HaoGuo98** [comment]
> Please checkout the LLM you used and max_token in dialog setting. This is probably caused by capability of LLM.

hi, please check issue1122, i think it is a bug. the setting is the same.

**Comment by HaoGuo98** [comment]
> Please checkout the LLM you used and max_token in dialog setting. This is probably caused by capability of LLM.

answer just too short when answer this question about url,  it stop in a wrong place. other questions are fine.

**Comment by laoLemon** [comment]
try to disable the maxtokens limit in the settings
![maxtoken](https://github.com/infiniflow/ragflow/assets/73423553/95e548a3-7aac-4231-8f6c-6fa116a33599)

**Comment by HaoGuo98** [comment]
> try to disable the maxtokens limit in the settings ![maxtoken](https://private-user-images.githubusercontent.com/73423553/338840321-95e548a3-7aac-4231-8f6c-6fa116a33599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzI2NTMsIm5iZiI6MTcxODE3MjM1MywicGF0aCI6Ii83MzQyMzU1My8zMzg4NDAzMjEtOTVlNTQ4YTMtN2FhYy00MjMxLThmNmMtNmZhMTE2YTMzNTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNWIyZmU0YmI4N2E2NTRmMDQ0OTBkYWQwZGI1ZjI5NGIxNmYxY2M5ZWY2YWIyYmUxYTMwNDQ5ZDJhNzZkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KnEWcrslsbtZVL42n3CTdBYtwvSDGd5nmPldVE1fTbk)

thx，it works, but in previous setting i set it to 512 and it obviously do not reach the limitation. and other question can output long sentence by previous setting.any idea?
