### ISSUE TITLE
[Bug]:  answer question which contains url stop in wrong place.

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#1122]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Other environment information

```Markdown
version：v0.7.0
form：Q&A
```

### Actual behavior

compare these two answers，the second  answer stop in the wrong place of url.
![Uploading image.png…]()

### Expected behavior

the answer should be same or similar to the whole search result.

### Steps to reproduce

```Markdown
like picture
```

**Comment by KevinHuSh** [comment]
Sorry, the image you attached is not right.

**Comment by yuzhichang** [comment]
Close due to no response.
