### ISSUE TITLE
[Question]: Permissions 

### ISSUE THREAD

**Issue by Scoutink** [infiniflow/ragflow#1134]
### Describe your problem

Is there a way to set accounts permissions? If I want to use the bot as a Q&A for example of people who want to know more about my work, I can't do this by giving them a login account because they will have access to the knowledgebase, api keys, etc... And they cant get to the assistant conversation without a login, and I tried the Team upgrade button incase that does the trick but it does not do anything (not sure if it is incomplete work or whether I am not noticing what it does.)

**Comment by Chunshan-Theta** [comment]
I got the answer from the other issue. the team workspace is currently not implemented (the Team upgrade button) . 
check it: [https://github.com/infiniflow/ragflow/issues/1146](https://github.com/infiniflow/ragflow/issues/1146)
