### ISSUE TITLE
[Bug]: [ERROR]Index failure!

### ISSUE THREAD

**Issue by fire717** [infiniflow/ragflow#1137]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main/v0.7.0

### Commit ID

83803a7

### Other environment information

```Markdown
3090tix2
Ubuntu18
```

### Actual behavior

OCR results is too long to use CV LLM.
Finished slicing files(1). Start to embedding the content.
Finished embedding(0.40)! Start to build index!
[ERROR]Index failure!

### Expected behavior

parse file successful.

### Steps to reproduce

```Markdown
download main branch code or v0.7.0 code.
cd docker
follow readme to launch.

then go to web ui, make a new database, then upload a file, click the parse buttom.
```

**Comment by fire717** [comment]
in my env it can be reproduced.
the file is not matter, I tested some diffierent files got same error.

here is the log:
```
[INFO] [2024-06-13 01:11:33,386] [_internal._log] [line:96]: 172.26.0.6 - - [13/Jun/2024 01:11:33] "GET /v1/document/list?kb_id=d6126470291e11ef9a600242ac1a0006&page=1&page_size=10 HTTP/1.1" 200 -
[INFO] [2024-06-13 01:11:34,253] [_internal._log] [line:96]: 172.26.0.6 - - [13/Jun/2024 01:11:34] "GET /v1/document/list?kb_id=7d91230a28aa11efa62a0242ac1a0006&page=1&page_size=10 HTTP/1.1" 200 -
[INFO] [2024-06-13 01:11:38,395] [_internal._log] [line:96]: 172.26.0.6 - - [13/Jun/2024 01:11:38] "GET /v1/document/list?kb_id=d6126470291e11ef9a600242ac1a0006&page=1&page_size=10 HTTP/1.1" 200 -
[INFO] [2024-06-13 01:11:39,201] [_internal._log] [line:96]: 172.26.0.6 - - [13/Jun/2024 01:11:39] "GET /v1/document/list?kb_id=7d91230a28aa11efa62a0242ac1a0006&page=1&page_size=10 HTTP/1.1" 200 -
[WARNING] [2024-06-13 01:11:41,965] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 61 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,966] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 0 of 3)
[WARNING] [2024-06-13 01:11:41,971] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 62 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,972] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 1 of 3)
[WARNING] [2024-06-13 01:11:41,978] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 63 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,978] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 2 of 3)
[WARNING] [2024-06-13 01:11:41,983] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 64 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,990] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 65 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,990] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 0 of 3)
[WARNING] [2024-06-13 01:11:41,995] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 66 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:41,995] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 1 of 3)
[WARNING] [2024-06-13 01:11:42,001] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 67 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:42,001] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 2 of 3)
[WARNING] [2024-06-13 01:11:42,007] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 68 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:42,013] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 69 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:42,013] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 0 of 3)
[WARNING] [2024-06-13 01:11:42,018] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 70 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:42,018] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 1 of 3)
[WARNING] [2024-06-13 01:11:42,023] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 71 times in a row, putting on 30 second timeout
[WARNING] [2024-06-13 01:11:42,023] [_transport.perform_request] [line:427]: Retrying request after non-successful status 503 (attempt 2 of 3)
[WARNING] [2024-06-13 01:11:42,028] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 72 times in a row, putting on 30 second timeout

```

**Comment by fire717** [comment]
And the embedding api I have tested can work correctly.

**Comment by fire717** [comment]
> Check out conf/service_conf.yml. Correct host and port in ES part. Make sure the ES is up and reachable.

Thx for your reply, here I got:
```
es:
  hosts: 'http://es01:9200'
```
How should I get the right setting?

**Comment by fire717** [comment]
And the docker info:
00eb8013cf16   docker.elastic.co/elasticsearch/elasticsearch:8.11.3         "/bin/tini -- /usr/l…"   15 hours ago   Up 15 hours (healthy)   9300/tcp, 0.0.0.0:1200->9200/tcp, :::1200->9200/tcp                                                                   ragflow-es-01

**Comment by fire717** [comment]
Finally, I work it out.

Just `docker-compose -f docker-compose-CN.yml down -v`
del all data.
Then `docker-compose -f docker-compose-CN.yml up -d` again.

maybe there just something wrong with old data or env.

**Comment by oneyet** [comment]
> Finally, I work it out.
> 
> Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> 
> maybe there just something wrong with old data or env.



> Finally, I work it out.
> 
> Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> 
> maybe there just something wrong with old data or env.



> Finally, I work it out.
> 
> Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> 
> maybe there just something wrong with old data or env.

I encountered the same problem, and I still couldn't build index after deleting data and restarting

**Comment by oneyet** [comment]
> Finally, I work it out.
> 
> Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> 
> maybe there just something wrong with old data or env.

I encountered the same problem, and I still couldn't build index after deleting data and starting again

**Comment by oneyet** [comment]
> > Finally, I work it out.
> > Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> > maybe there just something wrong with old data or env.
> 
> I encountered the same problem, and I still couldn't build index after deleting data and starting again
My problem is that the disk usage on the current node has exceeded the high watermark threshold (90%). So ES is not working properly.

**Comment by seetimee** [comment]
> > > Finally, I work it out.
> > > Just `docker-compose -f docker-compose-CN.yml down -v` del all data. Then `docker-compose -f docker-compose-CN.yml up -d` again.
> > > maybe there just something wrong with old data or env.
> > 
> > 
> > I encountered the same problem, and I still couldn't build index after deleting data and starting again
> > My problem is that the disk usage on the current node has exceeded the high watermark threshold (90%). So ES is not working properly.

that worked

**Comment by seetimee** [comment]
@KevinHuSh Can you ensure that the es disk usage bug for this issue is displayed in the Docker logs in the future?
