### ISSUE TITLE
[Bug]: api/completion endpoint returns 200 but body contains error

### ISSUE THREAD

**Issue by JamesAntisdel** [infiniflow/ragflow#1139]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

3b7b6240c3adb967c5fe9e98ed73c05cd60ecd46

### Actual behavior

API returns 200/OK with object:

data:{"retcode": 500, "retmsg": "'function' object is not subscriptable", "data": {"answer": "**ERROR**: 'function' object is not subscriptable", "reference": []}}

data:{"retcode": 0, "retmsg": "", "data": true}

### Steps to reproduce

```Markdown
POST object with "conversation_id" and "messages" to <base_url>/v1/api/completion

Receive 200/OK and error
```

**Comment by KevinHuSh** [comment]
Could you specify that errro. There's not any error message here.

**Comment by JamesAntisdel** [comment]
Screenshots attached. 
![completionerror_hoppscotch](https://github.com/infiniflow/ragflow/assets/65193532/b6c80d60-6fdd-4796-833d-5f840aebe2dd)
![completionerror](https://github.com/infiniflow/ragflow/assets/65193532/4c4ba087-b481-45d8-b11b-6bbb0c4d1472)

**Comment by KevinHuSh** [comment]
What is the version of the docker image and the code?
I suggest you to use dev version of image and pull the latest code.

**Comment by JamesAntisdel** [comment]
I have tried both latest and dev. They all have the same issue. All the other endpoints, including the ones that were not working before are functioning normally, i.e. list_chunks. It is just completion that shows this error.

Current env:
![Screenshot 2024-06-14 at 9 07 10 AM](https://github.com/infiniflow/ragflow/assets/65193532/795f8961-cb11-4048-9efa-d9bf3a09a90e)
![Screenshot 2024-06-14 at 9 08 07 AM](https://github.com/infiniflow/ragflow/assets/65193532/19162501-b5aa-41eb-b4b0-a2a019ef34d3)

**Comment by JamesAntisdel** [comment]
I have worked around this issue but the bug remains. The issue is with the 'stream' option which if set to True will cause the `retval 500`. For now I am able to get completion results by specifying `"stream": false`.
