### ISSUE TITLE
[Question]: "Get answer" API can't work

### ISSUE THREAD

**Issue by chickouo** [infiniflow/ragflow#1140]
### Describe your problem

I test the API of "Create conversation" and "Get answer" and "Get conversation history".
These APIs have been functioning normally for several weeks.
But about 4 hours ago I discovered that the "Get answer" API could not send the question correctly.

The image below shows "Create conversation" functioning properly and opening a new conversation:
![螢幕擷取畫面 2024-06-13 001224](https://github.com/infiniflow/ragflow/assets/38011096/a0634628-9d83-449e-bbcc-cb825f3e8a49)

Then I use "Get answer" to send a question: 
![螢幕擷取畫面 2024-06-13 001351](https://github.com/infiniflow/ragflow/assets/38011096/25e5e785-78b5-465f-b5cb-4155393c566a)

Finally, I got the history record from "", but I didn't see the question just asked in the history record as expected.
![螢幕擷取畫面 2024-06-13 001439](https://github.com/infiniflow/ragflow/assets/38011096/1db7efe1-ae0e-4c6e-9860-22fbddfdcb43)

I'm sure the API key and id are set correctly.
And the python program I wrote worked normally within a few weeks,
I suddenly encountered this problem tonight. I am not sure if there is a problem with the "Get answer" API.
I also tried opening a new account to test whether it was an API free quota issue.
But the result is still the same,
Hope someone can answer my doubts

**Comment by KevinHuSh** [comment]
I guess that it's caused by streaming chat. In the request 'completion', it use SSE in default. So, add {"stream": false} in the request.
