### ISSUE TITLE
[Question]: Team workspace

### ISSUE THREAD

**Issue by YangXuepei** [infiniflow/ragflow#1146]
Hello, I have noticed that the functionality of the team workspace is currently not implemented. There is a button, but it does not respond when clicked. Will your team consider implementing this feature in the future?

**Comment by KevinHuSh** [comment]
Of course, but this would not be open sourced.

**Comment by wangtao19871205** [comment]
如何向团队添加其他人，我想把知识库共享给其他团队成员，目前是不是没有这个功能

**Comment by YangXuepei** [comment]
> 如何向团队添加其他人，我想把知识库共享给其他团队成员，目前是不是没有这个功能

Look like so.

**Comment by CamusGao** [comment]
> > 如何向团队添加其他人，我想把知识库共享给其他团队成员，目前是不是没有这个功能
> 
> Look like so.

@wangtao19871205 
> > 如何向团队添加其他人，我想把知识库共享给其他团队成员，目前是不是没有这个功能
> 
> Look like so.

set your kdb permission to team and
```sql
insert into user_tenant (id,create_time,create_date,update_time,update_date,user_id,tenant_id,`role`,invited_by,status)
values (replace(uuid(),"-",""),unix_timestamp() * 1000,now(),unix_timestamp() * 1000,now(),'your_team_member_id','your_tenant_id','owner','your_id','1')
``` 
then your team member could see your kdb. but doesn't work for dialog

**Comment by ZKeeer** [comment]
> Of course, but this would not be open sourced.

@KevinHuSh When do you expect to be ready? I really want to be your first paying customer.
