### ISSUE TITLE
[Question]: About counting pages for docx paragraph parsing in RAGFlowDocxParser.py

### ISSUE THREAD

**Issue by w8iknowu** [infiniflow/ragflow#1147]
### Describe your problem

# Description
Howdy, for the docx paragraph parsing method in RAGFlowDocxParser.py:
https://github.com/infiniflow/ragflow/blob/64c83f300a1cb6990c230c99b440d5342fd93fcd/deepdoc/parser/docx_parser.py#L113-L131

The parsed page depends on counting the break mark of **run** in a **paragraph**. But in this way, I noticed that if there is a long paragraph that goes across multiple pages, even exceeding the limit of **to_page**, it may still be appended to the **secs**.

# Question

So based on the description above, I wonder if this is how the docx parser works, regardless of the length of a single paragraph?

If not, would it be more suitable to use a temp array to first save **run** within the range of paragraph and concatenate them later as:

```python
    from docx.text.run import Run

    @staticmethod
    def has_page_break(run: Run) -> bool:
        """check if there is a soft/hard page break in run"""

        if 'lastRenderedPageBreak' in run._element.xml:
            return True
        elif 'w:br' in run._element.xml and 'type="page"' in run._element.xml:
            return True
        else:
            return False

    def __call__(self, fnm, from_page=0, to_page=100000):
        self.doc = Document(fnm) if isinstance(
            fnm, str) else Document(BytesIO(fnm))
        pn = 0 # parsed page
        secs = [] # parsed contents
        for p in self.doc.paragraphs:
            # Make range between [from, to), 
            # close on the left and open on the right, just like the range() function.
            if pn >= to_page:
                break

            runs_within_single_paragraph = [] # save runs within the range of pages
            for run in p.runs:
                if pn >= to_page: # here range be changed as well
                    break

                """
                A run at the end of a page with a page break mark may:
                    - 1. Extend across two pages
                    - 2. Begin from the second page
                Based on the two phenomena above,  if the current run contains a page break,
                accumulate it first, treating the run with a break as the start of a new page.
                """
                if RAGFlowDocxParser.has_page_break(run._element.xml):
                    pn += 1

                if from_page <= pn < to_page and run.text.strip(): # check run's text instead of paragraph's
                    runs_within_single_paragraph.append(run.text) # append run.text first

            secs.append(("".join(runs_within_single_paragraph), p.style.name)) # then concat run.text as part of the paragraph

        tbls = [self.__extract_table_content(tb) for tb in self.doc.tables]
        return secs, tbls
```

**Comment by KevinHuSh** [comment]
I think it is a good implementation. Could you file a pull request about that?

**Comment by w8iknowu** [comment]
Hi, upon reviewing my code, I realized that there is room for improvement. Therefore, I have made two main changes to my original comment:
1. Changed the break condition from <code>pn > to_page</code> to <code>pn >= to_page</code>. This adjustment ensures that the page range is <code>[from, to)</code>, open on the left and closed on the right, aligning with the style of the range() function.
2. Considered the run with a break mark as the beginning of a new page.

Since these two changes may differ from my original one, please recheck this new version to see if it still serves the purpose
