### ISSUE TITLE
[Question]: How to parse the rotated picture in PDF

### ISSUE THREAD

**Issue by wang-sheng-pu1002** [infiniflow/ragflow#1148]
### Describe your problem

在知识库解析pdf时,我尝试了好几种解析方法,关于pdf内存在翻转90度的图片时,解析的文本错乱,请问怎么解决?
![image](https://github.com/infiniflow/ragflow/assets/51901366/527a0033-8db4-4d02-84aa-399515335dd7)

**Comment by KevinHuSh** [comment]
There's nothing better than rotate it back mannually right now.

**Comment by wang-sheng-pu1002** [comment]
The images in the PDF cannot be manually selected, right? Can the program automatically rotate during processing?
