### ISSUE TITLE
[Bug]: ERROR: 'float' object is not iterable

### ISSUE THREAD

**Issue by shichunshan** [infiniflow/ragflow#1150]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ragflow-0.7.0

### Other environment information

```Markdown
Hardware parameters:48C128G
OS type：20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Actual behavior

![微信图片_20240614102124](https://github.com/infiniflow/ragflow/assets/3012746/5b9ca855-1249-477e-a0ba-231c6930e7be)

### Steps to reproduce

```Markdown
answer the question
```

**Comment by KevinHuSh** [comment]
What about the log?

**Comment by yuzhichang** [comment]
No response. Close.
