### ISSUE TITLE
[Bug]: Bulk files parsing stall after several hours without any error info

### ISSUE THREAD

**Issue by yelluo** [infiniflow/ragflow#1154]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

83803a7

### Other environment information

```Markdown
Ubuntu20
32G RAM
MEM_LIMIT = 12073741824
Server in LAN withou internet access, have downloaded openai cache file and set os.environ["TIKTOKEN_CACHE_DIR"].
Start Ragflow server with docker compose -f docker-compose-CN.yml up -d.
Using chat, embedding and vision model from other LAN server.
```

### Actual behavior

This problem is reproducable. After start bulk files parsing, several files parsing will success and remaining task will stall at about 50% (start to do RAPTOR) after several hours without any error info in all logs. I can see python3 rag/svr/task_executor.py process (CPU 0~0.3%) via top command. All RAGFlow components are running properly via docker ps. I can see following warning info after docker logs -f ragflow-server:
/ragflow/rag/utils/es_conn.py:129: ElasticsearchWarning: A bulk action object contained multiple keys. Additional keys are currently ignored but will be rejected in a future version.
  r = self.es.bulk(index=(self.idxnm if not idx_nm else

When cancel and restart parsing the stalled file, the file parsing will success.

### Expected behavior

All bulk files parsing will success. Show error info in log when task stalled.

### Steps to reproduce

```Markdown
After start bulk files parsing and then wait several hours.
```

**Comment by KevinHuSh** [comment]
RAPTOR uses llm to do summary. So, I think it's probably caused by the serving capability of LLM server in your local LAN.

**Comment by yelluo** [comment]
> RAPTOR uses llm to do summary. So, I think it's probably caused by the serving capability of LLM server in your local LAN.

I am unable to locate any relevant error or warning logs through docker logs -f ragflow-*. I suggest enhancing the logging system to provide more detailed information when the task status is abnormal.

**Comment by yelluo** [comment]
> RAPTOR uses llm to do summary. So, I think it's probably caused by the serving capability of LLM server in your local LAN.

After extensive debugging, I have finally discovered that the stalling of the file parsing task prior to raptor was due to the expiration of REDIS_CONN.queue_product.

/ragflow/rag/settings.py
SVR_QUEUE_RETENTION = 60*60

To address this issue, I recommend adjusting the retention period for the server queue in /ragflow/rag/settings.py. Specifically, we should increase the SVR_QUEUE_RETENTION value to ensure that items in the queue do not expire prematurely.

**Comment by leecj** [comment]
I think this bug still exists, WS=1 is expected to get 20+ files stuck, if WS>1 will speed up the process, worst of all there is no error message

**Comment by yelluo** [comment]
> I think this bug still exists, WS=1 is expected to get 20+ files stuck, if WS>1 will speed up the process, worst of all there is no error message

Have you tried increasing the SVR_QUEUE_RETENTION value in /ragflow/rag/settings.py? It worked for me.

**Comment by leecj** [comment]
> > I think this bug still exists, WS=1 is expected to get 20+ files stuck, if WS>1 will speed up the process, worst of all there is no error message
> 
> Have you tried increasing the SVR_QUEUE_RETENTION value in /ragflow/rag/settings.py? It worked for me.

Thank you, it has solved the need for mass parsing.
