### ISSUE TITLE
[Bug]: failed to Create new Chunk in database

### ISSUE THREAD

**Issue by tonightmare** [infiniflow/ragflow#1159]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.7

### Commit ID

tonightmare

### Other environment information

```Markdown
Linux Ubuntu 22.04 with docker deplyment
```

### Actual behavior

when I tried to Create new Chunk in database, below error message shows that embedding model is not authorized...

please hlep check what cause this problem ?

![image](https://github.com/infiniflow/ragflow/assets/61832070/28511609-85bb-47cd-bf26-d052c3b8d40f)

### Expected behavior

I just need to manually add chunk information to improve my RAG search result.

### Steps to reproduce

```Markdown
I tried 3 different embedding module, all meet such problem.
```

**Comment by tonightmare** [comment]
also when I try to add keyword to existing chunk, it also shows the same error message.

**Comment by KevinHuSh** [comment]
0.7.0 has that problem.
I suggest you  to  use dev version.

**Comment by chinamerp** [comment]
the bug can be reproduced using dev version, because the current embedding module is not user configured at knowledgebase. It use the global embedding module, i fixed the bug at the upcate scene： https://github.com/infiniflow/ragflow/pull/1163
