### ISSUE TITLE
[Bug]: Query contains too many nested clauses; maxClauseCount is set to 1024

### ISSUE THREAD

**Issue by Logistic98** [infiniflow/ragflow#1161]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

4447039a4ce1ea6b14e3ac12c410398435f6388c

### Other environment information

```Markdown
实验环境：CentOS7，1024GB内存，412TB存储，NVIDIA A800显卡（80GB显存）、CUDA12.2环境
```

### Actual behavior

我用ollama接入deepseek-v2:236b大模型服务，最大Token数的限制我把它关了，偶发这个问题，而接入gpt4o就没遇到这种情况。ERROR: ApiError(500, 'search_phase_execution_exception', 'Query contains too many nested clauses; maxClauseCount is set to 1024')，这个看起来是es的问题，但改elasticsearch.yml也不生效。
<img width="883" alt="image" src="https://github.com/infiniflow/ragflow/assets/43904389/60cd0f10-2c70-4630-ac07-00b0abb626b8">

### Steps to reproduce

```Markdown
用ollama接入deepseek-v2:236b大模型服务，测试知识库问答，偶发该问题。
目前仅在接入deepseek-v2:236b的时候遇到此偶发问题，尝试过的其他模型都正常。
```

**Comment by JinHai-CN** [comment]
We tend to create a global community, so we encourage using English to ask question.

For your issue, can you try to print out the query text ?

**Comment by KevinHuSh** [comment]
I think it's irrelevant with LLM.
You'd better have a look at ES log in docker/ragflow-logs/api.

**Comment by Logistic98** [comment]
[错误日志.txt](https://github.com/user-attachments/files/15860582/default.txt)
这个是错误日志文件

**Comment by Logistic98** [comment]
的确不只是 deepseek-v2:236b 模型有这个问题，我在我们自己微调的模型也复现了这个情况，那应该还是ES的问题
