### ISSUE TITLE
[Question]:Network anomaly

### ISSUE THREAD

**Issue by ikun-lsw** [infiniflow/ragflow#1162]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/49890835/efc9b200-8bd7-487d-b4ea-a310d72c8e7c)

**Comment by JinHai-CN** [comment]
Demo or local deployment?

**Comment by KevinHuSh** [comment]
Online demo has the limitation of 10Mb.
If it's local, the default size of nginx is 128Mb.

**Comment by ChloeZhou1997** [comment]
> Online demo has the limitation of 10Mb. If it's local, the default size of nginx is 128Mb.

I am trying to local deployment, and then ran into the same problem, I can't fix this problem by using

docker compose down -v(delete all data)
docker compose up

either

**Comment by yuzhichang** [comment]
Please try v0.14.0

**Comment by GaoR311** [comment]
I have the same bug,however,my problem is ragflow can't login or logup

**Comment by GaoR311** [comment]
I use local docker deployment
