### ISSUE TITLE
[Bug]: Delete Assistant BUG

### ISSUE THREAD

**Issue by yungongzi** [infiniflow/ragflow#1166]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c68767a

### Other environment information

```Markdown
ragflow for demo or latest version
```

### Actual behavior

When deleting an **assistant**(**dialog**) with that you have chatted,
the previous chat information still exists, and you can have a new chat conversation

https://github.com/infiniflow/ragflow/assets/19431702/437931c1-47df-4a48-b188-5aaa40351418

### Steps to reproduce

```Markdown
- Create an Assistant
- New conversation
- Chat
- Delete Assistant
- Here we are
```

**Comment by KevinHuSh** [comment]
I can see nothing by this MP4. What about refreshing the page? Is it still there?

**Comment by cike8899** [comment]
Fixed
