### ISSUE TITLE
docker run failed, Can't connect to ES cluster, KIBANA_PORT not up

### ISSUE THREAD

**Issue by glider2019cn** [infiniflow/ragflow#1169]
### Discussed in https://github.com/infiniflow/ragflow/discussions/1167

<div type='discussions-op-text'>

<sup>Originally posted by **glider2019cn** June 15, 2024</sup>
Hi All,

At beginning, I have changed RAGFLOW_VERSION=v0.7.0, then run docker compose -f docker-compose-CN.yml up -d , 
it is not working until I run sudo, then start working.
no error, 
 sudo docker compose -f docker-compose-CN.yml up -d
[sudo] password for tac:
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string.
[+] Running 67/41
 ✔ mysql 11 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                 11.2s
 ✔ minio 7 layers [⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                      23.0s
 ✔ es01 10 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                   56.0s
 ✔ ragflow 26 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                              1014.9s
 ✔ redis 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                     15.1s

[+] Running 10/10
 ✔ Network docker_ragflow      Created                                                                                                                                                                   0.1s
 ✔ Volume "docker_minio_data"  Created                                                                                                                                                                   0.0s
 ✔ Volume "docker_redis_data"  Created                                                                                                                                                                   0.0s
 ✔ Volume "docker_esdata01"    Created                                                                                                                                                                   0.0s
 ✔ Volume "docker_mysql_data"  Created                                                                                                                                                                   0.0s
 ✔ Container ragflow-mysql     Healthy                                                                                                                                                                   2.2s
 ✔ Container ragflow-redis     Started                                                                                                                                                                   2.2s
 ✔ Container ragflow-minio     Started                                                                                                                                                                   2.2s
 ✔ Container ragflow-es-01     Healthy                                                                                                                                                                   2.2s
 ✔ Container ragflow-server    Started   

but sudo docker logs -f ragflow-server not show success but show :
udo docker logs -f ragflow-server
[sudo] password for tac:
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 28, in <module>
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.db.services.file2document_service import File2DocumentService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 32, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 26, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 35, in <module>
    from rag.utils.es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 460, in <module>
    ELASTICSEARCH = ESConnection()
    from api.db.db_models import close_connection
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
  File "/ragflow/api/db/db_models.py", line 32, in <module>
    instances[key] = cls(*args, **kw)
  File "/ragflow/rag/utils/es_conn.py", line 24, in __init__
    raise Exception("Can't connect to ES cluster")

Is there any wrong from my operation? Thanks!

on the port :1200, looks Elastic search was up
{
name: "es01",
cluster_name: "docker-cluster",
cluster_uuid: "AApBy9PCQSKf_t_9eAP75A",
version: {
number: "8.11.3",
build_flavor: "default",
build_type: "docker",
build_hash: "64cf052f3b56b1fd4449f5454cb88aca7e739d9a",
build_date: "2023-12-08T11:33:53.634979452Z",
build_snapshot: false,
lucene_version: "9.8.0",
minimum_wire_compatibility_version: "7.17.0",
minimum_index_compatibility_version: "7.0.0"
},
tagline: "You Know, for Search"
}

KIBANA_PORT not up, all other ports were up

Can access webpage, but register failed.</div>

**Comment by KevinHuSh** [comment]
If you're using 0.7.0 image, you should use code of 0.7.0 version too.
My suggestion is to use dev version of image and apply with the latest code.

**Comment by glider2019cn** [comment]
Hi Kevin,
Thanks a lot!
I have change docker env to use dev, it is working now.
When I upload pdf file use manual, looks some line was missed in the chunk preview, any suggestion? Thanks!
Is there any wechat group support? Thanks!
Best regards,
Yi DONG
    On Monday 17 June 2024 at 10:31:38 am AEST, KevinHuSh ***@***.***> wrote:  
 
 


If you're using 0.7.0 image, you should use code of 0.7.0 version too.
My suggestion is to use dev version of image and apply with the latest code.
