### ISSUE TITLE
[Question]: docker compose failed!

### ISSUE THREAD

**Issue by water-2022** [infiniflow/ragflow#1170]
### Describe your problem

(ragflow) [root@master docker]# docker compose -f docker-compose-CN.yml up -d
[+] Running 9/11
 ⠼ es01 [⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿] Pulling                                                                                                                                                                           9110.5s 
   ✔ 9e61d8b90935 Pull complete                                                                                                                                                                          83.5s 
   ✔ b72403a59eb9 Pull complete                                                                                                                                                                          85.0s 
   ✔ 9fe4457bccf6 Pull complete                                                                                                                                                                          85.0s 
   ✔ 89732bc75041 Pull complete                                                                                                                                                                          85.1s 
   ⠦ 7d1b8a7d0cf6 Downloading                                                                                                                                                                          9091.6s 
   ✔ 5f0c732baa5d Download complete                                                                                                                                                                      57.7s 
   ✔ df9f9c79894f Download complete                                                                                                                                                                      65.2s 
   ✔ 4cfe26a355c8 Download complete                                                                                                                                                                      73.2s 
   ✔ 4d9c5e900237 Download complete                                                                                                                                                                      81.7s 
   ✔ bc9c1e3bbcf8 Download complete                                                                                                                                                                      87.9s 
received unexpected HTTP status: 504 Gateway Time-out

**Comment by JinHai-CN** [comment]
Check your network environment.

**Comment by adzhua** [comment]
Encountered the same issue.
