### ISSUE TITLE
[Question]: Layout Detection is not happening when running in Local

### ISSUE THREAD

**Issue by AJAYSINGH1512** [infiniflow/ragflow#1171]
### Describe your problem

Hi Team,
I tried both versions your demo.ragflow and tried running at local as well. by trying with exact same embeddings same chunking method and each and every other settings were same. the result i got was different so the only change i saw was that on demo.ragflow when i activate layout detection it was working fine but in my local whether i activate layout detection or not it was not detecting the layout. can you help me identifying what might be the issue?

**Comment by AJAYSINGH1512** [comment]
[WARNING] [2024-06-16 15:18:59,287] [pdf_parser.cropout] [line:758]: Missing layout match: 3,table caption-1
[WARNING] [2024-06-16 15:18:59,297] [pdf_parser.cropout] [line:758]: Missing layout match: 2,figure caption-0
[WARNING] [2024-06-16 15:18:59,318] [pdf_parser.cropout] [line:758]: Missing layout match: 9,figure caption-1
getting this dont know if this is impacting the layout detection while in demo same document is parsed correctly

**Comment by JinHai-CN** [comment]
Models used in demo are different from and better than opensouce models.

**Comment by KevinHuSh** [comment]
If you want to change the configuration of parsing after uploading, you need to change it file by file, do you?

**Comment by AJAYSINGH1512** [comment]
@KevinHuSh currently it seems that way only

**Comment by AJAYSINGH1512** [comment]
@JinHai-CN are they trained on the same base model or they are completely different models?

**Comment by KevinHuSh** [comment]
Same model but different data.
