### ISSUE TITLE
[Feature Request]: Recognize table in markdown file.

### ISSUE THREAD

**Issue by zhwzhw110** [infiniflow/ragflow#1176]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

希望可以对markdown内容解析，识别表格布局，而不是转化为文本

**Comment by zhwzhw110** [comment]
markdown解析，表格识别布局无法识别，内容直接被转化成文本了

**Comment by JinHai-CN** [comment]
Propose to directly transfer the markdown table into format used by RAGFlow,without using OCR in this situation.

**Comment by KevinHuSh** [comment]
Implemented.
