### ISSUE TITLE
[Bug]: Do paper and law and native layout use the same model for parsing? I noticed that their MD5 values are the same.

### ISSUE THREAD

**Issue by papandadj** [infiniflow/ragflow#1179]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

<img width="590" alt="image" src="https://github.com/infiniflow/ragflow/assets/25424898/2ffdce73-c895-4294-9201-2c81044f0239">

### Steps to reproduce

```Markdown
no
```

**Comment by KevinHuSh** [comment]
Yes for the open source version.

**Comment by papandadj** [comment]
do you have a commercial version of this project available for use?

**Comment by ShirazC** [comment]
following this for commercial version as well.

**Comment by KevinHuSh** [comment]
> do you have a commercial version of this project available for use?

For commercial, you could refer to [this](https://github.com/infiniflow/ragflow/blob/main/README_zh.md#-%E5%8A%A0%E5%85%A5%E7%A4%BE%E5%8C%BA)

**Comment by KevinHuSh** [comment]
> following this for commercial version as well.

You could star this project to follow, we will open source more accurate models in the near future.
