### ISSUE TITLE
[Bug]: the error.log database.log ... are not fellow the formater: "[%(levelname)s] [%(asctime)s] [%(module)s.%(funcName)s] [line:%(lineno)d]: %(message)s"

### ISSUE THREAD

**Issue by chinamerp** [infiniflow/ragflow#1182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1eb4caf02a9fdb1f3c5a7e8f304163d8823bfa5c

### Actual behavior

LookupError: Model(text-embedding-v2) not authorized

### Expected behavior

[ERROR] [2024-06-11 09:09:13,408] [xxx.xxx] [line:xxx]: LookupError: Model(text-embedding-v2) not authorized

### Steps to reproduce

```Markdown
see log files of logs/api
```

**Comment by KevinHuSh** [comment]
text-embedding-v2 is autherized by [Aliyun](https://dashscope.aliyun.com/). Set API key in settings >> model providers.
Or, use embedding model from BAAI.

**Comment by chinamerp** [comment]
Actual behavior
LookupError: Model(text-embedding-v2) not authorized

Expected behavior
[ERROR] [2024-06-11 09:09:13,408] [xxx.xxx] [line:xxx]: LookupError: Model(text-embedding-v2) not authorized

**Comment by chinamerp** [comment]
i do not care the exception
