### ISSUE TITLE
[Bug]:  the current embedding module is not user configured at knowledgebase when when update/create new chunk.

### ISSUE THREAD

**Issue by chinamerp** [infiniflow/ragflow#1183]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1eb4caf02a9fdb1f3c5a7e8f304163d8823bfa5c

### Actual behavior

 It use the global embedding module

### Expected behavior

using user configured at knowledgebase

### Steps to reproduce

```Markdown
create new chunk or update a chunk
```

**Comment by KevinHuSh** [comment]
Which version of image you used? I remembered that it's fixed in the dev version of docker image.

**Comment by chinamerp** [comment]
see the code: it use global setting, not user configured at kb
       embd_mdl = TenantLLMService.model_instance(
            tenant_id, LLMType.EMBEDDING.value)

**Comment by KevinHuSh** [comment]
tenant_id is used for fetching the user configured model settings.

**Comment by chinamerp** [comment]
那知识库里配置的嵌入模型的作用是什么呢？查询和创建不使用同一个嵌入模型？
