### ISSUE TITLE
[Question]: The log shows No chunk! Done!

### ISSUE THREAD

**Issue by ie-hn** [infiniflow/ragflow#1184]
### Describe your problem

When running file parsing, the log shows No chunk! Done!
Previous versions that support streaming responses parse files properly, but the latest versions don't parse files properly.
![企业微信截图_17186039241322](https://github.com/infiniflow/ragflow/assets/96454090/352cfb1f-645f-42b0-b70f-3a6f8ed293a7)
![企业微信截图_17186037927162](https://github.com/infiniflow/ragflow/assets/96454090/4d280a08-709c-42c1-aff1-76f4a0bfb4e4)

**Comment by KevinHuSh** [comment]
Could you attach the file?

**Comment by ie-hn** [comment]
Sure, it's this pdf
[123.pdf](https://github.com/user-attachments/files/15879013/123.pdf)

**Comment by KevinHuSh** [comment]
It is okay on the demo. I guess the open sourced layout recognition model is not good enough.

**Comment by ie-hn** [comment]
我用的嵌入模型是text-embedding-v2。在执行解析操作时会判断es库中是否有键，没有的话会根据当前用户创建一个，但是新版本的无法成功创建，旧版本的却可以
