### ISSUE TITLE
[Question]: redis problem--unable to do the document parsing while launching service from source

### ISSUE THREAD

**Issue by ja3592** [infiniflow/ragflow#1187]
### Describe your problem

I follow the description in the md file and it can run normally until my try to parse the document, the process stucks in the website and the terminal shows like the followings:
![问题](https://github.com/infiniflow/ragflow/assets/42410824/6bf6f1a5-1c5f-4d3c-a916-ad2bccb96e9e)
![问题2](https://github.com/infiniflow/ragflow/assets/42410824/3559e191-05fb-4b6b-94b9-2d4486fdbb11)

It turns out that the redis still has some problems to connect the server:

![问题6](https://github.com/infiniflow/ragflow/assets/42410824/3026531e-a933-4d3a-89ac-2eba3d061d2f)

BUT, the redis run normally in docker:

![问题3](https://github.com/infiniflow/ragflow/assets/42410824/7dd7cc7b-6309-406d-a06e-b0fe86b952c7)
![问题4](https://github.com/infiniflow/ragflow/assets/42410824/1e8e3fec-b14b-4fc6-bcf8-bd62f1dd92b3)
![问题5](https://github.com/infiniflow/ragflow/assets/42410824/782a5f8f-5226-456d-b260-10c0f460bdb0)

Please give me some advice, thank you!

**Comment by ja3592** [comment]
the service_conf.yaml file is modified as:
![问题7](https://github.com/infiniflow/ragflow/assets/42410824/d3c8daaf-c971-40f1-ad40-d7b23b61dcbd)

**Comment by yangboz** [comment]
> the service_conf.yaml file is modified as:
> ![问题7](https://private-user-images.githubusercontent.com/42410824/340217535-d3c8daaf-c971-40f1-ad40-d7b23b61dcbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjQxNDAsIm5iZiI6MTcxODYyMzg0MCwicGF0aCI6Ii80MjQxMDgyNC8zNDAyMTc1MzUtZDNjOGRhYWYtYzk3MS00MGYxLWFkNDAtZDdiMjNiNjFkY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNWZjMDI4ZGJiOTc3YmM1NjhjODA0NWRkMTFkYmQ4ODY1MWZlMTE2N2U4M2I3NDkwOTc0YWJkMDNmZmYzNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKrN5QUsYEPec0xy6aUiYg9PY4RtLNgQWBjZSodTuxI)

记得ES默认端口是9200，应该修改yml中的1200位9200

**Comment by KevinHuSh** [comment]
Do you lauch ragflow by using docker? 
If it is, all the host need to be corrected.
If it is not, I guess the IP might be wrong. Please telnet 127.0.0.1 6379 on the machine you deploy RAGFlow.

**Comment by ja3592** [comment]
> Do you lauch ragflow by using docker? If it is, all the host need to be corrected. If it is not, I guess the IP might be wrong. Please telnet 127.0.0.1 6379 on the machine you deploy RAGFlow.

I launch ragflow from source, I found the reason is that the nginx was not started normally. I stoped the nginx casually before bashing the entrypoint.sh file，now it runs well.
Thank you sir!

**Comment by yangboz** [comment]
> Do you lauch ragflow by using docker? If it is, all the host need to be corrected. If it is not, I guess the IP might be wrong. Please telnet 127.0.0.1 6379 on the machine you deploy RAGFlow.

or ```redis-cli -h 192.168.0.88 -p 6379 ping
```
got 
PONG response
