### ISSUE TITLE
https://github.com/infiniflow/ragflow/blob/main/docs/ollama.md

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1191]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
still 404 ?
```

### Describe the feature you'd like

fully filled document to apply the ollama integration feature.

### Describe implementation you've considered

we can follow the document to verify the feature implementation .

### Documentation, adoption, use case

```Markdown
https://github.com/infiniflow/ragflow aliked if could be, that will be greatly  appreciated.
```

### Additional information

we would like to contribute the document on ollama  parts.

**Comment by KevinHuSh** [comment]
Refer to [this](https://github.com/infiniflow/ragflow/blob/main/docs/guides/deploy_local_llm.md)

**Comment by writinwaters** [comment]
Hey @yangboz, could you let us know where you find this broken link? We checked the main branch, but couldn't find a broken link.

**Comment by yangboz** [comment]
> Hey @yangboz, could you let us know where you find this broken link? We checked the main branch, but couldn't find a broken link.

couple days ago , it stills 404.

**Comment by yangboz** [comment]
弄完I found it here[ https://ragflow.io/docs/dev/deploy_local_llm]( https://ragflow.io/docs/dev/deploy_local_llm)
