### ISSUE TITLE
Port could not be cast to integer value as ' 11434'

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1192]
### Describe your problem

try to have a try  ollama model integration, but don't known how, maybe it needs more document. related to  #

can't wait to use ollama in local.

**Comment by KevinHuSh** [comment]
RAGFlow has already supported ollama. Configure it in settings >> model providers

**Comment by yangboz** [comment]
> RAGFlow has already supported ollama. Configure it in settings >> model providers
please give a live example picture better than hundreds of words.

**Comment by yangboz** [comment]
in mac , after running ollama, we checked it with ```curl localhost:11434``` it returns "ollama is running".

**Comment by KevinHuSh** [comment]
I don't think localhost is the right IP since it is not reachable in docker container. So, try to use the real machine IP.

**Comment by yangboz** [comment]
> I don't think localhost is the right IP since it is not reachable in docker container. So, try to use the real machine IP.

I don't think so , becuz I installed the ollama with dmg, also curled "curl localhost:11434" got "ollama is  running" response,  if localhost not working, how to integrate it in rag flow model configure window ? or only inference  works?

**Comment by yangboz** [comment]
> I don't think localhost is the right IP since it is not reachable in docker container. So, try to use the real machine IP.

after ```export OLLAMA_HOST=0.0.0.0:11434``` , ```ollama serve ```, still got  Fail to access model(qwen).**ERROR**: [Errno 111] Connection refused ```

> I don't think localhost is the right IP since it is not reachable in docker container. So, try to use the real machine IP.

**Comment by zzlTim** [comment]
> > 我不认为 localhost 是正确的 IP，因为它在 docker 容器中无法访问。所以，尽量使用真机IP。
> 
> 之后，仍然得到 '''无法访问 model（qwen）。**错误**：[Errno 111] 连接被拒绝 ''`export OLLAMA_HOST=0.0.0.0:11434``ollama serve `

你解决了吗？
