### ISSUE TITLE
[Question]: Can RAGFlow be deployed locally?

### ISSUE THREAD

**Issue by DAAworld** [infiniflow/ragflow#1193]
### Describe your problem

使用bash entrypoint.sh之后，用的是T4GPU ,感觉特别慢，离线部署的时候，
            embd_mdl = LLMBundle(r["tenant_id"], LLMType.EMBEDDING, llm_name=r["embd_id"], lang=r["language"])这行代码和
paddle layouts: 0.1166270489920862这个日志之间间隔差不多10分钟。不知道是哪一步占用了时间。
我查看nvidia-smi之后，发现有启动的进程好像有使用GPU，但就算不使用GPU，速度也不会有10分钟左右吧

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for discussion. Thank you.

**Comment by KevinHuSh** [comment]
It's probably downloading embedding model.
GPU can only accelerate embedding procedure. And you need to change docker-compose..yaml a little bit.

**Comment by DAAworld** [comment]
> It's probably downloading embedding model. GPU can only accelerate embedding procedure. And you need to change docker-compose..yaml a little bit.

That's a complete offline state. I feel that it is time to ask the external network timeout, but I don't know which part of the code.
