### ISSUE TITLE
[Feature Request]: Hope to support the local rerank model

### ISSUE THREAD

**Issue by YannSuper** [infiniflow/ragflow#1197]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
I want to support local rerank models,Ollama or Xinference ReRank models
```

### Describe the feature you'd like

I want to support local rerank models,Ollama or Xinference ReRank models

### Additional information

![image](https://github.com/infiniflow/ragflow/assets/53294632/04813fa6-98c5-4ab7-a6dc-29ebc1ca9c70)

**Comment by jay-jjwu** [comment]
is it implemented?

**Comment by KevinHuSh** [comment]
yes
