### ISSUE TITLE
[Question]: Any way to allow multiple users to share/access one knowledge base? Any way to allow a same account can be logged in on different clients at the same time?

### ISSUE THREAD

**Issue by HOU-SZ** [infiniflow/ragflow#1206]
### Describe your problem

1. Any way to allow multiple users to share/access one knowledge base? 
2. Any way to allow the same account can be logged in on different clients at the same time?

**Comment by ralienpp** [comment]
Wouldn't this feature solve #1? It is already there:

![image](https://github.com/infiniflow/ragflow/assets/295338/103016d9-86be-4c56-9c24-8b4414793ce8)

**Comment by HOU-SZ** [comment]
> Wouldn't this feature solve #1? It is already there:
> 
> ![image](https://private-user-images.githubusercontent.com/295338/340687862-103016d9-86be-4c56-9c24-8b4414793ce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTY3ODgsIm5iZiI6MTcxODcxNjQ4OCwicGF0aCI6Ii8yOTUzMzgvMzQwNjg3ODYyLTEwMzAxNmQ5LTg2YmUtNGM1Ni05YzI0LThiNDQxNDc5M2NlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMzE0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTA5NmI4NGJhYzQ4MTFiOTVmOGRhNWUyOWVjYzBhN2JiNTc5YzZlZjg0ZDZjZDUxZTJkYzliZGY3ZmVjZDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BtzU7S3-5cWvbc5z5WxTbsPz_6I7FHrFndy_CAfcJ5U)

How to manage team members such as adding other users to my team?

**Comment by KevinHuSh** [comment]
Sorry, this function is not open source yet.

**Comment by HOU-SZ** [comment]
> Sorry, this function is not open source yet.

When will the team manage function be open sourced?

**Comment by KevinHuSh** [comment]
Not planed yet.
