### ISSUE TITLE
[Question]: Application becomes unresponsive under moderate load

### ISSUE THREAD

**Issue by shichunshan** [infiniflow/ragflow#1208]
### Describe your problem

![1718718501850](https://github.com/infiniflow/ragflow/assets/3012746/de6079d2-5669-457e-9a3f-a72c58389042)

**Comment by shichunshan** [comment]
any suggestions?

**Comment by KevinHuSh** [comment]
I think you start multiple ragflow_server.py at the same time.

**Comment by shichunshan** [comment]
I deployed it through Docker Compose, didn't do any operations, just used two threads for testing.

**Comment by shichunshan** [comment]
It's because I turned on debug mode.
