### ISSUE TITLE
[Bug]: Unable to parse ppt and pptx files (not missing *.so)

### ISSUE THREAD

**Issue by fire717** [infiniflow/ragflow#1210]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8d667d5abdbd185e60140b22150851aa8e6a3ebe

### Actual behavior

init server from docker, then upload ppt file,  then try to parse, got error

.pdf is ok
.ppt got: ERROR]Internal server error: File is not a zip file
.pptx got :[ERROR]Internal server error: unsupported operand type(s) for //: NoneType and int

### Steps to reproduce

```Markdown
git clone main
then init docker and upload ppt
```

**Comment by guoyuhao2330** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> [8d667d5](https://github.com/infiniflow/ragflow/commit/8d667d5abdbd185e60140b22150851aa8e6a3ebe)
> 
> ### Other environment information
> _No response_
> 
> ### Actual behavior
> init server from docker, then upload ppt file, then try to parse, got error
> 
> .pdf is ok .ppt got: ERROR]Internal server error: File is not a zip file .pptx got :[ERROR]Internal server error: unsupported operand type(s) for //: NoneType and int
> 
> ### Expected behavior
> _No response_
> 
> ### Steps to reproduce
> ```
> git clone main
> then init docker and upload ppt
> ```
> 
> ### Additional information
> _No response_

can't reproduce
![image](https://github.com/infiniflow/ragflow/assets/43509927/b599d471-386d-40dc-8555-cf10b160875d)
![image](https://github.com/infiniflow/ragflow/assets/43509927/7c38b343-2202-4b26-8dba-00058d9e4000)

**Comment by stephenlzc** [comment]
Same problem.

Once I set up the Ragflow by using the method from [README](https://github.com/infiniflow/ragflow/blob/main/README_zh.md). There is not change.

When I upload a pptx file, the parse shows error.
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/34f9bba0-bdc6-4e17-852a-d1f2faebf1a1">


Here is the log from server:
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 146, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/presentation.py", line 105, in chunk
    for pn, (txt, img) in enumerate(ppt_parser(
  File "/ragflow/rag/app/presentation.py", line 27, in __call__
    txts = super().__call__(fnm, from_page, to_page)
  File "/ragflow/deepdoc/parser/ppt_parser.py", line 54, in __call__
    for shape in sorted(
  File "/ragflow/deepdoc/parser/ppt_parser.py", line 55, in <lambda>
    slide.shapes, key=lambda x: (x.top // 10, x.left)):
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

My computer is i7-12600 + 64RAM + 4060Ti 16G, and already install well Ubuntu Server, Docker, and other containers are all running well.
