### ISSUE TITLE
[Bug]: When I use Preview under chatbotAPI and ask some questions on demo site, it return ERROR: 'function' object is not subscriptable

### ISSUE THREAD

**Issue by ZEWorking123** [infiniflow/ragflow#1212]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Other environment information

```Markdown
https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961
```

### Actual behavior

https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961

### Steps to reproduce

```Markdown
https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961
```

**Comment by guoyuhao2330** [comment]
> ### 同一错误是否存在现有问题？
> * [x] 我已经检查了现有问题。
> 
> ### 分行名称
> 主要
> 
> ### 提交 ID
> 分子式：C3B2A1
> 
> ### 其他环境信息
> ```
> https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961
> ```
> 
> ### 实际行为
> [#1075 （评论）](https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961)
> 
> ### 预期行为
> _没有回应_
> 
> ### 重现步骤
> ```
> https://github.com/infiniflow/ragflow/issues/1075#issue-2337392961
> ```
> 
> ### 其他信息：
> _没有回应_

It's been fixed.
