### ISSUE TITLE
[Question]: In pdf_parser.py, is the code for determining whether a document is in English wrong?

### ISSUE THREAD

**Issue by ursa103079** [infiniflow/ragflow#1225]
### Describe your problem

in ragflow/deepdoc/parser/pdf_parser.py, line 980-line 988
![image](https://github.com/infiniflow/ragflow/assets/59460165/c06e2dc0-ff34-4013-a215-b7e2546d5957)
The regex matching here does not take into account the spaces`\s`.
And why the value`self.is_english` is set to `False` right after the judgment?

**Comment by KevinHuSh** [comment]
This is deprecated.
