### ISSUE TITLE
[Question]: I set the value of vm.max_map_count in WSL, but es still cannot start

### ISSUE THREAD

**Issue by Old-Lane** [infiniflow/ragflow#1226]
### Describe your problem

# I set the value of vm.max_map_count in WSL, but es still cannot start

![image](https://github.com/infiniflow/ragflow/assets/79893196/93e605f3-f928-406c-a930-f80d337168fe)

**Comment by aopstudio** [comment]
Maybe you can edit your [.wslconfig file⁠](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) to allocate more resources (especially memory) for wsl

**Comment by Old-Lane** [comment]
> Maybe you can edit your [.wslconfig file⁠](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) to allocate more resources (especially memory) for wsl

Thank you so much, by the way, why does this error appear in the service log? I have already installed this package
![image](https://github.com/infiniflow/ragflow/assets/79893196/625689ee-938b-4f4d-a5a8-b0aacbf543be)

**Comment by aopstudio** [comment]
Current official image doesn't include `roman_numbers`. Did you build your Docker image from scratch? If so, you need to manually install the missing dependency packages in the Docker container.
