### ISSUE TITLE
[Question]: There was a failure in adding the API key. So how to add the API-Key correctly?

### ISSUE THREAD

**Issue by water-2022** [infiniflow/ragflow#1228]
### Describe your problem

The details are as follows:

![企业微信截图_1718879993245](https://github.com/infiniflow/ragflow/assets/44528471/1fcfce70-3da1-4b40-bebc-a7f50fdc8441)

Thank you for your response.

**Comment by KevinHuSh** [comment]
It seems your DNS has issue to translate URL of ZHIPU.

**Comment by water-2022** [comment]
> It seems your DNS has issue to translate URL of ZHIPU.

I have made additional changes to the /etc/resolv.conf file.

~~~
docker exec -it ragflow-server /bin/bash
vi /etc/resolv.conf
nameserver 8.8.8.8
nameserver 114.114.114.114
~~~

The issue has been resolved. However, is it strange that it's not the default configuration in a docker container?
