### ISSUE TITLE
[Bug]: During the process of identifying chapter items within PDF documents using the rec.onnx model, a specific recognition error occurs

### ISSUE THREAD

**Issue by zhangxian** [infiniflow/ragflow#1234]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

This error involves the character "十", which represents the number ten in Chinese, being incorrectly identified as "于". This misinterpretation becomes evident when the model attempts to read phrases such as "第十条" (meaning "Article 10") or "第十二条" (meaning "Article 12"), where "十" should denote the digit ten.
![image](https://github.com/infiniflow/ragflow/assets/6063368/21f4c242-ed1a-4018-8333-44eeba3f6c6e)

use book parse method
![image](https://github.com/infiniflow/ragflow/assets/6063368/bb7e14a8-eae5-42f7-bbc9-4f084b5aa7be)

### Steps to reproduce

```Markdown
no
```

**Comment by guoyuhao2330** [comment]
This may be an error that occurred during OCR model recognition. This issue can be resolved by improving the model's capabilities in the future.
