### ISSUE TITLE
[Bug]: Missing Libraries When Rebuild Docker Image

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#1237]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

15bf9f8

### Actual behavior

Missing Libraries

Logged into ragflow server and installed missing libraries:

root@0ee418f234b0:/ragflow# pip3 install roman-numbers
Collecting roman-numbers
  Downloading roman_numbers-1.0.2-py3-none-any.whl.metadata (1.5 kB)
Downloading roman_numbers-1.0.2-py3-none-any.whl (3.7 kB)
Installing collected packages: roman-numbers
Successfully installed roman-numbers-1.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python3 -m pip install --upgrade pip
root@0ee418f234b0:/ragflow# pip3 install word2number
Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=9832fab24ab7d8cb15f81c5fc31a26fd3ba7128a06580ad0799f9b8e65c0c0ad
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python3 -m pip install --upgrade pip
root@0ee418f234b0:/ragflow# pip3 install cn2an
Collecting cn2an
  Downloading cn2an-0.5.22-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools>=47.3.1 in /usr/lib/python3/dist-packages (from cn2an) (59.6.0)
Collecting proces>=0.1.3 (from cn2an)
  Downloading proces-0.1.7-py3-none-any.whl.metadata (3.3 kB)
Downloading cn2an-0.5.22-py3-none-any.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 2.9 MB/s eta 0:00:00
Downloading proces-0.1.7-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.7/137.7 kB 11.3 MB/s eta 0:00:00
Installing collected packages: proces, cn2an
Successfully installed cn2an-0.5.22 proces-0.1.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python3 -m pip install --upgrade pip
root@0ee418f234b0:/ragflow#

### Expected behavior

build environment and install all appropriate libraries 

### Steps to reproduce

```Markdown
do a pull using git. and follow instructs to build sources
```

**Comment by KevinHuSh** [comment]
The dev version of docker image and base image(infiniflow/ragflow-base:v2.0) have already installed these package.
You could pull them to apply.
