### ISSUE TITLE
[Bug]: Stuck in search and the answer is cut.

### ISSUE THREAD

**Issue by fire717** [infiniflow/ragflow#1239]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8d667d5abdbd185e60140b22150851aa8e6a3ebe

### Other environment information

```Markdown
a6000 48g
ubuntu22
docker
```

### Actual behavior

1. When add some files and try to chatting, it stuck with "搜索中" ，and you cannot see the vertical line of the mouse cursor flickering in the end (under normal circumstances, it will flash and then start answering)
2. The model didn't answer a few sentences before it became "......由于长度的原因，回答被截断了，要继续吗“，evenif I change the MAX TOKEN from512 to2048 in the model setting page.And I am sure the token model has answered not even more than 100 token.

### Steps to reproduce

```Markdown
Origin code with the env list before. Add dozens of documents
```

**Comment by KevinHuSh** [comment]
For problem 1, I bleived it stucked in embedding or reranking since it's slowly running on CPU. Another option is to check ES status, like how much CPU or RAM it used.
For 2, disable max_token, just toggle out.

**Comment by skytodmoon** [comment]
mark， I met the same problem with dev version on 2024-09-11
