### ISSUE TITLE
[Question]: Parsing method table failed to parse xlxs

### ISSUE THREAD

**Issue by water-2022** [infiniflow/ragflow#1250]
### Describe your problem

The error is as follows：

~~~
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 146, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/table.py", line 141, in chunk
    dfs = excel_parser(
  File "/ragflow/rag/app/table.py", line 66, in __call__
    res.append(pd.DataFrame(np.array(data), columns=headers))
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 816, in __init__
    mgr = ndarray_to_mgr(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (0, 1), indices imply (0, 7)
~~~

**Comment by KevinHuSh** [comment]
Could you attach the file?

**Comment by water-2022** [comment]
> Could you attach the file?

The files are company property.
﻿
The Excel file contains an excessive number of sheets, and the table has some merged cells.

**Comment by KevinHuSh** [comment]
Could you mock up a sample that will fail.

**Comment by water-2022** [comment]
> Could you mock up a sample that will fail.

[1.xlsx](https://github.com/user-attachments/files/16012305/1.xlsx)

**Comment by water-2022** [comment]
> Could you mock up a sample that will fail.

This is a sample file.

[1.xlsx](https://github.com/user-attachments/files/16050142/1.xlsx)

**Comment by ZhichengQian1** [comment]
Hello, how do you use the parse module? Is it through command line interface (CLI) or deployment?

**Comment by water-2022** [comment]
> Hello, how do you use the parse module? Is it through command line interface (CLI) or deployment?

You can configure the Chunk method in the portal.

![企业微信截图_17200610601470](https://github.com/infiniflow/ragflow/assets/44528471/bd97c58f-6a47-47b7-a026-0781cd971c0f)

**Comment by ZhichengQian1** [comment]
> > Hello, how do you use the parse module? Is it through command line interface (CLI) or deployment?
> 
> You can configure the Chunk method in the portal.
> 
> ![企业微信截图_17200610601470](https://private-user-images.githubusercontent.com/44528471/345680133-bd97c58f-6a47-47b7-a026-0781cd971c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjIxMDcsIm5iZiI6MTcyMDA2MTgwNywicGF0aCI6Ii80NDUyODQ3MS8zNDU2ODAxMzMtYmQ5N2M1OGYtNmE0Ny00N2I3LWEwMjYtMDc4MWNkOTcxYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMGIzNWFmOTc2MWNmNmUzOTM5ZjQ2MWE5NzgzNjBmMTFjY2Y4YWZiMGM1ZGM3MWEzYTBjZjI2YWFjMjU2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-nzJ-9ZLPgZ-O3P722pJ8740mZbXlB6MHsGCqyEQ2U)

Thank you, but I just want to utilize the parse module.

**Comment by water-2022** [comment]
> Thank you, but I just want to utilize the parse module.

Maybe you can look at the source code of Ragflow.

**Comment by lvyoudashuju** [comment]
请问一下，你这个问题解决了吗？我也遇到了这个问题。

**Comment by JinHai-CN** [comment]
@lvyoudashuju We intend to create an international community, so we encourage using English for communication.

@KevinHuSh Any updates on this issue?

**Comment by KevinHuSh** [comment]
> > Could you mock up a sample that will fail.
> 
> @KevinHuSh This is a sample file.
> 
> [1.xlsx](https://github.com/user-attachments/files/16050142/1.xlsx)

This file can be parse smoothly on demo site.

**Comment by KevinHuSh** [comment]
> 请问一下，你这个问题解决了吗？我也遇到了这个问题。

Could you elabrate on your issue?
Attach the sample file if it's okay for you.

**Comment by lvyoudashuju** [comment]
> > 请问一下，你这个问题解决了吗？我也遇到了这个问题。
> 
> Could you elabrate on your issue? Attach the sample file if it's okay for you.

![image](https://github.com/user-attachments/assets/f7382037-9b65-4e9a-85f6-ee2797a41027)

**Comment by JokerRun** [comment]
Recreate the scenario: Create a new knowledge base, select the table parsing method, and import an Excel file (using [1.xlsx](https://github.com/user-attachments/files/17084458/1.xlsx)
 as an example).


I tried it, and it seems that when there are more than two sheets in the Excel file, this issue occurs.

Even with only two sheets, only the first sheet is parsed, and the subsequent sheets are not.

**Comment by KevinHuSh** [comment]
Method 'Table' is for data dumped from DB, so, you'd better parse it by 'General'.

**Comment by lvyoudashuju** [comment]
> Recreate the scenario: Create a new knowledge base, select the table parsing method, and import an Excel file (using [1.xlsx](https://github.com/user-attachments/files/17084458/1.xlsx) as an example).
> 
> I tried it, and it seems that when there are more than two sheets in the Excel file, this issue occurs.
> 
> Even with only two sheets, only the first sheet is parsed, and the subsequent sheets are not.


It's not exactly what you said. I uploaded an excel file containing 2 sheets and it could be parsed successfully, but when I uploaded another excel file containing 4 sheets, the parsing failed.

**Comment by yuzhichang** [comment]
As @KevinHuSh said, `Method 'Table' is for data dumped from DB, so, you'd better parse it by 'General'.`
