### ISSUE TITLE
how to run apps or whole project in local 

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1260]
### Describe your problem

anyway to run or debug the apps in api folder , for example   "apps/dialog_app.py" , and I am wondering the apps meaning  each one  can be standalone running ? 

and if could be , then how to run it ? after docker-compose -f docker-compose-base.yml  running the basic service up . then what's the next ? 

thanks.

**Comment by KevinHuSh** [comment]
I'm afraid that it can't run independently.
You could use post man to debug or test  it.

**Comment by yangboz** [comment]
> I'm afraid that it can't run independently.
> You could use post man to debug or test it.

so , how you guys to run/debug it in  local?

**Comment by KevinHuSh** [comment]
Start the server and use postman to debug the APIs

**Comment by yangboz** [comment]
> Start the server and use postman to debug the APIs

sorry ,man , I mean debug  in project codebase level .  how to running and debug rag flow-server.py in  terminal

**Comment by yangboz** [comment]
> Start the server and use postman to debug the APIs

even with  postman, there is no guide or document  on it.  if could be provided , we will be greatly appreciated.

thanks.

**Comment by yangboz** [comment]
> > > Start the server and use postman to debug the APIs
> > 
> > 
> > even with postman, there is no guide or document on it. if could be provided , we will be greatly appreciated.
> > thanks.
> > you can refer to this
> > https://ragflow.io/docs/dev/faq#9-how-to-upgrade-ragflow

most parts of it is docker based, how about codebase level with condo/pip way  ?

**Comment by KevinHuSh** [comment]
Please refer to [this](https://ragflow.io/docs/dev/faq#11-how-to-build-the-ragflow-image-from-scratch)

**Comment by peak-xu** [comment]
@KevinHuSh I still don’t quite understand, how to debug the code locally, you can set the type of breakpoint
