### ISSUE TITLE
[Question]: how should I optimize it in the production environment to ensure stability?

### ISSUE THREAD

**Issue by shichunshan** [infiniflow/ragflow#1265]
### Describe your problem

./entrypoint.sh: line 25: 18337 Killed                  $PY api/ragflow_server.py
[WARNING] [2024-06-24 07:59:24,499] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
SUM: [WARNING] Load term.freq FAIL!

    ____                 ______ __               
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
              /____/                             

    
[INFO] [2024-06-24 07:59:36,021] [_internal._log] [line:96]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://192.168.80.8:9380

The process was killed, how should I optimize it in the production environment to ensure stability?

**Comment by KevinHuSh** [comment]
No less than 64G RAM, more than 16G GPU mem, multiple nodes of ES cluster.
That will work.

**Comment by shichunshan** [comment]
My resources meet the requirements, but the system is still being killed with 5 concurrent requests, and the response time exceeds 40 seconds. At this point, the system resource usage is not high.
