### ISSUE TITLE
[Question]: Chinese Characters Converted to Unicode Escape Sequences in API Response

### ISSUE THREAD

**Issue by aiping312** [infiniflow/ragflow#1267]
### Describe your problem

in API response, the Chinese characters in the returned content are converted to Unicode escape sequences. For example, '管理规程' becomes '\u7ba1\u7406\u89c4\u7a0b'. How to resolve it？

**Comment by KevinHuSh** [comment]
[This](https://stackoverflow.com/questions/1207457/convert-a-unicode-string-to-a-string-in-python-containing-extra-symbols) might help.
