### ISSUE TITLE
[Bug]: Parsing progress not displayed correctly when RAPTOR turned on

### ISSUE THREAD

**Issue by cyhasuka** [infiniflow/ragflow#1272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

d3b3354b; d6c0310

### Actual behavior

Example: When embedding is started, the progress bar shows 67%. However, when the embedding is finished and RAPTOR is started, the progress bar decreases to 54.62%.
![image](https://github.com/infiniflow/ragflow/assets/34462246/0de3c33f-836f-4c01-899d-d4205c1a8658)
![image](https://github.com/infiniflow/ragflow/assets/34462246/5c53de24-dc41-4371-a879-ece40795471e)

### Steps to reproduce

```Markdown
Upload files.
Start a task.
Notice how the progress bar shows.
```

**Comment by KevinHuSh** [comment]
Yes, it doesn't make sense.

**Comment by Old-Lane** [comment]
There is actually no problem, it just takes a long time (I used Ollama)

**Comment by cyhasuka** [comment]
> There is actually no problem, it just takes a long time (I used Ollama)

I'm giving feedback on **display issues**, not functionality issues.

**Comment by Old-Lane** [comment]
> > There is actually no problem, it just takes a long time (I used Ollama)
> 
> I'm giving feedback on **display issues**, not functionality issues.
> 
> Besides, the long processing time may due to ollama reloads a different model, which takes a relatively long time.

i'm sorry，it's my fault.
By the way, have you ever encountered a situation where the answer was too short or incomplete?

**Comment by cyhasuka** [comment]
> > > There is actually no problem, it just takes a long time (I used Ollama)
> > 
> > 
> > I'm giving feedback on **display issues**, not functionality issues.
> > Besides, the long processing time may due to ollama reloads a different model, which takes a relatively long time.
> 
> i'm sorry，it's my fault. By the way, have you ever encountered a situation where the answer was too short or incomplete?

Just disable the "Max Tokens" in "Model Setting" tabs.

**Comment by Old-Lane** [comment]
> > > > There is actually no problem, it just takes a long time (I used Ollama)
> > > 
> > > 
> > > I'm giving feedback on **display issues**, not functionality issues.
> > > Besides, the long processing time may due to ollama reloads a different model, which takes a relatively long time.
> > 
> > 
> > i'm sorry，it's my fault. By the way, have you ever encountered a situation where the answer was too short or incomplete?
> 
> Just disable the "Max Tokens" in "Model Setting" tabs.

thank you very much！
