### ISSUE TITLE
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1280]
### Describe your problem

when running in ubuntu 22.04  follow the README.md, after running docker compose up -d , it throws:
```
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
(root) Additional property include is not allowed
```

any idea? thanks.

Current Repo: ragflow
Commit Id: 80163c0
Operating system: Ubuntu 24.04 (Kernel version: 6.8.0-35-generic)
CPU Type: x86_64
Memory: 62Gi
Docker Version: 24.0.7,
Python Version: 3.11.9

docker -v
Docker version 24.0.7, build 24.0.7-0ubuntu4

docker compose version
Docker Compose version v2.3.3

**Comment by cyhasuka** [comment]
If you are in mainland China, use the `docker-compose-CN.yml` instead.

`docker compose -f docker-compose-CN.yml up -d`

**Comment by yangboz** [comment]
> If you are in mainland China, use the `docker-compose-CN.yml` instead.
> 
> `docker compose -f docker-compose-CN.yml up -d`
still the same 
:(
```
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
(root) Additional property include is not allowed
```

**Comment by KevinHuSh** [comment]
Check the docker version. It's a little lower.

**Comment by yangboz** [comment]
so what's your suggested version ? thanks.

**Comment by cyhasuka** [comment]
My docker version is the same as yours, and my docker compose version is `v2.21.0`. It's works fine.

**Comment by yangboz** [comment]
and , here is my testing server info :
docker -v
Docker version 24.0.7, build 24.0.7-0ubuntu4
as required docker version >=24 from readme.md

**Comment by yangboz** [comment]
> My docker version is the same as yours, and my docker compose version is `v2.21.0`. It's works fine.

tried downgrade my docker-compose from version  v2,28.1 to v2.21.0 
after running docker compose up -d , 
here is coming the old issue   again.

<img width="884" alt="Screenshot 2024-06-27 at 17 36 02" src="https://github.com/infiniflow/ragflow/assets/481954/5a431086-9dd1-4f4e-96bd-bcbec38b3972">


just wondering , how the host know the es01 name ? even IP:1200 for es is working.
//es01:9200

**Comment by sushushimoonif** [comment]
> If you are in mainland China, use the `docker-compose-CN.yml` instead.
> 
> `docker compose -f docker-compose-CN.yml up -d`

成功啦~谢谢大佬！

**Comment by zzlTim** [comment]
> > My docker version is the same as yours, and my docker compose version is `v2.21.0`. It's works fine.
> 
> tried downgrade my docker-compose from version v2,28.1 to v2.21.0 after running docker compose up -d , here is coming the old issue again.
> 
> <img alt="Screenshot 2024-06-27 at 17 36 02" width="884" src="https://private-user-images.githubusercontent.com/481954/343717108-5a431086-9dd1-4f4e-96bd-bcbec38b3972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDY2NTUsIm5iZiI6MTcyMTA0NjM1NSwicGF0aCI6Ii80ODE5NTQvMzQzNzE3MTA4LTVhNDMxMDg2LTlkZDEtNGY0ZS05NmJkLWJjYmVjMzhiMzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMjI1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWI2MzgzMDA3NjkyYzJhMjY2MTEyZTkyYmNmM2JiZTc2Y2IxMmY3MzZhZDIwMzhhMzg3ODhlYjdjMGU2MDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRLxtIZXZ3u3LkRMW8j-RLBMwtImxd8wP7TusWw1hVc">
> just wondering , how the host know the es01 name ? even IP:1200 for es is working.
> 
> ```
> elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x72150feb18a0>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
> ```

你解决了吗？

**Comment by zzlTim** [comment]
> > If you are in mainland China, use the `docker-compose-CN.yml` instead.
> > `docker compose -f docker-compose-CN.yml up -d`
> 
> 成功啦~谢谢大佬！

你的docker-compose是什么版本？

**Comment by zzlTim** [comment]
> > > My docker version is the same as yours, and my docker compose version is `v2.21.0`. It's works fine.
> > 
> > 
> > tried downgrade my docker-compose from version v2,28.1 to v2.21.0 after running docker compose up -d , here is coming the old issue again.
> > <img alt="Screenshot 2024-06-27 at 17 36 02" width="884" src="https://private-user-images.githubusercontent.com/481954/343717108-5a431086-9dd1-4f4e-96bd-bcbec38b3972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDY2NTUsIm5iZiI6MTcyMTA0NjM1NSwicGF0aCI6Ii80ODE5NTQvMzQzNzE3MTA4LTVhNDMxMDg2LTlkZDEtNGY0ZS05NmJkLWJjYmVjMzhiMzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMjI1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWI2MzgzMDA3NjkyYzJhMjY2MTEyZTkyYmNmM2JiZTc2Y2IxMmY3MzZhZDIwMzhhMzg3ODhlYjdjMGU2MDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRLxtIZXZ3u3LkRMW8j-RLBMwtImxd8wP7TusWw1hVc">
> > just wondering , how the host know the es01 name ? even IP:1200 for es is working.
> > ```
> > elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x72150feb18a0>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
> > ```
> 
> 你解决了吗？

我把cn那个文件和base那个文件合成一个文件（可以问大模型怎么合并），然后执行。虽然有WARN但能支持拉取镜像了

**Comment by sushushimoonif** [comment]
> > > If you are in mainland China, use the `docker-compose-CN.yml` instead.
> > > `docker compose -f docker-compose-CN.yml up -d`
> > 
> > 
> > 成功啦~谢谢大佬！
> 
> 你的docker和docker-compose是什么版本？



> > > > My docker version is the same as yours, and my docker compose version is `v2.21.0`. It's works fine.
> > > 
> > > 
> > > tried downgrade my docker-compose from version v2,28.1 to v2.21.0 after running docker compose up -d , here is coming the old issue again.
> > > <img alt="Screenshot 2024-06-27 at 17 36 02" width="884" src="https://private-user-images.githubusercontent.com/481954/343717108-5a431086-9dd1-4f4e-96bd-bcbec38b3972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDY2NTUsIm5iZiI6MTcyMTA0NjM1NSwicGF0aCI6Ii80ODE5NTQvMzQzNzE3MTA4LTVhNDMxMDg2LTlkZDEtNGY0ZS05NmJkLWJjYmVjMzhiMzk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMjI1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWI2MzgzMDA3NjkyYzJhMjY2MTEyZTkyYmNmM2JiZTc2Y2IxMmY3MzZhZDIwMzhhMzg3ODhlYjdjMGU2MDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRLxtIZXZ3u3LkRMW8j-RLBMwtImxd8wP7TusWw1hVc">
> > > just wondering , how the host know the es01 name ? even IP:1200 for es is working.
> > > ```
> > > elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x72150feb18a0>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
> > > ```
> > 
> > 
> > 你解决了吗？
> 
> 我把cn那个文件和base那个文件合成一个文件（可以问大模型怎么合并），然后执行。虽然有WARN但能支持拉取镜像了



> > > If you are in mainland China, use the `docker-compose-CN.yml` instead.
> > > `docker compose -f docker-compose-CN.yml up -d`
> > 
> > 
> > 成功啦~谢谢大佬！
> 
> 你的docker和docker-compose是什么版本？

24.0.7。emmm...我没那么麻烦，跟着说的改了一步就成功了~
