### ISSUE TITLE
[Question]: Does text-embedding-v2 use a local model?

### ISSUE THREAD

**Issue by leecj** [infiniflow/ragflow#1298]
### Describe your problem

我使用了通义千问的API key,embedding模型选择text-embedding-v2，为什么CPU模式下embedding非常缓慢，并且后台在下载text-embedding-v2模型

I used the API key from Tongyi Qianwen, and selected the embedding model text-embedding-v2. Why is the embedding very slow in CPU mode, and is the backend downloading the text-embedding-v2 model?

<img width="1144" alt="image" src="https://github.com/infiniflow/ragflow/assets/7512945/1b92e5ba-60a0-4b83-9b3d-baa25426563b">

**Comment by yangboz** [comment]
> ### Describe your problem
> 我使用了通义千问的API key,embedding模型选择text-embedding-v2，为什么CPU模式下embedding非常缓慢，并且后台在下载text-embedding-v2模型
> 
> I used the API key from Tongyi Qianwen, and selected the embedding model text-embedding-v2. Why is the embedding very slow in CPU mode, and is the backend downloading the text-embedding-v2 model?
> 
> <img alt="image" width="1144" src="https://private-user-images.githubusercontent.com/7512945/343696556-1b92e5ba-60a0-4b83-9b3d-baa25426563b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODI4MjksIm5iZiI6MTcxOTQ4MjUyOSwicGF0aCI6Ii83NTEyOTQ1LzM0MzY5NjU1Ni0xYjkyZTViYS02MGEwLTRiODMtOWIzZC1iYWEyNTQyNjU2M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMTAwMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjY4MzIyNjVkYWVjYThlZmUwYzYyMjdhODQ1ZTVlNzBlY2FjNTFiMGRjNDMzNGY1NzY0Yjc4Yjk2N2RjNWRhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qs3No1_2Vj-9F2Oc2Ds7GRX0EAlHrpl79EUJOsPd32E">

可能需要预先手动执行如下命令：
export HF_ENDPOINT=https://hf-mirror.com
然后下载模型至本地缓存
huggingface-cli download --resume-download text-embedding-v2 --local-dir text-embedding-v2

**Comment by KevinHuSh** [comment]
Pull the dev version of docker image and git pull the latest code.

**Comment by leecj** [comment]
> Pull the dev version of docker image and git pull the latest code.

我还是不懂为什么需要本地的text-embedding-v2。另外当聊天时下载模型的设计非常失败，这不利于软件设计的稳定性，建议在启动、配置时就保障模型已经下载完成

I still don't understand why we need the local text-embedding-v2. Additionally, the design of downloading the model during the chat is very poor, which is not conducive to the stability of the software design. It is recommended that the model should be downloaded and completed during startup and configuration.
