### ISSUE TITLE
[Question]:  Why the Vector Similarity is always Zero？？

### ISSUE THREAD

**Issue by hyr910331** [infiniflow/ragflow#1304]
### Describe your problem

Why the Vector Similarity is always Zero？？
![image](https://github.com/infiniflow/ragflow/assets/13481396/509838c9-be4b-4e10-b70d-f82d569fc0ac)

**Comment by hyr910331** [comment]
im using openAI text-embedding-3-large

**Comment by KevinHuSh** [comment]
Wha't is dimension of this embedding? Any exception in log?

**Comment by seedclaimer** [comment]
> Wha't is dimension of this embedding? Any exception in log?

same problem. i'm using model yinka (1792d) on xinference，switching to bge(1024d, also on xinference) does solve the problem
