### ISSUE TITLE
[Question]: ERROR: No matching distribution found for Aspose.Slides==24.2.0

### ISSUE THREAD

**Issue by n3A87** [infiniflow/ragflow#1305]
### Describe your problem

> ERROR: Ignored the following versions that require a different python version: 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.10.0 Requires-Python >=3.5,<3.11; 22.11.0 Requires-Python >=3.5,<3.11; 22.12.0 Requires-Python >=3.5,<3.11; 22.4.0 Requires-Python >=3.5,<3.10; 22.6.0 Requires-Python >=3.5,<3.11; 22.7.0 Requires-Python >=3.5,<3.11; 22.8.0 Requires-Python >=3.5,<3.11; 22.9.0 Requires-Python >=3.5,<3.11; 23.1.0 Requires-Python >=3.5,<3.11; 23.10.0 Requires-Python >=3.5,<3.12; 23.11.0 Requires-Python >=3.5,<3.12; 23.12.0 Requires-Python >=3.5,<3.12; 23.2.0 Requires-Python >=3.5,<3.11; 23.3.0 Requires-Python >=3.5,<3.11; 23.4.0 Requires-Python >=3.5,<3.11; 23.5.0 Requires-Python >=3.5,<3.12; 23.6.0 Requires-Python >=3.5,<3.12; 23.7.0 Requires-Python >=3.5,<3.12; 23.8.0 Requires-Python >=3.5,<3.12; 23.9.0 Requires-Python >=3.5,<3.12; 24.1.0 Requires-Python >=3.5,<3.12; 24.2.0 Requires-Python >=3.5,<3.12; 24.3.0 Requires-Python >=3.5,<3.12; 24.4.0 Requires-Python <3.12,>=3.5; 24.5.0 Requires-Python <3.12,>=3.5
ERROR: Could not find a version that satisfies the requirement Aspose.Slides==24.2.0 (from versions: 24.6.0)
ERROR: No matching distribution found for Aspose.Slides==24.2.0

When I start ragflow locally according to the following command, I encounter the above error, should I adjust the version of python?
```
$ git clone https://github.com/infiniflow/ragflow.git
$ cd ragflow/

$ conda create -n ragflow python=3.11.0
$ conda activate ragflow
$ pip install -r requirements.txt
```
my conda version = 24.4.0

**Comment by KevinHuSh** [comment]
What about: python -m pip install --upgrade pip

**Comment by yuzhichang** [comment]
We've replaced pip with poetry. Poetry is much better on dependency management and download speed.
