### ISSUE TITLE
[Question]: use Mac M1 can not local develop 

### ISSUE THREAD

**Issue by uestc-lxp** [infiniflow/ragflow#1322]
### Describe your problem

env: Mac M1 
Use ragflow official method:
$ conda create -n ragflow python=3.11.0
$ conda activate ragflow
$ pip install -r requirements_dev.txt   
when execute install, error occurs, how to process?
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement triton==2.2.0 (from versions: none)
ERROR: No matching distribution found for triton==2.2.0

**Comment by KevinHuSh** [comment]
What about using [requirements_arm.txt](https://github.com/infiniflow/ragflow/blob/main/requirements_arm.txt)

**Comment by yangboz** [comment]
I noticed here:
> Requires-Python >=3.8,<3.11
Requires-Python >=3.8,<3.11  conflicts with  conda create -n ragflow python=3.11.0
