### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by exYze** [infiniflow/ragflow#1325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

83803a7

### Other environment information

```Markdown
Ubuntu
```

### Actual behavior

When chatting with the bot, you can't add a space after words without a workaround

### Expected behavior

The space bar should add a space after each word
![_box1](https://github.com/infiniflow/ragflow/assets/39066234/065b93e4-fbec-404d-b771-edcc3e4715a3)
![_box2](https://github.com/infiniflow/ragflow/assets/39066234/f6f4fc5a-92e3-48e2-a897-838e74b00ae3)

### Steps to reproduce

```Markdown
When chatting with the bot, start typing like normal, when you get to the end of the first word, pressing the spacebar doesn't add a space.  In order to get it to add a space, I have to go back one character and then press the spacebar.  This then requires you to readd the last letter of the first word and then make sure to remove the extra letter at the end once you finish.
```

**Comment by KevinHuSh** [comment]
Upgrade to the dev version of docker image. It's been fixed.
