### ISSUE TITLE
[Question]: as a local project, Does it`s runtime depend on GPU ?  

### ISSUE THREAD

**Issue by qinlg** [infiniflow/ragflow#1326]
### Describe your problem

as a local project, Does it`s runtime depend on GPU source?   I saw in the readme that it needs CPU >= 4 cores RAM >= 16 GB ,  but it also needs cuda to launch the service

**Comment by KevinHuSh** [comment]
No, it does not. But GPU will accelerate embedding procedure when parsing file or retrieving chunks.
