### ISSUE TITLE
[Question]: After deploy ragflow on local, when i do retrieval testing, it always pose a network error.

### ISSUE THREAD

**Issue by amdongyang** [infiniflow/ragflow#1330]
### Describe your problem

After deploy ragflow on local, when i do retrieval testing, it always pose a network error.

**ConnectionError('<urllib3.connection.HTTPConnection object at 0x7f583d2be3e0>: Failed to establish a new connection: [Errno 111] Connection refused', errors=(ConnectionError('<urllib3.connection.HTTPConnection object at 0x7f599a61e6e0>: Failed to establish a new connection: [Errno 111] Connection refused', errors=(NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f599a61e6e0>: Failed to establish a new connection: [Errno 111] Connection refused'),)), ConnectionError('<urllib3.connection.HTTPConnection object at 0x7f583f4d6590>: Failed to establish a new connection: [Errno 111] Connection refused', errors=(NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f583f4d6590>: Failed to establish a new connection: [Errno 111] Connection refused'),)), ConnectionError('<urllib3.connection.HTTPConnection object at 0x7f583f4d52a0>: Failed to establish a new connection: [Errno 111] Connection refused', errors=(NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f583f4d52a0>: Failed to establish a new connection: [Errno 111] Connection refused'),))))**

**Comment by KevinHuSh** [comment]
It can't access ES, Mysql or Minio. Please check all the hosts parts in conf/service_conf.yaml.
