### ISSUE TITLE
[Question]: Is there any problem with part-of-speech tagging of huqie

### ISSUE THREAD

**Issue by 1556900941lizerui** [infiniflow/ragflow#1331]
### Describe your problem

Does nr represent the part of speech of a person in huqie.txt?If so, two words such as "金童玉商" and "青禾服装" should not belong to nr, and there are many other words that are marked as nr parts of speech. Looking forward to your reply, thank you

**Comment by KevinHuSh** [comment]
I dojn't think nr is for person, it is for a proper noun.

**Comment by 1556900941lizerui** [comment]
Thanks for your answer, but I still have a question. After searching online, I found that the parts of speech of huqie.txt contains most of the parts of speech abbreviations of PKU partof speech tagging set, which makes me think that the tagging is made according to the standard of this tagging set, while "nr" represents the name of a person in it. May I ask what part of speech tagging is made according to huqie.txt?

**Comment by 1556900941lizerui** [comment]
Thank you for your answer, but I have one more question. After searching on the Internet, I found that the part-of-speech of huqie.txt contains most part-of-speech abbreviations of the part-of-speech tagg set of Peking University, which makes me think that tagg is carried out in accordance with the standards of this tagg set, and "nr" in it represents the name of a person. What part of speech standard does huqie.txt make part of speech tagging according to?

**Comment by KevinHuSh** [comment]
![image](https://github.com/infiniflow/ragflow/assets/12318111/2e131f82-1d78-4f58-b832-eeb0255486fc)

**Comment by 1556900941lizerui** [comment]
Ok, thank you for your reply. Could you please send me the link explanation of the corresponding parts of speech, I hope to grasp the specific meaning of each part of speech, and because in my actual scene, I may need to adjust the weight distribution of different parts of speech in the code.

**Comment by KevinHuSh** [comment]
What about [this](https://chinesenlp.xyz/docs/pos_tagging.html).
