### ISSUE TITLE
[Bug]: Online demo server error: int() base must be >= 2 and <= 36, or 0

### ISSUE THREAD

**Issue by Manamama** [infiniflow/ragflow#1342]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

?

### Other environment information

All online, on your https://demo.ragflow.io/knowledge/dataset?id=1cec9bb2379e11ef94380242ac120006 server, account set up 3 days ago, reproducible over many days. 

Embedding model: BGE Large EN v. 1.5
Chunk method: General
Chunk token number: 128

### Actual behavior

Error:
`Process Begin At:
Tue, 02 Jul 2024 15:26:17 GMT
Process Duration:
16.75 s
Progress Msg:
Task has been received.
Start to parse.
[ERROR]Internal server error: int() base must be >= 2 and <= 36, or 0 `

### Steps to reproduce

All the source files are TXT: medium and very small. 

Two short source samples below: 
1. 
`The programmer's wife couldn't take it anymore. Every discussion with her husband turned into an argument over semantics, picking over every piece of trivial detail. One day she sent him to the grocery store to pick up some eggs. On his way out the door, she said, "While you are there, pick up milk." `

2.  
```
Program:
class Programmer:
    def __init__(self):
        self.grocery_list = ['eggs']

    def go_to_store(self):
        while True: # Infinite loop to represent the joke's endless cycle
            print("Entering the store...")
            for item in self.grocery_list:
                print(f"Picking up {item}...")
            if 'milk' not in self.grocery_list:
                print("Oh, I need to pick up milk while I'm here.")
                self.grocery_list.append('milk')
            else:
                print("I've already picked up milk, but the instruction was 'while you are there, pick up milk'...")
                print("So, do I need to pick up another milk?")
                print("This is confusing... Let's start over.")
                self.grocery_list.remove('milk') # Reset the condition to keep the loop going

husband = Programmer()
husband.go_to_store()
```

### Additional information

It errors at about 20 percent of parsing, each time.

**Comment by guoyuhao2330** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> ?
> 
> ### Other environment information
> All online, on your https://demo.ragflow.io/knowledge/dataset?id=1cec9bb2379e11ef94380242ac120006 server, account set up 3 days ago, reproducible over many days.
> 
> Embedding model: BGE Large EN v. 1.5 Chunk method: General Chunk token number: 128
> 
> ### Actual behavior
> Error: `Process Begin At: Tue, 02 Jul 2024 15:26:17 GMT Process Duration: 16.75 s Progress Msg: Task has been received. Start to parse. [ERROR]Internal server error: int() base must be >= 2 and <= 36, or 0 `
> 
> ### Expected behavior
> _No response_
> 
> ### Steps to reproduce
> All the source files are TXT: medium and very small.
> 
> Two short source samples below: 1. `The programmer's wife couldn't take it anymore. Every discussion with her husband turned into an argument over semantics, picking over every piece of trivial detail. One day she sent him to the grocery store to pick up some eggs. On his way out the door, she said, "While you are there, pick up milk." `
> 
> 
> ```
> Program:
> class Programmer:
>     def __init__(self):
>         self.grocery_list = ['eggs']
> 
>     def go_to_store(self):
>         while True: # Infinite loop to represent the joke's endless cycle
>             print("Entering the store...")
>             for item in self.grocery_list:
>                 print(f"Picking up {item}...")
>             if 'milk' not in self.grocery_list:
>                 print("Oh, I need to pick up milk while I'm here.")
>                 self.grocery_list.append('milk')
>             else:
>                 print("I've already picked up milk, but the instruction was 'while you are there, pick up milk'...")
>                 print("So, do I need to pick up another milk?")
>                 print("This is confusing... Let's start over.")
>                 self.grocery_list.remove('milk') # Reset the condition to keep the loop going
> 
> husband = Programmer()
> husband.go_to_store()
> ```
> 
> ### Additional information
> It errors at about 20 percent of parsing, each time.

fixed

**Comment by Manamama** [comment]
Works now, on same files! 🐙👏
