### ISSUE TITLE
[Bug]: When I use the "RAPTOR to enhance retrieval" feature, it reports an error "Model(qwen-plus) not authorized" while parsing the file.

### ISSUE THREAD

**Issue by laoLemon** [infiniflow/ragflow#1352]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/73423553/f324d036-6400-4470-934b-f31a8b31d7b3)
If I use RAPTOR to enhance retrieval, I encounter this error, but it does not occur when it is disabled.
![企业微信截图_1719984174538](https://github.com/infiniflow/ragflow/assets/73423553/d381709e-4859-45bc-929a-11cd518581fc)
I suspect that qwen-plus is being called here. 

### Steps to reproduce

```Markdown
In Model Provides. I just add Ollama and OpenAI. Using text-embedding-ada-002 as Embedding model.
```

**Comment by laoLemon** [comment]
I suspect that the qwen-plus model is being called at line 59 in the rag/raptor.py file. I hope that RAPTOR should enhance retrieval without unauthorized model errors.

**Comment by cyhasuka** [comment]
Same issues. I'm using Ollama models for inference, but RAPTOR doesn't seem to automatically switch to them.

**Comment by cyhasuka** [comment]
Same issues. I'm using Ollama models for inference, but RAPTOR doesn't seem to automatically switch to them. @KevinHuSh

**Comment by KevinHuSh** [comment]
Raptor used LLM in system settings.
![image](https://github.com/infiniflow/ragflow/assets/12318111/632816ea-e2be-4f32-bafb-15d59d66271e)

**Comment by laoLemon** [comment]
> Raptor used LLM in system settings. ![image](https://private-user-images.githubusercontent.com/12318111/345667425-632816ea-e2be-4f32-bafb-15d59d66271e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTgyNDYsIm5iZiI6MTcyMDA1Nzk0NiwicGF0aCI6Ii8xMjMxODExMS8zNDU2Njc0MjUtNjMyODE2ZWEtZTJiZS00ZjMyLWJhZmItMTVkNTlkNjYyNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxNTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOWM3OWQ3YTgyNTFhZTNmZTA0NGM3NTEwMzk1ODAzMGFmMmRmYTY3MjBkYmQ2NmQwZTRmYmFlNmNlZDg1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jS0Bzlx1MA3353Pu9Cg7qg1ymtrOPzIy4FFm--fEuYU)


Thank you, the issue has been resolved.
