### ISSUE TITLE
[Question]:  JinaRerank name typo

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1355]
### Describe your problem

as https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/JinaRerank/ said 

should the  rerank using Jina Reranker  to replace of the name 'JinaRerank'  is not defined?

**Comment by KevinHuSh** [comment]
Sorry. I didn't get your point. Could you be more specific?

**Comment by yangboz** [comment]
please correct  the name  to JinaReranker  as suggested.
