### ISSUE TITLE
[Question]: Is there a way to solely utilize the document parsing functionality?

### ISSUE THREAD

**Issue by ZhichengQian1** [infiniflow/ragflow#1357]
### Describe your problem

I would like to leverage the document parsing module in the RAGflow technology, but there isn't much detailed description of this part in the project. Is there a project specifically dedicated to implementing this aspect?
To replace such as RecursiveCharacterTextSplitter in Langchain

**Comment by KevinHuSh** [comment]
Please refer to rag/app/*.py.

**Comment by ZhichengQian1** [comment]
Thank you for your reply!
