### ISSUE TITLE
[Bug]: Error when building docker images from source

### ISSUE THREAD

**Issue by NBQian** [infiniflow/ragflow#1359]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

745e98e56a802583756e61ccdb679e7e723f0eef

### Actual behavior

After running the command `docker build -t infiniflow/ragflow:dev .`, I get the following error:

![image](https://github.com/infiniflow/ragflow/assets/105575052/753588ef-7136-48f3-9ddf-ce2d64105467)

### Steps to reproduce

```Markdown
`docker build -t infiniflow/ragflow:dev .`
```

**Comment by 400yk** [comment]
same problem here, any solutions?

**Comment by KevinHuSh** [comment]
Fixed. Pull the latest code.
