### ISSUE TITLE
[Bug]: pull image elasticsearch:8.11.3 failed 404 page

### ISSUE THREAD

**Issue by Kobayashi-Wang** [infiniflow/ragflow#1360]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

dev

### Actual behavior

There is a problem when i run command "docker-compose up -d", i find pulling of the es01 image always time out. So When i check the image url, it returns 404 page. What should i do? Is there other image version i can use? ty
![issue](https://github.com/infiniflow/ragflow/assets/40856458/f95f2afc-cd30-4a2a-b8db-776899918631)

### Steps to reproduce

```Markdown
install fail
```

**Comment by Kobayashi-Wang** [comment]
It may be my network problem, i can not pull image from ES official web. So i change the docker-compose.yaml file and change the ES image url to the same version in docker hub, it works and run successfully!

**Comment by adzhua** [comment]
> It may be my network problem, i can not pull image from ES official web. So i change the docker-compose.yaml file and change the ES image url to the same version in docker hub, it works and run successfully!

Can you share the ES image URL?

**Comment by Kobayashi-Wang** [comment]
> > It may be my network problem, i can not pull image from ES official web. So i change the docker-compose.yaml file and change the ES image url to the same version in docker hub, it works and run successfully!
> 
> Can you share the ES image URL?

i just replace the official source to the dockerhub source, the version is same (8.11.3). And don't forget to change the docker-compose.yaml file! Good luck!

**Comment by Kobayashi-Wang** [comment]
> > It may be my network problem, i can not pull image from ES official web. So i change the docker-compose.yaml file and change the ES image url to the same version in docker hub, it works and run successfully!
> 
> Can you share the ES image URL?

elasticsearch:8.11.3
![image](https://github.com/user-attachments/assets/68309b62-b711-4800-8c27-c5cf121b342f)
Hope helpful to u!

**Comment by adzhua** [comment]
> elasticsearch:8.11.3

thank you
