### ISSUE TITLE
[Feature Request]: .eml email file

### ISSUE THREAD

**Issue by ilyasch199** [infiniflow/ragflow#1363]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

can you add the support for .eml files 

### Describe implementation you've considered

a parser for email files

**Comment by peizimo** [comment]
The presentation parsing method does not support "Enhancing RAPTOR strategy with Recalls"，ask for help，if thus，pptx file will lose context after parsing .
![84cdc8f8d56c40104830f8dc8d32e6f7](https://github.com/user-attachments/assets/834b2d84-5bb9-478b-89b3-1dde110cd7bc)

**Comment by KevinHuSh** [comment]
fixed.

**Comment by peizimo** [comment]
> fixed.

Thanks for your reply ! 
Today I found another bug , When I run the App and RAGFlow at the same time , the App will refer to the recent history reply of the API Key Token session window used , I don't know if you understand what I'm saying , Looking forward to communicating with you !

**Comment by KevinHuSh** [comment]
The API and server share the same data source.

**Comment by peizimo** [comment]
> The API and server share the same data source.

Thanks for your reply ! Even if it's not the same conversation id, one on ragflow and one newly created conversation id through the API call interface .

I'll follow up on that one.

I'm looking forward to feeding my voice to ragflow, I wonder when it will be available .

I also hope that chat module can support translation into multiple languages for retrieval. Is there any plan to launch it .

Thank you very much!

**Comment by peizimo** [comment]
![image](https://github.com/user-attachments/assets/47da3de8-d56a-4348-9a22-6d4de1df5921)
The audio file was parsed successfully, but no block was parsed

**Comment by peizimo** [comment]
thanks for your reply , this is the current scene
![image](https://github.com/user-attachments/assets/20b6c706-01db-45be-9b43-35e2b623bd3b)

**Comment by KevinHuSh** [comment]
Demo is upgraded.
