### ISSUE TITLE
[Feature Request]: Able to cancal the selection of rerank model

### ISSUE THREAD

**Issue by 400yk** [infiniflow/ragflow#1382]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
In the chat configuration > prompt engine, the default rerank model is unselected. However when I select a model, it's impossible to cancel the selection and go back to the unselected status.
```

### Describe the feature you'd like

Add a "N/A" option at the top of dropdown list to enable this non-selection

**Comment by cyhasuka** [comment]
Just click "x" to disable it.
![image](https://github.com/infiniflow/ragflow/assets/34462246/f0006bc5-6c82-4b7b-8bde-a67689f96751)

**Comment by 400yk** [comment]
well thanks!
