### ISSUE TITLE
[Bug]: For the same PDF file, the parsing result from the source code Docker startup is inconsistent with the result parsed on the demo website (https://demo.ragflow.io/knowledge). 

### ISSUE THREAD

**Issue by yuemenglong** [infiniflow/ragflow#1389]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

v0.7.0

### Commit ID

83803a72ee16cfe72b190e7e4093a0aae5e811fe

### Other environment information

```Markdown
ubuntu linux
```

### Actual behavior

For the same file, I used the Docker startup method of the source code v0.7.0 version, specifically using the image swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:v0.7.0 to start locally. For the same PDF file, with the same configuration, it parsed into 10 chunks.

However, on the demo website (https://demo.ragflow.io/knowledge), the same file with the same configuration was parsed into 127 chunks. From the results, it is evident that the result from the demo website is more reasonable.

I would like to know why this happens. Is it because of a version inconsistency? What version is used on the demo website?

PS: I have also tried the latest code, which is the dev version of the image, and it still parsed into 10 chunks instead of the 127 chunks on the demo website.
PS: I have tried on different machines, and the results are the same.
Thank you.

对于同一个文件，我使用源码v0.7.0版本的docker启动方式，即使用swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:v0.7.0这个镜像在本地启动，对于同一个pdf文件，同样的配置，解析出10块。
但是我在demo网站上（https://demo.ragflow.io/knowledge），同样的文件，同样的配置，解析出127块。从结果看明显demo网站的结果更合理。
我想知道为什么会这样，是使用的版本不一致吗，demo网站上是什么版本。
ps:我也尝试过最新的代码，也就是dev版本的镜像，同样是10块而不是demo网站的127块。
ps:我在不同的机器上做过尝试，结果也一样
谢谢

**the pdf file for test:**
**[test_general_128.pdf](https://github.com/user-attachments/files/16106381/test_general_128.pdf)**

![Snipaste_2024-07-05_15-14-37](https://github.com/infiniflow/ragflow/assets/16472971/3b994b40-32a2-4899-ba2b-abaf5657f9b6)
![Snipaste_2024-07-05_15-14-21](https://github.com/infiniflow/ragflow/assets/16472971/3a491915-00d5-4d0d-a1a0-489848e44761)
![Snipaste_2024-07-05_15-14-01](https://github.com/infiniflow/ragflow/assets/16472971/0c1c9a4d-3128-43e8-990b-4695092b50bd)
![Snipaste_2024-07-05_15-13-23](https://github.com/infiniflow/ragflow/assets/16472971/eb35f36f-9657-4d3c-a30c-9970e1e19ffe)

### Steps to reproduce

```Markdown
Create a knowledge base.
Use all default configurations (general + 128 tokens).
Upload the test PDF.
Trigger parsing and check the results.

1. 创建一个知识库
2. 配置全部是默认（general+128token）
3. 上传测试用pdf
4. 触发解析，查看结果
```

**Comment by JinHai-CN** [comment]
The model used in DEMO site are not same as the open source code.

**Comment by yuemenglong** [comment]
> The model used in DEMO site are not same as the open source code.

Could you please let me know which model is used on the demo website? Is it a paid model?

**Comment by JinHai-CN** [comment]
It is not a open source model. If you have any needs on this, please contact us: support@infiniflow.ai

**Comment by yuemenglong** [comment]
> It is not a open source model. If you have any needs on this, please contact us: [support@infiniflow.ai](mailto:support@infiniflow.ai)

The biggest issue we are facing is that the configured token count does not seem to limit the results. Although we have set the default to 128 tokens, some of the resulting chunks far exceed this limit. Is there a solution to this problem?

**Comment by KevinHuSh** [comment]
> > It is not a open source model. If you have any needs on this, please contact us: [support@infiniflow.ai](mailto:support@infiniflow.ai)
> 
> The biggest issue we are facing is that the configured token count does not seem to limit the results. Although we have set the default to 128 tokens, some of the resulting chunks far exceed this limit. Is there a solution to this problem?

We didn't plan to split entire semantics like a paragraph just because of token number.
