### ISSUE TITLE
[Question]: In the knowledge base search test page, the retrieval is successful. However, on the chat page, it returns that nothing is found in the knowledge base, despite the same similarity parameter configuration being used.

### ISSUE THREAD

**Issue by allentern** [infiniflow/ragflow#1397]
### Describe your problem

1.Running via Docker on Ubuntu 22.04, tested for multiple days, always fetching the latest code and images.
2.Established the knowledge base using BCE embedding, uploaded PDFs, parsing was successful, search tests were successful, the first result matched.
3.Configured the chat feature, using the same parameters and models as before; with the same query, the information could not be found.

What could be the possible reasons? How should I go about troubleshooting?
Thanks

knowledge:
![微信截图_20240705222920](https://github.com/infiniflow/ragflow/assets/776181/a38e45b6-4f71-4d5b-a689-2748df1b67db)

chat:
![image](https://github.com/infiniflow/ragflow/assets/776181/aba373ec-8de1-4900-b597-5e5b37690340)

**Comment by guoyuhao2330** [comment]
you can try to change the chat model or making the prompt less limitations

**Comment by KevinHuSh** [comment]
What LLM you're using?
LLM can't relate the question and the retrievals though the related answer has been already retrived.

**Comment by Stella12121** [comment]
Hi, I had the same problem. Have you solved it yet?

**Comment by sznariOsmosis** [comment]
Hi, I had the same problem. Have you solved it yet?

**Comment by sznariOsmosis** [comment]
There are two situations, you can add code debugging information, one is to retrieve the chunk but can't answer it, this kind of large model capability problem, change to a large model with strong ability should be able to solve, one is that the relevant chunk information is not retrieved at all, or the retrieved output is other block information, of course, the output will not find the relevant content, the reason may be that RagFlow's own strategy is to retrieve according to the combination of historical problems, which may lead to the weight of the current problem to be reduced

**Comment by yuzhichang** [comment]
I agree with [sznariOsmosis](https://github.com/sznariOsmosis). Close.

**Comment by RyanFlying** [comment]
![Image](https://github.com/user-attachments/assets/893bf63e-be57-4943-921c-3ca4bca484c6)
需要在提示引擎中配置变量 knowledge
