### ISSUE TITLE
[Bug]: Add Model Providers:Azure-OpenAI error

### ISSUE THREAD

**Issue by guoyuhao2330** [infiniflow/ragflow#1402]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

ValueError('Must provide one of the `base_url` or `azure_endpoint` arguments, or the `AZURE_OPENAI_ENDPOINT` environment variable')

### Steps to reproduce

```Markdown
Add Azure-OpenAI API-Key
```

**Comment by rpkpavan** [comment]
we are also facing same issue..please help.

**Comment by rpkpavan** [comment]
Dear @KevinHuSh : Thanks for the commit. I have done gitpull and i face the following error. kindly guide

while trying to add the Azure Open API from the portal ValueError('Must provide one of the `base_url` or `azure_endpoint` arguments, or the `AZURE_OPENAI_ENDPOINT` environment variable')

on backend logs i get this error:
"LLM factory gpt-4-32k has not supported yet, switch to 'Tongyi-Qianwen/QWen' automatically, and please check the API_KEY in service_conf.yaml."

**Comment by VietNguyenHoang812** [comment]
I add a GPT-4o key to with both API key and base_url but got this message error on Web:
"Hint 102
Fail to access embedding model(azure-text-embedding-3-large) using this api key.Unsupported data type Fail to access embedding model(azure-text-embedding-3-small) using this api key.Unsupported data type Fail to access embedding model(azure-text-embedding-ada-002) using this api key.Unsupported data type"

**Comment by rendybjunior** [comment]
I still got the same issue. I suspect this is because the Azure OpenAI configuration only allows full url chat completion as parameter. Meanwhile Azure openAI has different url for each deployment model for each different tasks.

Raised new issue here https://github.com/infiniflow/ragflow/issues/2840
