### ISSUE TITLE
[Question]: How to prevent re-download of models

### ISSUE THREAD

**Issue by PROGRAMMERHAO** [infiniflow/ragflow#1404]
### Describe your problem

I am building the model locally and every time after I finish building from source and I first docker compose up, the models such as OCR models will need to be re-downloaded.

May I ask if there is a way to prevent re-downloading of the model after I change the code and build and docker compose up from there? Thks a lot! Will really appreciate if you could give some detailed guidance on that.

**Comment by KevinHuSh** [comment]
You could change dockerfile a bit. Download all the  model and add them to /root/.ragflow/, like :
ADD ./ragflow/bge-large-zh-v1.5  /root/.ragflow/bge-large-zh-v1.5
