### ISSUE TITLE
[Question]: Chunks do not make sense

### ISSUE THREAD

**Issue by wartek69** [infiniflow/ragflow#1407]
### Describe your problem

Hi,

I have a 500+ pages law document that I chunked once with the general method & default settings and once with the law method & default settings.

In both cases, when looking at the chunks, the chunk looks gibberish. The text in the pdf isn't like that.
What is the reason for this and how can this be solved?

Br
Alex
![Screenshot from 2024-07-07 22-53-55](https://github.com/infiniflow/ragflow/assets/26298408/c81d0b30-c1b3-474d-8301-efca49e7f8d9)

**Comment by guoyuhao2330** [comment]
Can you provide this law document?

**Comment by KevinHuSh** [comment]
RAGFlow parsing methods restructured the text blocks to ensure that semantic expressions are not interrupted as much as possible.

**Comment by wartek69** [comment]
You can find the document here:
[cesni22_27en_annex1_ES_TRIN23.pdf](https://github.com/user-attachments/files/16123825/cesni22_27en_annex1_ES_TRIN23.pdf)

I have the same behavior on shorter non-law documents. I can understand that text blocks are restructured, but why does the text become gibberish? eg. bAoNiCleEr doesn't make sense, it's like a concatenation of parts from different words

**Comment by KevinHuSh** [comment]
Got it. We're gona to fix it.
