### ISSUE TITLE
[Bug]:  [ERROR]Internal server error: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by acbp1379** [infiniflow/ragflow#1425]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

13

### Actual behavior

Task has been received.
Page(1~13): OCR is running...
Page(1~13): OCR finished
Page(1~13): Layout analysis finished.
Page(1~13): Table analysis finished.
Page(1~13): Text merging finished
Page(1~13): Finished slicing files(9). Start to embedding the content.
Page(1~13): Finished embedding(1.02)! Start to build index!
Page(1~13): Done!
Task has been received.
Page(13~25): OCR is running...
Page(13~25): OCR finished
Page(13~25): [ERROR]Internal server error: [Errno 5] Input/output error
Task has been received.
Page(25~37): OCR is running...
Page(25~37): OCR finished
Page(25~37): [ERROR]Internal server error: [Errno 5] Input/output error
Task has been received.

### Steps to reproduce

```Markdown
本地已经搭建好了xinference的embedding服务，然后上传一个pdf文件，解析过程中出现问题
```

**Comment by KevinHuSh** [comment]
Could you show the error stack in log?
tail -f docker/ragflow-logs/api/*.log

**Comment by acbp1379** [comment]
> Could you show the error stack in log? tail -f docker/ragflow-logs/api/*.log

I'm starting the service with the source code, and there are only four database images inside the docker

**Comment by acbp1379** [comment]
There is no error message in the service I started

**Comment by acbp1379** [comment]
> Could you show the error stack in log? tail -f docker/ragflow-logs/api/*.log

I also found that changing the parsing method didn't respond when I tapped OK. Renaming a file and clicking OK doesn't work either.

**Comment by shuaills** [comment]
Same Issue here

**Comment by shuaills** [comment]
2024-07-09T10:51:19.940495Z 9211 [Note] Aborted connection 9211 to db: 'rag_flow' user: 'root' host: '10.115.0.43' (Got an error reading communication packets)

2024-07-09T10:51:26.572197Z 9209 [Note] Aborted connection 9209 to db: 'rag_flow' user: 'root' host: '10.115.0.43' (Got an error reading communication packets)

2024-07-09T10:51:32.749717Z 9210 [Note] Aborted connection 9210 to db: 'rag_flow' user: 'root' host: '10.115.0.43' (Got an error reading communication packets)

It seems a problem with embedded data format and mysql

**Comment by KevinHuSh** [comment]
Embeddings are not stored in Mysql. It seems mysql is down, doesn't it?

**Comment by shuaills** [comment]
> Embeddings are not stored in Mysql. It seems mysql is down, doesn't it?

MySQL worked well on other tasks

**Comment by acbp1379** [comment]
> Could you show the error stack in log? tail -f docker/ragflow-logs/api/*.log

Fail put 1720a0503fac11efb10f78ac4456d7f0/1.txt: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /1720a0503fac11efb10f78ac4456d7f0/%E6%B6%88%E9%98%B2%E9%9A%90%E6%82%A3.txt, request_id: 17E13C5030E80368, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 1720a0503fac11efb10f78ac4456d7f0, object_name: 1.txt

Hello, I checked the logs and tested several times and found that the file uploading process is very unstable, the same txt file, the first upload doesn't work, a few more uploads and it uploads. In this case, it is very difficult to handle in large files, in the middle of a part of the parsing failure will report an error.
The error message seems to be related to minio. Looking forward to your reply

**Comment by shuaills** [comment]
Problem solved.

[ERROR]Internal server error: [Errno 5] Input/output error.
The reason for this error is some outdated task_executor.py are taking tasks but they won't process them. 

You need to terminate the entrypoint.sh. It has

```
for ((i=0;i<WS;i++))
do
  task_exe  &
done
```

which would restart those task_executor.py all the time, including the outdated ones. 

grep those entrypoint.sh and task_executor.py, kill them.
terminate both the backend and frontend, restart them.

Then it should work.

**Comment by acbp1379** [comment]
> Problem solved.
> 
> [ERROR]Internal server error: [Errno 5] Input/output error. The reason for this error is some outdated task_executor.py are taking tasks but they won't process them.
> 
> You need to terminate the entrypoint.sh. It has
> 
> ```
> for ((i=0;i<WS;i++))
> do
>   task_exe  &
> done
> ```
> 
> which would restart those task_executor.py all the time, including the outdated ones.
> 
> grep those entrypoint.sh and task_executor.py, kill them. terminate both the backend and frontend, restart them.
> 
> Then it should work.

Oh thanks, I solved it too, I solved it by rebooting the system

**Comment by Potato-wll** [comment]
> Problem solved.
> 
> [ERROR]Internal server error: [Errno 5] Input/output error. The reason for this error is some outdated task_executor.py are taking tasks but they won't process them.
> 
> You need to terminate the entrypoint.sh. It has
> 
> ```
> for ((i=0;i<WS;i++))
> do
>   task_exe  &
> done
> ```
> 
> which would restart those task_executor.py all the time, including the outdated ones.
> 
> grep those entrypoint.sh and task_executor.py, kill them. terminate both the backend and frontend, restart them.
> 
> Then it should work.
I didn't catch what you said, could you be more careful
