### ISSUE TITLE
[Feature Request]: Add Groq to model providers

### ISSUE THREAD

**Issue by Palvr** [infiniflow/ragflow#1432]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add Groq to model providers

### Describe implementation you've considered

Just like Ollama or XInference are used to manage the load of models

**Comment by JinHai-CN** [comment]
#1447

**Comment by paresh2806** [comment]
@JinHai-CN & @KevinHuSh 

Should I add support for Gemini APIs to model providers in the same pull request, or should I create a new pull request for it ?
