### ISSUE TITLE
[Feature Request]: Calling an already setup Graph via the API

### ISSUE THREAD

**Issue by cyhasuka** [infiniflow/ragflow#1442]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Can not calling Graph via the API right now.
```

### Describe the feature you'd like

Needs to calling the already setup Graph via API #1102

**Comment by meoqi** [comment]
I have the same requirement! Is it solved yet?

**Comment by cyhasuka** [comment]
Solved in #1888
