### ISSUE TITLE
[Question]: Use docker to deploy xinference which can't be connected in RAGFlow.

### ISSUE THREAD

**Issue by moerfei** [infiniflow/ragflow#1452]
### Describe your problem

<img width="1661" alt="image" src="https://github.com/infiniflow/ragflow/assets/27693598/54ccf0ee-f311-422d-be50-757807735490">

**Comment by ipv6next** [comment]
用这个试试：http://host.docker.internal:9997/v1

**Comment by JinHai-CN** [comment]
Guys, we intend to create an international community, so we encourage using English for communication.

**Comment by moerfei** [comment]
> 用这个试试：http://host.docker.internal:9997/v1

thank you，it works！
