### ISSUE TITLE
[Question] I was wondering why when I upload a PDF document (which contains images), and click to analyze it, the process gets stuck and no error message appears?

### ISSUE THREAD

**Issue by 13416157913** [infiniflow/ragflow#1453]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

1

### Commit ID

1

### Actual behavior

您好，请问为什么上传PDF文档后（PDF文档包含图片），点击解析，怎么一直卡住，也没有报错？
![image](https://github.com/infiniflow/ragflow/assets/20581199/33a6b0a7-bcf7-416c-aa4b-2cd383116397)

### Steps to reproduce

```Markdown
1
```

**Comment by iamlaobie** [comment]
My case  is very strange, I used master branch build image, and ragflow server can parse documents. But i down the server and run again, the server didn't work.

**Comment by KevinHuSh** [comment]
ps aux|grep task
There should be a procedure named task_executor.
Check Redis connection.

**Comment by 13416157913** [comment]
> ps aux|grep task There should be a procedure named task_executor. Check Redis connection.

![image](https://github.com/infiniflow/ragflow/assets/20581199/b65c54ac-9640-475e-8d00-97539d5777d3)

**Comment by 13416157913** [comment]
> ps aux|grep task There should be a procedure named task_executor. Check Redis connection.

the task_executor procedure exist, but task running all the time.
![image](https://github.com/infiniflow/ragflow/assets/20581199/c24b5f5a-7bf6-4299-a20d-8ae7501e8432)

**Comment by KevinHuSh** [comment]
Embedding takes time with CPU.

**Comment by 13416157913** [comment]
> Embedding takes time with CPU.

how to set Embedding with GPU?

**Comment by KevinHuSh** [comment]
Change docker-compose.ymal a bit. Refer to [this](https://docs.docker.com/compose/gpu-support/)

**Comment by chengyuansen** [comment]
same issue。
![QQ20240717-090514](https://github.com/user-attachments/assets/0a30b9f3-0978-4f29-b485-b95962a09358)

**Comment by adzhua** [comment]
> same issue。 ![QQ20240717-090514](https://private-user-images.githubusercontent.com/17844797/349318984-0a30b9f3-0978-4f29-b485-b95962a09358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTczODIsIm5iZiI6MTcyMTI5NzA4MiwicGF0aCI6Ii8xNzg0NDc5Ny8zNDkzMTg5ODQtMGEzMGI5ZjMtMDk3OC00ZjI5LWI0ODUtYjk1OTYyYTA5MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjRhOTdkZTQwZGNjNWFlOGFkODAyMzFmM2E5NDg2NDAyYTM5NTRhODdmNmIyZmVkOTYxNjk2YWZmODJlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mBiqG4FEZbD4gXHMTmpEophRCBZO9AztUrN7xbDKws0)

同样的问题，你解决了没？

**Comment by chengyuansen** [comment]
> > same issue。 ![QQ20240717-090514](https://private-user-images.githubusercontent.com/17844797/349318984-0a30b9f3-0978-4f29-b485-b95962a09358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTczODIsIm5iZiI6MTcyMTI5NzA4MiwicGF0aCI6Ii8xNzg0NDc5Ny8zNDkzMTg5ODQtMGEzMGI5ZjMtMDk3OC00ZjI5LWI0ODUtYjk1OTYyYTA5MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjRhOTdkZTQwZGNjNWFlOGFkODAyMzFmM2E5NDg2NDAyYTM5NTRhODdmNmIyZmVkOTYxNjk2YWZmODJlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mBiqG4FEZbD4gXHMTmpEophRCBZO9AztUrN7xbDKws0)
> 
> 同样的问题，你解决了没？

不要批量解析，要一个一个解析，一个解析好了之后再点击下一个。我2000+文件基本把我搞半死。
感觉批量解析应该有bug，使用批量解析了好几天总是卡死。

**Comment by adzhua** [comment]
我就1个文件，十多页，就一直卡着。发自我的荣耀手机-------- 原始邮件 --------发件人： chengyuansen ***@***.***>日期： 2024年7月18日周四 18:39收件人： infiniflow/ragflow ***@***.***>抄送： adzhua ***@***.***>, Comment ***@***.***>主    题： Re: [infiniflow/ragflow] [Question] I was wondering why when I upload a PDF document (which contains images), and click to analyze it, the process gets stuck and no error message appears? (Issue #1453)


same issue。 

同样的问题，你解决了没？

不要批量解析，要一个一个解析，一个解析好了之后再点击下一个。我2000+文件基本把我搞半死。
感觉批量解析应该有bug，使用批量解析了好几天总是卡死。

**Comment by 13416157913** [comment]
> > > same issue。 ![QQ20240717-090514](https://private-user-images.githubusercontent.com/17844797/349318984-0a30b9f3-0978-4f29-b485-b95962a09358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTczODIsIm5iZiI6MTcyMTI5NzA4MiwicGF0aCI6Ii8xNzg0NDc5Ny8zNDkzMTg5ODQtMGEzMGI5ZjMtMDk3OC00ZjI5LWI0ODUtYjk1OTYyYTA5MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjRhOTdkZTQwZGNjNWFlOGFkODAyMzFmM2E5NDg2NDAyYTM5NTRhODdmNmIyZmVkOTYxNjk2YWZmODJlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mBiqG4FEZbD4gXHMTmpEophRCBZO9AztUrN7xbDKws0)
> > 
> > 
> > 同样的问题，你解决了没？
> 
> 不要批量解析，要一个一个解析，一个解析好了之后再点击下一个。我2000+文件基本把我搞半死。 感觉批量解析应该有bug，使用批量解析了好几天总是卡死。

我这边一个一个解析也是一样的问题；

**Comment by chengyuansen** [comment]
> > > > same issue。 ![QQ20240717-090514](https://private-user-images.githubusercontent.com/17844797/349318984-0a30b9f3-0978-4f29-b485-b95962a09358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTczODIsIm5iZiI6MTcyMTI5NzA4MiwicGF0aCI6Ii8xNzg0NDc5Ny8zNDkzMTg5ODQtMGEzMGI5ZjMtMDk3OC00ZjI5LWI0ODUtYjk1OTYyYTA5MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjRhOTdkZTQwZGNjNWFlOGFkODAyMzFmM2E5NDg2NDAyYTM5NTRhODdmNmIyZmVkOTYxNjk2YWZmODJlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mBiqG4FEZbD4gXHMTmpEophRCBZO9AztUrN7xbDKws0)
> > > 
> > > 
> > > 同样的问题，你解决了没？
> > 
> > 
> > 不要批量解析，要一个一个解析，一个解析好了之后再点击下一个。我2000+文件基本把我搞半死。 感觉批量解析应该有bug，使用批量解析了好几天总是卡死。
> 
> 我这边一个一个解析也是一样的问题；

这么多人遇到了同样的问题，本质上是个bug。

**Comment by adzhua** [comment]
> Change docker-compose.ymal a bit. Refer to [this](https://docs.docker.com/compose/gpu-support/)

How to configure the Embedding to use the GPU when starting the service from source?

**Comment by cyhasuka** [comment]
> Embedding takes time with CPU.嵌入需要 CPU 时间。

This is actually a bug and has nothing to do with the CPU or GPU. Try to fix it PLZ @KevinHuSh

**Comment by yuzhichang** [comment]
0.14.0 system page show task-executor status. Have a try.

**Comment by Mr-greenplus** [comment]
ragflow:V0.13.0,我也遇到了这样的问题，卡在解析0.09%几个小时，需要重启docker才能重新正常解析。

**Comment by Mr-greenplus** [comment]
ragflow:V0.13.0,我也遇到了这样的问题，卡在解析0.09%几个小时，需要重启docker才能重新正常解析。

**Comment by benni82** [comment]
ragflow：v0.17同样碰到这个问题， 看task表实际任务已经完成，由于没有把task的process_msg同步给document表, 所以在页面看没有进度更新。 
可能是这里异常时没有释放锁导致的。
``` ragflow_server.py
def update_progress():
    lock_value = str(uuid.uuid4())
    redis_lock = RedisDistributedLock("update_progress", lock_value=lock_value, timeout=60)
    logging.info(f"update_progress lock_value: {lock_value}")
    while not stop_event.is_set():
        try:
            if redis_lock.acquire():
                DocumentService.update_progress()
                redis_lock.release()
            stop_event.wait(6)
        except Exception:
            logging.exception("update_progress exception")
```

代码修改为
```
def update_progress():
    lock_value = str(uuid.uuid4())
    redis_lock = RedisDistributedLock("update_progress", lock_value=lock_value, timeout=60)
    logging.info(f"update_progress lock_value: {lock_value}")
    while not stop_event.is_set():
        try:
            if redis_lock.acquire():
                DocumentService.update_progress()
                redis_lock.release()
            stop_event.wait(6)
        except Exception:
            logging.exception("update_progress exception")
            if redis_lock.acquired:
                redis_lock.release()
```

**Comment by conkyboy** [comment]
**Is the same issue still unresolved up to now?**
