### ISSUE TITLE
[Question]: Wechat group?

### ISSUE THREAD

**Issue by wxch198610** [infiniflow/ragflow#1454]
### Describe your problem

能建个微信或者qq群吗？方便讨论问题的，在github上手机操作不太方便呀

**Comment by cyhasuka** [comment]
## 👥 加入社区

扫二维码添加 RAGFlow 小助手，进 RAGFlow 交流群。

<p align="center">
  <img src="https://github.com/infiniflow/ragflow/assets/7248/bccf284f-46f2-4445-9809-8f1030fb7585" width=20% height=20%>
</p>

**Comment by cyhasuka** [comment]
## 👥 Join the Wechat Community

Scan the QR code to add RAGFlow assistant and enter the RAGFlow group.

<p align="center">
  <img src="https://github.com/infiniflow/ragflow/assets/7248/bccf284f-46f2-4445-9809-8f1030fb7585" width=20% height=20%>
</p>

**Comment by wxch198610** [comment]
thank you!!!
