### ISSUE TITLE
[Feature Request]: Support xinference rerank model

### ISSUE THREAD

**Issue by hwzhuhao** [infiniflow/ragflow#1455]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

support xinference rerank model

### Describe implementation you've considered

1.Create a class XInferenceRerank that inherits from Base and overrides the similarity method.
2.Add a tag to XInference during data initialization with the value TEXT RE-RANK.
3.Modify the frontend code in ollama-modal/index.tsx to add an option for rerank.

**Comment by jay-jjwu** [comment]
whis is supposed to be the url for rerank model of xinference? i got an error when i use the base url "http://<your-xinference-endpoint-domain>:9997/v1", any ideas?

**Comment by hwzhuhao** [comment]
root@pc-gpu-86-41:~# curl -X 'POST'   'http://127.0.0.1:9997/v1/rerank'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
    "model": "bge-reranker-v2-m3",
    "query": "A man is eating pasta.",
    "return_documents":"true",
    "return_len":"true",
    "documents": [
        "A man is eating food.",
        "A man is eating a piece of bread.",
        "The girl is carrying a baby.",
        "A man is riding a horse.",
        "A woman is playing violin."
    ]
  }'
{"id":"610a8724-3e96-11ef-81ce-08bfb886c012","results":[{"index":0,"relevance_score":0.999574601650238,"document":{"text":"A man is eating food."}},{"index":1,"relevance_score":0.07814773917198181,"document":{"text":"A man is eating a piece of bread."}},{"index":3,"relevance_score":0.000017700713215162978,"document":{"text":"A man is riding a horse."}},{"index":2,"relevance_score":0.0000163753629749408,"document":{"text":"The girl is carrying a baby."}},{"index":4,"relevance_score":0.00001631895975151565,"document":{"text":"A woman is playing violin."}}],"meta":{"api_version":null,"billed_units":null,"tokens":{"input_tokens":38,"output_tokens":38},"warnings":null}}

**Comment by jay-jjwu** [comment]
the xinfernece works well (as above your scripts showed), and i also did test via curl and postman, all good. But when i try to add model in offical ragflow web-page, got errors. see below screenshot.
btw, i map the port 9997 to public 4419 via router and expose to internet to test on ragflow official site. 
The url works good and tested in postman, but always failed from the ragflow web site.
is the below config correct?
![image](https://github.com/user-attachments/assets/d6c66417-a69a-4aae-b986-3025a0c1a80e)

**Comment by hwzhuhao** [comment]
the base url should be http://domain-name:4419/v1/rerank，not http://domain-name:4419/v1

**Comment by jay-jjwu** [comment]
tried again, see error below:
![image](https://github.com/user-attachments/assets/1ec7aaa7-3555-47cc-81c6-3024220a45d6)

**Comment by imaben** [comment]
+1

**Comment by hwzhuhao** [comment]
I think I know where the problem is. It occurred due to an error in the token calculation. It should be res["meta"]["tokens"]["input_tokens"] + res["meta"]["tokens"]["output_tokens"] instead of res["tokens"]["input_tokens"] + res["tokens"]["output_tokens"]

**Comment by jay-jjwu** [comment]
do you mean the codes here?
i dont have a local delpoyment, meanwhile i cannot test it. 
would you test and pull a request? 
many thanks!

![image](https://github.com/user-attachments/assets/ebc43852-8742-4ce1-bec2-b9e604bcae8c)

**Comment by hwzhuhao** [comment]
https://github.com/infiniflow/ragflow/pull/1527

**Comment by jay-jjwu** [comment]
thanks!!
