### ISSUE TITLE
[Question]: can not answer question

### ISSUE THREAD

**Issue by zhanghaiqiangshigezhu** [infiniflow/ragflow#1457]
### Describe your problem

when i create a new account and a dialogue,it can not answer, the error is follow:
![Uploading answer.jpeg…]()

**Comment by zhanghaiqiangshigezhu** [comment]
ERROR: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_ec04dcd63f2111efa14f0242ac110006]', ragflow_ec04dcd63f2111efa14f0242ac110006, index_or_alias)
it seems the es has an error

**Comment by zhanghaiqiangshigezhu** [comment]
![answer2](https://github.com/infiniflow/ragflow/assets/21963943/2f94fa22-e378-496a-be1c-0f2a678a8210)

**Comment by KevinHuSh** [comment]
I guess that it lost ES connection while parsing files. What about re-parse it?

**Comment by zhanghaiqiangshigezhu** [comment]
re-parse the documents in the knowledge base?

**Comment by KevinHuSh** [comment]
> re-parse the documents in the knowledge base?

Yes.
