### ISSUE TITLE
[Question]: Which version of deepseek-chat is used in the Online demo?

### ISSUE THREAD

**Issue by Huoxu69** [infiniflow/ragflow#1460]
### Describe your problem

![deepseek-chat](https://github.com/infiniflow/ragflow/assets/120367515/fc76b78a-b69d-4c47-a8f6-051f1d7d455f)
Which version of deepseek-chat is used in the Online demo?  I think this one is great!

**Comment by KevinHuSh** [comment]
We use SaaS provided by [deepseek](https://platform.deepseek.com/)

**Comment by Huoxu69** [comment]
> We use SaaS provided by [deepseek](https://platform.deepseek.com/)
Thanks

**Comment by Huoxu69** [comment]
Resolved
