### ISSUE TITLE
[Question]: RAG-Graph Generate-Answer with history message in chat api

### ISSUE THREAD

**Issue by SG-XM** [infiniflow/ragflow#1472]
### Describe your problem

"I have a very complex graph model, and in one of the processes, I connect an answer generation component with a human-computer interaction component. In this stage, I need to continuously ask the user questions, and each conversation requires the complete history of the dialogue to ensure that the next question does not repeat previous ones. Therefore, I want to know how many past conversations are appended with each API call? And whether any summarization is performed? Additionally, how can I append historical information? My prompt works fine with GPT-4o and can complete multi-turn questioning as required. However, in the ragglow-graph, after several rounds of dialogue, it starts asking repetitive questions. I am also using the GPT-4o model, but I cannot see the detailed OpenAPI POST body, so I cannot determine where the problem is."

**Comment by KevinHuSh** [comment]
Could you paste the picture of canvas here?

**Comment by SG-XM** [comment]
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/4bc290e5-9aa2-4b37-bc61-a584812b5a5a">
here is my canvas，in this loop gpt-4o where ask about 21 questions，but after 10+ conversation，model begin to repeat previous question，but with the same prompt in chat.openai.com,gpt-4o, it works well.

**Comment by SG-XM** [comment]
<img width="971" alt="image" src="https://github.com/user-attachments/assets/72d3d113-2fe1-4333-8e7b-ad4639f609c2">
I use this "history" param to append history message,but in fact this editabe text is prompt rather than previous conversation list.

**Comment by KevinHuSh** [comment]
> <img alt="image" width="971" src="https://private-user-images.githubusercontent.com/32589854/348114019-72d3d113-2fe1-4333-8e7b-ad4639f609c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Njc3MzgsIm5iZiI6MTcyMDc2NzQzOCwicGF0aCI6Ii8zMjU4OTg1NC8zNDgxMTQwMTktNzJkM2QxMTMtMmZlMS00MzMzLThlN2ItYWQ0NjM5ZjYwOWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA2NTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTMzNjE0MjBiYWE2NmY1NDkzMzM4OWMxZmRlOTRkZmNiOTdhMDY1MWJkYzRkMDY4MjJjNTUwZTJiNjU3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Q4WLoBd4QzkdYJwqNKgznkGKjo_oUnHQY_6ZsAJLCc"> I use this "history" param to append history message,but in fact this editabe text is prompt rather than previous conversation list.

It's useless to add history parameter.
"回答时请考虑聊天历史" that's enough.

This is about enlarge hisotry window size. We will fixed it later.|

It's meaningless to add ’message‘(人机交互) after ’begin‘ since 'begin' has already include one piece of message.

**Comment by SG-XM** [comment]
its still has problem after 12 times conversations，i have set max window size to 64，but it looks like still 12. My conversation has repeated after 12.

**Comment by SG-XM** [comment]
@KevinHuSh,excuse, in your commit，it seems just update UI design rather than really request body?
