### ISSUE TITLE
[Feature Request]: 建议增加客户端UI

### ISSUE THREAD

**Issue by zhaofangtao** [infiniflow/ragflow#1474]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
1.目前ragflow的web页面，集模型配置，帐户，知识库创建等为一体。是默认用户是开发者。但对于终端用户，是不需要也不应该暴露这些配置和创建信息，只需要为其提供一个干净的chat页面。

2. 在创建知识库时增加开关，可选择是否在chat页面显示文档来源
```

### Describe the feature you'd like

解决方案:
不同的知识库生成一个客户端url，用id区分url。
比如创建了知识库 sg6fd3b，ha2es5f
url是：https://demo.ragflow.io/chat/sg6fd3b
和 https://demo.ragflow.io/chat//ha2es5f

**Comment by KevinHuSh** [comment]
What about using this?
![image](https://github.com/user-attachments/assets/9643e2a1-6c74-4d5d-bbfe-3ea04daf52bc)

**Comment by JinHai-CN** [comment]
Use the 'preview' above, you can get what you want.

**Comment by zzlTim** [comment]
> Use the 'preview' above, you can get what you want.

请问这个preview在哪设置

**Comment by bbj677** [comment]
> > Use the 'preview' above, you can get what you want.
> 
> 请问这个preview在哪设置

请问你找到这个按钮在哪了吗？

**Comment by KevinHuSh** [comment]
![Image](https://github.com/user-attachments/assets/dff5e104-2f87-4b35-969d-e7b93000935b)
