### ISSUE TITLE
[Bug]: Failed to parse table from xlsx (ValueError)

### ISSUE THREAD

**Issue by 400yk** [infiniflow/ragflow#1475]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

80803a7

### Actual behavior

When I upload an excel file and chose "table" as parsing method, it fails to parse. Server log says "ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().", code breaks here:

Traceback (most recent call last):
  File "rag/svr/task_executor.py", line 146, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/table.py", line 228, in chunk
    if pd.isna(row[clmns[j]]):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 1576, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The table parsing, however, does work occasionally for some very simple tables. However most of the times it breaks with the above error. My colleague tried on their machines and same problem occurs.

Plz help!

### Steps to reproduce

```Markdown
Using 0.7.0 version of Ragflow
Create a knowledge base using general method.
Upload an excel file, and choose "table" method for parsing this file
Click on start, parsing failed and error can be seen in server log.
```

**Comment by KevinHuSh** [comment]
Please attach the file, and let me debug it.

**Comment by 400yk** [comment]
> Please attach the file, and let me debug it.

[1234.xlsx](https://github.com/user-attachments/files/16190690/1234.xlsx)
Here you are

**Comment by 400yk** [comment]
> Please attach the file, and let me debug it.

Here you go.
[1234.xlsx](https://github.com/user-attachments/files/16190723/1234.xlsx)

**Comment by 400yk** [comment]
> Please attach the file, and let me debug it.

So it does seem that the column head name has to be distinct, otherwise it would cause an error

**Comment by KevinHuSh** [comment]
Bingo!

**Comment by Dax-Zhang-pxy** [comment]
最终怎么解决的啊？

**Comment by skyox** [comment]
0.16.0版本，excel一样报错。
