### ISSUE TITLE
[Question]: ragflow-mysql keep waiting status

### ISSUE THREAD

**Issue by fancygeek** [infiniflow/ragflow#1478]
### Describe your problem

when i check the logs , it shows
ragflow-mysql  |  rosetta error: unhandled auxillary vector type 28

**Comment by KevinHuSh** [comment]
Is it on MAC OS?
If so, change  it to mariaDB and set MACOS=1 in docker/.env

**Comment by fancygeek** [comment]
> Is it on MAC OS? If so, change it to mariaDB and set MACOS=1 in docker/.env

I tried this, mysql container works, but same error go to ragflow-server container

**Comment by fancygeek** [comment]
Seems it's a system issue in old MACOS version, after i upgrade to Sonoma, it works, Thanks for the help
