### ISSUE TITLE
Fail put  S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /145f302e403911efaa1b78ac4456d7f0, request_id: 17E17041C09B4FA5, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, 

### ISSUE THREAD

**Issue by acbp1379** [infiniflow/ragflow#1483]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

13

### Other environment information

```Markdown
源码启动和docker启动都会报这个错,minIO启动正常。
```

### Actual behavior

上传同一个文件，有时候能上传成功，有时候上传失败。10次能有4 5次失败。
但是进入minIO的console能看到有文件

### Steps to reproduce

```Markdown
上传同一个文件，有时候能上传成功，有时候上传失败。
```

**Comment by KevinHuSh** [comment]
I guess that files in minio might be broken. I suggest that clean data of minio and re-install it.

**Comment by TeslaZY** [comment]
Meet the same situation

**Comment by TeslaZY** [comment]
> I guess that files in minio might be broken. I suggest that clean data of minio and re-install it. Or check the network, and the load of minio by command 'top'

It doesn‘t work

**Comment by lizhen-lizhen** [comment]
解决了吗。
