### ISSUE TITLE
[Question]: response error

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#1490]
### Describe your problem

![QQ截图20240712165144](https://github.com/user-attachments/assets/9c74080b-c674-4737-9575-f8df13ac97d2)
what is the reason?

**Comment by KevinHuSh** [comment]
It's caused by Ollama.
I think you need to google the error. I guess it's related to the CUDA toolkit.

**Comment by adzhua** [comment]
> It's caused by Ollama. I think you need to google the error. I guess it's related to the CUDA toolkit.

But I can get the correct results when I use curl to request.
curl http://localhost:11434/api/chat -d '{
  "model": "glm4",
  "messages": [
    { "role": "user", "content": "hi" }
  ]
}'
