### ISSUE TITLE
[Question]: Thanks for open-source! Is RAPTOR available?

### ISSUE THREAD

**Issue by HuDi2018** [infiniflow/ragflow#1493]
### Describe your problem

谢谢你们的开源，请问raptor可以用了吗？

**Comment by KevinHuSh** [comment]
Do you mean this?
![image](https://github.com/user-attachments/assets/7ed55f5c-30e9-42cd-a128-4c93a2bf2799)

**Comment by HuDi2018** [comment]
> Do you mean this? ![image](https://private-user-images.githubusercontent.com/12318111/348224148-7ed55f5c-30e9-42cd-a128-4c93a2bf2799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzYxMTcsIm5iZiI6MTcyMTAzNTgxNywicGF0aCI6Ii8xMjMxODExMS8zNDgyMjQxNDgtN2VkNTVmNWMtMzBlOS00MmNkLWExMjgtNGM5M2EyYmYyNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA5MzAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjAwNmE4NTZiZWI4MzI5OGEzMGU1M2E1MDMwODQ5MmNiYTI1ZDczMzFiNDNjZGVjYTAwM2I1YjdmN2MwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxgZL0SzjCgKGeSveKHs9r1u7B08kP0Nu5XQJ5EI6HQ)
"Yes, this is the Raptor I was referring to. However, I would like to inquire if, in your version 0.8.0(rag/raptor.py:__call__), it seems that after enabling Raptor, an index tree was not constructed; only a few summaries were generated and indexed into Elasticsearch. Are there any additional implementations elsewhere?"
