### ISSUE TITLE
[Bug]: Encounter fatal error when update a PDF file with 136 MB size.

### ISSUE THREAD

**Issue by hugefrog** [infiniflow/ragflow#1507]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0000

### Actual behavior

向知识库上传一个163MB的pdf文件出错
![屏幕截图 2024-07-15 141416](https://github.com/user-attachments/assets/5c63b996-ecdc-49c4-a242-c57f0907b793)
![无标题](https://github.com/user-attachments/assets/d997a528-4197-4730-abf3-b122ef0a823d)

### Steps to reproduce

```Markdown
1.新建一个知识库
2.上传一个163MB的pdf
```

**Comment by KevinHuSh** [comment]
Is it local deployed? Demo site doesn't support file uploading of that large  size.
Set MAX_CONTENT_LENGTH in docker/.env to a very large number.
Or check nginx.conf about the package size.

**Comment by hugefrog** [comment]
> Is it local deployed? Demo site doesn't support file uploading of that large size. Set MAX_CONTENT_LENGTH in docker/.env to a very large number. Or check nginx.conf about the package size.

I modified the value of MAX_CONTENT_LENGTH in docker/.env and client_max_body_size in nginx.conf, and the issue has been resolved. However, the number of chunks parsed from the PDF is 0. I checked and found that the PDF is not in a scanned document format.
![屏幕截图 2024-07-18 105431](https://github.com/user-attachments/assets/e2ab092b-2912-434b-a234-c5af3a7cd024)

**Comment by kevinbaby0222** [comment]
> > Is it local deployed? Demo site doesn't support file uploading of that large size. Set MAX_CONTENT_LENGTH in docker/.env to a very large number. Or check nginx.conf about the package size.
> 
> I modified the value of MAX_CONTENT_LENGTH in docker/.env and client_max_body_size in nginx.conf, and the issue has been resolved. However, the number of chunks parsed from the PDF is 0. I checked and found that the PDF is not in a scanned document format. ![屏幕截图 2024-07-18 105431](https://private-user-images.githubusercontent.com/83398604/349766356-e2ab092b-2912-434b-a234-c5af3a7cd024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTE0OTIsIm5iZiI6MTcyMjg1MTE5MiwicGF0aCI6Ii84MzM5ODYwNC8zNDk3NjYzNTYtZTJhYjA5MmItMjkxMi00MzRiLWEyMzQtYzVhZjNhN2NkMDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNGU2MmM4NDZlMjg2NDc1YzlmOTllN2I3ZGEwMmNjYWUzZjk5YWQ2ZWFjMjdkYzU4MDE1ZDhiNTBmODc4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pb6pm-pN9hg0fO-HX3WZHAjZFIW-bqpId2c-x7BtWsI)

Same problem here.
