### ISSUE TITLE
[Question]: pip install dependency at local machine

### ISSUE THREAD

**Issue by zhanghaiqiangshigezhu** [infiniflow/ragflow#1509]
### Describe your problem

is it right that i should use the requirements-dev.txt when i run the ragflow python backend application at my local machine
![requirements](https://github.com/user-attachments/assets/995e9df8-5270-4503-8702-8ce3552097f1)

**Comment by zhanghaiqiangshigezhu** [comment]
when i pip install -r requirements_dev.txt，it encounter the error as follows，i am using python3.10，should i degrade the python version to 3.9
![error_trion](https://github.com/user-attachments/assets/c66ca935-e178-4bdd-b3e8-0720badd5939)

**Comment by KevinHuSh** [comment]
Comment out lines that assert errors, and try again.

**Comment by yuzhichang** [comment]
We've replaced pip with poetry.
