### ISSUE TITLE
[Question]: what's the difference between doc_aggs and reference in api /api/completion

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#1529]
### Describe your problem

![image](https://github.com/user-attachments/assets/978bff98-5abe-4ddd-98a2-7884f3187266)
the api description makes me confuse the difference between doc_aggs and reference in the response

**Comment by HaoGuo98** [comment]
actually the chunks also contains the params in doc_aggs, except the count

**Comment by HaoGuo98** [comment]
by the way， how can i get img and doc by api
![image](https://github.com/user-attachments/assets/5dbcfaaf-76f4-43b3-9a65-4d6e66777c9d)

**Comment by KevinHuSh** [comment]
doc_aggs is for document aggregation which means how many times the doc has been hit in the result.

**Comment by KevinHuSh** [comment]
Image and document can be got by their ID.
/document/image/<id>
/document/get/<id>

**Comment by HaoGuo98** [comment]
how to deal with this response? i followed what your advise to use api like this:  http://10.60.151.130:81/v1/api/document/get/d5b742b6432211efac0d0242ac120006, and i have added the auth in header.
![image](https://github.com/user-attachments/assets/d7f9cc53-0f54-4129-b0b1-08f49ecda527)
