### ISSUE TITLE
[Question]: The ragflow mysql container keeps restarting

### ISSUE THREAD

**Issue by metasavvy** [infiniflow/ragflow#1539]
### Describe your problem

1.Using Mac
2.$ docker compose -f docker-compose-base.yml up -d 
3.Ragflow-redis and ragflow-es-01 are up, but ragflow-mysql and ragflow-minio are not up. Ragflow-minio reports an exporting port TCP 0.0.0.0:9001->0.0.0.0:0: listen TCP 0.0.0.0:9001: bind: address already in use

ragflow-mysql log：
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
runtime stack:
runtime.throw(0x524da0, 0x9)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc820030000, 0xc82003ffc0)
        /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
        /usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674
goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002a770 sp=0xc82002a768
runtime.main()
        /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002a7c0 sp=0xc82002a770
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002a7c8 sp=0xc82002a7c0
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

**Comment by KevinHuSh** [comment]
Change mysql to mariaDB and set MACOS=1 in docker/.env

**Comment by CarloCobal** [comment]
E.g in line 8 of service_conf.yaml change to: 
host: 'mysql' --> host: 'mariaDB'
Or elsewhere/other changes as well?
