### ISSUE TITLE
[Bug]: error pulling image configuration: download failed after attempts=6: dial tcp 107.181.166.244:443: i/o timeout

### ISSUE THREAD

**Issue by zxjhellow2** [infiniflow/ragflow#1543]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

no

### Commit ID

no

### Other environment information

```Markdown
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

Docker version 20.10.14, build a224086
```

### Actual behavior

下载了代码然后运行下面的语句 ：
"docker compose -f docker-compose-CN.yml up -d".
之后下载了一段时间就出现这个错误
![image](https://github.com/user-attachments/assets/7c4a1419-574d-468b-bfba-8bda69204694)

### Expected behavior

希望能够解决bug，顺利部署ragflow

### Steps to reproduce

```Markdown
没有改变原代码的任何地方。
难道是docker版本影响的吗？因为我是普通用户没有权限升级docker
```

### Additional information

无

**Comment by KevinHuSh** [comment]
This is caused by network connection. Keep trying.

**Comment by zxjhellow2** [comment]
> This is caused by network connection. Keep trying.

原来是这样，可能是因为我在中国，一些镜像网站最近连接不好，后面我继续找找可以用的镜像网址。谢谢
