### ISSUE TITLE
Can't change the directory of data

### ISSUE THREAD

**Issue by taurusduan** [infiniflow/ragflow#1544]
### Describe your problem

![1721128828970](https://github.com/user-attachments/assets/d2831825-bb61-4362-89a7-3641c2028a2f)
出现这个问题的原因是我把映射目录改成了当前目录，方便迁移。
![image](https://github.com/user-attachments/assets/1e0e8338-1410-4b44-8d32-da9bdd80a669)
非常感谢。

**Comment by KevinHuSh** [comment]
What about using absolute path?

**Comment by taurusduan** [comment]
> What about using absolute path?

还是不行。

[root@rocky ragflow]# docker-compose up -d
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
service "es01" refers to undefined volume $(pwd)/esdata01: invalid compose project
[root@rocky ragflow]#

**Comment by yuzhichang** [comment]
`./esdata01` need be at `ragflow/docker/esdata01`.
