### ISSUE TITLE
[Bug]: requirements.txt can't install successfully

### ISSUE THREAD

**Issue by voulkon** [infiniflow/ragflow#1547]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

9e3a0e4d036f80b5d59f8b40a024ac9bc5bfa797

### Actual behavior

When trying to setup proper environment using the `requirements.txt` file:
`
python3 -m pip install -r requirements.txt
`
I get:

> Collecting fasttext==0.9.2 (from -r requirements.txt (line 137))
>   Using cached fasttext-0.9.2.tar.gz (68 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [25 lines of output]
>       /home/codespace/.python/current/bin/python3: No module named pip
>       Traceback (most recent call last):
>         File "<string>", line 38, in __init__
>       ModuleNotFoundError: No module named 'pybind11'
>       
>       During handling of the above exception, another exception occurred:
>       
>       Traceback (most recent call last):
>         File "/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/home/codespace/.python/current/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/tmp/pip-build-env-5dc49cy7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "/tmp/pip-build-env-5dc49cy7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-5dc49cy7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-5dc49cy7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 72, in <module>
>         File "<string>", line 41, in __init__
>       RuntimeError: pybind11 install failed.

![image](https://github.com/user-attachments/assets/08aa04e8-d8fe-4498-8b4f-cb418a795fd4)

### Steps to reproduce

```Markdown
Open whichever command prompt (either on linux or windows) and run
`
pip install -r requirements.txt
`
```

**Comment by KevinHuSh** [comment]
Comment out failed package and try it again.

**Comment by yuzhichang** [comment]
We've replaced pip with poetry.
