### ISSUE TITLE
[Question]: error pulling image configuration: download failed after attempts=6: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by hellowJuly** [infiniflow/ragflow#1549]
### Describe your problem

<img width="757" alt="image" src="https://github.com/user-attachments/assets/3c3b22fa-531b-46f6-bf2a-dfe34570d116">
<img width="762" alt="image" src="https://github.com/user-attachments/assets/d13a2770-0644-491b-bcd0-363be4789c52">
****

**Comment by KevinHuSh** [comment]
Keep trying or using docker-compose-CN.ymal

**Comment by yuzhichang** [comment]
No resonse. Close.
