### ISSUE TITLE
[Question]: Difficultly in getting conversation_id from request module. 

### ISSUE THREAD

**Issue by dishantsonawane23** [infiniflow/ragflow#1551]
### Describe your problem

I was following the offical documentation for RESTful API, and came up with the following code,
``
import requests
import json

# URL for new conversation
new_conversation_url = "http://10.25.18.217/v1/api/new_conversation?user_id=xyz"

# Headers
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer ragflow-E1ZjcwN2VjNDI2ZDExZWZhZGU1MDI0Mm"
}

# Make the POST request to start a new conversation
new_conversation_response = requests.get(new_conversation_url, headers=headers)

# Print the response for debugging
print("New Conversation Status Code:", new_conversation_response.status_code)
print("New Conversation Response Body:", new_conversation_response.json())

# Extract conversation_id from the response
new_conversation_data = new_conversation_response.json()
conversation_id = new_conversation_data["data"]["id"]

# Check if conversation_id is retrieved
if not conversation_id:
    raise Exception("Failed to retrieve conversation ID")

# URL for the completion request
completion_url = "http://10.25.18.217/v1/api/completion"

# Data to be sent in the completion request body
completion_data = {
    "conversation_id": conversation_id,
    "messages": [
        {
            "role": "user",
            "content": "How are you doing!"
        }
    ]
}

# Convert the completion data dictionary to a JSON string
completion_json_data = json.dumps(completion_data)

# Make the POST request to get the completion response
completion_response = requests.get(completion_url, headers=headers, data=completion_json_data)

# Print the completion response
print("Completion Status Code:", completion_response.status_code)
print("Completion Response Body:", completion_response.json())
``
And Here's the response of it. 
New Conversation Status Code: 200
New Conversation Response Body: {'data': {'create_date': 'Tue, 16 Jul 2024 18:11:03 GMT', 'create_time': 1721153463816, 'dialog_id': '4413147e40e411efb7100242ac120006', 'duration': 0.0, 'id': 'c3a6e0e6439e11ef8f780242ac120006', 'message': [{'content': 'Hi! I'm your assistant, what can I do for you?', 'role': 'assistant'}], 'reference': [], 'round': 0, 'thumb_up': 0, 'tokens': 0, 'update_date': 'Tue, 16 Jul 2024 18:11:03 GMT', 'update_time': 1721153463816, 'user_id': 'xyz'}, 'retcode': 0, 'retmsg': 'success'}
Completion Status Code: 200
Completion Response Body: {'data': None, 'retcode': 100, 'retmsg': "<MethodNotAllowed '405: Method Not Allowed'>"}

**Comment by KevinHuSh** [comment]
completion_response = requests.get(completion_url, headers=headers, data=completion_json_data) =>
completion_response = requests.post(completion_url, headers=headers, data=completion_json_data)

**Comment by dishantsonawane23** [comment]
I made those changes, Here's the output from that : 
New Conversation Status Code: 200
New Conversation Response Body: {'data': {'create_date': 'Wed, 17 Jul 2024 02:49:56 GMT', 'create_time': 1721184596621, 'dialog_id': '4413147e40e411efb7100242ac120006', 'duration': 0.0, 'id': '403fded043e711efb7090242ac120006', 'message': [{'content': 'Hi! I'm your assistant, what can I do for you?', 'role': 'assistant'}], 'reference': [], 'round': 0, 'thumb_up': 0, 'tokens': 0, 'update_date': 'Wed, 17 Jul 2024 02:49:56 GMT', 'update_time': 1721184596621, 'user_id': 'xyz'}, 'retcode': 0, 'retmsg': 'success'}
Completion Status Code: 200
Traceback (most recent call last):
  File "/mnt/data1/Gradio-app/env/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data1/Gradio-app/main.py", line 50, in <module>
    print("Completion Response Body:", completion_response.json())
  File "/mnt/data1/Gradio-app/env/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dishantsonawane23** [comment]
After sending 'Stream':False I was able to get correct response, closing the thread. Thanks @KevinHuSh !
