### ISSUE TITLE
parse the PDF document, an indexError occurred

### ISSUE THREAD

**Issue by chengyuansen** [infiniflow/ragflow#1554]
1. Firstly, I selected 100 lines per page. When I clicked to parse the PDF document, an indexError occurred
2. However, when selecting 50 lines per page and performing the same operation, the document can be parsed normally
3. 
![QQ20240717-094623](https://github.com/user-attachments/assets/ec8bd445-d01f-494d-b54a-c5ef84244407)

**Comment by Seaver-Zhu** [comment]
delete the PDF document and try uploading it again

**Comment by KevinHuSh** [comment]
Could you attach the file for  me to debug?

**Comment by chengyuansen** [comment]
Sorry, this is an internal document of the company and cannot be shared
