### ISSUE TITLE
[Question]: Why is the token count fixed at 128 when using the Ollama embedding model, instead of being based on the text content?

### ISSUE THREAD

**Issue by hwzhuhao** [infiniflow/ragflow#1563]
### Describe your problem

Why is the token count fixed at 128 when using the Ollama embedding model, instead of being based on the text content?

**Comment by KevinHuSh** [comment]
It's just a mockup data since ollama doesn't return the count.

**Comment by hwzhuhao** [comment]
thanks，i try it and get the same result.
