### ISSUE TITLE
[Question]:   cross-env: not found

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#1565]
### Describe your problem

ragflow version: v0.8.0

When launching the frontend service with the 'npm run dev' command, I encounter the following error:
> dev
> cross-env UMI_DEV_SERVER_COMPRESS=none umi dev

sh: 1: cross-env: not found

How can I resolve it?

**Comment by ouyang11111** [comment]
i meet the same question.  how can i solve it? 
<img width="464" alt="1725193239239" src="https://github.com/user-attachments/assets/d1de0f98-072a-4f52-beb2-29d9230dfbc7">
