### ISSUE TITLE
[Question]: use Xinference receive more request

### ISSUE THREAD

**Issue by Zzzz1111** [infiniflow/ragflow#1568]
### Describe your problem

when i use Xinference to deploy a local chat model. in Xinference , it get more requests,no one request.
![image](https://github.com/user-attachments/assets/ce570d1f-8fa8-471c-af11-53a40d43f160)
![image](https://github.com/user-attachments/assets/8e4b1b8a-56f6-40e3-a58b-25fa8e6d360e)
![image](https://github.com/user-attachments/assets/427d46f0-931a-4770-becf-c535ab01f8f3)
![image](https://github.com/user-attachments/assets/792e4596-beb7-46a7-87bb-8ded2c688a32)

**Comment by Zzzz1111** [comment]
use Chinese prompt and English prompt , can only use Chinese prompt to make one request？

**Comment by KevinHuSh** [comment]
Disable Self-RAG in the dialog settings. You would get one request to XInference.

**Comment by zzlTim** [comment]
@zzzz1111  你好，你使用Xinference部署本地大模型，并成功添加到ragflow里面了吗？请问你的基础 Url（base url）是怎么填的
我从Xinference下载 glm4-chat-1m，并且能够进入对话的ui，成功对话，但是无法添加到ragflow里面请问你的基础 Url是怎么填的
http://host.docker.internal:9997/v1#提示 : 102#Fail to access model( glm4-chat-1m).**ERROR**: Connection error.
http://localhost:9997/v1#提示 : 102#Fail to access model( glm4-chat-1m).**ERROR**: Connection error.
http://<服务器ip>:9997/v1#和上面一样
http://<服务器ip>:9997#ERROR: <html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405NotAllowed</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html>
![1721278482534](https://github.com/user-attachments/assets/337be81b-39a1-4277-a77e-645632c693f1)
![1721278524925](https://github.com/user-attachments/assets/2778def5-473e-4903-bc5d-8ef3cedb8571)
![1721278586558](https://github.com/user-attachments/assets/048071eb-f169-41db-b395-06a75f67666b)

**Comment by Zzzz1111** [comment]
> Disable Self-RAG in the dialog settings. You would get one request to XInference.

it is fine, thanks

**Comment by Zzzz1111** [comment]
> @Zzzz1111 你好，你使用Xinference部署本地大模型，并成功添加到ragflow里面了吗？请问你的基础 Url（base url）是怎么填的 我从Xinference下载 glm4-chat-1m，并且能够进入对话的ui，成功对话，但是无法添加到ragflow里面请问你的基础 Url是怎么填的 [http://host.docker.internal:9997/v1#提示](http://host.docker.internal:9997/v1#%E6%8F%90%E7%A4%BA) : 102#Fail to access model( glm4-chat-1m).**ERROR**: Connection error. [http://localhost:9997/v1#提示](http://localhost:9997/v1#%E6%8F%90%E7%A4%BA) : 102#Fail to access model( glm4-chat-1m).**ERROR**: Connection error. http://<服务器ip>:9997/v1#和上面一样 http://<服务器ip>:9997#ERROR: <title>405 Not Allowed</title>
> 
> # 405NotAllowed
> nginx/1.18.0 (Ubuntu)
> ![1721278482534](https://private-user-images.githubusercontent.com/144675216/349793820-337be81b-39a1-4277-a77e-645632c693f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzkwMjQsIm5iZiI6MTcyMTI3ODcyNCwicGF0aCI6Ii8xNDQ2NzUyMTYvMzQ5NzkzODIwLTMzN2JlODFiLTM5YTEtNDI3Ny1hNzdlLTY0NTYzMmM2OTNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNDU4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjA3ZTU4OWI4NWM2OWIzMzg4ZmZmOWIwMjhkYzVkMTA3ZjI2MWUxNDYzODZkOWNhZjRjMmU2NDZjZjM2ZmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxWaV2JI9OlsQWWMX6I1gI_4S44_iVEXghKSXzHykLA)
> ![1721278524925](https://private-user-images.githubusercontent.com/144675216/349794071-2778def5-473e-4903-bc5d-8ef3cedb8571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzkwMjQsIm5iZiI6MTcyMTI3ODcyNCwicGF0aCI6Ii8xNDQ2NzUyMTYvMzQ5Nzk0MDcxLTI3NzhkZWY1LTQ3M2UtNDkwMy1iYzVkLThlZjNjZWRiODU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNDU4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWQ5ZTgxOGQzOGE4NDU2OGY3MzdhOWRlZjQzMzBlZTM2MjljZmE3ZDUxYWQ3MThkYWMyN2YzZjVlOWM4Nzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Ilb3HzHGRZseGiWlnDKuUSaUXLU-EqQHhlAbFukpP4)
> ![1721278586558](https://private-user-images.githubusercontent.com/144675216/349794485-048071eb-f169-41db-b395-06a75f67666b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzkwMjQsIm5iZiI6MTcyMTI3ODcyNCwicGF0aCI6Ii8xNDQ2NzUyMTYvMzQ5Nzk0NDg1LTA0ODA3MWViLWYxNjktNDFkYi1iMzk1LTA2YTc1ZjY3NjY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNDU4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTJkMjllMDU3MjdkZWM0YTQwNTZhOGIyNDAwZmYxMGU2NTIyODg2ZDE5NmYzODcwOTg4N2JmY2Y1ZDkxYjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H6Md3X6DnNY4AQPclqG8paDQFp5x8IVLJPBkc3ziHUo)

我是这样填写的，运行正常 http://host.docker.internal:9997/v1

**Comment by zzlTim** [comment]
xinference-local --host 0.0.0.0 --port 9997
xinference launch --model-name custom-glm4-chat --model-format pytorch --model-engine Transformers
你是启动本地模型，然后直接去ragflow加模型就能加上了吗？@zzzz1111
现在不管怎么改base url 都报错
“提示 : 102
Fail to access model(glm4-chat-1m).**ERROR**: Connection error.”

**Comment by Zzzz1111** [comment]
> xinference-local --host 0.0.0.0 --port 9997 xinference launch --model-name glm4-chat-1m --model-format pytorch --model-engine Transformers 你是启动本地模型，然后直接去ragflow加模型就能加上了吗？ 现在不管怎么改base url 都报错 “提示 : 102 Fail to access model(glm4-chat-1m).**ERROR**: Connection error.”

是的，我的推理引擎使用的是 vllm
