### ISSUE TITLE
[Question]: The knowledge base is also unable to parse this xlsx file

### ISSUE THREAD

**Issue by metasavvy** [infiniflow/ragflow#1576]
### Describe your problem
I use a Mac computer and start the source code service，Before uploading, it was already opened in EXCEL and 'saved as' again

1. After uploading the xlsx file to the knowledge base and downloading it from the front-end to the local computer, it cannot be opened
2. The knowledge base is also unable to parse this xlsx file, resulting in an error message zipfile BadZipFile: File is not a zip file。
3. This file cannot be previewed on the front-end either
4. Jump to the system menu and receive a MinIO Object Storage error message, error:'NoneType' object has no attribute 'bucket_exists'
![screenshot-20240717-181539](https://github.com/user-attachments/assets/8fb0ee05-373a-487a-9b78-949bbea82833)

**Comment by KevinHuSh** [comment]
Check the status of Minio server.
Do you deploy  it by using docker?
If not check conf/service_conf.ynal about the field of host.

**Comment by metasavvy** [comment]
> Check the status of Minio server. Do you deploy it by using docker? If not check conf/service_conf.ynal about the field of host.
I use the command docker compose -f docker-compose-base.yml up -d to deploy it, and I can access the Minio server at http://127.0.0.1:9022/login.
But unable to parse this xlsx file and MinIO Object Storage show error msg.

![image](https://github.com/user-attachments/assets/c92c89cd-4453-4236-bf86-7032363bf1ff)
![image](https://github.com/user-attachments/assets/becddae2-178a-4d2f-8598-53cc7bfe2f69)
