### ISSUE TITLE
[Bug]: boost should be 0.5 other than 0.05?

### ISSUE THREAD

**Issue by cauwulixuan** [infiniflow/ragflow#1580]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

can you please explain the boost set in query? https://github.com/infiniflow/ragflow/blob/58e95f76c1054c9e4003d7b267b33cd8be870fc0/rag/nlp/search.py#L85

### Steps to reproduce

```Markdown
I am not sure: https://github.com/infiniflow/ragflow/blob/58e95f76c1054c9e4003d7b267b33cd8be870fc0/rag/nlp/search.py#L85

should `bqry.boost` be 0.5 as query(for bm25) and knn are both set to `bqry.boost`.

if it's not 0.5, why set 0.05 here? can you guys explain this? Thanks.
```

**Comment by KevinHuSh** [comment]
This is an expirenced value. The similarity score of BM25 is usually much bigger than consine score of knn which is between 0 and 1.
