### ISSUE TITLE
[Question]: Need more information on how ragflow-base image is built

### ISSUE THREAD

**Issue by bsquizz** [infiniflow/ragflow#1581]
### Describe your problem

Is the source and build scripts related to the "ragflow-base" image posted publicly anywhere? https://github.com/infiniflow/ragflow/blob/747e69ef6874b475775c2f81a12af0df92b39dfe/Dockerfile#L1

I am struggling to find information about it. Thanks!

**Comment by KevinHuSh** [comment]
It's build based on ubuntu 22.04, and it's not build based on Dockerfile.

**Comment by bsquizz** [comment]
Thanks. Are there plans to share the process for building the base image with the public or is that going to remain closed? When viewing the image layers, there are several `/bin/bash` entries which do not clearly show what command was run:

```
❯ docker history infiniflow/ragflow-base:v2.0           
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
9a67b01e86ef   2 days ago     /bin/bash                                       137kB     
<missing>      6 days ago     /bin/bash                                       748kB     
<missing>      6 days ago     /bin/bash                                       126MB     
<missing>      9 days ago     /bin/bash                                       32.8MB    
<missing>      12 days ago    /bin/bash                                       8.94MB    
<missing>      3 weeks ago    /bin/bash                                       693kB     
<missing>      3 weeks ago    /bin/bash                                       2.76MB    
<missing>      4 weeks ago    /bin/bash                                       1.7MB     
<missing>      5 weeks ago    /bin/bash                                       463MB     
<missing>      6 weeks ago    /bin/bash                                       25.4MB    
<missing>      7 weeks ago    /bin/bash                                       2.48MB    
<missing>      7 weeks ago    /bin/bash                                       283MB     
<missing>      8 weeks ago    /bin/bash                                       1.68MB    
<missing>      2 months ago   RUN /bin/sh -c rm -fr /root/.cache # buildkit   0B        buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c curl -sL https://deb.nodesour…   207MB     buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c apt remove -y nodejs libnode7…   2.81MB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c export PYTHONPATH=/ragflow # …   0B        buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c python3 -c "import nltk;nltk.…   61.9MB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c pip3 install -r ./requirement…   10.4GB    buildkit.dockerfile.v0
<missing>      2 months ago   ADD requirements_dev.txt ./ # buildkit          2.19kB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c pip --version # buildkit         0B        buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c python3 -m pip install --upgr…   1.78kB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c python3 get-pip.py # buildkit    14.3MB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c wget https://bootstrap.pypa.i…   2.64MB    buildkit.dockerfile.v0
<missing>      2 months ago   RUN /bin/sh -c apt-get update &&     apt-get…   1.38GB    buildkit.dockerfile.v0
<missing>      2 months ago   WORKDIR /ragflow                                0B        buildkit.dockerfile.v0
<missing>      2 months ago   USER root                                       0B        buildkit.dockerfile.v0
<missing>      5 months ago   /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B        
<missing>      5 months ago   /bin/sh -c #(nop) ADD file:7f9a3c5a4231ed191…   77.9MB    
<missing>      5 months ago   /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      5 months ago   /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      5 months ago   /bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH     0B        
<missing>      5 months ago   /bin/sh -c #(nop)  ARG RELEASE                  0B
```

**Comment by KevinHuSh** [comment]
Nothing is in this image.
Just pip installed all requirements on Ubuntu 22.04.

**Comment by rcking** [comment]
May we assume that this command

`docker build -f Dockerfile.scratch -t infiniflow/ragflow:dev .`

will create the correct final image?

Because otherwise, relying on pulling the base image `infiniflow/ragflow-base:v2.0` withouth knowing its composition is a security no-go for my organization.

**Comment by rcking** [comment]
And by the way, when I tried

`docker build -f Dockerfile.scratch -t infiniflow/ragflow:dev .`

I got the following error:

```
61.91 npm ERR! code ENOENT
61.91 npm ERR! syscall spawn git
61.91 npm ERR! path git
61.91 npm ERR! errno -2
61.91 npm ERR! enoent Error while executing:
61.91 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/dmarcos/three-bmfont-text.git
61.91 npm ERR! enoent
61.91 npm ERR! enoent
61.91 npm ERR! enoent spawn git ENOENT
61.91 npm ERR! enoent This is related to npm not being able to find a file.
61.91 npm ERR! enoent
61.92
61.92 npm ERR! A complete log of this run can be found in:
61.92 npm ERR!     /root/.npm/_logs/2024-09-18T10_57_21_271Z-debug.log
------
Dockerfile.scratch:39
--------------------
  37 |     ENV LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/openmpi/lib:$LD_LIBRARY_PATH
  38 |     RUN rm /root/miniconda3/envs/py11/compiler_compat/ld
  39 | >>> RUN cd ./web && npm i --force && npm run build
  40 |     RUN conda run -n py11 pip install -i https://mirrors.aliyun.com/pypi/simple/ -r ./requirements.txt
  41 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd ./web && npm i --force && npm run build" did not complete successfully: exit code: 254
```

**Comment by rplescia** [comment]
> And by the way, when I tried
> 
> `docker build -f Dockerfile.scratch -t infiniflow/ragflow:dev .`
> 
> I got the following error:
> 
> ```
> 61.91 npm ERR! code ENOENT
> 61.91 npm ERR! syscall spawn git
> 61.91 npm ERR! path git
> 61.91 npm ERR! errno -2
> 61.91 npm ERR! enoent Error while executing:
> 61.91 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/dmarcos/three-bmfont-text.git
> 61.91 npm ERR! enoent
> 61.91 npm ERR! enoent
> 61.91 npm ERR! enoent spawn git ENOENT
> 61.91 npm ERR! enoent This is related to npm not being able to find a file.
> 61.91 npm ERR! enoent
> 61.92
> 61.92 npm ERR! A complete log of this run can be found in:
> 61.92 npm ERR!     /root/.npm/_logs/2024-09-18T10_57_21_271Z-debug.log
> ------
> Dockerfile.scratch:39
> --------------------
>   37 |     ENV LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/openmpi/lib:$LD_LIBRARY_PATH
>   38 |     RUN rm /root/miniconda3/envs/py11/compiler_compat/ld
>   39 | >>> RUN cd ./web && npm i --force && npm run build
>   40 |     RUN conda run -n py11 pip install -i https://mirrors.aliyun.com/pypi/simple/ -r ./requirements.txt
>   41 |
> --------------------
> ERROR: failed to solve: process "/bin/sh -c cd ./web && npm i --force && npm run build" did not complete successfully: exit code: 254
> ```

I'm having this same issue. I pull v0.11 today and tried to build it but got the same error. I think the issue is with the SSH used to retrieve the 'three-bmfont-text.git'

**Comment by rplescia** [comment]
To fix this issues change 2 things.

Line 1:
Change "FROM ubuntu:**22.04**" to "FROM ubuntu:**24.04**"

Line 22:
Change "RUN curl -sL https://deb.nodesource.com/**setup_14.x** | bash -" to "RUN curl -sL https://deb.nodesource.com/**setup_20.x** | bash -"

**Comment by yuzhichang** [comment]
`Dockerfile.scratch` is remove on main.
Here's details of how ragflow image is built out:
https://github.com/infiniflow/ragflow/?tab=readme-ov-file#-build-a-docker-image-without-embedding-models
