### ISSUE TITLE
[Bug]: can not start ragflow

### ISSUE THREAD

**Issue by Tovi163** [infiniflow/ragflow#1582]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

58e95f7

### Other environment information

```Markdown
Linux 5.10.0-1.0.0.30 #1 SMP Wed Sep 6 10:38:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.9.2009 (Core)
```

### Actual behavior

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/1efd25f6-09d6-4dbf-9c3d-a70149dcd016">

ragflow-server  | IndentationError: unindent does not match any outer indentation level
ragflow-server  | [WARNING] [2024-07-18 01:58:28,934] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
ragflow-server  | [WARNING] Load term.freq FAIL!
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/api/ragflow_server.py", line 26, in <module>
ragflow-server  |     from api.apps import app
ragflow-server  |   File "/ragflow/api/apps/__init__.py", line 96, in <module>
ragflow-server  |     client_urls_prefix = [
ragflow-server  |   File "/ragflow/api/apps/__init__.py", line 97, in <listcomp>
ragflow-server  |     register_page(path)
ragflow-server  |   File "/ragflow/api/apps/__init__.py", line 83, in register_page
ragflow-server  |     spec.loader.exec_module(page)
ragflow-server  |   File "/ragflow/api/apps/canvas_app.py", line 26, in <module>
ragflow-server  |     from graph.canvas import Canvas
ragflow-server  |   File "/ragflow/graph/canvas.py", line 25, in <module>
ragflow-server  |     from graph.component import component_class
ragflow-server  |   File "/ragflow/graph/component/__init__.py", line 13, in <module>
ragflow-server  |     from .duckduckgo import DuckDuckGo, DuckDuckGoParam
ragflow-server  |   File "/ragflow/graph/component/duckduckgo.py", line 60
ragflow-server  |     if not duck_res:
ragflow-server  |                     ^

### Steps to reproduce

```Markdown
1. download this code
2. run "cd /ragflow/docker" and run "docker compose up"
```

**Comment by Tovi163** [comment]
After Fix, this problem remay

**Comment by Tovi163** [comment]
![image](https://github.com/user-attachments/assets/d3acb7b8-aec6-47db-82cc-589e3bd2bb42)
you need to update the docker mirror
﻿
we use command "docker compose up/down" 

> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> [58e95f7](https://github.com/infiniflow/ragflow/commit/58e95f76c1054c9e4003d7b267b33cd8be870fc0)
> 
> ### Other environment information
> ```
> Linux 5.10.0-1.0.0.30 #1 SMP Wed Sep 6 10:38:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> CentOS Linux release 7.9.2009 (Core)
> ```
> 
> ### Actual behavior
> <img alt="image" width="1003" src="https://private-user-images.githubusercontent.com/15190164/349755767-1efd25f6-09d6-4dbf-9c3d-a70149dcd016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTEyMTEsIm5iZiI6MTcyMTM1MDkxMSwicGF0aCI6Ii8xNTE5MDE2NC8zNDk3NTU3NjctMWVmZDI1ZjYtMDlkNi00ZGJmLTljM2QtYTcwMTQ5ZGNkMDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNWI0MTkxZWU0NDE1MDUyMjc5ODY3MjcxMGQyMjdiMWYwMjFlMjA0MWE2MTdhYTYzOWMzNzEwNWFjODU1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C3cOOtU2kLhPlIELbEI2PyhOPLDFZmUP6pHMIVlCRvI">
> ragflow-server | IndentationError: unindent does not match any outer indentation level ragflow-server | [WARNING] [2024-07-18 01:58:28,934] [synonym.**init**] [line:40]: Realtime synonym is disabled, since no redis connection. ragflow-server | [WARNING] Load term.freq FAIL! ragflow-server | Traceback (most recent call last): ragflow-server | File "/ragflow/api/ragflow_server.py", line 26, in ragflow-server | from api.apps import app ragflow-server | File "/ragflow/api/apps/**init**.py", line 96, in ragflow-server | client_urls_prefix = [ ragflow-server | File "/ragflow/api/apps/**init**.py", line 97, in ragflow-server | register_page(path) ragflow-server | File "/ragflow/api/apps/**init**.py", line 83, in register_page ragflow-server | spec.loader.exec_module(page) ragflow-server | File "/ragflow/api/apps/canvas_app.py", line 26, in ragflow-server | from graph.canvas import Canvas ragflow-server | File "/ragflow/graph/canvas.py", line 25, in ragflow-server | from graph.component import component_class ragflow-server | File "/ragflow/graph/component/**init**.py", line 13, in ragflow-server | from .duckduckgo import DuckDuckGo, DuckDuckGoParam ragflow-server | File "/ragflow/graph/component/duckduckgo.py", line 60 ragflow-server | if not duck_res: ragflow-server | ^
> 
> ### Expected behavior
> _No response_
> 
> ### Steps to reproduce
> ```
> 1. download this code
> 2. run "cd /ragflow/docker" and run "docker compose up"
> ```
> 
> ### Additional information
> _No response_

**Comment by KevinHuSh** [comment]
Got it.
