### ISSUE TITLE
[Question]: Error 400, 'parsing comprehension', 'Unknown key for a START-OBECT in [knn]'

### ISSUE THREAD

**Issue by metasavvy** [infiniflow/ragflow#1592]
### Describe your problem

1. I can access the ES page
![image](https://github.com/user-attachments/assets/1188b94c-8bef-47f1-8896-ae2a8c20f994)
2. The knowledge base has been configured, but when creating a chat conversation, an error occurs：
![image](https://github.com/user-attachments/assets/aee127a3-eb77-4dbe-a9c8-ca687e56e06d)
![image](https://github.com/user-attachments/assets/7b6a0f93-f893-49af-86ad-58ed0d0325c4)

**Comment by KevinHuSh** [comment]
Please refer to [this](https://discuss.elastic.co/t/unknown-key-for-a-start-object-in-knn/319381/5)
Maybe caused by client version issure.
