### ISSUE TITLE
[Feature Request]: Intermediate prompts and variables needed!

### ISSUE THREAD

**Issue by AldousShou** [infiniflow/ragflow#1593]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

A great framework for RAG! I'm experiencing some issues when using ragflow. Sometimes, the final results from the LLM are not what I expected. I would like to know the intermediate steps of the prompts or the chunks retrieved from the database. Any guidance or improvements on this would be greatly appreciated.

**Comment by KevinHuSh** [comment]
The knowledge base has 'Retrieval test' part. Have a look.

**Comment by AldousShou** [comment]
Sorry! It is my fault.
