### ISSUE TITLE
[Question]: cannot open the web service

### ISSUE THREAD

**Issue by TianyuLee** [infiniflow/ragflow#1598]
### Describe your problem

Dear author:

I deploy the ragflow via the docker, command "docker logs -f ragflow-server" show the same infos as in readme
![image](https://github.com/user-attachments/assets/c27a884c-b91d-49a6-8e52-5edebf07ee02)
but i can not open the web service in "200.110.200.132:80", i can access the backend api in "200.110.200.132:9380"。
![image](https://github.com/user-attachments/assets/24b044b0-450e-4cf2-bf45-d1daf9fd9173)

Is there a problem with nginx?

**Comment by KevinHuSh** [comment]
It seems the network is not fine.

**Comment by TianyuLee** [comment]
> It seems the network is not fine.

sorry, 80 Port seems to be occupied by some other application, I change docker-compose.yml:services/ragflow/ports"80:80" to "81:80" and can access the web service via 81 port.
