### ISSUE TITLE
Graph Functionality Not Working

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#1600]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

cf4fff6

### Other environment information

```Markdown
Standard Stock Dev Environment
```

### Actual behavior

Start service, get error see included diagram.
<img width="2241" alt="image" src="https://github.com/user-attachments/assets/1999fe41-15e3-4746-92a8-8ebe05d07d0b">

### Expected behavior

Should be able to select and work with graphs.

### Steps to reproduce

```Markdown
update to current version and go to Graph tab
```

**Comment by KevinHuSh** [comment]
It only happens when the server is down.

**Comment by rhudock** [comment]
It only happens on the graph tab.  where are graphs stored?

**Comment by rhudock** [comment]
here is the error message:
Can't update token usage for e661b820031d11ef95950242ac1f0005/CHAT
[Retrieval] Knowledge bases does not support empty value.
Traceback (most recent call last):
  File "/ragflow/api/apps/canvas_app.py", line 157, in reset
    canvas = Canvas(json.dumps(user_canvas.dsl), current_user.id)
  File "/ragflow/graph/canvas.py", line 102, in __init__
    self.load()
  File "/ragflow/graph/canvas.py", line 117, in load
    param.check()
  File "/ragflow/graph/component/retrieval.py", line 46, in check
    self.check_empty(self.kb_ids, "[Retrieval] Knowledge bases")
  File "/ragflow/graph/component/base.py", line 248, in check_empty
    raise ValueError(
ValueError: [Retrieval] Knowledge bases does not support empty value.
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 110] Connection timed out
[Errno 111] Connection refused
[Errno 111] Connection refused
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (249,) + inhomogeneous part.

**Comment by KevinHuSh** [comment]
ValueError: [Retrieval] Knowledge bases does not support empty value.
The retrieval component need to be setup with knowledge base.

And the server is down, I'm confused too. This would not cause server down.

**Comment by rhudock** [comment]
I think I corrupted a graph project by putting a null value into the variable setting, is there a way to delete stored graph projects manually?

**Comment by rhudock** [comment]
figured it out deleted from user_graph table and it fixed it.
