### ISSUE TITLE
[Question]: ocr gpu

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#1606]
### Describe your problem

deepdoc/vision/ocr.py load_mode第72-76行，onnxruntime session的代码如下：
if False and ort.get_device() == "GPU":
        sess = ort.InferenceSession(
            model_file_path,
            options=options,
            providers=['CUDAExecutionProvider'])
如果装的是onnxruntime gpu版本的，这样是不是不会用GPU执行？

**Comment by yuzhichang** [comment]
Our experience is that onnxruntime-gpu has obvious memory leaking bug.
So we've deleted onnxruntime-gpu from python dependencies.
