### ISSUE TITLE
[Bug]: docker-compose missing networks: ragflow

### ISSUE THREAD

**Issue by FrenchGithubUser** [infiniflow/ragflow#1613]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

347cb61

### Actual behavior

getting the error `RuntimeError: missing networks: ragflow` when running `docker-compose-gpu.yml`

### Steps to reproduce

```Markdown
docker-compose -f docker-compose-gpu.yml up
```

**Comment by KevinHuSh** [comment]
We can't reproduce it here. Is that caused by version of docker?
