### ISSUE TITLE
[Bug]: Start up RAGFlow on Windows11 and issue error: no such key

### ISSUE THREAD

**Issue by zscxc** [infiniflow/ragflow#1614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1666

### Other environment information

```Markdown
windows 11 
python 11
```

### Actual behavior

在页面中redis报错no such key问题
![image](https://github.com/user-attachments/assets/9c165d58-e13b-4d62-b8d9-385da7e73860)

### Expected behavior

期望在显示正常

### Steps to reproduce

```Markdown
在Windows系统中运行起来后，进入页面中看到redis有问题
```

**Comment by hwzhuhao** [comment]
this is because SVR_QUEUE_RETENTION is set to 60*60，so once expired, this key will be deleted, thus resulting in a "no such key" error.

**Comment by KevinHuSh** [comment]
Yes, we are gona fix that.
