### ISSUE TITLE
[Question]: ERROR: cannot access local variable 'rerank_mdl' where it is not associated with a value

### ISSUE THREAD

**Issue by cotaa956** [infiniflow/ragflow#1622]
### Describe your problem

now in demo ragflow when first time login and adjsuting knowledge base as well as llm models, the chatbot was working well.. however, i tried it today it wasn't working well at all.. everytime it gives me this error ERROR: cannot access local variable 'rerank_mdl' where it is not associated with a value.. Also in graph workflow sometimes it works and othertimes it gives me two errors one of which is Connection error and the other is an api error

**Comment by KevinHuSh** [comment]
fixed.
