### ISSUE TITLE
Multi-Generate Prompts, Corrupting Graph Structure, Generates an Error

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#1623]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

a0c1d83

### Actual behavior

When going through the following workflow:

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/87aca191-ae51-4f32-99d9-8cba73d2a3ee">

I get this error at the completion of the generation task

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/62fc106f-6b4a-42cd-ae21-42c1a81f19ad">

It appears as the workflow is completed the database record containing the graph design details is also used to store intermediate work products.  If one after the completion of the session, saves the workflow again after the generation task is completed it properly re-saves the graph structure.  However, if one does not re-save the graph, one is left with an intermediate product which ragflow is unable to handle likely because it is in an unexpected state.

Here is a compare of the before and after:
<img width="1818" alt="image" src="https://github.com/user-attachments/assets/c7101bdb-8cfc-4a4e-baaf-a962cb9a783d">

### Expected behavior

Graph structure should not be corrupted as part of the generation process.

### Steps to reproduce

```Markdown
As depicted above create a multi-step generation workflow.  Run the workflow, and do not resave the graph after the generation workflow.  I recommend saving the json graph structure so you can compare the new and old versions to see the differences.  It should be noted, the new json structure is not invalid per se.
```

**Comment by guoyuhao2330** [comment]
These parameters are defaulted in the backend but are not initially displayed in the frontend, they do not affect the operation, and please make sure the component id is configured correctly.
