### ISSUE TITLE
[Question]: Highlights the content and the corresponding reference

### ISSUE THREAD

**Issue by wangzhen38** [infiniflow/ragflow#1630]
### Describe your problem

在回模型答复后，用户可以查看哪些回答句子是借鉴了参考内容，并能将他们以高亮对比的形式展现出来，请问这其中回答和参考内容的相似句子是如何找出来的呢，非常期待您的解答，或者贴下相关实现代码链接也可以，感谢~

**Comment by KevinHuSh** [comment]
Please refer to [this](https://github.com/infiniflow/ragflow/blob/main/rag/nlp/search.py#L221)
