### ISSUE TITLE
[Bug]: meaningless  response for table file

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#1631]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

[test1.xlsx](https://github.com/user-attachments/files/16328407/test1.xlsx)
i use table to analysis this file，but the answer is in a wrong format.
<img width="830" alt="67ba9c0d5318190aab15865d84dcad6" src="https://github.com/user-attachments/assets/747e60a4-ab5f-4354-8051-8c6dc2c6a5ec">

### Steps to reproduce

```Markdown
try the attachment
```

**Comment by KevinHuSh** [comment]
'Table' is used for parsing data from database table.
Have you tried 'general' to parse it?

**Comment by HaoGuo98** [comment]
i tried   'general'，it works for xlsx file which contains one sheet， if the xlsx file contains more than one sheet， it does not work.

**Comment by HaoGuo98** [comment]
and the question will make my local llm on xinference crush.
![image](https://github.com/user-attachments/assets/021b0fe5-71ac-42cf-8461-6fdfb9366e1e)


> 'Table' is used for parsing data from database table. Have you tried 'general' to parse it?
