### ISSUE TITLE
Mac arm docker image

### ISSUE THREAD

**Issue by godeamon** [infiniflow/ragflow#1641]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
ragflow image does not support arm.
```

### Describe the feature you'd like

arm docker image.

**Comment by KevinHuSh** [comment]
You could use [this](https://github.com/infiniflow/ragflow/blob/main/Dockerfile.arm) to build the image.
