### ISSUE TITLE
[Bug]: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

### ISSUE THREAD

**Issue by Muieay** [infiniflow/ragflow#1643]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

bf2ea04d02656d199d9f04459e53210c207a4620

### Actual behavior

When deploying docker-compose-gpu-CN.yml, the error "NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)" occurred.

### Steps to reproduce

```Markdown
When inputting the question, it would answer the question at the first time, but halfway through the answer, the error "NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)" popped up. Subsequently, this error message was directly displayed for the subsequent responses.
```

**Comment by KevinHuSh** [comment]
NCCL is a driver for connection between GPUs. It's not properly installed or the hardware doesn't support that.
So, try to use just one GPU.

**Comment by lvxinliang** [comment]
> NCCL is a driver for connection between GPUs. It's not properly installed or the hardware doesn't support that. So, try to use just one GPU.

Why should multiple cpus be supported, and how do you specify using only one GPU with docker
