### ISSUE TITLE
[Question]: can't connect to Xinfrence embdding model

### ISSUE THREAD

**Issue by wanyuks** [infiniflow/ragflow#1646]
### Describe your problem

When I use code to connect my Xinference embedding model, it works as below
![image](https://github.com/user-attachments/assets/a958786a-732f-43ba-bad4-932132347510)

But when I use web page, it can't work, there is a connection error as below
![image](https://github.com/user-attachments/assets/cc6e20d1-aa54-4ce3-8b1f-53be69c6d2ba)

**Comment by KevinHuSh** [comment]
localhost in docker container is not accessible.
