### ISSUE TITLE
[Bug]: canvas 

### ISSUE THREAD

**Issue by trundleyrg** [infiniflow/ragflow#1651]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

https://demo.ragflow.io/flow/39de889647f411ef91dd0242ac18000a

### Actual behavior

Operate the workflow on the online demo website, using the workflow template chatbot. The chat model selected is deepseek-chat, and an error occurred in the second round of conversation: ERROR: unhashable type: ‘Series’
![workflow](https://github.com/user-attachments/assets/68641ed7-3106-478a-8e20-5715ebb8bab5)
![chatsteam](https://github.com/user-attachments/assets/2e9a6217-35b5-4d14-b5da-c50a00b6db3c)

### Steps to reproduce

```Markdown
Repeatedly asking the same question, the second round of reply throws an error.
```

**Comment by trundleyrg** [comment]
![image](https://github.com/user-attachments/assets/85d5915e-cec3-40b9-9eb8-8bac0f1aafb4)
![image](https://github.com/user-attachments/assets/9f817f52-26fb-427c-88e6-7f2f785f93d8)
Due to the concatenation of multiple chunks of the pandas DataFrame without resetting the index, it is not possible to find the corresponding chunk index when adding references. Therefore, can we change index=False to index=True at line 473 in ragflow/graph/component/base.py?

**Comment by KevinHuSh** [comment]
Yes, indeed.
Bug fixed.

**Comment by tanzeel291994** [comment]
Thanks for this resolution
