### ISSUE TITLE
[Bug]: Flask Version Conflict with Flask_script

### ISSUE THREAD

**Issue by Rama-19** [infiniflow/ragflow#1687]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

infiniflow/ragflow

### Commit ID

#flaskwrongrag0001

### Other environment information

```Markdown
OS Type:CentOs stream 9
```

### Actual behavior

at first ,when i ran the ./entrypoint.sh with bash , it came out error with the manager which is not defined ,then i imported flask_script and defined manager but it appear the error with conflict between flask and flask_script:ImportError: cannot import name ‘_request_ctx_stack’ from 'flask'.after that i changed the commands.py file of flask_script: 
```
from flask import _request_ctx_stack  
```
changed to:
`from flask import request_ctx`
but it did not success :
`ImportError: cannot import name 'request_ctx' from 'flask' (/root/.conda/envs/ragflow/lib/python3.11/site-packages/flask/__init__.py)`

### Steps to reproduce

```Markdown
1,bash run the entrypoint.sh
2,define manager
3,flask version conflict with flask_script
```

**Comment by KevinHuSh** [comment]
Install the requirements. And run python scripts as the entrypoint.sh tends to do.

**Comment by Rama-19** [comment]
> Install the requirements. And run python scripts as the entrypoint.sh tends to do.

I did it,but it didn't work!But i fixed it by installing this project again in other folder!it's a strange project! 😄
