### ISSUE TITLE
[Bug]: TypeError: reduce() of empty iterable with no initial value

### ISSUE THREAD

**Issue by Ishiki-Iroha** [infiniflow/ragflow#1704]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

80d703f9c2251f199c3c5eecb75e5f576b8856a8

### Actual behavior

当我使用General方式解析一个docx文档时，出现以下错误，从而导致解析文件失败：
When I use the General method to parse a docx document, the following error occurs, causing the file parsing to fail:
```
/usr/local/lib/python3.10/dist-packages/PIL/Image.py:981: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 147, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/naive.py", line 186, in chunk
    sections, tbls = Docx()(filename, binary)
  File "/ragflow/rag/app/naive.py", line 84, in __call__
    new_line = [(line[0], reduce(concat_img, line[1])) for line in lines]
  File "/ragflow/rag/app/naive.py", line 84, in <listcomp>
    new_line = [(line[0], reduce(concat_img, line[1])) for line in lines]
TypeError: reduce() of empty iterable with no initial value
```
这并非docx文档稳定触发的错误，而是含有特定内容的docx文档，我并没有追查是哪些内容，而是将rag/app/native.py:84
This is not an error that is stably triggered by the docx document, but rather by a docx document containing specific content. I did not investigate what content it is, but instead changed rag/app/native.py:84
```
new_line = [(line[0], reduce(concat_img, line[1])) for line in lines]
```
改为：
to:
```
new_line = [(line[0], reduce(concat_img, line[1], None)) for line in lines if line[1]]
```
从而规避该问题，请问这样做是否合适？
to avoid this issue. Is this approach appropriate?

### Steps to reproduce

```Markdown
使用General方式解析特定内容的docx文件
Use the General method to parse docx file contains specific content.
```

**Comment by guoyuhao2330** [comment]
Can you provide the wrong docx file?
