### ISSUE TITLE
[Question]: how to make the synonym.json works?

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#1706]
### Describe your problem

i edit the synonym.json, but in redis, the key shows no value. Then i restart the server container, the log shows  "Realtime synonym is disabled, since no redis connection." the key still has no value. But in the system page, the redis is connected.  How to fix it?  How can i load the synonym.json?
i use the latest code in main branch.
![image](https://github.com/user-attachments/assets/43a0a8ee-017e-47f6-9e6f-6851f70b0356)

**Comment by guoyuhao2330** [comment]
you can enter the container:ragflow-server to edit the synonym.json and restart the container

**Comment by HaoGuo98** [comment]
after i restart the server container, the log shows "Realtime synonym is disabled, the redis still has nothing.But the homepage shows i connected redis.

> you can enter the container:ragflow-server to edit the synonym.json and restart the container

**Comment by KevinHuSh** [comment]
Sorry, not supported yet. It needs to change code to make realtime synonym work.
