### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rama-19** [infiniflow/ragflow#1712]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

infiniflow/ragflow

### Commit ID

#flaskwrongrag0001

### Actual behavior

![image](https://github.com/user-attachments/assets/4eb23cab-aac0-4c95-8f7e-b4cac7975856)

### Steps to reproduce

```Markdown
i update the project because i think it's wrong with version or something,but it appears this kind of issue
```

**Comment by KevinHuSh** [comment]
No clue yet.

**Comment by Rama-19** [comment]
all right,just upgrade the huggingface_hub to fix it

**Comment by ouyang11111** [comment]
run this :  pip install --upgrade huggingface_hub
