### ISSUE TITLE
[Question]: When using OCR to recognize Chinese titles, the structure appears to be duplicated.

### ISSUE THREAD

**Issue by leecj** [infiniflow/ragflow#1718]
### Describe your problem

1. When using OCR to recognize Chinese titles, the structure appears to be duplicated.
OCR识别中文标题时，结构出现重复，比如“基本规定”识别为“基基本本规规定定”
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/4dc1cc23-78d2-4dc4-9811-6878179f991d">

2. OCR Recognition Content Structure Error, Leading to Mixing of Front and Back
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/3c04fd5c-a0aa-4bc3-af8e-9d9ab31e85db">

I am using the latest official version. Is there a plan for a fix?

**Comment by leecj** [comment]
the pdf file:
[高速公路运营作业安全操作规程.pdf](https://github.com/user-attachments/files/16388364/default.pdf)

**Comment by leecj** [comment]
我已经解决了问题1，因为pdf文件中将同一文本渲染两次，以达到加粗效果
详情见[pdfplumber issues](https://github.com/jsvine/pdfplumber/issues/992)
修改page.chars=>page.dedupe_chars().chars
![image](https://github.com/user-attachments/assets/e20d16da-628a-4e3a-8f0a-5b9209236906)

**Comment by leecj** [comment]
关于问题2，我本地使用的是0.7.0版本，主要问题是内容识别为引用，被移除掉
通过下面的方式修复：
self.garbage_layouts = ["footer", "header"]
![image](https://github.com/user-attachments/assets/ca5b6777-9c77-49b7-9fbb-5e590975152e)

**Comment by KevinHuSh** [comment]
Thanks for your contribution....Fatanstic work!
