### ISSUE TITLE
[Question]: why after the end of the answer, it will turn into an error

### ISSUE THREAD

**Issue by C-SunRay** [infiniflow/ragflow#1721]
### Describe your problem

Using ubuntu in wsl2 and docker-desktop integration,
![image](https://github.com/user-attachments/assets/8c50cd3d-0489-4a55-b5c8-bcc2ae2a6722)
At first it will give a nice answer,  but at the end the error "ERROR: can only concatenate str (not "NoneType") to str" replaces the answer the it looked like this instead

**Comment by C-SunRay** [comment]
using zhipu api does not report such a problem, i guess it is the issue of moonshot kimi llm then.

**Comment by andjelicmilovan** [comment]
I have same error with openAI LLM, but with deepseek everything working fine

**Comment by tcabanski** [comment]
Also seeing this error with open AI

**Comment by hangters** [comment]
thank for your mention #1728  already fix it
