### ISSUE TITLE
[Bug]: add model vision2text

### ISSUE THREAD

**Issue by Domi31tls** [infiniflow/ragflow#1726]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

549d67e  

### Other environment information

```Markdown
Ubuntu 24.04
intel i7 32go ram, 

I use docker and ollama. 
Instance ollama is on a other pc. All connection are in a vpn.
All other models with this config work well.
```

### Actual behavior

For add a model vision to text :
![image](https://github.com/user-attachments/assets/959813c5-92f7-4037-b515-21340c156b1f)

And after, I have this message : **hint : 102
Fail to access model(mskimomadto/chat-gph-vision).fail to download the test picture**

I see in code at the ligne 188 in the file : /AI/ragflow/api/apps/llm_app.py  ... perhaps ...

Thank for your help

### Expected behavior

I want to use vision to text !

### Steps to reproduce

```Markdown
Add a new model
```

**Comment by hangters** [comment]
@Domi31tls  thanks for your mention ,already fix it

**Comment by Domi31tls** [comment]
Thanks for your reactivty.
