### ISSUE TITLE
Parsing is too much slow

### ISSUE THREAD

**Issue by cotaa956** [infiniflow/ragflow#1730]
### Describe your problem

I was trying parsing in demo for small presentation files as well as simple text files, the process is too much slow and at the end it doesn't parse, it doesn't give me the message " parsing failed" but got stuck in start to build index if using presentation chunk method and RAPTOR if using other chunk methods.
![20240728_163749](https://github.com/user-attachments/assets/a944d58a-781d-460b-a84f-22f2781d76d3)

**Comment by KevinHuSh** [comment]
The RAPTOR needs to call LLM though.
The demo is slow indeed sometime since lack of computaion resource.

**Comment by coolbix** [comment]
I'm running it on a local machine and the parsing is still *very" slow.

**Comment by shaoupipi** [comment]
The GPU on the locally deployed machine is not fully utilized; should we consider increasing its usage rate?
