### ISSUE TITLE
[Bug]: Latest code runtime failure issue

### ISSUE THREAD

**Issue by zscxc** [infiniflow/ragflow#1753]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

16667

### Other environment information

```Markdown
ubuntu
```

### Actual behavior

Encountered while running code
![image](https://github.com/user-attachments/assets/2965bd96-a9c9-4c00-a823-d9cd7a2f1ac0)
Looking at the code, it was ![image](https://github.com/user-attachments/assets/4ed878ac-0e80-4269-888d-e39b5b05960e)The problem with this

### Expected behavior

希望能够修改，并且能正常的运行

### Steps to reproduce

```Markdown
main分支运行就会遇到这个错误
```

**Comment by zheroz00** [comment]
I'm have the same issue, same line as well.

**Comment by KevinHuSh** [comment]
Fixed.
