### ISSUE TITLE
[Question]: Will the document parsing process stall when the MinIO storage space is full?

### ISSUE THREAD

**Issue by amdongyang** [infiniflow/ragflow#1762]
### Describe your problem

After parsing several documents, the following document parsing process all stall. I wonder whether the minio storage can affect parsing process
![image](https://github.com/user-attachments/assets/1b4b9e21-706f-4d5c-910c-52c94cf2aa6b)

**Comment by KevinHuSh** [comment]
It's embedding which is a slow procedure and maybe downloading models.
