### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'jina'

### ISSUE THREAD

**Issue by xia-huang-411303** [infiniflow/ragflow#1767]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

None

### Other environment information

```Markdown
windows10 + docker 4.30.0 (149282)
.env argument
RAGFLOW_VERSION=dev
```

### Actual behavior

This is what happens when the docker deployment starts

### Steps to reproduce

```Markdown
$ cd ragflow/docker
$ chmod +x ./entrypoint.sh
$ docker compose -f docker-compose-CN.yml up -d
```

### Additional information

[WARNING] Load term.freq FAIL!
[WARNING] [2024-08-01 07:05:14,989] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-08-01 07:05:14,989] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 97, in <module>
    client_urls_prefix = [
  File "/ragflow/api/apps/__init__.py", line 98, in <listcomp>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 84, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/api_app.py", line 27, in <module>
    from api.db.services.dialog_service import DialogService, chat
  File "/ragflow/api/db/services/dialog_service.py", line 25, in <module>
    from api.db.services.llm_service import LLMService, TenantLLMService, LLMBundle
  File "/ragflow/api/db/services/llm_service.py", line 18, in <module>
    from rag.llm import EmbeddingModel, CvModel, ChatModel, RerankModel, Seq2txtModel
  File "/ragflow/rag/llm/__init__.py", line 17, in <module>
    from .chat_model import *
  File "/ragflow/rag/llm/chat_model.py", line 31, in <module>
    from rag.svr.jina_server import Prompt,Generation
  File "/ragflow/rag/svr/jina_server.py", line 1, in <module>
    from jina import Deployment
ModuleNotFoundError: No module named 'jina'
[WARNING] [2024-08-01 07:05:21,979] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.

**Comment by xia-huang-411303** [comment]
log i posted is result of `$ docker logs -f ragflow-server`
ragflow-server version: dev
Last pushed 7 hours ago by infiniflow
Digest	625a88f9666a

**Comment by death4444** [comment]
+1

**Comment by hangters** [comment]
@xia-huang-411303 thanks for you mention,it will be fixed soon

**Comment by ysf-gd** [comment]
+1 解决了吗？

**Comment by kevinbaby0222** [comment]
Same error.

**Comment by KevinHuSh** [comment]
Fixed.

**Comment by ysf-gd** [comment]
> Fixed.

How did you fix it?

**Comment by xia-huang-411303** [comment]
I suggest changing 'RAGFLOW_VERSION=dev' in the './docker/.env 'file to' RAGFLOW_VERSION=latest '
Re-use docker compose deployment, issue resolved

**Comment by death4444** [comment]
> I suggest changing 'RAGFLOW_VERSION=dev' in the './docker/.env 'file to' RAGFLOW_VERSION=latest ' Re-use docker compose deployment, issue resolved

thanks，this is right！
