### ISSUE TITLE
[Bug]:top_p is assigned to top_k

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#1769]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

latest

### Commit ID

c3b232

### Actual behavior

Why is top_p assigned to top_k on line 330 of rag/llm/chat_model.py?

### Steps to reproduce

```Markdown
Why is top_p assigned to top_k on line 330 of rag/llm/chat_model.py?
```

**Comment by KevinHuSh** [comment]
Ollama seems only accept topk.

**Comment by adzhua** [comment]
> Ollama seems only accept topk.

It can accept the top_p parameter; I’ve tested it.
reference link: https://github.com/ollama/ollama/blob/ce1fb4447efc9958dcf279f7eb2ae6941bec1220/examples/python-json-datagenerator/readme.md?plain=1#L45
