### ISSUE TITLE
[Bug]: show the network error alert when upload large file failed.

### ISSUE THREAD

**Issue by Chunshan-Theta** [infiniflow/ragflow#1782]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

240802twncutheta

### Actual behavior

I got the network error alert when trying to upload the files.
![large file -0](https://github.com/user-attachments/assets/9ab6a587-9832-4a80-87df-c86ab671c25e)

I checked the dev tool, and the true reason is the file's size is too large
![large file -1](https://github.com/user-attachments/assets/960949b3-62b7-40e9-9783-bba7856d0e4c)

1. Maybe the alert needs to update the text?
2. Do We have another way could upload large files?

### Steps to reproduce

```Markdown
upload a class textbook.
```

**Comment by KevinHuSh** [comment]
Check the nginx configuration.
BTW, demo site didn't support file larger than 10M.

**Comment by Chunshan-Theta** [comment]
the alert text had already changed! thank you for your quick action.
![large file -2](https://github.com/user-attachments/assets/191fb494-7d15-4778-8425-a9b255488954)

I followed your tips on updating the configuration of nginx.
nginx.conf:
![large file -3](https://github.com/user-attachments/assets/3187d156-3668-4d00-8647-43ef06195de5)
In container:
![large file -4](https://github.com/user-attachments/assets/2c31b353-fb25-4422-8146-30a57751af69)

but still show the 403 error

**Comment by KevinHuSh** [comment]
Set MAX_CONTENT_LENGTH=1000000000 in docker/.env

**Comment by Chunshan-Theta** [comment]
![large file -7](https://github.com/user-attachments/assets/07fdd914-0391-4794-bf87-565178b131bc)
added, But I am sorry it did not work.
Error 413 was returned.

**Comment by Chunshan-Theta** [comment]
I added it in docker-compose.yml, It work :)

![large file -8](https://github.com/user-attachments/assets/2b8e1009-87cf-4e73-901b-92e1ad870a9b)
