### ISSUE TITLE
what's the relationship between dialog and conversation in API references level?

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1786]
### Describe your problem

as titled.

for example get   http://192.168.0.21/v1/dialog/get?dialog_id=5279ed42353311ef85c20242ac120006   at first,  then post http://192.168.0.21/v1/conversation/completion ?

**Comment by yangboz** [comment]
or any post form data example will be greatly appreciated.

**Comment by KevinHuSh** [comment]
N conversations could belong to one dialog.
'Belong' means that all chats(conversation) use the setting of the dialog.
