### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Palvr** [infiniflow/ragflow#1791]
### Describe your problem

Hi team, I am a beginner user. Thank you for your patience and effort.
I'm encountering an issue while testing large prompts with different LLM models.
When I input a 2400-word prompt directly into the model on Ollama, I receive a response without problems. However, when I attempt the same query using Ragflow, I get an error code. 
Given that on this test im not using RAG methodology and only combines user and system prompts, is there a reason why Ragflow might have a lower token limit for queries compared to direct model consumption? 
What could be causing this discrepancy in handling large prompts between the two approaches?
My tests were using Qwen2 and Llama3.1., the 8b variants.

![Issue](https://github.com/user-attachments/assets/195db495-9376-4bdd-9447-e83e1b95ca9a)

**Comment by KevinHuSh** [comment]
It seems there may be some special terms.
Could you paste the entire message here?

**Comment by yuzhichang** [comment]
No response in 8 weeks. Close.
