### ISSUE TITLE
[Question]: How to use Gemini api in RAGflow

### ISSUE THREAD

**Issue by Lycnkd** [infiniflow/ragflow#1797]
### Discussed in https://github.com/infiniflow/ragflow/discussions/1796

<div type='discussions-op-text'>

<sup>Originally posted by **Lycnkd** August  3, 2024</sup>
It is mentioned in doc of RAGflow that google Gemini api has been supported. However, I have checked it in Model Providers page from the running docker image and also the service_conf.yaml file and neither of them indicate the availability of Gemini api. So I just want to ask for a hand about how to use Gemini api in RAGflow.
![屏幕截图 2024-08-03 001713](https://github.com/user-attachments/assets/9390516f-efac-4515-a579-b21a495f7cc9)
</div>

**Comment by hangters** [comment]
Hi @Lycnkd   update your ragflow version to the last or dev . 
![屏幕截图_5-8-2024_114553_ragflow io](https://github.com/user-attachments/assets/d81eea1c-0302-4942-a531-e1d31b9b8144)

**Comment by Lycnkd** [comment]
Thanks for answering, it works! And I think gemini only appears in a RAGflow dev version.
