### ISSUE TITLE
[Question]: Can't update token usage for cc28c3f250ae11ef9584acde48001122/EMBEDDING

### ISSUE THREAD

**Issue by fuhao009** [infiniflow/ragflow#1803]
### Describe your problem

    def encode_queries(self, query: str):
        emd, used_tokens = self.mdl.encode_queries(query)
        if not TenantLLMService.increase_usage(
                self.tenant_id, self.llm_type, used_tokens):
            database_logger.error(
                "Can't update token usage for {}/EMBEDDING".format(self.tenant_id))
        return emd, used_tokens

**Comment by hangters** [comment]
hi @fuhao009  thanks for mention that. This seems to be because there are no records of the local embedding model in the data table. This will not affect the usage, and we will fix it.
