### ISSUE TITLE
[Question]: Why knn instead of ann

### ISSUE THREAD

**Issue by Ishiki-Iroha** [infiniflow/ragflow#1815]
### Describe your problem

I noticed that ES is currently using KNN, but I see that it now supports the ANN algorithm. If you don't mind, could you please share the reasons for not using ANN? Thank you!

**Comment by KevinHuSh** [comment]
KNN is more computationally expensive and more accurate which is a prerequisite to adapt ANN which is less accurate in my point of view.
Only if KNN is good enough, then, we consider more efficient way to do it.
