### ISSUE TITLE
[Bug]: ModuleNotFoundError("No module named 'graph'")

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#1816]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

5650442  

### Actual behavior

I get this error when trying to run a graph workflow: ModuleNotFoundError("No module named 'graph'")

### Expected behavior

Not get a Module Not Found.

### Steps to reproduce

```Markdown
Run a graph workflow
```

**Comment by KevinHuSh** [comment]
Pull the latest version of docker image which is of dev version.

**Comment by rhudock** [comment]
I pulled: docker pull infiniflow/ragflow:dev
however, I still encounter the same issue.

**Comment by bingyunsky** [comment]
The latest version of docker image of dev version error。
File "/ragflow/agent/component/__init__.py", line 23, in component_class
    m = importlib.import_module("graph.component")
No module named 'graph'

**Comment by Ishiki-Iroha** [comment]
Have you tried building from source?
