### ISSUE TITLE
[Bug]: 我在对话时会出现错误

### ISSUE THREAD

**Issue by xs818818** [infiniflow/ragflow#1820]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

ERROR: Dealer._add_filters() missing 1 required positional argument: 'req'

### Commit ID

ERROR: Dealer._add_filters() missing 1 required positional argument: 'req'

### Actual behavior

ERROR: Dealer._add_filters() missing 1 required positional argument: 'req'

### Steps to reproduce

```Markdown
ERROR: Dealer._add_filters() missing 1 required positional argument: 'req'
```

**Comment by yebei199** [comment]
why close, same error

**Comment by 20070951** [comment]
same error
