### ISSUE TITLE
[Bug]: Knowledge Graph mode failed while parsing 

### ISSUE THREAD

**Issue by AAlexDing** [infiniflow/ragflow#1828]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

?

### Other environment information

```Markdown
online demo server
```

### Actual behavior

![微信图片_20240806180214](https://github.com/user-attachments/assets/00496cd4-c87d-4b4d-aa0e-8ad8646a1e4b)

Process Begin At:
Tue, 06 Aug 2024 16:51:00 GMT
Process Duration:
3805.33 s
Progress Msg:
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.
Task has been received.

### Steps to reproduce

```Markdown
1.Create KB
Language:Chinese
Embedding model：text-embedding-3-large
Chunk method:KG
Entity types: default

2.Add file:  1_《车库建筑设计规范》JGJ 100-2015.md

3.Click parse button
```

### Additional information

[1_《车库建筑设计规范》JGJ 100-2015.md](https://github.com/user-attachments/files/16508726/1_.JGJ.100-2015.md)

**Comment by KevinHuSh** [comment]
what's the error message?

**Comment by cyhasuka** [comment]
> what's the error message?
Same Issues. BTW, There is no error message at all, the parse success rate is very low, you have to reboot repeatedly to have a chance of success.
Use the following command to view the log:
`tail -f logs/api/*.log`

**Comment by cyhasuka** [comment]
> what's the error message?

Same Issues. BTW, There is no error message at all, the parse success rate is very low, you have to reboot repeatedly to have a chance of success.
Use the following command to view the log:
`tail -f logs/api/*.log`

**Comment by AAlexDing** [comment]
> what's the error message?

In the web logs, there is only the repeated message 'Task has been received.' with no other error messages.
I have only tested it in the [online service](https://demo.ragflow.io); I haven't tested the local deployment method, and I can't see the logs in the backend.

**Comment by KevinHuSh** [comment]
> > what's the error message?
> 
> In the web logs, there is only the repeated message 'Task has been received.' with no other error messages. I have only tested it in the [online service](https://demo.ragflow.io); I haven't tested the local deployment method, and I can't see the logs in the backend.

Redo it if it's too long.

**Comment by AAlexDing** [comment]
Solved. Thank you.

**Comment by huycke** [comment]
> Solved. Thank you.

What solved your issue? I have a similar one.

**Comment by AAlexDing** [comment]
> What solved your issue? I have a similar one.

Just redo and wait.  Before redo,set the right system model and check your API avaliability first.
