### ISSUE TITLE
[Question]: Knowledge Graph FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bingyunsky** [infiniflow/ragflow#1834]
### Describe your problem

![image](https://github.com/user-attachments/assets/ed62a536-e578-420f-9f52-7ed45a3f6d1a)
![image](https://github.com/user-attachments/assets/e0328c1a-64d9-4c4a-8a81-c0fbf63301f5)

**Comment by guoyuhao2330** [comment]
![image](https://github.com/user-attachments/assets/7af19f22-c568-4db8-84c2-fcac879b08de)

Sorry , I can't reproduce this problem, please provide more details or check your docker container.
