### ISSUE TITLE
[Bug]: Embedding error in file parsing

### ISSUE THREAD

**Issue by RELmon25** [infiniflow/ragflow#1835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

unknown

### Other environment information

```Markdown
macOS with chip Apple M2
```

### Actual behavior

1. Customize `user_default_llm` in `service_conf.yaml:`
`factory: 'OpenAI'`
  `api_key: MY_API_KEY`
2. Build Docker images and start up the server
3. Log in to RAGFlow
4. Set up knowledge base with gpt-4o as the embedding model
5. Upload file to knowledge base and start parsing

`SUCCESS` in parsing status but shows an embedding error:

`[ERROR]Embedding error:Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}`

<img width="1911" alt="image" src="https://github.com/user-attachments/assets/1ee65dfd-83c0-4d5d-93ae-21fc0fab8867">

Tried again after configuring OpenAI API key on the **Model Providers** page. The same error happened.

### Expected behavior

Succesful parsing.

### Steps to reproduce

```Markdown
See Actual behavior.
```

### Additional information

Error message:
`[ERROR]Embedding error:Error code: 403 - {'error': {'message': 'You are not allowed to generate embeddings from this model', 'type': 'invalid_request_error', 'param': None, 'code': None}}`

I've verified that my OpenAI API key works and has credit.

**Comment by TeresaUscanga** [comment]
Same issue.

**Comment by euscanga-krasamo** [comment]
Updates?

**Comment by KevinHuSh** [comment]
gpt-4o is not a embedding model. 
All the non-embedding models have been filtered out in knowledge base setting.
