### ISSUE TITLE
[Feature Request]: Enhance the user experience of Agent

### ISSUE THREAD

**Issue by tailover** [infiniflow/ragflow#1842]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Can you enhance the user experience of Agent? For example:
1. Adding the ability to view the operational status of each component that makes up the Agent, such as input and output
2. Adding corresponding backend APIs and Web APIs, such as enabling convenient conversations through Web APIs

**Comment by KevinHuSh** [comment]
Output is already there.
![image](https://github.com/user-attachments/assets/17c6a3c7-2f8d-4206-b89f-17114563b4e3)
