### ISSUE TITLE
[Bug]: AssertionError: cf9f5a6c267b11efa54d0242ac120006 empty task!

### ISSUE THREAD

**Issue by cjqyxq** [infiniflow/ragflow#1846]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

#1108

### Other environment information

```Markdown
ubutu22.04
docker build 24.0.7-0ubuntu2~22.04.1
```

### Actual behavior

It's running fine until I restart a job in 98.7%, then could no longer parse any files,time was gone,but no runner, chat was nomally with the bot.
I restart docker and restart ubutu but still fair.

### Expected behavior

Expected to parse documents again normally like usual.

### Steps to reproduce

```Markdown
Had about a document lined up to be parsed, cancelled halfway using bulk cancel.
```

### Additional information

Keep getting this on a loop, can't parse anything:
AssertionError: 6f405ed2548911ef89960242ac130004 empty task!
[WARNING] [2024-08-07 08:02:46,112] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[INFO] [2024-08-07 08:02:51,086] [_internal._log] [line:96]: 172.19.0.6 - - [07/Aug/2024 08:02:51] "GET /v1/document/list?kb_id=996ff1ea38eb11efa4df0242ac130002&page=1&page_size=10 HTTP/1.1" 200 -
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 376, in <module>
    main()
  File "/ragflow/rag/svr/task_executor.py", line 295, in main
    rows = collect()
  File "/ragflow/rag/svr/task_executor.py", line 118, in collect
    assert tasks, "{} empty task!".format(msg["id"])
AssertionError: 6f405f40548911ef89960242ac130004 empty task!

Thanks for you help!

**Comment by cjqyxq** [comment]
at last repull docker image ,and it's fine work.

**Comment by KevinHuSh** [comment]
Ignore this assertion, it will recover itself.
