### ISSUE TITLE
[Question]: How to set up network proxy for ragflow docker in order to access models such as Gemini?

### ISSUE THREAD

**Issue by Lycnkd** [infiniflow/ragflow#1847]
### Describe your problem

I have already set up VPN on my machine (Linux). However, after using docker-compose up -d or set up proxy environment in docker-compose.yml, it doesn't work for docker. I have try this same method on my windows laptop and it can successfully set up proxy for docker. Is there any difference on these two platform? And how could I set up network proxy for ragflow docker in order to access models such as Gemini?

**Comment by KevinHuSh** [comment]
No clue yet.
Try 'Clash'

**Comment by Lycnkd** [comment]
I have already started clash and then use docker compose to start RAGflow and all the database dockers but that does not work.

**Comment by Mr-brillianter** [comment]
To configure your Docker Compose setup to work with a proxy (e.g., Clash), follow these steps:

1. Update docker-compose.yml

    Add the following environment variables and extra_hosts configuration to your service in the docker-compose.yml file:

    environment:
    
    - HTTP_PROXY=http://host.docker.internal:7890
    - HTTPS_PROXY=http://host.docker.internal:7890
    - NO_PROXY=host.docker.internal
    
    extra_hosts:
    
    - host.docker.internal:host-gateway
2. Enable "Allow LAN" in Clash
    
    Ensure that the "Allow LAN" option is enabled in your Clash configuration. This is required for the proxy to route traffic properly.
    
3. Notes on host.docker.internal
    
    - The host.docker.internal hostname is only supported on Windows and macOS by default.
    - For Linux, the extra_hosts entry (host.docker.internal:host-gateway) ensures that the hostname resolves correctly.
4. Test the Configuration
      
    After updating the configuration, test the network connectivity inside the container:
    
    - Access the container:  
        docker exec -it ragflow-server /bin/bash
        
    - Install curl (if not already installed):  
        apt-get update && apt-get install -y curl
        
    - Test connectivity:
        
        - Test HTTP connectivity using curl:  
            curl -I https://www.google.com
        
        If the proxy and network are configured correctly, you should see successful responses.
