### ISSUE TITLE
[Bug]: AttributeError("'LocalAIChat' object has no attribute 'base_url'")

### ISSUE THREAD

**Issue by injet-zhou** [infiniflow/ragflow#1848]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

ragflow-server docker tag: dev

### Actual behavior

AttributeError("'LocalAIChat' object has no attribute 'base_url'")
![image](https://github.com/user-attachments/assets/1d65806b-12d9-46ad-beac-874bd933167c)

### Expected behavior

add LocalAI success

### Steps to reproduce

```Markdown
1. setting up ragflow with instructions in [doc](https://ragflow.io/docs/dev/)
2. go to http://myip
3. go to settings>LLM provider and choose LocalAI
4. fill the form
5. click "OK" button
```

**Comment by hangters** [comment]
hi @injet-zhou  thanks for mention that , it will be fixed quickly.

**Comment by hangters** [comment]
by the way, add local llm doesnot need input api_key .
