### ISSUE TITLE
[Bug]: Encounter error when building knowledge graph in RAGFlow demo site.

### ISSUE THREAD

**Issue by yuanrdwdcloudcc** [infiniflow/ragflow#1861]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.9.0

### Commit ID

无

### Other environment information

```Markdown
。
```

### Actual behavior

在demo中建立了两个Knowledge Graph类型的知识库，嵌入模型分别选择了BAAI/bge-large-zh-v1.5和azure-text-embedding-3-large，上传txt文档点击开始后，仅使用了大概500s就解析成功了(本地使用microsoft/graphrag创建图谱大概会用1个小时)，点击文档名不显示图谱预览
![image](https://github.com/user-attachments/assets/7165c4e8-38f6-49c3-8c21-b1504b47af1a)
[三国演义（改）.txt](https://github.com/user-attachments/files/16536512/default.txt)

### Expected behavior

无

### Steps to reproduce

```Markdown
无
```

### Additional information

无

**Comment by KevinHuSh** [comment]
It might be out of quota. Please set your own API-key.
