### ISSUE TITLE
DeepDoc对中文的支持怎么样

### ISSUE THREAD

**Issue by xiamulo** [infiniflow/ragflow#188]
### Describe your problem

DeepDoc对中文的支持怎么样，我看文档都是用的英文文档

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question:

Chinese is supported better than other language in term of DeepDoc. 
Chinese README will be ready recently.
