### ISSUE TITLE
used ollama but API key required.

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1882]
<img width="529" alt="Screenshot 2024-08-09 at 13 36 45" src="https://github.com/user-attachments/assets/31cc150a-b11b-49e2-83bd-c72a46ac80a7">

but got chatting  error as following:

```
ERROR: Invalid API-key provided. Please set LLM API-Key in 'User Setting -> Model Providers -> API-Key'
```

Current Repo: ragflow
Commit Id: 89004f1
Operating system: Ubuntu 24.04 (Kernel version: 6.8.0-39-generic)
CPU Type: x86_64
Memory: 62Gi
Docker Version: 24.0.7,
Python Version: 3.9.19

any database cache related, tried many times of configure operation before.

**Comment by hangters** [comment]
hi @yangboz thanks for your mention .If you are adding a local model, such as one added via ollama, the api_key can be left empty. We will address this in a future update.

**Comment by yangboz** [comment]
but this round is  ERROR: Model(qwen-plus) not authorized

**Comment by yangboz** [comment]
> but this round is ERROR: Model(qwen-plus) not authorized
> 
> <img alt="Screenshot 2024-08-09 at 14 11 35" width="691" src="https://private-user-images.githubusercontent.com/481954/356481826-4fedabec-b673-4e7b-8fac-198c63dcb383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODQyNzQsIm5iZiI6MTcyMzE4Mzk3NCwicGF0aCI6Ii80ODE5NTQvMzU2NDgxODI2LTRmZWRhYmVjLWI2NzMtNGU3Yi04ZmFjLTE5OGM2M2RjYjM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNjEyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDYyNmZjMmI5NTRkYjgwOWFmN2VlYjZjNjIxNDAzMzk2ZmFjNzVlNTQxYzBjN2NiZWFjOTQ4NDFmNWJkYmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bqzcXSbMsqa2t3nGte7coJKzO5zCzLbVAtBQmzgdtic"> actually ollama model added is llama2.

maybe here Model(qwen-plus)  is default select's option? and can not be deselected  even select to null?

**Comment by hangters** [comment]
This list displays all models, with successfully added models highlighted. If you successfully add a model using Ollama, you can scroll down with your mouse wheel to find it or type "ollama" in the selection bar to locate it.like this 
<img width="478" alt="屏幕截图 2024-08-09 143521" src="https://github.com/user-attachments/assets/7a22e0fc-11c3-4ca3-b935-4d2fd2a27dbd">

**Comment by yangboz** [comment]
> This list displays all models, with successfully added models highlighted. If you successfully add a model using Ollama, you can scroll down with your mouse wheel to find it or type "ollama" in the selection bar to locate it.like this <img alt="屏幕截图 2024-08-09 143521" width="478" src="https://private-user-images.githubusercontent.com/101850389/356489121-7a22e0fc-11c3-4ca3-b935-4d2fd2a27dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODYzNjAsIm5iZiI6MTcyMzE4NjA2MCwicGF0aCI6Ii8xMDE4NTAzODkvMzU2NDg5MTIxLTdhMjJlMGZjLTExYzMtNGNhMy1iOTM1LTRkMmZkMmEyN2RiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNjQ3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTk4ZjNhYjBiMDI2ZDg0YjQyNTkyY2M4NGZmNWVkNGMxNGZjZDgzYTJkNGVmMTIwMWE0YTYwOTczYzU0NWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.
<img width="1003" alt="Screenshot 2024-08-09 at 14 51 32" src="https://github.com/user-attachments/assets/e763ba10-3e7c-4336-9be7-8c782d91dc34">
-J3rENK9UeaMul2VA4gcaS4A_SoiJDuC6fhrRqZOCss">

then after selecting ollama/llama2 got  blank content  as uploaded .

**Comment by hangters** [comment]
This appears to be a browser rendering issue. Refreshing the browser might resolve the problem.

**Comment by yangboz** [comment]
> This appears to be a browser rendering issue. Refreshing the browser might resolve the problem.

how come?  before chatting, user should select database,  with model option , dialog option  during  those interactive  steps  may happen results to it. right ?

**Comment by gengyanlei** [comment]
main ip:192.168.0.122
other ip: 192.168.0.100
when ip100 request ip122 , error invalid api-key provided. 
but I use ollama model!
