### ISSUE TITLE
[Question]: Cannot utilize GPU even with docker-compose-gpu.yml

### ISSUE THREAD

**Issue by Lycnkd** [infiniflow/ragflow#1891]
### Describe your problem

In the parsing files and reranking phase of the chat, the GPU cannot be utilized (nvidia-smi shows 0% utilization), meaning that all models built into the Docker cannot use the GPU even after using the GPU version of the yml. I'd like to ask how this issue can be resolved? Or does ragflow have strict requirements regarding the CUDA version?

**Comment by KevinHuSh** [comment]
Utilization of GPU memory is 0, isn't it?
Are you using BCE/BGE embedding? Otherwise, GPU will not be used.

**Comment by Lycnkd** [comment]
![屏幕截图 2024-08-09 185039](https://github.com/user-attachments/assets/fdfd71fe-1cc0-4a5e-9399-f2865240b481)
I am using the BGE embedding, and I deploy a llama locally and use xinferece to incorporate it into RAGflow. However, except for llama inference, no other tasks will utilize the GPU.
