### ISSUE TITLE
[Question]: Return MinIO error to user?

### ISSUE THREAD

**Issue by Chunshan-Theta** [infiniflow/ragflow#1898]
### Describe your problem

I think maybe we could return the error to the frontend user, rather than keep the error in the log.
The user will consider the process well done when the minio failed if we don't return the error to the user.(real case: minio space is full)

![image](https://github.com/user-attachments/assets/b31e281d-4d43-4e17-9aae-e4ef0f95fc9e)

**Comment by KevinHuSh** [comment]
We will consider of that.
