### ISSUE TITLE
[Bug]: Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by 0xchaihu** [infiniflow/ragflow#190]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

6cf0889

### Actual behavior

README.md mentions:

> RAGFlow flourishes via open-source collaboration. In this spirit, we embrace diverse contributions from the community. If you would like to be a part, review our [Contribution Guidelines](https://github.com/infiniflow/ragflow/blob/main/CONTRIBUTING.md) first.

But the main branch of ragflow does not contain CONTRIBUTING.md.

![image](https://github.com/infiniflow/ragflow/assets/28855549/a8571741-4f8a-4ab7-adff-63595f6ab4bd)

### Expected behavior

CONTRIBUTING.md should exist.

### Steps to reproduce

```Markdown
NA
```

**Comment by KevinHuSh** [comment]
Fixed by #192
