### ISSUE TITLE
[Question]: Effect of GeminiAPI feature update on Repository 

### ISSUE THREAD

**Issue by vishaldwdi** [infiniflow/ragflow#1901]
### Describe your problem

I want to bring your attention to the latest update of Gemini. Gemini released its full support with "PDF Vision and Text understanding".

Let me quote from the reference, "The Gemini API and AI Studio now support PDF understanding through both text and vision. If your PDF includes graphs, images, or other non-text visual content, the model uses native multi-modal capabilities to process the PDF. You can try this out via Google AI Studio or in the Gemini API."

I am interpreting that OCR can be done through Gemini API or am I mistaken? Does it mean that RagFlow just got OCR through Google Vision by itself?

Please confirm whether if a user connects RagFlow with GeminiAPI and when the user prompts RAG of RagFlow then the API will perform OCR? If yes, then it indeed is great news.

If not, then can something be done easily to utilize this newly released capability of GeminiAPI?

Reference: https://developers.googleblog.com/en/gemini-15-flash-updates-google-ai-studio-gemini-api/

**Comment by KevinHuSh** [comment]
RAGFlow does not use Gemini to OCR since our approch is much cheeper than using LLM.

**Comment by vishaldwdi** [comment]
Please do check the updated pricing. It's very cheap now, atleast for the flash model version.

I mean wouldn't it be great to have it as an option for integrated OCR + LLM ?
