### ISSUE TITLE
[Question]: How to solve the serious memory leak

### ISSUE THREAD

**Issue by ywang-wy** [infiniflow/ragflow#1905]
### Describe your problem

Each Q&A fails to release 30M memory

**Comment by KevinHuSh** [comment]
Pain in the ass for Python applications.

**Comment by yuzhichang** [comment]
https://github.com/infiniflow/ragflow/pull/3555 introduced `TRACE_MALLOC_DELTA` and `TRACE_MALLOC_FULL`.
Please do heap profiling.

**Comment by luongphambao** [comment]
> [#3555](https://github.com/infiniflow/ragflow/pull/3555) đã được giới thiệu `TRACE_MALLOC_DELTA`và `TRACE_MALLOC_FULL`. Vui lòng thực hiện lập hồ sơ heap.

Not working ok
