### ISSUE TITLE
[Question]: I am not able to find "term.freq" file in the github repo can you send the link of that file so i can download the "term.freq" file 

### ISSUE THREAD

**Issue by narendra-bluebash** [infiniflow/ragflow#1915]
### Describe your problem

fnm = os.path.join(get_project_base_directory(), "rag/res")
self.ne, self.df = {}, {}
try:
    self.ne = json.load(open(os.path.join(fnm, "ner.json"), "r"))
except Exception as e:
    print("[WARNING] Load ner.json FAIL!")
try:
    **self.df = load_dict(os.path.join(fnm, "term.freq"))**
except Exception as e:
    print("[WARNING] Load term.freq FAIL!")

**Comment by KevinHuSh** [comment]
Ignore that warning log. It is highly related to your application domain, we do not provide this.

term.freq is a file composed of 2 columns(term\tfrequency) that split by TAB. It is used as a suppliment feature to calculate term weight which is strongly depends on specific domain, say, it is very different from medical to manufacture.

**Comment by narendra-bluebash** [comment]
can you provide some example of 
term.freq file composed of 2 columns(term\tfrequency) that split by TAB.
