### ISSUE TITLE
[Bug]: Error on chat api，<BadRequestKeyError '400: Bad Request'>

### ISSUE THREAD

**Issue by zzlTim** [infiniflow/ragflow#1918]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Branch name

main

### Commit ID

 i have pulled the newest version

### Other environment information

```Markdown
ubuntu 22.04
```

### Actual behavior

只要点击聊天api就会报错，已经更新到v0.9.0了，之前还是和
[https://github.com/infiniflow/ragflow/issues/1690](issue:1690) 一样的问题，更新后反而直接报错
![8bd77666c3aad3ecd2720c9eaf2c414a](https://github.com/user-attachments/assets/8639c689-4da9-4b0c-897f-b132259a3ad9)

![24b91f0cb5138a8b416115d46b927157](https://github.com/user-attachments/assets/7cd334bc-7915-41f3-aa97-25579d8b2aea)

### Expected behavior

能够正常使用

### Steps to reproduce

```Markdown
只要点击聊天api就会报错
```

**Comment by cotaa956** [comment]
This problem is also in demo, 
![image](https://github.com/user-attachments/assets/387ab160-c107-477b-bc07-b4c2f5eb733c)

**Comment by zzlTim** [comment]
虽然你们提了新commit，但是我拉最新代码还是有这个问题
