### ISSUE TITLE
[Question]: why MySQL container keeps reporting errors

### ISSUE THREAD

**Issue by ThierryHenry1994** [infiniflow/ragflow#1922]
### Describe your problem

I followed the user manual to pull the image and executed docker compose -f docker-compose-CN.yml up -d, but the MySQL image keeps reporting the error: '[Note] Access denied for user 'root'@'172.21.0.6' (using password: YES)'". My code version is v0.9.0

**Comment by KevinHuSh** [comment]
Check docker/.env and conf/service_conf.yml. The password in both file should be the same.

**Comment by ThierryHenry1994** [comment]
> Check docker/.env and conf/service_conf.yml. The password in both file should be the same.

Yes.I have checked password in two config files, but not work yet.The password used default value.This phenomenon occurs when I execute docker compose after I pull down the image, even if I change the password.
