### ISSUE TITLE
[Bug]: WARNING: can't find /ragflow/rag/res/broker.tm

### ISSUE THREAD

**Issue by htsh** [infiniflow/ragflow#193]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7a36d25  

### Other environment information

```Markdown
pop_os 22.04
docker 26.0
Intel i7-12800h
32gb
```

### Actual behavior

(base) hitesh@whiskey:~/ragflow/docker$ docker logs -f ragflow-server
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!

    ____                 ______ __               
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
              /____/                             

    
ERROR:dashscope:Request: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation failed, status: 401, message: Invalid API-key provided.
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.5:9380
INFO:werkzeug:Press CTRL+C to quit
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm
WARNING: can't find /ragflow/rag/res/broker.tm

### Expected behavior

    ____                 ______ __
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ /
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/
              /____/

 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.22.0.5:9380
 INFO:werkzeug:Press CTRL+C to quit

### Steps to reproduce

```Markdown
I followed the instructions for docker:

$ git clone https://github.com/infiniflow/ragflow.git
$ cd ragflow/docker
$ docker compose up -d
```

**Comment by KevinHuSh** [comment]
Thans for following!
------------------------------------------------------------------
![image](https://github.com/infiniflow/ragflow/assets/12318111/0469216b-4b58-4d87-a995-833503fb77ed)
For this issue, please configure your own LLM supplier and API-Key at the 'docker/service_config.yaml' in the following part:
![image](https://github.com/infiniflow/ragflow/assets/12318111/4c33d603-5446-4548-bd42-a610055262c9)
[llm_api_key_setup.md](https://github.com/infiniflow/ragflow/blob/main/docs/llm_api_key_setup.md) has the detail.

**Comment by KevinHuSh** [comment]
WARNING: can't find /ragflow/rag/res/broker.tm
Ignore this warning please. Once you uploaded documents in the system, this will dismiss.

**Comment by KevinHuSh** [comment]
WARNING: can't find /ragflow/rag/res/broker.tm
Ignore this warning please. Once you uploaded documents in the system, this will dismiss.

**Comment by timdonovanuk** [comment]
@KevinHuSh service_config.yaml is not mentioned at all in https://github.com/infiniflow/ragflow/blob/main/docs/quickstart.md. So is this an error, a requirement or a bug? I get this "error" starting ragflow-server and the server doesn't work.
