### ISSUE TITLE
[Question]: How do I save my data when I plan to update the docker image and move the ragflow project?

### ISSUE THREAD

**Issue by fmk54330502** [infiniflow/ragflow#1930]
### Describe your problem

Hi, last week I tried to put the ragflow project on my PC and tried using it. I felt good and I want to move it to my server. I notice that the dokcer image version is not the latest. So, How can I save my existing data, and change the docker image, and move the ragflow project to the server computer? Thanks a lot.

**Comment by KevinHuSh** [comment]
The docker container didn't hold  any data.
If you want to migrate data, you could search about migrating docker volumes which held all the data.

**Comment by fmk54330502** [comment]
> The docker container didn't hold any data. If you want to migrate data, you could search about migrating docker volumes which held all the data.

Thanks very much. I found the volumes.
