### ISSUE TITLE
[Bug]: chatting with OpenAI model  appear issue

### ISSUE THREAD

**Issue by Rama-19** [infiniflow/ragflow#1936]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

infiniflow/ragflow

### Commit ID

#flaskwrongrag0004

### Actual behavior

chatting appear error with gpt
![0632096af294ad9aa821f24840482e2](https://github.com/user-attachments/assets/954eeb3b-47ca-47fb-bea7-25cd5093bcba)
![9d7286f87e6c5db55617f7f837876c8](https://github.com/user-attachments/assets/4ac0d4e6-38f8-4478-bd5d-15cb639b04e4)

### Steps to reproduce

```Markdown
set model of openai gpt,embedding knowledge is  ok ,but appear error when i was chatting with gpt3 or gpt4
```

**Comment by hangters** [comment]
hi @Rama-19  This is because the default embedding model was not added to the relevant data table, but this does not affect usage.
