### ISSUE TITLE
能支持自定义接入LLM嘛

### ISSUE THREAD

**Issue by YYL1999** [infiniflow/ragflow#194]
### Describe your problem

如题，可以自己自定义接入openAI或其他LLM的能力嘛

**Comment by 0xchaihu** [comment]
Yes, please see [llm_api_key_setup.md](https://github.com/infiniflow/ragflow/blob/main/docs/llm_api_key_setup.md).

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question:
Already supported, but it's not friendly enough, we will document this feature after trying to make it easy to config and run.
Right now, you try this way:
1. run a LLM server: 
`python rag/llm/rpc_server.py --model_name QWen-14B-chat(your local LLM)`
2. Configure it at docker/service_conf.yaml  as following:
`
user_default_llm:
  factory: 'Local'
`
3. Chose local LLM in the interface.
