### ISSUE TITLE
[Question]: add bedrock LLM error

### ISSUE THREAD

**Issue by bxl1234** [infiniflow/ragflow#1942]
### Describe your problem

![image](https://github.com/user-attachments/assets/4fb1305a-1a6f-4a12-9c24-6c3a25e9a8b6)

**Comment by hangters** [comment]
hi @bxl1234  will fix it soon.

**Comment by Hyyusogood** [comment]
这个问题解决了么？

**Comment by JobSmithManipulation** [comment]
> 这个问题解决了么？

This issue has been resolved and closed

**Comment by Hyyusogood** [comment]
具体的解决方法可以说一下么？最近在0.12.0上又遇到了

**Comment by KevinHuSh** [comment]
We gona debug it again.
