### ISSUE TITLE
[Feature Request]: Support for formulas

### ISSUE THREAD

**Issue by fmk54330502** [infiniflow/ragflow#1954]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

When I am analyzing my scientific paper, I found amazingly that ragflow can recognize the formula. However, in the chat windows, the formulas in its answers seem not to be parsed correctly. Hope to add the support to parse the formulas. 
<img width="616" alt="PixPin_2024-08-15_10-58-05" src="https://github.com/user-attachments/assets/aff21f61-ce7d-480a-ab2a-8cca46e64d4b">

**Comment by cyhasuka** [comment]
Looking forward to this feature.
