### ISSUE TITLE
[Bug]: OpenAI's embedding model is limited to 8191 in length, but the truncated length in the code is 8196

### ISSUE THREAD

**Issue by lixiangtiandashen** [infiniflow/ragflow#1958]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c59c1b6

### Actual behavior

[ERROR]Embedding error:Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 8196 tokens (8196 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

![image](https://github.com/user-attachments/assets/437f6376-437a-4672-ad05-6f5dc72839b2)

![image](https://github.com/user-attachments/assets/33e3dacb-b0d8-4d56-9ae7-1524e1166cfa)

### Steps to reproduce

```Markdown
use graphrag to build knowledge base
```

**Comment by hangters** [comment]
hi @lixiangtiandashen  thanks for mention that, will fix it soon
