### ISSUE TITLE
[Bug]: Can't add models of SiliconFlow

### ISSUE THREAD

**Issue by netsailer** [infiniflow/ragflow#1968]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

853aa121a955ea359f2b5e9e6c0ade057ab76b4b

### Other environment information

```Markdown
Both demo.ragflow.io and self-deployed site
```

### Actual behavior

The following error occurrs while adding SILICONFLOW models:
Fail to access embedding model(BAAI/bge-large-en-v1.5 ) using this api key.Error code: 500 - {'code': 20402, 'message': 'Model not found.', 'data': None, 'error': 'Model not found.'}

### Steps to reproduce

```Markdown
Under Model Providers, find SILICONFLOW, click Add the Model, enter the API Key, and click Ok.
```

**Comment by hangters** [comment]
hi @netsailer  #1956  already fixed , pull the newest docker images could solve it.
