### ISSUE TITLE
[Question]: Encounter error when add 01.ai API

### ISSUE THREAD

**Issue by xxz196801** [infiniflow/ragflow#1976]
### Describe your problem

8月15日晚8点，docker装入ragflow后，运行时，01万物接入api错误，不知是否已经修复？

**Comment by hangters** [comment]
hi @xxz196801  thanks for mention that , will fix it soon

**Comment by hangters** [comment]
It seems that there are both Chinese and English API interfaces. Moving forward, the English version of the API interface will be used.
