### ISSUE TITLE
[Bug]: Documents stop processing after uploading a PDF on demo.ragflow.io

### ISSUE THREAD

**Issue by yangzq50** [infiniflow/ragflow#198]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

36f2d7b

### Actual behavior

Documents stop processing after uploading a PDF on demo.ragflow.io

### Steps to reproduce

```Markdown
Upload a PDF on demo.ragflow.io
```

**Comment by KevinHuSh** [comment]
Fixed.
Thanks for your attantion!
