### ISSUE TITLE
[Question]: Decreased quality of answers and confusing references after multiple Q&A sessions in a single session window

### ISSUE THREAD

**Issue by Zhangli20** [infiniflow/ragflow#1989]
### Describe your problem

Locally deployed docker version. When using it, I found that when doing multiple rounds of Q&A in the same session window, the answers become not based on the content in the knowledge base, but on the original knowledge of the qwen2:7b, and the citations are messed up (citing snippets that were cited in other historical sessions and are not relevant to the current question). However, a new session is opened to re-ask the question (same assistant and same knowledge base) and the answer is again faithful to the knowledge base and the citation is correct.

Relevant snippets from the knowledge base
![原文](https://github.com/user-attachments/assets/fee115f7-0f54-4fd3-af6a-7f7d32f58ebc)

Answers during multiple rounds of questions and answers
![多轮问答中](https://github.com/user-attachments/assets/f6f670d8-d8eb-4737-ad79-afe13523905b)

First Q&A in a new session window
![新会话中](https://github.com/user-attachments/assets/361eee83-58c4-470b-aaea-7104916d39d1)

Such questions occur frequently, and answers in a new session are significantly better than multiple Q&A sessions in a single session window.

**Comment by KevinHuSh** [comment]
All the chat history will be transfered to LLM. 
I guess LLM thought the first answer was not good enough so came the same quesion again, and it's also confused how to answer that.
