### ISSUE TITLE
[Question]: I want to pull the new version, how to ensure that the current data is not lost.

### ISSUE THREAD

**Issue by robertshuai** [infiniflow/ragflow#1990]
### Describe your problem

First of all, thank you very much. I love your project and have followed it since the beginning. I see that the new version has been updated a lot, I want to try, but I already have a lot of local data, can I directly pull the new project to retain the original data? Or it's already mounted in a local directory

**Comment by apulache** [comment]
Hello, here some recommendations:

- First, make a backup copy of your current ragflow setup including your data
- I recommend that you use the latest release v0.9.0 it is more stable that current dev version (i.e. in current dev version using Cohere break the Chat pages for all Knowledge Base that use Cohere LLMs)
- Edit your /docker/.env file and change the line from RAGFLOW_VERSION=dev to RAGFLOW_VERSION=v0.9.0
- Restart ragflow and  the new docker image for v0.9.0 will be pull, run and connect to your current Docker volumes
- If roll back is needed then change back to your previous value RAGFLOW_VERSION and restart ragflow
- If the update works then delete previos ragflow image to save almost 19GB
I've tested this procedure myself and it works.
Hope it helps.

**Comment by KevinHuSh** [comment]
Theoretically, you're not gona loss data by upgrade.
In term of data security, just backup the docker volumes.
