### ISSUE TITLE
[Question]: Hot-reloading not working?

### ISSUE THREAD

**Issue by 400yk** [infiniflow/ragflow#1993]
### Describe your problem

I use Ragflow as base framework to develop my web app. I mounted web/src through docker-compose.yml and checked that whenever code changes are made, they're updated in container in real-time. However, I can't see hot-reloading in web page, unless I rebuilt the image or restart the container.

I also tried moving npm start from Dockerfile to entrypoint.sh and replacing "npm run build" with "npm start", it doesn't work.

From my understanding, hot-reloading should be an automatic feature in React

Any help? Thanks!

**Comment by KevinHuSh** [comment]
After code modification, run ""npm run build"" to make it work.

**Comment by 400yk** [comment]
> After code modification, run ""npm run build"" to make it work.

although still not hot-reloading, but better than rebuilding the image. Thanks!

**Comment by 1953705297** [comment]
run_simple(
            hostname=settings.HOST_IP,
            port=settings.HOST_PORT,
            application=app,
            threaded=True,
            use_reloader=True,
            use_debugger=True,
            reloader_type='watchdog'
        )   

This is the setting, but it cannot be hot overloaded, may I ask how to solve it?

**Comment by 1953705297** [comment]
![Image](https://github.com/user-attachments/assets/a72f9140-eb5b-4106-9e53-9ebea5a12578)
