### ISSUE TITLE
[Bug]: container ragflow-mysql is unhealthy

### ISSUE THREAD

**Issue by cyx951211** [infiniflow/ragflow#1995]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Branch name

container ragflow-mysql is unhealthy

### Commit ID

329

### Other environment information

```Markdown
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose-base.yml: version is obsolete
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose.yml: version is obsolete
[+] Running 4/4
✘ Container ragflow-es-01 Error 0.0s
✔ Container ragflow-kibana Running 0.0s
✔ Container ragflow-minio Running 0.0s
✘ Container ragflow-mysql Error 0.0s
dependency failed to start: container ragflow-mysql is unhealthy
```

### Actual behavior

WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose-base.yml: version is obsolete
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose.yml: version is obsolete
[+] Running 4/4
✘ Container ragflow-es-01 Error 0.0s
✔ Container ragflow-kibana Running 0.0s
✔ Container ragflow-minio Running 0.0s
✘ Container ragflow-mysql Error 0.0s
dependency failed to start: container ragflow-mysql is unhealthy

### Steps to reproduce

```Markdown
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose-base.yml: version is obsolete
WARN[0000] /mnt/e/gpt/ragflow/docker/docker-compose.yml: version is obsolete
[+] Running 4/4
✘ Container ragflow-es-01 Error 0.0s
✔ Container ragflow-kibana Running 0.0s
✔ Container ragflow-minio Running 0.0s
✘ Container ragflow-mysql Error 0.0s
dependency failed to start: container ragflow-mysql is unhealthy
```

**Comment by KevinHuSh** [comment]
docker compose down -v (remove all the local data)
docker compose up

**Comment by lvxiaodong6688** [comment]
> docker compose down -v (remove all the local data) docker compose up

it works !thanks

**Comment by Encounter005** [comment]
it doesn't work for we 
![image](https://github.com/user-attachments/assets/64b731e5-b569-4317-bf30-a3aee23f12b8)
![image](https://github.com/user-attachments/assets/a3132172-3968-4aee-8b80-540af08bceaa)

**Comment by JeremyBickel** [comment]
[error_log.txt](https://github.com/user-attachments/files/17015662/error_log.txt)

Here's a trace. I installed it fresh and ran into this error. Then I applied the fix from @KevinHuSh to remove all the local data. When I ran it again, the output was different than the first run, but it ended with this same error.

**Comment by Linnnkkk** [comment]
> docker compose down -v (remove all the local data) docker compose up

it works,thx
