### ISSUE TITLE
[Bug]: API Endpoints 'Upload file' do not operate as expected

### ISSUE THREAD

**Issue by FinTechCao** [infiniflow/ragflow#2011]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0000

### Actual behavior

the result is 
{'data': None, 'retcode': 100, 'retmsg': "AttributeError("'NoneType' object has no attribute 'strip'")"}

### Steps to reproduce

```Markdown
self.url_prefix+end_point = 'http://xxx.xx:8080/v1/api/document/upload'
self.headers_json = {'Content-Type': 'application/json', 'Authorization': 'Bearer ragflow-XXX'}

end_point = "/api/document/upload"
with open(file_path, "r") as f:
    file_content = f.read()
params = {"file": file_content,
          "kb_name": kb_name,
         }
req = requests.post(url=self.url_prefix+end_point, headers=self.headers_json, data=json.dumps(params))
content = req.json()
```

**Comment by KevinHuSh** [comment]
it seems that kb_name is none.

**Comment by FinTechCao** [comment]
> it seems that kb_name is none.

I have already entered the kb_name parameter through

```
params = {"file": file_content,
          "kb_name": kb_name,
         }
```

and `kb_name` is not none

**Comment by KevinHuSh** [comment]
[May this help](https://stackoverflow.com/questions/22567306/how-to-upload-file-with-python-requests)

**Comment by FinTechCao** [comment]
> [May this help](https://stackoverflow.com/questions/22567306/how-to-upload-file-with-python-requests)

Thank you。 I changed the code to:
```
files = {'file': open(file_path, 'rb')}
data = {
            'kb_name': kb_name,
            'parser_id': 'naive'
        }
req = requests.post(url=self.url_prefix+end_point, headers=self.headers_json, files=files, data=data)
```
but the response is 
```
{'data': None, 'retcode': 101, 'retmsg': 'required argument are missing: kb_name; '}
```

**Comment by FinTechCao** [comment]
@KevinHuSh Hello, kindly need help

**Comment by FinTechCao** [comment]
I have fixed by myself, you should write like this:

```
end_point = "/api/document/upload"
header = {"Authorization": "Bearer " + self.api_key}
# 需要上传的文件
files = {'file': open(file_path, 'rb'),
                 'kb_name': (None, kb_name),
                 'parser_id': (None, parser_id),
                 'run': (None, "1")}
req = requests.post(url=self.url_prefix+end_point, headers=header, files=files)
```

**Comment by FinTechCao** [comment]
end_point = "/api/document/upload"
header = {"Authorization": "Bearer " + self.api_key}
# 需要上传的文件
files = {'file': open(file_path, 'rb'),
             'kb_name': (None, kb_name),
             'parser_id': (None, parser_id),
             'run': (None, "1")}
req = requests.post(url=self.url_prefix+end_point, headers=header, files=files)

**Comment by babyporgrammer** [comment]
url = f"{self.base_url}/api/document/upload"

        headers = {
            "Authorization": f"Bearer {self.api_key}"
        }

        files = {'file': open(file_path, 'rb'),
                 'kb_name': (None,"123123"),
                 'parser_id': (None,"naive"),
                 'run': (None,"1")}
        response = requests.post(url, files=files, headers=headers,verify=False)

I use the same code, but the error still same {'data': None, 'retcode': 100, 'retmsg': 'AttributeError("\'NoneType\' object has no attribute \'split\'")'}
