### ISSUE TITLE
[Question]: What is use of  variable and what is key 'knowledge' does it only add Json tag or uses only knowledge base if we enable it.

### ISSUE THREAD

**Issue by saineshwar** [infiniflow/ragflow#2016]
### Describe your problem

![image](https://github.com/user-attachments/assets/73969a26-977e-437c-9147-0c1e8de71dda)

**Comment by KevinHuSh** [comment]
When the setup dialog is gona be used by API, it can deliver variables to fullfill the prompt, like /api/completion?gender=male.
The prompt is like "You're a xxx. When the gender is male, you should xxx. When the gender is female, you should xxx. Now, the customer's gender is {gender}. Please do the right thing."

'knowledge' is for retrieved stuff from specified knowledge bases.
