### ISSUE TITLE
[Bug]: Parsing stuck at 0.62%

### ISSUE THREAD

**Issue by ovyan** [infiniflow/ragflow#202]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

I signed up on the demo site and uploaded pdf and docx files. They are both stuck at 0.62% for over 10 minutes now and not moving.
<img width="1129" alt="image" src="https://github.com/infiniflow/ragflow/assets/23217571/5575b327-a324-4d13-a1dc-0d6e6a01e19e">

Here is my config
<img width="485" alt="image" src="https://github.com/infiniflow/ragflow/assets/23217571/e33707ea-8012-4c9e-8c7c-61e2170c8c92">

### Expected behavior

I would expect parsing to finish, I guess.

### Steps to reproduce

```Markdown
1. Create an account on https://demo.ragflow.io/
2. Upload a document
```

**Comment by ovyan** [comment]
I tried creating a new knowledge base with default config and it can parse the same files I used before. So that might be an issue with the specific config I indicated above.

**Comment by ovyan** [comment]
My bad guys, after 15 minutes it seemed to parse it
<img width="1060" alt="image" src="https://github.com/infiniflow/ragflow/assets/23217571/75c70c45-a4ac-4800-b93c-320da49e85a0">

Should I close this issue?

**Comment by ovyan** [comment]
Though I am surprised how much it took to parse the pdf file

**Comment by KevinHuSh** [comment]
Thanks for following us.

'Paper' method has not supported docx file format yet. It will support later.

May I ask why you are uploading the paper and how you plan to ask questions? 😊
We want to make the system meet various needs.

**Comment by KevinHuSh** [comment]
> Though I am surprised how much it took to parse the pdf file

The server is a little short of computation resource. It's about 3 seconds per page for PDF in average if our server is idle.

**Comment by KevinHuSh** [comment]
> What I would like to have is:
> 
> * find papers on arxiv
> * save them locally
> * upload to RAG
> * chat about my ideas with these papers to find something related
> 
> that is my main use scenario.

How many papers will you upload?

**Comment by ovyan** [comment]
In each folder, I would expect to have 30-50 papers I guess at max. I mean the more the better...

Also something like – summarizing the paper or cluster the papers based on common topic is also nice to have

**Comment by KevinHuSh** [comment]
Summarize and cluster! Roger!

Thanks for your nice replay!

**Comment by ccly1996** [comment]
same problem,txt format also could not be parse

**Comment by ssy040504** [comment]
我的PPT和PNG也无法解析，提示Not supported yet!

**Comment by ssy040504** [comment]
![234](https://github.com/infiniflow/ragflow/assets/79555881/ff8a7118-ba62-4cf3-99b0-f369ff5e5250)
