### ISSUE TITLE
[Bug]: Getting Error on Calling POST completion API AssertionError('Nothing. Is it over?') 

### ISSUE THREAD

**Issue by saineshwar** [infiniflow/ragflow#2023]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ef8728a31439decdcb4e90b80d4391f3443e9f30

### Actual behavior

From Here we generate API Key 

**Step 1**
---------------
![image](https://github.com/user-attachments/assets/1a3987d6-37a2-4392-9c84-9c03b7b51b67)

**Step 2**
---------------
![image](https://github.com/user-attachments/assets/b15497db-0beb-4bef-a984-d4bb3f08f00e)

**Step 3 Calling Create Conversation API**
---------------
![image](https://github.com/user-attachments/assets/2bbb8ce7-9290-4e20-9062-f603bad047d0)

**Step 4 Calling POST Completion API**
---------------
![image](https://github.com/user-attachments/assets/53abf16b-6734-425f-b2ce-a7e492cde111)

**Getting Error.**

`{
    "data": null,
    "retcode": 100,
    "retmsg": "AssertionError('Nothing. Is it over?')"
}`

### Steps to reproduce

```Markdown
1. Creating an agent of type "Chat bot"
2. After that creating "Chat Bot API" from API button.
3. Generate API Key
4. Calling Create new_conversation API in response we will receive "id"
5. Calling completion API with id "Conversation Id"
```

### Additional information

**Error while call Completion API**

`{
    "data": null,
    "retcode": 100,
    "retmsg": "AssertionError('Nothing. Is it over?')"
}`

**Comment by KevinHuSh** [comment]
The diagram is inappropriate set.
The diagram indicates the proccessing procedure.
Component 'Relevant' has no upper stream, remove it.
After 'Message', there should be 'Answer' to display it, so, wire it to the 'Answer'.

**Comment by saineshwar** [comment]
Hi @KevinHuSh 
Is this Proper flow? Any reference please share. 
![image](https://github.com/user-attachments/assets/8eb7cb22-74b6-4c4d-901d-c0390db8cb9e)
