### ISSUE TITLE
[Question]: the max token of  raptor

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#2027]
### Describe your problem

what is the relation of the max token of raptor and the token of chunk? if the max token of raptor should be multiple of the token of chunk?

**Comment by HaoGuo98** [comment]
and what's suitable chunk size? 1024?

**Comment by KevinHuSh** [comment]
Max token of RAPTOR means the summary of a cluster should be in that maxium length.
1024 of chunk size is a reasonable choice.

**Comment by HaoGuo98** [comment]
thanks
