### ISSUE TITLE
[Bug]: The minio service can only be accessed by localhost, not 127.0.0.1, using the RAGFlow source deployment.

### ISSUE THREAD

**Issue by muou55555** [infiniflow/ragflow#2030]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

99b634c68d840095

### Other environment information

```Markdown
macos.14 m2
```

### Actual behavior

文件管理和上传文件总报错
<img width="247" alt="image" src="https://github.com/user-attachments/assets/240e66a8-3ae2-4036-b7c0-46fbf59fb597">

### Steps to reproduce

```Markdown
无
```

**Comment by KevinHuSh** [comment]
It depends on how you deploy minio.
