### ISSUE TITLE
[Question]: Can't get image by img_id.

### ISSUE THREAD

**Issue by CitySelection** [infiniflow/ragflow#2035]
### Describe your problem

<img width="598" alt="截屏2024-08-21 15 27 23" src="https://github.com/user-attachments/assets/5fac00f4-36b2-4a60-b6cb-e24df01a031a">
<img width="406" alt="截屏2024-08-21 15 27 55" src="https://github.com/user-attachments/assets/4bbf7a5f-c825-4343-9485-ed08338b1899">

**Comment by CitySelection** [comment]
通过返回的img_id拿不到图片

**Comment by KevinHuSh** [comment]
Image should be retrievaled by /document/image/image_id

**Comment by BoFan-tunning** [comment]
image_id :4607331a109a11f080490242ac160006-bc6b5af7d6559ee5
but i use this url can't get image
http://127.0.0.1/document/image/4607331a109a11f080490242ac160006-bc6b5af7d6559ee5

**Comment by BoFan-tunning** [comment]
how？
