### ISSUE TITLE
antd report that: Static function can not consume context like dynamic theme. Please use 'App' component instead. 

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#204]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f89c6c9d599c8e9f03f024691cdef61b3939859d

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/8089971/f4add233-003d-43a5-afda-09435db0ac1b)

### Steps to reproduce

```Markdown
![image](https://github.com/infiniflow/ragflow/assets/8089971/3b77d8ce-fc78-4006-8c4c-1e25f7d29fa6)

```

**Comment by KevinHuSh** [comment]
fixed!
