### ISSUE TITLE
[Question]: Dockerfile for ragflow-base image?

### ISSUE THREAD

**Issue by gitpurzy** [infiniflow/ragflow#205]
### Describe your problem

Building the project truly from source would involve building all resources, including base image. Any chance `ragflow-base` dockerfile could be included in repo?

**Comment by KevinHuSh** [comment]
Acctually, ragflow-base image was not built  from Dockerfile. 
We just run ubuntu 22.04 docker image, then install all the necessary thing, and commit this container to an image.

The Python version is 3.11, and you can find other thing in reqirements.txt

**Comment by kam-st** [comment]
> Acctually, ragflow-base image was not built from Dockerfile. We just run ubuntu 22.04 docker image, then install all the necessary thing, and commit this container to an image.
> 
> The Python version is 3.11, and you can find other thing in reqirements.txt

Hi Kevin,

Would you be able to do it from dockerfile and share file? Just makes it easier to use different distros based on preference.
