### ISSUE TITLE
请问系统架构图是使用什么工具绘制的

### ISSUE THREAD

**Issue by KKD4Soei** [infiniflow/ragflow#206]
### Describe your problem

请问系统架构图是使用什么工具绘制的
![Uploading IMG_8269.png…]()

**Comment by KKD4Soei** [comment]
![IMG_8269](https://github.com/infiniflow/ragflow/assets/58964439/a3970f10-b303-4a34-83bd-05892d944b55)

**Comment by zingistop** [comment]
Good evening, friend.

This was created using Figma, though it can easily be done with the Adobe suite as well, depending on your personal preferences.

If you're looking to create this graphic, here are a few tips:

1. Use lines of different colors to differentiate paths. In this case, I've used brand blue and brand black.
2. Add shadows to the node blocks. This allows you to maintain a clean look while also achieving a three-dimensional effect. For the shadow color, I chose brand blue-200, which is a subtle touch.
3. The background is gray, primarily to highlight the white node blocks.

I hope you find these tips helpful. Let me know if you need further help.

**Comment by KKD4Soei** [comment]
Thank you very much! In the past, when creating system architecture diagrams, I used Visio and WPS (a Chinese software) quite often. However, achieving such a visually appealing effect required a rather complex design. Recently, I have been looking for learning materials on Figma, which has further strengthened my confidence in learning. Thank you once again!
