### ISSUE TITLE
[Question]: Can not parsing files using local Ollama embedding models

### ISSUE THREAD

**Issue by kkrusher** [infiniflow/ragflow#2061]
### Describe your problem

I installed Ollama locally and set up Ragflow using Docker. I downloaded the Qwen2 7b model and two different embedding models through Ollama. Then I created a knowledge base, config embedding model to be the one in Ollama, and uploaded files, but they couldn't be parsed. What could be the issue, and how can I resolve it?

![Screenshot from 2024-08-22 22-32-30](https://github.com/user-attachments/assets/0144a4d5-b826-4ff4-a94d-397009f24ae7)
![Screenshot from 2024-08-22 22-34-37](https://github.com/user-attachments/assets/7436d4b1-57a9-482a-a270-1b695d06c32c)

**Comment by kkrusher** [comment]
Does this error matters?
![Screenshot from 2024-08-22 22-45-02](https://github.com/user-attachments/assets/865fd7d4-6082-41df-acbb-cff289430748)

**Comment by KevinHuSh** [comment]
I guess some process of ragflow did not execute well.
Could you paste the log by removing -d for docker compose?

**Comment by yangjc** [comment]
I have the same issue
<img width="433" alt="image" src="https://github.com/user-attachments/assets/2958de4e-6346-465b-a68d-b8b8b899dcd0">
My environment: apple macbook, arm, docker in vm

**Comment by kkrusher** [comment]
The following is log:

> ~/Documents/git_repos/ragflow/docker$ docker compose up
> WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
> [+] Running 6/6
>  ✔ Network docker_ragflow    Created                                                                                                                                          0.0s 
>  ✔ Container ragflow-mysql   Created                                                                                                                                          0.1s 
>  ✔ Container ragflow-redis   Created                                                                                                                                          0.1s 
>  ✔ Container ragflow-minio   Created                                                                                                                                          0.1s 
>  ✔ Container ragflow-es-01   Created                                                                                                                                          0.1s 
>  ✔ Container ragflow-server  Created                                                                                                                                          0.1s 
> Attaching to ragflow-es-01, ragflow-minio, ragflow-mysql, ragflow-redis, ragflow-server
> ragflow-redis   | 1:C 23 Aug 2024 10:19:10.959 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> ragflow-redis   | 1:C 23 Aug 2024 10:19:10.959 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
> ragflow-redis   | 1:C 23 Aug 2024 10:19:10.959 * Configuration loaded
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * monotonic clock: POSIX clock_gettime
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * Running mode=standalone, port=6379.
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * Server initialized
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * Loading RDB produced by version 7.2.4
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * RDB age 21 seconds
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * RDB memory usage when created 0.97 Mb
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.960 * Done loading RDB, keys loaded: 0, keys expired: 0.
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.961 * DB loaded from disk: 0.000 seconds
> ragflow-redis   | 1:M 23 Aug 2024 10:19:10.961 * Ready to accept connections tcp
> ragflow-minio   | MinIO Object Storage Server
> ragflow-minio   | Copyright: 2015-2023 MinIO, Inc.
> ragflow-minio   | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> ragflow-minio   | Version: RELEASE.2023-12-20T01-00-02Z (go1.21.5 linux/amd64)
> ragflow-minio   | 
> ragflow-minio   | Status:         1 Online, 0 Offline. 
> ragflow-minio   | S3-API: http://172.18.0.4:9000  http://127.0.0.1:9000   
> ragflow-minio   | Console: http://172.18.0.4:9001 http://127.0.0.1:9001  
> ragflow-minio   | 
> ragflow-minio   | Documentation: https://min.io/docs/minio/linux/index.html
> ragflow-minio   | Warning: The standard parity is set to 0. This can lead to data loss.
> ragflow-mysql   | 2024-08-23T10:19:11.142918Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> ragflow-mysql   | 2024-08-23T10:19:11.143580Z 0 [Note] mysqld (mysqld 5.7.18) starting as process 1 ...
> ragflow-mysql   | 2024-08-23T10:19:11.146013Z 0 [Note] InnoDB: PUNCH HOLE support available
> ragflow-mysql   | 2024-08-23T10:19:11.146071Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> ragflow-mysql   | 2024-08-23T10:19:11.146084Z 0 [Note] InnoDB: Uses event mutexes
> ragflow-mysql   | 2024-08-23T10:19:11.146093Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> ragflow-mysql   | 2024-08-23T10:19:11.146118Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
> ragflow-mysql   | 2024-08-23T10:19:11.146125Z 0 [Note] InnoDB: Using Linux native AIO
> ragflow-mysql   | 2024-08-23T10:19:11.146723Z 0 [Note] InnoDB: Number of pools: 1
> ragflow-mysql   | 2024-08-23T10:19:11.146827Z 0 [Note] InnoDB: Using CPU crc32 instructions
> ragflow-mysql   | 2024-08-23T10:19:11.148866Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
> ragflow-mysql   | 2024-08-23T10:19:11.154151Z 0 [Note] InnoDB: Completed initialization of buffer pool
> ragflow-mysql   | 2024-08-23T10:19:11.155544Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
> ragflow-mysql   | 2024-08-23T10:19:11.172572Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
> ragflow-mysql   | 2024-08-23T10:19:11.192782Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> ragflow-mysql   | 2024-08-23T10:19:11.192852Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> ragflow-mysql   | 2024-08-23T10:19:11.210930Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> ragflow-mysql   | 2024-08-23T10:19:11.211498Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
> ragflow-mysql   | 2024-08-23T10:19:11.211511Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
> ragflow-mysql   | 2024-08-23T10:19:11.211797Z 0 [Note] InnoDB: Waiting for purge to start
> ragflow-mysql   | 2024-08-23T10:19:11.262166Z 0 [Note] InnoDB: 5.7.18 started; log sequence number 246681350
> ragflow-mysql   | 2024-08-23T10:19:11.262482Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> ragflow-mysql   | 2024-08-23T10:19:11.262719Z 0 [Note] Plugin 'FEDERATED' is disabled.
> ragflow-mysql   | 2024-08-23T10:19:11.268025Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
> ragflow-mysql   | 2024-08-23T10:19:11.268097Z 0 [Warning] Failed to set up SSL because of the following SSL library error: TLS version is invalid
> ragflow-mysql   | 2024-08-23T10:19:11.268397Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
> ragflow-mysql   | 2024-08-23T10:19:11.268464Z 0 [Note] IPv6 is available.
> ragflow-mysql   | 2024-08-23T10:19:11.268469Z 0 [Note]   - '::' resolves to '::';
> ragflow-mysql   | 2024-08-23T10:19:11.268484Z 0 [Note] Server socket created on IP: '::'.
> ragflow-mysql   | 2024-08-23T10:19:11.270852Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240823 18:19:11
> ragflow-mysql   | 2024-08-23T10:19:11.273835Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
> ragflow-mysql   | 2024-08-23T10:19:11.273864Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
> ragflow-mysql   | 2024-08-23T10:19:11.273914Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
> ragflow-mysql   | 2024-08-23T10:19:11.273959Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
> ragflow-mysql   | 2024-08-23T10:19:11.286518Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
> ragflow-mysql   | 2024-08-23T10:19:11.307744Z 0 [Note] Event Scheduler: Loaded 0 events
> ragflow-mysql   | 2024-08-23T10:19:11.307955Z 0 [Note] Execution of init_file '/data/application/init.sql' started.
> ragflow-mysql   | 2024-08-23T10:19:11.308796Z 0 [Note] Execution of init_file '/data/application/init.sql' ended.
> ragflow-mysql   | 2024-08-23T10:19:11.308868Z 0 [Note] mysqld: ready for connections.
> ragflow-mysql   | Version: '5.7.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
> ragflow-mysql   | 2024-08-23T10:19:11.308877Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
> ragflow-mysql   | 2024-08-23T10:19:11.308878Z 0 [Note] Beginning of list of non-natively partitioned tables
> ragflow-mysql   | 2024-08-23T10:19:11.332534Z 0 [Note] End of list of non-natively partitioned tables
> ragflow-minio   | 
> ragflow-minio   |  You are running an older version of MinIO released 8 months before the latest release 
> ragflow-minio   |  Update: Run `mc admin update` 
> ragflow-minio   | 
> ragflow-minio   | 
> ragflow-es-01   | Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
> ragflow-es-01   | Aug 23, 2024 6:19:15 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
> ragflow-es-01   | WARNING: COMPAT locale provider will be removed in a future release
> ragflow-es-01   | {"@timestamp":"2024-08-23T10:19:15.824Z", "log.level": "INFO", "message":"Java vector incubator API enabled; uses preferredBitSize=256", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.apache.lucene.internal.vectorization.PanamaVectorizationProvider","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
> ragflow-es-01   | {"@timestamp":"2024-08-23T10:19:16.251Z", "log.level": "INFO", "message":"version[8.11.3], pid[175], build[docker/64cf052f3b56b1fd4449f5454cb88aca7e739d9a/2023-12-08T11:33:53.634979452Z], OS[Linux/6.10.0-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/21.0.1/21.0.1+12-29]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
> ragflow-es-01   | {"@timestamp":"2024-08-23T10:19:16.252Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}

**Comment by yuzhichang** [comment]
0.14.0 improved system healthy monitoring. Please upgrade.
