### ISSUE TITLE
[Question]: Chat in Agent are getting mixed up after creating new conversation also Using Agent API Key. 

### ISSUE THREAD

**Issue by saineshwar** [infiniflow/ragflow#2068]
### Describe your problem

1. Designed Flow in Agent (Assigned LLM Model And Knowledge Base)
2. Generate API Key 
3. Using API Key with POSTMAN
4. After creating a new Conversation (Conversation ID), it still references the last conversation. 

**Created New Conversation** 
![image](https://github.com/user-attachments/assets/40140272-ca0c-4158-af98-5f4d91918622)

**Calling Completion API**
![image](https://github.com/user-attachments/assets/094b2bc1-3ed4-4588-9d71-df24a44091f8)

I have asked a new Question with a new  **conversation_id**, but it refers to the same Conversation.

**Generate API Key From Here**

![image](https://github.com/user-attachments/assets/7cf57354-5fea-49a7-b319-11032caeaa13)

**Comment by guoyuhao2330** [comment]
Make sure the conversation_id is different and 'Hi there' is the default welcome message!
![image](https://github.com/user-attachments/assets/d48a5a22-491b-420b-80e7-551bd1e68ce9)
![image](https://github.com/user-attachments/assets/7a88f77f-658b-408e-8a83-b57212b14c94)

**Comment by saineshwar** [comment]
Hi @guoyuhao2330  

If we have a Different conversation then the '**Conversation not found**' error is shown.

![image](https://github.com/user-attachments/assets/a97d6340-6ee3-40f0-acd3-1cff2f408138)

![image](https://github.com/user-attachments/assets/268cc7f3-010c-47be-a188-03cb3b6bb69f)

**Comment by saineshwar** [comment]
> Make sure the conversation_id is different and 'Hi there' is the default welcome message! ![image](https://private-user-images.githubusercontent.com/43509927/361392142-d48a5a22-491b-420b-80e7-551bd1e68ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjU3ODMsIm5iZiI6MTcyNDc2NTQ4MywicGF0aCI6Ii80MzUwOTkyNy8zNjEzOTIxNDItZDQ4YTVhMjItNDkxYi00MjBiLTgwZTctNTUxYmQxZTY4Y2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNmQ2YTYzY2I4YWVkYWVmMzQ2OTM1ZGM5ZTZkNDZhNzc0YTE3NTgwNzQxOGZmOWVhOThmMzU0OTJiZmIzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._chmtkR63cFycAwOH-6NnMMsdzVgcxdnMFQ5MVrI5F4) ![image](https://private-user-images.githubusercontent.com/43509927/361392266-7a88f77f-658b-408e-8a83-b57212b14c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjU3ODMsIm5iZiI6MTcyNDc2NTQ4MywicGF0aCI6Ii80MzUwOTkyNy8zNjEzOTIyNjYtN2E4OGY3N2YtNjU4Yi00MDhlLThhODMtYjU3MjEyYjE0Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMmIyZmQ4NzU2NWNmNGNjNjY5ODEzNjY2OGRkZGQ4ZTlkMjlhMTViZjA5NTIxZTk3MWViNDI0OTg4YzVmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-l8mJoii-ODfGzCQ1UpEeJ0vdq7iltrzuUeNASr8rGk)

Hi @guoyuhao2330 ,

the solution you gave does not seems work can you please check it?

**Comment by guoyuhao2330** [comment]
You need to make sure that the conversation_id is obtained from the new_conversation API function, and the same token can get multiple conversation_id from the new_conversation API function.
When using the new_conversation API function, user_id is not required to use
