### ISSUE TITLE
[Bug]: Index Not Found - when testing retrieval

### ISSUE THREAD

**Issue by marktolson** [infiniflow/ragflow#207]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2673be8

### Other environment information

```Markdown
I've uploaded docs to the dataset, parsed and chunked successfully but testing the retrieval fails consistently. Using OpenAI model.
```

### Actual behavior

Error in top right - 'Index Not Found'

### Expected behavior

It should produce output from the LLM.

### Steps to reproduce

```Markdown
Test anything in retrieval testing.
```

**Comment by marktolson** [comment]
Response from server: {"data":false,"retcode":102,"retmsg":"Index not found!"}

**Comment by KevinHuSh** [comment]
Thanks for following！

How do you know that docs have been parsed and chunked successfully?

Could you take a screanshot at the processing bar like following?

![image](https://github.com/infiniflow/ragflow/assets/12318111/0009fe99-77db-4c0d-9580-e786a2a9249b)

Could you click the doc on the list to see the status of chunks?

**Comment by marktolson** [comment]
![image](https://github.com/infiniflow/ragflow/assets/1654182/5ca21c53-7053-400f-892b-028f3187454a)

**Comment by marktolson** [comment]
The label says success but it still doesn't look like it worked. If I click on the doc itself I get the same 'Index Not Found' error.

**Comment by KevinHuSh** [comment]
As your screan shot, the tips said: No chunk! Done!

So, the response is little confused. It should be No chunk found!

**Comment by marktolson** [comment]
So why would no chunk be found, it's a standard docx file?

**Comment by KevinHuSh** [comment]
This need to debug!
If it's convenient, please share part of your doc ?
Thanks!

**Comment by marktolson** [comment]
[Internal Role - Product Owner.docx](https://github.com/infiniflow/ragflow/files/14859130/Internal.Role.-.Product.Owner.docx)
Here is one example document.

**Comment by KevinHuSh** [comment]
It's a table in it. Surprise!

And Now we are able to support it.
Try it again.

**Comment by marktolson** [comment]
Thanks!
