### ISSUE TITLE
Index failure when parsing documents

### ISSUE THREAD

**Issue by zhengyb** [infiniflow/ragflow#208]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2d1

### Actual behavior

I test on https://demo.ragflow.io/,  upload a pdf file. Index failure every time.

Page(13~25): [ERROR]Index failure!

### Steps to reproduce

```Markdown
I test on https://demo.ragflow.io/,  upload a pdf file. Index failure every time.


Page(13~25): [ERROR]Index failure!
```

**Comment by KevinHuSh** [comment]
Thanks for following.

Our index server meets its bottleneck. Try that again, and let me know the results.
