### ISSUE TITLE
[Question]: Dialogue recall issues

### ISSUE THREAD

**Issue by sznariOsmosis** [infiniflow/ragflow#2108]
### Describe your problem

Debugging the source code found that the new question entered during the dialogue recall, the new question and the first three questions of the history will be combined to retrieve, which is normal, if the two questions before and after the question are far apart, will there be a problem?![image](https://github.com/user-attachments/assets/ea2bd41e-3f36-4b7e-891c-8d09e46a0a8d)
question:
['输变电线路故障特征有哪些 输变电线路故障特征有哪些 svm支持向量机 svm支持向量机']

**Comment by KevinHuSh** [comment]
Yes, that is a tough problem.
The best practice is to ask LLM which parts need to retain for the current retrieval.
