### ISSUE TITLE
[Question]:  "Table 'rag_flow.knowledgebase' doesn't exist" and  "Table 'rag_flow.document' doesn't exist"

### ISSUE THREAD

**Issue by zephyr737** [infiniflow/ragflow#211]
### Describe your problem

pymysql.err.ProgrammingError: (1146, "Table 'rag_flow.knowledgebase' doesn't exist")

**Comment by KevinHuSh** [comment]
Thanks for following!

Mysql didn't initialize properly.
Recommand, remove all the data and try that again.

docker compose down -v
docker compose up

**Comment by Stephenzza** [comment]
> Thanks for following!
> 
> Mysql didn't initialize properly. Recommand, remove all the data and try that again.
> 
> docker compose down -v docker compose up

same error, it doesn't work

**Comment by loong1118** [comment]
> > Thanks for following!
> > Mysql didn't initialize properly. Recommand, remove all the data and try that again.
> > docker compose down -v docker compose up
> 
> same error, it doesn't work

change this num as 180

then input this command
docker build -t swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:v1.0 .
docker compose -f docker-compose-CN.yml up -d
