### ISSUE TITLE
Can't pull the docker images.

### ISSUE THREAD

**Issue by jimleee** [infiniflow/ragflow#2115]
### Describe your problem

[Question]: 国内，用的是 梯子。
运行docker compose up -d
报错如下：PS D:\AI\ragflow\docker> docker compose up -d time="2024-08-27T13:33:02+08:00" level=warning msg="The \"MACOS\" variable is not set. Defaulting to a blank string." [+] Running 46/1  - ragflow 53 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 9.773GB/9.773GB Pulling                                         6851.2s  unexpected EOF。

重试很多很多很多次都这样。

**Comment by jimleee** [comment]
![image](https://github.com/user-attachments/assets/d2e5e79a-f67d-4b03-84a2-b78e7a64198b)
again

**Comment by jimleee** [comment]
![image](https://github.com/user-attachments/assets/97d4d358-4c66-43b5-8029-53d86e05a557)
and again

**Comment by cyhasuka** [comment]
Use this: [docker-compose-CN.yml](https://github.com/infiniflow/ragflow/blob/main/docker/docker-compose-CN.yml)
And If the problem persists, also change the docker in the following file to the image address
[docker-compose-base.yml](https://github.com/infiniflow/ragflow/blob/main/docker/docker-compose-base.yml)

**Comment by KevinHuSh** [comment]
Use this yaml : docker-compose-CN.yml
docker compose -f docker-compose-CN.yml up

**Comment by bot123124sa** [comment]
the same problem，“docker compose -f docker-compose-CN-oc9.yml up ” can‘t work，too
