### ISSUE TITLE
[Bug]: Raise KeyError: 'logical_operator' when using Agent, seems to be a front-end bug

### ISSUE THREAD

**Issue by cyhasuka** [infiniflow/ragflow#2120]
### Describe your problem

When I using Agent to extract seriel number, operator "switch" raise this. What's wrong with my settings? THX!

> ==> logs/api/ERROR.log <==
'logical_operator'
Traceback (most recent call last):
  File "/ragflow/api/apps/canvas_app.py", line 156, in reset
    canvas = Canvas(json.dumps(user_canvas.dsl), current_user.id)
  File "/ragflow/agent/canvas.py", line 102, in __init__
    self.load()
  File "/ragflow/agent/canvas.py", line 117, in load
    param.check()
  File "/ragflow/agent/component/switch.py", line 45, in check
    if cond["logical_operator"] not in ["and", "or"] and len(cond["items"]) > 1:
KeyError: 'logical_operator'

![image](https://github.com/user-attachments/assets/4bc16bac-f02e-42cc-8555-d59d71479b04)

**Comment by cyhasuka** [comment]
I think I found what is causing this bug. the Switch module in the first picture is from the DB assistant template which has the Logical operator option. But when I drag and drop a new Switch module from the left tab, the Logical operator option disappears. As I am not familiar with front end, sorry I can't provide a fix, please help with this issue, thanks. @KevinHuSh 

![image](https://github.com/user-attachments/assets/0d7d82a7-7eb9-4b3a-8de9-e4b7ef643a5c)
![image](https://github.com/user-attachments/assets/9e46053c-e57f-41fa-96e1-bc2beee59463)

**Comment by guoyuhao2330** [comment]
> 我想我找到了导致这个错误的原因。第一张图片中的 Switch 模块来自 DB Assistant 模板，该模板具有 Logical 运算符选项。但是，当我从左侧选项卡拖放新的 Switch 模块时，Logical operator 选项消失了。由于我不熟悉前端，抱歉我无法提供修复，请帮助解决这个问题，谢谢。
> 
> ![图像](https://private-user-images.githubusercontent.com/34462246/362159709-0d7d82a7-7eb9-4b3a-8de9-e4b7ef643a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzA5NjUsIm5iZiI6MTcyNDgzMDY2NSwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk3MDktMGQ3ZDgyYTctN2ViOS00YjNhLThkZTktZTRiN2VmNjQzYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNWYzZWZkZjEwZTU2M2E3OWY2N2E5NTVhZmQ1MmMxNWFmYjRhNTUxZWVkZDJlZTAwMzUzMTdmNzBjOWJhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fNFE2Wz24NorYwzIEGZvCpMjMWiJagx8qcYBv39c8Oo) ![图像](https://private-user-images.githubusercontent.com/34462246/362159467-9e46053c-e57f-41fa-96e1-bc2beee59463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzA5NjUsIm5iZiI6MTcyNDgzMDY2NSwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk0NjctOWU0NjA1M2MtZTU3Zi00MWZhLTk2ZTEtYmMyYmVlZTU5NDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTc5MDQzZmNiMGJiZWE5ZmI1N2EyYWU2MDZlMDYzMzhjODk3ODM1YmNlYzJiYTU1ZmRkNTBhNDMwZDVhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OvHtQBnhi6Dpw7PVHA1GpAPVc_0efesDU93Nx3_o2iw)

The and or logical operators only appear if each case contains more than one condition

> I think I found what is causing this bug. the Switch module in the first picture is from the DB assistant template which has the Logical operator option. But when I drag and drop a new Switch module from the left tab, the Logical operator option disappears. As I am not familiar with front end, sorry I can't provide a fix, please help with this issue, thanks. @KevinHuSh
> 
> ![image](https://private-user-images.githubusercontent.com/34462246/362159709-0d7d82a7-7eb9-4b3a-8de9-e4b7ef643a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzEyNzIsIm5iZiI6MTcyNDgzMDk3MiwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk3MDktMGQ3ZDgyYTctN2ViOS00YjNhLThkZTktZTRiN2VmNjQzYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTQ0MGQ4NTVlYzE2OTFiMjZiMDNiNmY5ODVjODlkOTg2ZTdjMWVkMTkxMzc3YjI0OGU1NTZiMGUxMTNjOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pw1UoAtkT3sX8p-IDdzYCFNIEz8bTE1O4We6qz_nlVo) ![image](https://private-user-images.githubusercontent.com/34462246/362159467-9e46053c-e57f-41fa-96e1-bc2beee59463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzEyNzIsIm5iZiI6MTcyNDgzMDk3MiwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk0NjctOWU0NjA1M2MtZTU3Zi00MWZhLTk2ZTEtYmMyYmVlZTU5NDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTM1MmYwNTRmYWUxYzU2NGVmZWEzODlkM2IwMjNmMmMxZDc3ZjI0MTg1ZWY5OTQ1OGE5NzZhMGFmMGI1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LqHDiBCXvfjBBzRYpYda5gpyiSHFlDXBKjwqOkfcYc)

The logical operators only appear if each case contains more than one condition

**Comment by guoyuhao2330** [comment]
> I think I found what is causing this bug. the Switch module in the first picture is from the DB assistant template which has the Logical operator option. But when I drag and drop a new Switch module from the left tab, the Logical operator option disappears. As I am not familiar with front end, sorry I can't provide a fix, please help with this issue, thanks. @KevinHuSh
> 
> ![image](https://private-user-images.githubusercontent.com/34462246/362159709-0d7d82a7-7eb9-4b3a-8de9-e4b7ef643a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzEyNzIsIm5iZiI6MTcyNDgzMDk3MiwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk3MDktMGQ3ZDgyYTctN2ViOS00YjNhLThkZTktZTRiN2VmNjQzYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTQ0MGQ4NTVlYzE2OTFiMjZiMDNiNmY5ODVjODlkOTg2ZTdjMWVkMTkxMzc3YjI0OGU1NTZiMGUxMTNjOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pw1UoAtkT3sX8p-IDdzYCFNIEz8bTE1O4We6qz_nlVo) ![image](https://private-user-images.githubusercontent.com/34462246/362159467-9e46053c-e57f-41fa-96e1-bc2beee59463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzEyNzIsIm5iZiI6MTcyNDgzMDk3MiwicGF0aCI6Ii8zNDQ2MjI0Ni8zNjIxNTk0NjctOWU0NjA1M2MtZTU3Zi00MWZhLTk2ZTEtYmMyYmVlZTU5NDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTM1MmYwNTRmYWUxYzU2NGVmZWEzODlkM2IwMjNmMmMxZDc3ZjI0MTg1ZWY5OTQ1OGE5NzZhMGFmMGI1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LqHDiBCXvfjBBzRYpYda5gpyiSHFlDXBKjwqOkfcYc)

The logical operators only appear if each case contains more than one condition

**Comment by cyhasuka** [comment]
> > I think I found what is causing this bug. the Switch module in the first picture is from the DB assistant template which has the Logical operator option. But when I drag and drop a new Switch module from the left tab, the Logical operator option disappears. As I am not familiar with front end, sorry I can't provide a fix, please help with this issue, thanks. @KevinHuSh
> 
> The logical operators only appear if each case contains more than one condition

But why is it reporting the error in the first picture condition?

**Comment by guoyuhao2330** [comment]
![image](https://github.com/user-attachments/assets/15271a39-26fa-4890-877d-5771c18b3083)
This is the condition I set, you can change it and set different conditions according to your needs.

**Comment by cyhasuka** [comment]
> ![image](https://private-user-images.githubusercontent.com/43509927/362197360-15271a39-26fa-4890-877d-5771c18b3083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzM1NDksIm5iZiI6MTcyNDgzMzI0OSwicGF0aCI6Ii80MzUwOTkyNy8zNjIxOTczNjAtMTUyNzFhMzktMjZmYS00ODkwLTg3N2QtNTc3MWMxOGIzMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljODhiZWUzN2I2Y2ViZWJlN2Q0NTNiYmYyOWViMGFkNjZiYmQ4YzIyNWIxZTJkZTkwYTQ0ZDRhYTM2ZGI0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3abcmK_9uK6UaR1vP0BxZpykOQmrFpM6yxBrhkoTxU) This is the condition I set, you can change it and set different conditions according to your needs.

I tried adding two identical condition and selecting “or” in the condition tab and the error disappeared. Perhaps the initial value of the condition is not set correctly causing the problem?

**Comment by guoyuhao2330** [comment]
Yeah there is an error in the check function

**Comment by cyhasuka** [comment]
Fixed, close this issue.
