### ISSUE TITLE
All documents in the knowledge base cannot be selected if they have not been parsed.

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#214]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

080cbd96e8330e327703dc6b50bc703fdfe5a42c

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/8089971/e580162d-149d-42ed-881d-7123beb35458)

![image](https://github.com/infiniflow/ragflow/assets/8089971/cea5d535-8613-4f3f-8cd7-b5b19d43ecea)

### Expected behavior

All documents in the knowledge base cannot be selected if they have not been parsed.

### Steps to reproduce

```Markdown
![image](https://github.com/infiniflow/ragflow/assets/8089971/e580162d-149d-42ed-881d-7123beb35458)

![image](https://github.com/infiniflow/ragflow/assets/8089971/cea5d535-8613-4f3f-8cd7-b5b19d43ecea)
```

**Comment by KevinHuSh** [comment]
fixed!
