### ISSUE TITLE
[Question]: Finetuning the OCR models

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2156]
### Describe your problem

Is it possible for users to somehow finetune the OCR models themselves? Since multiple models are donwloaded into the deepdoc folder, is there any available script or any recommended way to further fine-tune those models based on custom data?

**Comment by KevinHuSh** [comment]
RAGFlow uses [paddleOCR](https://github.com/PaddlePaddle/PaddleOCR).

**Comment by KevinHuSh** [comment]
Layouts recognition and table structure recognition all use Yolov8.
Nothing special on hyper-parameters.
Please refer to [this](https://github.com/infiniflow/ragflow/issues/2156) for trainning.
