### ISSUE TITLE
[Question]: How to increase Max token for Agent

### ISSUE THREAD

**Issue by saineshwar** [infiniflow/ragflow#2163]
### Describe your problem

Is there any option to increase Max token of Agent Chat.
![image](https://github.com/user-attachments/assets/16ffc5a6-4740-443a-9a18-02173b7e30e8)

**Comment by guoyuhao2330** [comment]
click:
![image](https://github.com/user-attachments/assets/3bfd661d-0b7d-4a7c-a0e9-6b14b729337e)

**Comment by saineshwar** [comment]
> click: ![image](https://private-user-images.githubusercontent.com/43509927/363056050-3bfd661d-0b7d-4a7c-a0e9-6b14b729337e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTk0MzcsIm5iZiI6MTcyNDk5OTEzNywicGF0aCI6Ii80MzUwOTkyNy8zNjMwNTYwNTAtM2JmZDY2MWQtMGI3ZC00YTdjLWEwZTktNmIxNGI3MjkzMzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA2MjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZDhkYjUwYzFlNmZjMjE0MTAxODJjOTg4NmI0MzI2ZDQ4ZmE2YzhiYTMxYmVhNzBhOTBkZjJkYTgzODcxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KRUcZsdIEV-Zo2jpb-oRX4fXnCefmkSuX1o4mViUtwM)

Here we select Model Name

**Comment by guoyuhao2330** [comment]
![image](https://github.com/user-attachments/assets/4d7bc7e3-29f3-4aaa-a706-7ac9d246edf9)

**Comment by saineshwar** [comment]
@guoyuhao2330 thank you
