### ISSUE TITLE
[Question]: Realtime synonym is disabled,and xpending rangetask consumer no such key 

### ISSUE THREAD

**Issue by ouyang11111** [infiniflow/ragflow#2168]
### Describe your problem

<img width="578" alt="1724932292674" src="https://github.com/user-attachments/assets/bddda95b-0bc6-44e2-9cd4-fd19a677908c">
when I run : docker logs-fragflow-server
it shows this warning   
and I can not runing below address:(I am not change address in docker-compose-CN.yml )
    * Running on all addresses (0.0.0.0)
    * Running on http://127.0.0.1:9380
    * Running on http://x.x.x.x:9380

**Comment by KevinHuSh** [comment]
You could ignore that infomation or pull dev images of docker.
