### ISSUE TITLE
For any type of file, if the parsing method is general, the chunk token number needs to be displayed.

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#217]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

963533bc2718dab294b9094beec8f53f2b9c6429

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/8089971/640577f4-a7ad-4394-a22c-4ab4db336491)

### Expected behavior

For any type of file, if the parsing method is general, the chunk token number needs to be displayed.

### Steps to reproduce

```Markdown
![image](https://github.com/infiniflow/ragflow/assets/8089971/640577f4-a7ad-4394-a22c-4ab4db336491)
```

**Comment by KevinHuSh** [comment]
fixed
