### ISSUE TITLE
[Bug]: UI defect when file name is large

### ISSUE THREAD

**Issue by GunjanGMG** [infiniflow/ragflow#2170]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

demo

### Actual behavior

when the file name is large, the popup window isn't rendered properly

![image](https://github.com/user-attachments/assets/34e62604-b090-4fc6-94b5-d02c4324b332)

### Expected behavior

filename should be wrapped

### Steps to reproduce

```Markdown
upload a pdf with 120 character name and search for it.
```

**Comment by cike8899** [comment]
Fixed
