### ISSUE TITLE
[Bug]: Glitched scroller in Knowledge Base-Configuration page

### ISSUE THREAD

**Issue by Randname666** [infiniflow/ragflow#2172]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.10.0

### Commit ID

e18f07

### Other environment information

```Markdown
Client:
Mozilla Firefox 130.0b8 / Chromium Edge 128.0.2739.42 
Windows 10 Professional version 19045.4780

Server:
Ubuntu 24.04
Nginx 1.24.0-2ubuntu7
```

### Actual behavior

When the scroller of "Embedding Model" is scrolled over to a certain point (I believe it's "PerfXCloud" section), items in the scroller begin to duplicate and override all contents before and after it, resulting in other options not being selectable anymore.
![bug](https://github.com/user-attachments/assets/20f1bdce-151f-4af7-8c78-fa43831010e9)

### Expected behavior

The scroller is able to display and select all the available options without missing, duplicating, or overriding items.

### Steps to reproduce

```Markdown
Create a new knowledge base, then enter the configuration page, click Embedding Model to open the scroller and scroll it down to the point mentioned.
```

### Additional information

No particular error message has been shown in browser console.

**Comment by KevinHuSh** [comment]
It's fixed for dev version of image and demo.
