### ISSUE TITLE
Encounter errors

### ISSUE THREAD

**Issue by lizhen-lizhen** [infiniflow/ragflow#2173]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

主要

### Commit ID

11

### Actual behavior

S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /0accee98667211efacb10242c0a82006/1-1%E9%A4%90%E9%A5%AE%E9%A3%9F%E5%93%81%E8%90%A5%E5%85%BB%E6%A0%87%E8%AF%86%E6%8C%87%E5%8D%97-%E9%97%AE%E7%AD%94.pdf, request_id: 17F06A0998666FE3, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 0accee98667211efacb10242c0a82006, object_name: 1-1-问答.pdf
401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/usr/local/lib/python3.10/dist-packages/flask_login/login_manager.py", line 178, in unauthorized
    abort(401)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

### Steps to reproduce

```Markdown
如何解决呢
```

**Comment by KevinHuSh** [comment]
Unauthorized.
You need to login firstly.

**Comment by lizhen-lizhen** [comment]
我登录了啊，主要那个s3的错误如何修改。

**Comment by KevinHuSh** [comment]
Make sure password of minio in docker/.env and conf/service_conf.yaml is the same.

**Comment by newnob6** [comment]
i found this bug produced by domain name binding. if you use ip to access the web，the error will not show. i guess the error is caused by flask in domain name binding.
