### ISSUE TITLE
[Question]: In application we are going to have only single user. Any reason it is blocked. 

### ISSUE THREAD

**Issue by saineshwar** [infiniflow/ragflow#2174]
### Describe your problem

We want to use it for 3 to 4 users for the Admin end. Why is it blocked because it is available in a commercial version or not developed only?

**Comment by JinHai-CN** [comment]
> ### Describe your problem
> 
> We want to use it for 3 to 4 users for the Admin end. Why is it blocked because it is available in a commercial version or not developed only?

It could be used for multiple users now. Each user can register its own account. Which function blocks your usage?

**Comment by KevinHuSh** [comment]
It's under development.

**Comment by saineshwar** [comment]
> It's under development.

Till that time any other solution we have. One user's login is blocking the use of this product. can we remove this check?

**Comment by KevinHuSh** [comment]
Sorry, no.

**Comment by KevinHuSh** [comment]
If you just want to chat, you could use this part of functions.
![image](https://github.com/user-attachments/assets/080fb3a7-43c1-4c4e-a288-fd7b638cb43d)
