### ISSUE TITLE
[Question]: Failed to open http://127.0.0.1

### ISSUE THREAD

**Issue by LucasZen** [infiniflow/ragflow#2183]
Executing docker logs -f ragflow-server seems to be normal.
![image](https://github.com/user-attachments/assets/0a9932da-b0d1-493b-a974-21472fff8eb2)
but:
![image](https://github.com/user-attachments/assets/4af83762-aaf5-4b94-8074-8c9757df60d1)

It was accessible a few days ago, but today it suddenly stopped working. Even after reinstalling, it still can't be opened. How can this be resolved?

**Comment by JinHai-CN** [comment]
http://127.0.0.1:9380

**Comment by LucasZen** [comment]
> Looks like you didn't fill in the port. Have you tried http://127.0.0.1:9380 ?
Yes, I have tried http://127.0.0.1:9380, but this is what was returned.
![image](https://github.com/user-attachments/assets/dbde403d-b951-4169-bf8b-558f7fe9b737)

I have not made any changes to the configuration, and I was able to log in successfully using http://127.0.0.1 before. I followed these instructions.
![image](https://github.com/user-attachments/assets/750ab266-4378-4179-bb76-4ee497352ae7)

**Comment by KevinHuSh** [comment]
You need to start Nginx.
Or port 80 has been restricted.

**Comment by LucasZen** [comment]
> You need to start Nginx. Or port 80 has been restricted.
yes, port 80 has been restricted. I changed the port and it's working properly now.
Thank you for your help.
