### ISSUE TITLE
[Question]: How to add a new local rerank model

### ISSUE THREAD

**Issue by guijuzhejiang** [infiniflow/ragflow#2185]
### Describe your problem

Great works. How to add a new local rerank model. Don't want to use ollama because ollama doesn't support rerank models. just put it in the ~/.ragflow directory like the default BAAI/bge-reranker-v2-m3 model, but where do I need to change all the configuration files? Do I need to add the new reranker in conf/llm_factories.json?

**Comment by hangters** [comment]
hi @guijuzhejiang  You can use LM_Studio to add a local reranker model or select one from [https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/llm_reranker](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/llm_reranker). After downloading, add it to the `~/.ragflow` directory, and then include the model you want to add under the `BAAI` section in the `conf/llm_factories` file.here  
<img width="920" alt="2" src="https://github.com/user-attachments/assets/61a2ff19-1c1c-45b4-b67c-6a3e280969c8">, then restart  ragflow

**Comment by guijuzhejiang** [comment]
@hangters clever, thank you, I added the new reranking model the way you said!

**Comment by Tofuu-2202** [comment]
> [@hangters](https://github.com/hangters) clever, thank you, I added the new reranking model the way you said!

You used lm_studio or which one?
