### ISSUE TITLE
[Question]: access http://localhost:9380/favicon.ico  Tips ：{"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"}

### ISSUE THREAD

**Issue by NlMay** [infiniflow/ragflow#2186]
### Describe your problem

{"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"} 
How to deal with this problem?

**Comment by KevinHuSh** [comment]
Do not user port number. Try this: http://localhost

**Comment by mintisan** [comment]
@KevinHuSh it works, thanks

**Comment by NlMay** [comment]
![image](https://github.com/user-attachments/assets/bd8dd3d4-f044-44a3-b39e-9d07015db7aa)
![image](https://github.com/user-attachments/assets/a497cb55-aa7e-4a91-af25-b07283d589a4)
I tried to remove the port access and the result was the same。
response data:
Failed to load response data : no resource with given identifier.
How should I handle this issue?

**Comment by zc317414** [comment]
> Do not user port number. Try this: http://localhost

502 Bad Gateway
nginx/1.24.0 (Ubuntu)

**Comment by nakroy** [comment]
The problem is if do not use hostPort 80 & 443, we can't visit the web
