### ISSUE TITLE
[Question]: Excel file how to set the segmentation tokens number correctly

### ISSUE THREAD

**Issue by guijuzhejiang** [infiniflow/ragflow#2187]
### Describe your problem

When I enter an excel file into the knowledge base, no matter how many Tokens numbers are set in the configuration, the split result is the same, and each block has a lot of content, even I seted the number of block Token=16, the content of each block that is split is also very long. How to set the segmentation block correctly?

**Comment by KevinHuSh** [comment]
Excel being splited by token number is inappropriate, which will destroy the semantic.
Every chunk is composed of a row in Execl with columns such as: coloumnA: A1; coloumnB: B1; ...

**Comment by guijuzhejiang** [comment]
@KevinHuSh Thanks for your reply, Agree with you. I've tested it, and it seems like the content of a sheet is divided into a chunk. But some sheets have too much content and are also split into multiple chunks. Am I understanding this correctly? What are the rules for splitting one sheet into multiple chunks?

**Comment by KevinHuSh** [comment]
After spliting a table into rows, it will merge rows into chunk by 'chunk token number'. But row is still the minimum unit to merge.

**Comment by guijuzhejiang** [comment]
Viewed the excel to html code, which the chunk_rows parameter is a fixed value of 256, meaning that an excel sheet if the number of rows is less than 256, the entire sheet as a chunk, the number of rows is greater than 256, it will be 256 rows divided into a chunk.

**Comment by guijuzhejiang** [comment]
Add: Sorry I didn't specify the parsing method at the beginning, the parsing method I'm using is general, the parsing method you said may be table
