### ISSUE TITLE
[Question]: Failed to parse any local file

### ISSUE THREAD

**Issue by Vickzhang** [infiniflow/ragflow#219]
### Describe your problem

After deployed with the pre-built docker images and started up the ragflow server, I could successfully access the ragflow  web page, but failed to parse any pdf file in the knowlege base.

**All configurations follow the official configuration, except for the service port of Minio in the ./docker/docker-compose.yml**

> minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - 19000:9000
      - 19011:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}

ERROR msg:

> ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_0eea0066f16411eeadae0242ac150006]', ragflow_0eea0066f16411eeadae0242ac150006, index_or_alias)【Q】：{'match': {'doc_id': '9f5aac32f18611eeb9eb0242ac150006'}}
> Fail put 55d6b0f0f16411ee90d40242ac150006/xxxxxx_my_test_file.pdf: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /55d6b0f0f16411ee90d40242ac150006/26-Tesla%20Model%20X%E8%AF%8A%E6%96%AD%E5%AF%B9%E6%A0%87%E6%8A%A5%E5%91%8A20171013.pdf, request_id: 17C2B3E1E8FCF95A, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 55d6b0f0f16411ee90d40242ac150006, object_name: -xxxxxx_my_test_file.pdf

**Comment by KevinHuSh** [comment]
It seems minio not successfully started.
`docker restart ragflow-minio`

Or, the minio password error. 

Keep these 2 values consistent:
docker/.env: MINIO_PASSWORD
docker/service_conf.yml: minio.password

**Comment by GuoCoder** [comment]
我也有同样的问题。
自己重启了ragflow-minio，核对了密码。
ERROR.log
>Fail put 2fc35944f88b11ee8ba90242c0a87005/zhiu.docx: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /2fc35944f88b11ee8ba90242c0a87005/zhiu.docx, request_id: 17C5BA3B05CAA16C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 2fc35944f88b11ee8ba90242c0a87005, object_name: zhiu.docx
ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_246d31dcf88b11eea3710242c0a87005]', ragflow_246d31dcf88b11eea3710242c0a87005, index_or_alias)【Q】：{'match': {'doc_id': '6d2aff86f94811ee8c2f0242c0a8c005'}}


## 问题：
![Uploading image.png…]()

**Comment by GuoCoder** [comment]
我也有同样的问题。
自己重启了ragflow-minio，核对了密码。
ERROR.log
>Fail put 2fc35944f88b11ee8ba90242c0a87005/zhiu.docx: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /2fc35944f88b11ee8ba90242c0a87005/zhiu.docx, request_id: 17C5BA3B05CAA16C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 2fc35944f88b11ee8ba90242c0a87005, object_name: zhiu.docx
ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_246d31dcf88b11eea3710242c0a87005]', ragflow_246d31dcf88b11eea3710242c0a87005, index_or_alias)【Q】：{'match': {'doc_id': '6d2aff86f94811ee8c2f0242c0a8c005'}}


## 问题：
![Uploading image.png…]()

**Comment by hhzxxx** [comment]
> 我也有同样的问题。 自己重启了ragflow-minio，核对了密码。 查看了ragflow-minio容器，数据已经上传成功，不过ERROR.log还是没变。
> 
> ERROR.log
> 
> > Fail put 2fc35944f88b11ee8ba90242c0a87005/zhiu.docx: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /2fc35944f88b11ee8ba90242c0a87005/zhiu.docx, request_id: 17C5BA3B05CAA16C, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 2fc35944f88b11ee8ba90242c0a87005, object_name: zhiu.docx
> > ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_246d31dcf88b11eea3710242c0a87005]', ragflow_246d31dcf88b11eea3710242c0a87005, index_or_alias)【Q】：{'match': {'doc_id': '6d2aff86f94811ee8c2f0242c0a8c005'}}
> 
> ## 问题：
> ![image](https://private-user-images.githubusercontent.com/166698373/322174479-c0a78aa6-6d0e-45ae-9ce6-34886fddcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzUxNzQsIm5iZiI6MTcxMzI3NDg3NCwicGF0aCI6Ii8xNjY2OTgzNzMvMzIyMTc0NDc5LWMwYTc4YWE2LTZkMGUtNDVhZS05Y2U2LTM0ODg2ZmRkY2Y5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMzQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzQ5MzA5YTY5MTBhMmM4YzI0NGE2YjA2MTdiOGZhNTlmMDg3MmYzNDNkMjRiYmUzNjg0MWJjZjYyMzczNzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbewaHr4h0F6dVat5H5jakDj2AlTeSim_50RzwxeigI)

请问一下你解决了吗，我也是同样问题

**Comment by GuoCoder** [comment]
我跑通了，写了篇文章记录问题：https://mp.weixin.qq.com/s/XhcOqphdV4a7yESbTlfYZQ

**Comment by acbp1379** [comment]
> image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z

老哥你怎么解决的，我现在上传文件，同一个文件，10次上传，能有4 5次失败的。    就报fail put这个错
