### ISSUE TITLE
[Bug]: CV LLM to describe a picture   Error

### ISSUE THREAD

**Issue by mayonggang** [infiniflow/ragflow#2198]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Other environment information

```Markdown
docker  ubuntu22.04
```

### Actual behavior

流程开始于:
Mon, 02 Sep 2024 09:28:50 GMT
过程持续时间:
2.24 s
进度消息:
Task has been received.
Finish OCR: (T
China ...)
Use CV LLM to describe the picture.
[ERROR]Error code: 400, with error text {"error":{"code":"1214","message":"messages[0].content[1].type:不能为空"}}
No chunk! Done!

### Steps to reproduce

```Markdown
流程开始于:
Mon, 02 Sep 2024 09:28:50 GMT
过程持续时间:
2.24 s
进度消息:
Task has been received.
Finish OCR: (T
China ...)
Use CV LLM to describe the picture.
[ERROR]Error code: 400, with error text {"error":{"code":"1214","message":"messages[0].content[1].type:不能为空"}}
No chunk! Done!
```

### Additional information

是

**Comment by hangters** [comment]
hi @mayonggang I would like to know which CV model you are using. The settings page is located in the system settings of the model provider.

**Comment by mayonggang** [comment]
> hi @mayonggang I would like to know which CV model you are using. The settings page is located in the system settings of the model provider.

it should be GLM-4V

**Comment by mayonggang** [comment]
![微信图片_20240903125911](https://github.com/user-attachments/assets/8e67253d-3623-47d0-b7d3-01bc0c463a80)

**Comment by mayonggang** [comment]
@hangters 

![微信图片_20240903125911](https://github.com/user-attachments/assets/404d0b2b-3475-482f-ae84-4a13b021da96)

**Comment by hangters** [comment]
Got it, this issue will be fixed soon.

**Comment by mayonggang** [comment]
> Got it, this issue will be fixed soon.

thank you very mush

**Comment by mayonggang** [comment]
error msg is changed like under info. [ERROR]Request **Timeout**

流程开始于:
Tue, 03 Sep 2024 10:30:40 GMT
过程持续时间:
9.38 s
进度消息:
Task has been received.
Finish OCR: (T
China ...)
Use CV LLM to describe the picture.
[ERROR]Request Timeout
No chunk! Done!

**Comment by hangters** [comment]
It appears to be a network connection issue, possibly related to your internet connection or Zhipu's server. If the problem persists, please let me know, and I will make further adjustments.

**Comment by mayonggang** [comment]
> It appears to be a network connection issue, possibly related to your internet connection or Zhipu's server. If the problem persists, please let me know, and I will make further adjustments.

Even if the CV model is changed to qwen-vl-max, the error still appears to be a network related issue  like under infomation:


流程开始于:
Tue, 03 Sep 2024 11:04:56 GMT
过程持续时间:
32.10 s
进度消息:
Task has been received.
Finish OCR: (T
China ...)
Use CV LLM to describe the picture.
[ERROR]HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/uploads?action=getPolicy&model=qwen-vl-max (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
No chunk! Done!

**Comment by mayonggang** [comment]
maybe I should change the timeout value  cauce cv_model is more time-cost. where can i change timeout of cv-model

**Comment by mayonggang** [comment]
it seems like  after changed the source code and re-docker building the package, this kind of network problem will occur. Not only the CVmodel request times out, but also the chat model does not work.
