### ISSUE TITLE
[Bug]: pip install -r requirements.txt error!

### ISSUE THREAD

**Issue by jojogh** [infiniflow/ragflow#220]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

aae84f6

### Other environment information

```Markdown
Collecting accelerate==0.27.2 (from -r requirements.txt (line 1))
  Downloading accelerate-0.27.2-py3-none-any.whl (279 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.0/280.0 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: aiohttp==3.9.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (3.9.3)
Requirement already satisfied: aiosignal==1.3.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: annotated-types==0.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (0.6.0)
Collecting anyio==4.3.0 (from -r requirements.txt (line 5))
  Downloading anyio-4.3.0-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 13.8 MB/s eta 0:00:00
Requirement already satisfied: argon2-cffi==23.1.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (23.1.0)
Requirement already satisfied: argon2-cffi-bindings==21.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (21.2.0)
Collecting Aspose.Slides==24.2.0 (from -r requirements.txt (line 8))
  Downloading Aspose.Slides-24.2.0-py3-none-manylinux1_x86_64.whl (88.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.7/88.7 MB 2.6 MB/s eta 0:00:00
Requirement already satisfied: attrs==23.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (23.2.0)
Collecting blinker==1.7.0 (from -r requirements.txt (line 10))
  Downloading blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting cachelib==0.12.0 (from -r requirements.txt (line 11))
  Downloading cachelib-0.12.0-py3-none-any.whl (20 kB)
Requirement already satisfied: cachetools==5.3.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (5.3.3)
Requirement already satisfied: certifi==2024.2.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (2024.2.2)
Requirement already satisfied: cffi==1.16.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: charset-normalizer==3.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (3.3.2)
Requirement already satisfied: click==8.1.7 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 16)) (8.1.7)
Collecting coloredlogs==15.0.1 (from -r requirements.txt (line 17))
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 7.2 MB/s eta 0:00:00
Requirement already satisfied: cryptography==42.0.5 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 18)) (42.0.5)
Collecting dashscope==1.14.1 (from -r requirements.txt (line 19))
  Downloading dashscope-1.14.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 86.1 MB/s eta 0:00:00
Collecting datasets==2.17.1 (from -r requirements.txt (line 20))
  Downloading datasets-2.17.1-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.7/536.7 kB 57.4 MB/s eta 0:00:00
Collecting datrie==0.8.2 (from -r requirements.txt (line 21))
  Downloading datrie-0.8.2.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 kB 9.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting demjson==2.2.4 (from -r requirements.txt (line 22))
  Downloading demjson-2.2.4.tar.gz (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.5/131.5 kB 17.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Actual behavior

pip install -r -r requirements.txt 

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected behavior

pip install -r -r requirements.txt  will be successful

### Steps to reproduce

```Markdown
1. pip install -r requirements.txt
2. Error happened again.
```

### Additional information

Collecting accelerate==0.27.2 (from -r requirements.txt (line 1))
  Using cached accelerate-0.27.2-py3-none-any.whl (279 kB)
Requirement already satisfied: aiohttp==3.9.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (3.9.3)
Requirement already satisfied: aiosignal==1.3.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: annotated-types==0.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (0.6.0)
Collecting anyio==4.3.0 (from -r requirements.txt (line 5))
  Using cached anyio-4.3.0-py3-none-any.whl (85 kB)
Requirement already satisfied: argon2-cffi==23.1.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (23.1.0)
Requirement already satisfied: argon2-cffi-bindings==21.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (21.2.0)
Collecting Aspose.Slides==24.2.0 (from -r requirements.txt (line 8))
  Using cached Aspose.Slides-24.2.0-py3-none-manylinux1_x86_64.whl (88.7 MB)
Requirement already satisfied: attrs==23.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (23.2.0)
Collecting blinker==1.7.0 (from -r requirements.txt (line 10))
  Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting cachelib==0.12.0 (from -r requirements.txt (line 11))
  Using cached cachelib-0.12.0-py3-none-any.whl (20 kB)
Requirement already satisfied: cachetools==5.3.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (5.3.3)
Requirement already satisfied: certifi==2024.2.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (2024.2.2)
Requirement already satisfied: cffi==1.16.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: charset-normalizer==3.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (3.3.2)
Requirement already satisfied: click==8.1.7 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 16)) (8.1.7)
Collecting coloredlogs==15.0.1 (from -r requirements.txt (line 17))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: cryptography==42.0.5 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 18)) (42.0.5)
Collecting dashscope==1.14.1 (from -r requirements.txt (line 19))
  Using cached dashscope-1.14.1-py3-none-any.whl (1.2 MB)
Collecting datasets==2.17.1 (from -r requirements.txt (line 20))
  Using cached datasets-2.17.1-py3-none-any.whl (536 kB)
Collecting datrie==0.8.2 (from -r requirements.txt (line 21))
  Using cached datrie-0.8.2.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting demjson==2.2.4 (from -r requirements.txt (line 22))
  Using cached demjson-2.2.4.tar.gz (131 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by KevinHuSh** [comment]
try this:

`pip install --upgrade setuptools==57.5.0`

**Comment by jojogh** [comment]
if you have installed blink>=1.7.0, you have to remove it first by following commands:
!sudo apt-get remove blinker
!sudo -H pip install --ignore-installed -U blinker

**Comment by le-dawg** [comment]
Such an in-obvious solution .... "not a supported wheel on this platform" is very misdirecting as an error msg!
