### ISSUE TITLE
[Question]: how to launch service from source in an environment of windows and Vscode

### ISSUE THREAD

**Issue by fangnster** [infiniflow/ragflow#2201]
### Describe your problem

Whether we could execute the first page's steps of official "launch service from source" successfully in an environment of windows and Vscode. Or it is necessary of modify the scripts in steps .

**Comment by KevinHuSh** [comment]
I recomand to start it and debug it by docker container as long as you're not quite familiar with it, which will make an easy start for you.

**Comment by fangnster** [comment]
Do you mean that I need build a updated docker image from source every time to deploy it to container in development stage ?

> I recomand to start it and debug it by docker container as long as you're not quite familiar with it, which will make an easy start for you.

Do you mean that I need build a updated docker image from source every time to deploy it to container in development stage ?

**Comment by yuzhichang** [comment]
Run containers or launch from code in WSL2 is much easier than porting code from linux to windoes.

**Comment by peak-xu** [comment]
@yuzhichang Can you please advise on how to set breakpoints for debugging
