### ISSUE TITLE
[Question]: How to make huqie.txt files for other languages

### ISSUE THREAD

**Issue by guijuzhejiang** [infiniflow/ragflow#2208]
### Describe your problem

How to make huqie.txt files, or is there a download address for huqie.txt files in other languages?

**Comment by KevinHuSh** [comment]
This is for Chinese tokenization.
Other language you mean...?

**Comment by guijuzhejiang** [comment]
Yes, for other small languages languages, e.g. Korean, Japanese, etc. I was able to find the word document, but the numbers in the middle that I don't know how to write. For example, in ‘左移 17 nr’, how to count the number 17 in the middle? Or is there a link to a similar file in another language?

**Comment by KevinHuSh** [comment]
The number in the middle represents the degree of frequency it exists in a text corpus.
The bigger it is, the more popular the term is, the less informative it is.

**Comment by guijuzhejiang** [comment]
Thanks for the reply, I see, the middle number represents the word frequency which is related to the data corpus.

**Comment by ZhenhangTung** [comment]
@guijuzhejiang How are you handling this issue right now? Did you fork the repository and modify huqie.txt yourself?
