### ISSUE TITLE
[Bug]:SILICONFLOW Retrieval testing BAAI/bge-reranker-v2-m3  KeyError('results')

### ISSUE THREAD

**Issue by liangtongt** [infiniflow/ragflow#2231]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev

### Commit ID

sha256:fad795902597a18360247749de74166783e6704b1557a13e019efdf089191506

### Actual behavior

![微信截图_20240904102822](https://github.com/user-attachments/assets/b732ec2f-1c03-47b5-a695-60d0208b9bda)
![微信截图_20240904103705](https://github.com/user-attachments/assets/ea828c8a-654d-4e9b-b196-545dc89b296f)

### Steps to reproduce

```Markdown
As shown in the above figure
```

**Comment by Zhangsir125** [comment]
docker logs -f ragflow-server去查看日志，应该是在下载模型

**Comment by emptinessboy** [comment]
1.0.12版本使用本地模型运行正常，使用硅基流动模型，当**关键词没有命中时**会出现KeyError('results')。

我猜测可能是硅基流动模型对response做了处理，未命中时不返回result字段；而本地不论是否命中都有result字段返回。可能这两处差异导致了json解析中出现问题。
