### ISSUE TITLE
[Question]: add  azure-openai  error

### ISSUE THREAD

**Issue by wdqzdd** [infiniflow/ragflow#2236]
### Describe your problem

![image](https://github.com/user-attachments/assets/f2d5df0f-2b5e-4402-85f7-8f3ab041c468)

![image](https://github.com/user-attachments/assets/69230f4c-21aa-45a9-988d-5512f51f704f)

Azure-OpenAI不是应该有四个参数的吗?

**Comment by wdqzdd** [comment]
openai怎么指定模型?
![image](https://github.com/user-attachments/assets/c59f775c-03ab-4efa-976b-df735825921a)

**Comment by hangters** [comment]
For the Azure-OpenAI model provider, we have added the models it offers under `conf/llm_factories`. You just need to apply for an API key to access all its models.  see here:
<img width="433" alt="image" src="https://github.com/user-attachments/assets/8c5a4265-810b-4dfd-b5ca-818ad1746bbc">
If you want to specify a model using the OpenAI interface, you can add it in the `openai-api-compatible` section.
![image](https://github.com/user-attachments/assets/371be073-ef0c-457c-931c-7f57bd892e6f)

**Comment by wdqzdd** [comment]
> For the Azure-OpenAI model provider, we have added the models it offers under `conf/llm_factories`. You just need to apply for an API key to access all its models. see here: <img alt="image" width="433" src="https://private-user-images.githubusercontent.com/101850389/365494564-8c5a4265-810b-4dfd-b5ca-818ad1746bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTA2MzUsIm5iZiI6MTcyNTg1MDMzNSwicGF0aCI6Ii8xMDE4NTAzODkvMzY1NDk0NTY0LThjNWE0MjY1LTgxMGItNGRmZC1iNWNhLTgxOGFkMTc0NmJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmUzNjY0MDJlYzE3ZjRiYWUyYzNlNTNlZjk3YjRiZWY5NDI5OTAxYzU5MDNjZjljMjc2Zjc5MWQ4ZjZhMThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OZNTvmVR5zeicySeMc6aTmFK2PRLPP63Y_qRzYHyrJw"> If you want to specify a model using the OpenAI interface, you can add it in the `openai-api-compatible` section. ![image](https://private-user-images.githubusercontent.com/101850389/365494787-371be073-ef0c-457c-931c-7f57bd892e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTA2MzUsIm5iZiI6MTcyNTg1MDMzNSwicGF0aCI6Ii8xMDE4NTAzODkvMzY1NDk0Nzg3LTM3MWJlMDczLWVmMGMtNDU3Yy05MzFjLTdmNTdiZDg5MmU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTQxNTc3YTlmMTI5MmUyZGJkNjA5NWVmOTVjNDJiYmI1MGFmMDI0MGFmMjJmZjBmZDM5ZDk4YTMxODVmOTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDB5mu66Jm_kdQp4Hiu10hiMpU76EHu73K8Mb-D20dc)

我们Azure-OpenAI model 的名字叫gpt-4o不叫你们配置的Azure-gpt-4o。所以报错了。

**Comment by hangters** [comment]
Got it, we will fix it.

**Comment by lvyoudashuju** [comment]
> For the Azure-OpenAI model provider, we have added the models it offers under `conf/llm_factories`. You just need to apply for an API key to access all its models. see here: <img alt="image" width="433" src="https://private-user-images.githubusercontent.com/101850389/365494564-8c5a4265-810b-4dfd-b5ca-818ad1746bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTYxMjEsIm5iZiI6MTcyNjc5NTgyMSwicGF0aCI6Ii8xMDE4NTAzODkvMzY1NDk0NTY0LThjNWE0MjY1LTgxMGItNGRmZC1iNWNhLTgxOGFkMTc0NmJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMTMwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2IwYzE4YTZmYWNjMWNkNzgwN2IyOGU0MWVhMTIxY2E4MGFhM2IzNmExZGUzYWRjNzA5MTFjMDhjMDFjYmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hPZfSHg6uGg45ASulsReiTvwciEip166n-pVFRdgd4o"> If you want to specify a model using the OpenAI interface, you can add it in the `openai-api-compatible` section. ![image](https://private-user-images.githubusercontent.com/101850389/365494787-371be073-ef0c-457c-931c-7f57bd892e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTYxMjEsIm5iZiI6MTcyNjc5NTgyMSwicGF0aCI6Ii8xMDE4NTAzODkvMzY1NDk0Nzg3LTM3MWJlMDczLWVmMGMtNDU3Yy05MzFjLTdmNTdiZDg5MmU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMTMwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjRjYmJkOTgzNTkwMzJhYWQxYWVhZDFjN2Q3ZjIxNzJmNzA3ZTFhM2I1MGIyN2VkODI5NzEzZjZhMGEzODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IKVlQ_Luh9BHKhBl34LM75GkxoUI11o2eSsuh2eLdok)

![image](https://github.com/user-attachments/assets/c0454094-d2be-469d-af26-2f7d2b4549a1)
According to your changes, I changed conf/llm_factories.json. After restarting, I still cannot add the Azure_openai model.

**Comment by lvyoudashuju** [comment]
![image](https://github.com/user-attachments/assets/05fa4d82-5bfe-4fa8-81e4-4c7894bbba83)

Supplementary information, the model cannot be added, the error is as follows
