### ISSUE TITLE
[Bug]: API return 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Sure0520** [infiniflow/ragflow#2238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

none

### Other environment information

```Markdown
v0.10.0
```

### Actual behavior

调用  /v1/api/completion 接口返回错误。
{
  "status_code": 200,
  "body": "{\"data\":null,\"retcode\":100,\"retmsg\":\"TypeError(\\\"'NoneType' object is not subscriptable\\\")\"}\n",
  "headers": {
    "server": "nginx/1.18.0 (Ubuntu)",
    "date": "Wed, 04 Sep 2024 07:36:30 GMT",
    "content-type": "application/json",
    "content-length": "93",
    "cache-status": "f47f2fc580e9;detail=mismatch",
    "via": "1.1 f47f2fc580e9 (squid/6.6)",
    "connection": "keep-alive"
  },
  "files": []
}

请求参数如下：
{
  "request": "POST http://*****:28080/v1/api/completion HTTP/1.1\nContent-Type: multipart/form-data; boundary=----WebKitFormBoundaryulzypeboilyiwlrg\nAuthorization: ***********************************************\n\n------WebKitFormBoundaryulzypeboilyiwlrg\nContent-Disposition: form-data; name=\"conversation_id\"\n\n1231321231321321\n------WebKitFormBoundaryulzypeboilyiwlrg\nContent-Disposition: form-data; name=\"messages\"\n\n[{\"role\": \"user\", \"content\": \"How are you doing!\"}]\n------WebKitFormBoundaryulzypeboilyiwlrg--"
}

### Steps to reproduce

```Markdown
none
```

**Comment by prettyprettyboy** [comment]
同问

**Comment by prettyprettyboy** [comment]
解决了，把data用json=传进去而不要用data=传进去。但是后面我这边报错Conversation not found! 但是我上传了conversation_id这个参数的，而且这个参数是通过new_conversation这个api来得到的

**Comment by prettyprettyboy** [comment]
用json=传入，不要用data=传入，但是后续我会得到Conversation not found!的错误

**Comment by Sure0520** [comment]
> 用json=传入，不要用data=传入，但是后续我会得到Conversation not found!的错误

hi，
是否可以截图说明一下如何配置的？

**Comment by prettyprettyboy** [comment]
就是我这边是用requests去访问的，requests.post(url,json=｛｝)

**Comment by danhuazhou** [comment]
请求时需要`json`方式传入参数，必填参数是`conversation_id`和`messages`。其中`conversation_id`是`new_conversation`接口返回的`data.id`，`messages`是类似列表的格式`[{"role": "user", "content": "How are you doing!"}]`并不是个字符串。

**Comment by yuzhichang** [comment]
Here's code of `completion` handler: https://github.com/infiniflow/ragflow/blob/ea8a59d0b01b4edaa8aea6ceb4591e2e4c1cc001/api/apps/api_app.py#L187
