### ISSUE TITLE
[Bug]: API preview page of Chat and Agent are not compliant with test result.

### ISSUE THREAD

**Issue by Aska7T** [infiniflow/ragflow#2242]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

240904172133

### Actual behavior

1、聊天的API预览页面不能显示引用的文档。
2、Agent的API预览页面的openning始终是hi！there。
以上两个在直接运行测试时表现正常。

### Steps to reproduce

```Markdown
在使用官方模版时表现依旧不一致。
```

**Comment by szfly888** [comment]
聊天的API预览页面不能显示引用的文档。请问你说的在直接运行测试时表现正常是什么意思，是本地化部署后可以显示引用文档吗？为什么我这边采用最新版本，在聊天预览界面还是无法显示引用文档，并且在此界面上传的文档打不开，一点文档马上退出登录。

**Comment by Aska7T** [comment]
> 聊天的API预览页面不能显示引用的文档。请问你说的在直接运行测试时表现正常是什么意思，是本地化部署后可以显示引用文档吗？为什么我这边采用最新版本，在聊天预览界面还是无法显示引用文档，并且在此界面上传的文档打不开，一点文档马上退出登录。

本地部署后，在聊天界面聊天是可以显示引用文档的，但是在聊天那里点“聊天API”按钮，那个界面里面的测试 Web App里面的预览是显示不了引用文档的。

**Comment by szfly888** [comment]
是的，聊天api打开界面后，上传文件，点击文件直接退出登录。这块设计的逻辑不清，希望尽快修复。
