### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by ouyang11111** [infiniflow/ragflow#2249]
web-UI can not open ### Describe your problem

![image](https://github.com/user-attachments/assets/fbed77b1-c0f2-4645-ba8b-34ecf1d065f6)
WSL2 
I follow READ.ME of Launch service from source(源码启动服务)  , I can not open the web-UI the  Email and password is useless . How to do?

**Comment by KevinHuSh** [comment]
Remember to start Nginx.
