### ISSUE TITLE
[Question]: Could you please teach me how to conduct question answering based on tables, which may involve filtering and summarizing calculations of table data?

### ISSUE THREAD

**Issue by tulei2006** [infiniflow/ragflow#2261]
### Describe your problem

For example, if the table has three columns: Year, Quarter, and Revenue, when asked about the revenue for a specific year, it involves obtaining all data for that year and then summing it up. How can this be done? Does RAG support such operations, and are there any future plans?

**Comment by KevinHuSh** [comment]
RAG do not support well.
I recommand you to use DB Assistant in agent.
