### ISSUE TITLE
[Bug]: [ERROR]too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by mayonggang** [infiniflow/ragflow#2263]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

none

### Other environment information

```Markdown
ubuntu docker
```

### Actual behavior

流程开始于:
Thu, 05 Sep 2024 03:11:01 GMT
过程持续时间:
3.45 s
进度消息:
Task has been received.
USE Sequence2Txt LLM to transcription the audio
Sequence2Txt LLM file_name: temp_3.wav ...
[ERROR]too many values to unpack (expected 2)
No chunk! Done!

### Steps to reproduce

```Markdown
audio file(wav) to embedding,  use  dashscope 'paraformer-realtime-8k-v1' asr model.
```

**Comment by hangters** [comment]
hi @mayonggang  When integrating the Qianwen ASR service, an issue was encountered. It is recommended to temporarily use another provider's ASR service.
