### ISSUE TITLE
[Bug]: Change RAGFlow port, after deploy the docker version. The profile photo can't be showed any more.

### ISSUE THREAD

**Issue by Zhangsir125** [infiniflow/ragflow#2268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

docker

### Commit ID

111

### Actual behavior

docker部署后修改端口号之后修改头像不显示

### Steps to reproduce

```Markdown
docker部署后修改端口号之后修改头像不显示
```

**Comment by KevinHuSh** [comment]
I think this is irrelevant with port alteration.
