### ISSUE TITLE
[Question]: Can I download only the basic file, not the model file, and directly connect to openai or other apis?

### ISSUE THREAD

**Issue by BigworldNebula** [infiniflow/ragflow#2295]
### Describe your problem

Can I download only the basic file, not the model file? Directly connect to openai or other apis, so that the amount of downloaded data is much smaller, and then run it in docker?

**Comment by JinHai-CN** [comment]
We're shrinking the RAGFlow docker image size by removing some python modules and the built-in models. This will be done before next release.

**Comment by BigworldNebula** [comment]
> We're shrinking the RAGFlow docker image size by removing some python modules and the built-in models. This will be done before next release.

Thanks for your reply and contribution to rag technology. By the way, when is the next release expected to be released and what size will the reduced docker image be?

**Comment by JinHai-CN** [comment]
> > We're shrinking the RAGFlow docker image size by removing some python modules and the built-in models. This will be done before next release.
> 
> Thanks for your reply and contribution to rag technology. By the way, when is the next release expected to be released and what size will the reduced docker image be?

1. Before Oct.
2. Still under evaluation.
