### ISSUE TITLE
[Bug]: Can not make file-embedding rework after stop it

### ISSUE THREAD

**Issue by yunc0701** [infiniflow/ragflow#2297]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

yunceng01

### Actual behavior

When I upload the file and start to parse and embedding it, if I stop it by clicking the red fork，it stopped, but never start to work again. Although restart the whole service,create new account ,all file can't be parsed anymore.

### Expected behavior

when the file is embedding, I can stop it by click the red fork. After it , I still can restart it or embedding other files correctly

### Steps to reproduce

```Markdown
1、upload a file;
2、start to embdding;
3、stop embdding by click the red fork;
4、restart it or try another file.
5、restart all service , it does't work anymore.
```

**Comment by KevinHuSh** [comment]
Can't reproduce it.
What about pulling the dev version of docker image?

**Comment by yunc0701** [comment]
I found the question. Because the disk space is not enough, so ES can't write data and throw " unassigned shards ". After freeing up disk space, the problem was resolved

**Comment by yunc0701** [comment]
this is not a bug, but lack of disk space and something wrong with ES

**Comment by yunc0701** [comment]
this is not a bug, but lack of disk space and something wrong with ES. Thanks.
















At 2024-09-09 12:35:00, "Kevin Hu" ***@***.***> wrote:

Can't reproduce it.
What about pulling the dev version of docker image?
