### ISSUE TITLE
[Bug]: the model_type field is fixed parameter "image2text" when using ollama to add a chat model on the webUI

### ISSUE THREAD

**Issue by laneado** [infiniflow/ragflow#2329]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

265a7a283ae1a29a4827d2a973d62cad14c41dc5

### Actual behavior

the model_type field is fixed parameter "image2text" when using ollama to add a chat model on the webUI，lead to I can not add a chat model

### Steps to reproduce

```Markdown
1. using ollama to deploy a chat model
2. using ollama add a chat model on the webUI
3. model_type select "chat" and add other paramters
4. click ok，then it is failed
```

### Additional information

![image](https://github.com/user-attachments/assets/d2cad229-34d0-4782-9a40-a25ddf5b3143)

**Comment by KevinHuSh** [comment]
Sorry, can't reproduce that. Maybe upgrade the system?
![image](https://github.com/user-attachments/assets/fbd97cb0-8f25-4a29-8e06-1e7ea2d13fac)

**Comment by yuzhichang** [comment]
Cannot reproduce.
