### ISSUE TITLE
[Feature Request]: Hello, if possible, we'd like to customize responses when there's no relevant content in the knowledge base.

### ISSUE THREAD

**Issue by live98563** [infiniflow/ragflow#233]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
When a user asks a question and there's no relevant content in the knowledge base, we can reply with a custom message.

For example:
Knowledge base: 1. Professional knowledge
User input: Hello, xxxxxx?
[No relevant content found]
Assistant output: Sorry, I'm unable to answer your question. You can submit a ticket at https://xxx.com.
```

### Describe the feature you'd like

When a user asks a question and there's no relevant content in the knowledge base, we can reply with a custom message.

**Comment by KevinHuSh** [comment]
In dialog setting, there's a blank for 'Empty response'.
Is this what you want?
![image](https://github.com/infiniflow/ragflow/assets/12318111/505f1ed0-349f-43e1-8146-7856958ec530)
