### ISSUE TITLE
[Bug]: using ollama add an embedding model and a chat model, but system model settings do not select this two model

### ISSUE THREAD

**Issue by laneado** [infiniflow/ragflow#2332]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

265a7a283ae1a29a4827d2a973d62cad14c41dc5

### Actual behavior

using ollama add an embedding model and a chat model, but system model settings do not select this two model. I can not use ollama models

### Steps to reproduce

```Markdown
1. using ollama to add models
2. selecting ollama models in the system model settings
```

### Additional information

![image](https://github.com/user-attachments/assets/87ea01b5-8c55-4a56-96de-6b5390d6534f)
it is not ollama's dage model
![image](https://github.com/user-attachments/assets/e654aa01-8b3b-4ec9-8f4e-204e2a9e1488)
it is not ollama's bge-m3 embedding model
![image](https://github.com/user-attachments/assets/0c456826-91b4-4a92-abdf-da3f90bba51a)
Actually, system model settings only read config file
![image](https://github.com/user-attachments/assets/f68e7589-d560-42f3-87f0-701a4c9d5e10)

**Comment by KevinHuSh** [comment]
It seems version of your system is a little older.

**Comment by laneado** [comment]
> It seems version of your system is a little older.

sorry, I use the lastest main version

**Comment by hangters** [comment]
hi  @laneado  You should be able to find the added Ollama models by scrolling down with your mouse wheel. Are you unable to find them?

**Comment by laneado** [comment]
> hi @laneado You should be able to find the added Ollama models by scrolling down with your mouse wheel. Are you unable to find them?

Yes, I can not find it. I already pull the latest verison on 2024-09-12 and it is normal. I do not know why it's reason

**Comment by yuzhichang** [comment]
Cannot reproduce.
