### ISSUE TITLE
[Bug]: embedding model repeatly downloading

### ISSUE THREAD

**Issue by statsmind** [infiniflow/ragflow#2333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c57cc0

### Other environment information

```Markdown
Dockerfile.cuda + docker-compose-gpu-CN.yml
```

### Actual behavior

From the log, the embedding model is being downloaded repeatly. No cache?

[INFO] [2024-09-09 21:13:20,492] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:13:20] "GET /v1/conversation/list?dialog_id=a123df0a67d011efb28f0242ac1f0006 HTTP/1.1" 200 -
[INFO] [2024-09-09 21:13:24,318] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:13:24] "GET /v1/user/info HTTP/1.1" 200 -
1_Pooling/config.json: 100%|██████████| 191/191 [00:00<00:00, 328kB/s]
modules.json: 100%|██████████| 349/349 [00:00<00:00, 641kB/s]/s]
config.json: 1.00kB [00:00, 1.86MB/s]                 ]
sentence_bert_config.json: 100%|██████████| 52.0/52.0 [00:00<00:00, 102kB/s]
.gitattributes: 1.52kB [00:00, 2.60MB/s]                 :00<?, ?B/s]
special_tokens_map.json: 100%|██████████| 125/125 [00:00<00:00, 210kB/s]
tokenizer_config.json: 100%|██████████| 394/394 [00:00<00:00, 702kB/s]
README.md: 30.4kB [00:00, 126kB/s]      | 0.00/125 [00:00<?, ?B/s]
tokenizer.json: 439kB [00:00, 1.17MB/s]2 [00:01<00:05,  1.71it/s]
config_sentence_transformers.json: 100%|██████████| 124/124 [00:00<00:00, 533kB/s]
vocab.txt: 110kB [00:01, 95.9kB/s]  5/12 [00:02<00:02,  3.05it/s]
pytorch_model.bin: 100%|██████████| 1.30G/1.30G [02:08<00:00, 10.1MB/s]
Fetching 12 files: 100%|██████████| 12/12 [02:23<00:00, 11.96s/it]MB/s]?B/s]
[INFO] [2024-09-09 21:15:49,492] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:15:49] "POST /v1/conversation/completion HTTP/1.1" 200 -
[INFO] [2024-09-09 21:15:49,541] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:15:49] "GET /v1/conversation/get?conversation_id=5713f5186ef011efa9720242c0a81006 HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:07,437] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:07] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:07,481] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:07] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:11,176] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:11] "POST /v1/user/login HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:11,221] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:11] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:11,225] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:11] "GET /v1/kb/list HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:13,247] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:13] "GET /v1/user/info HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:13,275] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:13] "GET /v1/dialog/list HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:13,344] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:13] "GET /v1/conversation/list?dialog_id=a123df0a67d011efb28f0242ac1f0006 HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:13,348] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:13] "GET /v1/dialog/get?dialog_id=a123df0a67d011efb28f0242ac1f0006 HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:18,839] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:18] "POST /v1/conversation/set HTTP/1.1" 200 -
[INFO] [2024-09-09 21:24:18,853] [_internal._log] [line:96]: 192.168.16.6 - - [09/Sep/2024 21:24:18] "GET /v1/conversation/list?dialog_id=a123df0a67d011efb28f0242ac1f0006 HTTP/1.1" 200 -
config.json: 1.00kB [00:00, 1.77MB/s]                 /s]
.gitattributes: 1.52kB [00:00, 2.67MB/s]                 
config_sentence_transformers.json: 100%|██████████| 124/124 [00:00<00:00, 212kB/s]
modules.json: 100%|██████████| 349/349 [00:00<00:00, 654kB/s][00:00<?, ?B/s]
README.md: 30.4kB [00:00, 5.41MB/s]
tokenizer_config.json: 100%|██████████| 394/394 [00:00<00:00, 732kB/s]
1_Pooling/config.json: 100%|██████████| 191/191 [00:00<00:00, 369kB/s]
tokenizer.json: 439kB [00:00, 705kB/s]12 [00:01<00:08,  1.16it/s]
special_tokens_map.json: 100%|██████████| 125/125 [00:00<00:00, 266kB/s]
vocab.txt: 110kB [00:00, 146kB/s] B/s] 
sentence_bert_config.json: 100%|██████████| 52.0/52.0 [00:00<00:00, 115kB/s]
pytorch_model.bin: 100%|██████████| 1.30G/1.30G [02:07<00:00, 10.2MB/s]
Fetching 12 files: 100%|██████████| 12/12 [02:18<00:00, 11.53s/it]MB/s]

### Expected behavior

The model should be cached

### Steps to reproduce

```Markdown
run the docker container, and then chat.
```

**Comment by KevinHuSh** [comment]
What kind of embedding model you're using?
The BGE model is already in the docker image.

**Comment by yuzhichang** [comment]
No response in 3 week. Close.
