### ISSUE TITLE
[Question]: There is a bug for docker compose up -d

### ISSUE THREAD

**Issue by whysirier** [infiniflow/ragflow#2334]
### Describe your problem

![企业微信截图_20240910094509](https://github.com/user-attachments/assets/8a355149-6b9b-456e-a0d4-d904c7f983da)
I use command 'lsof -i:6379' to kill the PID, but the problem not solved

**Comment by whysirier** [comment]
Error response from daemon: driver failed programming external connectivity on endpoint ragflow-redis (733c4ae5131bf58c6f7dca5feb91b3e18258a852a20ff7aaa6f96f2ec174d089): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use

**Comment by KevinHuSh** [comment]
Port 6379 is occupied by other program, probably another redis.
ps aux|grep redis
netstat -nlp|grep 6379

**Comment by whysirier** [comment]
> Port 6379 is occupied by other program, probably another redis. ps aux|grep redis netstat -nlp|grep 6379

thanks, the original redis occupy the port
