### ISSUE TITLE
[Question]: Agent might mismatch the empty_response

### ISSUE THREAD

**Issue by Chunshan-Theta** [infiniflow/ragflow#2336]
### Describe your problem

I don't set the value in empty_response, but the agent returned the  `Nothing found in knowledgebase!`

![image](https://github.com/user-attachments/assets/a3697556-c73a-4149-9c4b-088c60742d01)
![image](https://github.com/user-attachments/assets/fd7a6f8f-d028-40c2-b724-49dfe6149b7f)

I traced the code. Let us consider the value `empty_response` existing and the value is empty, the Agent should not return the static label.
![image](https://github.com/user-attachments/assets/03c159aa-cb7e-4e4e-981a-3f3f3559dac1)

**Comment by KevinHuSh** [comment]
That's from the prompt in 'Generate'.
And 'Categorize' should not all lead to the same downstream, which is meaningless.
Three different categories should lead to three different components.

Three categories lead to three different 'Retrieval', which is more reasonable.

**Comment by Chunshan-Theta** [comment]
yes, you are right, I separated `rewrite` into three parts, but I got the same response `Nothing found in knowledgebase!`
![image](https://github.com/user-attachments/assets/9c382b1d-40f6-43b0-848c-fa6863f9a253)

and my setting was kept empty for `Empty response`. In my expectation, this case should get the response from the LLM model if can't found the references from knowledgebase.
![image](https://github.com/user-attachments/assets/032d2001-97a2-4faa-91bf-c9c57caf2070)
