### ISSUE TITLE
[Question]: how to start this project without using Docker? 

### ISSUE THREAD

**Issue by 1193700079** [infiniflow/ragflow#2337]
### Describe your problem

Would you like to know how to start this project without using Docker? Additionally, I'd like to ask how to check the running commands when Docker is used to start the project.

**Comment by KevinHuSh** [comment]
Please checkout docker/entrypoint.sh.
Commands in it are all about start the system.

**Comment by yuzhichang** [comment]
Here's the doc: https://github.com/infiniflow/ragflow/blob/main/docs/guides/develop/launch_ragflow_from_source.md

**Comment by 1907010218** [comment]
hello, did you make it
