### ISSUE TITLE
[Bug]: ！！！！123.60.95.134 redirect attack

### ISSUE THREAD

**Issue by learnerLj** [infiniflow/ragflow#2350]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

lastest

### Actual behavior

somebody replaces the backend to his own server!!! 123.60.95.134 instead of the localhost

### Steps to reproduce

```Markdown
somebody replaces the backend to his own server!!! 123.60.95.134 instead of the localhost
```

**Comment by learnerLj** [comment]
https://github.com/infiniflow/ragflow/commit/f1ad778250f378cc1455e3089df2aa52e9d7989b Never upload any sensitive file when developing your application

**Comment by cyhasuka** [comment]
There really needs to be a more rigorous code review.
