### ISSUE TITLE
[Bug]: Couldn't add OpenRounter Api

### ISSUE THREAD

**Issue by lionkingc** [infiniflow/ragflow#2359]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

eg

### Actual behavior

When I try to add OpenRouter Api-Key , it shows :
Fail to access model(01-ai/yi-34b) 
using this api key.**ERROR**: Error code: 404 - 
{'error': {'message': 'No endpoints found for this model.', 'code': 404}, 'user_id': 'user_2lBakZZi7xxxxxxxxxxbTJ4'}

### Expected behavior

Here is The OpenRouter API LIST:
https://openrouter.ai/docs/models

only nousresearch/nous-hermes-yi-34b  

### Steps to reproduce

```Markdown
Added models
```

**Comment by hangters** [comment]
hi @lionkingc  Thank you for raising this issue. It seems that the OpenRouter model list has been updated. To permanently resolve this problem, we will change the method for adding OpenRouter models, so that you can add the models you wish to use more easily.
