### ISSUE TITLE
[Question]: How to set `vm.max_map_count` in Windows

### ISSUE THREAD

**Issue by ooooo-create** [infiniflow/ragflow#236]
### Describe your problem

The `README.md` show the way to  set `vm.max_map_count` in Linux. But how to set it in Windows?

**Comment by KevinHuSh** [comment]
Please refer to the following page to set vm.max_map_count to at least 262144.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144
