### ISSUE TITLE
[Bug]: Process Begin At: Tue, 10 Sep 2024 15:32:20 GMT Process Duration: 325.09 s Progress Msg: Task dispatched...

### ISSUE THREAD

**Issue by zxj197865** [infiniflow/ragflow#2360]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

document parsing

### Commit ID

83803a7

### Other environment information

```Markdown
docker 4.34.1
ragflow:0.10
```

### Actual behavior

When I upload a document for document parsing, Progress Msg: Task dispatched..., and the document cannot be parsed normally

### Expected behavior

Parsing documents normally

### Steps to reproduce

```Markdown
Every time a file is uploaded for parsing, it appears
```

### Additional information

none

**Comment by KevinHuSh** [comment]
Please check the status of task executor.
![image](https://github.com/user-attachments/assets/457d63d1-c3f3-4969-8987-70c73e6bd3f3)

**Comment by zxj197865** [comment]
Hello, there are no tasks in the Task    ##@Executo.
![20240912084933](https://github.com/user-attachments/assets/42dd87de-19ab-4e89-858f-aea29ffa7aa3)
![3](https://github.com/user-attachments/assets/d53ced2d-816a-43b4-978b-224560499231)

**Comment by KevinHuSh** [comment]
Start the task executor, which has been shown in docker/entrypoint.sh

**Comment by cuntoushifu** [comment]
流程开始于:
Fri, 20 Sep 2024 06:17:37 GMT
过程持续时间:
848.41 s
进度消息:
Task has been received.
Start to parse.
![image](https://github.com/user-attachments/assets/9a1d6fc9-f29c-427e-8804-ad1c536f2562)

**Comment by yuzhichang** [comment]
Please upgrade to v0.14.1 which has much better monitoring on task executor.
