### ISSUE TITLE
[Bug]: Chat retrieval issues

### ISSUE THREAD

**Issue by sznariOsmosis** [infiniflow/ragflow#2362]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Actual behavior

The debugging discovery is currently based on the latest 4 problems in the history to retrieve, and the debugging found that the consequence of this is that sometimes the content cannot be retrieved, but when I use the latest problem to retrieve, I can get the retrieved chunk

### Expected behavior

What was the purpose of using the 4 questions to search in the first place, and will this be a hidden danger?
![61726023665_ pic](https://github.com/user-attachments/assets/b12440cd-92f4-4ebb-803d-1d749e4ce25d)

### Steps to reproduce

```Markdown
Attachments shown above
```

**Comment by KevinHuSh** [comment]
It's normal. The longer the query is, the lower the recall rate is.

**Comment by sznariOsmosis** [comment]
> It's normal. The longer the query is, the lower the recall rate is.

What is the purpose of this strategy, after testing, it uses the 4 questions of the history to retrieve chunks, which is easy to cause false detections and missed detections

**Comment by KevinHuSh** [comment]
It's related to multi-turn conversations. We're gona refine it soon.
