### ISSUE TITLE
[Question]: RAGFlow - how to add json(l)/csv files containing an academic corpus and metadata

### ISSUE THREAD

**Issue by HCSS-StratBase** [infiniflow/ragflow#237]
### Describe your problem

Can somebody tell us how we can load a json(l) or csv file into the system?

**Comment by KevinHuSh** [comment]
Thanks for following!

You'd better look into chunking method 'Table' which is for structured data.

Let me know if it fits in your scenario!

![image](https://github.com/infiniflow/ragflow/assets/12318111/d17b9fac-bc6e-4023-858b-1852837b6c95)
