### ISSUE TITLE
[Question]: Requirement confliction caused by "yfinance"

### ISSUE THREAD

**Issue by blizzardwj** [infiniflow/ragflow#2379]
### Describe your problem

When I `pip install -r requirement.txt`, I got the following prompt. If I comment the line 103 `yfinance=0.2.43`, will it affect something?

```
ERROR: Cannot install -r requirements.txt (line 103), -r requirements.txt (line 56) and -r requirements.txt (line 95) because these package versions have conflicting dependencies.

The conflict is caused by:
    pandas 2.2.2 depends on pytz>=2020.1
    volcengine 1.0.146 depends on pytz==2020.5
    yfinance 0.2.43 depends on pytz>=2022.5
```

**Comment by yimisiyang** [comment]
I encountered the same problem！！！！help help

**Comment by mingSummer** [comment]
> ### Describe your problem
> When I `pip install -r requirement.txt`, I got the following prompt. If I comment the line 103 `yfinance=0.2.43`, will it affect something?
> 
> ```
> ERROR: Cannot install -r requirements.txt (line 103), -r requirements.txt (line 56) and -r requirements.txt (line 95) because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     pandas 2.2.2 depends on pytz>=2020.1
>     volcengine 1.0.146 depends on pytz==2020.5
>     yfinance 0.2.43 depends on pytz>=2022.5
> ```

You can comment out this dependency, as yfinance is a Python open-source tool that uses Yahoo’s public API to access financial data. You may not use this dependency.

**Comment by yuzhichang** [comment]
We've replaced pip with poetry. Poetry is much better on dependency management and download speed.
