### ISSUE TITLE
[Question]: rag.app.table.column_data_type, Why do we have to handle it like this?

### ISSUE THREAD

**Issue by lybtt** [infiniflow/ragflow#2405]
### Describe your problem

Why does it need to be all one type?

**Comment by KevinHuSh** [comment]
It's like create table in DB.
You need to tell DB data type of all the fields.

**Comment by lybtt** [comment]
> It's like create table in DB. You need to tell DB data type of all the fields.

But isn't the final result just string anyway?

**Comment by lybtt** [comment]
<img width="274" alt="image" src="https://github.com/user-attachments/assets/5e8ebffa-acba-4d63-b175-4d1e8f9ca74c">
For example, this would result in the B column showing: None, None, yes, yes, no.

**Comment by KevinHuSh** [comment]
Different type of fields need different type of indexing procedure and support different caculation like average, max, min...
