### ISSUE TITLE
[Question]: How to Configure RAGFlow for Accurate Responses without AI Hallucinations

### ISSUE THREAD

**Issue by robertshuai** [infiniflow/ragflow#2408]
### Describe your problem

Hi there,
I've been using RAGFlow with much enthusiasm, and I'm quite impressed with its potential! However, I encountered an issue where the model tends to generate its own information or "hallucinate" when it can't find certain details like product prices in the knowledge base.

To resolve this, I added a cute and playful prompt that instructs the assistant to fetch product details from the knowledge base and return relevant results or gracefully handle missing information. However, despite using the "Accurate" mode and a well-structured prompt, the model still sometimes invents answers rather than admitting a lack of data.

I've been continuously working with this setup, and I'd love to keep refining it for better accuracy. I admire this project a lot and have been a consistent user for some time now. Could you help me understand how I can improve the system so that it strictly relies on the knowledge base and avoids generating unrelated or incorrect data?

Looking forward to your advice! 😊
![image](https://github.com/user-attachments/assets/6429187c-abfe-47c6-886d-acf3872e6c9b)
![image (1)](https://github.com/user-attachments/assets/8fbeb8e3-347d-4d6a-a646-889d581a3f6c)

**Comment by KevinHuSh** [comment]
Here're some suggestions:
1. Enlarge the threshold of similarity.
2. Reduce the top N of retrievals.
3. Reduce the temperature of LLM.
4. Optimize the prompt.

**Comment by robertshuai** [comment]
> Here're some suggestions:
> 
> 1. Enlarge the threshold of similarity.
> 2. Reduce the top N of retrievals.
> 3. Reduce the temperature of LLM.
> 4. Optimize the prompt.

牛逼！调整Top P直接可以了，其他的参数我再调整试试区别 ，大佬 yyds！

**Comment by Dyson-Ido** [comment]
> > Here're some suggestions:
> > 
> > 1. Enlarge the threshold of similarity.
> > 2. Reduce the top N of retrievals.
> > 3. Reduce the temperature of LLM.
> > 4. Optimize the prompt.
> 
> 牛逼！调整Top P直接可以了，其他的参数我再调整试试区别 ，大佬 yyds！

@robertshuai So in the end , did you adjust Top N or Top P, and how you adjusted to improve the accuracy?
