### ISSUE TITLE
[Question]: No Self-Rag in Demo?

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2420]
### Describe your problem

Hi, I just saw that in the demo one can't choose to whether use or not use Self-Rag, as in the prior versions. Was that option simply removed?
![image](https://github.com/user-attachments/assets/8b449d0d-3aca-40b4-b3ed-91ec364de868)

**Comment by KevinHuSh** [comment]
We deprecate it since a lot of uncertainties of results.
Once LLM judgement of relevance between question and retrieval went wrong, it became very time consuming and enventully no resualt at all for most cases.
