### ISSUE TITLE
[Bug]: npm ERR! code 1 npm ERR! path /home/leiwei/programs/ragflow/web npm ERR! command failed npm ERR! command sh -c umi setup

### ISSUE THREAD

**Issue by Weishaoya** [infiniflow/ragflow#2426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

the latest code 

### Other environment information

```Markdown
OS: ubuntu 22.04
python: 3.11
```

### Actual behavior

I need to Launch the service from source. When I run the commad "npm install --registry=https://registry.npmmirror.com --force", the bug was occurred.

### Expected behavior

I want to solve the bug, how can I do? Thank you.

### Steps to reproduce

```Markdown
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/leiwei/programs/ragflow/web/node_modules/@umijs/utils/dist/index.js:76:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/leiwei/programs/ragflow/web
npm ERR! command failed
npm ERR! command sh -c umi setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lw03-10052696/.npm/_logs/2024-09-14T02_41_32_269Z-debug-0.log
```

**Comment by cike8899** [comment]
Run `npm install` directly in the web directory

![image](https://github.com/user-attachments/assets/16f12b03-13a9-4458-a6da-998346b017b9)

**Comment by Weishaoya** [comment]
> Run `npm install` directly in the web directory
> 
> ![image](https://private-user-images.githubusercontent.com/8089971/367494621-16f12b03-13a9-4458-a6da-998346b017b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNjY0ODUsIm5iZiI6MTcyNjM2NjE4NSwicGF0aCI6Ii84MDg5OTcxLzM2NzQ5NDYyMS0xNmYxMmIwMy0xM2E5LTQ0NTgtYTZkYS05OTgzNDZiMDE3YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMDIwOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ4MWZkMTIwZDU3YjQwYTU5NDQxNGU3OWM2N2YwMDcxNjIyMzZhOTgzMjgyMDU2NDAxMDEyMDUzMjE1NTY2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cVAPc6yjUSq6B2LsyfoSsGLmseD80F2UKjC_bvXRTTQ)

Thank you! I was running nodejs version 12, and the bug was fixed when I upgraded it to version 18.
