### ISSUE TITLE
[Bug]: View function mapping is overwriting an existing endpoint function: doc.rm

### ISSUE THREAD

**Issue by 5200016** [infiniflow/ragflow#2433]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

主要

### Commit ID

c3b2a1

### Actual behavior

源码启动项目报错

### Steps to reproduce

```Markdown
执行./entrypoint.sh命令后，启动项目时报错
```

**Comment by danny-zhu** [comment]
我也遇到类似的报错了，我这边是因为合并的代码的时候，没注意，在session.py中出现了两个同名的函数导致的，你可以检查一下是否有类似的情况。
