### ISSUE TITLE
如何溯源？

### ISSUE THREAD

**Issue by tonylin52** [infiniflow/ragflow#244]
### Describe your problem

请问如果精召回了3个chunk，都丢给大模型，最终是如何确认答案是基于哪个chunk回答的呢？

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question:
This is a very challenging task. We need to calculate the similarity between answer and chunks sentence by sentence.
BTW, we use weighted similarity of term and embedding in RAGFlow.
The other way to write a good prompt to LLM, let LLM do the job.

**Comment by tonylin52** [comment]
> Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊
> 
> For your question: This is a very challenging task. We need to calculate the similarity between answer and chunks sentence by sentence. BTW, we use weighted similarity of term and embedding in RAGFlow. The other way to write a good prompt to LLM, let LLM do the job.

Thanks！

**Comment by cristianohello** [comment]
@KevinHuSh 
你好，你说的we use weighted similarity of term and embedding in RAGFlow. 这个在代码里面哪个地方？
