### ISSUE TITLE
[Bug]: Docx document leads to a blank display for the knowledge graph

### ISSUE THREAD

**Issue by WildCamel** [infiniflow/ragflow#2451]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1621313c0f6dcd82fb67d4d00e0f9552c814361a

### Other environment information

```Markdown
Ubuntu 20.04
Python 3.11
NodeJs v18.8.0
Nvidia RTX 3090
CUDA 11.8
```

### Actual behavior

When using the GraphRAG model, clicking on a parsed docx document leads to a blank display for the knowledge graph image, but the mind map guide is displayed correctly. Then I imported a book.txt, and both the knowledge graph and the mind map were displayed correctly.
Blank graph:
<img width="1575" alt="image" src="https://github.com/user-attachments/assets/01474842-4ff4-4702-ba61-d85263785eba">
Mind map is ok:
<img width="723" alt="image" src="https://github.com/user-attachments/assets/452ebc8f-5a25-44b6-85bf-dcd7aa6ee586">
book.txt knowledge graph and mind map both ok:
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/35c730fa-1f3f-4675-a55d-0193a2657bd0">

### Steps to reproduce

```Markdown
upload docx file and trunk by GraphRAG method
```

**Comment by yuzhichang** [comment]
@WildCamel Can you upload the file which failed to display knowledge graph?

**Comment by yuzhichang** [comment]
Close due to no response.
