### ISSUE TITLE
[Bug]: Knowledge base error when I use the Knowledge graph methord

### ISSUE THREAD

**Issue by kknd222** [infiniflow/ragflow#2452]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.11.0

### Commit ID

none

### Actual behavior

An error occured when I use the Knowledge graph methrod in version 0.11.0:

> Task has been received.
> Start to parse.
> Finish parsing.
> Extracting entities.
> Knowledge graph extraction error:'NoneType' object is not subscriptable
> Knowledge graph extraction error:'NoneType' object is not subscriptable
> 1/1, elapsed: 66.27512523718178s, used tokens: 3887
> 1/1, elapsed: 90.88857838138938s, used tokens: 3861

The error logs was found from console of ragflow-server:

> [INFO] [2024-09-15 07:42:43,610] [_internal._log] [line:96]: 192.168.224.7 - - [15/Sep/2024 07:42:43] "GET /v1/document/list?kb_id=5108961c733511ef82ce0242c0a8e007&page=1&page_size=10 HTTP/1.1" 200 -
> [ERROR] [2024-09-15 07:42:47,859] [graph_extractor.__call__] [line:135]: error extracting graph
> Traceback (most recent call last):
>   File "/ragflow/graphrag/graph_extractor.py", line 128, in __call__
>     result, token_count = self._process_document(text, prompt_variables)
>   File "/ragflow/graphrag/graph_extractor.py", line 166, in _process_document
>     response = self._llm.chat(text, [{"role": "user", "content": "Output:"}], gen_conf)
>   File "/ragflow/api/db/services/llm_service.py", line 250, in chat
>     txt, used_tokens = self.mdl.chat(system, history, gen_conf)
>   File "/ragflow/rag/llm/chat_model.py", line 45, in chat
>     ans = response.choices[0].message.content.strip()
> TypeError: 'NoneType' object is not subscriptable
> [ERROR] [2024-09-15 07:42:48,000] [graph_extractor.__call__] [line:135]: error extracting graph
> Traceback (most recent call last):
>   File "/ragflow/graphrag/graph_extractor.py", line 128, in __call__
>     result, token_count = self._process_document(text, prompt_variables)
>   File "/ragflow/graphrag/graph_extractor.py", line 166, in _process_document
>     response = self._llm.chat(text, [{"role": "user", "content": "Output:"}], gen_conf)
>   File "/ragflow/api/db/services/llm_service.py", line 250, in chat
>     txt, used_tokens = self.mdl.chat(system, history, gen_conf)
>   File "/ragflow/rag/llm/chat_model.py", line 45, in chat
>     ans = response.choices[0].message.content.strip()
> TypeError: 'NoneType' object is not subscriptable

### Steps to reproduce

```Markdown
upload the document and process with Knowledge graph methord
```

**Comment by KevinHuSh** [comment]
It seems the response from LLM has error.

**Comment by KevinHuSh** [comment]
What's LLM you're using?

**Comment by kknd222** [comment]
> What's LLM you're using?

new-api with deepseek and glm4 api

**Comment by KevinHuSh** [comment]
What is new-api? Could you give me a reference?
For glm-4, do you mean you're using Zhipu SaaS for calling LLM?

**Comment by kknd222** [comment]
> What is new-api? Could you give me a reference? For glm-4, do you mean you're using Zhipu SaaS for calling LLM?

https://github.com/MartialBE/one-hub/blob/main/README.en.md
It's a copy of the one-api, which is an api hub toolkit.

**Comment by yuzhichang** [comment]
I guess you need some development to integrate `one-hub` into chat_model.py.
However we don't have bandwidth for this.
