### ISSUE TITLE
[Bug]: `doc_aggs` are sometimes empty even though resources are provided in API response /v1/api/completion

### ISSUE THREAD

**Issue by Defozo** [infiniflow/ragflow#2459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

v0.10.0

### Commit ID

e18f40760414342a1c3644ddb8872418544d4194

### Other environment information

```Markdown
AWS EC2 r7i.xlarge, Ubuntu
```

### Actual behavior

I received response from /v1/api/completion that had empty `doc_aggs` even though the chatbot referenced an article and `reference` and the chunks were provided. This resulted in no links to documents when the message was displayed on the frontend in the chat.

### Expected behavior

I believe `doc_aggs` should always be populated when the chatbot references anything.

### Steps to reproduce

```Markdown
I'm not sure.
```

### Additional information

The answer was based on an image from a pdf file.

**Comment by jackerha123** [comment]
I am experiencing the same issue with V0.11.0. My current base knowledge is em
<img width="1332" alt="Screenshot 2024-09-17 at 08 56 27" src="https://github.com/user-attachments/assets/5d970976-3db4-42e7-9704-29a85c8036ed">
pty.

**Comment by KevinHuSh** [comment]
> I am experiencing the same issue with V0.11.0. No matter what the question is, the reference is empy. <img alt="Screenshot 2024-09-17 at 08 56 27" width="1332" src="https://private-user-images.githubusercontent.com/126239501/367981497-5d970976-3db4-42e7-9704-29a85c8036ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjMzMzYsIm5iZiI6MTcyNjYyMzAzNiwicGF0aCI6Ii8xMjYyMzk1MDEvMzY3OTgxNDk3LTVkOTcwOTc2LTNkYjQtNDJlNy05NzA0LTI5YTg1YzgwMzZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMTMwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDcwYzBlNzNlMzQ1ZWIwMmJkYjk4N2ZmMGNhZWY4Yjc5YzE1MmRmMGZiMjMxNGE4NmJkNDBiZTE0ZDlhY2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xuqyIX93SZRCUro8yZV6JF0NpH8_gOfPcA4cxT73cuo">

The prompt says there is nothing retrievaled.

**Comment by jacker000** [comment]
> > I am experiencing the same issue with V0.11.0. No matter what the question is, the reference is empy. <img alt="Screenshot 2024-09-17 at 08 56 27" width="1332" src="https://private-user-images.githubusercontent.com/126239501/367981497-5d970976-3db4-42e7-9704-29a85c8036ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjMzMzYsIm5iZiI6MTcyNjYyMzAzNiwicGF0aCI6Ii8xMjYyMzk1MDEvMzY3OTgxNDk3LTVkOTcwOTc2LTNkYjQtNDJlNy05NzA0LTI5YTg1YzgwMzZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMTMwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDcwYzBlNzNlMzQ1ZWIwMmJkYjk4N2ZmMGNhZWY4Yjc5YzE1MmRmMGZiMjMxNGE4NmJkNDBiZTE0ZDlhY2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xuqyIX93SZRCUro8yZV6JF0NpH8_gOfPcA4cxT73cuo">
> 
> The prompt says there is nothing retrievaled.


![image](https://github.com/user-attachments/assets/e957ca41-ec62-461f-af20-b2f889947fb5)
![image](https://github.com/user-attachments/assets/a9ec4e00-58cc-4cb8-878a-1df141be2a92)
I have configured it correctly. With version V0.9.0, it still runs and has data. However, after upgrading to V0.11.0, it encounters an error.

**Comment by KevinHuSh** [comment]
It seems nothing retrieved. What about runing a retrieval test on the page of knowledge base detail?

**Comment by jacker000** [comment]
Running Retrieval testing on the Knowledge Base still doesn't return any data.

**Comment by KevinHuSh** [comment]
> Running Retrieval testing on the Knowledge Base still doesn't return any data.

What is your query, and what's the content you want to retrieve by this query?

**Comment by yuzhichang** [comment]
Close due to no response.
