### ISSUE TITLE
[Bug]: deepseek模型在本地部署完以后聊天的时候没有选项

### ISSUE THREAD

**Issue by bidada-bcr** [infiniflow/ragflow#2465]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

模型不信是

### Commit ID

cccc

### Other environment information

```Markdown
deepseek模型在本地部署完以后聊天的时候没有选项
```

### Actual behavior

deepseek模型在本地部署完以后聊天的时候没有选项

### Steps to reproduce

```Markdown
deepseek模型在本地部署完以后聊天的时候没有选项
```

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for communication.

For you question, what do you mean no option ? Would you please provide a screenshot on this issue ?

**Comment by bidada-bcr** [comment]
> 我们打算创建一个国际社区，因此我们鼓励使用英语进行交流。
> 
> 对于你的问题，你是什么意思 没有选择？您能否提供此问题的屏幕截图？

![image](https://github.com/user-attachments/assets/af483468-071a-4f84-806e-7c3c8c34150e)
![image](https://github.com/user-attachments/assets/5062d38a-b211-400e-8c32-d39645d2e01c)
I have configured the Deepseek model with my supplier, but when I try to chat, I cannot select Deepseek.

**Comment by bidada-bcr** [comment]
请帮忙再看一下

**Comment by JinHai-CN** [comment]
This is a BUG and we are going to fix it before next release.
