### ISSUE TITLE
[Bug]: Can't parse PPTX file, error code: 102

### ISSUE THREAD

**Issue by sherzlock** [infiniflow/ragflow#2467]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

deeb950e1c75321e44d06771f39c98115cf2ef8a

### Actual behavior

![3321726495253_ pic](https://github.com/user-attachments/assets/5a7a8549-e40a-4f39-8747-8a7ffef38321)
知识库是 general的解析，但里面有些文件是 pptx，所以单独设置为 presentation，但显示为 102，不支持

### Steps to reproduce

```Markdown
1. 文件管理中建立 1 个文件夹，上传相关文件，有pdf/pptx/xls等格式
2. 建立知识库，关联此文件夹，进行解析，general 方案，关闭布局识别，打开raptor策略
3. 开始解析，pptx 文件解析失败，显示不支持
4. 单独转换为 presentation 格式进行解析，显示上面如图所示，102 错误，不支持
```

**Comment by KevinHuSh** [comment]
Bug fixed. But you need to redo action of linking.

**Comment by sherzlock** [comment]
> Bug fixed. But you need to redo action of linking.错误已修复。但您需要重新执行链接操作。

thanks a lot.
Do I need to pull the mirror again or perform an upgrade?
