### ISSUE TITLE
[Question]: ERROR: Knowledge bases use different embedding models

### ISSUE THREAD

**Issue by DennLie** [infiniflow/ragflow#2468]
### Describe your problem

Hello, 
i updated from 0.10.0 to 0.11.0 and now encounter a weird error that hasnt happened before. In Chat or Agent it is working fine but as soon  i use the api i get the following response from the llm:
{'data': {'answer': 'ERROR: Knowledge bases use different embedding models.', 'reference': []}, 'retcode': 0, 'retmsg': 'success'}
This is in the payload:
 payload = {
            "conversation_id": conversation_id,
            "messages": [{"role": "user", "content": message_content}],
            "stream": False
        }
i deleted all except one knowledge bases and i use snowflake-arctic-embed-l as embedding modell via ollama.

**Comment by KevinHuSh** [comment]
This means the conversation_id is related to several knowledge bases which apply different embedding models.

**Comment by DennLie** [comment]
Ok thx for the help. I found the error in my code.

**Comment by TanMIMI** [comment]
> Ok thx for the help. I found the error in my code.

hello, could you share how to solve it, i meet the same issue.
