### ISSUE TITLE
demo website problem：hint : 102 Tenant not found.

### ISSUE THREAD

**Issue by beyondskyway** [infiniflow/ragflow#247]
### Describe your problem

demo website create knowledge：hint : 102 Tenant not found.

**Comment by liux001** [comment]
Me too...

**Comment by KevinHuSh** [comment]
What about re-signup a new account?

**Comment by vikotse** [comment]
> What about re-signup a new account?

@KevinHuSh The issue remains on a new account.

**Comment by hiheaven** [comment]
Me too

**Comment by KevinHuSh** [comment]
It's a bug and fixed. But I'm afraid that you need to sign up again.
Sorry for the inconvenience!

**Comment by yungongzi** [comment]
最新版本0.5.0又出现这个BUG了

**Comment by zouchengli** [comment]
<img width="305" alt="Image" src="https://github.com/user-attachments/assets/12b75ade-58d9-42e3-bd0a-27128e23a81e" />
