### ISSUE TITLE
[Question]: Is there an endpoint that we could ping that would only give us back the retrieved chunks?

### ISSUE THREAD

**Issue by wolfassi123** [infiniflow/ragflow#2476]
### Describe your problem

I was wondering if there is any endpoint that can be pinged that would give us the chunks needed to answer the question.
It would great if it can be done as it would an easier way for evaluation and in case there was any locally deployed LLM we can still use RAGFlow for the retrieval part but use the local LLM to generate the answer from the chunks.

**Comment by KevinHuSh** [comment]
# POST /v1/api/retrieval
## mandatory  parameters:
- kb_ids
- question
