### ISSUE TITLE
[Question]: Add model by ollama in model provider page, user can't choose the model in chat window.

### ISSUE THREAD

**Issue by backtime1** [infiniflow/ragflow#2479]
### Describe your problem

![1726650289524](https://github.com/user-attachments/assets/83fb1584-8d37-467b-9330-facb7fff5862)
![1726650321565](https://github.com/user-attachments/assets/4f9408d9-f7e0-4e61-abd0-10c073d12d2a)
我添加了qwen2模型，但是我在助手设置模型时并没有发现qwen2模型

**Comment by JinHai-CN** [comment]
#2465 Same issue.
