### ISSUE TITLE
Refresh the login page and the language setting becomes invalid.

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#249]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c8297994744d88e39d3d982cda5ee73c814ae705

### Actual behavior

Refresh the login page and the language setting becomes invalid.

### Steps to reproduce

```Markdown
Refresh the login page and the language setting becomes invalid.
```

**Comment by KevinHuSh** [comment]
fixed
