### ISSUE TITLE
[Question]: Fail to run: docker build -t infiniflow/ragflow:dev .

### ISSUE THREAD

**Issue by xxz196801** [infiniflow/ragflow#2501]
### Describe your problem

运行docker build -t infiniflow/ragflow:dev .时，出现ERROR [internal] load metadata for docker.io/infiniflow/ragflow-base:v2.0 ，单独运行docker pull infiniflow/ragflow-base:v2.0,成功后，总是出现多处错误

**Comment by KevinHuSh** [comment]
Could you paste the error message?

**Comment by xxz196801** [comment]
单独安装/infiniflow/ragflow-base:v2.0后，再执行命令docker build -t infiniflow/ragflow:dev .还是勉强可以的
