### ISSUE TITLE
Demo website gets stuck in the document parsing stage.

### ISSUE THREAD

**Issue by vikotse** [infiniflow/ragflow#251]
### Describe your problem

<img width="1019" alt="image" src="https://github.com/infiniflow/ragflow/assets/5728396/07a28103-8bbe-4088-9286-19fa1954ce47">
After several attempts, it did not work.

**Comment by KevinHuSh** [comment]
Thanks for follwing!

Our demo site is a little short of resouces, you might wait a little bit for processing the docs please.

**Comment by KevinHuSh** [comment]
Thanks for follwing!

Our demo site is a little short of resouces, you might wait a little bit for processing the docs please.
