### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#2519]
### Describe your problem

env:

Operating system: Ubuntu 24.04 (Kernel version: 6.8.0-44-generic)
CPU Type: x86_64
Memory: 62Gi
Docker Version: 24.0.7,
Python Version: 3.11.4

after repeating  same question to complete the same dialog, same  conversation it will throws  following error:

**ERROR**: Dealer._add_filters() missing 1 required positional

**Comment by KevinHuSh** [comment]
Fail to reproduce it.
I guess your code version is not consistant with branch main.

**Comment by yangboz** [comment]
> Fail to reproduce it. I guess your code version is not consistant with branch main.

Current Repo: ragflow
Commit Id: 80163c0
