### ISSUE TITLE
[Question]: Can you publish an article referencing your project? 

### ISSUE THREAD

**Issue by Darryl-lilin** [infiniflow/ragflow#2532]
### Describe your problem

Can you publish an article referencing your project? If so, how should I cite the reference?

If you need further assistance or specific guidelines on how to structure your article or citation, feel free to ask!

**Comment by writinwaters** [comment]
Hi @Darryl-lilin, Apologies, but I don't quite understand your point. Could you elaborate a bit?

**Comment by writinwaters** [comment]
Blog articles about RAGFlow can be found on either medium.com or our official site, which is ragflow.io.

**Comment by Darryl-lilin** [comment]
> Hi @Darryl-lilin, Apologies, but I don't quite understand your point. Could you elaborate a bit?嗨，抱歉，但我不太明白你的意思。您能详细解释一下吗？

I want to make modifications based on the code and then write a paper to publish it.

**Comment by writinwaters** [comment]
Thanks for the clarification. You can add a reference to our github repo, https://github.com/infiniflow/ragflow, in your paper.

**Comment by Darryl-lilin** [comment]
Thank you for your response.
