### ISSUE TITLE
[Question]: Run: docker build -t infiniflow/ragflow:dev . error.

### ISSUE THREAD

**Issue by xxz196801** [infiniflow/ragflow#2558]
### Describe your problem

运行ragflow11.0版本时，执行命令docker build -t infiniflow/ragflow:dev .时，出错。无法继续运行下去。显示错误内容如下：
![image](https://github.com/user-attachments/assets/1441b526-9116-478b-a1d8-89099beed4e9)
感觉应该是infiniflow/ragflow-base:v2.0升级缘故，执行命令docker pull infiniflow/ragflow-base:v2.0得以继续执行下去。在git clone现实库时，运行命令docker build -f Dockerfile.scratch -t infiniflow/ragflow:dev .时，出现[internal] load metadata for docker.io/library/ubuntu:24.04错误。请给出一个解决办法，谢谢！

**Comment by JinHai-CN** [comment]
Have you check your network connection?
I just use the latest version to run the docker builder, it works.

**Comment by JinHai-CN** [comment]
![6df67d85-b8de-4f6d-82ae-5a971df9b213](https://github.com/user-attachments/assets/ce6e1ace-4cc4-49a6-ae7e-4fa68059fa0a)

**Comment by KevinHuSh** [comment]
The error message shows you can't access docker.io.

**Comment by rplescia** [comment]
I have the same issue trying to build a docker image, there is an issue raised for this by another user. This may be a bug #2564 

![image](https://github.com/user-attachments/assets/9273240e-edde-4d3a-bab2-f8d9c0404c6d)

**Comment by JinHai-CN** [comment]
Use following command doesn't issue any error. Please check your network.
`
docker build -t infiniflow/ragflow:dev .
`

![6588ef81-fa12-47ef-97c0-3b86ee8b858e](https://github.com/user-attachments/assets/caac6668-30f2-44f4-afa6-4d990b5f1500)

**Comment by rplescia** [comment]
Hi, there is nothing wrong with the network, I can pull and run the pre-built docker images OK but I won't build locally. 
![Capture](https://github.com/user-attachments/assets/4c6140e8-df42-42d6-8858-f20796018484)

**Comment by xxz196801** [comment]
估计是docker版本问题，我用的是最新docker版本，以前老版本可以用

**Comment by KevinHuSh** [comment]
Comment out the line with 'COPY' command.

**Comment by rplescia** [comment]
The image builds successfully after commenting out the COPY command but the image won't run now.
![Screenshot from 2024-09-28 09-04-51](https://github.com/user-attachments/assets/2c6944f6-e540-41bd-93de-44881402fbfd)
