### ISSUE TITLE
[Bug]: Repeated answer history problems occur when using Agent

### ISSUE THREAD

**Issue by yijingli19** [infiniflow/ragflow#2566]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Actual behavior

When I have a conversation using the default WebSearch Assistant templates, previous questions are answered repeatedly
![微信截图_20240924174012](https://github.com/user-attachments/assets/4534c9cb-f1de-4229-a9ec-e2859089748b)
![截图_20240924190013](https://github.com/user-attachments/assets/427ebafb-5355-4a11-916c-557c9019a9c2)

### Steps to reproduce

```Markdown
The parameters are not changed, and the prompt word uses the default prompt word.
```

**Comment by KevinHuSh** [comment]
It depends on the NLP capability of LLM.
![image](https://github.com/user-attachments/assets/432fbc1f-3f85-47ff-8b12-e80b845bfd9d)

**Comment by gujiandada** [comment]
thx,question

**Comment by yijingli19** [comment]
> It depends on the NLP capability of LLM. ![image](https://private-user-images.githubusercontent.com/12318111/370684472-432fbc1f-3f85-47ff-8b12-e80b845bfd9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTUxNTEsIm5iZiI6MTcyNzQxNDg1MSwicGF0aCI6Ii8xMjMxODExMS8zNzA2ODQ0NzItNDMyZmJjMWYtM2Y4NS00N2ZmLThiMTItZTgwYjg0NWJmZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA1MjczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NjlmZmRiYzFhZDIzN2U4ODRlYWMwZjU4MzYxMTAzYTcxMzc4NGEyMjY4MjFiMTBlYTRmNjM0YWRkODk3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0nmpWmiJ_V7UF7cbGAALHnkSwfkON6vpIlQH3axeBJ4)

What size model are you using? Because this situation occurred when I used deepseek-chat in the demo, and a similar situation occurred when using qwen2-7b-instruct locally.

**Comment by KevinHuSh** [comment]
gpt-4
