### ISSUE TITLE
[Question]: Do we have a version range or recommended version for postgres?

### ISSUE THREAD

**Issue by KevinLiangX** [infiniflow/ragflow#2572]
### Describe your problem

Do we have a version range or recommended version for postgres?

**Comment by KevinHuSh** [comment]
No clue yet.

**Comment by KevinLiangX** [comment]
Hi， It‘s ok for  PostgreSQL 10.12 (Debian 10.12-2.pgdg90+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**Comment by KevinHuSh** [comment]
> Hi， It‘s ok for PostgreSQL 10.12 (Debian 10.12-2.pgdg90+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

Thanks a lot!!!
