### ISSUE TITLE
[Bug]: Can't find service_conf.yaml when deploy RAGFlow.

### ISSUE THREAD

**Issue by CoderJzy** [infiniflow/ragflow#2587]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

dda1367ab217b451f5365b0afabad04a5c4a7374

### Actual behavior

在按照本地部署的流程执行到bash docker/entrypoint.sh的时候会报conf下的service_conf.yaml找不到
![image](https://github.com/user-attachments/assets/ea1d48ed-c2e8-46f4-9118-0042edb9754d)

然后我看了一下conf目录下是存在一个指向docker/service_conf.yaml的软链接文件的，但是在运行的时候会显示找不到。然后我尝试把docker目录下的service_conf.yaml复制到conf目录下后，就可以正常部署了，不知道这算不算个bug。

### Steps to reproduce

```Markdown
按照README.md的本地部署流程，运行到bash docker/entrypoint.sh时
```

**Comment by yuzhichang** [comment]
@CoderJzy Please try latest main.
