### ISSUE TITLE
[Feature Request]: Requirement: Currently, the answers in the chat API do not show citations. It is recommended to show citations.

### ISSUE THREAD

**Issue by mi-zy** [infiniflow/ragflow#2593]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Show Quote is selected,so chat API recommended to show citations.
```

### Describe the feature you'd like

chat API recommended to show citations.

**Comment by Feiue** [comment]
> ### Is there an existing issue for the same feature request?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> ```
> Show Quote is selected,so chat API recommended to show citations.
> ```
> 
> ### Describe the feature you'd like
> chat API recommended to show citations.
> 
> ### Describe implementation you've considered
> _No response_
> 
> ### Documentation, adoption, use case
> _No response_
> 
> ### Additional information
> _No response_
Which API endpoint are you using? I'd like to see your URL or request.

**Comment by Feiue** [comment]
> ### Is there an existing issue for the same feature request?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> ```
> Show Quote is selected,so chat API recommended to show citations.
> ```
> 
> ### Describe the feature you'd like
> chat API recommended to show citations.
> 
> ### Describe implementation you've considered
> _No response_
> 
> ### Documentation, adoption, use case
> _No response_
> 
> ### Additional information
> _No response_

Which API endpoint are you using? I'd like to see your URL or request.

**Comment by mi-zy** [comment]
url like this :      ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat

**Comment by mi-zy** [comment]
![Uploading 1.JPG…]()

**Comment by Feiue** [comment]
> url like this : ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat

ok,I will check it

**Comment by Feiue** [comment]
This jpg link seems to be wrong

**Comment by Feiue** [comment]
If you use  ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat, you can't set `quote=true`, so you can't see the quote.

Suggest you use ip:port/v1/api/completion if you want to set quote. This is the api. You can curl this url and set data like:
```
{
    "conversation_id":"99071d7e7bed11ef8a5d0242ac120006",
    "messages":[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "1"}
  ],
  "quote":true
}
```

**Comment by mi-zy** [comment]
If I call the API using the GET method in the address bar, can "quote" be set to true by default? What you mentioned is a POST request, where parameters are placed in the request body and won't be displayed in the address bar. But I am using the address bar.

**Comment by Feiue** [comment]
> If I call the API using the GET method in the address bar, can "quote" be set to true by default? What you mentioned is a POST request, where parameters are placed in the request body and won't be displayed in the address bar. But I am using the address bar.

If you want to see reference in `ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat`. You can try to change the source code which is in `api/apps/api_app.py` line 197. "  `quote" not in req: req["quote"] = False`. If you must use it in `demo`, tell me please.

**Comment by mi-zy** [comment]
OK，thanks。Here is another phenomenon.  see what the problem is. “AttributeError("'list' object has no attribute 'get'")”
![typewong](https://github.com/user-attachments/assets/a218c5b3-cada-4321-894c-b1875a34fe16)

**Comment by Feiue** [comment]
> OK，thanks。Here is another phenomenon. see what the problem is. “AttributeError("'list' object has no attribute 'get'")” ![typewong](https://private-user-images.githubusercontent.com/46146632/371387549-a218c5b3-cada-4321-894c-b1875a34fe16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTA0OTYsIm5iZiI6MTcyNzQxMDE5NiwicGF0aCI6Ii80NjE0NjYzMi8zNzEzODc1NDktYTIxOGM1YjMtY2FkYS00MzIxLTg5NGMtYjE4NzVhMzRmZTE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA0MDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjI0NDk4MmMyOTBmNzg1Y2E5YzBmNDBhMjRlMWY3MjAzOTE5MTNkY2YzYjM4ZmVjNTIyMzY5Y2Y0MDQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.678kvgQgoG94pMxAcFLgUtyzA3IjftJIejTtlGSBtBs)

The problem appears in which situation?

**Comment by mi-zy** [comment]
by  https://demo.ragflow.io/      Chat Bot API-->Preview，at https://demo.ragflow.io/chat/share?shared_id=ragflow-Y3Zjc3...YTA3NDIwMT&from=chat    ask a quetion ,Switch tabs. Then this error occurs.

**Comment by mi-zy** [comment]
> > If I call the API using the GET method in the address bar, can "quote" be set to true by default? What you mentioned is a POST request, where parameters are placed in the request body and won't be displayed in the address bar. But I am using the address bar.
> 
> If you want to see reference in `ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat`. You can try to change the source code which is in `api/apps/api_app.py` line 197. `if "quote" not in req: req["quote"] = False`. If you must use it in `demo`, tell me please.

I hope to make this changes（...if "quote" not in req: req["quote"] = True） in the images file.(image: swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev)

**Comment by Feiue** [comment]
> > > If I call the API using the GET method in the address bar, can "quote" be set to true by default? What you mentioned is a POST request, where parameters are placed in the request body and won't be displayed in the address bar. But I am using the address bar.
> > 
> > 
> > If you want to see reference in . You can try to change the source code which is in  line 197. . If you must use it in , tell me please.`ip:port/chat/share?shared_id=ragflow-IzN2JjNTc4NzY5ZTE4NGVhZT&from=chat``api/apps/api_app.py``if "quote" not in req: req["quote"] = False``demo`
> 
> I hope to make this changes（...if "quote" not in req: req["quote"] = True） in the images file.(image: swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev)

This may can't be implemented in `demo`, you can change it in local.

**Comment by Feiue** [comment]
> OK，thanks。Here is another phenomenon. see what the problem is. “AttributeError("'list' object has no attribute 'get'")” ![typewong](https://private-user-images.githubusercontent.com/46146632/371387549-a218c5b3-cada-4321-894c-b1875a34fe16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTM0MjUsIm5iZiI6MTcyNzQxMzEyNSwicGF0aCI6Ii80NjE0NjYzMi8zNzEzODc1NDktYTIxOGM1YjMtY2FkYS00MzIxLTg5NGMtYjE4NzVhMzRmZTE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA0NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTM2ZWQ1Y2Y1NmU4MzQ2ZjczNjc4NzU4NzE4MDg2ODY1YTc5Y2U0MTYzODVlNjMyZTg1Yjk4MWI0MWE5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QMoy-OSKmX3oZfS3HigU4CMRMtKnKtLOgS6HXEy0Blg)

I understand it, it's a bug and will fix it

**Comment by JinHai-CN** [comment]
@Feiue Any update on this issue?

**Comment by Feiue** [comment]
It has been fixed.
