### ISSUE TITLE
[Bug]: Unable to retrieval some data after parsing excel by general method

### ISSUE THREAD

**Issue by Gitttttttt** [infiniflow/ragflow#2596]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2f33ec7

### Actual behavior

[accounts.xlsx](https://github.com/user-attachments/files/17142186/accounts.xlsx)

I uploaded the above excel file in my knowledge base and parsed it using the general method. The detailed configuration is as follows：
![image](https://github.com/user-attachments/assets/c11ae747-30d5-49dd-84ba-c1591cb67939)

And then，when I send a request for the `/retrieval_test` , I got nothing, even if I set the similarity weight to 0. But the data actually exists. As the pic show：
![b0619b8a80976dfe33f001d087b9ea3](https://github.com/user-attachments/assets/e33658ed-b458-4174-8ddd-b25ae8631517)
![01f41a94faf8c766b36cc6ec9d9ef4f](https://github.com/user-attachments/assets/ce58f041-9c8e-45d7-8f3b-0e0b74ba1d75)

### Steps to reproduce

```Markdown
As the `Actual behavior` show
```

**Comment by JobSmithManipulation** [comment]
![1728641078243](https://github.com/user-attachments/assets/da6f44f9-e198-42ae-bc05-6ae8c8014565)
The latest RagFlow development environment code has no issues with retrieval testing, and we will deploy it to the demo as soon as possible
