### ISSUE TITLE
[Bug]: AttributeError: 'ESConnection' object has no attribute 'es'

### ISSUE THREAD

**Issue by ly0303521** [infiniflow/ragflow#2611]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

832c90ac3e319e5f615dbbd1b52545ad3258b90f

### Other environment information

```Markdown
ubuntu20.04
```

### Actual behavior

sudo bash ./entrypoint.sh

### Steps to reproduce

```Markdown
Follow the steps of "Launch service from source for development"， after "sudo bash ./entrypoint.sh", the error comes
```

**Comment by ly0303521** [comment]
> (ragflow) ly@BOE:~/SPACE_SDD/Projects/ragflow$ sudo bash ./entrypoint.sh
> Traceback (most recent call last):
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/ragflow_server.py", line 26, in <module>
> Traceback (most recent call last):
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/svr/task_executor.py", line 29, in <module>
>     from api.apps import app
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/apps/__init__.py", line 26, in <module>
>     from api.db.db_models import close_connection
>     from api.db.services.file2document_service import File2DocumentService
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/db/db_models.py", line 33, in <module>
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/db/services/__init__.py", line 18, in <module>
>     from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/settings.py", line 35, in <module>
>     from .user_service import UserService
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/db/services/user_service.py", line 22, in <module>
>     from rag.utils.es_conn import ELASTICSEARCH
>     from api.db.db_models import DB, UserTenant
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/utils/es_conn.py", line 462, in <module>
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/db/db_models.py", line 33, in <module>
>     from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
>   File "/home/ly/SPACE_SDD/Projects/ragflow/api/settings.py", line 35, in <module>
>     from rag.utils.es_conn import ELASTICSEARCH
>     ELASTICSEARCH = ESConnection()
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/utils/es_conn.py", line 462, in <module>
>                     ^^^^^^^^^^^^^^
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/utils/__init__.py", line 28, in _singleton
>     instances[key] = cls(*args, **kw)
>                      ^^^^^^^^^^^^^^^^
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/utils/es_conn.py", line 23, in __init__
>     ELASTICSEARCH = ESConnection()
>     if not self.es.ping():
>            ^^^^^^^
>                     ^^^^^^^^^^^^^^
>   File "/home/ly/SPACE_SDD/Projects/ragflow/rag/utils/__init__.py", line 28, in _singleton
>     instances[key] = cls(*args, **kw)
> AttributeError: 'ESConnection' object has no attribute 'es'
>                      ^^^^^^^^^^^^^^^^
>

**Comment by JinHai-CN** [comment]
Have you checked your Elasticsearch instance status?

**Comment by ly0303521** [comment]
> Have you checked your Elasticsearch instance status?

@JinHai-CN 
Thanks for your reply, I think there's no problem with base components of es01、mysql、minio、redis, because ragflow works very well when launching from docker, I just replace launching from docker with launching from source,  the base components services are still running.

**Comment by JinHai-CN** [comment]
Check the host address of ES and the config if they are not matched.

**Comment by ly0303521** [comment]
Because there two definition of "delete_llm" in "llm_app.py", in latest version, it's solved
