### ISSUE TITLE
[Question]:  When I chat with Agent, error: LookupError('Model(deepseek-chat) not authorized')

### ISSUE THREAD

**Issue by LillyChen** [infiniflow/ragflow#2612]
### Describe your problem

factory: 'Tongyi-Qianwen' 设置通义千问，但是agent问答的时候报错说LookupError('Model(deepseek-chat) not authorized')

**Comment by JinHai-CN** [comment]
From the error message, it seems 'deepseek-chat' is used in your agent. You may change the LLM of your agent to 'Qianwen'.

**Comment by LillyChen** [comment]
I found the problem. Thank you!
