### ISSUE TITLE
[Bug]: No requirments.txt 

### ISSUE THREAD

**Issue by ly0303521** [infiniflow/ragflow#2631]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

674d342761d7f03df5c58854f9c9309fb5cf40f2

### Actual behavior

"requirments.txt"  disappeared, I remember it existed before.

### Steps to reproduce

```Markdown
"requirments.txt"  disappeared, I remember it existed before.
```

**Comment by yingfeng** [comment]
Poetry is used right now, requirements.txt is removed instead.

**Comment by yuzhichang** [comment]
poetry is much better than pip.
