### ISSUE TITLE
[Feature Request]: Ability to add custom search engine/website to agent

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2634]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
No
```

### Describe the feature you'd like

Making it possible for the agent to also search on a custom website/database, which require an API and Endpoint.

### Documentation, adoption, use case

```Markdown
Imagine you classify that a "special search" in another kb is needed. Therefore it will call the other source by using its API and Endpoint to do so, retrieves the top results and so on.
```

**Comment by KevinHuSh** [comment]
Do you mean this: 
![image](https://github.com/user-attachments/assets/fb2f1cb3-231e-42db-ab3c-87ad6e512412)

**Comment by Said-Apollo** [comment]
Not quite, here you use DuckDuckGo, Baidu and Co. What if I have some other App, which also conducts searches on custom datasets, but it needs an API and Endpoint
