### ISSUE TITLE
[Question]: Redundant database.log

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#264]
### Describe your problem

We've observed that the size of the database.log file increases rapidly, reaching gigabytes in a very short span of time. By using tail -f to monitor the file, we noticed it generates numerous entries similar to the ones below. Is there a way to suppress these logs?

Returning 140199553734352 to pool.
('SELECT `t1`.`id`, `t1`.`doc_id`, `t1`.`from_page`, `t1`.`to_page`, `t2`.`kb_id`, `t2`.`parser_id`, `t2`.`parser_config`, `t2`.`name`, `t2`.`type`, `t2`.`location`, `t2`.`size`, `t3`.`tenant_id`, `t3`.`language`, `t4`.`embd_id`, `t4`.`img2txt_id`, `t4`.`asr_id`, `t1`.`update_time` FROM `task` AS `t1` INNER JOIN `document` AS `t2` ON (`t1`.`doc_id` = `t2`.`id`) INNER JOIN `knowledgebase` AS `t3` ON (`t2`.`kb_id` = `t3`.`id`) INNER JOIN `tenant` AS `t4` ON (`t3`.`tenant_id` = `t4`.`id`) WHERE ((((((`t2`.`status` = %s) AND (`t2`.`run` = %s)) AND NOT (`t2`.`type` = %s)) AND (`t1`.`progress` = %s)) AND (`t1`.`update_time` >= %s)) AND ((`t1`.`create_time` %% %s) = %s)) ORDER BY `t1`.`update_time` ASC LIMIT %s OFFSET %s', ['1', '1', 'virtual', 0.0, 1712592641735, 2, 1, 64, 0])
('SELECT `t1`.`id`, `t1`.`doc_id`, `t1`.`from_page`, `t1`.`to_page`, `t2`.`kb_id`, `t2`.`parser_id`, `t2`.`parser_config`, `t2`.`name`, `t2`.`type`, `t2`.`location`, `t2`.`size`, `t3`.`tenant_id`, `t3`.`language`, `t4`.`embd_id`, `t4`.`img2txt_id`, `t4`.`asr_id`, `t1`.`update_time` FROM `task` AS `t1` INNER JOIN `document` AS `t2` ON (`t1`.`doc_id` = `t2`.`id`) INNER JOIN `knowledgebase` AS `t3` ON (`t2`.`kb_id` = `t3`.`id`) INNER JOIN `tenant` AS `t4` ON (`t3`.`tenant_id` = `t4`.`id`) WHERE ((((((`t2`.`status` = %s) AND (`t2`.`run` = %s)) AND NOT (`t2`.`type` = %s)) AND (`t1`.`progress` = %s)) AND (`t1`.`update_time` >= %s)) AND ((`t1`.`create_time` %% %s) = %s)) ORDER BY `t1`.`update_time` ASC LIMIT %s OFFSET %s', ['1', '1', 'virtual', 0.0, 0, 2, 0, 64, 0])
Returning 139777349632080 to pool.
Returning 140199553734352 to pool.
('SELECT `t1`.`id`, `t1`.`doc_id`, `t1`.`from_page`, `t1`.`to_page`, `t2`.`kb_id`, `t2`.`parser_id`, `t2`.`parser_config`, `t2`.`name`, `t2`.`type`, `t2`.`location`, `t2`.`size`, `t3`.`tenant_id`, `t3`.`language`, `t4`.`embd_id`, `t4`.`img2txt_id`, `t4`.`asr_id`, `t1`.`update_time` FROM `task` AS `t1` INNER JOIN `document` AS `t2` ON (`t1`.`doc_id` = `t2`.`id`) INNER JOIN `knowledgebase` AS `t3` ON (`t2`.`kb_id` = `t3`.`id`) INNER JOIN `tenant` AS `t4` ON (`t3`.`tenant_id` = `t4`.`id`) WHERE ((((((`t2`.`status` = %s) AND (`t2`.`run` = %s)) AND NOT (`t2`.`type` = %s)) AND (`t1`.`progress` = %s)) AND (`t1`.`update_time` >= %s)) AND ((`t1`.`create_time` %% %s) = %s)) ORDER BY `t1`.`update_time` ASC LIMIT %s OFFSET %s', ['1', '1', 'virtual', 0.0, 1712592641735, 2, 1, 64, 0])
('SELECT `t1`.`id`, `t1`.`doc_id`, `t1`.`from_page`, `t1`.`to_page`, `t2`.`kb_id`, `t2`.`parser_id`, `t2`.`parser_config`, `t2`.`name`, `t2`.`type`, `t2`.`location`, `t2`.`size`, `t3`.`tenant_id`, `t3`.`language`, `t4`.`embd_id`, `t4`.`img2txt_id`, `t4`.`asr_id`, `t1`.`update_time` FROM `task` AS `t1` INNER JOIN `document` AS `t2` ON (`t1`.`doc_id` = `t2`.`id`) INNER JOIN `knowledgebase` AS `t3` ON (`t2`.`kb_id` = `t3`.`id`) INNER JOIN `tenant` AS `t4` ON (`t3`.`tenant_id` = `t4`.`id`) WHERE ((((((`t2`.`status` = %s) AND (`t2`.`run` = %s)) AND NOT (`t2`.`type` = %s)) AND (`t1`.`progress` = %s)) AND (`t1`.`update_time` >= %s)) AND ((`t1`.`create_time` %% %s) = %s)) ORDER BY `t1`.`update_time` ASC LIMIT %s OFFSET %s', ['1', '1', 'virtual', 0.0, 0, 2, 0, 64, 0])
Returning 140199553734352 to pool.
Returning 139777349632080 to pool.

**Comment by KevinHuSh** [comment]
Fixed. Please pull the latest source code and docker images.
