### ISSUE TITLE
[Question]: How to modify the max token for LLM in the agent module

### ISSUE THREAD

**Issue by GxiFan** [infiniflow/ragflow#2640]
### Describe your problem

When I use the agent module to create a chatbot for Q&A, the response shows 'Due to the length, the response was truncated. Would you like to continue?'. Is this because the agent module limits the max tokens for output? How can I modify the max tokens to prevent the response from being truncated?

**Comment by guoyuhao2330** [comment]
![image](https://github.com/user-attachments/assets/c023c163-c9a1-4db5-baf2-d079a801d3da)

**Comment by GxiFan** [comment]
thank you
