### ISSUE TITLE
[Bug]: Chat function can not work !

### ISSUE THREAD

**Issue by crazymsn** [infiniflow/ragflow#2647]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

i don't know

### Commit ID

i don't know

### Actual behavior

Chat function can not work !

### Steps to reproduce

```Markdown
Chat function can not work !
```

**Comment by KevinHuSh** [comment]
Could you specify the error message and the scenario?

**Comment by yuzhichang** [comment]
Close due to no response.
