### ISSUE TITLE
[Bug]: call ChatGLM failed

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

d0a1ffe6e21e81f64b1c9199123be6936dbc4a01

### Actual behavior

Configure the LLM as ChatGLM and chat, got 
ERROR: Completions.create() got an unexpected keyword argument 'presence_penalty'
![image](https://github.com/infiniflow/ragflow/assets/35255629/a9697cfa-6424-4570-8e58-13812344cf86)

### Steps to reproduce

```Markdown
Deployed local docker environment.
Create a knowledge base, uploading some docs.
Config ChatGLM as LLM and config the ApiKey.
Then create an assistant with ChatGLM, chat with it, the error will happen.
```

**Comment by Yang-HangWA** [comment]
I met this problem when I run ChatGLM . You can solve this by closing the `Presence penalty` option.

**Comment by KevinHuSh** [comment]
Pull the latest source code and images, try it again.

The website has  already updated.
