### ISSUE TITLE
[Question]: Failed to Deploy

### ISSUE THREAD

**Issue by taowang1993** [infiniflow/ragflow#2655]
### Describe your problem

max@Tao-M2 docker % docker run --rm --privileged --pid=host alpine sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144
max@Tao-M2 docker % docker compose up -d
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
[+] Running 6/6
 ✔ Network docker_ragflow    Created                                                                                    0.0s 
 ✔ Container ragflow-minio   Started                                                                                    0.3s 
 ✔ Container ragflow-es-01   Healthy                                                                                   20.8s 
 ✔ Container ragflow-mysql   Healthy                                                                                   10.8s 
 ✔ Container ragflow-redis   Started                                                                                    0.3s 
 ✔ Container ragflow-server  Started                                                                                   20.9s 
max@Tao-M2 docker % docker logs -f ragflow-server
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
[WARNING] [2024-09-29 15:12:24,862] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:24,869] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:25,643] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:25,647] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 39, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/task_service.py", line 20, in <module>
    from deepdoc.parser import PdfParser
  File "/ragflow/deepdoc/parser/__init__.py", line 21, in <module>
    from .txt_parser import RAGFlowTxtParser as TxtParser
  File "/ragflow/deepdoc/parser/txt_parser.py", line 13, in <module>
    from deepdoc.parser.utils import get_txt
ImportError: cannot import name 'get_txt' from 'deepdoc.parser.utils' (/ragflow/deepdoc/parser/utils.py). Did you mean: 'get_text'?
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 99, in <module>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 84, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/api_app.py", line 28, in <module>
    from api.db.services.dialog_service import DialogService, chat
  File "/ragflow/api/db/services/dialog_service.py", line 28, in <module>
    from rag.app.resume import forbidden_select_fields4resume
  File "/ragflow/rag/app/resume.py", line 22, in <module>
    from deepdoc.parser.resume import refactor
  File "/ragflow/deepdoc/parser/__init__.py", line 21, in <module>
    from .txt_parser import RAGFlowTxtParser as TxtParser
  File "/ragflow/deepdoc/parser/txt_parser.py", line 13, in <module>
    from deepdoc.parser.utils import get_txt
ImportError: cannot import name 'get_txt' from 'deepdoc.parser.utils' (/ragflow/deepdoc/parser/utils.py). Did you mean: 'get_text'?
[WARNING] [2024-09-29 15:12:32,257] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:32,261] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:32,442] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 15:12:32,447] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 99, in <module>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 84, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/api_app.py", line 28, in <module>
    from api.db.services.dialog_service import DialogService, chat
  File "/ragflow/api/db/services/dialog_service.py", line 28, in <module>
    from rag.app.resume import forbidden_select_fields4resume
  File "/ragflow/rag/app/resume.py", line 22, in <module>
    from deepdoc.parser.resume import refactor
  File "/ragflow/deepdoc/parser/__init__.py", line 21, in <module>
    from .txt_parser import RAGFlowTxtParser as TxtParser
  File "/ragflow/deepdoc/parser/txt_parser.py", line 13, in <module>
    from deepdoc.parser.utils import get_txt

**Comment by KevinHuSh** [comment]
Pull the latest dev version of docker image.

**Comment by crazymsn** [comment]
the same question！

**Comment by MeteorshoW8** [comment]
met the same error.

**Comment by MeteorshoW8** [comment]
> Pull the latest dev version of docker image.

How to pull the latest dev version? which yaml doc.

**Comment by xiayi0409** [comment]
met the same error.how to slove it?

**Comment by xiayi0409** [comment]
When pulling the docker image, my network connection failed, but I have already modified the daemon's image. How should I solve this problem？

docker compose -f docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ✘ ragflow Error Get "https://registry-1.docker.io/v2/": dial tcp 199.59.148.7:443: co...               33.6s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 199.59.148.7:443: connect: connection refused

**Comment by yuzhichang** [comment]
@xiayi0409 Change `RAGFLOW_IMAGE` setting in `docker/.env`. See `docker/.env` for details.

**Comment by KevinHuSh** [comment]
> > Pull the latest dev version of docker image.
> 
> How to pull the latest dev version? which yaml doc.

docker pull {RAGFLOW_IMAGE}
RAGFLOW_IMAGE is defined in your docker/.env

**Comment by xiayi0409** [comment]
> @xiayi0409 Change `RAGFLOW_IMAGE` setting in `docker/.env`. See `docker/.env` for details.

Thanks soooooooooo much！But I encountered another problem，After parsing the document, proceed “检索测试”，ERROR——AttributeError("'NoneType' object has no attribute 'encode_queries'")  

May I ask what problem you encountered？？

**Comment by KevinHuSh** [comment]
It's like the embedding model you configured does not exist anymore.
Suggestion:
Re-configure the embedding model in KB and system setting.

**Comment by xiayi0409** [comment]
> It's like the embedding model you configured does not exist anymore. Suggestion: Re-configure the embedding model in KB and system setting.

Thank you for your help!

**Comment by KevinHuSh** [comment]
Arm64 is not ready yet.

**Comment by yuzhichang** [comment]
We have difficulity on building multi-arch image with CI. So we will not publish arm64 image officially in the near future. 
However you can build it by yourself on a `linux/arm64` host:
```
docker build --build-arg ARCH=arm64 -f Dockerfile.slim -t infiniflow/ragflow:dev-slim .
docker build --build-arg ARCH=arm64 -f Dockerfile -t infiniflow/ragflow:dev .
```
