### ISSUE TITLE
[Bug]: exec ./entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by DemonDamon** [infiniflow/ragflow#266]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

dfeqxewc

### Actual behavior

i have followed the instructions but got this error while printout the log by
'sudo docker logs -f ragflow-server'
-->
exec ./entrypoint.sh: no such file or directory

### Steps to reproduce

```Markdown
1. cd ragflow/docker
2. chmod +x ./entrypoint.sh
3. sudo docker compose -f docker-compose-CN.yml up -d
```

**Comment by Yang-HangWA** [comment]
It seems that there is no commit ID dfeqxewc. I think you can try docker-compose.yml with command `docker compose -d`.  Follow [this](https://github.com/infiniflow/ragflow/tree/main?tab=readme-ov-file#%EF%B8%8F-build-from-source).

**Comment by KevinHuSh** [comment]
Are your machine Arm64 architecture ?

**Comment by ChaoII** [comment]
I have the same problem in WSL.

**Comment by younggggger** [comment]
i have the same problem.
PS E:\gpt\ragflow\docker> docker logs -f ragflow-server
exec ./entrypoint.sh: no such file or directory

**Comment by KevinHuSh** [comment]
What about removing this line in docker compose yaml?
![image](https://github.com/infiniflow/ragflow/assets/12318111/c88de2b7-dc79-4ab5-b0e6-f1ac2edf3367)

**Comment by younggggger** [comment]
It still doesn't work, and there are even more error messages.

before:
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory


now
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory
exec ./entrypoint.sh: no such file or directory

**Comment by drndos** [comment]
If you comment out the line "- ./entrypoint.sh:/ragflow/entrypoint.sh" it might work. I am more concerned about the dockerfiles transparency. Could you please provide the base Dockerfiles you are using? Thank you.

**Comment by KevinHuSh** [comment]
Check this version.

Docker Compose >= v2.26.1

**Comment by younggggger** [comment]
Docker is the latest version.

**Comment by 448486810** [comment]
Docker is the latest version.
have    - ./entrypoint.sh:/ragflow/entrypoint.sh
logs exec ./entrypoint.sh: no such file or directory
can't  use files add entrypoint.sh

please help me

**Comment by ooooo-create** [comment]
i think may be it only appear in the windows, we should convert the sh file fromCRLF(Windows) toLF (Linux) end of linesequence. The vscode can change it in lower right. also can use `dos2unix .\entrypoint.sh` which install in https://sourceforge.net/projects/dos2unix/files/dos2unix/7.5.2/dos2unix-7.5.2-win64.zip/download and add it to PATH. but now i don't have the windows machine, so i am not sure it is useful

**Comment by ooooo-create** [comment]
> i think may be it only appear in the windows, we should convert the sh file fromCRLF(Windows) toLF (Linux) end of linesequence. The vscode can change it in lower right. also can use `dos2unix .\entrypoint.sh` which install in https://sourceforge.net/projects/dos2unix/files/dos2unix/7.5.2/dos2unix-7.5.2-win64.zip/download and add it to PATH. but now i don't have the windows machine, so i am not sure it is useful

I have tried it , it seems useful to  convert the sh file from **CRLF**(Windows) to **LF** (Linux) end of linesequence
![图片](https://github.com/infiniflow/ragflow/assets/106524776/4fe8a9bb-a831-48a3-a274-7dd586f83440)
