### ISSUE TITLE
[Bug]: [ERROR]No module named 'FlagEmbedding' when uploading to knowledge base

### ISSUE THREAD

**Issue by tanzeel291994** [infiniflow/ragflow#2671]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest(2667)

### Other environment information
This is from 'Launch service from source for development'

_No response_

### Actual behavior

![image](https://github.com/user-attachments/assets/d97ef241-5298-454e-afca-1dae332c2b0b)

No module named 'FlagEmbedding'

### Steps to reproduce

```Markdown
1. Uploading .xlsx file to knowledge base.
2. Start parsing when the error comes up on the UI. and parsing fails
```

**Comment by RickFallen** [comment]
> for these dependencies to get installed `[tool.poetry.group.full.dependencies] bcembedding = "0.1.3" fastembed = "^0.3.6" flagembedding = "1.2.10" torch = "2.3.0" transformers = "4.38.1"`
> 
> need to `poetry install --with full`

__________________________


it works , thx
