### ISSUE TITLE
[Question]: Set Xinference as default system LLM or disable local embedding model

### ISSUE THREAD

**Issue by yufeng97** [infiniflow/ragflow#2684]
### Describe your problem

Hi, thank you for the awesome project.

I would like to setup a default model which hosted by Xinference for all users, so that new user does not need to configure the system LLM.
Is it able to disable local embedding/rerank model like 'BAAI/bge-large-zh-v1.5' which is quite resource consuming and sometimes makes application crash.

**Comment by KevinHuSh** [comment]
Pull the latest dev-slim version of docker image which deprecated inside-inference.
Or, set the envirement variable: LIGHTEN=1

What about setting LLM in conf/service_conf.ymal?

**Comment by yufeng97** [comment]
Thanks, I will have a try.
