### ISSUE TITLE
[Question]: Ollama setup help

### ISSUE THREAD

**Issue by hirowa** [infiniflow/ragflow#269]
### Describe your problem

Hi, I'm having trouble setting up ragflow with Ollama. this is the error I'm getting, and I've tried different versions in the base URL without success.

Hope you can help me!

This image is running Ollama in docker
![image](https://github.com/infiniflow/ragflow/assets/42184093/e3be5556-ca1d-4583-8d08-66eb54ed7cd7)

This image is running Ollama as Windows 11 .exe
![image](https://github.com/infiniflow/ragflow/assets/42184093/c404cbf3-b7cf-46b9-afb6-653e945e7618)

**Comment by KevinHuSh** [comment]
You need to install Ollama firstly.

And if you're  using our online service, make sure the server runing ollama has a reachable IP which means you can PING that IP on any machine that has internet connection.

**Comment by hirowa** [comment]
I have Ollama installed, both in docker and as stand alone app. The ollama server is running, but I keep getting those errors.
I'm also using the ragflow locally.

What else can I do?

**Comment by hirowa** [comment]
@ShortArrow yes thank you, I was using "localhost" in the url and I needed to use my IPv4 Address, maybe include that in the documentation?

**Comment by ysyx2008** [comment]
same problem. did u fix it?

**Comment by hirowa** [comment]
> same problem. did u fix it?
@ysyx2008 
Yes, read the message above, use your IPv4 not the localhost.
Open terminal -> ipconfig -> enter
Look for the IPv4 and use that with the default port.
