### ISSUE TITLE
[Bug]: Dockerfile fails to build and run

### ISSUE THREAD

**Issue by rplescia** [infiniflow/ragflow#2693]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main, 0.12.0

### Commit ID

na

### Other environment information

```Markdown
Ubuntu 24.04
Docker: 27.3.1
Docker Compose: 2.29.7

Tested on 2 different computers, laptop with Ubuntu 24.04 Desktop and server with Ubuntu Server 24.04
```

### Actual behavior

I am unable to build the ragflow image using the dockerfile

![Screenshot from 2024-09-30 09-24-22](https://github.com/user-attachments/assets/eb83316d-030f-4959-a1ac-3c0ca697704d)

### Steps to reproduce

```Markdown
Run this command 

sudo docker build -f Dockerfile -t infiniflow/ragflow:dev .
```

**Comment by rplescia** [comment]
I have now managed to build the docker file successfully after using the [updated build instructions found here.](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-the-docker-image-including-embedding-models)  

After the build had been completed, I ran it using the command 'sudo docker run infiniflow/ragflow:dev'. The container fails to start with the following message.

**Comment by KevinHuSh** [comment]
> I have now managed to build the docker file successfully after using the [updated build instructions found here.](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-the-docker-image-including-embedding-models)
> 
> After the build had been completed, I ran it using the command 'sudo docker run infiniflow/ragflow:dev'. The container fails to start with the following message.
> 
> ![image](https://private-user-images.githubusercontent.com/31313681/372103707-0e9406c0-e495-4bd0-b5c3-d1b60ad14695.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzIwNTMsIm5iZiI6MTcyNzc3MTc1MywicGF0aCI6Ii8zMTMxMzY4MS8zNzIxMDM3MDctMGU5NDA2YzAtZTQ5NS00YmQwLWI1YzMtZDFiNjBhZDE0Njk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA4MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMThlM2ZmMmM3OGFiN2QxZmIxOTk3NDAzZWNmYjc2YWYwY2U0YWNhZjc0NmMxMTlhYTcyODIxYmU4NTQzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.slTWp-lNBL7VQlKMFYRwABXJMgbTJQSwrPKk85fXXo4)

Link docker/service_conf.yaml to conf/service_conf.yaml in container.

**Comment by rplescia** [comment]
Hi Kevin, thanks for your reply. I'm not sure I understand what you mean by link the yaml files to the container, can you provide an example please.

**Comment by KevinHuSh** [comment]
docker cp docker/service_conf.yaml ragflow-server:/ragflow/conf/service_conf.yaml

**Comment by yuzhichang** [comment]
@rplescia Look at `docker/docker-compose.yml` for run ragflow container only. However it's recommended to run via the compose file which contains ragflow and its dependencies.

**Comment by rplescia** [comment]
Thanks for all the help. 

So the correct way to start the container after the image has been built is modify the docker-compose.yaml file to use the local image and then start it using 'docker compose up...'?

**Comment by yuzhichang** [comment]
Users needn't to build the ragflow image.  'docker compose up...' download the image automatically.
