### ISSUE TITLE
[Question]: Access to whisper-large-v3 from groq and question about personalized components on the agent flow.

### ISSUE THREAD

**Issue by Palvr** [infiniflow/ragflow#2704]
### Describe your problem

Im looking for some initial guidance on the process of adding custom components to the Agents flow editor, as this would open up many possibilities for personalizing the interactions on it. It would be great if the flow could integrate access to Python scripts.

Additionally, I'd like to know if it's possible to update the models that can be used from Groq, especially Whisper-large-v3

Thank you for your work on this project.

**Comment by KevinHuSh** [comment]
All the components are in agent/component/.  Specify paramter and function _run in component.
