### ISSUE TITLE
[Question]: process "/bin/sh -c cd ./web && npm i && npm run build" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by leokaka2** [infiniflow/ragflow#271]
### Describe your problem

![Snipaste_2024-04-09_09-54-28](https://github.com/infiniflow/ragflow/assets/153987340/20d4612c-316d-48c6-88ad-ce5d07d06542)

在wsl里面执行“docker build -t infiniflow/ragflow:v1.0 .”就挂在这里了？不知道什么问题，有谁知道么？

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question:
It seems the network to the overseas server is little dragging.
Might you try that for a little more times!

**Comment by GuoCoder** [comment]
When building an image, simply add -- network host at the end of the command.
``` 
docker build -t <镜像名> . --network host 
```
