### ISSUE TITLE
[Question]: [ERROR] module 'umap' has no attribute 'UMAP'

### ISSUE THREAD

**Issue by c123853648** [infiniflow/ragflow#2721]
### Describe your problem

When I use the RAPTOR strategy to upload an md file and start parsing, I encounter this error: [ERROR] module 'umap' has no attribute 'UMAP'. If I do not enable the RAPTOR strategy, the parsing is successful. The error message and LLM configuration information are as follows
![微信截图_20241006100940](https://github.com/user-attachments/assets/0cd0a9af-1ad6-41a3-ade2-99b4561e984b)
![微信截图_20241006101420](https://github.com/user-attachments/assets/0e3f5de3-ae1d-4dba-b9c3-8f76e9f7c821)
![微信截图_20241006101442](https://github.com/user-attachments/assets/a3d0d9e1-dcea-447b-972b-c3f190a995f6)

**Comment by KevinHuSh** [comment]
update umap: pip install umap-learn==0.5.6
