### ISSUE TITLE
[Bug]: the same name of PDF uploaded with new content updated will make chunks with inconsistency error

### ISSUE THREAD

**Issue by zhanwenzhuo-github** [infiniflow/ragflow#2725]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

001_zwz

### Actual behavior

I delete the old pdf uploaded, then the new pdf with new content updated with the same name was uploaded, but the chunks content is not up-to-date still remained the old things, so at last I change the pdf with a different name and the chunks content is consistent with the pdf uploaded.

### Expected behavior

As long as the pdf uploaded was deleted, the new pdf even with the same name should be chunked with the consistent content with the pdf newly uploaded.

### Steps to reproduce

```Markdown
1. upload a local pdf then chunked it in the RAGFlow portal, and confirm the chunk is consistent with the pdf content
2. delete the pdf in the RAGFlow portal
3. update the local pdf with new content
4. upload the local pdf updated without changing the file name
5. chunk the pdf in the RAGFlow portal and compare the chunk with the pdf content, you will find the chunk had the old content
```

**Comment by yuzhichang** [comment]
Cannot reproduce with v0.14.1
