### ISSUE TITLE
[Bug]: Embedding Problem: None Object has no attribute 'encode'

### ISSUE THREAD

**Issue by RyanTree-HS** [infiniflow/ragflow#2726]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

ryantest

### Commit ID

bd8fcbb509a19bf3b5313f97394da7a725b132b3

### Other environment information

```Markdown
Windows, but docker desktop is correctly configured
```

### Actual behavior

(https://github.com/infiniflow/ragflow/issues/2723)

details all in this link

### Expected behavior

(https://github.com/infiniflow/ragflow/issues/2723)

details all in this link

### Steps to reproduce

```Markdown
(https://github.com/infiniflow/ragflow/issues/2723)


python3 download_deps.py
docker build -f Dockerfile -t infiniflow/ragflow:dev
 docker compose up -d
```

**Comment by KevinHuSh** [comment]
What's the embedding did you choose?

**Comment by RyanTree-HS** [comment]
> What's the embedding did you choose?

The default one from huggingface.co, but it did not seem to exist
