### ISSUE TITLE
[Bug]: Cannot use Chat API in other apps, such as autogen

### ISSUE THREAD

**Issue by zsp0901** [infiniflow/ragflow#2730]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

commit 0a7654c747082c512e7ac39ec1fc967a943957b3

### Actual behavior

I have already setup everything in ragflow:
![2024-10-07 184704](https://github.com/user-attachments/assets/e3cb6930-d6ac-477f-87a7-e0d9962489fe)

Then I want import the Chat API as a model to use in Autogen studio, error occurs:
![2024-10-07 185236](https://github.com/user-attachments/assets/9a4e66e6-8ae8-4fa1-be4b-835037507977)

It failed no matter I used http://139.xxx.xxx.xxx:5000/v1/api/，http://139.xxx.xxx.xxx:5000/v1/ or http://139.xxx.xxx.xxx:5000/v1/api/completions.

I also try to use FastAPI to make a proxy, it always failed.

Isn't ragflow API the openai-compatible API?

### Steps to reproduce

```Markdown
non
```

**Comment by KevinHuSh** [comment]
No, it's not.
Checkout [this](https://ragflow.io/docs/dev/api).

**Comment by zsp0901** [comment]
> No, it's not. Checkout [this](https://ragflow.io/docs/dev/api).

Could you please tell me more? I know litter about API.

For example, which type listed below should I adopt? If none of them is right, how should I utilize the API from Ragflow in AutoGen? Many thanks!

![image](https://github.com/user-attachments/assets/e8db2a07-6b68-4146-8ea2-3b62e1045f25)

**Comment by KevinHuSh** [comment]
API of RAGFlow has its own protocols. It can be used for generation tasks.
