### ISSUE TITLE
[Feature Request]: Please Build a Retrieval API

### ISSUE THREAD

**Issue by taowang1993** [infiniflow/ragflow#2731]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

I want to integrate Ragflow's knowledge base and Dify. 

Ragflow specializes in building robust RAG, while Dify specializes in building powerful agent.

I want to leverage the strengths of both platforms via API.

But I can't find a retrieval API in Ragflow's docs.

So I want to kindly ask Ragflow's team to build a retrieval API.

This will make the AI agent revolution take a huge step forward!

https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation

**Comment by KevinHuSh** [comment]
Check out [this](https://github.com/infiniflow/ragflow/blob/main/sdk/python/test/t_document.py#L292)

**Comment by kaleocheng** [comment]
ragflow indeed has the retrieval api already https://github.com/infiniflow/ragflow/blob/2a86472b88a7cc7e25fc832bde724ae9fe06acf6/api/apps/api_app.py#L805

but this request is more specific for the Dify external retrieval api implement. https://docs.dify.ai/guides/knowledge-base/external-knowledge-api-documentation, which has a different parameter name:
- `kb_id` vs `knowledge_id`
- `question` vs `query`
- ...

**Comment by nicklhy** [comment]
+1.
Great help if we can integrate ragflow with dify.

**Comment by taowang1993** [comment]
> +1. Great help if we can integrate ragflow with dify.

Already integrated. Check out the latest merge:

https://github.com/infiniflow/ragflow/pull/2848
