### ISSUE TITLE
[Bug]: 文档上传到RAGFlow中，会出现_xOOOD_字符串

### ISSUE THREAD

**Issue by Zhengbiao-Xue** [infiniflow/ragflow#2733]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Actual behavior

上传文档到ragflow后台知识库，会出现_xOOOD_字符，删除回车，还是会这样
![_xOOOD_字符](https://github.com/user-attachments/assets/991c99ce-4813-44c8-94ef-b468868d41b1)
我的邮件是：2573223949@qq.com，方便联系我

### Steps to reproduce

```Markdown
整理好Q&A一问一答文档，点击上传，解析成功，后台知识库中出现_XOOOD_字符
```

### Additional information

我的邮件是：2573223949@qq.com，方便联系我

**Comment by KevinHuSh** [comment]
I'm sure that RAGFlow would not add those words.
