### ISSUE TITLE
[Question]: (root) Additional property include is not allowed

### ISSUE THREAD

**Issue by younggggger** [infiniflow/ragflow#274]
### Describe your problem

$ git clone https://github.com/infiniflow/ragflow.git
$ cd ragflow/
$ docker build -t infiniflow/ragflow:v1.0 .
$ cd ragflow/docker
$ docker compose up -d

当我执行到docker compose up -d时，显示错误(root) Additional property include is not allowed

**Comment by KevinHuSh** [comment]
Upgrade the 'docker-compose' please.

**Comment by seanzhang-zhichen** [comment]
> Upgrade the 'docker-compose' please.

不升级不行吗

**Comment by seanzhang-zhichen** [comment]
> Upgrade the 'docker-compose' please.

压根就不是升级的问题，升级了还是一样报错

**Comment by seanzhang-zhichen** [comment]
> > > Upgrade the 'docker-compose' please.
> > 
> > 压根就不是升级的问题，升级了还是一样报错
> 
> 找到问题了吗？

木有，环境跑不通就没有浪费时间了

**Comment by 0sengseng0** [comment]
> > > > Upgrade the 'docker-compose' please.
> > > 
> > > 
> > > 压根就不是升级的问题，升级了还是一样报错
> > 
> > 
> > 找到问题了吗？
> 
> 木有，环境跑不通就没有浪费时间了

我最开始是打算源码部署的，但提供的requirements.txt 和 requirements_dev.txt 有依赖冲突，试了很久没好。但是docker版的，我升了级，确实可以了

**Comment by seanzhang-zhichen** [comment]
> > > > > Upgrade the 'docker-compose' please.
> > > > 
> > > > 
> > > > 压根就不是升级的问题，升级了还是一样报错
> > > 
> > > 
> > > 找到问题了吗？
> > 
> > 
> > 木有，环境跑不通就没有浪费时间了
> 
> 我最开始是打算源码部署的，但提供的requirements.txt 和 requirements_dev.txt 有依赖冲突，试了很久没好。但是docker版的，我升了级，确实可以了

我升到最新版本也不行，就没试了

**Comment by symya** [comment]
> > Upgrade the 'docker-compose' please.
> 
> 不升级不行吗

I upgraded to 2.27.1 and it was successful

**Comment by tbwtd** [comment]
> > > Upgrade the 'docker-compose' please.
> > 
> > 
> > 不升级不行吗
> 
> I upgraded to 2.27.1 and it was successful

when i upgraded version v2.27.1  the problem is still   (⊙︿⊙)

and i used  this way check  docker-compose.yml
https://stackoverflow.com/questions/29225972/validating-docker-compose-yml-file

**Comment by fire717** [comment]
同样问题，把官方的readme的docker compose -f docker-compose.yml up -d 改成docker-compose -f docker-compose.yml up -d就OK了...

**Comment by divided7** [comment]
> > 同样问题，把官方的readme的docker compose -f docker-compose.yml up -d 改成docker-compose -f docker-compose.yml up -d就OK了...
> 
> 报错：command not found

You should try to use `sudo docker-compose -f docker-compose.yml up -d`

**Comment by shiyuzh2007** [comment]
I upgraded to 2.27.1 and it was successful too.
