### ISSUE TITLE
[Question]: Sharing LLMs/embedding models for the same tenant

### ISSUE THREAD

**Issue by commandblock2** [infiniflow/ragflow#2742]
### Describe your problem

First of all, this is a great project and I would like to thank you for your effort on this project. 😆

I would like to share a knowledge base along with it's embedding model and a default LLM provider(with API keys) among many users. 

By manually creating a new row in the `user_tenant` table, I am now able to share the knowledge base to the user I would like to share. However, when I tried using the search app in ragflow, I got a Model not authorized error, the function for `/my_llms` end point seems to use the current user id instead of joined tenants that is related by the user id like what you did for the knowledge base service.

I am, currently aware of this issue, https://github.com/infiniflow/ragflow/issues/2530 . But I am not sure how you will implement this feature (permission models), and I would like to ask if there are further updates.

**Comment by KevinHuSh** [comment]
tenant_llm stores authorization of tenant to LLM models.
The 'Team' function will be release soon.

**Comment by commandblock2** [comment]
just a bit of docs in case someone tried this in this version around Oct 10 2024, the previous steps does not work yet. When I tried duplicate the entries in the tenant_llm and changed the tenant_id to the id of the user I would like to grant access for, the error message is now in the reply, and it seems to be an error when trying to get some chunk from elastic search there could be 2 different errors depending on if the other user has created a knowledge base using RagFlow.

**Comment by commandblock2** [comment]
should be good to close as teams function is working for me.

**Comment by commandblock2** [comment]
The search process was not actually working properly, the documents can be listed under the section but doesn't seem to be available for the generation procedure.

**Comment by KevinHuSh** [comment]
Did not get it.
Could you elabrate on that?

**Comment by commandblock2** [comment]
this was fixed a while ago and I will close this one
