### ISSUE TITLE
[Bug]: Azure OpenAI model only GPT3.5 on web demo

### ISSUE THREAD

**Issue by robertobalestri** [infiniflow/ragflow#2749]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2e33ed3

### Actual behavior

Get this error because i have only deployed instances of gpt-4o and 4o-mini.

Fail to access model(azure-gpt-35-turbo) using this api key.**ERROR**: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

### Expected behavior

The user should be able to use other models instead of GPT 3.5.

### Steps to reproduce

```Markdown
Just try to insert you api key and deployment name under settings.
```

**Comment by KevinHuSh** [comment]
What's the version of the docker image? It is fixed in latest version.
You need to mannually delete all records in DB of table llm and restart the system.

**Comment by robertobalestri** [comment]
No, i'm talking about the web demo that is not updated
