### ISSUE TITLE
[Bug]: "Token is not valid for this conversation_id!\""

### ISSUE THREAD

**Issue by supersoulsoul** [infiniflow/ragflow#2752]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Actual behavior

After creating a second API key, I successfully obtained a conversation_id using the new_conversation endpoint. However, when requesting /api/conversation/conversation_id, I get the error: 'Token is not valid for this conversation_id!'

### Steps to reproduce

```Markdown
After creating a second API key, I successfully obtained a conversation_id using the new_conversation endpoint. However, when requesting /api/conversation/conversation_id, I get the error: 'Token is not valid for this conversation_id!'
```

**Comment by KevinHuSh** [comment]
It's post request whose url is not like this.

**Comment by supersoulsoul** [comment]
> It's post request whose url is not like this.

![image](https://github.com/user-attachments/assets/c27f67f6-1026-4ae9-8cc9-4c4ba9b81690)
This is get request.

**Comment by supersoulsoul** [comment]
@KevinHuSh 
![image](https://github.com/user-attachments/assets/66ad2c89-4363-431e-aa0e-446583e533d2)

**Comment by supersoulsoul** [comment]
@KevinHuSh 
![image](https://github.com/user-attachments/assets/e934f008-e44e-4a3c-9a83-5967d9fc56b7)

**Comment by KevinHuSh** [comment]
My bad.
The first step is to get conversation id with a specific token, which is bind to that conversation ID.
