### ISSUE TITLE
[Question]: "Table 'rag_flow.document' doesn't exist")

### ISSUE THREAD

**Issue by xiaohong020408** [infiniflow/ragflow#276]
### Describe your problem

 pymysql.err.ProgrammingError: (1146, "Table 'rag_flow.document' doesn't exist")

**Comment by xiaohong020408** [comment]
ragflow-mysql   | 2024-04-09T06:51:47.701985Z 21 [Note] Aborted connection 21 to db: 'rag_flow' user: 'root' host: '172.24.0.5' (Got an error reading communication packets)

**Comment by KevinHuSh** [comment]
#226
