### ISSUE TITLE
[Bug]: InfiniFlow RagFlow Issue with Ollama 0.3.12 in GraphRag Using Qwen2.5 Model

### ISSUE THREAD

**Issue by gzmud** [infiniflow/ragflow#2765]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

dev (image ID: 6ee854751c7e)

### Other environment information

```Markdown
一、问题描述 (Issue Description)

在使用InfiniFlow RagFlow的dev版本（镜像ID: 6ee854751c7e）和Ollama版本0.3.12时，调用Qwen2.5模型进行GraphRag操作时，发现无法正确提取关系。以下是详细描述：

When using the InfiniFlow RagFlow dev version (image ID: 6ee854751c7e) and Ollama version 0.3.12, the relationship extraction fails to work correctly with the Qwen2.5 model during GraphRag operations. Details are as follows:

环境配置 (Environment Setup)
InfiniFlow RagFlow版本：dev (image ID: 6ee854751c7e)
Ollama版本：0.3.12
```

### Actual behavior

实际结果 (Actual Result) 实际操作中，GraphRag未能正确提取关系，输出结果与预期不符。

### Expected behavior

期望结果 (Expected Result) 使用GraphRag功能时，期望能够从输入文本中正确提取出关系。

### Steps to reproduce

```Markdown
拉取InfiniFlow RagFlow的dev版本镜像。
启动容器并安装所有依赖。
加载Ollama的Qwen2.5模型。
执行GraphRag功能，传入相应的输入数据。
观察GraphRag的输出，发现没有提取关系。
```

### Additional information

that‘s all

**Comment by KevinHuSh** [comment]
If you can chat with that LLM deployed by Ollama, then it goes  to the NLP capability of the LLM.
Go to the larger model.

**Comment by gzmud** [comment]
Is there a way to record the complete communication between Ragflow and ollama for debugging purposes?

**Comment by yuzhichang** [comment]
@gzmud Look at `rag/llm/chat_model.py`  `OllamaChat.chat`. You can add some log there.
