### ISSUE TITLE
[Question]: field [q_1024_vec] does not exist in the mapping

### ISSUE THREAD

**Issue by CatInCloud** [infiniflow/ragflow#278]
### Describe your problem

![企业微信截图_17126534631711](https://github.com/infiniflow/ragflow/assets/45314758/d0cc40c5-ad0c-40d5-a3a8-4387dac1a142)
when send a message,got this error

**Comment by juinjonn** [comment]
How do you solve this problem? help thanks

**Comment by jacky68147527** [comment]
+1

**Comment by jacky68147527** [comment]
@CatInCloud please help me, thanks.
My environment: 
Apple M2 Pro
Docker Engine v24.0.6
