### ISSUE TITLE
[Bug]: exec ./entrypoint.sh: no such file or directory bug , due to which rag server restarts.

### ISSUE THREAD

**Issue by pydv9991** [infiniflow/ragflow#279]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

dfeqxewc

### Actual behavior

the rag server starts again and again

### Expected behavior

rag server should be in running state.

### Steps to reproduce

```Markdown
$ git clone https://github.com/infiniflow/ragflow.git
$ cd ragflow/
$ docker build -t infiniflow/ragflow:v1.0 .
$ cd ragflow/docker
$ chmod +x ./entrypoint.sh
$ docker compose up -d
```

**Comment by KevinHuSh** [comment]
Are your machine Arm64 architecture ?

**Comment by pydv9991** [comment]
My system is X64.

**Comment by pydv9991** [comment]
will it not work on x64 ?

**Comment by KevinHuSh** [comment]
What about remove this line in docker_compose.yml
![image](https://github.com/infiniflow/ragflow/assets/12318111/4fbad924-cf81-4bde-a5d9-9d9dfd94413c)

**Comment by pydv9991** [comment]
after removing this.
$docker logs -f ragflow-server
**request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/ragflow-server/json, check if the server supports the requested API version**

**Comment by KevinHuSh** [comment]
Docker version >= 24.0.0 ?

**Comment by domsebalj** [comment]
Same problem, "Docker version 26.0.0, build 2ae903e"

**Comment by Shreyansh-Sheth** [comment]
change line 22 on docker-compose.yml to 
`      - ./ragflow-logs:/ragflow/logs
`

**Comment by domsebalj** [comment]
Still the same error message "exec ./entrypoint.sh: no such file or directory"

**Comment by KevinHuSh** [comment]
> change line 22 on docker-compose.yml to ` - ./entrypoint.sh:/entrypoint.sh`

Does this method work?

BTW.
Docker Compose >= v2.26.1

**Comment by pydv9991** [comment]
trying on linux now.
   raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()

es cluster is not starting

**Comment by domsebalj** [comment]
> > change line 22 on docker-compose.yml to ` - ./entrypoint.sh:/entrypoint.sh`
> 
> Does this method work?
> 
> BTW. Docker Compose >= v2.26.1

That didn't work. Still getting the same error.

Docker compose is 2.26.1

**Comment by KevinHuSh** [comment]
About the ES connection please refer to: https://github.com/infiniflow/ragflow/blob/main/docs/faq.md

**Comment by KevinHuSh** [comment]
Upgrade to the latest dev version of the docker image. Problem solved.

**Comment by williamyszhou** [comment]
ERROR: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: field [q_1536_vec] does not exist in the mapping')
it is shown in version 0.7.Pls help me to resolve it,thks. @KevinHuSh
