### ISSUE TITLE
[Bug]: ./entrypoint.sh: line 15:  3718 Segmentation fault      $PY rag/svr/task_executor.py $1   ./entrypoint.sh: line 28:  3730 Segmentation fault      $PY api/ragflow_server.py 

### ISSUE THREAD

**Issue by focusunsink** [infiniflow/ragflow#2793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

5b4b252895b66627dec65570eb8f0f3c087543e0 

### Other environment information

```Markdown
Hardward:cpu  8700k, GPU RTX4090 
OS types: WINDOW 10
PYTHON3: 3.12.0
Docker Engine v27.2.0
```

### Actual behavior

when I input "docker logs -f ragflow-server" into the terminal opened by administrator. I can't successfully run.
errors and warning occured. 
[WARNING] [2024-10-11 00:53:52,065] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                   [WARNING] [2024-10-11 00:53:52,073] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                   [WARNING] [2024-10-11 00:53:53,315] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                   [WARNING] [2024-10-11 00:53:53,322] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                   ./entrypoint.sh: line 15:  6406 Segmentation fault      $PY rag/svr/task_executor.py $1                                                                                                                                                      ./entrypoint.sh: line 28:  6418 Segmentation fault      $PY api/ragflow_server.py 

### Expected behavior

output: 
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://x.x.x.x:9380

### Steps to reproduce

```Markdown
1. open a windows terminal 
2. git clone this project 
3. cd ragflow/docker
4. docker compose -f docker-compose.yml up -d
5. docker logs -f ragflow-server
```

**Comment by KevinHuSh** [comment]
Weird! What about pulling and using dev version of docker images?

**Comment by focusunsink** [comment]
![image](https://github.com/user-attachments/assets/a7723b78-f36e-4527-b4af-2914369af166)
this is my docker image ,
is there any suggestion for the version of docker image.

**Comment by focusunsink** [comment]
Thansk you KevinHush, 
After Update docker image to dev version insteam of dev-slim.
I got this. 
`
[WARNING] [2024-10-11 16:02:00,124] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                      [WARNING] [2024-10-11 16:02:00,132] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                      [WARNING] [2024-10-11 16:02:00,305] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                      [WARNING] [2024-10-11 16:02:00,313] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.                                                                                                                      [WARNING] Load term.freq FAIL!                                                                                          [WARNING] Load term.freq FAIL!                                                                                                                                                                                                                          ____   ___    ______ ______ __                                                                                         / __ \ /   |  / ____// ____// /____  _      __                                                                         / /_/ // /| | / / __ / /_   / // __ \| | /| / /                                                                        / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /                                                                        /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/                                                                                                                                                                                                                                                                                                                     [INFO] [2024-10-11 16:02:12,694] [_internal._log] [line:96]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.                                                              * Running on all addresses (0.0.0.0)                                                                                    * Running on http://127.0.0.1:9380                                                                                      * Running on http://xxx.xx.x.x:9380                                                                                    [INFO] [2024-10-11 16:02:12,696] [_internal._log] [line:96]: Press CTRL+C to quit    `

**Comment by KevinHuSh** [comment]
It seems normal.
