### ISSUE TITLE
[Question]: How to use ragflow in feishu robot

### ISSUE THREAD

**Issue by ly0303521** [infiniflow/ragflow#2797]
### Describe your problem

I found function that feishu_callback, which is used to register and login with feishu, but how to use it, and no user guide about that.
I want to know whether ragflow can be used in feishu robot or not, and how to use, thank you very much

**Comment by KevinHuSh** [comment]
This is from a contributor.

**Comment by ly0303521** [comment]
@KevinHuSh OK, thanks for reply, I found we can use feishu api and ragflow to do it
