### ISSUE TITLE
[Sugeestion]  Move thresholds and parameters to an external configuration directory

### ISSUE THREAD

**Issue by 1191658517** [infiniflow/ragflow#280]
a good job!
After reading your code in depth, I found that the only flaw is that many parameters and thresholds in the code are not independently provided for external settings, but are hard-coded internally, and many of them have no explanation about the thresholds and parameters. .
Therefore, for the sake of readability, can we move the various algorithm parameters and thresholds that are hard-coded internally to the external config directory, and give corresponding instructions?

**Comment by Svardfox** [comment]
说的好，写的太难受了。

**Comment by KevinHuSh** [comment]
We will refactor that later to make it more readable.
