### ISSUE TITLE
[Bug]: Click the feedback button and 401 will appear

### ISSUE THREAD

**Issue by Wuhall** [infiniflow/ragflow#2812]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

mian

### Commit ID

blank

### Other environment information

```Markdown
Operating System: Ubuntu 22.04.5 LTS              
Kernel: Linux 5.15.0-117-generic
Architecture: x86-64
```

### Actual behavior

Use source code to build docker compile. When I built an agent and started previewing, I clicked the thumbsUp button and a 401 problem occurred, and I was logged out to the home page.
![image](https://github.com/user-attachments/assets/6da6f3f2-e906-46ef-8d23-24c8e3445043)
<img width="963" alt="image" src="https://github.com/user-attachments/assets/965afe92-2e43-4e3f-8bef-450b0e9a0012">

### Steps to reproduce

```Markdown
Use source code to build docker compile. When I built an agent and started previewing, I clicked the thumbsUp button and a 401 problem occurred, and I was logged out to the home page.
```

**Comment by KevinHuSh** [comment]
This function has not been implemented yet.
