### ISSUE TITLE
[Bug]: Chunking pdf appears error

### ISSUE THREAD

**Issue by Rama-19** [infiniflow/ragflow#2813]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

infiniflow/ragflow

### Commit ID

#flaskwrongrag0009

### Actual behavior

using zhipuai's embedding3 or embedding2 to parse document in knowledge which is manual or paper apeears erro with losing location
![新版ragflow文件解析出现的错误](https://github.com/user-attachments/assets/acb50b0f-d280-447d-9628-1a035c846472)

### Steps to reproduce

```Markdown
just upload document and parse it
```

**Comment by KevinHuSh** [comment]
No clue yet.

**Comment by yuzhichang** [comment]
@Rama-19 Please upgrade to v0.14.1 which has better log and fixed many bugs.
In theory RAGFlow shall not try to down zhipuai's embedding3 from huggingface.io.
