### ISSUE TITLE
[Bug]: Can't restart document parsing

### ISSUE THREAD

**Issue by adogwangwang** [infiniflow/ragflow#2814]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.10.0

### Commit ID

 e18f407

### Other environment information

```Markdown
docker
```

### Actual behavior

上传文件点击启动，解析过程中发生点击取消，再重新进行解析无法成功，解析进度没有进展，报错"{} empty task!".format(msg["id"])   显示没有这个task，这里断言没有过的话，导致后续所有文档都无法进行解析
![image](https://github.com/user-attachments/assets/d9940b26-99d8-472c-a9e2-e87e629ec32e)

### Expected behavior

希望大佬能够解答为什么，以及怎么处理，使得文档解析成功

### Steps to reproduce

```Markdown
一个文档失败了，后续新加的文档也无法进行解析，进度条没有进展
```

**Comment by adogwangwang** [comment]
后面无法进行的文档，我看到document表中一直都是 Task dispatched...    ，task表中一直为0，一直没有出现 task received...的msg，

**Comment by JinHai-CN** [comment]
Would you please upgrade RAGFlow to the latest version?

By the way, we intend to create an international community, so we encourage using English for communication.

**Comment by adogwangwang** [comment]
> Would you please upgrade RAGFlow to the latest version?
> 
> By the way, we intend to create an international community, so we encourage using English for communication.

does the latest version  can solve this problem ?  and When can the team version be released?  hope your reply ~~~

**Comment by yuzhichang** [comment]
@adogwangwang v0.14.0+ has much better log and task monitoring and failure handling.

**Comment by chuangzhidan** [comment]
> [@adogwangwang](https://github.com/adogwangwang) v0.14.0+ has much better log, task monitoring and failure handling.

i think its not fixed,i have the same problem
