### ISSUE TITLE
[Question]: api/http_api.md这个文档过期了吗，按这个里面操作无法访问API

### ISSUE THREAD

**Issue by changqingla** [infiniflow/ragflow#2830]
### Describe your problem

我参考这个文档新建一个知识库，我的代码是curl --request POST \
--url http://10.0.169.144:8088/api/v1/dataset \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {ragflow-Y3OTAwN2QyODg2MDExZWY5ZTQ4MDI0Mm}' \
--data '{
  "name": "test",
  "chunk_count": 0,
  "document_count": 0,
  "embedding_model"：BAAI/bge-large-zh-v1.5,
  "parse_method": "naive"
}'
输出显示404：<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by ShenweiXie** [comment]
I've encounter the same problem, how do you solve this problem?

**Comment by JinHai-CN** [comment]
We are refactoring the API. If you are using the latest version, you might encounter the issue.

**Comment by writinwaters** [comment]
Hiya, these API references are still under development. Shall be ready next week. Please stay tuned.

**Comment by Feiue** [comment]
> ### Describe your problem
> 我参考这个文档新建一个知识库，我的代码是curl --request POST --url http://10.0.169.144:8088/api/v1/dataset --header 'Content-Type: application/json' --header 'Authorization: Bearer {ragflow-Y3OTAwN2QyODg2MDExZWY5ZTQ4MDI0Mm}' --data '{ "name": "test", "chunk_count": 0, "document_count": 0, "embedding_model"：BAAI/bge-large-zh-v1.5, "parse_method": "naive" }' 输出显示404：
> 
> <title>405 Not Allowed</title>
> # 405 Not Allowed
> nginx/1.18.0 (Ubuntu)

Please ensure that your code is up to date with the latest version on GitHub. If you're using Docker, you need to sync the code from GitHub to your Docker environment.

**Comment by ShenweiXie** [comment]
ok thanks, I'll stay tuned
