### ISSUE TITLE
[Feature Request]:  When can the team version be released?

### ISSUE THREAD

**Issue by adogwangwang** [infiniflow/ragflow#2834]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

希望能够体验提供团队功能，团队有管理员和普通用户，做用户分层及隔离

**Comment by KevinHuSh** [comment]
Could you elaberate on this feature?

**Comment by adogwangwang** [comment]
> Could you elaberate on this feature?

您好，我看到ragflow点击头像那里会出现一个灰色的 ‘团队’ ，再看了下源码中其实已经预留了团队功能，比如一个团队下的有哪些用户，团队公开资源的话这个团队下的用户都可以看到，用户私有的资源只有该用户自己能看到，总体形成一个团队的概念，不知道这个团队功能什么时候可以开放呢？

**Comment by KevinHuSh** [comment]
What do you mean by '公开资源' and '私有的资源' and '用户分层及隔离'?

**Comment by adogwangwang** [comment]
> What do you mean by '公开资源' and '私有的资源' and '用户分层及隔离'?

对，点击界面右上角，看到左侧一个按钮 “团队” ，点击进去有个 “升级” 是不能点的，这个团队功能什么时候开放？

**Comment by KevinHuSh** [comment]
In next release version.
