### ISSUE TITLE
[Bug]: task_executor occupy cpu too much

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

28d29949c6a58206c3a081e7ad2a4c0c6b56b250

### Actual behavior

Observed the CPU is very busy even when no task to do.
Seems task_executor main loop will run continuously even when no task, which caused it occupy the cpu and never release.
Is it possible to add a sleep here to release CPU when no task?

### Steps to reproduce

```Markdown
start docker and watch the cpu usage.
```

**Comment by KevinHuSh** [comment]
fixed!
