### ISSUE TITLE
[Bug]: Failure of raptor cost too much?

### ISSUE THREAD

**Issue by adogwangwang** [infiniflow/ragflow#2851]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.10.0

### Commit ID

 e18f407

### Actual behavior

我上传了一篇两千多页的文档，好不容易跑完embedding，进入到raptor任务，但是raptor失败了，导致前端显示整体失败，点击刷新之后，是整体重来，而不是仅重新跑raptor，这个代价太大了。。。

### Steps to reproduce

```Markdown
我觉得哪一步失败了就只重新来哪一步，包括之前embedding过程，一个文档假如分成100个task，那么在第79个task失败的话就重新从79开始，而不是整体重新开始，既然raptor是embedding阶段成功后才添加的task，更应该分开成两块，raptor过程失败了就仅仅重做raptor就好了啊~~ 大佬们能不能改良下
```

**Comment by KevinHuSh** [comment]
RAPTOR is a sub-task. If raptor failed, all the parsed chunks are still there. You could click the file, then check out all the chunks.

**Comment by adogwangwang** [comment]
> RAPTOR is a sub-task. If raptor failed, all the parsed chunks are still there. You could click the file, then check out all the chunks.

yes it is ,we can see all the chunks when raptor failed ,but there is no single button to restart raptor, if I want to retry raptor then click refresh button, the document will start embedding from the first task again.   This is unreasonable.

There is another issue: if Raptor fails, the progress bar for this document will remain stuck at 99%. In this state, is it still possible to perform Q&A? Or if Raptor fails, does this document become invalid for knowledge base Q&A?
![image](https://github.com/user-attachments/assets/39cfd2fa-e400-427a-8911-c2813bf73de4)
hope your reply ~

**Comment by KevinHuSh** [comment]
Yes, if the chunk number is not zero, they're available for chat.

**Comment by yuzhichang** [comment]
Tracked by https://github.com/infiniflow/ragflow/issues/3793
