### ISSUE TITLE
[Question]: What does func "single team per user" mean?

### ISSUE THREAD

**Issue by cyhasuka** [infiniflow/ragflow#2852]
### Describe your problem

I found a line in "ROADMAP 2024 #1821" that says: Supports single team per user.
What does func "single team per user" mean?
Does this mean that Team feature will be supported in the new v0.13.0 release? Functions such as those mentioned by #2530 and #2742.

**Comment by KevinHuSh** [comment]
One user can create on team, and KB can be shared between team members.

**Comment by cyhasuka** [comment]
> One user can create on team, and KB can be shared between team members.

Can the creator (or administrator) make changes to user permissions? For example, some members of the Team have R&W permissions to the KB, others only have read-only permissions.

**Comment by KevinHuSh** [comment]
There's no administrator.

**Comment by Said-Apollo** [comment]
@KevinHuSh  Is there a reason as to why no admin will be added? 
From an enterprise perspective, it would be great if there is a super-admin user, which can then create multiple different teams. In each team, it might be useful to assign a member to either "Member", who can just chat or upload files directly to the chat or "Admin", which can also upload files directly to the knowledge base

**Comment by KevinHuSh** [comment]
Just not developed yet.
