### ISSUE TITLE
[Bug]: Whole System Broke after parsing a 100 line table

### ISSUE THREAD

**Issue by yw2598** [infiniflow/ragflow#2860]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

current

### Other environment information

```Markdown
Ubuntu 2204 Docker V0.12
```

### Actual behavior

After parsing the a 100 line table, chat will only respond one message even if I disable the table document or change to a different chat. 
This will only be resolved after a whole deletion of every knowledge base. 

### Steps to reproduce

```Markdown
Parse a table with 100 rows, 

sample row: 
编号 定义 速度 备注 
F0-01 低压端子 3 none
```

**Comment by KevinHuSh** [comment]
Could you specify the error message?

**Comment by yw2598** [comment]
There is no error message, but in the chat dialogue, no matter what I input, regardless of the knowledge base, embedding model, or llm model used, the assistant will only reply with the same message, a message contains a dozens of rows for the table I parsed, and even reference to documents that has been deleted. Also, I add keywords to every chunk of the parsed table, the keywords are product codes, such as RS32, **ragflow seems cannot detect error codes or product codes, which are combinations or letters and numbers, is this a problem with embedding or something else?**

**Comment by KevinHuSh** [comment]
What about using `General` as the parsing method.

**Comment by yw2598** [comment]
it seams like once the excel is parsed, there is no other way to delete it, except deleting all the knowledge bases. I will try General method with a fresh build docker image on my another machine to avoid contaminating my running server.

**Comment by yuzhichang** [comment]
@yw2598 I cannot reproduce this issue with v0.14.1. Can you upload the excel which cause the issue?
