### ISSUE TITLE
[Question]: How's the password encrypted in login api?

### ISSUE THREAD

**Issue by tttmck** [infiniflow/ragflow#2862]
### Describe your problem

Hello, i want to  login with my backend, but the password was encrypted by front, is there any way to encrypt the origin password in my program?
thanks!

**Comment by tttmck** [comment]
I've solved it

**Comment by liuxukang** [comment]
你好，我也想用自己的东西加进去，但是修改他docker中的镜像中的文件后，还是不起作用，也就是修改的内容不会生效，即便是改个标题也不会生效，是因为需要重新编译吗

**Comment by tttmck** [comment]
> 你好，我也想用自己的东西加进去，但是修改他docker中的镜像中的文件后，还是不起作用，也就是修改的内容不会生效，即便是改个标题也不会生效，是因为需要重新编译吗

你如果改的是前端的话，我不太清楚。但是如果改的是后端代码，需要重启容器才会生效。

**Comment by liuxukang** [comment]
就跟你的需求一样呢，去掉加密就用登陆时的密码作为数据库中的密码，该修改哪个文件呢，谢谢
