### ISSUE TITLE
Add contact information to security policy

### ISSUE THREAD

**Issue by p-** [infiniflow/ragflow#2864]
Hey 👋 

I would like to report potential vulnerabilities in RAGFlow. But the current [security policy](https://github.com/infiniflow/ragflow/security/policy) is missing a security contact (e.g. email address). - So it doesn't seem possible to report vulnerabilities in private.

Instead of providing a security contact you can also enable private vulnerability reporting:
https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository
for your repositories.

Thanks

**Comment by KevinHuSh** [comment]
Appreciate!
`Private vulnerability reporting` is enabled.
