### ISSUE TITLE
[Feature Request]: OpenAI API compatibility

### ISSUE THREAD

**Issue by ga-it** [infiniflow/ragflow#287]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Many applications allow integration with OpenAI via API. An example is Nextcloud.

The LocalAI project allows drop-in private AI replacement for these applications by conforming to the OpenAI API specification.

RagFlow offers the promise of leveraging off document management services such as NextCloud and Alfresco. Having OpenAI API connectivity would complete this circle allowing RAG in the source application with the original documents.

**Comment by KevinHuSh** [comment]
Good feature. This is what we want to do next....
