### ISSUE TITLE
[Question]: Agent interface Sider style issue

### ISSUE THREAD

**Issue by yungongzi** [infiniflow/ragflow#2874]
### Describe your problem

Excuse me, the Agent part of the code is consistent, why is the collapse button at the bottom of the Sider?

![image](https://github.com/user-attachments/assets/53a259d9-491d-463c-9b43-1f7a8bfc59dc)

**Comment by cike8899** [comment]
Does the latest version have this problem?

**Comment by yungongzi** [comment]
最新版本没有这个问题。但是我做了二次开发，在我的版本上，是这个问题（可能是样式覆盖了）。
Sider组件强制关闭按钮`trigger={null}`，然后自定义按钮可以。
我就是好奇，为什么最新版本没有使用自定义按钮，它就是这个样式。
主要，我是前端小白，见笑了。

**Comment by cike8899** [comment]
I have never used custom buttons, and the problem you mentioned has not occurred.

**Comment by yungongzi** [comment]
非常感谢你的回复
