### ISSUE TITLE
[Question]: Alternatives to Minio and Redis?

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2887]
### Describe your problem

Does ragflow also offer alternatives to 

1. Mino/s3: Maybe also Google Cloud Storage
2. Redis: Google Memorystore

Or if its already possible, how could one use them. Unfortunately I was not able to find more infos on that

**Comment by KevinHuSh** [comment]
Please refer to [this](https://github.com/infiniflow/ragflow/blob/main/rag/utils/storage_factory.py)
and conf/service_conf.yaml.
