### ISSUE TITLE
[Feature Request]: Support Function Calling? 

### ISSUE THREAD

**Issue by willzzq** [infiniflow/ragflow#2908]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

我们需要在使用知识库的同时，如果没有查到内容（或者指定前缀），就调用外部API获得内容并经过LLM处理后输出。
现在没有看到有此功能。 
通过配置Agent可以做到吗？

**Comment by KevinHuSh** [comment]
It's coming soon.

**Comment by willzzq** [comment]
解决了？可能你理解错了我的意思。我们希望RAG系统能做到像OpenAI那样能配置外部函数（可自己添加函数，自定义名称、参数等），然后在RAG系统中，在用户像Agent提问时，可以根据内容进行判断（路由）是否调用外部函数。比如，用户问今天上海天气如何？ 那么系统判断后调用天气预报函数，并将返回值输出给用户。

https://blog.csdn.net/weixin_41736460/article/details/139619520

**Comment by KevinHuSh** [comment]
I think it could accomplish this goal by  'Invoke'.
![image](https://github.com/user-attachments/assets/0cd3f88a-03d3-4fd9-907c-f5c22ac4a3de)

**Comment by willzzq** [comment]
> I think it could accomplish this goal by 'Invoke'. ![image](https://private-user-images.githubusercontent.com/12318111/381803135-0cd3f88a-03d3-4fd9-907c-f5c22ac4a3de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDM2NTMsIm5iZiI6MTczMDM0MzM1MywicGF0aCI6Ii8xMjMxODExMS8zODE4MDMxMzUtMGNkM2Y4OGEtMDNkMy00ZmQ5LTkwN2MtZjVjMjJhYzRhM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAyNTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2YzZWEyZmEyOWFkZmNjNzc5OTUwNDczNWVlYmIwYWNiMmU1ODE0YWIzMjE3OGIzYjU0NWJlYWFhMWZlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n5co9N49LyNYg_AodRWrxIhSzaro2rIPJvrNW8E_JDw)

好的，建议你参考一下linkAI的配置Function的UI界面。
对了，咱们系统现在已经实现了吗？好像没看到

**Comment by willzzq** [comment]
另外，语义路由（语义拆分）也要解决，比如用户问：帮我查一下我上季度的销售业绩。 如何找到那个正确的函数去调用。

**Comment by KevinHuSh** [comment]
Appreciate your suggestion.
You could scroll down to find the 'Invoke'.
I think this is what you're talking about:
![image](https://github.com/user-attachments/assets/06b2578e-ce5b-4c05-baa3-a3b7ed77404c)

**Comment by Match-Yang** [comment]
> I think it could accomplish this goal by 'Invoke'. ![image](https://private-user-images.githubusercontent.com/12318111/381803135-0cd3f88a-03d3-4fd9-907c-f5c22ac4a3de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDA2MjcsIm5iZiI6MTczMDU0MDMyNywicGF0aCI6Ii8xMjMxODExMS8zODE4MDMxMzUtMGNkM2Y4OGEtMDNkMy00ZmQ5LTkwN2MtZjVjMjJhYzRhM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA5Mzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmE3YmY3NDhjZjZhNzZjMjZiYjAyN2QxZjM3N2ZmMjVmZGUyMTI5NzUyOWI3ZTY2NmQ4NGU4YzFlOGZlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sZbFMHHr_vKqDBO7fgI0DkIbnt4vGyGAvjflQEQWUH4)

When I use POST method, where can I put the form data?

**Comment by KevinHuSh** [comment]
![image](https://github.com/user-attachments/assets/a452d872-dc79-42a0-bcde-d48bed06414e)
It can assign the upstreams' output to request parameters.

**Comment by Match-Yang** [comment]
> ![image](https://private-user-images.githubusercontent.com/12318111/382626758-a452d872-dc79-42a0-bcde-d48bed06414e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTM5MzIsIm5iZiI6MTczMDY5MzYzMiwicGF0aCI6Ii8xMjMxODExMS8zODI2MjY3NTgtYTQ1MmQ4NzItZGM3OS00MmEwLWJjZGUtZDQ4YmVkMDY0MTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhN2ViZjhmODVmYjg1ZTcwYjI5ODMwZDBmMWI3OWQyNjJkYjg5MGY4YzQ2MzBlYzMyYzdiODZjNjNhNDdhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sV6kXUzoApUs1aT0MLP356AdHFKbam-uGmP8jxod2i8) It can assign the upstreams' output to request parameters.

<img width="495" alt="image" src="https://github.com/user-attachments/assets/7ef64ea3-8c06-4d8a-9aed-c142d9e691d8">
Do you mean I can use the key like this?

**Comment by KevinHuSh** [comment]
No. The URL is just base url.
If it's GET request, it will obtain the parameter value and attach them to the url automatically.

**Comment by Match-Yang** [comment]
> No. The URL is just base url. If it's a GET request, it will obtain the parameter value and attach them to the url automatically.

I don't get it. What do you mean by "attach them to the URL automatically"? How do you know the params I want to attach to the end of the URL? Could you please share some examples?

**Comment by KevinHuSh** [comment]
The parameter comes from here:
![image](https://github.com/user-attachments/assets/623803be-32a3-4469-8aef-d9e08a0d283e)

**Comment by DoItRightNow** [comment]
cool!
