### ISSUE TITLE
[Question]:  Get an answer from first knowledge base，Use another question to ask second knowledge will get the same answer.:{ content: { 0: "sequence item 8: expected str instance, dict found" } }

### ISSUE THREAD

**Issue by smileyee** [infiniflow/ragflow#2921]
### Describe your problem

{ content: { 0: "sequence item 8: expected str instance, dict found" } }
![664f89069f7bad4e0f81fca79b5be96](https://github.com/user-attachments/assets/fbed74f0-1ca6-458b-86b2-88581e566c57)
模型的api没有问题，是我的工作流配置有问题吗

**Comment by KevinHuSh** [comment]
Did you deployed yourself, or on demo site?
If it is local deployed, what about pulling the dev version of docker image again? 
We fixed something about the components.

**Comment by smileyee** [comment]
> Did you deployed yourself, or on demo site? If it is local deployed, what about pulling the dev version of docker image again? We fixed something about the components.
![image](https://github.com/user-attachments/assets/9759ff2b-d655-4716-aea5-4895ff53fa09)

I deployed it myself, using version 0.12. Now that the dev version is updated, the following error occurs:ERROR: expected string or bytes-like object. At the same time, is there no preview of the chat module of the following dev version? Can the original api still be used?

**Comment by KevinHuSh** [comment]
Yes, it can.
Hover to the components to check which one exported this error.
And have a look at the docker logs to see if you can find anything.

**Comment by smileyee** [comment]
Relevant text was retrieved in knowledge retrieval, problems appeared in the component that generated answers：{
content: {
0: "sequence item 8: expected str instance, dict found"
}
}

 and docker had no obvious abnormal information

**Comment by huolongguoa** [comment]
您好，这个问题解决了吗，我也是本地部署了v0.12.0，在使用agent的集线器后面加了一个生成回答组件，第一轮回答还能输出，多轮回复就无法正常回复。模型回复sequence item 0: expected str instance, dict found 。
Hello, has this issue been resolved? I deployed v0.12.0 locally. After adding a Generate component following the Concentrator in an agent workflow, the first round of conversation works fine, but subsequent rounds cannot generate responses normally. The model returns the error: "sequence item 0: expected str instance, dict found".

**Comment by KevinHuSh** [comment]
Fixed. Please pull the dev version of docker image.
