### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by pleabargain** [infiniflow/ragflow#2922]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

web UI

### Commit ID

aaa

### Other environment information

```Markdown
https://demo.ragflow.io/chat?dialogId
```

### Actual behavior

![image](https://github.com/user-attachments/assets/7a9a106b-1e49-48f0-94cf-1a8c51169bc6)
chat UI fails

### Expected behavior

Chat should respond to my queries

### Steps to reproduce

```Markdown
go to https://demo.ragflow.io
log in
load a document
select chat
start chatting
```

### Additional information

![image](https://github.com/user-attachments/assets/25aa7862-4a5d-43ba-8181-dded1f925524)

**Comment by JimmyTsai75** [comment]
我今天刚刚测试了，也是遇到完全一样的问题

**Comment by KevinHuSh** [comment]
Fixed.
