### ISSUE TITLE
Python SDK error: get /retrieval should be post

### ISSUE THREAD

**Issue by wbhob** [infiniflow/ragflow#2927]
SDK: https://github.com/infiniflow/ragflow/blob/1a623df8493acdc89e69a7341fc9a1c3ef3b3a57/sdk/python/ragflow/ragflow.py#L179
Implementation: https://github.com/infiniflow/ragflow/blob/1a623df8493acdc89e69a7341fc9a1c3ef3b3a57/api/apps/api_app.py#L800

Notice that the SDK tries to GET the route when it should be POST. Docs also do not provide clarity on what the Retrieve method does or why it is there.

**Comment by KevinHuSh** [comment]
Functions in SDK would call functions in api/apps/sdk.

**Comment by wbhob** [comment]
thanks, found that as well. this is a great project, but its a bit disorganized and hard to understand for new contributors. it's not my place, but I'll recommend exploring domain-driven design principles and hexagonal architecture to make it easier to attract contributions.
