### ISSUE TITLE
[Question]: network anomaly

### ISSUE THREAD

**Issue by joechen2024** [infiniflow/ragflow#293]
### Describe your problem

I deployed it with docker.,It's normal before last night.,Established a knowledge inventory and uploaded a batch of PDF documents for chunk.,Last night I tried to restart the server.,And pull it again.,Now whether it's a new registered user or a login, it prompts "network anomaly".,What is the reason?
In addition, I want to back up the data in it and transfer it to another physical server for deployment, and I need to copy those files or folders. Thanks!

**Comment by xbsoft** [comment]
Same issue, waiting for answer!
I used MacBookPro with Docker Desktop, and pulled repo, start with docker-compose.

**Comment by KevinHuSh** [comment]
Firstly, check the status of all the docker containers.
`$ docker ps`

Secondly, check the network between the server and the client. 
`$ ping IP_of_ragflow_server`

Backup your data:
Data is in the default docker folder like /var/lib/docker/volumns

**Comment by xbsoft** [comment]
The reason may because it didn't start completed.
