### ISSUE TITLE
[Question]: parsing task is not running

### ISSUE THREAD

**Issue by muyuwuxin** [infiniflow/ragflow#294]
### Describe your problem

I run this program locally, and it seems that the parsing task is not running, the parsing progress is always 0%
![微信截图_20240410150413](https://github.com/infiniflow/ragflow/assets/23050353/409a15ed-d69b-4f70-8046-f53f7dd21d3d)

**Comment by KevinHuSh** [comment]
Pull the latest source code and images.
Problem will be solved.

**Comment by KevinHuSh** [comment]
Pull the latest source code and images.
Problem will be solved.

**Comment by muyuwuxin** [comment]
> Pull the latest source code and images. Problem will be solved.
I pulled the latest code, but it still doesn't work

**Comment by muyuwuxin** [comment]
> Pull the latest source code and images. Problem will be solved.

 solved ，thanks
