### ISSUE TITLE
[Question]: Failed to parse a PDF file by 'resume' method

### ISSUE THREAD

**Issue by tiefan** [infiniflow/ragflow#296]
### Describe your problem

When I try to parse a PDF file by 'resume' method, I got the following ERRORS:
File "/home/z0226/Work/ragflow/rag/app/resume.py", line 88, in chunk
    raise Exception("Resume parser remote call fail!")
Exception: Resume parser remote call fail!

I checked out the source code, and find out that: in src/app/resume.py line 54, remote_call try to get access to url: "http://127.0.0.1:61670/tog", which does not exist.

Is this a bug or something?

**Comment by KevinHuSh** [comment]
resume parser is not open sourced yet.
