### ISSUE TITLE
TTS-[Bug]: ERROR: 'CompletionUsage' object has no attribute 'get'

### ISSUE THREAD

**Issue by peizimo** [infiniflow/ragflow#2966]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

tts

### Commit ID

peizimo

### Actual behavior

ERROR: 'CompletionUsage' object has no attribute 'get'

### Expected behavior

text to speech

### Steps to reproduce

```Markdown
In 'chat' moudle , first the chat assistant setting, second choose/open the 'text to speech', third confirm, then chat with assistant, it will reply 'ERROR: 'CompletionUsage' object has no attribute 'get',but I want to hear the audio.
```

**Comment by KevinHuSh** [comment]
There's no error if disable 'text to speech', isn't it?

**Comment by peizimo** [comment]
thanks , This may be due to a version issue that has been resolved after the upgrade
