### ISSUE TITLE
[Feature Request]: About Database interaction

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#2981]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

At present, only query data function, can it achieve the function of writing to the database?

**Comment by JinHai-CN** [comment]
Do you mean the API to read or write document to RAGFlow?

**Comment by ZxnSnowy** [comment]
> Do you mean the API to read or write document to RAGFlow?

I hope to be able to write to the database, for example, to implement the reservation function, to write the answered user information into mysql, so that other software tools can see the reservation information when they query the database.

**Comment by JinHai-CN** [comment]
In general, RAGFlow does not expose the interfaces for reading and writing to the underlying database. Therefore, it is recommended that you directly access the database for reading and writing outside of RAGFlow.
