### ISSUE TITLE
[Question]: How do I check the RAGFlow version?

### ISSUE THREAD

**Issue by SAIL-Fang** [infiniflow/ragflow#2986]
### Describe your problem

I installed ragflow in docker, but I can't find a place to view the version of ragflow, what should I do?

**Comment by KevinHuSh** [comment]
![image](https://github.com/user-attachments/assets/0d767a68-1226-4647-a381-a8867d3d8310)

**Comment by SAIL-Fang** [comment]
> ![image](https://private-user-images.githubusercontent.com/12318111/379513291-0d767a68-1226-4647-a381-a8867d3d8310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzYyNzksIm5iZiI6MTcyOTczNTk3OSwicGF0aCI6Ii8xMjMxODExMS8zNzk1MTMyOTEtMGQ3NjdhNjgtMTIyNi00NjQ3LWEzODEtYTg4NjdkM2Q4MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODA5YjViZjNlNjIwMzM0YmQ0Mzc4NzUyZDJkNzVlMjU1OWE3ZWIwYTkxMjQzZDE0YThmMzM0NzU2MTZlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1573A1AnqcrYVpAxMC1HxtPW82tHJ4JVJ_QVKGRHbW0)

![image](https://github.com/user-attachments/assets/a240fe79-03ca-48d2-a98c-6732334bec10)
Thank you for your reply, but I don't see the relevant version number (v0.11.0 or v0.12.0) on this interface. By the way, could you tell me how to upgrade the old RAGFlow version (installed in docker)?

**Comment by SAIL-Fang** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12318111/379513291-0d767a68-1226-4647-a381-a8867d3d8310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzYyNzksIm5iZiI6MTcyOTczNTk3OSwicGF0aCI6Ii8xMjMxODExMS8zNzk1MTMyOTEtMGQ3NjdhNjgtMTIyNi00NjQ3LWEzODEtYTg4NjdkM2Q4MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODA5YjViZjNlNjIwMzM0YmQ0Mzc4NzUyZDJkNzVlMjU1OWE3ZWIwYTkxMjQzZDE0YThmMzM0NzU2MTZlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1573A1AnqcrYVpAxMC1HxtPW82tHJ4JVJ_QVKGRHbW0)
> 
> ![image](https://private-user-images.githubusercontent.com/135190100/379519441-a240fe79-03ca-48d2-a98c-6732334bec10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzY0ODEsIm5iZiI6MTcyOTczNjE4MSwicGF0aCI6Ii8xMzUxOTAxMDAvMzc5NTE5NDQxLWEyNDBmZTc5LTAzY2EtNDhkMi1hOThjLTY3MzIzMzRiZWMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMjE2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmFhOTQ4OWU2YjMyOTk3YTQ5YzMyNTE2N2MxMjYxMmIyNTIyNTBkNzE3ZGJlNDM0ZDhkOGQ1OWRlMTkwM2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nEtGPl8V_g1UhfOIqZyuU-si_2gTSjEK5V0FuoNemoI) Thank you for your reply, but I don't see the relevant version number (v0.11.0 or v0.12.0) on this interface. By the way, could you tell me how to upgrade the old RAGFlow version (installed in docker)?感谢您的回复，但我在此界面上没有看到相关的版本号（v0.11.0 或 v0.12.0）。顺便说一句，您能告诉我如何升级旧的 RAGFlow 版本（安装在 docker 中）吗？

`docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev` to update!
