### ISSUE TITLE
[Feature Request]: support xorbitsai inference as model provider 

### ISSUE THREAD

**Issue by lordk911** [infiniflow/ragflow#299]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

`My models are deploy on linux server through xinference and export api about chat、embdding 、rerank`

### Describe the feature you'd like

`ragflow could use these remote api`

**Comment by yingfeng** [comment]
We are going to introduce xinference later

**Comment by yingfeng** [comment]
Closing as has already been implemented
