### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'compute_score'

### ISSUE THREAD

**Issue by kdta91** [infiniflow/ragflow#3002]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

524699da7d9b7b7c607b6f76cafb03b57528fdd6

### Other environment information

```Markdown
AWS EC2
Ubuntu 24.04 LTS
4 vCPUs
16GB RAM
```

### Actual behavior

Using the Agent template HR recruitment pitch assistant, I'm getting the response > 'NoneType' object has no attribute 'compute_score'.

The model is gpt-4o.
I have a 9 page PDF document uploaded to the knowledge base and the settings are in the attached image below.

![Screenshot from 2024-10-24 16-34-03](https://github.com/user-attachments/assets/0cd753e0-96d6-47b3-90b8-47f421ee4d8e)

### Expected behavior

Should respond based on the knowledge base.

### Steps to reproduce

```Markdown
1. Setup system models using OpenAI gpt-4o.
2. Create agent from template HR recruitment pitch assistant
3. Chat.
```

**Comment by KevinHuSh** [comment]
It seems you have configured rerank model for retrieval, and what rerank model did you use?

**Comment by kdta91** [comment]
> It seems you have configured rerank model for retrieval, and what rerank model did you use?

Oh silly me. I actually need to click on the x icon to remove the default rerank model. I thought it was disabled cause it'
s in gray.
