### ISSUE TITLE
[Bug]: 404 error when chat

### ISSUE THREAD

**Issue by spectereye** [infiniflow/ragflow#3007]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

*

### Actual behavior

when chat with knowledge database, always return 404 error below - seems it's nginx error, but no idea how to solve, help please.

```html
**ERROR**: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Steps to reproduce

```Markdown
install by docker, run, create a knowledge db, then  chat.
```

**Comment by KevinHuSh** [comment]
404 means the url path of request is not right.

**Comment by spectereye** [comment]
@KevinHuSh  thanks! and could you please give more details about how to solve it? i follow the instruction with docker to install but met this issue... strange

**Comment by yuzhichang** [comment]
@spectereye Please fill detail info:
RAGFlow git repo version:
RAGFlow image version (show on `/user-setting/profile`):
Log pieces related with the issue:

**Comment by yuzhichang** [comment]
Close due to no response.
