### ISSUE TITLE
[Bug]: Web-crawler

### ISSUE THREAD

**Issue by levi19982** [infiniflow/ragflow#3009]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

Commit ID

### Actual behavior

I get this error, when I set up web-crawler in Agents:
{
content: {
0: "An unexpected error occurred: BrowserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1134/chrome-linux/chrome ╔════════════════════════════════════════════════════════════╗ ║ Looks like Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers: ║ ║ ║ ║ playwright install ║ ║ ║ ║ <3 Playwright Team ║ ╚════════════════════════════════════════════════════════════╝"
}
}

### Steps to reproduce

```Markdown
Add web-crawler to an agent, add proxy, ask something and then it produces that error.
```

**Comment by KevinHuSh** [comment]
What about execuating the following command and restart/kill ragflow_server.py in the container?
pip install pytest-playwright
playwright install

**Comment by levi19982** [comment]
Sorry, I forgot to write it. It's on the demo site

**Comment by yumu7777777** [comment]
您好，我是通过docker 安装的，为啥也有这个问题
