### ISSUE TITLE
[Bug]: required argument are missing: conversation_id,messages

### ISSUE THREAD

**Issue by anian1030** [infiniflow/ragflow#3010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

#2892

### Actual behavior

![1](https://github.com/user-attachments/assets/194912da-6611-4a0f-ab86-fe7eda254fc2)
请问是什么问题

### Steps to reproduce

```Markdown
1
```

**Comment by KevinHuSh** [comment]
Please check this out.
![image](https://github.com/user-attachments/assets/e627d17c-cf97-4dff-8ad2-35b71b28720c)

**Comment by anian1030** [comment]
@KevinHuSh Hello, I've created a knowledge base using the Chat Assistant API, but when I send a question via Postman, I receive an error saying a parameter is missing, even though I've clearly provided values. Could you help me identify where the issue might be?

**Comment by KevinHuSh** [comment]
Please paste the whole error message.

**Comment by yuzhichang** [comment]
Close due to no response.
