### ISSUE TITLE
[Bug]: Parsing display error

### ISSUE THREAD

**Issue by peizimo** [infiniflow/ragflow#3013]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

 Parsing display error

### Commit ID

peizimo

### Actual behavior

![image](https://github.com/user-attachments/assets/5df39069-aad9-4553-99ee-6e1dc203d3be)
The file was parsed successfully, but the display failed, and I looked at the parsed content without error

### Steps to reproduce

```Markdown
presentation parsed one file
```

**Comment by KevinHuSh** [comment]
It seems raptor fail.
RAPTOR is after all the chunks. 
Could you attach this file if it's convenient?

**Comment by yuzhichang** [comment]
Close due to no response.
