### ISSUE TITLE
[Question]: [ERROR]Internal server error while chunking: Unable to start Tika server.

### ISSUE THREAD

**Issue by Github-Polaris** [infiniflow/ragflow#3017]
### Describe your problem

Can someone tell me how to solve this problem? Which place I can find the corresponding logs?

**Comment by JayCroghan** [comment]
Same issue.


```
2024-10-26 13:05:20,574 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server-standard/2.6.0/tika-server-standard-2.6.0.jar to /tmp/tika-server.jar.
[INFO] [2024-10-26 13:05:20,574] [tika.getRemoteJar] [line:802]: Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server-standard/2.6.0/tika-server-standard-2.6.0.jar to /tmp/tika-server.jar.

```

From the logs, it isn't able to fetch it, it times out because I'm in China.

**Comment by KevinHuSh** [comment]
Please make sure the network is working at the first time you star it.

**Comment by yuzhichang** [comment]
@KevinHuSh It's better to put this jar into images. I'll have a try.

**Comment by yuzhichang** [comment]
@Github-Polaris The fix is in main. You can build image by yourself, or wait v0.14

**Comment by SiDaiJie** [comment]
If error occurs during file parsing, it may be due to an unsupported file type being passed in
