### ISSUE TITLE
[Question]: ragflow-mysql cannot be start: ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

### ISSUE THREAD

**Issue by jingshenghang** [infiniflow/ragflow#3029]
### Describe your problem

When I did `docker-compose --file docker-compose.yml up -d`，container ragflow-mysql report an Error. I use `docker logs -f ragflow-server` to check the log, find the following error:
```
2024-10-26 19:11:58+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.39-1.el9 started.
2024-10-26 19:11:58+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-10-26 19:11:58+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.39-1.el9 started.
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
```

I try to config the volumes, and add `privileged: true`, all of this doesn't work.
Anyone know how to fix this problem?

**Comment by yuzhichang** [comment]
Looks like an env issue.
What's the OS?
Did you change some code or configuration?
Try run mysql via `sudo docker run` and see what happen.

**Comment by yuzhichang** [comment]
Close due to no response from the author in 2 weeks.
