### ISSUE TITLE
[Bug]: Installation dependency package error, there will be errors when changing to various versions

### ISSUE THREAD

**Issue by tanyo520** [infiniflow/ragflow#303]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

e

### Commit ID

e

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/5094034/4193ff82-0b80-45b3-99a0-1e5fb9afc18b)

### Expected behavior

ERROR: Ignored the following versions that require a different python version: 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.4.0 Requires-Python >=3.5,<3.10
ERROR: Could not find a version that satisfies the requirement nvidia-nccl-cu12==2. (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-nccl-cu12==2.

### Steps to reproduce

```Markdown
pip3 install -r requirements.txt
```

### Additional information

ERROR: Ignored the following versions that require a different python version: 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.4.0 Requires-Python >=3.5,<3.10
ERROR: Could not find a version that satisfies the requirement nvidia-nccl-cu12==2. (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-nccl-cu12==2.

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

The preferable Python version  is 3.11.
Have a try.

Thanks again!

**Comment by tanyo520** [comment]
Is it difficult to set up a local environment on Windows? Should this be developed on Linux

**Comment by tanyo520** [comment]
> Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊
> 
> The preferable Python version is 3.11. Have a try.
> 
> Thanks again!

Is it difficult to set up a local environment on Windows? Should this be developed on Linux

**Comment by lanbowcn** [comment]
> Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊感谢您的关注！我们打算创建一个国际社区，因此我们鼓励使用英语进行问答，以帮助其他有类似疑问的人。 😊
> 
> The preferable Python version is 3.11.最好的 Python 版本是 3.11。 Have a try.  试试。
> 
> Thanks again! 再次感谢！

The same problem, I want to run “ /rag/app/presentation.py” to verify the corresponding OCR capability, but it always show that dependencies cannot be downloaded.

**Comment by xianyuxm** [comment]
I encountered the same problem while running in the Windows 10 environment with Python 3.11. However, when using the WSL environment, I was able to install the dependencies successfully.

**Comment by yuzhichang** [comment]
We've replaced pip with poetry. Poetry is much better on dependency management and download speed.
