### ISSUE TITLE
[Feature Request]: add Moonshot's moonshot-v1-auto model

### ISSUE THREAD

**Issue by littletoxic** [infiniflow/ragflow#3048]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

according to [this document](https://platform.moonshot.cn/docs/guide/choose-an-appropriate-kimi-model), add Moonshot's moonshot-v1-auto model into RAGFlow to optimize costs and and simplify use

**Comment by KevinHuSh** [comment]
Set the API key again then you could get the model.
