### ISSUE TITLE
[Question]: dependency failed to start: container ragflow-es-01 is unhealthy

### ISSUE THREAD

**Issue by fst813** [infiniflow/ragflow#305]
### Describe your problem

dependency failed to start: container ragflow-es-01 is unhealthy

**Comment by giulioz4** [comment]
You need to install the last docker compose version "Docker Compose version v2.26.1" and set vm.max_map_count to 262144 with "sudo sysctl -w vm.max_map_count=262144"

**Comment by KevinHuSh** [comment]
![image](https://github.com/infiniflow/ragflow/assets/12318111/1bf9842d-1aef-41fa-ae98-73e2d3acb852)

**Comment by e1817** [comment]
container ragflow-es-01 is unhealthy

**Comment by xiaobai-marker** [comment]
事实上Docker Compose version v2.26.1和sudo sysctl -w vm.max_map_count=262144不起作用 还是有一样的错误

**Comment by wuyeguo** [comment]
查看es01对应的volume的权限是否对elasticsearch 可写
如果不是，改一下权限

**Comment by Shehjad-Ishan** [comment]
I change vm.max_map_count=262144. Yet showing unhealthy.

**Comment by HarshitMishra76** [comment]
If you are running docker with `colima` 

1. set colima memory to 10Gib because Elastic search needs 8Gib of memory
```
colima start --memory 10
```
2. set the max map count 
```
colima ssh
```
```
sudo sysctl -w vm.max_map_count=262144
```
