### ISSUE TITLE
Replace dataset icon

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#306]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

533ac3b5342059aeea013d7f6ca373ff55761e41

### Actual behavior

The dataset icon is not beautiful enough

### Steps to reproduce

```Markdown
Replace dataset icon
```

**Comment by KevinHuSh** [comment]
fixed
