### ISSUE TITLE
[Bug]: I cannot get the API key from the front end, only the chat ID.

### ISSUE THREAD

**Issue by Weishaoya** [infiniflow/ragflow#3072]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

the latest

### Other environment information

```Markdown
ubuntu 22.04
python 3.12
```

### Actual behavior

![image](https://github.com/user-attachments/assets/cbe898bb-40c3-41b5-9155-8e5c9147b2aa)
![image](https://github.com/user-attachments/assets/072dca63-9210-4a39-9efe-73371b09751e)

### Steps to reproduce

```Markdown
I cloned the latest code using Git, started it from the source code, but I am unable to retrieve the API key from the front end. What should I do to resolve this?
```

**Comment by KevinHuSh** [comment]
This dialog ID is for http API. Please check this out.
![image](https://github.com/user-attachments/assets/f1e5e498-ac93-41ea-943b-f8514700e12e)

**Comment by Weishaoya** [comment]
> This dialog ID is for http API. Please check this out. This is 'chat_id' as below, ![image](https://private-user-images.githubusercontent.com/12318111/380955098-f1e5e498-ac93-41ea-943b-f8514700e12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE1NzUsIm5iZiI6MTczMDMwMTI3NSwicGF0aCI6Ii8xMjMxODExMS8zODA5NTUwOTgtZjFlNWU0OTgtYWM5My00MWVhLTk0M2ItZjg1MTQ3MDBlMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE1MTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhODhiYjcxZmM1YjQ5YmMyNzUzZjgzMzkyYzMyM2Q1MzVhNzQwN2QyNDE4OWRmMzc3NmVjOWQyMzdmOTBhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4ZwIZma9YhWYMx5qGduZyGINQXZaj49lRvL44Gho53g)

Thank you! But I only want to get the API key for different dialogs, not the chat_id. How can I solve the bug?

**Comment by KevinHuSh** [comment]
![image](https://github.com/user-attachments/assets/ca7c4df2-5589-42b3-87e9-70b49b331e75)

**Comment by Weishaoya** [comment]
![image](https://github.com/user-attachments/assets/0f1291ef-e778-435c-8320-61ca6dc34099)
It cannot create a new api. How can I create a new api? Thank you!

**Comment by KevinHuSh** [comment]
Follow this documentation and you could get a chat ID through UI.
![image](https://github.com/user-attachments/assets/6a617c94-2662-47ba-9c72-aaf76d3b5dd0)
![image](https://github.com/user-attachments/assets/1682176f-574a-4962-961d-68e2a8f58f9c)
