### ISSUE TITLE
[Question]: Modified tsx file, how to update the code, currently start the container or the original page.

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3083]
### Describe your problem

I changed showLikeButton to false, but the docker started with the same page components as before. How can I update this component so that it does not appear?

**Comment by KevinHuSh** [comment]
What is 'showLikeButton'?

**Comment by ZxnSnowy** [comment]
![image](https://github.com/user-attachments/assets/65d3b91b-63b4-42a0-8731-0f30911a650d)

**Comment by KevinHuSh** [comment]
You need to change the code in the container and execute 'npm build' to make it effective.

**Comment by ZxnSnowy** [comment]
![image](https://github.com/user-attachments/assets/2534a6fc-44ea-4818-903e-5fd11f0cc415)
I have entered the container. Do I run the npm run build command in the ragflow/web folder? Do you want to install Node.js and npm?

**Comment by KevinHuSh** [comment]
Yes, install Node.js and npm.
