### ISSUE TITLE
[Question]: Secure authentication login support?

### ISSUE THREAD

**Issue by albert-queralto** [infiniflow/ragflow#3093]
### Describe your problem

Right now, the registration form allows anybody who has access to the tool to register. I would like to know if there is a way to use secure authentication methods that limit the registration to certain type of emails (allowing certain @domain.xxx) or third party methods such as google, microsoft or github authentication.

**Comment by KevinHuSh** [comment]
All these kind of features are easy to implement as long as a slight alteration of front end code.
Github authentication is supported. But you need to alter the front end code to show that button.

**Comment by albert-queralto** [comment]
Thank you very much for your reply.
