### ISSUE TITLE
[Question]: Chat assistant not retrieving any chunks

### ISSUE THREAD

**Issue by rplescia** [infiniflow/ragflow#3095]
### Describe your problem

I have added a document to a new KB and chucked it using the 'General' method. When I do retrieval testing on the KB, it retrieves the correct chucks. I have also created a chat assistant on my knowledge base, when I ask the same question as I did during retrieval testing it returns no results. I have tried all different types of configuration on the assistant but it doesn't seem to work. Is there any way I can see what the query the assistant is sending?

**Comment by KevinHuSh** [comment]
I think it's the thing about LLM lack of capability to under stand the relevance between your question and the retrievals.
There's a lamp up on the assistant output. You could click it to see the prompt send to LLM.

**Comment by rplescia** [comment]
I see, thank you very much.
