### ISSUE TITLE
[Feature Request]: API addition knowledge CRUD

### ISSUE THREAD

**Issue by xuchunhua-com** [infiniflow/ragflow#3100]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Manage the contents of the knowledge base through apis

**Comment by KevinHuSh** [comment]
It does have that kind of API.
![image](https://github.com/user-attachments/assets/dd53d0f2-3c18-4ac9-bb16-915383548db7)

**Comment by xuchunhua-com** [comment]
> It does have that kind of API. ![image](https://private-user-images.githubusercontent.com/12318111/381790995-dd53d0f2-3c18-4ac9-bb16-915383548db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzkwMDgsIm5iZiI6MTczMDMzODcwOCwicGF0aCI6Ii8xMjMxODExMS8zODE3OTA5OTUtZGQ1M2QwZjItM2MxOC00YWM5LWJiMTYtOTE1MzgzNTQ4ZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxMzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZjFjZjNlNWM0M2NjYTJhNWRkYzM3MjFmNTJiMmUwNmRmNDVjOTU4MTlmMWM5ZGY1MzU4Yzk1M2I2MjJlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HT4LZWPsuwIgX-di7gLEGSFD4MDYVXPA7DGovI6bTXc)

What version of the environment is it?

**Comment by KevinHuSh** [comment]
Please upgrade [RAGFlow](https://ragflow.io/docs/dev/upgrade_ragflow).
