### ISSUE TITLE
[Question]: A Simple Table but TSR failed

### ISSUE THREAD

**Issue by cailurus** [infiniflow/ragflow#3102]
### Describe your problem

Hi there,

Thanks for this amazing work.

I was testing the basic TSR module in the deepdoc with a table but it didn't recognize the spanning cell. Cuz I thought this example is very basic that should be 100% right, I'm curious that is there anything wrong in my setup?

Here's the pdf file which has a simple table and the result:

[merge 1.pdf](https://github.com/user-attachments/files/17567257/merge.1.pdf)

Cmd I used: `python ragflow/deepdoc/vision/t_recognizer.py --threshold=0.2 --mode=str`

<img width="808" alt="image" src="https://github.com/user-attachments/assets/9ea06d9f-cd6e-4be3-b3e4-7aaf58a5d1ee">

**Comment by KevinHuSh** [comment]
There's no concept of easy or hard for a machine learning model. It mostly depends on the trainnig dataset.
In trainning dataset, it actually has little easy cases like this.
