### ISSUE TITLE
[Feature Request]: The api key button of the agent cannot be clicked, and the api cannot be created

### ISSUE THREAD

**Issue by 1006076811** [infiniflow/ragflow#3105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

last

### Actual behavior

The api key button of the agent cannot be clicked, and the api cannot be created

### Steps to reproduce

```Markdown
The api key button of the agent cannot be clicked, and the api cannot be created
```

**Comment by KevinHuSh** [comment]
It's still on development.
