### ISSUE TITLE
[Question]: all servers are running，sign in error , why , what should i do next?

### ISSUE THREAD

**Issue by CatInCloud** [infiniflow/ragflow#311]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/45314758/9851f8b5-bb2d-41b0-a1f2-93713eccb609)
![image](https://github.com/infiniflow/ragflow/assets/45314758/433abd0b-8dbe-455b-ba65-b8ddaa558a45)

**Comment by KevinHuSh** [comment]
Network between your laptop and the ragflow server is not steady, isn't it?

**Comment by CatInCloud** [comment]
> Network between your laptop and the ragflow server is not steady, isn't it?

I can access the login page everytime means the network is ok . But login always fails .what shoul i do next to find out the issue

**Comment by MRZHUH** [comment]
Read the manual, wait for the server to finish booting

```
docker logs -f ragflow-server
```

**Comment by CatInCloud** [comment]
maybe the network is not steady.because it restore normal with doing nothing
