### ISSUE TITLE
[Question]: Missing Yi-lightning model

### ISSUE THREAD

**Issue by Upcreat** [infiniflow/ragflow#3111]
### Describe your problem

例如使用零一万物的API，但是这里通过模型解析的模型缺少最新的yi-lightning

![局部截取_20241030_180114](https://github.com/user-attachments/assets/4602766a-51dc-4c9e-b9f4-4aa57e67e2b7)

**Comment by KevinHuSh** [comment]
You need to pull the dev version of docker image and add API-key again to make it effective.
