### ISSUE TITLE
[Question]: how can i avoid download files every time i restart docker?

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#3123]
### Describe your problem

i have add root/.cache to a specific directory, the model.bin do not download  every time i restart the docker,but the log still shows i download layout.mamnual.onnx and fetching  10 files.  how to avoid download these files every time i restart docker?
![image](https://github.com/user-attachments/assets/65b42c7f-cee3-4d7e-b7bf-eb0dc06c340c)

**Comment by KevinHuSh** [comment]
These model files will be stored in /ragflow/rag/res/deepdoc/. So, mount out this folder or copy them into image when you build it.

**Comment by yuzhichang** [comment]
@HaoGuo98 Use docker image `infiniflow/ragflow:v0.13.0`. It includes deepdoc models, embedding models and Python libraries, is approximately 9GB in size and may take significantly longer time to load.
