### ISSUE TITLE
[Question]: In the future, will the Agent chat interface have the capability to make API calls? I'm not rushing you, just curious. If so, when do you anticipate this feature being implemented? Additionally, I would like to suggest having a separate chat interface for the Agent. Currently, interacting through flowcharts feels somewhat inconvenient.

### ISSUE THREAD

**Issue by fyxkszz** [infiniflow/ragflow#3128]
### Describe your problem

1. I found that the API button of the new version of the agent is gray, and I saw that the developers replied that it is currently under normal development. I would like to know, can we chat by calling the API after it is completed? Will the previous preview interface be saved (I think this feature is great).
2. Currently, the background of the agent's operating interface is a flowchart I drew, which doesn't look particularly good and gives an impression of being unfinished. Will the agent chat and the current chat tags be merged later?
![image](https://github.com/user-attachments/assets/638bf486-ce1b-4937-8b92-3c8ad2aded8d)

**Comment by KevinHuSh** [comment]
What about this one?
![image](https://github.com/user-attachments/assets/4e5b5a83-cbbd-43f4-a235-045693fb3269)

**Comment by fyxkszz** [comment]
So here it is, great, thank you
