### ISSUE TITLE
[Question]: no space left on device when running docker compose

### ISSUE THREAD

**Issue by rudysev** [infiniflow/ragflow#3129]
### Describe your problem

Built docker image successfully on Mac OS from top of tree (ID: 9a5ff320f3c21229cde0134e398b9a20107be178).

Getting no space left on device when running `docker compose`. It looks like there may not be enough virtual space for the docker container?

```
(venv) rudys@mac-studio ~/.../Software/ragflow/docker % docker compose -f docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string.
[+] Running 102/5
 ✔ minio Pulled                                                                                                                                                           12.2s
 ✔ redis Pulled                                                                                                                                                           23.2s
 ⠹ ragflow [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 11.33GB / 11.35GB Pulling                                                                   231.2s
 ✔ mysql Pulled                                                                                                                                                           31.7s
 ✔ es01 Pulled                                                                                                                                                           100.6s
failed to extract layer sha256:a02c9c8115e19b42e544995307b0233efb20d5ef9e1e0195a181dd1945e5d73e: write /var/lib/desktop-containerd/daemon/io.containerd.snapshotter.v1.overlayfs/snapshots/773/fs/root/.ragflow/bge-reranker-v2-m3/model.safetensors: no space left on device: unknown
```

**Comment by JinHai-CN** [comment]
Check your disk left space of docker images used.

**Comment by rudysev** [comment]
Thank you.

I ran
```
docker system df
```

Then recovered some space by purning with:

```
docker system prune --all --force --volumes
```

**Comment by Amitt1412** [comment]
@rudysev after running the commands above 
```
docker system df
docker system prune --all --force --volumes
```
How did you run it images to complete the app hosting process?

**Comment by BillShiyaoZhang** [comment]
> [@rudysev](https://github.com/rudysev), [@JinHai-CN](https://github.com/JinHai-CN) In my docker I only have the setup for RAGFLow only. After running the commands above docker is supposed to delete everything in memory.
> 
> ```
> docker system df
> docker system prune --all --force --volumes
> ```
> 
> How did you run it images to complete the app hosting process?

@Amitt1412 I guess you may change it here.

<img width="1270" alt="Image" src="https://github.com/user-attachments/assets/530b30f3-7fd5-4419-8fbd-b832f71736ba" />
