### ISSUE TITLE
[Bug]: When running the program from source code, it failed to convert some pdf documents and gave an error

### ISSUE THREAD

**Issue by YannSuper** [infiniflow/ragflow#313]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Actual behavior

After uploading the file, click Convert

### Steps to reproduce

```Markdown
After uploading the file, click Convert
```

### Additional information

![b63803d96cc45745cc9b440c8503cfc](https://github.com/infiniflow/ragflow/assets/53294632/7abcf203-314e-49bc-894e-500207b94eb5)
![144f8a284cc272caf6842d02b7c7821](https://github.com/infiniflow/ragflow/assets/53294632/7e362fed-2aa1-469e-88c8-6d1057e226e3)

**Comment by dfalt0** [comment]
What was on the pdf?

**Comment by KevinHuSh** [comment]
Pull the latest source code and docker images.
