### ISSUE TITLE
[Question]: {"data":null,"retcode":100,"retmsg":"Exception(\"Account abnormal. Please ensure it's on good standing to use QWen's text-embedding-v2\")"}

### ISSUE THREAD

**Issue by fyxkszz** [infiniflow/ragflow#3130]
### Describe your problem

What does this problem mean? What caused it? After I asked several times, it returned to normal
![image](https://github.com/user-attachments/assets/5346f723-ecdd-4e44-b5f6-b8351e83961c)

**Comment by KevinHuSh** [comment]
Set a validate QWen API key in setting.

**Comment by fyxkszz** [comment]
> Set a validate QWen API key in setting.在设置中设置验证 QWen API 密钥。

Actually I have set the correct QWen API key. I asked again without making any changes and it went back to normal. I guess it's because I asked too many times at the same time

**Comment by KevinHuSh** [comment]
Possibly.
