### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by kjjman** [infiniflow/ragflow#314]
### Describe your problem

![1](https://github.com/infiniflow/ragflow/assets/107842066/f472b6e3-c2e3-4724-92a0-9c3a1057b820)

**Comment by dfalt0** [comment]
Hi - I don't think the program supports the Chinese language as input; the program says it expected a "str" type, got a "list" instead - meaning that the input type (in chinese) is not supported

I used Google Translate - sorry for the bad Chinese

-----------------------

你好 - 我认为该程序不支持中文输入； 程序说它需要一个“str”类型，却得到一个“list” - 这意味着不支持输入类型（中文）

我用了谷歌翻译 - 抱歉中文不好

**Comment by dfalt0** [comment]
nope im dumb forget i said anything - LOL 

不，我很笨，忘了我说过什么 - 哈哈

**Comment by dfalt0** [comment]
maybe I'm on the right track? what happened exactly, what did you try to type
------------------
也许我走在正确的轨道上？ 究竟发生了什么，您尝试输入什么
