### ISSUE TITLE
[Question]: Is API not functioning now?

### ISSUE THREAD

**Issue by Dovahlore** [infiniflow/ragflow#3142]
### Describe your problem

im trying APIs on version dev-slim version by sending request using python, but get this
```
"data": null,
    "retcode": 100,
    "retmsg": "<NotFound '404: Not Found'>"
```
heres my code 
```
import requests

base_url = "http://127.0.0.1/v1/api"
key = 'ragflow-Y1Y2VhYzY3OTc3YzExZWY5OThmMDI0Mm'
headers= {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {key}"
}

def create_new_conversation(headers):
    url = f"{base_url}/datasets"
    print(url)
    response = requests.post(url=url, headers=headers)

    return response.json()

print(create_new_conversation(headers))
```

Is APIs not functioning right now

**Comment by Dovahlore** [comment]
> if API can be used on oldversion v0.12.0，can any one provide the api docs？ 

the old doc

**Comment by wbhob** [comment]
I deleted my containers from docker desktop and then ran docker-compose up -d again and it worked for me. Not really sure why

**Comment by wbhob** [comment]
actually, it only seems to work on ragflow dev container. v0.13.0 does not work

**Comment by Dovahlore** [comment]
i m using ranflow-sdk module for Python and it works

**Comment by Dovahlore** [comment]
works for v0.13

**Comment by yuzhichang** [comment]
v0.13.0 contains some worked API. Other API is still on developing.

**Comment by wbhob** [comment]
A fresh install fixed this for me, my database was stale
