### ISSUE TITLE
[Question]: Could you please provide a documentation on how to debug RagFlow using Windows? I am unable to install the dependencies (fasttext and pyicu) using Poetry, and I would appreciate your help.

### ISSUE THREAD

**Issue by Boctopus** [infiniflow/ragflow#3146]
### Describe your problem

~~~

**Comment by jdx2099** [comment]
I met this problem too, unable to install the dependencies (fasttext and pyicu)

**Comment by jdx2099** [comment]
How do you solve this problem

**Comment by Boctopus** [comment]
> How do you solve this problem

The installation of pyicu requires the ICU library. I downloaded the "icU4c-761-win64-msvC202.zip" file and reported other errors. If you have a solution, please let me know, thank you.

**Comment by midilandlu** [comment]
You could download corresponding whl file for fastext and pyicu and install them.
 example : python -m pip install fasttext_wheel-0.9.2-cp310-cp310-win32.whl

then remove fasttext and pyicu in pyproject.toml



[https://pypi.org/project/fasttext-wheel/#files](https://pypi.org/project/fasttext-wheel/#files)
[https://github.com/cgohlke/pyicu-build/releases](https://github.com/cgohlke/pyicu-build/releasesl)
