### ISSUE TITLE
[Question]: How to obtain detailed backend logs？

### ISSUE THREAD

**Issue by SiDaiJie** [infiniflow/ragflow#3148]
### Describe your problem

# I have started ragflow from the source code
- `docker logs -f ragflow-server` cannot meet the logging requirements. I need to obtain logs of front-end operations on the webpage, including logs from conversations and more details on file parsing. I hope to distinguish between the details of the conversation and the file. I use `Olama` as an API service provider
- I used xinference as rerank provider. I saw the effect of rerank in the `test retrieval` of the knowledge base. Does this part also have background logs?
- I hope that in the question, there is a more detailed check method for the situation that the documents cannot be retrieved, such as viewing the slice of the hits
- Is there a more detailed document for viewing logs?

**Comment by yuzhichang** [comment]
There are multiple log files under `docker/ragflow-logs`, each for a dedicated internal package.
We'll merge all into one log file in future, maybe v0.15.

**Comment by KevinHuSh** [comment]
All the logs are in ragflow/logs.

**Comment by SiDaiJie** [comment]
thanks，i find it
