### ISSUE TITLE
[Bug]: Can not parse docs when use http api base on v0.13

### ISSUE THREAD

**Issue by galen1980guo** [infiniflow/ragflow#3149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest

### Actual behavior

![image](https://github.com/user-attachments/assets/b965e877-3baa-429a-8213-a4d418b0e322)
![image](https://github.com/user-attachments/assets/181f5f3a-7fa7-4248-9109-013ac8c831a7)
![image](https://github.com/user-attachments/assets/6e22556d-fc9d-4ded-8f77-53a9233b857e)

### Steps to reproduce

```Markdown
refer to http_api reference had error when use parse docs interface.
```

**Comment by KevinHuSh** [comment]
The URL path is not right: dataset => datasets

**Comment by galen1980guo** [comment]
> The URL path is not right: dataset => datasets

So is there a mistake in the api documentation?

**Comment by Feiue** [comment]
> So is there a mistake in the api documentation?↳
Please update your image to the dev version or use the latest code from GitHub. You can also refer to  (http_api.md)[https://github.com/infiniflow/ragflow/blob/main/docs/references/http_api_reference.md] and (sdk_api.md)[https://github.com/infiniflow/ragflow/blob/main/docs/references/python_api_reference.md]

**Comment by Feiue** [comment]
You can refer to [http_api_reference.md](https://github.com/infiniflow/ragflow/blob/main/docs/references/http_api_reference.md) and [python_api_reference.md](https://github.com/infiniflow/ragflow/blob/main/docs/references/python_api_reference.md). Or please update your image to the dev version or use the latest code from GitHub.
