### ISSUE TITLE
[Feature Request]: URL support: Capable of web crawling and the corresponding content extraction.

### ISSUE THREAD

**Issue by Umpire2018** [infiniflow/ragflow#315]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

This feature should be capable of navigating through specified URLs to collect and parse data, allowing for the extraction of specific content based on user-defined criteria. Ideally, it would support a variety of content types, including text, images, and tables, and allow for easy manipulation and storage of the extracted data.

### Describe implementation you've considered

Reference: [QAnything](https://github.com/netease-youdao/QAnything)

![QAnything Architecture](https://raw.githubusercontent.com/netease-youdao/QAnything/master/docs/images/qanything_arch.png)

1. **Task Management**
   - Deploy a task manager to handle the distribution of crawling jobs.
   - Ensure tasks are evenly distributed across available resources to prevent bottlenecks.
   - Use a robust queue system to prioritize tasks, manage retries, and monitor the crawling process.

2. **Content Extraction with Playwright-Python and OCR**
   - Employ [Playwright for Python](https://github.com/microsoft/playwright-python) to automate and control browser environments for scraping dynamic web pages that rely on JavaScript.
   - Integrate OCR technology to recognize and extract text from images and other irregular content types that cannot be easily selected.

3. **Page Classification**
   - Analyze the structure of the data stored and classify pages accordingly.
   - Use machine learning or heuristic methods to categorize pages for targeted data extraction.

### Additional information

[BCEmbedding](https://github.com/netease-youdao/BCEmbedding): Bilingual and Crosslingual Embedding for RAG

**Comment by raikloe** [comment]
Hey @Umpire2018. Can you please describe why you decided to close this issue as not planned? I find the feature request very interesting and would be happy to see it in Ragflow!
