### ISSUE TITLE
[Bug]: TypeError: ESConnection.search() got an unexpected keyword argument 'idxnm'

### ISSUE THREAD

**Issue by polar99** [infiniflow/ragflow#3151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

33e5e5db

### Other environment information

```Markdown
Hardware parameters: Tesla T4
OS type: Ubuntu 20.04 (Host machine)
```

### Actual behavior

Chunk Method: `Knowledge Graph`
Error: `TypeError: ESConnection.search() got an unexpected keyword argument 'idxnm'`
When chatting with a Knowledge base, it raised this error.

### Expected behavior

No error when chatting

### Steps to reproduce

```Markdown
1. Following official guide to start RAGFlow with docker.
2. Start a chat with a Knowledge base which chunked by Knowledge Graph.
3. run 
docker logs -f ragflow-server
showing the following logs.
```

### Additional information

Traceback (most recent call last):
  File "/ragflow/api/apps/conversation_app.py", line 181, in stream
    for ans in chat(dia, msg, True, **req):
  File "/ragflow/api/db/services/dialog_service.py", line 210, in chat
    kbinfos = retr.retrieval(" ".join(questions), embd_mdl, tenant_ids, dialog.kb_ids, 1, dialog.top_n,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/search.py", line 380, in retrieval
    sres = self.search(req, [index_name(tid) for tid in tenant_ids], embd_mdl, highlight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/graphrag/search.py", line 71, in search
    ent_res = self.es.search(deepcopy(s), idxnm=idxnm, timeout="600s", src=src)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ESConnection.search() got an unexpected keyword argument 'idxnm'

**Comment by SummerDream233** [comment]
Hello. I want to enquiry when the bug can be fixed? Because it is really important.
In the current version, all functions which involve the knowledge graph-based construction method do not work, including the offical demo webset (https://ragflow.io/), api and chat interfance.
If possible, I hope that you can fix the bug as soon as possible. It is very IMPORTANT for me!
Thank you for your time and understanding!

**Comment by KevinHuSh** [comment]
Pull the dev version of docker.
