### ISSUE TITLE
[Question]: HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2552fb8940>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))

### ISSUE THREAD

**Issue by yifeifeng** [infiniflow/ragflow#3155]
### Describe your problem

I met problem of chatting with default setting.
What I have did:

- network should be fine. I check network connection between dashscope.aliyun.com and docker image, and it returns 200. 

- docker exec -it IMAGE /bin/bash AND curl -x proxy -I https://   dashscope.aliyun.com
- I added my proxy on docker-compose.yml
- I tried to add different LLM api keys on webpage, such as MOONSHOOT, the "add" button just keeps circling and it seems doesn't work

is there any suggestion to fix this? 
Thanks

**Comment by KevinHuSh** [comment]
What about ping 'dashscope.aliyuncs.com' inside and outside the container?

**Comment by yifeifeng** [comment]
HI Kevin,  ping 'dashscope.aliyuncs.com' shows no network connection ouside the container(100% packet loss).
but I am wondering if this affect ragflow? because urllib3 sent request via HTTP/HTTPS protocol and curl 'dashscope.aliyun.com' inside and outside BOTH return 404, which means HTTP/HTTPS request is fine

**Comment by KevinHuSh** [comment]
In my envirement, I can ping it both way. I think that is the problem.

**Comment by yifeifeng** [comment]
I think ping connection issue is caused by lack of proxy, cuz this environment does not allow connect to web directly. It is required to use proxy and ping command does not support connect with proxy

**Comment by KevinHuSh** [comment]
Hope [this](https://docs.docker.com/engine/cli/proxy/) can help.

**Comment by yifeifeng** [comment]
I found the issue. Have to uncomment unset http proxy(line 4) in entrypoint.sh in order to use proxy. Thanks for your help
