### ISSUE TITLE
[Bug]: The new version of the api cannot be invoked

### ISSUE THREAD

**Issue by Weishaoya** [infiniflow/ragflow#3166]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.13.0

### Commit ID

37d71dfa9067a8b68a94605dc76f466f97452fc9

### Other environment information

```Markdown
Current Repo: ragflow
Commit Id: 37d71dfa
Operating system: Ubuntu 22.04 (Kernel version: 6.8.0-47-generic)
CPU Type: x86_64
Memory: 
Docker Version: 27.2.0,
Python Version: 3.12.7
```

### Actual behavior

![image](https://github.com/user-attachments/assets/8f556270-1727-48d9-8746-36ea51034b50)
![image](https://github.com/user-attachments/assets/84b7e397-7391-4d2b-80ea-15fb8acdd43c)

### Steps to reproduce

```Markdown
The result returned does not match the expected result. How can I solve it? Thank you!
```

**Comment by KevinHuSh** [comment]
I think the port should be 9380.

**Comment by JinHai-CN** [comment]
Error port number is given in the API page.

**Comment by cike8899** [comment]
Fixed, get the latest code.

**Comment by Weishaoya** [comment]
> I think the port should be 9380.



> Error port number is given in the API page.



> Fixed, get the latest code.

Thank you very much! I I updated to the latest code，it work.
![image](https://github.com/user-attachments/assets/406a3178-c6e2-457b-8fae-78ceb8148334)
