### ISSUE TITLE
[Feature Request]: logout when somebody closes or unloads the web tab

### ISSUE THREAD

**Issue by Rama-19** [infiniflow/ragflow#3172]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

logout when somebody closes or unloads the web tab

**Comment by Rama-19** [comment]
switch loacalStorage in the utils/authorization-util.ts to sessionStorage

**Comment by cike8899** [comment]
The current login status is determined by the backend. The backend returns 401 to log out.
