### ISSUE TITLE
[Bug]: ERROR: 'NoneType' object has no attribute 'encode_queries'

### ISSUE THREAD

**Issue by SummerDream233** [infiniflow/ragflow#3173]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8d9238d

### Actual behavior

When I want to ask question with any chatbot, the problem encounter:

### Steps to reproduce

```Markdown
Pull the latest code from github and pull the latest docker version (dev-slim)
Start enquery
```

### Additional information

Traceback (most recent call last):
  File "/ragflow/api/apps/conversation_app.py", line 181, in stream
    for ans in chat(dia, msg, True, **req):
  File "/ragflow/api/db/services/dialog_service.py", line 210, in chat
    kbinfos = retr.retrieval(" ".join(questions), embd_mdl, tenant_ids, dialog.kb_ids, 1, dialog.top_n,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/search.py", line 380, in retrieval
    sres = self.search(req, [index_name(tid) for tid in tenant_ids], embd_mdl, highlight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/search.py", line 129, in search
    s["knn"] = self._vector(
               ^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/search.py", line 58, in _vector
    qv, c = emb_mdl.encode_queries(txt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/db/services/llm_service.py", line 217, in encode_queries
    emd, used_tokens = self.mdl.encode_queries(query)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/llm/embedding_model.py", line 92, in encode_queries
    return self._model.encode_queries([text]).tolist()[0], token_count
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode_queries'

**Comment by SummerDream233** [comment]
Hello, I want to know the reason and whether it cause influence for everyone.
I note that all chat do not work in the latest version, but the offical demo website (ragflow.io) can conduct enquiry normally.
If you encounter difficulties in reproducing the problem, please feel free to contact me at any time.
I really hope that the related bugs can be fixed as soon as possible. 
I didn't expect to fix a bug just now. Now a new bug has appeared again.

**Comment by SummerDream233** [comment]
At the same time, the front end page will display:
![image](https://github.com/user-attachments/assets/36ad9d19-c5ae-4f25-979f-0b4875e4c8c1)

**Comment by SummerDream233** [comment]
I try to pull new docker image, and the problem still remain.
But there is no bug in the offical website (ragflow.io). I don't know why this happened.

**Comment by KevinHuSh** [comment]
It seems not embedding model found.
What is KB's embedding model?

**Comment by SummerDream233** [comment]
> It seems not embedding model found. What is KB's embedding model?

![image](https://github.com/user-attachments/assets/1dd97ba9-ab75-4fba-9bc0-a88a0efca896)

**Comment by SummerDream233** [comment]
> It seems not embedding model found. What is KB's embedding model?

Hello. I pull the code from github and the lastest docker image (dev-slim), and the problem still remain.

At the same time, the bug report is the same, and it display 'NoneType' object has no attribute 'encode_queries'.

I note that you add the related code to test whether embedding model exist. But I do not know am I operating correctly.

Do I need to connect Docker image to my local code? Or docker image already contains the running code?

**Comment by SummerDream233** [comment]
I come to update this bug.

I find you have updated the docker image. After I change the .env to ragflow:dev, the problem is missing.

But I am not sure if this bug will still exist when .env switching to ragflow:dev-slim. 

Since the code is now ready to run when using ragflow:dev, I may not update this issue again.

Thank you for your cooperation! LOVE YOU!

**Comment by showmaker-hub** [comment]
> I come to update this bug.
> 
> I find you have updated the docker image. After I change the .env to ragflow:dev, the problem is missing.
> 
> But I am not sure if this bug will still exist when .env switching to ragflow:dev-slim.
> 
> Since the code is now ready to run when using ragflow:dev, I may not update this issue again.
> 
> Thank you for your cooperation! LOVE YOU!

How can I reproduce your operation? I also encountered the same problem. Thank you

**Comment by SummerDream233** [comment]
> > I come to update this bug.
> > I find you have updated the docker image. After I change the .env to ragflow:dev, the problem is missing.
> > But I am not sure if this bug will still exist when .env switching to ragflow:dev-slim.
> > Since the code is now ready to run when using ragflow:dev, I may not update this issue again.
> > Thank you for your cooperation! LOVE YOU!
> 
> How can I reproduce your operation? I also encountered the same problem. Thank you

1. change the .env file
2. pull the Docker image again

More detailed information about the specific operation can be found in this project homepage.
