### ISSUE TITLE
[Question]: 0/0 Files after successfully parsing documents

### ISSUE THREAD

**Issue by JiatongXie** [infiniflow/ragflow#3177]
### Describe your problem

I have successfully parsed my documents
<img width="642" alt="image" src="https://github.com/user-attachments/assets/3f45af89-40ef-46cb-81ce-200449513caf">
but whenever I tried to open a chat or do the retrieval testing. No file is found
<img width="238" alt="image" src="https://github.com/user-attachments/assets/2c8a0ecc-4592-4793-afc4-577e8b05e736">
what's wrong with my settings?

**Comment by KevinHuSh** [comment]
It mean your query can't match any chunks.
Click into files, check if there're chunks after parsing.

**Comment by JiatongXie** [comment]
Thanks for the explanation, i have checked about chunks and it seems there are chunks after parsing
<img width="181" alt="image" src="https://github.com/user-attachments/assets/f797faab-06c9-451c-9c55-f2f559345c8f">
and after some more tests i noticed that with proper query it does respond normally.
what made i confused at first is that when i directly asked it what it knows it will reply as if the knowledge base is empty.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/ad38b4de-b0fa-4bff-b449-d591c749308c">
but now i understand that's because the question is too vague to be answered

**Comment by Mapzle** [comment]
0/0 Files

> Thanks for the explanation, i have checked about chunks and it seems there are chunks after parsing <img alt="image" width="181" src="https://private-user-images.githubusercontent.com/169595040/383019167-f797faab-06c9-451c-9c55-f2f559345c8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA3MTIwNTgsIm5iZiI6MTc0MDcxMTc1OCwicGF0aCI6Ii8xNjk1OTUwNDAvMzgzMDE5MTY3LWY3OTdmYWFiLTA2YzktNDUxYy05YzU1LWYyZjU1OTM0NWM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyOFQwMzAyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZhMTFhYmI3ZDQ3ZDNmNDUxNTRkMzM4YWQzMzAxYTM4MmU3MWMxN2M5YjM2ZmI4N2I4MTI1YTYwZDY0ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J5M0f3bc6EJfwvq70HDRIj-RQUBrkeYW7_GlqKtyIvE"> and after some more tests i noticed that with proper query it does respond normally. what made i confused at first is that when i directly asked it what it knows it will reply as if the knowledge base is empty. <img alt="image" width="899" src="https://private-user-images.githubusercontent.com/169595040/383051664-ad38b4de-b0fa-4bff-b449-d591c749308c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA3MTIwNTgsIm5iZiI6MTc0MDcxMTc1OCwicGF0aCI6Ii8xNjk1OTUwNDAvMzgzMDUxNjY0LWFkMzhiNGRlLWIwZmEtNGJmZi1iNDQ5LWQ1OTFjNzQ5MzA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyOFQwMzAyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzBhYjVhN2QzM2ZjM2JiNDAxYWViMGZhM2Q0ZDczODEyNzZhZGNiMGM1NDQyZDZmZmRkYTIwMjAyYjhiMmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gURRWMl0bMYwFfRNT0cRu10jjn0inEkWe4UZ3g5qEIc"> but now i understand that's because the question is too vague to be answered

This just works, but Retrieval testing is still 0/0 Files, do you have a solution for this problem? @JiatongXie
