### ISSUE TITLE
[Bug]: Python API list chunks

### ISSUE THREAD

**Issue by syh-24** [infiniflow/ragflow#3179]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

syhao

### Other environment information

```Markdown
ragflow v0.13.0
```

### Actual behavior

Write the python api according to the official documentation to list the chunks of the current documentation

### Expected behavior

Lists chunks in the current document.

### Steps to reproduce

```Markdown
rag_object = RAGFlow(api_key=api_key, base_url=url)
datasets = rag_object.list_datasets(name="api_test_1")
dataset = datasets[0]
documents = dataset.list_documents()
doc = dataset.list_documents(id="886c38b69a5e11efa3780242ac120006")
doc = doc[0]
chunks = doc.list_chunks()
```

### Additional information

Traceback (most recent call last):
  File "E:\pycharm\study\RAGFlow-api\api_py_1104.py", line 117, in <module>
    chunks = doc.list_chunks()
             ^^^^^^^^^^^^^
  File "D:\an\envs\lgraph\Lib\site-packages\ragflow_sdk\modules\document.py", line 63, in list_chunks
    raise Exception(res.get("message"))
Exception: None

**Comment by Feiue** [comment]
The bug has been fixed and the update is available on GitHub.
