### ISSUE TITLE
[Bug]: Can not parse docs on V0.13

### ISSUE THREAD

**Issue by galen1980guo** [infiniflow/ragflow#3182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest

### Actual behavior

![image](https://github.com/user-attachments/assets/a8db5708-df1c-4b4f-9204-5030eff8858e)

### Steps to reproduce

```Markdown
Can not parse docs on V0.13, always stuck.
```

**Comment by KevinHuSh** [comment]
Check the status of both redis and task executor.

**Comment by galen1980guo** [comment]
> Check the status of both redis and task executor.

I found that it was very slow and not really stuck, but it was really stuck until the knowledge graph was used to parse it.
like below:

**Comment by galen1980guo** [comment]
![截屏2024-11-04 17 28 00](https://github.com/user-attachments/assets/4b94c960-055d-4694-ae7e-5353656f10af)

**Comment by wbhob** [comment]
![CleanShot 2024-11-04 at 09 49 24@2x](https://github.com/user-attachments/assets/ba3526c6-ca7b-488a-a31b-e2ab2a101c35)
Services show as available, but I am facing the same problem, can not figure out why I am unable to ingest

**Comment by KevinHuSh** [comment]
There's yellow bar which means Task executor seems not well conditioned.
Watch the memory usage. It's usually caused by lack of RAM.

**Comment by wbhob** [comment]
For some reason, a clean install and erasing the db actually fixed it. Thanks for the help

**Comment by glowzz** [comment]
how to delete db?

**Comment by KevinHuSh** [comment]
docker compose down -v
All the data will be erased.

**Comment by wbhob** [comment]
in my case I went into docker desktop and deleted the corresponding volumes as well, if that helps
