### ISSUE TITLE
[Question]:There is no chatgpt-on-wechat/plugins inside the container

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3193]
### Describe your problem

I have noticed that the wechat plug-in has been updated. When I started ragflow with docker, I found that this folder was not found inside the container. Is there any update command?

**Comment by JinHai-CN** [comment]
@timebankspace Would you please help check this issue? Thx.

**Comment by timebankspace** [comment]
@ZxnSnowy 

Thank you for your question!

The chatgpt-on-wechat project should be independently deployed in server mode. After setting it up, you can place the plugin folder (ragflow_chat) within the chatgpt-on-wechat/plugins directory. Then, update the necessary configurations in the config.json file accordingly to ensure it integrates properly. Once configured, you should be able to run it smoothly.

Let us know if you have any further questions!
