### ISSUE TITLE
[Bug]: After modifying the port of the configuration file, I can log in normally, but when uploading a file, I get a message that the network is abnormal, configuration file docker-compose-gpu.yml - 8185:80

### ISSUE THREAD

**Issue by alanOO7** [infiniflow/ragflow#3195]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

8305632852a44648b923acd1e5a85627040519a4

### Other environment information

```Markdown
ubuntu20lts
```

### Actual behavior

![1730714414358](https://github.com/user-attachments/assets/12f676b9-1049-4706-ae5f-1ed833421012)

无法上传，提示网络

### Steps to reproduce

```Markdown
修改docker-compose-gpu.yml 
- 8080:80至
- 8185:80

新建知识库上传。出现
```

### Additional information

日志无异常

**Comment by KevinHuSh** [comment]
Possibly, the file is too large which exceed the body length of Nginx setting.
