### ISSUE TITLE
[Bug]: No module named 'flasgger' in docker image version (dev)

### ISSUE THREAD

**Issue by SummerDream233** [infiniflow/ragflow#3200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8d9238d

### Actual behavior

The ragflow can not run

### Steps to reproduce

```Markdown
pull the latest code and dev version docker image
run the docker
```

### Additional information

Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 24, in <module>
    from flasgger import Swagger
ModuleNotFoundError: No module named 'flasgger'

**Comment by SummerDream233** [comment]
Please note: The docker image version is dev instead of dev-slim

**Comment by KevinHuSh** [comment]
The image is updated.

**Comment by SummerDream233** [comment]
> The image is updated.

Excuse me, I find that the docker image infiniflow/ragflow-base:v2.0 is updated, instead of infiniflow/ragflow:dev.

I think you may need update infiniflow/ragflow:dev?

**Comment by SummerDream233** [comment]
THANK YOU!!
I find that you have updated the docker image infiniflow/ragflow:dev.
Now, there is no problem, and I will close this comment.
Thank you for your cooperation and understanding!
