### ISSUE TITLE
[Question]: About the GOT-OCR2_0 model of Xinference

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3215]
### Describe your problem

![image](https://github.com/user-attachments/assets/2952b06a-6c32-4e31-bbbf-de3830808fdf)
Error message:
Fail to access model(GOT-OCR2_0).HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
![image](https://github.com/user-attachments/assets/4df9aa0b-98e3-4930-aa85-eadab248e6e7)
However, there is no problem importing the TTS model, which can be successfully imported. What is the reason for this?

**Comment by ZxnSnowy** [comment]
![image](https://github.com/user-attachments/assets/339c0e5b-3b6e-47e1-b3d6-b1456ff0312a)
In addition, I found an error when importing the OCR model in Xinference, but the model works fine：
![image](https://github.com/user-attachments/assets/b266598b-05cd-4d26-87b4-8dc91b2ac6d4)

**Comment by KevinHuSh** [comment]
Xinference seems upload something to upload.wikimedia.org.
So, it's network issue.

**Comment by ZxnSnowy** [comment]
However, using a Python client of Xinference to try the OCR API is no problem and returns text successfully. If the TTS model where ragflow is deploying Xinference is not in this situation, an error is reported only when OCR is deployed. After I ask the ragflow communication group, I find that someone in the RagFlow communication group is in the same situation.

**Comment by ZxnSnowy** [comment]
upload.wikimedia.org cannot be accessed using a domain name due to the DNS of the server. Can I download Upload.wikimedia.org locally and upload it to ragflow?

**Comment by ZxnSnowy** [comment]
But I ping upload.wikimedia.org is successful, so far only the OCR model is failed and the TTS model is successfully added. The OCR model is downloaded locally, and a Python client using Xinference can also export text. How can I load it into ragflow successfully? Looking forward to your reply！
![image](https://github.com/user-attachments/assets/3f60db47-497d-4760-93e4-e0980451c643)

**Comment by KevinHuSh** [comment]
What about ping it in xinference docker container?

**Comment by ZxnSnowy** [comment]
I deployed xinference locally and ragflow deployed with docker.

**Comment by ben-8878** [comment]
@ZxnSnowy  Same problem, has it been solved?

**Comment by ZxnSnowy** [comment]
> @ZxnSnowy Same problem, has it been solved?

not yet

**Comment by ZxnSnowy** [comment]
@ben-8878 Do you have any idea about this：
![image](https://github.com/user-attachments/assets/f4b71e7c-61e9-4c20-b960-1b12912439bd)

**Comment by ben-8878** [comment]
已经解决了，谢谢。

**Comment by ZxnSnowy** [comment]
@ben-8878 Can you share your solution？

**Comment by ben-8878** [comment]
容器内解析不了你的域名，需要把你的域名和ip对应起来，
extra_hosts:
- 域名：ip

**Comment by ben-8878** [comment]
咱两的情况可能有点区别，我的基础url是一个域名，通过extra_hosts 指定域名对应的ip,就可以了，你的是ip+port，你需要确认你的服务的访问权限是否放开了，像ollama服务默认是127.0.0.1，如果是ollama，http：ip+port方式，容器内无法访问，

**Comment by ZxnSnowy** [comment]
目前内网其他电脑可以实现服务器的IP地址访问，您的意思是在容器内的/etc/hosts 把upload.wikimedia.org域名和对应的 IP 地址写进去吗？比如 192.168.1.1 upload.wikimedia.org

**Comment by ben-8878** [comment]
你可以试试这样，我报upload.wikimedia.org错的时候好像开了VPN，关了VPN报另一个错：Fail to access model **ERROR**: Connection error.

**Comment by DankerMu** [comment]
我是离线环境，添加qwen2vl时也遇到了这个问题

**Comment by DankerMu** [comment]
> > @ZxnSnowy Same problem, has it been solved?
> 
> not yet

解决了吗

**Comment by ZxnSnowy** [comment]
@DankerMu Should be the server side can not access the reason for this URL, has not yet found a solution。
