### ISSUE TITLE
[Bug]: After upgrading to version v0.13, the Agent API button is unavailable.

### ISSUE THREAD

**Issue by pan003** [infiniflow/ragflow#3222]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

cbca7dfc

### Other environment information

```Markdown
root@llmdev:~/llm/ragflow-0.13.0# sh printEnvironment.sh
/usr/bin/docker
printEnvironment.sh: 46: python: not found
Current Repo: ragflow-0.13.0
Commit Id: cbca7dfc
Operating system: Ubuntu 22.04 (Kernel version: 6.8.0-48-generic)
CPU Type: x86_64
Memory:
Docker Version: 24.0.5,
Python Version:
```

### Actual behavior

<img width="642" alt="image" src="https://github.com/user-attachments/assets/1d28c99c-2da4-4e35-b8bf-ee052aa20808">

### Steps to reproduce

```Markdown
agent->open the agent you created
```

**Comment by pan003** [comment]
I have switched the docker image to dev, but the API button shows the agentid. The previous API separate dialog box and iframe embedded page code function is gone.

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/90b6ff33-a537-41fa-ade1-e8693f0e8881">

**Comment by KevinHuSh** [comment]
It is no longer supported.
