### ISSUE TITLE
[Question]: use upload documents API in Python, NO file part!

### ISSUE THREAD

**Issue by SiDaiJie** [infiniflow/ragflow#3225]
## Is there an existing issue for the same bug?
 - [x] I have checked the existing issues.

## Actual behavior

 I use `Postman` to test the official API, which work normally; I use the `Python Requests` code generated by postman, which gets an wrong answer.How to modify it to make it work normally?

```
import requests

url = "http://172.19.10.219:8080/api/v1/datasets/68f55a9c9b5211efb0f70242ac160006/documents"

payload = {}
files=[
  ('file',('QtConcurrent.pdf',open('/path/to/docs/QtConcurrent.pdf','rb'),'application/pdf'))
]
headers = {
  'Content-Type': 'multipart/form-data',
  'Authorization': 'Bearer <api-key>'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)

```

![image](https://github.com/user-attachments/assets/5ceda1b0-4bff-490d-9b24-5abc56632510)

**Comment by amabilee** [comment]
Try removing the `'Content-Type': 'multipart/form-data'` header.

**Comment by SiDaiJie** [comment]
After remove the `'Content-Type': 'multipart/form-data' ` header,it works properly.Need to check whether the header is correct.
