### ISSUE TITLE
[Question]: When parsing a docx file using the Book parsing method, to_page is always -1, resulting in a block count of 0 even if parsing is successful

### ISSUE THREAD

**Issue by kuschzzp** [infiniflow/ragflow#3230]
### Describe your problem

`docx`  with  `Book` ， `to_page` always  `-1`

**I don't know what code can be changed to make to_page correct**

https://github.com/infiniflow/ragflow/blob/af74bf01c0b75ebb15745801802a9b0c914b89c0/deepdoc/parser/docx_parser.py#L113-L136

**When parsing a docx file using the Book parsing method, to_page is always -1, resulting in a block count of 0 even if parsing is successful**

**to fix another error info , i update the below code**
https://github.com/infiniflow/ragflow/blob/af74bf01c0b75ebb15745801802a9b0c914b89c0/deepdoc/parser/docx_parser.py#L133

**to** 

`secs.append(("".join(runs_within_single_paragraph), p.style.name if hasattr(p.style, 'name') else ''))`

**i found here is the default value**
https://github.com/infiniflow/ragflow/blob/af74bf01c0b75ebb15745801802a9b0c914b89c0/api/db/db_models.py#L843

**Comment by KevinHuSh** [comment]
Coud you submit a PR about this issue?
Change the default value of to_page to 100000000.

**Comment by kuschzzp** [comment]
> Coud you submit a PR about this issue? Change the default value of to_page to 100000000.

I have submitted it, please check whether it meets the requirements
