### ISSUE TITLE
[Question]: ragflow request api bug

### ISSUE THREAD

**Issue by lvyoudashuju** [infiniflow/ragflow#3233]
### Describe your problem

When using HTTP API, the error is reported as shown in the figure：
![image](https://github.com/user-attachments/assets/b2302e78-f64b-4d58-a3ed-d981c272d262)

**Comment by Feiue** [comment]
Your authorization is wrong. Should be `Bearer xxxx`

**Comment by lvyoudashuju** [comment]
Thanks.But there is a problem with the documentation
![企业微信截图_17309564121944](https://github.com/user-attachments/assets/50083226-70c0-46fc-a4e7-888657908736)

**Comment by Feiue** [comment]
Sorry. I will update it.

**Comment by Remember12344** [comment]
hi，could you share your python file using HTTP API?

**Comment by Remember12344** [comment]
how you solve the login issue when you using http API? I can't obtain the response data. please help me! thanks.

**Comment by Feiue** [comment]
> how you solve the login issue when you using http API? I can't obtain the response data. please help me! thanks.↳

@Remember12344 HTTP API format should be `requests.post(url=api_url + path, json=json, headers={"Authorizatin": "Bearer ragflow-xxx"})`

**Comment by Feiue** [comment]
> how you solve the login issue when you using http API? I can't obtain the response data. please help me! thanks.↳

@Remember12344 HTTP API format should be `requests.post(url=api_url + path, json=json, headers={"Authorizatin": "Bearer ragflow-xxx"})`
