### ISSUE TITLE
[Bug：unable to install the dependencies (fasttext and pyicu) using Poetry

### ISSUE THREAD

**Issue by jdx2099** [infiniflow/ragflow#3236]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

odff64f

### Other environment information

```Markdown
OS type:Ubuntu 20.04
```

### Actual behavior

When I was trying to launch service from source, I encountered a problem. 
I completely follow the readme file
![image](https://github.com/user-attachments/assets/50cad795-78bc-4bb7-aee7-7c33dd82bcba)
I typed this command "~/.local/bin/poetry install --sync --no-root # install RAGFlow dependent python modules" to install the dependencies but it didn't completely succeed. The following is the error message.

=================================================================================
- Installing fasttext (0.9.3): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  /tmp/tmpz4evzljs/.venv/lib/python3.12/site-packages/setuptools/dist.py:495: SetuptoolsDeprecationWarning: Invalid dash-separated options

Note: This error originates from the build backend, and is likely not a problem with poetry but with fasttext (0.9.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "fasttext (==0.9.3)"'.
=================================================================================

=================================================================================
  - Installing pyicu (2.14): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  <string>:56: DeprecationWarning: Use shutil.which instead of find_executable
  /tmp/tmpgvd94te0/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
    warnings.warn(msg)

=================================================================================

It seems that these two packages pyicu and fasttext  can not be installed properly.

### Steps to reproduce

```Markdown
follow the readme.md
```

**Comment by yuzhichang** [comment]
The gcc on Ubuntu 20.04 is too old to build fasttext和pyicu. Please upgrade to gcc-14, or use Ubuntu 24.04 instead.

**Comment by YiFraternity** [comment]
+1
