### ISSUE TITLE
[Question]: what is the difference between chat and search?

### ISSUE THREAD

**Issue by eleganterRyan** [infiniflow/ragflow#3237]
### Describe your problem

does search block just use embeded model while chat block LLM?

**Comment by KevinHuSh** [comment]
Chat is supposed to directly answer your question.
Search is for users to determine what kind of information they want  which is more precise and trustable. That's why Google is still there and we use it every day.

**Comment by eleganterRyan** [comment]
> Chat is supposed to directly answer your question. Search is for users to determine what kind of information they want which is more precise and trustable. That's why Google is still there and we use it every day.

thx  4 your reply
