### ISSUE TITLE
[Question]: Converse about python api

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3238]
### Describe your problem

I created my_test.py in the sdk/python/ragflow_sdk folder.
![image](https://github.com/user-attachments/assets/837780b4-84a0-4a6a-beca-3bd5e75da060)
![image](https://github.com/user-attachments/assets/9ca1b9e2-4d32-4fc2-b078-d323e109b40c)
Then I modified ragflow.py
![image](https://github.com/user-attachments/assets/5936da5e-e091-4fff-9222-486a8c32755f)
Error now：
![image](https://github.com/user-attachments/assets/414a9bd4-04d0-4991-8622-0802e9d2a5cf)
I deployed ragflow with docker。Can be successfully to http://0.0.0.0/chat/share? shared_id=ragflow-API_KEY&from=chat

**Comment by Feiue** [comment]
404 error means that there might be an issue with your URL.

**Comment by ZxnSnowy** [comment]
But I can open the page using IP:80
![image](https://github.com/user-attachments/assets/4e1a54e0-2ea0-4e3a-8827-1a3e0da2511c)
![image](https://github.com/user-attachments/assets/3b1cabdc-5e9e-4cd0-bef8-911f9276ff25)

**Comment by Feiue** [comment]
You may need to update your docker code. Try `docker pull infiniflow/ragflow:dev`. Then `docker compose -f docker-compose.yml up -d`

**Comment by ZxnSnowy** [comment]
I have successfully updated docker. The HTTP API command can successfully connect, but the Python API still cannot. I notice that the Python API only requires api_key and base_url, while the HTTP API requires api_key, base_url and chat_id. How can I change it? Looking forward to your reply.

**Comment by ZxnSnowy** [comment]
@Feiue 
This is not a 404 error:
![image](https://github.com/user-attachments/assets/cf735611-c85f-463a-a112-63f6c868f0f7)

**Comment by Feiue** [comment]
Please make sure your token is correct.

**Comment by ZxnSnowy** [comment]
@Feiue Where can I get my token? The example where I tried List chat assistants had the same error：
![image](https://github.com/user-attachments/assets/616289b4-ebf0-4865-991b-8372be63b6c1)

**Comment by Feiue** [comment]
![image](https://github.com/user-attachments/assets/36f5e8fd-766d-4540-88d4-e61539a4576a)

**Comment by ZxnSnowy** [comment]
![image](https://github.com/user-attachments/assets/76496dbf-d549-40d0-8b8b-9e641e49ab2b)
I have an API created from a previous docker version, do I need to replace doceker with a developer version to regenerate an API?

**Comment by ZxnSnowy** [comment]
@Feiue 
I tried different versions of docker and found that the button to create the key was unclickable. I created a token in version 0.12, but it still doesn't work。
![image](https://github.com/user-attachments/assets/ab2b07a0-93a6-48d8-b4b4-28147831b654)
![image](https://github.com/user-attachments/assets/a9d8cfd5-e475-4ee5-940f-fadd84bef20c)

**Comment by ZxnSnowy** [comment]
@Feiue  How can we solve this problem：
![image](https://github.com/user-attachments/assets/52427d6d-ed87-4451-b175-f9b160c0b148)

**Comment by Feiue** [comment]
The first issue you mentioned is related to the documentation, and the `get_prologue` function has already been removed. I will modify it accordingly. For the second issue, you can use the latest `session.py` file from the module on GitHub.
