### ISSUE TITLE
[Question]: can not find file det.onnx and can not find file ocr.res

### ISSUE THREAD

**Issue by xmwells** [infiniflow/ragflow#324]
### Describe your problem

1:can't find file  det.onnx
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/deepdoc/vision/ocr.py", line 486, in __init__
ragflow-server  |     self.text_detector = TextDetector(model_dir)
ragflow-server  |                          ^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/ocr.py", line 381, in __init__
ragflow-server  |     self.predictor, self.input_tensor = load_model(model_dir, 'det')
ragflow-server  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/ocr.py", line 65, in load_model
ragflow-server  |     raise ValueError("not find model file path {}".format(
ragflow-server  | ValueError: not find model file path /ragflow/rag/res/deepdoc/det.onnx
2:can't find file ocr.res
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 42, in <module>
ragflow-server  |     from rag.app import laws, paper, presentation, manual, qa, table, book, resume, picture, naive, one
ragflow-server  |   File "/ragflow/rag/app/picture.py", line 23, in <module>
ragflow-server  |     ocr = OCR()
ragflow-server  |           ^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/ocr.py", line 491, in __init__
ragflow-server  |     self.text_recognizer = TextRecognizer(model_dir)
ragflow-server  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/ocr.py", line 95, in __init__
ragflow-server  |     self.postprocess_op = build_post_process(postprocess_params)
ragflow-server  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/postprocess.py", line 20, in build_post_process
ragflow-server  |     module_class = eval(module_name)(**config)
ragflow-server  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/deepdoc/vision/postprocess.py", line 335, in __init__
ragflow-server  |     super(CTCLabelDecode, self).__init__(character_dict_path,
ragflow-server  |   File "/ragflow/deepdoc/vision/postprocess.py", line 258, in __init__
ragflow-server  |     with open(character_dict_path, "rb") as fin:
ragflow-server  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  | FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--InfiniFlow--deepdoc/snapshots/be0c1e50eef6047b412d1800aa89aba4d275f997/ocr.res'

**Comment by KevinHuSh** [comment]
I suggest you that remove the ragflow-server container,  make sure you can ping hf-mirriror.com.

**Comment by hanxl1** [comment]
> I suggest you that remove the ragflow-server container, make sure you can ping hf-mirriror.com.

具体怎么操作呢，每太明白，我在本机可以curl  hf-mirriror.com.
