### ISSUE TITLE
[Question]: which rag framework and vector database used in ragflow?

### ISSUE THREAD

**Issue by liudonghua123** [infiniflow/ragflow#3248]
### Describe your problem

Hi, I just curious which rag framework and vector database used in ragflow, langchain or LlamaIndex, weaviate or milvus or others?

**Comment by amabilee** [comment]
Here's a quick overview of the frameworks and vector databases used in some popular RAG:

| Tool | RAG Framework | Vector Database |
|--------|--------|--------|
| RAGFlow | GraphRAG | Weaviate, Milvus |
| LangChain | LangChain | Astra DB, Redis |
| LlamaIndex | LangChain | Astra DB, Redis |
| Weaviate | Weaviate | Weaviate | 
| Milvus | Milvus | Milvus |

**Comment by JinHai-CN** [comment]
RAGFlow doesn't use other RAG framework like LangChain or LlamaIndex.

As for vector database, RAGFlow uses Elasticsearch for vector and full-text search. #2894 is going to integrate [Infinity](https://github.com/infiniflow/infinity) into RAGFlow

**Comment by doubleheiker** [comment]
> @liudonghua123
> 
> RAGFlow doesn't use other RAG framework like LangChain or LlamaIndex. It is built from scratch.
> 
> As for vector database, RAGFlow uses Elasticsearch for vector and full-text search, now. And #2894 is going to integrate [Infinity](https://github.com/infiniflow/infinity) into RAGFlow. Most likely, the integration will be finished before next RAGFlow release.

Hope to roll out Infinity integration soon！

**Comment by yuzhichang** [comment]
@doubleheiker Infinity integation is done, and release in v0.14.0.
