### ISSUE TITLE
[Bug]: LLMBundle的encode,encode_queries,chat方法执行完TenantLLMService.increase_usage后database_logger的判断逻辑写反了

### ISSUE THREAD

**Issue by geekil** [infiniflow/ragflow#325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

fd7fcb5

### Actual behavior

<img width="687" alt="image" src="https://github.com/infiniflow/ragflow/assets/19562946/3845e9db-6b15-4ed3-99fa-11bb4c4057ad">
正常更新后不应记录错误日志

### Steps to reproduce

```Markdown
chat_mdl.chat
```

**Comment by KevinHuSh** [comment]
fixed
