### ISSUE TITLE
[Feature Request]: Introduce bce text embedding model as an alternative

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/ragflow#326]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

[bce](https://github.com/netease-youdao/BCEmbedding) is an excellent embedding model compared with current bge. So we need to add it as an alternative.

**Comment by Umpire2018** [comment]
```python
from BCEmbedding import EmbeddingModel

# list of sentences
sentences = ['sentence_0', 'sentence_1']

# init embedding model
model = EmbeddingModel(model_name_or_path="maidalun1020/bce-embedding-base_v1")

# extract embeddings
embeddings = model.encode(sentences)
```

**Comment by Umpire2018** [comment]
```python
try:
    flag_model = FlagModel(os.path.join(
            get_project_base_directory(),
            "rag/res/bge-large-zh-v1.5"),
                           query_instruction_for_retrieval="为这个句子生成表示以用于检索相关文章：",
                           use_fp16=torch.cuda.is_available())
except Exception as e:
    flag_model = FlagModel("BAAI/bge-large-zh-v1.5",
                       query_instruction_for_retrieval="为这个句子生成表示以用于检索相关文章：",
                       use_fp16=torch.cuda.is_available())
```

1. 
Maybe we can set `bce` as default hf model? Because it supports Chinese and English.

`bge-large-zh-v1.5` only support chinese.

2. Currently the project use `text-embedding-ada-002` for openai embedding. Maybe it's time to use latest `text-embedding-3-small`? Reference [here](https://openai.com/blog/new-embedding-models-and-api-updates).

**Comment by shenlei1020** [comment]
Please be careful that `maidalun1020/bce-embedding-base_v1` does not need "query instruction", and you'd better use `BCEmbedding` instead.

**Comment by JinHai-CN** [comment]
Fixed.
