### ISSUE TITLE
[Question]Do you have a test file or template for the knowledge_graph parsing method that I can use to verify if it is correct?

### ISSUE THREAD

**Issue by fengyunweia** [infiniflow/ragflow#3270]
### Describe your problem

Do you have a test file or template for the knowledge_graph parsing method that I can use to verify if it is correct?

**Comment by KevinHuSh** [comment]
I'm not sure how to determine a knowledge graph extracted is right or wrong. Do you have some clue about this?

**Comment by fengyunweia** [comment]
Base: Based on the test document in GRAPH_EXTRACTION_PROMPT
1: Verify that the value returned by your graph_extractor: 166 matches the case in GRAPH_EXTRACTION_PROMPT
2: Verify that the value returned by index.py: 89 contains "link or edges"
3: Check your vector database for "knowledge_graph_kwd": "graph" "knowledge_graph_kwd": "mind_map"
Check if the corresponding data is correct.
