### ISSUE TITLE
[Bug]: Variable MACOS is no longer in use in Docker

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/ragflow#3282]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c0919c9

### Actual behavior

`{MACOS} still appears in the docker-compose files.

### Steps to reproduce

```Markdown
For example: https://github.com/infiniflow/ragflow/blob/main/docker/docker-compose.yml
```

**Comment by yuzhichang** [comment]
MACOS is used in `api/db/services/task_service.py`:
```
        if os.environ.get("MACOS"):
```
