### ISSUE TITLE
[Question]: Has the API functionality of the agent module been removed?

### ISSUE THREAD

**Issue by biofer** [infiniflow/ragflow#3290]
### Describe your problem

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/4759f349-f085-4f8c-932b-6ad948d118e0">

**Comment by KevinHuSh** [comment]
Pull the dev version of docker image. It dose support, and refer to [this](https://github.com/infiniflow/ragflow/blob/main/sdk/python/test/t_session.py#L106) about how to use the ID.

**Comment by biofer** [comment]
Will this feature no longer be supported in versions after RAGFLOW_IMAGE=infiniflow/ragflow:v0.13.0?

**Comment by KevinHuSh** [comment]
Yes.
