### ISSUE TITLE
[Question]:The chat model that uses the QWEN2-VL-INST instruct response structure does not include the "relationship_strength" question. What models are you using?

### ISSUE THREAD

**Issue by fengyunweia** [infiniflow/ragflow#3292]
### Describe your problem

[Question]:The chat model that uses the QWEN2-VL-INST instruct response structure does not include the "relationship_strength" question. What models are you using?

**Comment by KevinHuSh** [comment]
The knowledge graph extraction primarily depends on the ability of LLM. I suggest it should no less than 70B parameters.

**Comment by fengyunweia** [comment]
> The knowledge graph extraction primarily depends on the ability of LLM. I suggest it should no less than 70B parameters.

For small files, I used the MiniCPM-3-4B model to convert the format, and the results were very good.
