### ISSUE TITLE
[Bug]: re.sub(r"^[^\{]*", "", response) Here only remove the initial { and }. However, the examples given in COMMUNITY_REPORT_PROMPT are {{ and }}, which will cause an error of CommunityReportsResult:86

### ISSUE THREAD

**Issue by fengyunweia** [infiniflow/ragflow#3299]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

Update license (#2086)

### Actual behavior

    "title": "Taylor and The Device",
    "summary": "The community revolves around Taylor, a person portrayed with authoritarian certainty, and The Device, a technology central to the story. The relationship between Taylor and The Device is significant, as it indicates a change in perspective an

### Steps to reproduce

```Markdown
1:graph 上传源码中的测试数据txt文档，run 报错
```

**Comment by KevinHuSh** [comment]
Could you paste the response or the error message here?

**Comment by fengyunweia** [comment]
> Could you paste the response or the error message here?

response:
{{
    "title": "Experimental Data and Individuals",
    "summary": "The community revolves around the Experimental Data, which is the subject of research and holds potential to transform the industry. There are several individuals involved, including Zhang Wei, Zhao Min, and Li Ming",
     "rating": 4.0,
    "rating_explanation": "The impact severity rating is moderate due to the potential for conflict or collaboration among the individuals involved in the project.",
    "findings": [
        {{
            "summary": "Experimental Data as the central focus",
            "explanation": "Experimental Data is the central entity in this community, serving as the subject of research and holding potential to transform the industry. The significance of the data is evident from the"
            }},
        {{
        "summary": "Roles of Zhang Wei, Zhao Min, and Li Ming",
            "explanation": "Zhang Wei and Zhao Min show respect towards Experimental Data, indicating its significance. Li Ming, on the other hand, experiences frustration and is part of the project. The roles and interactions among these indi"
              }}
    ]
}}  
error:
json.loads(response)
PyDev console: starting.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2024.2.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\haozhuang\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
           
           File "C:\Users\haozhuang\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               File "C:\Users\haozhuang\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by KevinHuSh** [comment]
Got it~
Appreciate it.
