### ISSUE TITLE
[Bug]: Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by Aikun7777777** [infiniflow/ragflow#3303]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

1

### Commit ID

1

### Actual behavior

1

### Steps to reproduce

```Markdown
1
```

**Comment by KevinHuSh** [comment]
Please refer to [this](https://forums.developer.nvidia.com/t/could-not-select-device-driver-with-capabilities-gpu/80200).
