### ISSUE TITLE
[Bug]: AnthropicChat Messages.create() got an unexpected keyword argument 'presence_penalty'

### ISSUE THREAD

**Issue by shijiefengjun** [infiniflow/ragflow#3308]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7e0148c

### Actual behavior

Based on Anthropic model provider.
When I created the knowledge base and entered the chat, I encountered the following error:
![image](https://github.com/user-attachments/assets/bbc35ba9-8904-4f03-96ad-40b236fca243)

I traced the error to the file rag/llm/chat_model.py , located in function ```AnthropicChat.chat_streamly```.
![image](https://github.com/user-attachments/assets/8c9ae7c7-cd02-4d0a-9f85-baa8ea689a3e)

When I encountered the first problem, I tried making changes to make the program run smoothly , It achieved my goal. 
This is the problem I discovered:
1. When use Anthropic model, need remove ```presence_penalty``` and ```frequency_penalty``` from parameter ```gen_conf``` .
It solved the problem:
 ```ERROR: Messages.create() got an unexpected keyword argument 'presence_penalty'``` 
```ERROR: Messages.create() got an unexpected keyword argument 'frequency_penalty'```

2. Change code of mark 2 in image to solve ```ERROR: 'Stream' object has no attribute 'iter_lines' ``` and add ```yield ans```
```
for res in response:
    if res.type == 'content_block_delta':
        text = res.delta.text
        ans += text
        total_tokens += num_tokens_from_string(text)
        yield ans
```
Smooth response: 
![image](https://github.com/user-attachments/assets/bd899571-3b9f-42bd-aae7-941eed5b3045)

I only provide the problems encountered and minor adjustments, hoping it will be helpful

### Steps to reproduce

```Markdown
Based on Anthropic model provider.
When I created the knowledge base and entered the chat, I encountered the error
```

**Comment by KevinHuSh** [comment]
It seems you have  fix this. Could you submit a PR about this?

**Comment by shijiefengjun** [comment]
> It seems you have fix this. Could you submit a PR about this?

Thanks, I am not very active. I will try it if there is a chance in the future
