### ISSUE TITLE
[Question]: How to get correct HTTP response.

### ISSUE THREAD

**Issue by Remember12344** [infiniflow/ragflow#3311]
### Describe your problem

> /api/v1/chats/{chat_id}/sessions

通过这个链接http://localhost/api/v1/chats/chat_id/sessions无法访问这个链接，我想通过request获得响应的结果，但是无法传递access_token请问该怎么解决？
我的代码是这样的“
import requests
import json

# login

session=requests.session()
    
session.headers={
        "User-agent":'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ragflow-JlMmIyYTFlOTc4OTExZWY5YmNiMDI'
    }

login_url='http://localhost/v1/user/login'   
login_payload={
        "email": "17700...1@qq.com",
        "password": "..."
        }
login_response=session.post(login_url,headers=session.headers,json=login_payload)

print("Login Cookies:", session.cookies.get_dict())

if login_response.ok:
    with open('rag.html', 'wb') as f:
        f.write(login_response.content)
    print("登录成功，页面已保存到 rag.html")

    try:
       login_data= login_response.json()
       new_access_token = login_data['data']['access_token']
       session.headers['access_token']=new_access_token
       print(f"Access token: {new_access_token}")

       Conversation_url='http://localhost/chat?dialogId=b6f6576c943911efaa650242ac120006&conversationId=ca5c652be2ff49a9b32be1c5c70a70cb&isNew='
       params={
       'conversation_id': 'ca5c652be2ff49a9b32be1c5c70a70cb'
       }
       response2=session.get(Conversation_url,headers=session.headers,params=params)
       if response2.ok:
          with open('reply.html',"wb") as f:
            f.write(response2.content)
          print("成功回复")
       else:
          print("登陆失败")
    except json.JSONDecoderError:
       print("登录响应不是有效的JSON格式")
    except KeyError:
       print("无法登录响应从中提取access_token")

else:
    print(f"登录失败: {login_response.status_code} - {login_response.text}")

响应的结果是：
 <!DOCTYPE html>
 <html>
 <head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <link rel="shortcut icon" href="/logo.svg">
 <title>RAGFlow</title>
 <link rel="stylesheet" href="/umi.f0c06456.css">
 </head>
 <body>
 <div id="root"></div>
 <script src="/umi.29be9b7e.js"></script>
 </body>
 </html>

代码可以正常运行，但是无法拿到结果，分析可能是因为access_token在变化，无法登录，而且每次运行后，ragflow会退出登录，请问该怎么解决？

**Comment by KevinHuSh** [comment]
Please refer [this](https://ragflow.io/docs/dev/http_api_reference) to apply HTTP API.

**Comment by happyCoding2025** [comment]
> Please refer [this](https://ragflow.io/docs/dev/http_api_reference) to apply HTTP API.

unfortunately, i got this:
{
    "data": null,
    "retcode": 100,
    "retmsg": "<NotFound '404: Not Found'>"
}
when i use all http api from here:https://github.com/infiniflow/ragflow/blob/main/example/http/simple_example.sh

**Comment by KevinHuSh** [comment]
What's the version of the docker image?

**Comment by Remember12344** [comment]
> What's the version of the docker image?

Actually，it is the Dev version. which version is more reliable?

**Comment by happyCoding2025** [comment]
> > Please refer [this](https://ragflow.io/docs/dev/http_api_reference) to apply HTTP API.
> 
> unfortunately, i got this: { "data": null, "retcode": 100, "retmsg": "<NotFound '404: Not Found'>" } when i use all http api from here:https://github.com/infiniflow/ragflow/blob/main/example/http/simple_example.sh

i take following steps and get correct result:
1 update to latest code(https://github.com/infiniflow/ragflow);
2 cd infiniflow/ragflow;
3 docker compose -f docker-compose.yml up -d;

**Comment by Feiue** [comment]
> > > Please refer [this](https://ragflow.io/docs/dev/http_api_reference) to apply HTTP API.↳
> > 
> > 
> > unfortunately, i got this: { "data": null, "retcode": 100, "retmsg": "<NotFound '404: Not Found'>" } when i use all http api from here:https://github.com/infiniflow/ragflow/blob/main/example/http/simple_example.sh↳
> 
> i take following steps and get correct result: 1 update to latest code(https://github.com/infiniflow/ragflow); 2 cd infiniflow/ragflow; 3 docker compose -f docker-compose.yml up -d;↳

![image](https://github.com/user-attachments/assets/64badb97-ebe5-4e2a-940f-dfd73ab2d18c)
