### ISSUE TITLE
[Question]: Can't upload too large files.

### ISSUE THREAD

**Issue by fg2501** [infiniflow/ragflow#3312]
### Describe your problem

 我根据这个文档里面4.13设置了，但是还是显示上传的总文件太大。
![1](https://github.com/user-attachments/assets/99f6e0cc-8fcf-41da-a3e6-83bf13dd568e)
![2](https://github.com/user-attachments/assets/da720489-fef1-4da6-ba58-77ca4684cde6)
我把这个系统变量设置写到了最后一行。
![3](https://github.com/user-attachments/assets/4410d192-cd2f-4694-b13a-812b25a2d893)
这里我也设置了

**Comment by oom2018** [comment]
中间转发的ng配置了吗？例如，如果我们想要在全局范围内增加请求大小限制为100M，我们可以在nginx.conf文件中的http块中添加如下一行：

client_max_body_size  100m;

**Comment by haddad9** [comment]
If you are running nginx apps on top the apps, the default size for the  nginx is around 1Mb to upload a file. You need to configure the size limit manually by adding this line in the docker/nginx.conf:

```
http{
# existing code
client_max_body_size 1000m;
# existing code
}
```

You can change the number to meet your needs, this example is for 1000Mb file. Read more in this [discsussion](https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size)

**Comment by fg2501** [comment]
> 如果你在运行 nginx 应用，上传文件的默认大小约为 1MB。你需要手动配置大小限制，在 docker/nginx.conf 中添加以下行：
> 
> ```
> http{
> # existing code
> client_max_body_size 1000m;
> # existing code
> }
> ```
> 
> 你可以更改数字以满足你的需求，这个例子是针对 1000Mb 文件的。在此[讨论](https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size)中了解更多详情

根据您的指导，我已经解决了问题，谢谢！

**Comment by fg2501** [comment]
> 中间转发的ng配置了吗？例如，如果我们想要在全局范围内增加请求大小限制为100M，我们可以在nginx.conf文件中的http块中添加如下一行：
> 
> client_max_body_size 100m;

谢谢，已经搞定了
