### ISSUE TITLE
[Bug]:Import rerank model from ollama: KeyError('Ollama')

### ISSUE THREAD

**Issue by Liamskey** [infiniflow/ragflow#3313]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ragflow 0.13.0

### Other environment information

```Markdown
Import rerank model from ollama: KeyError('Ollama')
```

### Actual behavior

Import rerank model from ollama: KeyError('Ollama')

### Expected behavior

Import rerank model from ollama: KeyError('Ollama')

### Steps to reproduce

```Markdown
Import rerank model from ollama: KeyError('Ollama')
```

### Additional information

Import rerank model from ollama: KeyError('Ollama')

**Comment by haddad9** [comment]
Could you please provide more detail explanation and an how-to-step to reproduce the bug?

**Comment by Liamskey** [comment]
you see



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 10, 2024 01:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [infiniflow/ragflow] [Bug]:Import rerank model from ollama:KeyError('Ollama') (Issue #3313)




 
Could you please provide more detail explanation and an how-to-step to reproduce the bug?

**Comment by shizzgar** [comment]
There is no rerank models in ollama provider yet. You maybe sould use LocalAI.

**Comment by zhuyuhan1994** [comment]
Same here.
Although there is no rerank model in ollama provider yet, you can run it by .gguf

**Comment by yuzhichang** [comment]
@Liamskey Where does `Import rerank model from ollama: KeyError('Ollama')` come?
I don't see it in log.
RAGFlow rerank_model.py doesn't contain ollama rerank code.

**Comment by yuzhichang** [comment]
Close due to no response.
