### ISSUE TITLE
[Question]: How to deploy rerank model by Ollama?

### ISSUE THREAD

**Issue by fg2501** [infiniflow/ragflow#3318]
### Describe your problem

![8751020f-cd39-470a-9b11-eb686ca14181](https://github.com/user-attachments/assets/c35cdeb5-a4fa-4f2b-8912-cbe274129f3b)
![733d9adb-6d29-4a77-8614-97f2e9f6b5b9](https://github.com/user-attachments/assets/9319e102-f5ac-4f72-b18e-720ac48f0344)

**Comment by KevinHuSh** [comment]
Re-rank model from Ollama has not been implemented yet.

**Comment by fg2501** [comment]
> 重新排序模型尚未从 Ollama 实现。

好吧，那算了。
