### ISSUE TITLE
[Question]: What is the custom tokenizer used for ?

### ISSUE THREAD

**Issue by aguadoenzo** [infiniflow/ragflow#3321]
### Describe your problem

I'm pretty new to AI so this question might stem from a simple misunderstanding, but AFAIK, embedding models can only be used in conjunction with the tokenizer they were trained with (i.e. tiktoken for ChatGPT4o, SentencePiece for LLama, etc).

With that in mind, what is the use of this project [tokenizer](https://github.com/infiniflow/ragflow/blob/main/rag/nlp/rag_tokenizer.py) since the output is going to go through the embedding model tokenizer anyway ? From a few tests, it seems it would actually even remove some details before feeding the content to the embedding model

**Comment by KevinHuSh** [comment]
This tokenizer is for search engine to build reverted index. RAGFlow primarily uses keywords to do retrieval.
