### ISSUE TITLE
[Question]: Multiple questions and answers about the python api failed

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3323]
### Describe your problem

Here's my code:
![image](https://github.com/user-attachments/assets/0020afb4-9a34-47b7-92de-fa4a4345fd7a)
I found no assistant.get_prologue(). create_session() generates an opening that is not a custom opening in the front-end chat configuration, but instead becomes a Hi! I am your assistant, can I help you? Most importantly, you can only do a few Q&A sessions and then report an error:
![image](https://github.com/user-attachments/assets/eb09764d-4fd7-4552-9d0f-b233a27004c1)

**Comment by Feiue** [comment]
What's your code version? Maybe you could just copy the 'modules/session.py' in github

**Comment by JinHai-CN** [comment]
@ZxnSnowy If your issue isn't resolved, please re-open it.
