### ISSUE TITLE
[Bug]: Run the knowledge_graph parsing method, after parsing the document, an error occurs during the retrieval_test in search.py:323.

### ISSUE THREAD

**Issue by fengyunweia** [infiniflow/ragflow#3329]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

#3306

### Actual behavior

Run the knowledge_graph parsing method, after parsing the document, an error occurs during the retrieval_test in search.py:323. The error message is: "sres.field[i][cfield].split(" ")", where cfield is set to "content_ltks", but the knowledge_graph parsing method has the following keywords without the "content_ltks" attribute: "knowledge_graph_kwd": "graph", "knowledge_graph_kwd": "mind_map", and "knowledge_graph_kwd": "text".

### Steps to reproduce

```Markdown
1: Run the knowledge_graph parsing method
2:retrieval_test
```

**Comment by fengyunweia** [comment]
code:
chunks.append(
        {
            "content_with_weight": json.dumps(nx.node_link_data(graph), ensure_ascii=False, indent=2),
            "knowledge_graph_kwd": "graph"
        })   
You can see that the "knowledge_graph_kwd" attribute is set to "graph". There are only two attributes in total.

**Comment by fengyunweia** [comment]
code:
chunks.append(
        {
            "content_with_weight": json.dumps(nx.node_link_data(graph), ensure_ascii=False, indent=2),
            "knowledge_graph_kwd": "graph"
        })   
You can see that the "knowledge_graph_kwd" attribute is set to "graph". There are only two attributes in total.

**Comment by Andiezz** [comment]
How did you solve this problem? I have encountered the same situation.
