### ISSUE TITLE
[Bug]: the term similarity and vctor similarity giving wrong values 

### ISSUE THREAD

**Issue by tanzeel291994** [infiniflow/ragflow#3330]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest

### Actual behavior

in the retrieval test why exactly few documents that aren't similar show 100 % term and vector similarity 

![image](https://github.com/user-attachments/assets/08a95ed2-6bf0-4fb4-9dc5-fcf9c249bb38)

### Steps to reproduce

```Markdown
only 'name' is used for vector embeddings not and code_ID is used as metadata
```

**Comment by KevinHuSh** [comment]
How to reproduce that?

**Comment by yuzhichang** [comment]
Close due to no response.
