### ISSUE TITLE
When I run the command "docker compose -f docker-compose-CN.yml up -d" in the could sever, the exception occurs, and the exception information is as follows: service "ragflow" refers to undefined network ragflow: invalid compose project

### ISSUE THREAD

**Issue by nevesaynever1** [infiniflow/ragflow#334]
### Describe your problem

mat@matcloud:/mnt/ragflow/docker$ docker compose -f docker-compose-CN.yml up -d
service "ragflow" refers to undefined network ragflow: invalid compose project

**Comment by KevinHuSh** [comment]
Please check that:
![image](https://github.com/infiniflow/ragflow/assets/12318111/4d141920-ed8c-400c-a7cc-33a6e7a0ce22)
