### ISSUE TITLE
[Question]: How can we make the model accurately predict the content of the next token block?

### ISSUE THREAD

**Issue by fg2501** [infiniflow/ragflow#3344]
### Describe your problem

![1](https://github.com/user-attachments/assets/2cf6bcc2-08da-4d3b-907b-8141fa1ffad7)
![image](https://github.com/user-attachments/assets/c1e39035-5a25-4a69-a6f7-f2827155a2c1)
My knowledge base divides token blocks by carriage returns, so using this method splits these two parts into different token blocks. When I ask a large language model if it knows what comes next in the sentence, it starts fabricating information. Is there any way to enable the model to correctly answer this question?

**Comment by KevinHuSh** [comment]
Is the raw data `txt` files?
If it is, use a special token as the delimiter and turn down the token number.
If it's a PDF file, turn the task size to 1 and token number to a very large number.
![image](https://github.com/user-attachments/assets/47f5042a-e446-44f7-9614-62f6d32f6059)

**Comment by fg2501** [comment]
> 原始数据是`txt`文件吗？如果需要这样做，使用一个特殊的标记作为分隔符，并减少标记的数量。如果是一个 PDF 文件，将任务大小设置为 1，令牌数量设置为一个非常大的数字。 ![image](https://private-user-images.githubusercontent.com/12318111/385113335-47f5042a-e446-44f7-9614-62f6d32f6059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODA1MzgsIm5iZiI6MTczMTM4MDIzOCwicGF0aCI6Ii8xMjMxODExMS8zODUxMTMzMzUtNDdmNTA0MmEtZTQ0Ni00NGY3LTk2MTQtNjJmNmQzMmY2MDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAyNTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOWY5ZTE4NTQ3MGYzZjdkYTRkNjY5ZDg5NzExMzc2MDJkZTY2YWU3ZDI5OGRkNjAwZTY3N2RlNzYxZDYxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vfk-5Fx5vv5QkWZhTfwtsIPBLrbDyssFT1B6XdhyUDc)

Boss, I have another question. What's going on when the response is off-topic or only partially answers the question? I've already set the token count to its maximum value, and the dialogue model is loaded by Ollama while the embedding model is loaded by Xinference.
![image](https://github.com/user-attachments/assets/97f03703-1ebc-4e58-80fb-1d8a8af82b73)

**Comment by KevinHuSh** [comment]
It's the ability limitation or robustness of the LLM that you chose.
