### ISSUE TITLE
[Question]: Port number about wechat plugin

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3369]
### Describe your problem

Do you need to start ragflow first, open port 80, and then go to the wechat public account page to enable the server configuration, because the URL must be port 80, and then start COW to obtain the two-dimensional code after the successful start?
![image](https://github.com/user-attachments/assets/4eee8d71-8beb-40b3-bc55-aa857c96026f)

**Comment by KevinHuSh** [comment]
Yes, start RAGFlow server firstly.
