### ISSUE TITLE
[Question]: How can I configure RAGFlow as an External Knowledge Base in the dify Knowledge Base

### ISSUE THREAD

**Issue by vicoxia** [infiniflow/ragflow#3377]
### Describe your problem

    How can I configure RAGFlow as an External Knowledge Base in the dify Knowledge Base? This includes how to fill out 'Add an External Knowledge API' and 'Connect to an External Knowledge Base'. Thanks a lot for your help.

I have fill the dify "Edit the External Knowledge API" form with API endpoint "http://xx.xx.xx.xx/api/v1/dify/" and ragflow generated bearer API key.

and in the dify "Connect to an External Knowledge Base" page, I put the dataset id (queried with curl /datasets API) in the "External Knowledge ID" field, is it right?

I can sucessfully exec curl command like this:
curl --request POST \
  --url http://xx.xx.xx.xx/api/v1/dify/retrieval \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer ragflow-xxxxx' \
  --data '{"knowledge_id":"b34xxxxxxxxxxxxx0005","query":"xxxxxxxxx"}'

but dify external knowledge base is no testable.

**Comment by vicoxia** [comment]
api key only need input ragflow-xxxxx, without 'Bearer ". now it's OK.

**Comment by Mason1992-Git** [comment]
maybe in the new version,url changed?i cant find api/v1/dify/retrieval
