### ISSUE TITLE
[Bug]: Can not contact with database(MySQL, PostgreSQL and MariaSQL, what all of if giving)

### ISSUE THREAD

**Issue by 12dc32d** [infiniflow/ragflow#3381]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)

### Commit ID

none

### Other environment information

```Markdown
Windows wsl CentOS7
```

### Actual behavior

I can connect to MySQL, PostgreSQL, and MariaSQL normally in the terminal and other database operation software (I have tried all of them).
However, I cannot connect to the local database using the database name, user name, host, and password in the ragflow Agent.

I turned off the firewall and confirmed that all three databases are running in Task Manager and can be operated normally in the terminal and visualization tool.
The error is: 
**Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)**.  

Of course, I also tried using "localhost" as the host, but the error message was: 
_**Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused**_).

This is my input:
Database type
MariaSQL

Database
ragflow

User name
root

Host
127.0.0.1

Port
3306

Password
**************

### Expected behavior

Connect to the database after entering the correct parameters

### Steps to reproduce

```Markdown
When creating a workflow in the agent, you cannot connect to any of the local databases MySQL, PostgreSQL, or MariaSQL when using a database connection.
```

**Comment by KevinHuSh** [comment]
Check conf/service_conf.yaml, make sure all the `host` in that configuration file can be accessible through the network that hosts RAGFlow.

Do you run RAGFlow by docker container or what?
If it is, 127.0.0.1 is a wrong IP for other services deployed on the same host.

**Comment by 12dc32d** [comment]
> Check conf/service_conf.yaml, make sure all the `host` in that configuration file can be accessible through the network that hosts RAGFlow.
> 
> Do you run RAGFlow by docker container or what? If it is, 127.0.0.1 is a wrong IP for other services deployed on the same host.

Thank you very much for your reply, it is very useful to me. I have read many articles and blogs about how to use docker in the past, but I didn't use it correctly.
Is it possible to integrate the workflow (especially the agent) started by docker on the web page into a separate application? I packaged it directly on dockerhub but failed.
