### ISSUE TITLE
[Bug]: cohere key error

### ISSUE THREAD

**Issue by ksztone-huanggonghao** [infiniflow/ragflow#3384]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

-

### Actual behavior

![image](https://github.com/user-attachments/assets/886e5ca5-df7b-4a81-9e68-d34fe00b61ef)
![image](https://github.com/user-attachments/assets/6b4f3d9d-7cbe-4559-9f9c-cd485a18f0d7)
The request parameters are incorrect, leading to a KeyError issue.

### Steps to reproduce

```Markdown
send request in the web
```

**Comment by yuzhichang** [comment]
Fixed by #3392
