### ISSUE TITLE
[Question]: redis error,mysql error. Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by wrl02** [infiniflow/ragflow#3385]
### Describe your problem

(base) wrl@rgzn:~/code/RAGflow/ragflow/docker$ docker compose -f docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string. 
[+] Running 17/4
 ⠧ es01 10 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                      63.8s 
 ⠧ ragflow 67 layers [⣿⣿⣤⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] 619.1MB/7.831GB Pulling                                          63.8s 
 ✘ redis Error                                                                                                                                              63.8s 
 ✘ mysql Error                                                                                                                                              63.8s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by KevinHuSh** [comment]
Downloading image error since network is not accessible.

Add the following to /etc/docker/daemon.json
{
  "registry-mirrors": [
    "https://docker.211678.top",
    "https://docker.1panel.live",
    "https://hub.rat.dev"",
    "https://docker.m.daocloud.io",
    "https://do.nark.eu.org",
    "https://dockerpull.com",
    "https://dockerproxy.cn",
    "https://docker.awsl9527.cn/",
  ]
}
