### ISSUE TITLE
[Question]: how elastic search got used? and in the rag folder, how naive.py, qa.py different ? 

### ISSUE THREAD

**Issue by bzr1** [infiniflow/ragflow#3387]
### Describe your problem

as title
1:how elastic search got used?
2:how naive.py, qa.py different ?

**Comment by KevinHuSh** [comment]
Elasticsearch is used for full text search.
`naive.py` and `qa.py` are two different chunk methods.
 - `naive.py` basicly apply token number as a chunking condition.
 - `qa.py`  is for Q&A fromated raw data, and only Q indexed.

**Comment by bzr1** [comment]
> Elasticsearch is used for full text search. `naive.py` and `qa.py` are two different chunk methods.
> 
> * `naive.py` basicly apply token number as a chunking condition.
> * `qa.py`  is for Q&A fromated raw data, and only Q indexed.

thank you so much
