### ISSUE TITLE
[Question]: Which types of documents are suitable for using the Knowledge Graph chunking method?

### ISSUE THREAD

**Issue by Match-Yang** [infiniflow/ragflow#3389]
### Describe your problem

I have a technical documentation website about SDK usage. 

The documents include feature introduction documents, API documents, concepts and terminology, error codes, etc. Among them, API documents account for about half of the total volume. 

Which types of documents are suitable for using the Knowledge Graph chunking method? Because obviously, if all are used with the Knowledge Graph chunking method, it will be very slow and consume a lot of LLM tokens. However, if the API documents, which account for nearly half of the total volume, do not use the Knowledge Graph chunking method, it will be difficult to associate them with the feature documents, leading to "hallucinations" when generating example code in the final answers.

I hope to have some usage suggestions or best practice guidance.

**Comment by KevinHuSh** [comment]
I don't think KG is a good choise.
Could you make an example why API instructions can't associate with feature documents, and why human being can related them?
