### ISSUE TITLE
[Question]: The wechat plugin was unable to create a conversation

### ISSUE THREAD

**Issue by ZxnSnowy** [infiniflow/ragflow#3395]
### Describe your problem

![image](https://github.com/user-attachments/assets/c665bd0a-4567-4768-845c-ce7a6e3a6617)
I have successfully started ragflow, is it a problem with the version of ragflow I am using? Currently, I am using the development version of docker image, may I ask how can I successfully create a session using the open version?

In addition, I noticed that the from common.log import logger was changed to from api.utils.log_utils import logger, but there was no api package for importing files in plugins folder to COW. You still have to use the original from common.log import logger。

**Comment by KevinHuSh** [comment]
What do you mean by common.log?

**Comment by ZxnSnowy** [comment]
From the COW project. Because if want to copy ragflow's plugin folder into the COW project, should use the "from common.log import logger"
