### ISSUE TITLE
[Question]: raptor issue

### ISSUE THREAD

**Issue by DankerMu** [infiniflow/ragflow#3398]
### Describe your problem

离线部署v0.13.0，使用raptor总结时，出现"Connectionerror" object has no attribute "f_lineno"

**Comment by Sail64** [comment]
这种错误，要检查一下你的大语言模型的配置是否正确。

**Comment by DankerMu** [comment]
> 这种错误，要检查一下你的大语言模型的配置是否正确。

这是在知识库设置时，处理文档出现的错误，更模型没关系吧

**Comment by DankerMu** [comment]
> 这种错误，要检查一下你的大语言模型的配置是否正确。

确实是系统模型没配置好
