### ISSUE TITLE
[Bug]: The progress cannot advance in MacOS (showing ⚠️ARM64)

### ISSUE THREAD

**Issue by Harryyu24** [infiniflow/ragflow#3408]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

88072b1e900cf69716038bba77087e19f38ee45e

### Actual behavior

When installing ragflow, the ARM64 architecture has already been configured, but after running Docker, it still shows ⚠️ amd64, and the CPU usage reaches nearly 200%. The performance is reported to be extremely low. Additionally, while parsing DOC files, the progress cannot advance. It seems that this open-source project cannot function effectively on macOS.

### Steps to reproduce

```Markdown
I just follow the standard steps for MacOS. And I also use a updated requirements_arm.txt and Dockerfile.arm in a closed case"[Macosx M1 not supported?](https://github.com/infiniflow/ragflow/issues/1164#top) #1164". 
Similar situations with the same bug(⚠️AMD64)
```

**Comment by KevinHuSh** [comment]
You can try dev-slim version of docker image since it do not handle embeding inference itself.

**Comment by Harryyu24** [comment]
I have 

> You can try dev-slim version of docker image since it do not handle embedding inference itself.

I have tried all versions, same situations ⚠️AMD64 and embedding doesn't work.

**Comment by KevinHuSh** [comment]
For slim version of RAGFlow, it dose not handle embedding procedure itself. You need to use Ollama to deploy an embedding inference.

**Comment by tiankongzhicheng0862** [comment]
M3 chip, installation fails, error message
rosetta error:
Rosetta is only intended to run on Apple Silicon with a macOS host using Virtualization.framework with Rosetta mode enabled
% , is there a similar situation?

**Comment by midilandlu** [comment]
it work on M2 chip , I build docker image from source code. follow these steps :  
conda env 
git clone https://github.com/infiniflow/ragflow.git
cd ragflow/
pip3 install huggingface-hub nltk
python3 download_deps.py
docker build -f Dockerfile.slim -t infiniflow/ragflow:dev-slim .
docker compose -f docker-compose.yml -p ragflow up -d

**Comment by yuzhichang** [comment]
We have difficulty on building multi-arch image with CI. So we will not publish arm64 image officially in the near future.  
However you can build it by yourself on a `linux/arm64` or `darwin/arm64` host.
