### ISSUE TITLE
[Bug]: Maximum Doc size is hardcoded

### ISSUE THREAD

**Issue by zzecool** [infiniflow/ragflow#341]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

uknown

### Other environment information

```Markdown
Docker
```

### Actual behavior

The maximum Doc size is not only defined in nginx.conf but it is also hardcoded in the source as 128MB

### Expected behavior

Maximum Doc size should either  entered in configuration over UI and - or dictated within .env 

### Steps to reproduce

```Markdown
Try to upload a Doc bigger than 128MB
```

**Comment by hehemagic** [comment]
The problem hasn't been solved yet.   rag/settings also has the limitation
DOC_MAXIMUM_SIZE = 128 * 1024 * 1024
