### ISSUE TITLE
[Bug]: Getting "Can't inference the where the component input is." on use of categorize component in some cases.

### ISSUE THREAD

**Issue by arjunw3nuts** [infiniflow/ragflow#3410]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

df9d054

### Actual behavior

Can't inference the where the component input is.

![image](https://github.com/user-attachments/assets/8073119d-33a7-42e0-8881-f53d125c60de)

### Expected behavior

Generate answer from the websearch tool.

### Steps to reproduce

```Markdown
Create an agent from the general chatbot template.
Run the agent.
Ask for something that triggers websearch tool.
```

### Additional information

Works okay in the demo app. Getting the error in local setup.

**Comment by KevinHuSh** [comment]
Could you pull the dev version of docker image again since we fixed things about this recently?
Is it on demo, but I can't re-produce it again?
![image](https://github.com/user-attachments/assets/bee0e09e-c8a1-436a-8732-3e6388babe8f)

**Comment by arjunw3nuts** [comment]
I am running the server locally from source on wsl. I took the latest pull from main branch.
Pulled the docker by: docker compose -f docker/docker-compose-base.yml pull
Running the server using: bash docker/launch_backend_service.sh

Am I missing anything? @KevinHuSh Appreciate your help.

**Comment by KevinHuSh** [comment]
```
docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev 
```
