### ISSUE TITLE
[Bug]: Getting "KeyError('messages')" when calling agent completions HTTP API

### ISSUE THREAD

**Issue by ddallabenetta** [infiniflow/ragflow#3413]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

df9d054

### Actual behavior

Can't use agents via api, since the completions api always return the following error:
<img width="339" alt="Screenshot 2024-11-14 alle 14 26 48" src="https://github.com/user-attachments/assets/5989178b-c411-42d6-b882-c1bd127640ff">

By looking at the session.py code, I noticed that the session gets created with a 'message' field instead of a'messages' one. This may be the reason of the issue.

### Expected behavior

Generate response from agent via HTTP API

### Steps to reproduce

```Markdown
1. Create an agent
2. Call the HTTP request via POST /api/v1/agents/{agentId}/completions with the following body

{
    "stream": true,
    "question": "Hello?"
}
```
```


### Additional information

_No response_

**Comment by KevinHuSh** [comment]
Which LLM do you use?

**Comment by ddallabenetta** [comment]
I am using OpenAI gpt 4o mini. The api key is set and it’s working through the agent run web ui

**Comment by zzhh777** [comment]
I I have the same issue. I configured an Agent and successfully ran it via the web UI, but when I tried to invoke it using the HTTP API, it returned an error: {"data":null,"retcode":100,"retmsg":"KeyError('messages')"}. I rebuilt an Agent without LLM, but it still returns this error.
![微信图片_20241107003948](https://github.com/user-attachments/assets/e8d43cd6-baf1-4477-b15c-ccf69d666e0b)
@KevinHuSh

**Comment by zzhh777** [comment]
I have the same issue. I configured an Agent and successfully ran it via the web UI, but when I tried to invoke it using the HTTP API, it returned an error: {"data":null,"retcode":100,"retmsg":"KeyError('messages')"}. I rebuilt an Agent without LLM, but it still returns this error.
![微信图片_20241117223707](https://github.com/user-attachments/assets/c78f9186-73ca-46ac-a1a1-0489c498a709)
@KevinHuSh

**Comment by Feiue** [comment]
Please update your code.
![Uploading image.png…]()

**Comment by ddallabenetta** [comment]
What do you mean? I can't really spot the dfference between mine and your request

<img width="1388" alt="Screenshot 2024-11-18 alle 08 41 16" src="https://github.com/user-attachments/assets/cacd9900-aa91-4575-92d2-f8715cdbd96b">

**Comment by Feiue** [comment]
Please modify the `.env` file by changing `dev-slim` to `dev`, then run `docker compose -f docker-compose.yml pull`, followed by `docker compose -f docker-compose.yml up -d`. Finally, select an agent with a properly configured available model to call the API.

**Comment by ddallabenetta** [comment]
It finally solved my issue. Thank you very much 🙏
