### ISSUE TITLE
[Bug]: there is a no such key error when using dev-slim latest

### ISSUE THREAD

**Issue by laozaim** [infiniflow/ragflow#3447]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

9d395ab

### Other environment information

```Markdown
OS: ubuntu24.04LTS
Hardware: intel based 4C/16G 50G server.

docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.23
  GitCommit:        57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Actual behavior

clone the repo and go to docker folder
clear volum with `docker volume prune -a`
use `docker compose docker-compose.yml up -d` to start with dev-slim (also tried dev)
the ragflow server omit a error on function `queue_lengthrag_flow_svr_queue`

```
2024-11-16 03:07:58,413 ERROR    16 queue_lengthrag_flow_svr_queue got exception
Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 231, in queue_info
    groups = self.REDIS.xinfo_groups(queue)
  File "/usr/local/lib/python3.10/dist-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/usr/local/lib/python3.10/dist-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/dist-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/dist-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.10/dist-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.10/dist-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.10/dist-packages/valkey/connection.py", line 570, in read_response
    raise response
valkey.exceptions.ResponseError: no such key
```

the system is in unkown state, see the screen shot:
<img width="1498" alt="图片" src="https://github.com/user-attachments/assets/64c6efd9-9ea0-49e3-a55e-bdbb8ad2b2ce">

### Steps to reproduce

```Markdown
clone the repo and go to docker folder
clear volum with `docker volume prune -a`
use `docker compose docker-compose.yml up -d` to start with dev-slim (also tried dev)
the ragflow server omit a error on function `queue_lengthrag_flow_svr_queue`
```

**Comment by thehuanlwd** [comment]
我也是这样，知识库解析会卡死

**Comment by a617733197** [comment]
同样遇到了这个问题,解析文件时会报错
![image](https://github.com/user-attachments/assets/dbe0120a-6d11-4078-a191-c70b36f0f37c)

**Comment by shizzgar** [comment]
Same here!
```bash
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/rag/utils/redis_conn.py", line 231, in queue_info
ragflow-server  |     groups = self.REDIS.xinfo_groups(queue)
ragflow-server  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
ragflow-server  |     return self.execute_command("XINFO GROUPS", name)
ragflow-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/client.py", line 570, in execute_command
ragflow-server  |     response = conn.retry.call_with_retry(
ragflow-server  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/retry.py", line 62, in call_with_retry
ragflow-server  |     return do()
ragflow-server  |            ^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/client.py", line 571, in <lambda>
ragflow-server  |     lambda: self._send_command_parse_response(
ragflow-server  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/client.py", line 543, in _send_command_parse_response
ragflow-server  |     return self.parse_response(conn, command_name, **options)
ragflow-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/client.py", line 590, in parse_response
ragflow-server  |     response = connection.read_response()
ragflow-server  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
ragflow-server  |   File "/ragflow/.venv/lib/python3.12/site-packages/valkey/connection.py", line 570, in read_response
ragflow-server  |     raise response
ragflow-server  | valkey.exceptions.ResponseError: no such key
```

**Comment by zzj756321** [comment]
main分支是会这样，可以用v0.13.0版本的

**Comment by Nils-Rep** [comment]
I still get the same error ``valkey.exceptions.ResponseError: no such key``.

Also when I enter the browser on http://127.0.0.1:9380 it returns the following:
``{
    "code": 100,
    "data": null,
    "message": "<NotFound '404: Not Found'>"
}``

**Comment by zzj756321** [comment]
源码里有这个service_config.yaml的模板，拷贝一个，然后挂载到镜像的对应路径即可ragflow/conf/service_conf

**Comment by Nils-Rep** [comment]
> 源码里有这个service_config.yaml的模板，拷贝一个，然后挂载到镜像的对应路径即可ragflow/conf/service_conf @Nils-Rep

Thanks for the quick response, but now I get the following error:

```
$ docker logs -f ragflow-server
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 26, in <module>
    from api.db.db_models import close_connection
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
  File "/ragflow/api/settings.py", line 36, in <module>
    from rag.utils.es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 464, in <module>
    ELASTICSEARCH = ESConnection()
  File "/ragflow/rag/utils/__init__.py", line 28, in _singleton
    instances[key] = cls(*args, **kw)
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    if not self.es.ping():
AttributeError: 'ESConnection' object has no attribute 'es' 
```

I did the following:
`cp .\docker\service_conf.yaml.template .\conf\service_conf.yaml`
in docker/.env: `RAGFLOW_IMAGE=infiniflow/ragflow:v0.13.0`
in docker/docker-compose.yaml: 
```
volumes:
  - ../conf/service_conf.yaml:/ragflow/conf/service_conf.yaml
  ...
 ```
 
 Other than that I previously followed the Get-Started Guide of the Read-Me

**Comment by AlexdanerZe** [comment]
> > 源码里有这个service_config.yaml的模板，拷贝一个，然后挂载到镜像的对应路径即可ragflow/conf/service_conf @Nils-Rep
> 
> Thanks for the quick response, but now I get the following error:
> 
> ```
> $ docker logs -f ragflow-server
> Traceback (most recent call last):
>   File "/ragflow/api/ragflow_server.py", line 26, in <module>
>     from api.apps import app
>   File "/ragflow/api/apps/__init__.py", line 26, in <module>
>     from api.db.db_models import close_connection
>   File "/ragflow/api/db/db_models.py", line 33, in <module>
>     from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
>   File "/ragflow/api/settings.py", line 36, in <module>
>     from rag.utils.es_conn import ELASTICSEARCH
>   File "/ragflow/rag/utils/es_conn.py", line 464, in <module>
>     ELASTICSEARCH = ESConnection()
>   File "/ragflow/rag/utils/__init__.py", line 28, in _singleton
>     instances[key] = cls(*args, **kw)
>   File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
>     if not self.es.ping():
> AttributeError: 'ESConnection' object has no attribute 'es' 
> ```
> 
> I did the following: `cp .\docker\service_conf.yaml.template .\conf\service_conf.yaml` in docker/.env: `RAGFLOW_IMAGE=infiniflow/ragflow:v0.13.0` in docker/docker-compose.yaml:
> 
> ```
> volumes:
>   - ../conf/service_conf.yaml:/ragflow/conf/service_conf.yaml
>   ...
> ```
> 
> Other than that I previously followed the Get-Started Guide of the Read-Me

可以匹配一下对应es和mysql端口，让service_conf.yaml和docker-compose-base.yml 保持一致

**Comment by yuzhichang** [comment]
Please try v0.14.0. The system status page has been reworked.

**Comment by brucegamma** [comment]
ragflow/conf/service_conf.yaml这个文件会在docker restart的时候被重写。改什么都没用
