### ISSUE TITLE
[Question]: I saw that after the integration of infinity, the configuration of infinity was not written in serice_conf.yml, is it not developed yet? 

### ISSUE THREAD

**Issue by 1006076811** [infiniflow/ragflow#3450]
### Describe your problem

I saw that after the integration of infinity, the configuration of infinity was not written in serice_conf.yml, is it not developed yet? In addition, does infinity have GUI pages similar to es and milvus?

**Comment by JinHai-CN** [comment]
Infinity has a GUI, but it is still in its early stages and is relatively simple.

**Comment by yuzhichang** [comment]
The following default configuration (in `rag/settings.py`) works:
```
INFINITY = get_base_config("infinity", {"uri": "infinity:23817"})
```
So there's no need to mention infinity in service_conf.yml.
However recording the default config into service_conf.yml is doable.
