### ISSUE TITLE
[Bug]: The launch_backend_service.sh command is used to start the service. After logging in to the system and viewing system information, the location of the original es and the location of the task executor are abnormal.

### ISSUE THREAD

**Issue by 1006076811** [infiniflow/ragflow#3452]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

last

### Actual behavior

The launch_backend_service.sh command is used to start the service. After logging in to the system and viewing system information, the location of the original es and the location of the task executor are abnormal.
![image](https://github.com/user-attachments/assets/09dd240c-5c48-44cd-a02b-eeb388f56c90)

### Steps to reproduce

```Markdown
Normal start
```

**Comment by KevinHuSh** [comment]
Check out the conf/service_conf.yaml at first place and check out the status of ES.

**Comment by 1006076811** [comment]
> Check out the conf/service_conf.yaml at first place and check out the status of ES.首先查看 conf/service_conf.yaml 并查看 ES 的状态。

es状态是正常的，并且问答功能可以正常召回。

**Comment by 1006076811** [comment]
> Check out the conf/service_conf.yaml at first place and check out the status of ES.首先查看 conf/service_conf.yaml 并查看 ES 的状态。

The es status is normal, and the Q&A function can be recalled normally.

**Comment by yuzhichang** [comment]
@1006076811 RAGFlow v0.14.1 has fixed above issues.
