### ISSUE TITLE
[Bug]: dependency failed to start: container ragflow-es-01 is unhealthy

### ISSUE THREAD

**Issue by thistleknot** [infiniflow/ragflow#346]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

d0ff779d3fee9a845f945ce18235b230113fab6e

### Actual behavior

WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
[+] Running 3/3
 ✘ Container ragflow-es-01  Error                                                                                                                        2.0s
 ✔ Container ragflow-mysql  Healthy                                                                                                                      0.0s
 ✔ Container ragflow-minio  Running                                                                                                                      0.0s
dependency failed to start: container ragflow-es-01 is unhealthy

### Steps to reproduce

```Markdown
git clone https://github.com/infiniflow/ragflow
cd ragflow/
docker build -t infiniflow/ragflow:v1.0 .
cd ragflow/docker
chmod +x ./entrypoint.sh
docker compose up -d
```

**Comment by KevinHuSh** [comment]
Have a look at this: https://github.com/infiniflow/ragflow/blob/main/docs/faq.md
which has the solution.

**Comment by thistleknot** [comment]
I searched the faq for the phrase 'unhealthy' as well as 'ragflow-es-01' and the closest I found was 'healthy' (what I don't see), and some information about cluster 'Exception: Can't connect to ES cluster?'

I'm assuming you are saying that I don't have a specific response within that document that solves my problem, but there are processes within that document that I should try to see if it resolves the problem I've listed?

**Comment by thistleknot** [comment]
sysctl -w vm.max_map_count=262144
that was the solution

**Comment by OmegAshEnr01n** [comment]
Ok this worked. In order to make sure that there is no confusion around this, it should be added to FAQ with this error message `dependency failed to start: container ragflow-es-01 is unhealthy`

**Comment by SuperTangW** [comment]
Excuse me, where is this configuration set? 
Is it in ES's container?
