### ISSUE TITLE
[Question]: I cannot use localhost to call api

### ISSUE THREAD

**Issue by sun-timer** [infiniflow/ragflow#3464]
### Describe your problem

I used the method in api doc like this:
![image](https://github.com/user-attachments/assets/1a3c5fff-563a-4da1-8601-2daa0a200949)
it returned 200, but 404 in retmsg
![image](https://github.com/user-attachments/assets/0a3868e6-a016-4767-bb65-04845b2cc0e2)
![image](https://github.com/user-attachments/assets/90bd3d96-7d20-4ced-a47e-8c03effadae6)
did I use wrong address?

**Comment by sun-timer** [comment]
I tried to stop the docker image and get new source code(dev-slim), it was resolved. Maybe pre version(dev) have some problem?
![image](https://github.com/user-attachments/assets/5ab4c604-8120-4795-81c9-55579110eba4)

**Comment by Feiue** [comment]
Your dev version is too outdated.Please modify the .env file by changing dev-slim to dev, then run docker compose -f docker-compose.yml pull, followed by docker compose -f docker-compose.yml up -d. Finally, select an agent with a properly configured available model to call the API.
