### ISSUE TITLE
[Question]: Why doesn't the project I deployed have the 'Chat Bot API' option

### ISSUE THREAD

**Issue by xxc-11** [infiniflow/ragflow#3465]
### Describe your problem

It looks different
![0104daa6714d42d760a27bc1febffac](https://github.com/user-attachments/assets/e2a61e94-f45a-44af-b573-d90937e38fa5)
![dda84ade29ff046352a82d07cb5700d](https://github.com/user-attachments/assets/bed7077a-bde3-4917-95d9-a799ed8dc6c3)

**Comment by cgx-avenue** [comment]
Exactly the same problem. I need the API for demo case. Could anyone kindly answer this?

**Comment by kdta91** [comment]
You have to use dev version for that. As of version 0.13, you can find the API keys by clicking on the profile icon -> API but you cannot add an API key for now. They'll probably set everything up on version 0.14 [See roadmap](https://github.com/infiniflow/ragflow/issues/1821)

**Comment by KevinHuSh** [comment]
Since the mechanism for authorization of API token has changed, we are gona figure out how to provide an embeded iframe for specific chat bot.

**Comment by xxc-11** [comment]
Thank you all for your answers

**Comment by kdta91** [comment]
> > You have to use dev version for that. As of version 0.13, you can find the API keys by clicking on the profile icon -> API but you cannot add an API key for now. They'll probably set everything up on version 0.14 [See roadmap](https://github.com/infiniflow/ragflow/issues/1821)
> 
> I'm using ifiniflow/ragflow:dev image now. Is there any way that I could use Chatbot API again? like a specific version of 0.12.0?

If you upgraded from version 0.12 and have a chat assistant from that version you'll see the API Keys from your chat assistants by clicking on the profile icon on the top right. From there there is an API tab, click on that and you'll see this screen: 
![Screenshot from 2024-11-19 12-27-33](https://github.com/user-attachments/assets/89530957-50f0-497d-8d5f-7ecfadaf7a78)

Note: You cannot create a new API Key

To use a specific chat assistant, you have to make use of the Chat ID.

In my case this is how I used the API:

1. [Create session with chat assistant](https://ragflow.io/docs/dev/http_api_reference#create-session-with-chat-assistant)
2. Grab session id from response
3. [Converse with the chat bot](https://ragflow.io/docs/dev/http_api_reference#converse-with-chat-assistant)

You need the ff:

1. API Key for the Authorization header
2. Chat ID for step 3 above `/api/v1/chats/{chat_id}/completions`

**Comment by cgx-avenue** [comment]
> > > You have to use dev version for that. As of version 0.13, you can find the API keys by clicking on the profile icon -> API but you cannot add an API key for now. They'll probably set everything up on version 0.14 [See roadmap](https://github.com/infiniflow/ragflow/issues/1821)
> > 
> > 
> > I'm using ifiniflow/ragflow:dev image now. Is there any way that I could use Chatbot API again? like a specific version of 0.12.0?
> 
> In a fresh install of 0.13, I don't think you can create an API key.
> 
> If you upgraded from version 0.12 and have a chat assistant from that version you'll see the API Keys from your chat assistants by clicking on the profile icon on the top right. From there there is an API tab, click on that and you'll see this screen:
> 
> ![Screenshot from 2024-11-19 12-27-33](https://private-user-images.githubusercontent.com/7354911/387491499-89530957-50f0-497d-8d5f-7ecfadaf7a78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTY0NzAsIm5iZiI6MTczMTk5NjE3MCwicGF0aCI6Ii83MzU0OTExLzM4NzQ5MTQ5OS04OTUzMDk1Ny01MGYwLTQ5N2QtOGQ1Zi03ZWNmYWRhZjdhNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMDYwMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAyYTc2NThkYjMyYzkyOWI5OGQwMmYwNTg5MTlhMGRlN2RiN2MxNjc4MjJmNzIyYzczMTdlYmYxMWYzZjJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wzO2dXB_yfLWUQP4htGddVqbpFQCl0qNaQNDhAb8BH4)
> 
> To use a specific chat assistant, you have to make use of the Chat ID.
> 
> In my case this is how I used the API:
> 
> 1. [Create session with chat assistant](https://ragflow.io/docs/dev/http_api_reference#create-session-with-chat-assistant)
> 2. Grab session id from response
> 3. [Converse with the chat bot](https://ragflow.io/docs/dev/http_api_reference#converse-with-chat-assistant)
> 
> You need the ff:
> 
> 1. API Key for the Authorization header
> 2. Chat ID for step 3 above `/api/v1/chats/{chat_id}/completions`

Thanks for the reply! I checked this and the HTTP API doc, finally succeed in calling it. But still looking forward for your new API mechanism implementation.

**Comment by stickuser2022** [comment]
great
