### ISSUE TITLE
[Question]: http://127.0.0.1:9380/   showing {"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"}

### ISSUE THREAD

**Issue by younggggger** [infiniflow/ragflow#347]
### Describe your problem

what's the problem?

**Comment by KevinHuSh** [comment]
The port is wrong.
9380 is web server port, 80 is.

**Comment by nguyenvulong** [comment]
The `docker logs` is misleading.
For those who want to see the web dashboard, go for **port 80, NOT port 9380**


![image](https://github.com/infiniflow/ragflow/assets/1311412/3678ba9c-1593-42bd-b570-d50d5ed33dd2)
