### ISSUE TITLE
[Bug]: No file parsed successfully

### ISSUE THREAD

**Issue by wulala-star1** [infiniflow/ragflow#3476]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

1

### Commit ID

1

### Other environment information

```Markdown
1
```

### Actual behavior

1

### Expected behavior

1

### Steps to reproduce

```Markdown
1
```

### Additional information

尝试了pdf ，txt，docx全都不成功

**Comment by JinHai-CN** [comment]
Would you please attach a failed file?

**Comment by wulala-star1** [comment]
> Would you please attach a failed file?

[mpi相关.txt](https://github.com/user-attachments/files/17810900/mpi.txt)
please see it

**Comment by KevinHuSh** [comment]
What is error message by hovering the processing bar?

**Comment by yuzhichang** [comment]
Close due to no response.
@wulala-star1 Please fill detailed info in BUG report next time.
