### ISSUE TITLE
[Question]: In the latest version (ragflow:v0.13.0), the "Team" feature seems to be completely non-functional. Team members cannot see the configured model API or the constructed knowledge base. It’s unclear how teams are supposed to use this feature, as it currently provides no visible functionality.

### ISSUE THREAD

**Issue by biofer** [infiniflow/ragflow#3479]
### Describe your problem

In the latest version (ragflow:v0.13.0), the "Team" feature seems to be completely non-functional. Team members cannot see the configured model API or the constructed knowledge base. It’s unclear how teams are supposed to use this feature, as it currently provides no visible functionality.

**Comment by Constey** [comment]
In v0.13.0 adding team member looks like non functional or not yet build:
![image](https://github.com/user-attachments/assets/3fccc3d1-0281-4ac5-a8fd-83d7172518c4)

**Comment by Constey** [comment]
I can see the kb created from a team member:
![image](https://github.com/user-attachments/assets/95a4fb6c-c430-41a6-b977-80310fa050e9)

**Comment by biofer** [comment]
1、The team member invitation was successful.
<img width="1887" alt="image" src="https://github.com/user-attachments/assets/9a48e458-22fe-46b1-89bb-4492ef5f628b">
2、The knowledge base has been successfully created.
<img width="820" alt="image" src="https://github.com/user-attachments/assets/4c395350-0b08-4120-a031-431156ba8749">
3、

**Comment by biofer** [comment]
> I can see the kb created from a team member: ![image](https://private-user-images.githubusercontent.com/11457386/387594966-95a4fb6c-c430-41a6-b977-80310fa050e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzA2MjAsIm5iZiI6MTczMjA3MDMyMCwicGF0aCI6Ii8xMTQ1NzM4Ni8zODc1OTQ5NjYtOTVhNGZiNmMtYzQzMC00MWE2LWI5NzctODAzMTBmYTA1MGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzQ1NzI1ZTcxY2Q5YzVmYmUwYzY1MDgwMTIxOGMzNjU4YWM0YzcxNDljMGVjZTYyOTI4NWFkYjljZTcxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GI9O8xHemvs7qE2v8oXwf1s8C5bhexq5uh-ieyYLJVs)

Is this screenshot from the online version or the locally deployed version?
