### ISSUE TITLE
[Question]: 安装并启动成功后，验证了RAG基本功能后有事关机了，然后再也启动不来了，一直提示：There is an abnormality in your network and you cannot connect to the serve。

### ISSUE THREAD

**Issue by mjiulee** [infiniflow/ragflow#348]
### Describe your problem

[Question]: 如题，昨天安装并启动成功后，验证了RAG基本功能后有事关机了，然后今天想再继续深入研究先，但登录的时候，一直提示：There is an abnormality in your network and you cannot connect to the serve。

查看了下日志，发现是elastic_transport链接不成功，但是readme里面没有相关的配置说明，我也没改过相关的配置，

请问我应该如何解决这个问题呢？

`

[WARNING] [2024-04-14 19:09:25,210] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 3 times in a row, putting on 4 second timeout
[WARNING] [2024-04-14 19:09:25,211] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5ee616cd50>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-04-14 19:09:25,213] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout
[WARNING] [2024-04-14 19:09:29,826] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-04-14 19:09:29,835] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 13070.44it/s]
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 7825.19it/s]
[WARNING] [2024-04-14 19:11:47,977] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.

`

**Comment by KevinHuSh** [comment]
docker compose down -v(delete all data)
docker compose up

**Comment by KevinHuSh** [comment]
BTW, Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

**Comment by mjiulee** [comment]
got it , thank you~~
