### ISSUE TITLE
[Feature Request]: Proposal for Implementing a Dev Branch to Enhance Code Quality and Development Efficiency

### ISSUE THREAD

**Issue by 1006076811** [infiniflow/ragflow#3489]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

It is recommended that your team create a new dev branch for the iterative development of new features. Recently, there have been a significant number of bugs in commits to the main branch, some of which should not have occurred. It is suggested that commits to the main branch should only be merged after thorough testing has been completed. Daily development should take place on the dev branch.

**Comment by yuzhichang** [comment]
Thanks for you suggestion. However I don't think it can solve the core problem.
Most outer developers use the `ragflow:dev` and `ragflow:dev-slim` images (the git commit is on `system` page) and correlated code.
If they want to contribute, they fetch `master` branch.
