### ISSUE TITLE
[Question]: how ENV `HF_ENDPOINT` works

### ISSUE THREAD

**Issue by ooooo-create** [infiniflow/ragflow#350]
### Describe your problem

link: https://github.com/infiniflow/ragflow/issues/323#issuecomment-2050800223
because I have the same problem to connetct hf-mirror.com.
So I build the docker image from source https://github.com/infiniflow/ragflow?tab=readme-ov-file#%EF%B8%8F-build-from-source
And i delete the line 15 `ENV HF_ENDPOINT=https://hf-mirror.com`.Then `docker compose up `, the error is disappear.
I found it will not to download the model, so that when i upload docs and parse it, there is no model in path. 
As you say,i clone the deepdoc and add a volumes, like - ~/deepdoc:/ragflow/rag/res/deepdoc
That works!
But I still have the question how ENV `HF_ENDPOINT` works, why it influence whether to download models? This show it will have a default values in https://huggingface.co/docs/huggingface_hub/v0.13.3/package_reference/environment_variables#hfendpoint

**Comment by danielstankw** [comment]
@ooooo-create 
Can you please tell me where you delete the ENV from ?

**Comment by ooooo-create** [comment]
> @ooooo-create 
> Can you please tell me where you delete the ENV from ? 
> 

yes, I delete it in `dockerfile` which in the root dir

**Comment by KevinHuSh** [comment]
This is a mirror site for huggingface scince some of district can't access huggingface.

> @ooooo-create Can you please tell me where you delete the ENV from ?

If you can access huggingface, you'd better use docker-compose.yml.
