### ISSUE TITLE
[Bug]: ragflow-16fbe992(v0.13.0~146)-test at 2024-11-20：create Knowledge Base use Knowledge Graph and general method

### ISSUE THREAD

**Issue by neo-workship** [infiniflow/ragflow#3507]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

docker image version：16fbe992(v0.13.0~146)

### Commit ID

Knowledge Base method

### Other environment information

```Markdown
Hardware parameters:  Ultra 7 ，rtx 4060
OS type ：win11 - docker desktop
ragflow version： ragflow-16fbe992(v0.13.0~146)
others： embedding modle - baichuan-text-embedding ， LLM Model-Deepseek chat
```

##  Knowledge Graph method（Knowledge Graph 方法无法解析，报错）
The original text file is in Chinese ，the following issue occur：
- web page
![image](https://github.com/user-attachments/assets/4ac4b862-337d-4879-a2c7-f11d3871efb2)
- docker log
![image](https://github.com/user-attachments/assets/092a44d6-07fd-4d50-8900-eedd6e938270)

## General method
Using the general method, the text can be successfully parsed, but not queried（使用general方法，可成功解析文本，但无法查询）
![image](https://github.com/user-attachments/assets/dfec524e-c8af-456b-9bed-614841df3d97)

![image](https://github.com/user-attachments/assets/c65c6b04-cdec-4024-aabc-ae61cf3c70fc)

### Steps to reproduce

```Markdown
- step 1、Configure third-party AI apis
- step 2、Create a Knowledge base and configure it to use the Knowledge Graph method and general method
- step 3、Step 2 config embedding modle and llm modle which are config in step 1
- step 4、upload file ，The contents are in Chinese
- step 4、parse
```

**Comment by KevinHuSh** [comment]
Please pull the dev version of docker image. It's fixed.
