### ISSUE TITLE
Setting OpenAI Models

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#351]
### Describe your problem

I am trying to use GPT-4-Turbo instead of GPT-4, when I make the change in the configuration files it is not be passed through when I rebuild the docker images, and start the service.  How can I change the name of the model for OpenAI to use GPT-4-Turbo?

**Comment by KevinHuSh** [comment]
Fullfilled. git pull the latest souce code, and docker pull the latest image.

**Comment by rhudock** [comment]
Thank you.  The model should be gpt-4-turbo.
