### ISSUE TITLE
ERROR: Method agent.component.base.ComponentBase.set_output() parameter v={'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} violates type hint functools.partial | pandas.core.frame.DataFrame, as dict {'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} not <class "pandas.core.frame.DataFrame"> or <class "functools.partial">

### ISSUE THREAD

**Issue by jiao119** [infiniflow/ragflow#3522]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

111

### Other environment information

```Markdown
windows
```

### Actual behavior

ERROR: Method agent.component.base.ComponentBase.set_output() parameter v={'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} violates type hint functools.partial | pandas.core.frame.DataFrame, as dict {'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} not <class "pandas.core.frame.DataFrame"> or <class "functools.partial">.

### Steps to reproduce

```Markdown
ERROR: Method agent.component.base.ComponentBase.set_output() parameter v={'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} violates type hint functools.partial | pandas.core.frame.DataFrame, as dict {'content': "pd.DataFrame( {'message': ['你好！ 我是你的助理，有什么可以帮到你的吗？']})"} not <class "pandas.core.frame.DataFrame"> or <class "functools.partial">.
```

**Comment by KevinHuSh** [comment]
Fixed.
