### ISSUE TITLE
[Bug]: Click to log in but nothing happens

### ISSUE THREAD

**Issue by wulala-star1** [infiniflow/ragflow#3527]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

1

### Commit ID

1

### Other environment information

```Markdown
1
```

### Actual behavior

![image](https://github.com/user-attachments/assets/bbd48dd5-d5e5-467c-86d3-8938fe03ad95)
![image](https://github.com/user-attachments/assets/16a53108-2582-451a-95f6-31cab0875514)
![image](https://github.com/user-attachments/assets/a5ca1ebe-3497-45db-9619-c46b3d264e55)

### Expected behavior

1

### Steps to reproduce

```Markdown
1
```

### Additional information

1

**Comment by KevinHuSh** [comment]
Redis is not up. Check out the status of REDIS.

**Comment by yuzhichang** [comment]
@wulala-star1  Please file bug report details next time.
