### ISSUE TITLE
[Question]: Raptors always make mistakes

### ISSUE THREAD

**Issue by waiking1970** [infiniflow/ragflow#3533]
### Describe your problem

Start to do RAPTOR (Recursive Abstractive Processing for Tree-Organized Retrieval).
Task has been received.
[ERROR]Method rag.raptor.RecursiveAbstractiveProcessing4TreeOrganizedRetrieval.__call__() parameter chunks=[('XXXXXXXXX...]))] violates type hint tuple[str, numpy.ndarray], as list [('XXXXXXXXX...]))] not instance of tuple

**Comment by KevinHuSh** [comment]
Fixed.
