### ISSUE TITLE
[Question]: task will stuck when you delete the parsing doc,right?

### ISSUE THREAD

**Issue by tttmck** [infiniflow/ragflow#3541]
### Describe your problem

![image](https://github.com/user-attachments/assets/f4415a21-9d6a-4bbf-9460-33250de4c3e0)

I found that if i delete the parsing doc, all the doc parse task stuck, is that a bug?

**Comment by tttmck** [comment]
version: v0.13.0

**Comment by KevinHuSh** [comment]
It's fixed in the latest dev version of docker image.

**Comment by tttmck** [comment]
thank you
