### ISSUE TITLE
[Question]: 2024-11-21 10:56:29,347 ERROR    8452 report_status got exception Traceback (most recent call last):   File "/data1/work/workspaceai/ragflowgit/ragflow/rag/svr/task_executor.py", line 470, in report_status     LAG_TASKS = int(group_info["lag"])                     ~~~~~~~~~~^^^^^^^ KeyError: 'lag'

### ISSUE THREAD

**Issue by 120805481** [infiniflow/ragflow#3545]
### Describe your problem

2024-11-21 10:56:29,347 ERROR    8452 report_status got exception
Traceback (most recent call last):
  File "/data1/work/workspaceai/ragflowgit/ragflow/rag/svr/task_executor.py", line 470, in report_status
    LAG_TASKS = int(group_info["lag"])
                    ~~~~~~~~~~^^^^^^^
KeyError: 'lag'
这个报错是什么原因，怎么解决

**Comment by yuzhichang** [comment]
@120805481 Looks like a bug. Please provide detail information:
- Git code commit
- Docker image version
- How to reproduce

**Comment by kin1n** [comment]
[
![Snipaste_2024-11-27_17-14-52](https://github.com/user-attachments/assets/bc101ead-4c4d-4731-a5a2-43d60847efbb)
](url)

**Comment by kin1n** [comment]
> @120805481 Looks like a bug. Please provide detail information:
> 
> * Git code commit
> * Docker image version
> * How to reproduce

![Snipaste_2024-11-27_17-14-52](https://github.com/user-attachments/assets/1945c023-300a-4f47-9716-c562185d8eed)
我是拉取最新的版本，然后源码启动，就直接报这个错误了，跟上面提到的应该是一致的
