### ISSUE TITLE
[Question]: Errror with unicode database

### ISSUE THREAD

**Issue by isthaison** [infiniflow/ragflow#3566]
### Describe your problem

![image](https://github.com/user-attachments/assets/82af0bd8-1166-47c0-81f0-66bdbe63a070)
![image](https://github.com/user-attachments/assets/5d18b2da-35dd-4a8b-ac5c-11115da82070)
I see the utf8mb4_0900_ai_ci is used, it doesn't support unicode, when passing data to cloud model chat. It won't understand, is there any way to fix it?

**Comment by KevinHuSh** [comment]
Please refer to [this](https://stackoverflow.com/questions/202205/how-to-make-mysql-handle-utf-8-properly).
