### ISSUE TITLE
[Question]:如何链接到本地部署的LLM？ 

### ISSUE THREAD

**Issue by OKC13** [infiniflow/ragflow#357]
### Describe your problem

如何链接到本地部署的LLM？ 如下。

**Comment by cwingho** [comment]
RAGFlow 支持用 Ollama 链接到本地 LLM

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

Please refer to https://github.com/infiniflow/ragflow/blob/main/docs/ollama.md

**Comment by ysyx2008** [comment]
> Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊
> 
> Please refer to https://github.com/infiniflow/ragflow/blob/main/docs/ollama.md

run ollama in same computer (not docker), follow this doc, can't connected to ollama.

it seems like the ragflow in docker can't connect to the ollama service in host.

![图片](https://github.com/infiniflow/ragflow/assets/11251894/3d644509-a352-444e-a113-53e873dcceb2)

i'm sure ollama is worked fine.

i don't know docker very well, work for this promble serval days. Any suggestion will be appreciated.

**Comment by ysyx2008** [comment]
have i run ollama by docker and add it to ragflow networks?
