### ISSUE TITLE
[Bug]: Python SDK session.ask(question, stream=True) issue

### ISSUE THREAD

**Issue by nordy1145** [infiniflow/ragflow#3570]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

9b2f19fa66bb4a0bf2ddd787eabc9e39caf02ada

### Actual behavior

When running the Python Agent example, it's throwing a few exceptions.

Here is my python code.

```
from ragflow_sdk import RAGFlow,Agent

rag_object = RAGFlow(api_key="ragflow-apikey", base_url="http://urlhere:9380")
AGENT_id = "2a6fb1b0a78311ef96d60242asadfsdfafd"

session = Agent.create_session(AGENT_id,rag_object)    

print("\n===== Miss R ====\n")
print("Hello. What can I do for you?")

while True:
    question = input("\n===== User ====\n> ")
    print("\n==== Miss R ====\n")
    
    cont = ""
    for ans in session.ask(question, stream=True):
        print(ans.content[len(cont):], end='', flush=True)
        cont = ans.content
```

I get the following error:

```
Exception has occurred: TypeError
Session.ask() got an unexpected keyword argument 'stream'
  File "C:\Users\Coding\Ragflow\testagent.py", line 17, in <module>
    for ans in session.ask(question, stream=True):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.ask() got an unexpected keyword argument 'stream'
```

When I remove stream from session.ask (looks like stream isn't defined in the sdk at all) I get this error:

```
Exception has occurred: Exception
AssertionError('Nothing. Is it over?')
  File "C:\Users\Coding\Ragflow\testagent.py", line 17, in <module>
    for ans in session.ask(question): #, stream=True):
Exception: AssertionError('Nothing. Is it over?')
```

### Steps to reproduce

```Markdown
run this code from python.

from ragflow_sdk import RAGFlow,Agent

rag_object = RAGFlow(api_key="ragflow-apikey", base_url="http://urlhere:9380")
AGENT_id = "2a6fb1b0a78311ef96d60242acasfdsf"

session = Agent.create_session(AGENT_id,rag_object)    

print("\n===== Miss R ====\n")
print("Hello. What can I do for you?")

while True:
    question = input("\n===== User ====\n> ")
    print("\n==== Miss R ====\n")
    
    cont = ""
    for ans in session.ask(question, stream=True):
        print(ans.content[len(cont):], end='', flush=True)
        cont = ans.content
```

**Comment by zzhh777** [comment]
I used the dev image and encountered a similar bug. I built and successfully ran an Agent, but when I tried to invoke it using the HTTP API, it returned
` {"code":100,"data":null,"message":"AssertionError('Nothing. Is it over?')"}.`
![无标题](https://github.com/user-attachments/assets/85443836-e58f-485c-b115-91cf678a2a07)
![无标题2](https://github.com/user-attachments/assets/9e17201e-7faa-4421-960f-9ee994a6ad72)

**Comment by peizimo** [comment]
![image](https://github.com/user-attachments/assets/1f70b824-c492-429b-bac7-5d1a7d3ef6bf)
same problem , how should I change API , or mv service_conf.yaml to conf/ or so on , thanks

**Comment by fyxkszz** [comment]
me too. I get the error like this:
{
    "code": 100,
    "data": null,
    "message": "AssertionError('Nothing. Is it over?')"
}

**Comment by yuzhichang** [comment]
Fixed by #3581

**Comment by Yinst0** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> [9b2f19f](https://github.com/infiniflow/ragflow/commit/9b2f19fa66bb4a0bf2ddd787eabc9e39caf02ada)
> 
> ### Other environment information
> _No response_
> 
> ### Actual behavior
> When running the Python Agent example, it's throwing a few exceptions.
> 
> Here is my python code.
> 
> ```
> from ragflow_sdk import RAGFlow,Agent
> 
> rag_object = RAGFlow(api_key="ragflow-apikey", base_url="http://urlhere:9380")
> AGENT_id = "2a6fb1b0a78311ef96d60242asadfsdfafd"
> 
> session = Agent.create_session(AGENT_id,rag_object)    
> 
> print("\n===== Miss R ====\n")
> print("Hello. What can I do for you?")
> 
> while True:
>     question = input("\n===== User ====\n> ")
>     print("\n==== Miss R ====\n")
>     
>     cont = ""
>     for ans in session.ask(question, stream=True):
>         print(ans.content[len(cont):], end='', flush=True)
>         cont = ans.content
> ```
> 
> I get the following error:
> 
> ```
> Exception has occurred: TypeError
> Session.ask() got an unexpected keyword argument 'stream'
>   File "C:\Users\Coding\Ragflow\testagent.py", line 17, in <module>
>     for ans in session.ask(question, stream=True):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: Session.ask() got an unexpected keyword argument 'stream'
> ```
> 
> When I remove stream from session.ask (looks like stream isn't defined in the sdk at all) I get this error:
> 
> ```
> Exception has occurred: Exception
> AssertionError('Nothing. Is it over?')
>   File "C:\Users\Coding\Ragflow\testagent.py", line 17, in <module>
>     for ans in session.ask(question): #, stream=True):
> Exception: AssertionError('Nothing. Is it over?')
> ```
> 
> ### Expected behavior
> _No response_
> 
> ### Steps to reproduce
> ```
> run this code from python.
> 
> from ragflow_sdk import RAGFlow,Agent
> 
> rag_object = RAGFlow(api_key="ragflow-apikey", base_url="http://urlhere:9380")
> AGENT_id = "2a6fb1b0a78311ef96d60242acasfdsf"
> 
> session = Agent.create_session(AGENT_id,rag_object)    
> 
> print("\n===== Miss R ====\n")
> print("Hello. What can I do for you?")
> 
> while True:
>     question = input("\n===== User ====\n> ")
>     print("\n==== Miss R ====\n")
>     
>     cont = ""
>     for ans in session.ask(question, stream=True):
>         print(ans.content[len(cont):], end='', flush=True)
>         cont = ans.content
> ```
> 
> ### Additional information
> _No response_

I also encountered a problem when running this code in Python. But my question is as follows, how did you solve it later?
Traceback (most recent call last):
  File "/workspace/myragflow/test.py", line 15, in <module>
    for ans in session.ask(question, stream=True):
  File "/root/anaconda3/envs/ragflow/lib/python3.12/site-packages/ragflow_sdk/modules/session.py", line 34, in ask
    reference = json_data["data"]["reference"]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'reference'

**Comment by Gilmour6415** [comment]
We've encountered the same problem. and to solve, we print the "line" object  in 
![image](https://github.com/user-attachments/assets/ba3efdfd-0753-43f8-8669-a5c752216c67)
the debug console shows that:
![image](https://github.com/user-attachments/assets/b6f5c2b6-45b0-4e50-ac7f-deafa545bbf9)
the agent we use actually calls the RAG knowledge base , **so the "reference" should not suppose to an empty list**,
we guess its because the "reference" part is still in developing

Whatever, to solve this bug and to successfully call this agent api , the easiet way is to pass a "None" value to the "reference" key like this:
![image](https://github.com/user-attachments/assets/f92f139f-8231-4fc7-8f1c-47a145d35c92)
and therefore the code functions correctly:
![image](https://github.com/user-attachments/assets/a7ae7747-6207-442c-a8ee-6dc2f77e96c4)

**Comment by KevinHuSh** [comment]
#4131
