### ISSUE TITLE
[Bug]: No chunk found Check the chunk status please

### ISSUE THREAD

**Issue by pan003** [infiniflow/ragflow#3578]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

85dd9fde

### RAGFlow image version

85dd9fde(v0.13.0~172)

### Other environment information

```Markdown
/usr/bin/docker
printEnvironment.sh: 46: python: not found
Current Repo: ragflow-dev20241121
Commit Id: 85dd9fde
Operating system: Ubuntu 22.04 (Kernel version: 6.8.0-49-generic)
CPU Type: x86_64
Memory:
Docker Version: 24.0.5,
Python Version:
```

### Actual behavior

After updating infiniflow/ragflow:dev to the latest version, search feature is completely unavailable.

![ragflow-search-bug](https://github.com/user-attachments/assets/7510c095-2235-464e-a14c-961eef0af9ea)

### Steps to reproduce

```Markdown
docker pull infiniflow/ragflow:dev
git clone xxx (the latest version code)
docker-compose -f docker-compose.yml down
docker-compose -f docker-compose.yml up -d
```

### Additional information

http://xxx/v1/chunk/retrieval_test
reqest payload {"kb_id":["a00e2e4e9c1011ef8bab0242ac120006","aecfdee0966c11efa4210242ac120006","0b179b3a966c11efacd10242ac120006","560087e0950b11ef9ad30242ac120006","80098038950a11ef8bc30242ac120006","c92c2a4294ef11efadcd0242ac120006","593ebffc91e211ef9c940242ac120006","aca2c95491d811ef8a4b0242ac130006"],"highlight":true,"question":"发动机维修","page":1,"size":10}

response
 {
    "code": 102,
    "data": false,
    "message": "No chunk found! Check the chunk status please!"
}

**Comment by KevinHuSh** [comment]
What about retrieval test? I guess ES might be something wrong.

![image](https://github.com/user-attachments/assets/f85c3284-9b08-4fde-8cd4-d6e3e14664f7)

**Comment by vasede** [comment]
为什么分块chunk全部是0，检索测试中也测试不出相关内容，remark模型没有数据可选
<img width="633" alt="xx" src="https://github.com/user-attachments/assets/3c94bf98-05e5-4e5b-898a-6703f810f9d7" />

**Comment by KevinHuSh** [comment]
Have these documents been successfully parsed?
