### ISSUE TITLE
[Question]: About ChatGPT-on-WeChat

### ISSUE THREAD

**Issue by kunkeji** [infiniflow/ragflow#3583]
### Describe your problem

请问目前ChatGPT-on-WeChat功能已经可以使用了吗？有没有详细的文档说明，目前github上面的文档只说明了config的配置，没有相关的部署

**Comment by JinHai-CN** [comment]
The chatgpt-on-wechat project should be independently deployed in server mode. For more details on setting up in server mode, please refer to the guide here: [server mode](https://docs.link-ai.tech/cow/quick-start).

@timebankspace Would you please provide more information on the question?

**Comment by timebankspace** [comment]
> ### Describe your problem
> 请问目前ChatGPT-on-WeChat功能已经可以使用了吗？有没有详细的文档说明，目前github上面的文档只说明了config的配置，没有相关的部署

按官方文档部署好服务器模式的ChatGPT-on-WeChat之后，把插件文件夹复制到对应位置，
再根据微信个人、微信群、企业微信、飞书、钉钉等[对应的应用通道](https://docs.link-ai.tech/cow/multi-platform/wechat-mp)，修改根目录的config.json。

插件内的config.json只要修改地址和api key即可，目前只支持0.12.0及其之前的版本，0.13.0之后的api文档更新很大，我看时间升级。

**Comment by kunkeji** [comment]
好的，十分感谢
&nbsp;


鲲科技
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [infiniflow/ragflow] [Question]: About ChatGPT-on-WeChat (Issue #3583)














  
Describe your problem
 
请问目前ChatGPT-on-WeChat功能已经可以使用了吗？有没有详细的文档说明，目前github上面的文档只说明了config的配置，没有相关的部署
  
按官方文档部署好服务器模式的ChatGPT-on-WeChat之后，把插件文件夹复制到对应位置，
 再根据微信个人、微信群、企业微信、飞书、钉钉等对应的应用通道，修改根目录的config.json。
 
插件内的config.json只要修改地址和api key即可，目前只支持0.12.0及其之前的版本，0.13.0之后的api文档更新很大，我看时间升级。
