### ISSUE TITLE
[Bug]: In the Dockerfile building logic, when copying the huggingface.co file directory, since there are soft links pointing to the local cache addresses, it is impossible to copy the actual files into the image.

### ISSUE THREAD

**Issue by YANGBoSunning** [infiniflow/ragflow#3584]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

ee7fd71f

### RAGFlow image version

ee7fd71f(v0.13.0~174)

### Other environment information

```Markdown
OS type: MacOS & Linux
Chip Architecture: AMD
```

### Actual behavior

- First, I used the download_deps.py file to download the model resources required for building. 
<img width="355" alt="image" src="https://github.com/user-attachments/assets/5913f04c-924b-4844-bfff-6b7c94495e4d">
- After that, I used the dockerfile in the project to build a server image. 
- After I started the entrypoint.sh command using this image, I found that the server service still downloads resources from huggingface.co when starting up.
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/ecfec941-5873-4f08-b1a9-daaaf038bfe2">
- When I check the address information of the model file in the container, I find that many soft links in the model file point to the cache path on my local hard disk. This path does not exist in the container.
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/caf0fb3f-8704-4486-acc1-4ff002395601">

### Expected behavior

After the image is started, the server side can recognize the downloaded model resources and does not need to download from Hugging Face again.

### Steps to reproduce

```Markdown
1. git clone https://github.com/infiniflow/ragflow.git
cd ragflow/
pip3 install huggingface-hub nltk
2. python3 download_deps.py
3. bash build_docker_image.sh full
4. docker run -d image_name
```

**Comment by yuzhichang** [comment]
Fixed By #3586
