### ISSUE TITLE
[Bug]: several api bugs

### ISSUE THREAD

**Issue by zydmtaichi** [infiniflow/ragflow#3585]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

1d0a5606b2cb39962ca4ec0e38fcd59faeafee37

### RAGFlow image version

dev

### Other environment information

```Markdown
os type: ubuntu 22.04
```

### Actual behavior

1.the api path should /v1/api while the path that doc describes starts with /api/v1
2.the api in code like `api_app.py` is /completion while the api in doc is /completions
3.the agent api is invalid (like /api/v1/agents/{agent_id}/completions)

### Steps to reproduce

```Markdown
1.refer [doc](https://ragflow.io/docs/dev/http_api_reference) and the api define code like `api_app.py`
2.use postman to send the post request to `/api/v1/agents/{agent_id}/completions` api
```

**Comment by yuzhichang** [comment]
Fixed by #3589
