### ISSUE TITLE
[Feature Request]: non-monolithic docker-compose / more deployment options

### ISSUE THREAD

**Issue by ayushin** [infiniflow/ragflow#3610]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In order to be able to create scalable deployments it would be great to have non-monolithic docker-compose with a single service (mysql, redis, minio, ragflow server, ragflow task manager, etc) per container rather then running them in a single container. This would unlock multiple deployment options from ansible to helm to terraform.

I believe this has to be initiated by the core team as to take care of multiple interdependencies and once done, somebody else can easily do ansible, helm and terraform

This will also solve #864

**Comment by yuzhichang** [comment]
@ayushin Currently each component runs in seperated container while all are menaged in a single compose file.
It requires all run on a single host.
Are you saying deploing them in multiple host with ansible? Actaully you can deploy ragflow dependencies(redis, mysql, es) with ansible, and only ragflow with docker.
