### ISSUE TITLE
[Bug]: 解析暂停删除后后台任务还在跑

### ISSUE THREAD

**Issue by kunkeji** [infiniflow/ragflow#3611]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

6a3f9bc

### RAGFlow image version

6a3f9bc

### Other environment information

```Markdown
使用源码启动方式执行的
```

### Actual behavior

首先在知识库上传一个较大的txt文档，我上传的大概是6M的文字小说，然后开始解析，状态显示Task is queued...且没执行解析前暂停并删除这个文件，过一会后台任务就会持续解析，请求接口

### Steps to reproduce

```Markdown
首先在知识库上传一个较大的txt文档，我上传的大概是6M的文字小说，然后开始解析，状态显示Task is queued...且没执行解析前暂停并删除这个文件，过一会后台任务就会持续解析，请求接口
```

**Comment by maojum** [comment]
I have encountered the same problem. Have you solved it？

**Comment by 0zxq0** [comment]
我也有这个问题
