### ISSUE TITLE
[Question]: Answering randomly when there is no knowledge in the knowledge base

### ISSUE THREAD

**Issue by liguoyu666** [infiniflow/ragflow#3612]
### Describe your problem

the llm first answers question about the lack of relevant knowledge in the knowledge base, but later it still answers some irrelevant content
![微信截图_20241124154836](https://github.com/user-attachments/assets/38c5938b-a1fc-462c-812f-0f17fa324d0f)

**Comment by KevinHuSh** [comment]
You need modify the prompt if no KB is involved.

**Comment by liguoyu666** [comment]
> You need modify the prompt if no KB is involved.

Thank you
