### ISSUE TITLE
[Question]: Txt parsed as garbled code

### ISSUE THREAD

**Issue by liguoyu666** [infiniflow/ragflow#3613]
### Describe your problem

Only one txt parsed as garbled code
![微信截图_20241124155707](https://github.com/user-attachments/assets/6a6cbf7b-d7c6-4f66-a4af-4ecebcaf9728)
[三国演义.txt](https://github.com/user-attachments/files/17892453/default.txt)

**Comment by KevinHuSh** [comment]
Fixed. Pull the dev version of image.
