### ISSUE TITLE
[Bug]: 聊天配置——助理设置——助理头像上传后无法正常显示

### ISSUE THREAD

**Issue by ysyx2008** [infiniflow/ragflow#362]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

e5a5b82

### Other environment information

```Markdown
默认docker安装
```

### Actual behavior

聊天配置——助理设置——助理头像上传后无法正常显示，如下图（上传JPG文件，可正常预览）：

![图片](https://github.com/infiniflow/ragflow/assets/11251894/e9768c3f-f23d-4d3e-80cf-0ede7362d4da)

### Steps to reproduce

```Markdown
重复上传，错误依旧。
```

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question: 
Please execute the following SQL:

    alter table knowledgebase modify avatar longtext;
    alter table user modify avatar longtext;
    alter table dialog modify icon longtext;
