### ISSUE TITLE
[Question]: Parameters of retrieval API doesn't work

### ISSUE THREAD

**Issue by cuihangrui** [infiniflow/ragflow#3621]
### Describe your problem

![image](https://github.com/user-attachments/assets/9c5779e6-08ea-4f36-b3d9-c4b324496138)
检索数据块，已经根据http_api中设置了分页和每个块数参数，搜索的没有生效
![image](https://github.com/user-attachments/assets/6aab2e4e-720a-418d-ac8b-a438d767052d)

**Comment by Feiue** [comment]
What ‘s your version? I don't have this problem.

**Comment by JinHai-CN** [comment]
@cuihangrui If your issue isn't resolved, please re-open it.
