### ISSUE TITLE
[Bug]: Expected version index: 0.5.0.dev5, connecting version: 0.5.0.dev2

### ISSUE THREAD

**Issue by pan003** [infiniflow/ragflow#3645]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

3df1663e

### RAGFlow image version

3df1663e(v0.14.0)

### Other environment information

```Markdown
root@llmdev:~/llm/ragflow-dev20241126# sh printEnvironment.sh
/usr/bin/docker
printEnvironment.sh: 46: python: not found
Current Repo: ragflow-dev20241126
Commit Id: 3df1663e
Operating system: Ubuntu 22.04 (Kernel version: 6.8.0-49-generic)
CPU Type: x86_64
Memory:
Docker Version: 24.0.5,
Python Version:
```

## Upgrade to v0.14.0, user login failed.
<img width="758" alt="image" src="https://github.com/user-attachments/assets/ea295940-8364-40c7-98cb-5d275e92dba7">

## logs
2024-11-26 04:24:17,270 WARNING  415 (2004, 'Expected version index: 0.5.0.dev5, connecting version: 0.5.0.dev2'). Waiting Infinity IP: infinity, Port: 23817 to be healthy.
Exception ignored in: <function ThriftInfinityClient.__del__ at 0x79534985f520>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/infinity/remote_thrift/client.py", line 35, in __del__
    if self._is_connected:
AttributeError: 'ThriftInfinityClient' object has no attribute '_is_connected'
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x795340da0160>
Traceback (most recent call last):

## .env settings
<img width="511" alt="image" src="https://github.com/user-attachments/assets/d272ca12-7d62-43a9-ba09-34512949cd82">
<img width="341" alt="image" src="https://github.com/user-attachments/assets/547d9582-6879-4b8b-bd89-014f9d608e5d">

### Expected behavior

Users can log in normally.

### Steps to reproduce

```Markdown
git clone the latest code.
Modify the .env file, DOC_ENGINE to infinity and RAGFLOW_IMAGE to infiniflow/ragflow:dev
docker compose up
```

**Comment by yuzhichang** [comment]
@pan003 Update your code workspace to the latest.

**Comment by pan003** [comment]
The latest code has been updated, but the login still reports an error.
Commit Id: b6f3f15f
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/69e171e0-28e5-439d-8fa8-d90c08b11e90">
