### ISSUE TITLE
[Bug]: Dataset chunk list is empty

### ISSUE THREAD

**Issue by huangbaichao** [infiniflow/ragflow#366]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

ragflow:v1.0

### Commit ID

ragflow:v1.0

### Other environment information

```Markdown
Applicable to docker deployment, the version is: image: infiniflow/ragflow:v1.0
```

### Actual behavior

When adding a file to the dataset, the file is selected for table analysis. After the analysis is completed, the number of chunks is displayed, but when the file is clicked to enter the chunk list, the list is empty.
<img width="2159" alt="image" src="https://github.com/infiniflow/ragflow/assets/9191067/2ee2ec09-06ab-4012-b050-81d739179587">
<img width="2186" alt="image" src="https://github.com/infiniflow/ragflow/assets/9191067/cf23c2e0-453d-4de3-94a1-92e92333a665">

### Steps to reproduce

```Markdown
This problem may occur after passing in multiple xlsx files.
```

**Comment by KevinHuSh** [comment]
> empty

Is this locally deployed?

**Comment by KevinHuSh** [comment]
Could you share  a sample of your file?
Let me debug.

**Comment by huangbaichao** [comment]
> Could you share a sample of your file? Let me debug.

I will update to the latest version to verify if the problem still exists, thank you. Attached is the sheet that I have trouble using.
[苹果电池信息表AppleMacbookBatteryInfo.xlsx](https://github.com/infiniflow/ragflow/files/15011527/AppleMacbookBatteryInfo.xlsx)
