### ISSUE TITLE
[Question]: When the front-end web runs build through npm, the compiled file will report an error after being uploaded to the server.

### ISSUE THREAD

**Issue by kunkeji** [infiniflow/ragflow#3669]
### Describe your problem

前端web通过npm run build编译的文件在上传到服务器后会报错，前端默认接口是9222，我是用内网穿透绑定127.0.0.1:9222页面可以正常访问，但是请求登录接口会报404，通过npm run dev生成的链接反向代理就不会，这是为什么呢？

**Comment by cike8899** [comment]
The built code is proxied through nginx, while the development environment is proxied through the umirc file

**Comment by kunkeji** [comment]
Thank you very much, I feel annoyed because of this thing, I will follow this method to try
