### ISSUE TITLE
[Bug]:  Container ragflow-server  Starting Error (CN-oc9 yaml file) 

### ISSUE THREAD

**Issue by neoliuhua** [infiniflow/ragflow#3678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

no

### RAGFlow image version

dev-slim & 0.14.0

### Other environment information

```Markdown
Ubuntu 24.04.1 amd64,docker 27.0.0 or 26.0.0 (both tested).

Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:17:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:48 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.23
  GitCommit:        57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Actual behavior

 Container ragflow-server  Starting
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/neo/ragflow/docker/service_conf.yaml" to rootfs at "/ragflow/conf/service_conf.yaml": create mount destination for /ragflow/conf/service_conf.yaml mount: cannot mkdir in /var/lib/docker/overlay2/4f624f9fd314d685dd82cd96ae34c0f26411e651879ff6d2bf30e78d131bde2e/merged/ragflow/conf/service_conf.yaml: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

I checked the path in local machine:
neo@win:~/ragflow/docker$ ll
drwxr-xr-x  5 root root 4096 11月 27 13:38 ./
drwxr-xr-x 16 root root 4096 11月 26 20:04 ../
-rw-r--r--  1 root root  924 11月 26 20:04 docker-compose-admin-tool.yml
-rw-r--r--  1 root root 3342 11月 26 20:04 docker-compose-base.yml
-rw-r--r--  1 root root  767 11月 26 20:04 docker-compose-CN-oc9.yml
-rw-r--r--  1 root root  925 11月 26 20:04 docker-compose-gpu-CN-oc9.yml
-rw-r--r--  1 root root  855 11月 26 20:04 docker-compose-gpu.yml
-rw-r--r--  1 root root  952 11月 26 20:04 docker-compose.yml
-rwxr-xr-x  1 root root  841 11月 26 20:04 entrypoint.sh*
-rw-r--r--  1 root root 5096 11月 27 13:38 .env
-rw-r--r--  1 root root 5048 11月 27 13:32 .env-bak
-rwxr-xr-x  1 root root 2631 11月 26 20:04 init-kibana.sh*
-rw-r--r--  1 root root   53 11月 26 20:04 init.sql
-rw-r--r--  1 root root 2733 11月 26 20:04 launch_backend_service.sh
drwxr-xr-x  2 root root 4096 11月 26 20:04 nginx/
drwxr-xr-x  2 root root 4096 11月 26 22:56 ragflow-logs/
-rw-r--r--  1 root root 7045 11月 26 20:04 README.md
drwxr-xr-x  2 root root 4096 11月 26 22:56 service_conf.yaml/

The last line is a directory, not a file, and mount error on it.

### Steps to reproduce

```Markdown
docker compose -f docker-compose-CN-oc9.yml up  -d
```

**Comment by KevinHuSh** [comment]
Pull the latest code too.

**Comment by neoliuhua** [comment]
> Pull the latest code too.

docker compose -f docker-compose-CN-oc9.yml up  -d 

will cause this error, while 

docker compose -f docker-compose.yml up  -d

worked well.

**Comment by KevinHuSh** [comment]
Fixed. Pull the latest code.

**Comment by KevinHuSh** [comment]
Fixed. Pull the latest code.
