### ISSUE TITLE
[Question]: One Chunk only limit?

### ISSUE THREAD

**Issue by Snify89** [infiniflow/ragflow#3693]
### Describe your problem

I have a (fairly large) document, which has been chunked in one piece.
When using this (only) one chunk in the chat - the chunk is truncated (I can see it in the lightbulb symbol).
Is this one chunk really truncated (or just visually limited/truncated)? 

Are there any settings/limits for the one chunk template (Output size/lenght?!) 
I tried to increase the max token when adding ollama but no luck/success.

Thank you in advance for answering my question(s) :)

**Comment by KevinHuSh** [comment]
Every LLM has context window size. So, that's why we need to chunk a file into pieces.
I guess the  chunk token size exceed the content length limitation of the chosen LLM.

**Comment by Snify89** [comment]
> Every LLM has context window size. So, that's why we need to chunk a file into pieces. I guess the chunk token size exceed the content length limitation of the chosen LLM.

Thank you for the response/answer. 
I will look further into it and let you know, if there are still any issues.
