### ISSUE TITLE
[Question]: Web Crawler: how to past data to url?

### ISSUE THREAD

**Issue by isthaison** [infiniflow/ragflow#3694]
### Describe your problem

Web Crawler: how to past data to url? 
![image](https://github.com/user-attachments/assets/212cd31a-13c2-4b93-a10a-ec7d0effd063)

**Comment by KevinHuSh** [comment]
What about using 'invoke' component?

**Comment by isthaison** [comment]
I want to scrape google data through this node. instead of using api. I use https://www.google.com/search?q={data search}
