### ISSUE TITLE
[Bug]: 3097

### ISSUE THREAD

**Issue by Shidongxu** [infiniflow/ragflow#3697]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

3097

### RAGFlow image version

0.14.0slim

### Actual behavior

服务器重启后。infinitf起不来了。
以下为报错信息
![image](https://github.com/user-attachments/assets/7c24fd5d-8840-45a5-a73e-f46d9439760a)
![image](https://github.com/user-attachments/assets/364b8461-1ffd-41fa-a97b-afa4782b374d)

### Steps to reproduce

```Markdown
重启服务器后。
```

**Comment by JinHai-CN** [comment]
What is the mean of 3097? error code, commit id?

**Comment by JinHai-CN** [comment]
Please also attach the log file, which is located in /var/infinity/log/infinity.log

**Comment by yuzhichang** [comment]
@Shidongxu any update?
