### ISSUE TITLE
[Bug]: No context in Agent API

### ISSUE THREAD

**Issue by kunkeji** [infiniflow/ragflow#3699]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

0.14.0

### RAGFlow image version

--

### Actual behavior

在使用api调用agent应用时对话没有引用上下文，agent的流程测试是有上下文的，我在数据库中查找到的message是有上下文的，但是没有引用，并且数据库中保存的聊天记录没有user_id,我认为可以通过api_key获取用户的id进行保存，或者参数中传递自定义的userid。另外我在数据库中发现相同的会话id可以保存很多条不同的对话记录，我认为这也是一个BUG，希望能够尽快解决，谢谢

### Steps to reproduce

```Markdown
我处理接口的流程是先创建一个会话id，然后调用相关的接口传入对应的会话id，我可以肯定流程是没错的。
```

**Comment by KevinHuSh** [comment]
The references are stored in canvas DSL.

**Comment by kunkeji** [comment]
DSL中记录的是在调试画布中的消息，并不是用户聊天的消息，已经修复并提交
