### ISSUE TITLE
[Feature Request] RAGFlow, add metadata to the documents and chunks

### ISSUE THREAD

**Issue by KevinHuSh** [infiniflow/ragflow#3701]
### Discussed in https://github.com/orgs/infiniflow/discussions/3668

<div type='discussions-op-text'>

<sup>Originally posted by **devMls** November 26, 2024</sup>
Maybe this feature is present but I don't find that.

I miss can specify descriptions arround a document, for example in excels, write something like stoks from 2022 or stoks from 2024

In adittion in my case, I wish tell, this documents include corrections for this other. In laws something publish a correction for previous documents.

Other data like publish date can be usefull.

If this metadata is present in the chunks, the knowege for the LLM will be more productive.</div>

**Comment by yingfeng** [comment]
duplicate with #3690
