### ISSUE TITLE
[Bug]: Field types of avatars in the database

### ISSUE THREAD

**Issue by kunkeji** [infiniflow/ragflow#3730]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

c2ed5ba9(v0.14.0~37)

### RAGFlow image version

c2ed5ba9(v0.14.0~37)

### Actual behavior

text的最大字节只有65535个字节，并且上传的图片会以base64的形式保存，但是有些色彩比较丰富的格式比较大的会超出这个最大值，导致保存到头像的base64记录不全，无法显示完整的头像，我的建议是要么把字段改成longtext，要么做文件大小的限制，或者保存头像的路径而不是base64

### Steps to reproduce

```Markdown
text的最大字节只有65535个字节，并且上传的图片会以base64的形式保存，但是有些色彩比较丰富的格式比较大的会超出这个最大值，导致保存到头像的base64记录不全，无法显示完整的头像，我的建议是要么把字段改成longtext，要么做文件大小的限制，或者保存头像的路径而不是base64
```

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for communication.

**Comment by kunkeji** [comment]
The maximum byte size of text is only 65535 bytes, and uploaded images will be saved in base64 format. However, some colorful and formatted images may exceed this maximum value, resulting in incomplete base64 records saved to the avatar and unable to display the complete avatar. My suggestion is to either change the field to longtext, limit the file size, or save the avatar path instead of base64

**Comment by kunkeji** [comment]
I still can't use longtext because it can cause resource waste and page lag. I suggest saving it in the form of a URL link instead
