### ISSUE TITLE
[Bug]: TypeError: Huqie.qie() missing 1 required positional argument: 'line'

### ISSUE THREAD

**Issue by steven140811** [infiniflow/ragflow#374]
### Is there an existing issue for the same bug?

- [ ] I have checked the existing issues.

### Branch name

main

### Commit ID

null

### Actual behavior

I want to try the code for the PDF text parsing section locally, and I have written an example of calling pdf_parser. py
like this:
parser = HuParser()
pdf_path = r"d:\\xxx\\xxxx\\xxx.pdf"
result, tables = parser(pdf_path, need_image=True, zoomin=3, return_html=False)

When I execute the code, the following error is reported:
![ragFlow_issue_01](https://github.com/infiniflow/ragflow/assets/63778907/17ad4372-895d-4b46-ab53-1646db80c71b)
Then I debugged the code and found some strange situations：
When executing the steps shown in the figure, it should have jumped into the huqie. qie() function, but it did not.
![ragFlow_issue_02](https://github.com/infiniflow/ragflow/assets/63778907/9f7c356b-4987-4454-ac8d-b4c8935b9a33)
![ragFlow_issue_03](https://github.com/infiniflow/ragflow/assets/63778907/41240664-4599-4da8-ae38-7d8e044cc02b)

### Steps to reproduce

```Markdown
As shown above.
```

**Comment by steven140811** [comment]
pdf file : [汽车车身设计（下卷）：系统设计.pdf.pdf](https://github.com/infiniflow/ragflow/files/14986558/pdf.pdf)

**Comment by steven140811** [comment]
page_from=0,page_to=5

**Comment by KevinHuSh** [comment]
I wonder that the code you execute and the code you see is not consistent.
