### ISSUE TITLE
[Bug]: 这个库想本地跑一下，它依赖的python版本是多少

### ISSUE THREAD

**Issue by papandadj** [infiniflow/ragflow#375]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3444

### Actual behavior

我想在本地跑下这个项目，但是安装依赖的时候，开始用3.10版本，显示必须大于等于3.9 小于310。然后用3.9版本，显示必须大于3.10，我应该使用哪个python版本

### Steps to reproduce

```Markdown
无
```

**Comment by KevinHuSh** [comment]
3.11

**Comment by DAAworld** [comment]
你本地跑起来了嘛？

**Comment by JinHai-CN** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊
