### ISSUE TITLE
[Question]: Agent page cannot load the created agent when update to v0.14.1

### ISSUE THREAD

**Issue by RoboSimonLee** [infiniflow/ragflow#3752]
### Agent page cannot load the created agent when update to v0.14.1

After I updated the version, I used infinity to execute the KB parsed by es, which resulted in an error in the response when the Agent referenced the KB. Then I used infinity to reparse the knowledge base files and get the correct response, but after a while, the Agent page could not load the Agent I created, Why?Feels like I trapped in a small BUG.
![image](https://github.com/user-attachments/assets/e19b6b13-244c-4ace-b96f-6887a0b4a03d)
Also, I deleted the container and redeployed it, and it still retained my previous configuration and uploaded files. Where are they stored? Thanks a lot

**Comment by RoboSimonLee** [comment]
![image](https://github.com/user-attachments/assets/436f0d67-071d-41f2-b9d6-339296ba3443)
here's the task log

**Comment by KevinHuSh** [comment]
There're stored in docker volumn.
`docker compose down -v` is gona remove them all.

**Comment by RoboSimonLee** [comment]
Thanks for your answer, It's very helpful ! But the problem doesn't seem to be accidental.. In the T2S sample under version v0.14.1-slim, after I conducted several rounds of dialogue queries, the above problem appeared again. Dont' know what is the cause?
