### ISSUE TITLE
[Question]: Cannot Login with the previous account after restart docker

### ISSUE THREAD

**Issue by southkorea2013** [infiniflow/ragflow#3753]
### Describe your problem

Hi Experts,

My Env is: Apple silicon M3, macOS 15.1 . I use the following steps to install RagFlow.
```
conda create -n ragflow python=3.12 -y
conda activate ragflow
git clone https://github.com/infiniflow/ragflow.git
cd ragflow/
pip install huggingface-hub nltk
python download_deps.py
docker build --build-arg ARCH=arm64 -f Dockerfile.slim -t infiniflow/ragflow:dev-slim .
docker compose -f ./docker/docker-compose.yml -p ragflow up -d
```
It works smoothly, I register a new account, then create a knowledge base repository. But If i rebounce the service with the following commands:
```
docker compose -f ./docker/docker-compose.yml -p ragflow down -v
docker compose -f ./docker/docker-compose.yml -p ragflow up -d

```
I cannot login with the previous created account. 
<img width="381" alt="image" src="https://github.com/user-attachments/assets/0f2fbfce-0207-458a-9748-445656da4967">

Please shed some light on it. 

Thanks,
Nan

**Comment by Snify89** [comment]
You have added the "-v" parameter when you used docker compose down.
This will also delete all associated volumes, exactly where your data is.
To "shutdown" your container without data loss, ommit the -v parameter.
