### ISSUE TITLE
[Question]: ✘ redis Error        Get "https://registry-1.docker.io/v2/": dial tcp 162.220.12.226:443: i/o timeout

### ISSUE THREAD

**Issue by lzg553665176** [infiniflow/ragflow#3761]
### Describe your problem

docker版本
Version:    26.1.4
Docker Compose version v2.27.1

docker info:
....
Registry Mirrors:
  https://docker.m.daocloud.io/
  https://registry.cn-hangzhou.aliyuncs.com/
  https://registry.docker-cn.com/
  https://dockerpull.com/
  https://dockerproxy.cn/
 Live Restore Enabled: false

docker compose -f docker-compose.yml up -d
报错：
[+] Running 17/14
 ⠦ mysql [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] Pulling                                                                                                                                                        110.7s 
 ✘ redis Error        Get "https://registry-1.docker.io/v2/": dial tcp 162.220.12.226:443: i/o timeout                                                                                110.7s 
 ⠦ es01 [⣿⣿⣿⣿⡀⣿⣿⣿⣿⣿] 204.2MB / 747.8MB Pulling                                                                                                                                        110.7s 
 ⠦ ragflow [⣿⣿⣿⣿⣿⡀⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] Pulling

Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 162.220.12.226:443: i/o timeout

已经设置国内源了，但是还是报错

**Comment by JinHai-CN** [comment]
Obviously, you are pulling mysql docker image from official Docker hub site. You might need to resolve your network issue or use other docker mirrors.

**Comment by lzg553665176** [comment]
我已经设置源了，docker info已经生效

docker info:
....
Registry Mirrors:
https://docker.m.daocloud.io/
https://registry.cn-hangzhou.aliyuncs.com/
https://registry.docker-cn.com/
https://dockerpull.com/
https://dockerproxy.cn/
Live Restore Enabled: false

**Comment by lzg553665176** [comment]
现在已经可以下载了，我不确定是不是这样的配置生效：
我最后设置意图是要走宿主的代理，可能是这个产生效果，可以尝试
"registry-mirrors": [
	"https://docker.m.daocloud.io",
	"https://registry.cn-hangzhou.aliyuncs.com", 
	"https://registry.docker-cn.com",
	"https://dockerpull.com",
	"https://6kx4zyno.mirror.aliyuncs.com",
	"https://dockerproxy.cn"
  ],
  "dns" : [
    "114.114.114.114",
    "8.8.8.8"
  ],
  "proxies": {
    "http-proxy": "http://192.168.16.104:7890",
    "https-proxy": "http://192.168.16.104:7890"
  }

**Comment by WaterDrop-EarthDivision** [comment]
对于每个出现这个错误的人，都可以通过这种方式进行下载：
For everyone who is experiencing this error, it can be downloaded in this way:

## 1.寻找一个dockerhub镜像源例如dockerpull.org([更多的源](https://github.com/dongyubin/DockerHub))

## 2.寻找文件中的单个docker容易并手动进行下载，例如:
![image](https://github.com/user-attachments/assets/898afda2-8227-495c-9ace-d87642d45091)
![image](https://github.com/user-attachments/assets/dacceb8e-fc71-4262-94af-16139e258f84)

寻找其中的image的内容，其中就是源docker文件。如果是{$....}，的话就去.env中寻找版本，都能找到的。

## 3.将其中的docker文件单独下载，在这里就是:
```bash
docker pull dockerpull.org/infiniflow/infinity:v0.5.0-dev5
docker pull dockerpull.org/edwardelric233/ragflow:oc9
docker pull dockerpull.org/minio/minio:RELEASE.2023-12-20T01-00-02Z
```
还有一些自己找去

## 4.上面下载的文件名字不对 名字前面有dockerpull.org。要使用docker tag进行重新命名
```bash
docker tag dockerpull.org/infiniflow/infinity:v0.5.0-dev5 infiniflow/infinity:v0.5.0-dev5
docker tag dockerpull.org/edwardelric233/ragflow:oc9 edwardelric233/ragflow:oc9
docker tag dockerpull.org/minio/minio:RELEASE.2023-12-20T01-00-02Z minio/minio:RELEASE.2023-12-20T01-00-02Z
```
一定要注意名字要对应 不然也会报错的

之后按照官方教程来就可以

ps: 如果这种方法还不行的话，可以使用能科学上网的计算机先下载下来，之后通过docker save打包成tar文件，再将打包文件转移docker load解压也可以。
