### ISSUE TITLE
[Question]: Use llm to rewrite chunks on knowledge base

### ISSUE THREAD

**Issue by isthaison** [infiniflow/ragflow#3766]
### Describe your problem

When using pdf ocr file, the result is not true to reality, for example spelling mistakes, missing words, use llm to rewrite the sentence to make it more complete

**Comment by isthaison** [comment]
Can we build a feature right here? 
![image](https://github.com/user-attachments/assets/4868aec9-dff8-436a-9384-34a3cc7e06be)

**Comment by Simpler-Dz** [comment]
I suggest adding a feature that allows LLM (Large Language Model) to rewrite parsed content blocks with customizable prompt templates. This functionality is truly essential and would be very valuable. Thank you
