### ISSUE TITLE
[Bug]: Can't update dataset_ids with PUT /api/v1/chats/{chat_id}

### ISSUE THREAD

**Issue by Match-Yang** [infiniflow/ragflow#3772]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

v0.14.1

### RAGFlow image version

v0.14.1

### Actual behavior

I can't update the dataset_ids when I try to update chat assistant with PUT /api/v1/chats/{chat_id}. But I can update the name or llm or other options.

I am very certain that the dataset_ids are correct, and they were all created by me.

### Steps to reproduce

```Markdown
Just request with dataset_ids param.

Here is what I sent:

curl --request PUT \
     --url https://{server}/api/v1/chats/20bff9caa8c611ef9dc40242ac120003 \
     --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer My-API-Key' \
     --data '
     {
          "name":"ZH Android",
          "dataset_ids":["33fcd080a8a311ef93f60242ac120003","a616581ca8a311efbed70242ac120003","033ab2aeaf1611efba670242ac120006"]
     }'

error output:
{"code":102,"message":"You don't own the dataset 33fcd080a8a311ef93f60242ac120003"}
```

**Comment by Match-Yang** [comment]
I'm running ragflow with docker image. When can I get this update?

**Comment by Feiue** [comment]
Run `docker exec -it ragflow-server /bin/bash`, apply the modification, then execute `exit` and `docker restart ragflow-server`.
