### ISSUE TITLE
[Question]: Fail to upgrade RAGFlow

### ISSUE THREAD

**Issue by junchenfeng** [infiniflow/ragflow#3782]
### Describe your problem

我通过计算巢部署了Raglfow社区版，发现是7月的老版本。我手动升级到最新dev，已经完成了docker compose pull 和 docker compose up。但是当我启动后发现

1. 反复报infinity unhealthy。我已经将docker/.env的配置改为`DOC_ENGINE=${DOC_ENGINE:-infinity}`
```2024-12-02 00:31:41,611 ERROR    125 failed to resolve sockaddr for infinity:23817
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 126, in open
    addrs = self._resolveAddr()
  File "/ragflow/.venv/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 37, in _resolveAddr
    return socket.getaddrinfo(self.host,
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2024-12-02 00:31:41,611 WARNING  125 failed to resolve sockaddr for infinity:23817. Waiting Infinity IP: infinity, Port: 23817 to be healthy.
```

2. 通过http页面注册register接口502，错误为

```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)Understand this errorAI
index.tsx:54 Failed: TypeError: Cannot read properties of null (reading 'data')
    at login-hooks.ts:68:15
```

**Comment by JinHai-CN** [comment]
1. Host name can't be resolve correctly
Have you try to use latest docker compose file?

2. @cike8899

**Comment by cike8899** [comment]
2. The interface returns 502. Please check whether it is an interface proxy problem.

**Comment by Snify89** [comment]
Infinity is not (yet) working with latest v0.14.1 release.
I think this has been fixed right after this release.

**Comment by junchenfeng** [comment]
I checked out tag 0.14.1 and used its docker compose file.

Btw, if you guys maintained "计算巢" service, can you upgrade to a later version? it is still in july.

**Comment by yuzhichang** [comment]
@junchenfeng RAGFlow doesn't maintain "计算巢" service. If tag 0.14.1 doesn't work, please try the nightly version according to README.
