### ISSUE TITLE
[Question]: Why can't the paper method be used to parse documents in infinity? Setting DOC-INGINE to elasticsearch can solve this problem.

### ISSUE THREAD

**Issue by waiking1970** [infiniflow/ragflow#3788]
### Describe your problem

When using the Infinity database, using the paper parsing method, it stopped running until 80% and kept starting to build the index. After upgrading to v0.14.1, the problem persisted. 
log:
raise InfinityException(res.error_code, res.error_msg)
infinity.common.InfinityException: (3024, "Column: authors_tks doesn't exist@src/storage/meta/entry/table_entry.cpp:1292")

**Comment by Snify89** [comment]
> ### Describe your problem
> When using the Infinity database, using the paper parsing method, it stopped running until 80% and kept starting to build the index. After upgrading to v0.14.1, the problem persisted. log: raise InfinityException(res.error_code, res.error_msg) infinity.common.InfinityException: (3024, "Column: authors_tks doesn't exist@src/storage/meta/entry/table_entry.cpp:1292")

As far as I know, infinity is not yet quite supported/implemented in the latest version. 
Wait for the next release or clone/pull the latest files in the repository and build it yourself.

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/ragflow/pull/4054
