### ISSUE TITLE
[Feature Request]: Optimize the batch file upload function

### ISSUE THREAD

**Issue by ysyx2008** [infiniflow/ragflow#380]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
When I upload over 900 PDF documents at once, the browser freezes for a long time (the latest version of Firefox). 

When uploading 60 files at once, all documents will be started together instead of automatically starting parsing batch by batch.
```

### Describe the feature you'd like

Support uploading thousands of documents at once and optimize the parsing process.

**Comment by KevinHuSh** [comment]
We have API for files uploading to fullfill this feature.
