### ISSUE TITLE
[Bug]: After applying agent  DB Assistant template，created AGENT can't be found any more

### ISSUE THREAD

**Issue by liuman632** [infiniflow/ragflow#3805]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

无

### RAGFlow image version

无

### Actual behavior

当配置完知识库和模型后，点击运行查询一次数据表内容后，再刷新agent页面不显示已经创建过的agent

### Expected behavior

已经创建的agent正常显示

### Steps to reproduce

```Markdown
新建DB Assistant模版的agent，配置完知识库、大模型以及数据库连接，进行提问正常，再次刷新agent页面，没有任何显示，找不到已经创建的agent
```

**Comment by KevinHuSh** [comment]
Could you reproduce the scenario again?
I can't reproduce it here.

**Comment by liuman632** [comment]
> 你能重现一下这个场景吗？ 我这里无法重现。

重现步骤里我有描述的，然后现在我agent页面是直接不显示的，重新创建一个agent也不显示，但是数据库是有的

**Comment by liuman632** [comment]
如果重新换一个空的mysql数据库，重新注册和配置完agent是显示的，但是连接上mysql后用ollama模型提问后，访问agent页面就会刷新一会然后没有任何显示，后端有返回查到数据

**Comment by liuman632** [comment]
这或许和前端的代码更改有关，我看到15号balibabu的提交和这个相关

**Comment by liuman632** [comment]
![微信图片_20241203095946](https://github.com/user-attachments/assets/bf40d8fe-a273-4498-a05f-e09845bcc3a4)
![微信图片_20241203143143](https://github.com/user-attachments/assets/9259a098-2776-4028-95d9-b6ff71e2bb93)

**Comment by liuman632** [comment]
![微信图片_20241203143500](https://github.com/user-attachments/assets/0c08fe02-b3a5-46f2-9fd0-9dfa9ed80c40)
![微信图片_20241203143453](https://github.com/user-attachments/assets/24b07388-9753-4e1e-8afb-d847d8cda4c0)

**Comment by liuman632** [comment]
> 你能重现一下这个场景吗？ 我这里无法重现。

![image](https://github.com/user-attachments/assets/919fa78b-ac7b-456c-9fb9-f75c455b6c19)

**Comment by liuman632** [comment]
问题仍然存在，今天进行了多次查询后agent又不显示了，这个bug我这边还是一直出现的，很不稳定

**Comment by liuman632** [comment]
> 你能重现一下这个场景吗？ 我这里无法重现。
现在创建完新的agent，也直接不显示了
![image](https://github.com/user-attachments/assets/df8cbfe6-2776-4830-9309-435c683eaae9)
![image](https://github.com/user-attachments/assets/9c0caf49-d0d4-426c-902f-5c99e37b2691)

**Comment by liuman632** [comment]
> Could you reproduce the scenario again? I can't reproduce it here.

请问这个问题是否还不能重现，我这边目前依然存在的
