### ISSUE TITLE
[Question]: Analyzer on es

### ISSUE THREAD

**Issue by guijuzhejiang** [infiniflow/ragflow#3806]
### Describe your problem

I would like to know why es uses whitespace analyzer when analysing documents, instead of analyzer such as ik, which can parse Chinese.

**Comment by KevinHuSh** [comment]
We tokenize Chinese outside of ES. And also, we can assign term weight to terms while querying.

**Comment by guijuzhejiang** [comment]
@KevinHuSh Yes, I see in term_weight.py what are doing with split words outside of es and attaching weights to them. Not saying this is bad, just wondering why don't just use the existing Chinese analyzer in es, after all, it's simpler. Is it because split words outside es can arbitrarily modify the split word dictionary (huqie.txt)

**Comment by KevinHuSh** [comment]
The tokenization procedure of indexing and querying with term weight should be consistant.
So, both outside or both inside.
Otherwise, what you mention about huqie is another reason that we can manipulate tokenizer freely.

**Comment by guijuzhejiang** [comment]
Thanks.
