### ISSUE TITLE
[Question]: ValueError: not find model file path /root/.cache/huggingface/hub/models--InfiniFlow--deepdoc/snapshots/be0c1e50eef6047b412d1800aa89aba4d275f997/layout.onnx

### ISSUE THREAD

**Issue by hanxl1** [infiniflow/ragflow#381]
### Describe your problem

上传pdf，报没有这个文件

**Comment by KevinHuSh** [comment]
If you do not have the internet connection, or are unable to ping hf-mirror.com, we recommend that you manually download the resource from [InfiniFlow/deepdoc](https://huggingface.co/InfiniFlow/deepdoc) into local folder, say, ~/deepdoc. Then, change the docker-compose.yml, add a volumes, like - ~/deepdoc:/ragflow/rag/res/deepdoc
