### ISSUE TITLE
[Question]: how large it suport when  uploading local files for once

### ISSUE THREAD

**Issue by cqray1990** [infiniflow/ragflow#3813]
### Describe your problem

 400M files raise "The total size of the files uploaded at once is too large"

**Comment by KevinHuSh** [comment]
The following places define the maximun uploading file size.

![image](https://github.com/user-attachments/assets/290e6689-2327-45cd-bb81-dd5227e9419b)
![image](https://github.com/user-attachments/assets/812f04a1-6cf6-4fe4-bcd0-6d6829541489)

**Comment by JinHai-CN** [comment]
Please check https://ragflow.io/docs/dev/faq#why-did-i-fail-to-upload-a-128mb-file-to-my-locally-deployed-ragflow @cqray1990
