### ISSUE TITLE
[Bug]: tasks executor is unable to get a file from MINIO

### ISSUE THREAD

**Issue by alexff77** [infiniflow/ragflow#3817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

834c4d8

### RAGFlow image version

 v0.14.1 834c4d8

### Other environment information

```Markdown
Updated from 0.13
minio
postgres
```

### Actual behavior

Hi 
after upgrading I have an issue with chinking.
Existing KB work fine. I can also upload and download new and existing files.

When I try to process MD or HTML file I get an error:
```
Page(1~100000001): Start to parse.
Page(1~100000001): [ERROR]Internal server error while chunking: [Errno 2] No such file or directory: 

```
I see MINIO error in logs and in MINIO status
S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /txtxtxtxt1, request_id: 180D7E13B64E2978, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: txtxtxtxt1.

Thank you!
![ScreenShot 2024-12-02 at 17 55 10@2x](https://github.com/user-attachments/assets/73257d5f-9d95-408e-a860-b06b953ded0a)
![ScreenShot 2024-12-02 at 18 01 30@2x](https://github.com/user-attachments/assets/176d5ddb-7080-4d15-a7a1-bebcc4758c33)

### Expected behavior

Chunking should work since I'm able to upload files.

### Steps to reproduce

```Markdown
Updated to 0.14.1 from 0.13.0
upload a file
process file
```

**Comment by JinHai-CN** [comment]
1. The latest RAGFlow will show the version info. So, it looks your RAGFlow isn't the latest version.
2. I already try to upload a MD file into a knowledge base, no error.
3. Which chunking method do you choose?

**Comment by alexff77** [comment]
1. How else can I confirm this? Where is it getting version number from? Here is what I merged:
![ScreenShot 2024-12-03 at 08 48 28@2x](https://github.com/user-attachments/assets/6c120735-4b6e-4e0a-961e-b4e3f1b81c05)
2. I also can upload MD and html files and then download them as well. That seems to work fine.
3. I tried General, QA and Knowledge Graph, same error.
thanks!

**Comment by KevinHuSh** [comment]
I guess the password to Minio is inappropriate configured in service_config.ymal.

**Comment by alexff77** [comment]
It's strange, I can see all the files uploaded to minio and I can add more via app interface.
Seems like only the workers that processing chunks can't access minio.
Is this possible?
Thanks!

**Comment by alexff77** [comment]
Looks like we had two different auth parameters setup in 2 different way. Now it's fixed. Thank you.
