### ISSUE TITLE
[Bug]: api/apps/document_app.py - module `os` is not imported 

### ISSUE THREAD

**Issue by kratorado** [infiniflow/ragflow#382]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c344486aa098f6e611c4d656bc7b57419bbdf61b

### Actual behavior

api/apps/document_app.py, line 60

the commit changed 128 to `os.environ.get('MAX_FILE_NUM_PER_USER', 8192)` while module os is not imported, which will cause a `NameError: name 'os' is not defined`

### Steps to reproduce

```Markdown
uploading a local file triggers.
```

**Comment by nexussdad** [comment]
I've met it as well.

**Comment by ooooo-create** [comment]
it seems be fixed in #383
you can pull the latest version
