### ISSUE TITLE
[Bug]: Unable to add embedding model but can add chat model from same server

### ISSUE THREAD

**Issue by missedmyeye** [infiniflow/ragflow#3820]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

834c4d8, 49494d4

### RAGFlow image version

v0.14.1 slim, v0.14.0 slim

### Other environment information

```Markdown
Server:
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-1024-aws x86_64)

Model Server:
Models hosted on LiteLLM v1.46.0 https://github.com/BerriAI/litellm/releases/tag/v1.46.0
```

### Actual behavior

No issues with connecting chat models via OpenAI API Compatible connection, but when connecting embedding models on the same server, the following error is encountered:
```
hint : 102
Fail to access embedding model(BAAI/bge-m3___OpenAI-API).Fail
```
Input: 
Model type: embedding
Model name: BAAI/bge-m3
Base URL: https://SERVER_URL

When attempting to connecting, there is no sign of rejection:
```
2024-12-02 18:14:20,014 INFO     18 HTTP Request: POST https://<SERVER URL>/v1/embeddings "HTTP/1.1 200 OK"
2024-12-02 18:14:20,016 INFO     18 <IP ADDRESS> - - [02/Dec/2024 18:14:20] "POST /v1/llm/add_llm HTTP/1.1" 200 -
```

Embedding model is on `/v1/embeddings` endpoint. I have tried multiple iterations of the Base URL as well, with/without `https://` and `/v1`

I have also tried curl command to the embedding model from within the ragflow-server docker container, which receives an adequate response:
```
curl -H "Authorization: Bearer API_KEY"  \
--data '{"input":"Hello", "model":"BAAI/bge-m3"}' \
https://<SERVER_URL>/v1/embeddings
```
Response:
```
{
"model":"BAAI/bge-m3",
"data":[{"embedding":[<EMBEDDING>],"index":0,"object":"embedding"}],
"object":"list",
"usage":{"completion_tokens":0,"prompt_tokens":3,"total_tokens":3}
}
```

### Expected behavior

Addition of embedding model without issue, as per how chat models were added.

### Steps to reproduce

```Markdown
Spin up RAGFlow as per Quick Start instructions: https://ragflow.io/docs/dev/
Add chat models
Add embedding model
```
Enter docker container `ragflow-server`:
```
docker exec -it ragflow-server /bin/bash
```
Execute curl command as written in `Actual behavior`

**Comment by KevinHuSh** [comment]
Could you paste the full error message?
Fail to access embedding model(BAAI/bge-m3___OpenAI-API).Fail...

**Comment by missedmyeye** [comment]
May I check if there is another location I can access the full error message?
This is what I observed via the UI:
![image](https://github.com/user-attachments/assets/4ff3fe63-2c0c-48c7-9af5-56037562178f)
If accessing the ragflow-server container logs, it seems like it returns status code 200:
```
2024-12-04 17:56:59,271 INFO     17 HTTP Request: POST https://api.sea-lion.ai/v1/embeddings "HTTP/1.1 200 OK"
2024-12-04 17:56:59,273 INFO     17 192.168.224.6 - - [04/Dec/2024 17:56:59] "POST /v1/llm/add_llm HTTP/1.1" 200 -
```
