### ISSUE TITLE
[Bug]: The same question returned different answers through APIs and console

### ISSUE THREAD

**Issue by sven0219** [infiniflow/ragflow#3824]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

tag v0.14.1

### RAGFlow image version

v0.14.1

### Actual behavior

The same question, the answer I get through `/api/v1/chats/chat_id/completions` api is different from the answer directly obtained on the page.
The answers obtained on the page are clearly more in line with the requirements.
answers from api
![image](https://github.com/user-attachments/assets/4a12383c-a34a-489c-95f1-03ec46ac8e09)
answers from console
![image](https://github.com/user-attachments/assets/9426aab4-c8ae-4162-8dd9-2fe7832dc7b5)

### Expected behavior

get same answer from api and console

### Steps to reproduce

```Markdown
1. ask question though api `/api/v1/chats/chat_id/completions`
2. ask question though pages 
3. the answers are different
```

**Comment by Feiue** [comment]
No matter where the conversation takes place, they all call the same final interface. The issue might be caused by the settings of the large model or the assistant. You could try disabling the multi-turn conversation optimization option and see if it resolves the problem.

**Comment by sven0219** [comment]
Perhaps due to an error in the assistant configuration, I have recreated the assistant and now it returns the same answer.
Closing the issue

**Comment by SendDreams** [comment]
> No matter where the conversation takes place, they all call the same final interface. The issue might be caused by the settings of the large model or the assistant. You could try disabling the multi-turn conversation optimization option and see if it resolves the problem.

I also encountered a problem regarding multi-round conversations. If the multi-round conversation optimization is enabled, after conducting multiple conversations, no matter what question is asked subsequently, it directly returns an empty response. If the multi-round conversation optimization is disabled, the context of the conversation cannot be connected coherently
