### ISSUE TITLE
[Question]: v0.14 & v0.13problem( Upgrade & Agents)

### ISSUE THREAD

**Issue by RoboSimonLee** [infiniflow/ragflow#3827]
### Describe your problem

I updated the version to v0.14.1. When I use DB assistant, it gives basically correct responses, but the input and output of the component are no longer displayed, and when I click the agent page to view the component again, everything is gone. However, when I create a new component with the same name, it prompts a duplicate value, indicating that it still exists, but I can't see it.
<img width="1280" alt="3fc27b9b56063a9b7d155a07ec7058b" src="https://github.com/user-attachments/assets/4b52393e-1ede-4fd0-8c5a-1d95d68934bc">
<img width="1280" alt="614a9cc968268fac6e1a0ff3856042b" src="https://github.com/user-attachments/assets/f4670b7c-7d77-4df4-af79-20c9bd919895">
<img width="645" alt="6f9eb3c39c1cd963a7fd5d2a20d80e6" src="https://github.com/user-attachments/assets/fc1531e8-56ff-466f-9056-b2381c10016f">
<img width="1280" alt="cbdd6c08be34aa2773371165691161d" src="https://github.com/user-attachments/assets/9dcef3e1-0513-477a-821f-3ddbf47379e6">
<img width="1280" alt="3e97f82e269ba1db392085a584485d9" src="https://github.com/user-attachments/assets/9facfdbd-ec55-49fd-b26e-23a7052dfb95">
I tried to redeploy, and even redeployed my Docker and still had this problem. I also had this problem with dev-slim, and when I used v0.13.0, it told me that the service_config.yaml file could not be found. This is exactly the same as the problem raised by another friend I saw, but I couldn't pull the correct version to solve this problem. Here are my screenshots and task logs
![image](https://github.com/user-attachments/assets/a8c79677-91a1-4c1e-8da4-c19ac3a9565d)
I don't know if these two issues are related.Please help me, thank you

**Comment by RoboSimonLee** [comment]
[https://github.com/infiniflow/ragflow/issues/3572](url)
[https://github.com/infiniflow/ragflow/issues/3418](url)

**Comment by JinHai-CN** [comment]
Upgrade needs latest docker images and latest docker compose file which can be fetched from Github.

So, you can follow the upgrade guide:
https://github.com/infiniflow/ragflow/blob/main/docs/guides/upgrade_ragflow.mdx

I think it will resolve the service_config.yaml related issue.

**Comment by RoboSimonLee** [comment]
> Upgrade needs latest docker images and latest docker compose file which can be fetched from Github.
> 
> So, you can follow the upgrade guide: https://github.com/infiniflow/ragflow/blob/main/docs/guides/upgrade_ragflow.mdx
> 
> I think it will resolve the service_config.yaml related issue.

thanks a lot, but the issue still exist
<img width="1280" alt="db153d239dfaa7f94f0086899f1e125" src="https://github.com/user-attachments/assets/9b6fa9db-553a-4445-8668-f35ed03681d5">
<img width="1280" alt="a887218129df6b140c0ed857f9e27c2" src="https://github.com/user-attachments/assets/c88ba1c0-18a5-46f5-99f7-46c7f1530be7">
<img width="1280" alt="e3a0ef863d9de8bf18a5bc6cc53e8c9" src="https://github.com/user-attachments/assets/73a77967-bcf1-4571-9660-7c5a811238e6">
This only seems to happen when using DB_assistant

**Comment by KevinHuSh** [comment]
What about pulling the latest dev version of image?

**Comment by RoboSimonLee** [comment]
> What about pulling the latest dev version of image?

![image](https://github.com/user-attachments/assets/0c7a4b67-6862-4f57-8c50-2bb4c8ad215b)
Thanks for your suggestion, but I have tested all versions of slim(>=0.14 & dev) and the problem still exists.When I check the logs:
![image](https://github.com/user-attachments/assets/fec61d9d-5854-4bf7-b468-ef84c722c071)
Is the issue related to this?

**Comment by RoboSimonLee** [comment]
![image](https://github.com/user-attachments/assets/5f149407-ec20-481e-a0b4-cd23115767cb)
I tried the latest version, but it still doesn't work
