### ISSUE TITLE
Missing necessary system packages to install Python dependencies

### ISSUE THREAD

**Issue by scruel** [infiniflow/ragflow#3831]
### Describe your problem

For Debian/Ubuntu users:
If you meet errors like `KeyError: 'ICU_VERSION'`, execute:
```
apt install pkg-config libicu-dev
```

for erros like `fatal error: Python.h: No such file or directory`, execute:
```
apt install build-essential python3-dev
```

And you also need to install npm:
```
apt install npm
```

**Comment by Alixhan** [comment]
For centos 10 , How to fix？
