### ISSUE TITLE
[Bug]: Answers with links to information not parsing

### ISSUE THREAD

**Issue by devMls** [infiniflow/ragflow#3839]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

dont now

### RAGFlow image version

0.14.1

### Other environment information

```Markdown
docker swarm

voyageai embedding and reranking

openai GPT4o mini LLM
```

### Actual behavior

![image](https://github.com/user-attachments/assets/527dac86-e051-41f4-9cf9-8a3c47646b6e)

### Expected behavior

Link to proper information

### Steps to reproduce

```Markdown
ask something
```

**Comment by KevinHuSh** [comment]
I did not get it.
What needs to parse?

**Comment by rplescia** [comment]
I think he refers to the ##5 and ##2. I get them in some of my responses as well.

**Comment by devMls** [comment]
> I think he refers to the ##5 and ##2. I get them in some of my responses as well. ![Capture(1)](https://private-user-images.githubusercontent.com/31313681/392329140-6b61c656-defc-406e-940c-e659c012e62e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTIzMjQsIm5iZiI6MTczMzM5MjAyNCwicGF0aCI6Ii8zMTMxMzY4MS8zOTIzMjkxNDAtNmI2MWM2NTYtZGVmYy00MDZlLTk0MGMtZTY1OWMwMTJlNjJlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MWQ0YTA3MTcwM2ViMzk5MDY4YWMxM2FkOTM5MTU0MDY1NzhiOGRjZGU3NWRiNDQzMzZhYmFjY2RlODQwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NDxvqKP0n9plmM1nD2h3CgE0NdeYm8NxUuJ_rlpipws)

yes that is the problem I suspect that is in intent of the webui to link a additional information
