### ISSUE TITLE
[Bug]: windows GB2312 txt  parser error

### ISSUE THREAD

**Issue by 4pythonai** [infiniflow/ragflow#384]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

23412341cdfd2342

### Actual behavior

after upload a txt file ,got error: 

 Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 130, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/naive.py", line 143, in chunk
    txt = binary.decode("utf-8")
          ^^^^^^^^^^^^^^^^^^^^^^

save it to utf8 encoding txt file, error gone

### Steps to reproduce

```Markdown
upload an  windows os txt file
```

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/ragflow/pull/458
