### ISSUE TITLE
[Bug]: embedding models  

### ISSUE THREAD

**Issue by 4pythonai** [infiniflow/ragflow#386]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

23412341cdfd2342f4

### Other environment information

```Markdown
BAAI--bge-large-zh-v1.5 not listed in embedding model list,  but the docker download it every times ?
```

### Actual behavior

should list in options

### Steps to reproduce

```Markdown
create an  new knowlegdge base, in setting, click embedding
```

**Comment by KevinHuSh** [comment]
By default, it use BGE embeding model to be convinient for newbies to start the system.
