### ISSUE TITLE
[Question]: RAGFlow does not connect to Together.ai, Hugging Face and Alibaba Cloud. Please help

### ISSUE THREAD

**Issue by wouldbe12** [infiniflow/ragflow#3865]
### Describe your problem

RAGFlow does not connect to Together.ai, Hugging Face and Alibaba Cloud.

My settings for Together.ai via Settings / Model Providers are as follows: 

Model Name: Qwen/Qwen2.5-72B-Instruct-Turbo
Base url: https://api.together.xyz/v1/chat/completions
API: [my api]
Max tokens: 8192

ERROR: Fail to access model(Qwen/Qwen2.5-72B-Instruct-Turbo).**ERROR**...

My settings for Hugging Face are as follows: 

Model Name: Qwen/Qwen2.5-72B-Instruct
Base url: https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct/v1/chat/completions
API: [my api]
Max tokens: 8192

ERROR: Fail to access model(Qwen/Qwen2.5-72B-Instruct___HuggingFace).**ERROR**: Error code: 400 - {'error': 'Authorization header is correct, but the token seems invalid'}

My setting for Alibaba

Model: Tonqui Quianwen (chosen from the list of model in Setting / Model Providers)
Api: [my api at Alibaba Cloud]

ERROR: Fail to access model(gte-rerank) using this api key.'text' Fail to access model(qwen-long) using this api key.**ERROR**: **ERROR**: Invalid API-key provided. Fail to access model(qwen-plus) using this api key.**ERROR**: **ERROR**: Invalid API-key provided. Fail to access model(qwen-turbo) using this api key.**ERROR**: **ERROR**: Invalid API-key provided. Fail to access embedding model(text-embedding-v2) using this api key.Account abnormal. Please ensure it's on good standing to use QWen's text-embedding-v2 Fail to access embedding model(text-embedding-v3) using this api key.Account abnormal. Please ensure it's on good standing to use QWen's text-embedding-v3

These apis work for other aps, so the problem is not likely related to them. 

Please help.

**Comment by kunkeji** [comment]
The error message is written very clearly, the api-key is incorrect

**Comment by CRTTV** [comment]
Was a solution ever found for this? I am having the same issue. The API Key fails only on RAGFlow. The same key works on other programs. Any help is greatly appreciated.

**Comment by wouldbe12** [comment]
No solution found for me yet. :( My Together AI, HuggingFace and Alibaba API keys don't work with RAGFlow. 

I have only been able to add CHAT Together AI model with an endpoint that is different from their standard recommended (the one that worked was api.together.xyz/v1 rather then api.together.xyz/v1/chat/completions). 

But I was unable to connect any EMBEDDING model from Together.ai with the endpoints provided in their specs and my API keys. At the same time their embedding models work if I access them and log in via a python script provided on their website, so the problem is clearly with RAGFlow while the Together AI API works. 

Unfortunately, I have only  been successfully in connected OpenAI models to RAGFlow.   

@KevinHuSh, @CRTTV, I believe the problem is in the RAGFlow code. Any thoughts?

**Comment by CRTTV** [comment]
I just updated to the latest release and the problem persists. On the logs I get a "HTTP/1.1 400 bad request". I have tried several different versions of the URLs provided in Huggingface and they don't work. 
I have tried:
    https://api-inference.huggingface.co
    https://api-inference.huggingface.co/v1/
    https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct/v1/chat/completions
    https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct/v1
    https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct

These all have the same error message: "The authorization header is correct, but the token seems invalid" 

I am currently using the same API Key in Open WebUI and am able to access and use the model without any issue.
