### ISSUE TITLE
[Bug]: infinity available_int filter does not work

### ISSUE THREAD

**Issue by auxpd** [infiniflow/ragflow#3904]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

655b01a0a40373cfbcd115bb2186d7a9f89e6cd1

### RAGFlow image version

v0.14.1

### Actual behavior

Filtering did not take effect

### Steps to reproduce

```Markdown
When using the Infinity engine, filtering whether or not to disable it on the Knowledge Base screen does not take effect

/v1/chunk/list
```

**Comment by yuzhichang** [comment]
@auxpd I cannot reproduce.
rag/nlp/search.py:303 use available_int=1 as a fitler.
How do you know "available_int filter does not work"?

**Comment by auxpd** [comment]
I look at the request header on the page I tried to close the forbidden fragment and then filtered out the forbidden fragment and found that it didn't work, these cases only occur when using the infinity backend

> @auxpd I cannot reproduce. 我无法复制。 rag/nlp/search.py:303 use available_int=1 as a fitler.rag/nlp/search.py：303 使用 available_int=1 作为拟合器。 How do you know "available_int filter does not work"?你怎么知道“available_int过滤器不起作用”？

**Comment by yuzhichang** [comment]
It's not frontent but rag/nlp/search.py adds filter `available_int=1` to all searchs,
