### ISSUE TITLE
[Question]: The delete contents can be found.

### ISSUE THREAD

**Issue by cuihangrui** [infiniflow/ragflow#3927]
### Describe your problem

使用搜索功能搜索关键词块，把已经删除的文件也搜索出来了
![image](https://github.com/user-attachments/assets/e7233fac-c7c3-4650-8d34-b47677c3a12e)
![image](https://github.com/user-attachments/assets/0adf349d-0292-4bd3-a1a3-52fcde1cda88)

**Comment by cuihangrui** [comment]
0.13版本

**Comment by KevinHuSh** [comment]
Could you upgrade RAGFlow please?

It seems nothing can be done for these older versions.

**Comment by cuihangrui** [comment]
> 你能升级 RAGFlow 吗？
> 
> 似乎对这些旧版本无能为力。

新版本已经解决这个问题了吗？

**Comment by cuihangrui** [comment]
> 你能升级 RAGFlow 吗？
> 
> 似乎对这些旧版本无能为力。

新版本已经解决这个问题了吗？

**Comment by cuihangrui** [comment]
> Could you upgrade RAGFlow please?
> 
> It seems nothing can be done for these older versions.

我想问您一下有哪些情况，会出现搜不到文件但是搜块的关键词可以搜索出来

**Comment by cuihangrui** [comment]
找到问题发生的原因了，因为解析过程中我调用了后端删除文档的接口，导致出现上述问题
