### ISSUE TITLE
[Question]: My project only has one account, and modify a dataset using the ’HTTP API‘ will return an error：You don't own the dataset 1fad8bd2b3b711ef85900242ac120006。If only modify the assistant's name, it can be successful

### ISSUE THREAD

**Issue by xxc-11** [infiniflow/ragflow#3928]
### Describe your problem

![1733715043437](https://github.com/user-attachments/assets/29c1b86f-7a8e-423d-9768-4a1a520721e0)

**Comment by KevinHuSh** [comment]
What's the version of your image?
![image](https://github.com/user-attachments/assets/6b53c8eb-e251-4ea2-90af-916872445551)

**Comment by xxc-11** [comment]
I upgraded to the latest one at noon and it was resolved. Thank you.
