### ISSUE TITLE
[Question]: Why python package installed but couldn't be used?

### ISSUE THREAD

**Issue by lugq1990** [infiniflow/ragflow#3947]
### Describe your problem

Hi all,

I have just installed the ragflow python package, but after `pip install ragflow`, try to `import ragflow` with error:

```shell
In [1]: import ragflow
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import ragflow

ModuleNotFoundError: No module named 'ragflow'
```

Just like to know how to use the python package?

The reason is that would like to code to to interact with system. please advice how to solve?

**Comment by KevinHuSh** [comment]
`pip install ragflow-sdk`

**Comment by lugq1990** [comment]
> `pip install ragflow-sdk`

Much thanks for the guide, but I  just think that for python API doc should be updated, right?  what do you think? @KevinHuSh 

One thing to notice is that only python>=3.10 could be used.

https://ragflow.io/docs/v0.14.1/python_api_reference#examples

**Comment by lugq1990** [comment]
I have get the info that already update the code ref/

**Comment by lugq1990** [comment]
For currently latest API reference for python:   https://github.com/infiniflow/ragflow/blob/main/docs/references/python_api_reference.md
