### ISSUE TITLE
[Question]: duckduckgo-search = "5.3.1b1" 

### ISSUE THREAD

**Issue by isthaison** [infiniflow/ragflow#3959]
### Describe your problem

with current version. really doesn't work

**Comment by KevinHuSh** [comment]
But current version is like this:
![image](https://github.com/user-attachments/assets/534253a1-55c1-4739-b3b9-35ebc3c2d013)

**Comment by isthaison** [comment]
![image](https://github.com/user-attachments/assets/d5e84226-14d5-47ad-9a6c-e179d164baac)
with current version it seems it doesn't work

**Comment by isthaison** [comment]
![image](https://github.com/user-attachments/assets/00af992a-b0d3-4edd-b431-f00580a529de)
with  duckduckgo-search = "6.4.1"

![image](https://github.com/user-attachments/assets/69aaf299-bab1-49b2-8cc0-7fe66944ed33)
It' working
