### ISSUE TITLE
[Bug]: network anomaly There is an abnormality in your network and you cannot connect to the server.

### ISSUE THREAD

**Issue by wengbenjue** [infiniflow/ragflow#397]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

e439d0959492c6808427677ad09dd096827146ad 

### Other environment information

```Markdown
OS:Mac M2
```

### Actual behavior

When I input http://127.0.0.1/login in brower,I got a bug that
there is an abnormality in your network and you cannot connect to the server.
Could you help me ,thanks!

### Steps to reproduce

```Markdown
http://127.0.0.1/login
```

**Comment by wengbenjue** [comment]
I check the logs,It's about Es can not connect .
Fail to connect to es: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x400917fb90>: Failed to establish a new connection: [Errno 111] Connection refused))
How to fix it

**Comment by waiking1970** [comment]
I also encountered the same issue, and it was resolved after executing the following command:

$ docker logs -f ragflow-server

**Comment by wengbenjue** [comment]
> I also encountered the same issue, and it was resolved after executing the following command:
> 
> $ docker logs -f ragflow-server
It disppeared.
Thank you,Perhaps It's initialzing.

**Comment by KevinHuSh** [comment]
Have a look at this. It may help.
https://github.com/infiniflow/ragflow/blob/main/docs/faq.md

**Comment by hsmio** [comment]
@wengbenjue I had the same issue and restarting docker-compose solved it for me, as suggested here: https://github.com/infiniflow/ragflow/issues/348#issuecomment-2054020194
