### ISSUE TITLE
[Question]: Monitor res locale

### ISSUE THREAD

**Issue by isthaison** [infiniflow/ragflow#3977]
### Describe your problem
Hi @cike8899  
I have added a place to control multi-language. Where should I put it? Currently it has the link /user-setting/locale 
![image](https://github.com/user-attachments/assets/fcb23098-c20b-4631-9916-a5d4792ce8f6)

**Comment by KevinHuSh** [comment]
**Appreciations**
I'm wondering why monitoring these translation is nessasary?

**Comment by isthaison** [comment]
The language will not be fully supported, in different language interfaces. For non-developer users. They will not really understand the meaning of the words. They have to go through tranlates. This is quite inconvenient. I think this function will be for developers by country, it can control the languages ​​that are missing and they can update in time according to the added features.

**Comment by isthaison** [comment]
as in present in spanish. still missing tooptips.
