### ISSUE TITLE
[Bug]: file Parsing failed

### ISSUE THREAD

**Issue by ysyx2008** [infiniflow/ragflow#398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2afe7a7

### Other environment information

```Markdown
当前仓库的名称是：ragflow
当前目录的Git版本号是: 2afe7a7
操作系统: Ubuntu 22.04 (内核版本: 6.5.0-27-generic)
CPU类型：x86_64
内存容量：
Docker版本：26.0.1,
Python版本：Python未安装
```

### Actual behavior

![图片](https://github.com/infiniflow/ragflow/assets/11251894/9fe34049-354f-45eb-a277-540e1f4632d9)
![图片](https://github.com/infiniflow/ragflow/assets/11251894/8ab873db-f268-494d-b1a9-b5d0d0f759b5)

can't parse any file.
removed all docker volume, not working.

### Steps to reproduce

```Markdown
1. Normal deployment.
2. Create a knowledge base.
3. Upload any document.
```

**Comment by KevinHuSh** [comment]
Upgrade to latest dev version of the docker image. Problem solved.
