### ISSUE TITLE
[Bug]: 'Invalid query statement: OrQueryNode should not have both not child and non-not child@src/storage/invertedindex/search/query_node.cpp:385

### ISSUE THREAD

**Issue by wz96cj** [infiniflow/ragflow#3980]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

无

### RAGFlow image version

无

### Other environment information

```Markdown
ragflow:0.14.0
doc_engine:infinity
```

### Actual behavior

![3c8a73f08de81a73e9f6f8e07379978](https://github.com/user-attachments/assets/f2492484-9051-41bc-bcb3-34d70282d9f4)

### Expected behavior

查询不到问题后，可以正常输出结果

### Steps to reproduce

```Markdown
聊天对话
```

**Comment by wz96cj** [comment]
> Can you paste your query here?您可以在这里粘贴查询吗？

![1733907634387](https://github.com/user-attachments/assets/eccb96ea-7a7b-4753-a67b-493084d76961)
今天服务重启后好像  又正常运行了 等下个版本发布后 我再看看还有没有这样的问题

**Comment by yuzhichang** [comment]
@wz96cj RAGFlow v0.15.0 is released.Have a try.

**Comment by asuperwei** [comment]
I have a similar problem
![image](https://github.com/user-attachments/assets/76c190c2-4392-4378-bf40-73870b63d078)
![image](https://github.com/user-attachments/assets/52affcdc-ea0e-4c86-b3b8-9746f4f32107)

**Comment by yuzhichang** [comment]
@asuperwei Your issue is tracked by #4160 and has been resolved.
