### ISSUE TITLE
[Feature Request]: Remove the API token option from chat assistant in DEMO

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/ragflow#3987]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

On the Chat page, hover over a chat assistant, you can still find the API option. After clicking it, the following message appears:
![20241211-153552](https://github.com/user-attachments/assets/ce0b6006-9b72-47dd-8750-1b9e08a356c5)

**Comment by KevinHuSh** [comment]
> Same issue in RAGflow v0.14.1-130-g6d19294d slim
> 
> on Agent page , while click API button , the error message : The beta field of the API Token cannot be empty!
> 
> ![Screenshot 2024-12-11 at 11 38 37 PM](https://private-user-images.githubusercontent.com/12210951/394813056-e499f00d-c23e-4cda-871f-3232af0901be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5Njg0MTMsIm5iZiI6MTczMzk2ODExMywicGF0aCI6Ii8xMjIxMDk1MS8zOTQ4MTMwNTYtZTQ5OWYwMGQtYzIzZS00Y2RhLTg3MWYtMzIzMmFmMDkwMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAxNDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNzhkM2E4NzFjMjQyZDNjZTZlNmJhMGQwYTAwODYwOGIyZjU4NDkwYjAyZGVkZmM0OTZjMzVkZjg3Yzg4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.owzLhhp4YWUUl8zj1hsfGwpXGe8W3Tvf1IA5TMA34wE)

Apply an API key in system setting.
