### ISSUE TITLE
[Bug]: failed to start with the error " ./entrypoint.sh: line 22:  1180 Illegal instruction     $PY rag/svr/task_executor.py"

### ISSUE THREAD

**Issue by qiulang** [infiniflow/ragflow#3989]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

74c6b21f

### RAGFlow image version

failed to start

### Other environment information

```Markdown
uname -a
Darwin localhost 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
```

### Actual behavior

```
docker compose -f docker/docker-compose.yml up -d
[+] Running 5/5
 ✔ Container ragflow-es-01   Running                                                                                                                                       0.0s
 ✔ Container ragflow-mysql   Healthy                                                                                                                                       0.5s
 ✔ Container ragflow-redis   Running                                                                                                                                       0.0s
 ✔ Container ragflow-server  Running                                                                                                                                       0.0s
 ✔ Container ragflow-minio   Running
 
```

But  it fails to start

```
docker logs -f ragflow-server
./entrypoint.sh: line 35:  3430 Illegal instruction     $PY api/ragflow_server.py
```

Stop the docker and start it again, sometimes it will show the following error, but sometimes it does not!

```
! ragflow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

### Steps to reproduce

```Markdown
git pull the latest code and  run on mac M2
```

**Comment by KevinHuSh** [comment]
```
docker build --build-arg ARCH=arm64 -f Dockerfile.slim -t infiniflow/ragflow:dev-slim .
docker build --build-arg ARCH=arm64 -f Dockerfile -t infiniflow/ragflow:dev .
```

**Comment by qiulang** [comment]
I delete the docker image and pull the latest code (12.16) but I hit this error "The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

How do I fix it ?

```
[+] Running 33/6
 ✔ ragflow Pulled                                                                                                                                                          8.1s





[+] Running 6/6
 ✔ Container ragflow-minio                                                                                                                                Started         10.5s
 ✔ Container ragflow-es-01                                                                                                                                Started         10.5s
 ✔ Container ragflow-redis                                                                                                                                Started         10.4s
 ✔ Container ragflow-server                                                                                                                               Started         21.2s
 ✔ Container ragflow-mysql                                                                                                                                Healthy         10.8s
 ! ragflow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                  0.0s
```

**Comment by southkorea2013** [comment]
> ```
> docker build --build-arg ARCH=arm64 -f Dockerfile.slim -t infiniflow/ragflow:dev-slim .
> docker build --build-arg ARCH=arm64 -f Dockerfile -t infiniflow/ragflow:dev .
> ```


Hi Kevin,

I cann't find the Dockerfile.slim from the latest RAGFlow repository. Please shed some light on it. Thanks.

 Nan

**Comment by KevinHuSh** [comment]
Please refer to [this](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-a-docker-image-without-embedding-models).

**Comment by southkorea2013** [comment]
> Please refer to [this](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-a-docker-image-without-embedding-models).

Thanks Kevin. so does the following docker build command work for macOS(Apple silicon)?
docker build --build-arg LIGHTEN=1 --build-arg ARCH=arm64 -f Dockerfile -t infiniflow/ragflow:v0.14.1-slim .

**Comment by qiulang** [comment]
@southkorea2013 @KevinHuSh I am also using m2, I just want run ragflow without building it,  after that why I use docker. But I still failed to run it even with your suggestion.

**Comment by KevinHuSh** [comment]
Impossible. You have to build an image that fits the platform.

**Comment by southkorea2013** [comment]
> > Please refer to [this](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-a-docker-image-without-embedding-models).
> 
> Thanks Kevin. so does the following docker build command work for macOS(Apple silicon)? docker build --build-arg LIGHTEN=1 --build-arg ARCH=arm64 -f Dockerfile -t infiniflow/ragflow:v0.14.1-slim .

@KevinHuSh How about this?

**Comment by yuzhichang** [comment]
NOTE While we also test RAGFlow on ARM64 platforms, we do not plan to maintain RAGFlow Docker images for ARM. However, you can build an image yourself on a linux/arm64 or darwin/arm64 host machine as well.
```
git clone https://github.com/infiniflow/ragflow.git
cd ragflow/
python3 download_deps.py
docker build -f Dockerfile.deps -t infiniflow/ragflow_deps .
docker build -f Dockerfile -t infiniflow/ragflow:nightly .
docker build --build-arg LIGHTEN=1 -f Dockerfile -t infiniflow/ragflow:nightly-slim .
```

**Comment by qiulang** [comment]
But this information does not mention  at readme at all!

**Comment by qiulang** [comment]
Okay I try to run it on x86 linux, but it still fails with the error {"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}

I will open a new issue for it.

**Comment by KevinHuSh** [comment]
Strip the port number in the web browser.
