### ISSUE TITLE
[Question]: The problem of creating a chat assistant

### ISSUE THREAD

**Issue by xxc-11** [infiniflow/ragflow#4000]
### Describe your problem

attribute  "prompt"-> "rerank_model"  
![1733972684815](https://github.com/user-attachments/assets/edb123bf-4729-49ba-8254-8200e2d08c76)
![1733973055349](https://github.com/user-attachments/assets/7f44a0a9-227a-43de-96bc-8282d52ee19a)
![1733973172017](https://github.com/user-attachments/assets/55547ee4-2e84-46ef-81d0-e82d26f20fac)
Neither "BAAI/bge-reranker-v2-m3@BAAI" nor "BAAI/bge-reranker-v2-m3"  works.
How should this value be transmitted?

**Comment by KevinHuSh** [comment]
What about setting it in system model setting firstly?

**Comment by xxc-11** [comment]
It can be set in the system, only through the "API" method is not possible. I just don't know how to set it up through the 'API'.
![1](https://github.com/user-attachments/assets/54679f7c-37df-4155-b9ab-34defa42141d)
![2](https://github.com/user-attachments/assets/28bb7aa3-fa09-4404-a929-db83d552fe90)

**Comment by xxc-11** [comment]
> What about setting it in system model setting firstly?

It can be set in the system, only through the "API" method is not possible. I just don't know how to set it up through the 'API'.
![1](https://github.com/user-attachments/assets/00a46d2c-22f9-418c-9d0f-fd4d7dfbedf3)
![2](https://github.com/user-attachments/assets/4c912368-f515-4024-a047-74fdcd5ea5bc)

**Comment by xxc-11** [comment]
Solved, thank you very much
