### ISSUE TITLE
[Bug]:Fail to access model(qwen:7b-fp16).**ERROR**: [Errno 99] Cannot assign requested address 

### ISSUE THREAD

**Issue by wengbenjue** [infiniflow/ragflow#402]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

e439d0959492c6808427677ad09dd096827146ad 

### Other environment information

```Markdown
Mac M2
```

### Actual behavior

I can't add the ollama models

### Expected behavior

I want add ollama local model to the platform,

### Steps to reproduce

```Markdown
When I Submit,The error happened.
```

### Additional information

Fail to access model(qwen:7b-fp16).**ERROR**: [Errno 99] Cannot assign requested address
![image](https://github.com/infiniflow/ragflow/assets/5533297/e5aef048-1e88-4337-93ac-c7bde72ca4de)

**Comment by KevinHuSh** [comment]
- If RAGFlow is locally deployed, ensure that your RAGFlow and Ollama are in the same LAN. 
- If you are using our online demo, ensure that the IP address of your Ollama server is public and accessible.

**Comment by zzlTim** [comment]
你解决了吗

**Comment by CjhHa1** [comment]
have you fixed that？
