### ISSUE TITLE
[Bug]: CHAT CANNOT ACCESS TEAM KBs

### ISSUE THREAD

**Issue by EzeLLM** [infiniflow/ragflow#4022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

765a114b

### RAGFlow image version

v0.13

### Actual behavior

I signup and add llm and do other configs. i get access to a team kb which i can see its contents when i make a search or when i click on it in knowledge bases. however, the llm is not getting access to it! when i try to ask a question i get the default answer for not found in knowledge base. however when i enter the user that is the owner of the knowledge base i can ask the llm the same question and it answers perfectly. 

### Steps to reproduce

```Markdown
try to chat using team kb
```

**Comment by KevinHuSh** [comment]
Do you add the KB for dialog setting?

**Comment by EzeLLM** [comment]
I did add the knowledge base when creating the assistant in chat section. Is that what you mean?
But when the knowledge base is owned by other member in the team it always returns the default empty answer.
The same query retrieves successfully when sending from other user.

**Comment by KevinHuSh** [comment]
I can't reproduce this scenario for latest version of RAGFlow.
Pull  the version 'nightly' docker image then have a try?

**Comment by EzeLLM** [comment]
> I can't reproduce this scenario for latest version of RAGFlow.
> 
> Pull  the version 'nightly' docker image then have a try?

With pulling the new version my problem has been solved. Thanks for the help 🤗
