### ISSUE TITLE
[Question]: ragflow-server  | [ERROR] [2024-04-17 10:36:27,681] [http_request._handle_request] [line:221]: HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0de4104590>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))

### ISSUE THREAD

**Issue by hanxl1** [infiniflow/ragflow#403]
### Describe your problem

这个问题要配啥，我用了自己本地的qwen模型的api-key

**Comment by ooooo-create** [comment]
it seems should use the api-key from  https://dashscope.console.aliyun.com/model

**Comment by hanxl1** [comment]
> it seems should use the api-key from https://dashscope.console.aliyun.com/model

但我配的是自己的  factory: 'Tongyi-Qianwen'
  api_key: 'sk-xxxxxxxxxxxxx'
  base_url: ''
这里我填的是我自己的api_key和base_url

**Comment by KevinHuSh** [comment]
Your ragflow server can't access dashscope.aliyuncs.com.


BTW.
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

**Comment by hanxl1** [comment]
> Your ragflow server can't access dashscope.aliyuncs.com.
> 
> BTW. Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

But I configured my own
{
    factory: 'Tongyi-Qianwen'
    api_key: 'sk-xxxxxxxxxxxxx'
    base_url: ''
}
Here I filled in my own api_key and base_url.   Why is it trying to call dashscope.aliyuncs.com?
