### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by hanxl1** [infiniflow/ragflow#404]
### Describe your problem

![822de41d-6d3a-49db-a286-1efbc99799cf](https://github.com/infiniflow/ragflow/assets/167157823/0aadf44f-aadc-4e95-9afa-333079962fcc)
这个上传pdf总是卡着不动呀

**Comment by KevinHuSh** [comment]
![image](https://github.com/infiniflow/ragflow/assets/12318111/7c0eed89-d215-443f-9936-067b58c78a06)

**Comment by chengxs1994** [comment]
> ![image](https://private-user-images.githubusercontent.com/12318111/323067275-7c0eed89-d215-443f-9936-067b58c78a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTQ4NzksIm5iZiI6MTcxMzg1NDU3OSwicGF0aCI6Ii8xMjMxODExMS8zMjMwNjcyNzUtN2MwZWVkODktZDIxNS00NDNmLTk5MzYtMDY3YjU4Yzc4YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2NDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhY2Q4ZTk0M2FiN2VlM2UxZTJjM2FhODJlODYzNjE3YmEwZDhmZmYzODZjNGJlM2FiNmEyMjE2ZjRhNDI3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.917bWSTBzfHddu1ON6aKZ9gjQpqvY8YWTpVDahWAhZA)

**Comment by chengxs1994** [comment]
> ![图像](https://private-user-images.githubusercontent.com/12318111/323067275-7c0eed89-d215-443f-9936-067b58c78a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjMxMjIsIm5iZiI6MTcxMzg2MjgyMiwicGF0aCI6Ii8xMjMxODExMS8zMjMwNjcyNzUtN2MwZWVkODktZDIxNS00NDNmLTk5MzYtMDY3YjU4Yzc4YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzA3MThkMDUyZjk1NzBkODQ3ZDI1NGI2ZDdjMTk5ZThiNzBhY2NlN2ZiZWUxODhmMjY0YjIxZDE5YWI1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a51877s9vc75S0JKR-Sy9MmXUkfJPPYawMdW8kAroN0)

ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_18cb3dde011811efa5100242ac120006]', ragflow_18cb3dde011811efa5100242ac120006, index_or_alias)【Q】：{'match': {'doc_id': '8a79d1ce014b11ef808b0242ac120005'}}

docker logs -f ragflow-server (is work)
Check if the tast_executor.py process exist. (is work)
Check if your RAGFlow server can access hf-mirror.com or huggingface.com. (can access)
but ES index not create and 404
