### ISSUE TITLE
[Question]: Chunk Highlight Display Issue in Knowledge Base and Search Features

### ISSUE THREAD

**Issue by midilandlu** [infiniflow/ragflow#4040]
### Describe your problem

Same Issue : https://github.com/infiniflow/ragflow/issues/3864#event-15534966183 

RAGflow ver : v0.14.1-151-g4a7bc4df slim

Issue Description:
Knowledge Base / Dataset / Chunk - Chunk data cannot display highlights in the preview document.

Steps to reproduce:
1. Upload a file to the Knowledge Base and parse it successfully.
2. Check the chunk data on the file chunk page.

Observed: Chunk data cannot display highlights on the document. This behavior is different from previous versions, as shown in the screenshots below.
![Screenshot 2024-12-15 at 1 07 21 AM](https://github.com/user-attachments/assets/17a5a995-45f8-44dc-b702-9b021e085b4e)

Search Functionality - Search results do not display chunk highlights but only show chunk images.

Observed: The chunk highlights are missing in the search results, and only chunk images are displayed, as shown in the screenshots below.

![Screenshot 2024-12-15 at 1 16 09 AM](https://github.com/user-attachments/assets/75e97f0e-2404-4bfe-b75c-83ae1af3994b)

I believe this is not the intended behavior.

**Comment by KevinHuSh** [comment]
Pull the version 'nightly' of docker image. It's fixed there.

**Comment by midilandlu** [comment]
I pull and build the version 'nightly' of docker image : v0.14.1-155-g8ea631a2 slim 
same issue as v0.14.1-151-g4a7bc4df slim.

![image](https://github.com/user-attachments/assets/1abb2b5a-d270-440f-869c-b9740b6240c6)

![image](https://github.com/user-attachments/assets/b2a43172-f619-4108-8747-73225c8a48d6)

![image](https://github.com/user-attachments/assets/27180a59-5450-4cf6-89ab-67bbc5b98b2f)

**Comment by midilandlu** [comment]
In the current RAGflow v0.14.1-172-g79e435fc slim version, the issue has been confirmed as resolved.

![image](https://github.com/user-attachments/assets/5058f059-4f19-4757-9534-ea123259bfcc)
