### ISSUE TITLE
[Question]: ERROR: too many indices for array: array is 0-dimensional, but 1 were indexed

### ISSUE THREAD

**Issue by uu5208** [infiniflow/ragflow#4076]
### Describe your problem

![image](https://github.com/user-attachments/assets/b60fc238-66d5-41a2-8ac6-84c9d112d6e2)

Occasionally occurs while using chat service.  
The chat answer has generated, but assertion happen when inserting citations。

**Comment by KevinHuSh** [comment]
It seems the embedding model not return normally occasionally.

**Comment by uu5208** [comment]
Thanks.  The max embedding batch size was 32. However，the len of "pieces_"was 86，which caused the assertion.
