### ISSUE TITLE
[Question]: Can you come up with a tutorial to start ragflow locally instead of docker

### ISSUE THREAD

**Issue by HanYu666666** [infiniflow/ragflow#408]
### Describe your problem

Can you come up with a tutorial to start ragflow locally instead of docker

**Comment by KevinHuSh** [comment]
Please refer to https://github.com/infiniflow/ragflow/blob/main/Dockerfile.scratch
Every RUN in it is what you need to do.

1. Python 3.11
2. pip install -r requirements.txt
3. python rag/svr/task_executor.py  0 1
4. python rag/svr/task_broker.py
5. python api/ragflow_server.py

**Comment by HanYu666666** [comment]
thanks, i will refer to https://github.com/infiniflow/ragflow/blob/main/Dockerfile.scratch ,and have a try  run ragflow on windows.

**Comment by Nuclear6** [comment]
Why is there still an error connecting to es?
$ python3.11 rag/svr/task_executor.py 0 1
[WARNING] [2024-04-28 21:46:04,147] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
