### ISSUE TITLE
[Bug]: Model name length of Ollama cannot be used if it is too long. Once model is created, it cannot be deleted any more.

### ISSUE THREAD

**Issue by edisonzf2020** [infiniflow/ragflow#409]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

no

### Other environment information

```Markdown
docker
```

### Actual behavior

Such as when I add nous-hermes2-mixtral:8x7b-dpo-q5_K_M model into Ollama. The model name was truncated. Another issue is how to remove the model I added in Ollama?

### Steps to reproduce

```Markdown
As above description.
```

**Comment by KevinHuSh** [comment]
Please upgrade to dev version or 0.6.0
