### ISSUE TITLE
[Question]: MaxConnectionsExceeded('Exceeded maximum connections.')

### ISSUE THREAD

**Issue by CatInCloud** [infiniflow/ragflow#410]
### Describe your problem

MaxConnectionsExceeded('Exceeded maximum connections.')
what should i do

**Comment by KevinHuSh** [comment]
What if you increase that number?
![image](https://github.com/infiniflow/ragflow/assets/12318111/5cb7215e-8fb1-45e4-83e7-61254abd10d7)

**Comment by Siwmy** [comment]
how to deal with [Question]: MaxConnectionsExceeded('Exceeded maximum connections.')
, i can't understand what you have say
