### ISSUE TITLE
[Question]: The input of Q→SQL comonent（Retrieval）is not correct, when using the DB Assistant in the Agent module.

### ISSUE THREAD

**Issue by riverhell** [infiniflow/ragflow#4108]
### Describe your problem

fig 1：I create an agent from DB Assistant template, choose DDL、Q→SQL、DB Description knowledge base for the corresponding retrival componet. When run the agent, asking any question, encounter the same error 
<img width="766" alt="1" src="https://github.com/user-attachments/assets/51d4506a-4665-41a8-ac76-e78fbf10a9fe" />

fig 2: the DDL retrieval componet gets right input
<img width="329" alt="2" src="https://github.com/user-attachments/assets/429e34fa-94ed-4e9e-97b6-025d1738e3b5" />

fig 3: the Q→SQL retrival component gets wrong input, it should be the user query, not the output of the DDL retrivel component.
<img width="369" alt="3" src="https://github.com/user-attachments/assets/33453e5d-21f5-4e59-b940-6d4b6384e910" />

How can i fix it, is there any mistake i made?

**Comment by riverhell** [comment]
fig 4: the input set default for the Q→SQL retrieval component
![image](https://github.com/user-attachments/assets/8a7686dc-dbd5-4edf-ae96-4d44c1bd65ce)

**Comment by KevinHuSh** [comment]
It's usually caused by too many fields in the query to ES.
What's the ES version you apply?

**Comment by riverhell** [comment]
> It's usually caused by too many fields in the query to ES. What's the ES version you apply?

Thanks for responsing, the version of ES is 8.11.4

**Comment by riverhell** [comment]
> It's usually caused by too many fields in the query to ES. What's the ES version you apply?

According to the error info it shows, it may be too many query to ES, but from the fig3, it can be seen that the further reason is the wrong input of "Q→SQL retrival component "，how to change it to user's query?

**Comment by KevinHuSh** [comment]
Set the input of the component to `interface`.

**Comment by riverhell** [comment]
> Set the input of the component to `interface`.

It still doesn't work.
![image](https://github.com/user-attachments/assets/8367b81c-7ec8-4691-8e3b-91a09861a458)
I set all the input of the three component to "Reference-interface", but i get nothing output:
![image](https://github.com/user-attachments/assets/95440fdc-d98d-4187-9784-e678ef39d229)
and all the input of the three components are the opener of the Begin component, without user's query.

**Comment by riverhell** [comment]
And then, i run the "test run" button of each component, and get right response.
![image](https://github.com/user-attachments/assets/4b9f188d-3605-4636-8e15-0f59c0b22b12)
![image](https://github.com/user-attachments/assets/f1c223d3-996f-412d-9d5c-595f41a3d415)
![image](https://github.com/user-attachments/assets/03dcaaa3-e867-4ae6-a5b7-516cd208f24a)

**Comment by riverhell** [comment]
Thanks for fixing it.
