### ISSUE TITLE
[Question]: docker-compose up -d    Error

### ISSUE THREAD

**Issue by ciaoyizhen** [infiniflow/ragflow#411]
### Describe your problem

  Here's what I did.
1. Replace "https://registry.npmmirror.com" in web/package-lock.json with own image source.

2. Modify user_default_llm in both service_conf.yaml.
Modify 'Tongyi-Qianwen'->'Local' in factory, add base_url

3. modified api/settings.py file, changed chat_model in Local in default_llm to ChatGLM3-6b.

4. docker build -t ragflow:v0.2.0 .

5. docker compose up -d   
At this point an error occurs
[+] Running 5/5
x mysql Error
x minio Error
x es01 Error
x ragflow Error
x kibana Error
Error response from daemon: Get https://registry-1.docker.io/v2/:dial tcp: lookup registry-1.docker.io on xx.xx.xx.xx(a host ip): server misbehaving

**Comment by ciaoyizhen** [comment]
don't know where this https://registry-1.docker.io/v2/:dial came from I searched the whole folder and there's no such address.

**Comment by ciaoyizhen** [comment]
The mirror source was replaced because the machine was offline.

**Comment by KevinHuSh** [comment]
What's in docker-compose.yml is not 'ragflow:v0.2.0'.
Check the images name in yaml file.
