### ISSUE TITLE
[Question]: 直接访问es，请问每个字段什么意思

### ISSUE THREAD

**Issue by cuihangrui** [infiniflow/ragflow#4118]
### Describe your problem

我想知道es库中每条数中，那个字段是原文内容，content_with_weight字段是原文内容，没有经过分词的吗
![image](https://github.com/user-attachments/assets/0e1a89e2-fc66-4d8e-9e94-310a0c5c1382)

**Comment by JinHai-CN** [comment]
We intend to create an international community, please using English for communication. Thank you very much.

**Comment by cuihangrui** [comment]
> ### 描述您的问题
> I want to know which field is the original content of each number in the es library, and the content_with_weight field is the original content without word segmentation ![图像](https://private-user-images.githubusercontent.com/86222753/397275370-0e1a89e2-fc66-4d8e-9e94-310a0c5c1382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NTczNDksIm5iZiI6MTczNDY1NzA0OSwicGF0aCI6Ii84NjIyMjc1My8zOTcyNzUzNzAtMGUxYTg5ZTItZmM2Ni00ZDhlLTllOTQtMzEwYTBjNWMxMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAxMTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMmUxNzYyNTdiOWM2ZTQxNjkwMjg4ZjhmNGNhMTRmYjczNjFkZjczNjExZGMwNmZkZjZkMTdhODhlMzMyNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D7cc4KXxpr2iqwIr_n1eWqcHzXRP-r-B4xaLwV5MtgI)

**Comment by cuihangrui** [comment]
> We intend to create an international community, please using English for communication. Thank you very much.

Is there documentation to explain what each field in es means

**Comment by JinHai-CN** [comment]
> > We intend to create an international community, please using English for communication. Thank you very much.
> 
> Is there documentation to explain what each field in es means

I am afraid not.
