### ISSUE TITLE
[Question]: I can't set  vm.max_map_count

### ISSUE THREAD

**Issue by lemon-little** [infiniflow/ragflow#412]
### Describe your problem

<img width="1043" alt="image" src="https://github.com/infiniflow/ragflow/assets/53484050/389df6c9-63a7-4eb1-bf6f-6a4637a890e4">

**Comment by KevinHuSh** [comment]
The 'screen' is not successful. Please refer to:
https://stackoverflow.com/questions/41192680/update-max-map-count-for-elasticsearch-docker-container-mac-host

**Comment by lemon-little** [comment]
<img width="920" alt="image" src="https://github.com/infiniflow/ragflow/assets/53484050/1b5660f3-9737-40a3-be1a-19fbb0974ba2">
