### ISSUE TITLE
[Bug]: Reparse GraphRAG failed when cancel the parsing at first with Infinity doc engine

### ISSUE THREAD

**Issue by bubaidoudi** [infiniflow/ragflow#4120]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

none

### RAGFlow image version

none

### Other environment information

```Markdown
Embedding model: BAAl/bge-large-zh-v1.5
Ragflow: 0.15.0
Infinity: 0.5.0
Analysis method: Knowledge graph, I have also encountered issues with General.
```

### Actual behavior

I used the vector database, successfully parsed 2 out of 3, but I encountered an error when querying
<img width="1031" alt="2b9e38d90e7500d560f7ce9f002860f" src="https://github.com/user-attachments/assets/95a502ef-3040-457f-9d2f-708d2cc2ed56" />
I canceled the parsing of the third one at the beginning, and when I tried to parse it again, it got stuck and kept waiting. Then I restarted the container and started parsing again, but it got stuck at the last step. The querying also got stuck and didn’t respond.
![b93aac7dc7d4faa7c683471376476c3](https://github.com/user-attachments/assets/73857d26-be0a-48e5-9303-498800950af9)

Then when I restart the container, it automatically starts parsing again, but it still gets stuck at the last step.
<img width="790" alt="fa15bfd91c04d67866558deb040fff4" src="https://github.com/user-attachments/assets/54f79272-433e-47dd-b2dc-75f5362dcc84" />

I also encountered a situation where the container got stuck during a restart. I had to delete the data from the vector database before it could restart successfully. I didn't have time to reproduce the issue.

### Steps to reproduce

```Markdown
When parsing with RAGFlow 0.15.0 and Infinity 0.5.0, if I cancel and then try to reparse, it gets stuck at the last step.


```

**Comment by yuzhichang** [comment]
@bubaidoudi Please write issue in English.

**Comment by bubaidoudi** [comment]
> @bubaidoudi Please write issue in English.

It has been modified.

**Comment by asuperwei** [comment]
I have samo question

**Comment by asuperwei** [comment]
I have same question

**Comment by yuzhichang** [comment]
@bubaidoudi We've found sometimes infinity transactions fail or stuck due to txn conflict.

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/ragflow/pull/4207
