### ISSUE TITLE
［Bug］ Infinity AssertionError

### ISSUE THREAD

**Issue by mayanlong2020** [infiniflow/ragflow#4141]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

n/a

### RAGFlow image version

v0.15.0-14-g10a62115 full

### Other environment information

```Markdown
Ubuntu 24
```

### Actual behavior

When using infinity, an Assertion Error is displayed when viewing the chunk pages of the dataset during the parsing process, and the log is shown in the attachment.

### Steps to reproduce

```Markdown
1.Start parsing the datesets
2.Check the chunks have been extract and emeded. 
3.“AssertionError” will be raised.
```

### Additional information

ragflow - infinity [00:56:32.208][211][ warning ] Another checkpoint txn is started in 949, new checkpoint 951 will do nothing 
 ragflow - infinity [00:56:32.211][211][ info ] WalManager :: Checkpoint delete wal file :/ var / infinity / wal / wal . log .944
 ragflow - infinity [00:56:32.211][210][ info ] wal / var / infinity / wal / wal . log swap to new path :/ var / infinity / wal / wal . log .948
 ragflow - infinity [00:56:32.211][210][ info ] Open new wal file / var / infinity / wal / wal . log 
 ragflow - server 2024-12-2008:56:33,324 INFO 20172.18.0.6--[20/Dec/202408:56:33]" GET /v1/user/ info HTTP /1.1t200-
 ragflow - server 2024-12-2008:56:33,354 INFO 20172.18.0.6--[20/Dec/202408:56:33]" GET /v1/kb/ detail ? kb _ id =5b7cadc8bdbc11efa5820242ac120006 HTTP /1.1"200-
 ragflow - server 2024-12-2008:56:33,370 INFO 20172.18.0.6--[20/Dec/202408:56:33]" GET /v1/user/ tenant _ info HTTP /1.1"200-
 ragflow - server 2024-12-2008:56:33,371 INFO 20172.18.0.6--[20/Dec/202408:56:33]" GET /v1/document/ list ? kb _ id =5b7cadc8bdbc11efa5820242ac120006& keywords =& page _ size =10& page =1 HTTP /1.1"200
 ragflow - infinity [00:56:36.399] [28] [ error Table ragflow _02b3b390bb8b11ef925c0242ac120006_a3129914bc4911efb2330242ac120006 doesn ' t exist 
 flow - infini [00:56:36.399] [28] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006_a3129914bc4911efb2330242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.399] [28] [ error [ THRIFT ERROR ]: Table ragflow _02b3b390bb8b11ef925c0242ac120006_a3129914bc4911efb2330242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [27] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006a3129914bc4911efb2330242ac120006 doesn ' t exist 
 ragflow - infinity [00:56:36.403] [27] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006_a3129914bc4911efb2330242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [27] [ error [ THRIFT ERROR ]: Table ragflow 02b3b390bb8b11ef925c0242ac120006_a3129914bc4911efb2330242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [28] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006d44bc09ebce611efa57b0242ac120006 doesn ' t exist 
 ragflow - infinity [00:56:36.403] [28] [ error Table ragflow _02b3b390bb8b11ef925c0242ac120006_d44bc09ebce611efa57b0242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [28] [ error [ THRIFT ERROR ]: Table ragflow _02b3b390bb8b11ef925c0242ac120006_d44bc09ebce611efa57b0242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [27] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006_d44bc09ebce611efa57b0242ac120006 doesn ' t exist 
 ragflow - infinity [00:56:36.403] [27] [ error Table ragflow 02b3b390bb8b11ef925c0242ac120006_d44bc09ebce611efa57b0242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - infinity [00:56:36.403] [27] [ error [ THRIFT ERROR ]: Table ragflow _02b3b390bb8b11ef925c0242ac120006_d44bc09ebce611efa57b0242ac120006 doesn ' t exist @ src / main / query _ context . cpp :225
 ragflow - server 2024-12-2008:56:36,408 ERROR 120
 ragflow - server Traceback ( most recent call last ):
 ragflow - server File "/ ragflow / api / apps / chunk _ app . py ", line 77, in list chunk 
 ragflow - server assert len ( d [" positions "])==0 or ( isinstance ( d [" positions "][0], list ) and len ( d [" positions "][0])==5)
 ragflow - server AssertionError 
 ragflow - server 2024-12-2008:56:36,419 INFO 20172.18.0.6--[20/Dec/202408:56:36]" POST /v1/chunk/ list HTTP /1.1"200-
 ragflow - server 2024-12-2008:56:36,420 INFO 20172.18.0.6--[20/Dec/202408:56:36]" GET /v1/chunk/ knowledge _ graph ? doc _ id =89160028bdc511ef8e870242ac120006 HTTP /1.1"200-
 ragflow - infinity [00:56:37.212][212][ info ] ScanAndOptimize opt begin ts :953
 ragflow - infinity [00:56:37.220][211][ info ] WalManager :: Checkpoint delete wal file :/ var / infinity / wal / wal . log .948
 ragflow - infinity [00:56:37.221][210][ info ] Wal / var / infinity / wal / wal . log swap to new path :/ var / infinity / wal / wal . log .952
 ragflow - infinity [00:56:37.221][210][ info ] Open new wal file / var / infinity / wal / wal . log 
 ragflow - infinity [00:56:42.215][211][ info ] WalManager :: Checkpoint delete wal file :/ var / infinity / wal / wal . log .952
 ragflow - infinity [00:56:42.216][210][ info ] Wal / var / infinity / wal / wal . log swap to new path :/ var / infinity / wal / wal . log .956
 ragflow - infinity [00:56:42.216][210][ info ] Open new wal file / var / infinity / wal / wal . log 
 ragflow - infinity [00:56:47.215][212][ info ] ScanAndOptimize opt begin ts :959

**Comment by JinHai-CN** [comment]
Related to #4109

**Comment by yuzhichang** [comment]
PR #4144  fixed following exception:
```
ragflow - server Traceback ( most recent call last ):
ragflow - server File "/ ragflow / api / apps / chunk _ app . py ", line 77, in list chunk
ragflow - server assert len ( d [" positions "])==0 or ( isinstance ( d [" positions "][0], list ) and len ( d [" positions "][0])==5)
ragflow - server AssertionError
```
