### ISSUE TITLE
[Question]: The chunk token number of general chunk method is not word for .md file 

### ISSUE THREAD

**Issue by UndefinedMan** [infiniflow/ragflow#4142]
## The situation
When building the knowledge base, I tested several `. md` documents which are Chinese papers, and the parsing results showed that almost all the content of the papers was parsed into one chunk. Can you tell me the reason? Did I do something wrong?

## One example
I have 
ragflow version: v0.14.1
upload file: chinese paper
chunk method:
![1](https://github.com/user-attachments/assets/d2e59990-a518-43b0-9df8-fcd4af1dfbbe)
chunk result: The paper is only divided into 4 chunks, and the main content of the paper is concentrated in the first chunk
![2](https://github.com/user-attachments/assets/44f73b12-1c28-4773-925a-707c966a4f04)

**Comment by JinHai-CN** [comment]
Try 0.15.0, Markdown parsing is fixed.

**Comment by surmount1** [comment]
I also encountered the same problem, but my document is in txt format. I feel that the delimiter # # # doesn't work at all, it is divided according to the length of the token.

![Image](https://github.com/user-attachments/assets/493b8f14-4ad0-4c3a-a721-9f6bb483dd36)

![Image](https://github.com/user-attachments/assets/253a373b-49b7-4837-8f01-357f6154b035)

**Comment by ellaann** [comment]
I also encountered the same problem, my document is in md format.
