### ISSUE TITLE
[Question]: Is the code on Gitee synchronized with the code on GitHub?

### ISSUE THREAD

**Issue by xxc-11** [infiniflow/ragflow#4143]
### Describe your problem

https://gitee.com/infiniflow/ragflow  and   https://github.com/infiniflow/ragflow

**Comment by yuzhichang** [comment]
https://gitee.com/infiniflow/ragflow is created and maintained by gitee.com. We don't intend to maintain this mirror.

**Comment by xxc-11** [comment]
> https://gitee.com/infiniflow/ragflow is created and maintained by gitee.com. We don't intend to maintain this mirror.

Understood, thank you for your response
