### ISSUE TITLE
[Bug]: New created agent is disappeared

### ISSUE THREAD

**Issue by winston-xing** [infiniflow/ragflow#4150]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

ragflow-0.14.1

### RAGFlow image version

ragflow-0.14.1

### Actual behavior

使用docker部署的ragflow-0.14.1，在Agent tab页，新建的agent,保存后，切换tab页， 新建的agent就不见了。

### Steps to reproduce

```Markdown
切换tab页， 新建的agent就不见了。
```

**Comment by JinHai-CN** [comment]
Can you reproduce this fault?

**Comment by JinHai-CN** [comment]
Already fixed in the new release.
