### ISSUE TITLE
[Bug]:  api：  /v1/chunk/list

### ISSUE THREAD

**Issue by asuperwei** [infiniflow/ragflow#4160]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

no

### RAGFlow image version

v0.15.0 slim

### Other environment information

```Markdown
"SCORE() / SCORE_FACTORS() requires Fusion or MATCH TEXT or MATCH TENSOR@src/planner/expression_binder.cpp:1003"
```

### Actual behavior

no 

### Steps to reproduce

```Markdown
Knowledge Base/Dataset/Chunk  click chunk list
```

**Comment by asuperwei** [comment]
I use infinity have this problem . Es no

**Comment by JinHai-CN** [comment]
#4110 already fix this issue. Please use nightly build.
