### ISSUE TITLE
[Bug]: Infinity Txn conflict

### ISSUE THREAD

**Issue by mayanlong2020** [infiniflow/ragflow#4163]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

n/a

### RAGFlow image version

nightly（v0.15.0-17-g35580af8 full）

### Other environment information

```Markdown
1.Ubuntu 24
2.Ragflow (config with Infinity engine)
```

### Actual behavior

1.Once upon a local docment is selected (I still havn't press 'confirm' button), Ragserver raised the **3022 error** list below. There no any error displayed in the frontend page.

ragflow-infinity  | [13:54:18.257] [28] [error] Table ragflow_dd78793cbfa211efaa260242ac150006_eb856922bfa211ef97d60242ac150006 doesn't exist
ragflow-infinity  | [13:54:18.257] [28] [error] Table ragflow_dd78793cbfa211efaa260242ac150006_eb856922bfa211ef97d60242ac150006 doesn't exist@src/main/query_context.cpp:225
ragflow-infinity  | [13:54:18.257] [28] [error] [THRIFT ERROR]: Table ragflow_dd78793cbfa211efaa260242ac150006_eb856922bfa211ef97d60242ac150006 doesn't exist@src/main/query_context.cpp:225
ragflow-server    | 2024-12-21 21:54:18,257 ERROR    17 (3022, "Table ragflow_dd78793cbfa211efaa260242ac150006_eb856922bfa211ef97d60242ac150006 doesn't exist@src/main/query_context.cpp:225")
ragflow-server    | Traceback (most recent call last):
ragflow-server    |   File "/ragflow/api/apps/kb_app.py", line 107, in update
ragflow-server    |     settings.docStoreConn.update({"kb_id": kb.id}, {"pagerank_fea": req["pagerank"]},
ragflow-server    |   File "/ragflow/rag/utils/infinity_conn.py", line 430, in update
ragflow-server    |     table_instance = db_instance.get_table(table_name)
ragflow-server    |   File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/utils.py", line 403, in wrapper
ragflow-server    |     return func(*args, **kwargs)
ragflow-server    |   File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/db.py", line 113, in get_table
ragflow-server    |     raise InfinityException(res.error_code, res.error_msg)
ragflow-server    | infinity.common.InfinityException: (3022, "Table ragflow_dd78793cbfa211efaa260242ac150006_eb856922bfa211ef97d60242ac150006 doesn't exist@src/main/query_context.cpp:225")

2. When I start to parse the documentation, the proccess is stop in the stage 'task has been received' over 30 mins without any issues rasied in backend and frontend before the actual parsing process started.  There is no any loading over CPU/MEM/DISK IO.
p.s. I have 20 CPUs and 64G mem, which is running the previous version RAGFLOW perfectly and the dataset was successfuly parsed by previous realsed RAGFLOW.
![log2](https://github.com/user-attachments/assets/a3a69fff-501f-406c-b29a-1956eab19e1a)

 3. After chunk has been produced (still havn't finish the whole parsing process), Infinity **error 4002** was raised when I try to drop this knowlegebase. 
 ![log3](https://github.com/user-attachments/assets/d3275b95-da00-4290-8a55-08481d2178af)

4.During the parsing process, there is **a long time waiting**（still waiting after 1 hour when I capture the log ） between each stage (from OCR started to Embedding the chunks) without any loading on CPU/MEM/DISK IO.  It seems everything is GOOD but everything is HANGING UP without doing anything. I use the RAGFLOW  nomic-text @ FastEmbeded and SILICONFLOW's chat model in system wide.

ragflow-server    | 2024-12-21 22:38:27,787 INFO     19 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-21T22:38:27.786730", "boot_at": "2024-12-21T21:51:55.278526", "pending": 1, "lag": 37, "done": 1, "failed": 0, "current": {"id": "f605ad3ebfa311efbf9d0242ac150006", "doc_id": "59bb2120bfa311efb8850242ac150006", "from_page": 12, "to_page": 24, "retry_count": 0, "kb_id": "eb856922bfa211ef97d60242ac150006", "parser_id": "book", "parser_config": {"auto_keywords": 3, "auto_questions": 1, "raptor": {"use_raptor": true, "prompt": "\u8bf7\u603b\u7ed3\u4ee5\u4e0b\u6bb5\u843d\u3002 \u5c0f\u5fc3\u6570\u5b57\uff0c\u4e0d\u8981\u7f16\u9020\u3002 \u6bb5\u843d\u5982\u4e0b\uff1a\n      {cluster_content}\n\u4ee5\u4e0a\u5c31\u662f\u4f60\u9700\u8981\u603b\u7ed3\u7684\u5185\u5bb9\u3002", "max_token": 512, "threshold": 0.1, "max_cluster": 64, "random_seed": 0}}, "name": "2023\u5e74\u7248GMP\u6307\u5357-\u8d28\u91cf\u7ba1\u7406\u4f53\u7cfb.pdf", "type": "pdf", "location": "2023\u5e74\u7248GMP\u6307\u5357-\u8d28\u91cf\u7ba1\u7406\u4f53\u7cfb.pdf", "size": 7081164, "tenant_id": "dd78793cbfa211efaa260242ac150006", "language": "Chinese", "embd_id": "nomic-ai/nomic-embed-text-v1.5@FastEmbed", "pagerank": 10, "img2txt_id": "", "asr_id": "paraformer-realtime-8k-v1@Tongyi-Qianwen", "llm_id": "THUDM/glm-4-9b-chat@SILICONFLOW", "update_time": 1734789640003}}

![log4](https://github.com/user-attachments/assets/9d8d40de-8081-4aad-b8d0-ecb88f1f8c7f)
![log5](https://github.com/user-attachments/assets/8372544f-9f33-44f3-8935-6f2fa22292a8)

### Steps to reproduce

```Markdown
upload a document and start parsing process.
```

**Comment by yuzhichang** [comment]
#4207 fixed this.

**Comment by qlanto224** [comment]
我使用的infinity:v0.6.0-dev3和ragflow:0.16.0,同样有这个问题

**Comment by 948024326** [comment]
> 我使用的infinity:v0.6.0-dev3和ragflow:0.16.0,同样有这个问题

请问大佬解决了吗？
