### ISSUE TITLE
[Bug]: Chunks info mismatch

### ISSUE THREAD

**Issue by mayanlong2020** [infiniflow/ragflow#4164]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

N/A

### RAGFlow image version

Nightly（v0.15.0-17-g35580af8 full）

### Other environment information

```Markdown
*sh show_env.sh
/usr/bin/docker
/usr/bin/python3
Current Repository: It NOT a Git repo
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Commit Id: The current directory is not a Git repository, or the Git command is not installed.
Operating system: Ubuntu 24.04 (Kernel version: 6.8.0-51-generic)
CPU Type: x86_64
Memory: 64Gi
Docker Version: 27.3.1,
Python Version: 3.12.3

* Ragflow with infinity doc engine
```

### Actual behavior
The chunks is 0 in the list. 
![image](https://github.com/user-attachments/assets/d9d81123-0c07-431c-ab99-ff790c514ec1)
But, when I click into the document chunk  detail, there are several chunks already extracted.
![企业微信截图_17347984908755](https://github.com/user-attachments/assets/9c9b6f96-9cfc-4ea6-919a-480b0402ad41)

### Steps to reproduce

```Markdown
Just check the chunk detail info.
```

_No response_

**Comment by yuzhichang** [comment]
Cannot reproduce. `Chunk Number` works for me.
![image](https://github.com/user-attachments/assets/c25a660c-c63d-4004-ac55-ade78b6c393e)

**Comment by mayanlong2020** [comment]
> Cannot reproduce. `Chunk Number` works for me. ![image](https://private-user-images.githubusercontent.com/153784/398084868-c25a660c-c63d-4004-ac55-ade78b6c393e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDE1MDksIm5iZiI6MTczNDk0MTIwOSwicGF0aCI6Ii8xNTM3ODQvMzk4MDg0ODY4LWMyNWE2NjBjLWM2M2QtNDAwNC1hYzU1LWFkZTc4YjZjMzkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODA2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzIwMzdkNDI3NzdhNjk5NGRlNWQyM2ZmMmM4YjY2ZWU0MjUxMzIxNmUwZWNkN2MzMGMxNTZjMTFlNmNlYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eGGOymHOJZ99Z7Nwd7D7iTvi-5oRHnDlLFoQGO1w2P0)

My situation is:
1. Parsing the dataset by ES.
2. As soon as the parsing finished (because I gonna change to infinity), change the doc engine to Infinity, and then re-do parsing.
the scene will be appeard.

**Comment by yuzhichang** [comment]
#4207 should have fixed this.
