### ISSUE TITLE
[Question]: After upgrading to 0.15.0, if the chat assistant is configured with rerank model and answers questions very slowly, how can this problem be solved?

### ISSUE THREAD

**Issue by xxc-11** [infiniflow/ragflow#4172]
### Describe your problem

After upgrading to 0.15.0, if the chat assistant is configured with rerank model and answers questions very slowly, how can this problem be solved?
![slow](https://github.com/user-attachments/assets/5b42786c-d3dd-4008-8599-36d80a86c0b4)

**Comment by KevinHuSh** [comment]
Which re-rank model did you choose?
Re-rank is indeed very slow by the way.

**Comment by xxc-11** [comment]
> Which re-rank model did you choose? Re-rank is indeed very slow by the way.

BAAI/bge-reranker-v2-m3
Before version 0.15.0, I felt it was very fast

**Comment by controZheng** [comment]
> > 你选择了哪种重新排序模型？顺便说一句，重新排序确实很慢。
> 
> BAAI/bge-reranker-v2-m3 在0.15.0版本之前，我感觉它非常快



> > Which re-rank model did you choose? Re-rank is indeed very slow by the way.
> 
> BAAI/bge-reranker-v2-m3 Before version 0.15.0, I felt it was very fast

I encountered this problem as well. How did you solve it?

**Comment by xxc-11** [comment]
> > > 你选择了哪种重新排序模型？顺便说一句，重新排序确实很慢。
> > 
> > 
> > BAAI/bge-reranker-v2-m3 在0.15.0版本之前，我感觉它非常快
> 
> > > Which re-rank model did you choose? Re-rank is indeed very slow by the way.
> > 
> > 
> > BAAI/bge-reranker-v2-m3 Before version 0.15.0, I felt it was very fast
> 
> I encountered this problem as well. How did you solve i t?
 0.15.1

**Comment by KevinHuSh** [comment]
What about v0.15.1?
