### ISSUE TITLE
[Bug]:  [ERROR]Internal server error while chunking: Shape instance of unrecognized shape type [ERROR]Exceptions occur, Shape instance of unrecognized shape type

### ISSUE THREAD

**Issue by itDjango** [infiniflow/ragflow#4189]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

8d73cf6

### RAGFlow image version

8d73cf6

### Other environment information

```Markdown
https://demo.ragflow.io
```

### Actual behavior

上传一个带有LINE形状的pptx文件，会报未识别到形状的错误。

![image](https://github.com/user-attachments/assets/2ff632dc-c97c-4022-bbe6-d3640cab8f64)

[新建 PPTX 演示文稿.pptx](https://github.com/user-attachments/files/18227976/PPTX.pptx)

### Expected behavior

这是一个很普通的ppt文件，希望可以正常解析

### Steps to reproduce

```Markdown
在https://demo.ragflow.io上传一个pptx文件

上传正常，但是在解析时报了无法识别形状的错误。

失败的文件：

[新建 PPTX 演示文稿.pptx](https://github.com/user-attachments/files/18227976/PPTX.pptx)

这个文件包含了LINE类型的形状，而目前ragflow并不支持
```

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/ragflow/pull/4202
