### ISSUE TITLE
[Question]: Rag startup error

### ISSUE THREAD

**Issue by HanYu666666** [infiniflow/ragflow#419]
### Describe your problem

![捕获1](https://github.com/infiniflow/ragflow/assets/76785154/00119fcb-3982-41e3-ad3d-3c05a1f60aba)
![捕获2](https://github.com/infiniflow/ragflow/assets/76785154/1d4c75d5-8769-4163-bedf-baf3dbb4a24c)
thanks very much!

**Comment by KevinHuSh** [comment]
Sorry, no clue about this.

**Comment by HanYu666666** [comment]
> Sorry, no clue about this.

it's so pity
