### ISSUE TITLE
[Question]: Mac computers: Docker-compose is unable to execute sudo sysctl -w vm.max_map_count=262144.

### ISSUE THREAD

**Issue by erichan2046** [infiniflow/ragflow#420]
### Describe your problem

Hello. I am using Docker Desktop on a Mac system and I'm unable to configure using this command.
sudo sysctl -w vm.max_map_count=262144.
 It results in a failure to start Ragflow. Could you please suggest any solutions?

By the way, I am using a Mac with an ARM architecture, and I cannot install docker-machine. Additionally, I am unable to run `screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty`. Is there a solution you could suggest?

**Comment by jaskirat-1998** [comment]
Try this:

Open the file /etc/sysctl.conf in a text editor with administrative privileges. You can use the sudo command with a text editor of your choice, such as Nano or Vim:

`sudo nano /etc/sysctl.conf`
Add the following line to the end of the file:

`vm.max_map_count=262144`

**Comment by jaskirat-1998** [comment]
> does the `ragflow-es-01` container fail for you when you try to run without setting this parameter? I think I am facing the same issue. I used `sysctl -a` command to check all the system parameters, the vm.max_map_count parameter is not present in the available system parameters on my macOS system.

In short I cannot set this parameter as it does not exist on my Mac M2 OS

**Comment by ooooo-create** [comment]
may be it's helpful.https://github.com/infiniflow/ragflow/blob/main/docs%2Fmax_map_count.md

**Comment by 1of13** [comment]
Macs running macOS do not have the vm.max_map_count parameter because it is specific to the Linux kernel. The developers added a "Dockerfile.scratch" script to help with installation on Macs with Apple silicone. However, that is not currently working either. It is too bad! I was looking forward to using Ragflow.

**Comment by FellowTraveler** [comment]
Having trouble running ragflow on M3 Silicon Mac or even building the docker:
```docker build --no-cache -t infiniflow/ragflow:dev -f Dockerfile.arm .```

Output:
```
Dockerfile.arm:7
--------------------
   6 |     COPY requirements_arm.txt /ragflow/requirements.txt
   7 | >>> RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&\
   8 | >>> python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
   9 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&python -c \"import nltk;nltk.download('punkt');nltk.download('wordnet')\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/fvay1k2wtt4fzbb2yijrj0r2t
```

**Comment by learnerLj** [comment]
> 在 M3 Silicon Mac 上运行 ragflow 甚至构建 docker 时遇到问题： `docker build --no-cache -t infiniflow/ragflow:dev -f Dockerfile.arm .`
> 
> 输出：
> 
> ```
> Dockerfile.arm:7
> --------------------
>    6 |     COPY requirements_arm.txt /ragflow/requirements.txt
>    7 | >>> RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&\
>    8 | >>> python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
>    9 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&python -c \"import nltk;nltk.download('punkt');nltk.download('wordnet')\"" did not complete successfully: exit code: 1
> 
> View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/fvay1k2wtt4fzbb2yijrj0r2t
> ```

Same problem

**Comment by dividor** [comment]
This is being looked at under this issue, where there is a proposed fix ...

https://github.com/infiniflow/ragflow/issues/1919

**Comment by yuzhichang** [comment]
@FellowTraveler @learnerLj We've published multi-arch image `ragflow:dev-slim`. Here's how we do it: https://github.com/infiniflow/ragflow/blob/main/docs/guides/develop/build_docker_image.md

**Comment by yuzhichang** [comment]
Issue fixed in PR https://github.com/infiniflow/ragflow/pull/2041
