### ISSUE TITLE
[Bug]: ES retrieval fails when docker restarts

### ISSUE THREAD

**Issue by chinamerp** [infiniflow/ragflow#4200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

a5cf6fc5460d73ed8bbef28ad61b65139288e63d

### RAGFlow image version

bbfcec2bfff1(v0.15.0-slim )

### Actual behavior

NotFoundError('index_not_found_exception', meta=ApiResponseMeta(status=404, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'content-type': 'application/vnd.elasticsearch+json;compatible-with=8', 'content-length': '569'}, duration=0.0018908977508544922, node=NodeConfig(scheme='http', host='es01', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/8.12.1 (Python/3.10.12; elastic-transport/8.12.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=False, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'index_not_found_exception', 'reason': 'no such index [ragflow_c2dcab89852411ef9af70242ac1a0006]', 'resource.type': 'index_or_alias', 'resource.id': 'ragflow_c2dcab89852411ef9af70242ac1a0006', 'index_uuid': '_na_', 'index': 'ragflow_c2dcab89852411ef9af70242ac1a0006'}], 'type': 'index_not_found_exception', 'reason': 'no such index [ragflow_c2dcab89852411ef9af70242ac1a0006]', 'resource.type': 'index_or_alias', 'resource.id': 'ragflow_c2dcab89852411ef9af70242ac1a0006', 'index_uuid': '_na_', 'index': 'ragflow_c2dcab89852411ef9af70242ac1a0006'}, 'status': 404})

### Steps to reproduce

```Markdown
docker-compose -p ragflow -f docker-compose-gpu.yml down
docker-compose -p ragflow -f docker-compose-gpu.yml up -d
```

**Comment by JinHai-CN** [comment]
How do you create the index? which method of file chunking?
