### ISSUE TITLE
 'Unknown key for a START_OBJECT in [knn].', 'line': 1, 'col': 461}, 'status': 400}) es need init？

### ISSUE THREAD

**Issue by lizhichao999** [infiniflow/ragflow#4204]
### Describe your problem

BadRequestError('parsing_exception', meta=ApiResponseMeta(status=400, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'Warning': '299 Elasticsearch-7.16.2-2b937c44140b6559905130a8650c64dbd0879cfb "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security."', 'content-type': 'application/json; charset=UTF-8', 'content-length': '237'}, duration=0.029458999633789062, node=NodeConfig(scheme='http', host='es01', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/8.12.1 (Python/3.11.9; elastic-transport/8.12.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'parsing_exception', 'reason': 'Unknown key for a START_OBJECT in [knn].', 'line': 1, 'col': 461}], 'type': 'parsing_exception', 'reason': 'Unknown key for a START_OBJECT in [knn].', 'line': 1, 'col': 461}, 'status': 400})
![1735015500948](https://github.com/user-attachments/assets/ff7acc39-b3fb-427c-ac78-a01ccc22c225)

**Comment by JinHai-CN** [comment]
Which version of ES are you using?

**Comment by lizhichao999** [comment]
7.16.2
