### ISSUE TITLE
[Question]: WS in entrypoint.sh cannot accelerate file processing

### ISSUE THREAD

**Issue by hehemagic** [infiniflow/ragflow#4205]
### Describe your problem

I compared ws of 1 and 5, the deepdoc model is not running concurrently and the processing time for the same file is longer with ws set to 5. It is not normal. Is it because there is some shared resource in the code that causes the context switch to take longer?

**Comment by yuzhichang** [comment]
Both OCR and embedding consume 10+ CPU. It's normal that enlarging WS makes the whole procedure slower.
