### ISSUE TITLE
[Question]: Batch file parsing is blocked.

### ISSUE THREAD

**Issue by YuYun329** [infiniflow/ragflow#4218]
### Version: v0.15.0 full

When I enable batch parsing, if there is one task_executor running, only one file can be parsed at a time; similarly, if there are two task_executors, only two files can be parsed at a time. The parsing of the remaining files will not make any progress, even if the previous files have been successfully parsed：

one task_executor:
![image](https://github.com/user-attachments/assets/467e7ee7-fc1e-4234-a5de-c4b15b3d9b93)

tow task_executors:
![image](https://github.com/user-attachments/assets/e8782159-65a4-4a8c-b93f-cd9970362575)

### There are no error messages in the console, and there are no logs about the parsing tasks:
![image](https://github.com/user-attachments/assets/006f307f-5222-4643-aa22-089a496b1896)

### The system status is normal：
![image](https://github.com/user-attachments/assets/6b8f5026-b3db-444d-9c5b-5a8ac4bee33e)
![image](https://github.com/user-attachments/assets/ac5c478b-624c-4992-9164-c130bc6356fb)

### I clicked the parse button from here：
![image](https://github.com/user-attachments/assets/b699f806-7748-42ea-8e5f-5d48ba067205)

**Comment by KevinHuSh** [comment]
The task executor should be like this:
![image](https://github.com/user-attachments/assets/de5363c0-97fb-497f-9b3d-63474210e915)

**Comment by YuYun329** [comment]
> The task executor should be like this: ![image](https://private-user-images.githubusercontent.com/12318111/398502481-de5363c0-97fb-497f-9b3d-63474210e915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTUwMjMsIm5iZiI6MTczNTA5NDcyMywicGF0aCI6Ii8xMjMxODExMS8zOTg1MDI0ODEtZGU1MzYzYzAtOTdmYi00OTdmLTliM2QtNjM0NzQyMTBlOTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyNDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNWMzNDBjN2FiNGY4ZWRkNzg5MzFiZGUxZGIzYWJmNjY4MjZlNDNkOTNlZGY4ODYzNGRiM2Y5N2FiMWJmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H-XxGuQiYK1W0DPKfeP0q_SgmhBIRDydhuKcNFNErQM)

May I ask what could be the possible reasons for this situation? Because parsing them one by one works fine.

**Comment by YuYun329** [comment]
> The task executor should be like this: ![image](https://private-user-images.githubusercontent.com/12318111/398502481-de5363c0-97fb-497f-9b3d-63474210e915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTUwMjMsIm5iZiI6MTczNTA5NDcyMywicGF0aCI6Ii8xMjMxODExMS8zOTg1MDI0ODEtZGU1MzYzYzAtOTdmYi00OTdmLTliM2QtNjM0NzQyMTBlOTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyNDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNWMzNDBjN2FiNGY4ZWRkNzg5MzFiZGUxZGIzYWJmNjY4MjZlNDNkOTNlZGY4ODYzNGRiM2Y5N2FiMWJmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H-XxGuQiYK1W0DPKfeP0q_SgmhBIRDydhuKcNFNErQM)

May I ask what could be the possible reasons for this situation? Because parsing them one by one works fine.

**Comment by KevinHuSh** [comment]
The host possiblly can't handle so many executor process since lack of RAM.

**Comment by YuYun329** [comment]
> The host possiblly can't handle so many executor process since lack of RAM.

OK, Thank you for your reply!
