### ISSUE TITLE
[Question]: place for tutorials for beginners

### ISSUE THREAD

**Issue by senovr** [infiniflow/ragflow#4246]
### Describe your problem

Hi there,

I hope I didn't miss anything, but are there any step-by-step tutorials available (e.g., on YouTube) that demonstrate how to achieve specific use cases with ragflow?

For example, you have an excellent blog post about using GraphRag to analyze relationships in the Game of Thrones dataset. It would be incredibly helpful if you could provide more detailed instructions, such as:

Take these files.
Upload them.
Choose these entities (and explain why, as well as any alternative entities that can be extracted/used). ...
Additionally, I would like to upvote for the feature of reconstructing multiple documents with GraphRag. Imagine having a codebase with folders and files, and wanting to better understand which files do what and how they are inter-related. This seems like a great use case.

Thank you!

**Comment by writinwaters** [comment]
Hi @senovr 

Thanks for the suggestions. Agreed that our step-by-step tutorials are still on the thin side. We are currently refactoring our docs for agents, and the GraphRAG tutorial is also on our to-do list. Should be ready in the first half of January. 

Also, GraphRAG appears as a chunk method in knowledge base configurations. For the time being, you may want to try our demo.ragflow.io, making sure you choose the right entity type.

Cheers.
