### ISSUE TITLE
[Bug]: I can't register or login to the ragflow

### ISSUE THREAD

**Issue by JieWade** [infiniflow/ragflow#4268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

latest

### RAGFlow image version

infiniflow/ragflow:v0.15.1-slim

### Actual behavior

<img width="716" alt="image" src="https://github.com/user-attachments/assets/d253b746-a08a-450d-a254-ca8b9c629da6" />
<img width="662" alt="image" src="https://github.com/user-attachments/assets/675bb9a3-9e79-4780-93c9-0d909036ff43" />

### Steps to reproduce

```Markdown
can't login
```

**Comment by KevinHuSh** [comment]
Check the error message from backend service.
`docker logs -f ragflow-server`

**Comment by ODAncona** [comment]
Make sure all your services are up and running. with `docker logs -f ragflow-server`

**Comment by JieWade** [comment]
> Make sure all your services are up and running. with `docker logs -f ragflow-server`

<img width="955" alt="image" src="https://github.com/user-attachments/assets/3df28de9-ca69-49b3-a546-fcdf8630d91f" />
<img width="801" alt="image" src="https://github.com/user-attachments/assets/f74be78b-1187-4883-8ce8-235769fa9539" />
above is the logs

**Comment by JieWade** [comment]
> Check the error message from backend service. `docker logs -f ragflow-server`

<img width="801" alt="image" src="https://github.com/user-attachments/assets/6ce88d03-54dd-4105-9fa2-9bbbee6f3fe7" />
here is the logs

**Comment by JieWade** [comment]
I have installed ragflow on 3 devices ,one windos PC successed to login. Another windos PC and a linux PC caused the same bug,can't login.

**Comment by JinHai-CN** [comment]
RAGFlow depends on python module: polars which need CPU supporting AVX2. Check the CPU of your host.

**Comment by JieWade** [comment]
> RAGFlow depends on python module: polars which need CPU supporting AVX2. Check the CPU of your hos

**Comment by JieWade** [comment]
I have solved the problem use polars-lts-gpu instead of polars which can fix the bug.

**Comment by twyl3513** [comment]
> I have solved the problem use polars-lts-gpu instead of polars which can fix the bug.

 I met same problem ，how to solve to use polars-lts-cpu instead of polars,thank you

**Comment by binary2010** [comment]
in the ragflow-server container ,install polars-lts-cpu
```bash
pip install polars-lts-cpu
```

**Comment by wrtz008** [comment]
I am getting same error, tried the polars but without success : /
