### ISSUE TITLE
[Bug]: [ERROR] Can not find file<11111111.txt>

### ISSUE THREAD

**Issue by hmltzb** [infiniflow/ragflow#427]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

task_executor.py

### Commit ID

zzzzzzzz2334e

### Other environment information

```Markdown
满足环境要求
```

### Actual behavior

满足

### Expected behavior

镜像获取：从测试机pull原始镜像打包拷贝到正式服务器
Dockerfile：由于正式服务器版本问题对Dockerfile文件进行改造，见附件：
[docker-compose-new.txt](https://github.com/infiniflow/ragflow/files/15021397/docker-compose-new.txt)
页面报错：见附件：
![微信图片_20240418153933](https://github.com/infiniflow/ragflow/assets/157361804/709f281f-88bb-49c9-8af1-02bd4be7e94b)

### Steps to reproduce

```Markdown
操作步骤：
1、正式启动 docker compose -f docker-compose-new.yml up -d 文件  镜像正常启动
2、进入ragflow_server 容器将挂载的rag/res/deepdoc、rag/res/bge-large-zh-v1.5 ---> cp 到 ~/.cache 中
3、重启ragflow_server 容器
4、进入页面-->创建知识库-->加入文件
```

### Additional information

ragflow-server logs:

LOADING BCE...
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 130, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/naive.py", line 145, in chunk
    with open(filename, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '111111111.txt'

rag/res/logs/Error.log:

fail get 2143d108fd5111eeb7990242ac1d0006/111111111.txt: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /2143d108fd5111eeb7990242ac1d0006, request_id: 17C74DC27AE5E1F2, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 2143d108fd5111eeb7990242ac1d0006
Chunkking 111111111.txt/111111111.txt: [Errno 2] No such file or directory: '111111111.txt'

**Comment by JinHai-CN** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

**Comment by KevinHuSh** [comment]
1. Check if the minio is healthy.
2. Check the configuration of user name and password in both docker/.env and docker/service_conf.yml. Keep them consistent.
