### ISSUE TITLE
[Question]:  一个用户下所有知识库的切片放在一个es index里， 如果不同的知识库用了不同的embedding model该如何做向量匹配呢？

### ISSUE THREAD

**Issue by qiankunli** [infiniflow/ragflow#429]
### Describe your problem

根据对源码的初步学习，每个切片 都有kb_id, doc_id 等属性，一个用户下所有知识库的切片放在一起的，即一个用户一个es index。

一般情况下，一个kb用一个embedding 模型，向量匹配时，对query也用同样的embedding model 计算vector，进而获取topk条记录。

那如果不同的知识库用了不用的embedding model，混在一起检索的话，对于用户的query 总要指定一个embedding model 计算一个向量，会不会有错乱呢？代码细节较多，对这块有一些疑问，请多指教。

**Comment by KevinHuSh** [comment]
It will recieve error message if embedding model mismatched between knowledge base.

Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊
