### ISSUE TITLE
[Bug]: Your demo page login mechanism is very buggy

### ISSUE THREAD

**Issue by IAmRobotic** [infiniflow/ragflow#4296]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

DEMO

### RAGFlow image version

DEMO

### Actual behavior

Keeps logging me out and essentially I keep staying in a loop logging in and getting logged out

### Steps to reproduce

```Markdown
Simply try to login and stay logged in for the demo. Tried it both with Github login as well as with a separate email address.
```

**Comment by KevinHuSh** [comment]
Fixed now.
