### ISSUE TITLE
[Question]: Already set to use infinity， why RAGFlow still connect to ES？

### ISSUE THREAD

**Issue by cony323** [infiniflow/ragflow#4298]
### Describe your problem

**.env配置：DOC_ENGINE=${DOC_ENGINE:-infinity}**
启动ragflow时一直报错：
[WARNING] [2024-12-31 10:34:12,285] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
[WARNING] [2024-12-31 10:34:12,285] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fa6055cd250>: Failed to resolve 'es01' ([Errno -2] Name or service not known))

**Comment by JinHai-CN** [comment]
1. Which version of RAGFlow ?
2. Please follow the guide:
https://github.com/infiniflow/ragflow?tab=readme-ov-file#switch-doc-engine-from-elasticsearch-to-infinity

**Comment by cony323** [comment]
thank you~
