### ISSUE TITLE
[Question]: Cannot parse all types of files

### ISSUE THREAD

**Issue by HanYu666666** [infiniflow/ragflow#430]
### Describe your problem

Cannot parse all types of files
![微信截图_20240418162759](https://github.com/infiniflow/ragflow/assets/76785154/f878d0df-e04e-4b8d-b298-b7cd810f8cdd)

**Comment by HanYu666666** [comment]
![Uploading 微信截图_20240418163855.png…]()

**Comment by HanYu666666** [comment]
![微信截图_20240418163855](https://github.com/infiniflow/ragflow/assets/76785154/a3e6a6b1-6168-432a-aa06-0e469b08bab0)

**Comment by KevinHuSh** [comment]
1. Is it locally deployed? Have a look at the FAQ.
2. Only docx supported yet.
