### ISSUE TITLE
Help!!!! : [ERROR] Can not find file<11111111.txt>

### ISSUE THREAD

**Issue by hmltzb** [infiniflow/ragflow#432]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

task_executor.py

### Commit ID

zzzzzzzz2334ewertwe

### Other environment information

```Markdown
Meet environmental requirements
```

### Actual behavior

Image acquisition: Pull the original image from the testing machine, package and copy it to the official server.

Dockerfile: Due to issues with the official server version, the Dockerfile file has been modified. Please refer to the attachment:
[docker-compose-new.txt](https://github.com/infiniflow/ragflow/files/15022662/docker-compose-new.txt)

Page error: see attachment:
![微信图片_20240418153933](https://github.com/infiniflow/ragflow/assets/157361804/4e4b859c-a555-4c59-9e9a-72bfe1a28005)

### Expected behavior

The parsing went smoothly, but an error occurred

### Steps to reproduce

```Markdown
Operation steps:
1. Formally start Docker Compose - f Docker Compose new. yml up - d file image starts normally
2. Enter the ragflow_server container and transfer the mounted rag/res/deepdoc, rag/res/bge target zh v1.5-->cp to~/. cache
3. Restart the ragflow_server container
4. Enter the page ->Create knowledge base ->Add file
```

### Additional information

ragflow-server logs:

LOADING BCE...
Traceback (most recent call last):
File "/ragflow/rag/svr/task_executor.py", line 130, in build
cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/app/naive.py", line 145, in chunk
with open(filename, "r") as f:
^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '111111111.txt'

rag/res/logs/Error.log:

fail get 2143d108fd5111eeb7990242ac1d0006/111111111.txt: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /2143d108fd5111eeb7990242ac1d0006, request_id: 17C74DC27AE5E1F2, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: 2143d108fd5111eeb7990242ac1d0006
Chunkking 111111111.txt/111111111.txt: [Errno 2] No such file or directory: '111111111.txt'

**Comment by KevinHuSh** [comment]
1. Check if the minio is healthy.
2. Check the configuration of user name and password in both docker/.env and docker/service_conf.yml. Keep them consistent.
