### ISSUE TITLE
[Feature Request]: Provide docker image for Mac with ARM 

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/ragflow#434]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

There are several builtin models depending on PyTorch, ONNXRuntime,...,etc, which requires extra works for migrating.

**Comment by yingfeng** [comment]
@KevinHuSh pls give some instructions to build mac images.

**Comment by KevinHuSh** [comment]
ragflow/Dockerfile.scratch has every necessary steps to build an image.

**Comment by 1of13** [comment]
Hi. I tried using Dockerfile.scratch and the image was not built successfully. Would you mind writing detailed instructions on how to set up on Mac with ARM?

**Comment by 1of13** [comment]
The Dockerfile.scratch file has many issues. For example, it points to the wrong URL for Miniconda3. It should be something like this: https://repo.anaconda.com/miniconda/Miniconda3-py311_24.3.0-0-MacOSX-arm64.sh, instead of the "... latest-Linux-x86_64 ..." used in the script. The latest version of Miniconda3 uses Python3.12, and consequently, some of the libraries included in the requirements are incompatible, as they require Python3.11 at most.

**Comment by zhengwu119** [comment]
> I tried to run it on Oracle's ARM host and rebuild docker image. I removed some packages which isn't supported on ARM platform such as Aspose.Slides and N-card. Therefore, Some features won't work any more, for example, Powerpoint file isn't support any more. Updated requirements.txt and Dockerfile.scratch are attached. [requirements.txt](https://github.com/infiniflow/ragflow/files/15110515/requirements.txt) [Dockerfile.scratch.txt](https://github.com/infiniflow/ragflow/files/15110522/Dockerfile.scratch.txt)

it works!

**Comment by qmy777** [comment]
> I tried to run it on Oracle's ARM host and rebuild docker image. I removed some packages which isn't supported on ARM platform such as Aspose.Slides and N-card. Therefore, Some features won't work any more, for example, Powerpoint file isn't support any more. Updated requirements.txt and Dockerfile.scratch are attached. [requirements.txt](https://github.com/infiniflow/ragflow/files/15110515/requirements.txt) [Dockerfile.scratch.txt](https://github.com/infiniflow/ragflow/files/15110522/Dockerfile.scratch.txt)

Excuse me. How to run zhe docker image with the changed files？
I just known how to use docker compose run the program in the docker folder

**Comment by chminsc** [comment]
does it support mps on Mac M1 chip?

**Comment by FellowTraveler** [comment]
Having trouble running ragflow on M3 Silicon Mac or even building the docker:
```docker build --no-cache -t infiniflow/ragflow:dev -f Dockerfile.arm .```

Output:
```
Dockerfile.arm:7
--------------------
   6 |     COPY requirements_arm.txt /ragflow/requirements.txt
   7 | >>> RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&\
   8 | >>> python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
   9 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&python -c \"import nltk;nltk.download('punkt');nltk.download('wordnet')\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/fvay1k2wtt4fzbb2yijrj0r2t
```

**Comment by yangboz** [comment]
> Having trouble running ragflow on M3 Silicon Mac or even building the docker: `docker build --no-cache -t infiniflow/ragflow:dev -f Dockerfile.arm .`
> 
> Output:
> 
> ```
> Dockerfile.arm:7
> --------------------
>    6 |     COPY requirements_arm.txt /ragflow/requirements.txt
>    7 | >>> RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&\
>    8 | >>> python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
>    9 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c pip install -i https://mirrors.aliyun.com/pypi/simple/ --default-timeout=1000 -r requirements.txt &&python -c \"import nltk;nltk.download('punkt');nltk.download('wordnet')\"" did not complete successfully: exit code: 1
> 
> View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/fvay1k2wtt4fzbb2yijrj0r2t
> ```

same here, 
and 
```
ERROR [linux/amd64 internal] load metadata for docker.io/library/python:3.11
```

any idea ?

**Comment by yuzhichang** [comment]
We've published multi-arch image `ragflow:dev-slim`. Here's how we do it: https://github.com/infiniflow/ragflow/blob/main/docs/guides/develop/build_docker_image.md

**Comment by peterzyk** [comment]
> 我们已经发布了多架构镜像`ragflow:dev-slim`。具体操作如下：https: [//github.com/infiniflow/ragflow/blob/main/docs/guides/develop/build_docker_image.md](https://github.com/infiniflow/ragflow/blob/main/docs/guides/develop/build_docker_image.md)

这个链接失效了

**Comment by KevinHuSh** [comment]
[Here](https://github.com/infiniflow/ragflow?tab=readme-ov-file#-build-a-docker-image-without-embedding-models).

**Comment by HendrikSchoettle** [comment]
For anyone still looking for this: I built a fully automated, idempotent build pipeline that produces native ARM64 Docker images for RAGFlow v0.24.0, tested on NVIDIA DGX Spark (Grace CPU / GB10 Blackwell GPU, SM_121).

It patches the upstream Dockerfiles at build time, compiles an onnxruntime-gpu wheel from source for SM_121 / CUDA 13, and includes several bug fixes for European-language deployments (encoding detection, multilingual OCR, AVIF support, IMAP connector crash).

It's jus a small and quick-and-dirty standalone script package that wraps the existing repo:
https://github.com/HendrikSchoettle/ragflow-dgx-spark
