### ISSUE TITLE
[Question]: The page loads slowly after display

### ISSUE THREAD

**Issue by Alchemistqqqq** [infiniflow/ragflow#441]
### Describe your problem

After you helped me solve the problem in the morning, I also successfully displayed the output you said
![image](https://github.com/infiniflow/ragflow/assets/146717415/61d7434e-b597-4528-96f3-f40cdbc72418)
Since I'm using vscode to connect to a remote server, I noticed localhost: 5601 in the bottom right corner
![image](https://github.com/infiniflow/ragflow/assets/146717415/eebc8050-42d6-4b57-82bf-0fff08db3233)
But I have been waiting for about 1-2 hours and nothing has changed. Is it that the page I entered is wrong or I need to be patient and wait a little longer? I'm sorry to trouble you to help me solve the problem again, thank you!

**Comment by Alchemistqqqq** [comment]
Sorry, I'm a beginner. This port is the port that vscode pops up on startup. I remotely connect to the server is a command line, how can I view the results of the operation.

**Comment by KevinHuSh** [comment]
It uses nginx to support web service. So, 80 is the default port number.
