### ISSUE TITLE
[Feature Request]: Markdown and JSON Support

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#443]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Can you allow importation and importing of markdown documents?
```

### Describe the feature you'd like

Can you allow importation and importing of markdown documents?

### Additional information

Can you allow importation and importing of markdown documents?

**Comment by chinamerp** [comment]
+1

**Comment by ARSblithe212** [comment]
+1

**Comment by KevinHuSh** [comment]
supported
