### ISSUE TITLE
[Bug]: parse pdf file error

### ISSUE THREAD

**Issue by ben-qiao** [infiniflow/ragflow#444]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

fjoiesjf0923iur092jdpo2

### Other environment information

```Markdown
linux
docker install ragflow
copy deepdoc model manually because of the "No such file or directory: '/ragflow/rag/res/deepdoc/ocr.res'be0c1e50eef6047b412d1800aa89aba4d275f997/ocr.res"
```

### Actual behavior

the ragflow start normally.
but when import pdf file, it report error:
Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

### Expected behavior

the pdf file can be parsed normally

### Steps to reproduce

```Markdown
create a knowledge base and then import pdf file
```

**Comment by Jiafan** [comment]
I have tested with the pdf file on my server , It works fine.

![Screenshot 2024-04-19 at 10 10 49](https://github.com/infiniflow/ragflow/assets/10692668/225a90ec-b08e-4009-906d-358ce9856ad6)

But I have checked my docker path. The `ocr.res` file located in `/ragflow/rag/res` : `/ragflow/rag/res/ocr.res` .

![Screenshot 2024-04-19 at 10 13 27](https://github.com/infiniflow/ragflow/assets/10692668/534f2301-a077-4556-8e7e-fe0172464c54)

**Comment by ben-qiao** [comment]
> I have tested with the pdf file on my server , It works fine.
> 
> ![Screenshot 2024-04-19 at 10 10 49](https://private-user-images.githubusercontent.com/10692668/323810157-225a90ec-b08e-4009-906d-358ce9856ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTQ3MTIsIm5iZiI6MTcxMzQ5NDQxMiwicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTAxNTctMjI1YTkwZWMtYjA4ZS00MDA5LTkwNmQtMzU4Y2U5ODU2YWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyNDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMTBkNzEzZWEyMzBiMGFhMmZhZmQ5MzRlMDBjMTM0ODk0NzE0NzFjM2Y0MDZjY2E5NTZmZGFmODYyNjY3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHL3HdTONNp7Ly5Igen2Dclf6M8Vpe7gq4X_ErW-B5g)
> 
> But I have checked my docker path. The `ocr.res` file located in `/ragflow/rag/res` : `/ragflow/rag/res/ocr.res` . It's different than the path you mentioned
> 
> @ben-qiao
> 
> ![Screenshot 2024-04-19 at 10 13 27](https://private-user-images.githubusercontent.com/10692668/323810604-534f2301-a077-4556-8e7e-fe0172464c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTQ3MTIsIm5iZiI6MTcxMzQ5NDQxMiwicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTA2MDQtNTM0ZjIzMDEtYTA3Ny00NTU2LThlN2UtZmUwMTcyNDY0YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyNDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjcyNTkzMzU4N2ZlYTA1MDVkM2U4OTdjZTA2MGNkMGRlMjFlZTVhNTdjNmZmMWUxMjVhZGM3MTQzOTk1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xeoOnARJ5JlU80b6au7OsQX277ANHoVYLU5jkGfeKSc)



> I have tested with the pdf file on my server , It works fine.
> 
> ![Screenshot 2024-04-19 at 10 10 49](https://private-user-images.githubusercontent.com/10692668/323810157-225a90ec-b08e-4009-906d-358ce9856ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTQ3MTIsIm5iZiI6MTcxMzQ5NDQxMiwicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTAxNTctMjI1YTkwZWMtYjA4ZS00MDA5LTkwNmQtMzU4Y2U5ODU2YWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyNDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMTBkNzEzZWEyMzBiMGFhMmZhZmQ5MzRlMDBjMTM0ODk0NzE0NzFjM2Y0MDZjY2E5NTZmZGFmODYyNjY3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHL3HdTONNp7Ly5Igen2Dclf6M8Vpe7gq4X_ErW-B5g)
> 
> But I have checked my docker path. The `ocr.res` file located in `/ragflow/rag/res` : `/ragflow/rag/res/ocr.res` . It's different than the path you mentioned
> 
> @ben-qiao
> 
> ![Screenshot 2024-04-19 at 10 13 27](https://private-user-images.githubusercontent.com/10692668/323810604-534f2301-a077-4556-8e7e-fe0172464c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTQ3MTIsIm5iZiI6MTcxMzQ5NDQxMiwicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTA2MDQtNTM0ZjIzMDEtYTA3Ny00NTU2LThlN2UtZmUwMTcyNDY0YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyNDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjcyNTkzMzU4N2ZlYTA1MDVkM2U4OTdjZTA2MGNkMGRlMjFlZTVhNTdjNmZmMWUxMjVhZGM3MTQzOTk1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xeoOnARJ5JlU80b6au7OsQX277ANHoVYLU5jkGfeKSc)

i checked my path, the ocr.res file is same path:
![image](https://github.com/infiniflow/ragflow/assets/42063239/f5339386-508e-4775-8551-3aa64b8c0dce)

**Comment by KevinHuSh** [comment]
> I have tested with the pdf file on my server , It works fine.
> 
> ![Screenshot 2024-04-19 at 10 10 49](https://private-user-images.githubusercontent.com/10692668/323810157-225a90ec-b08e-4009-906d-358ce9856ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTc3MDMsIm5iZiI6MTcxMzQ5NzQwMywicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTAxNTctMjI1YTkwZWMtYjA4ZS00MDA5LTkwNmQtMzU4Y2U5ODU2YWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDAxOThmNjNlYzkxNDFlNjQwYzkyZWQ5NDNhMDAzMTU5ZjY5MjVjOGUxMDY2YTljN2ViNmRlZjNiZjcwNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84MZh2AJgezn6G-Ui1aoYmYQBLyw4w4oBv3vSTv4gmM)
> 
> But I have checked my docker path. The `ocr.res` file located in `/ragflow/rag/res` : `/ragflow/rag/res/ocr.res` . It's different than the path you mentioned
> 
> @ben-qiao
> 
> ![Screenshot 2024-04-19 at 10 13 27](https://private-user-images.githubusercontent.com/10692668/323810604-534f2301-a077-4556-8e7e-fe0172464c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTc3MDMsIm5iZiI6MTcxMzQ5NzQwMywicGF0aCI6Ii8xMDY5MjY2OC8zMjM4MTA2MDQtNTM0ZjIzMDEtYTA3Ny00NTU2LThlN2UtZmUwMTcyNDY0YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAzMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNzkzNDM3ZDlhMDAxNzY5MjE5YjBmNTYzMDljZjg2NzVhMDIzZjVjNzk1ZjU4YmQ3NGM3MWEyYWUwMDE3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vS-v1Ru3TZuPgOjOEOYzD-ERwppmPxrDrt0Z8bmCTO4)

1. Manually download the resource files from huggingface.co/[InfiniFlow/deepdoc](https://huggingface.co/InfiniFlow/deepdoc) to your local folder ~/deepdoc. 
2. Add a volumes to docker-compose.yml, for example:
 - ~/deepdoc:/ragflow/rag/res/deepdoc

**Comment by KevinHuSh** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> fjoiesjf0923iur092jdpo2
> 
> ### Other environment information
> ```
> linux
> docker install ragflow
> copy deepdoc model manually because of the "No such file or directory: '/ragflow/rag/res/deepdoc/ocr.res'be0c1e50eef6047b412d1800aa89aba4d275f997/ocr.res"
> ```
> 
> ### Actual behavior
> the ragflow start normally. but when import pdf file, it report error: Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again. Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again. Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again. Chunkking Java开发手册(黄山版).pdf/Java开发手册(黄山版).pdf: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
> 
> ### Expected behavior
> the pdf file can be parsed normally
> 
> ### Steps to reproduce
> ```
> create a knowledge base and then import pdf file
> ```
> 
> ### Additional information
> _No response_

If it happened on demo website, please delete and upload  again.
If it's local, check the status of minio.

**Comment by ben-qiao** [comment]
> * ragflow/rag/res/deepdoc

i download deepdoc from huggingface and add a volumes to docker-compose.yml, after ragflow startup, i import pdf file to kb, and get a new error:

'''
WARNING] [2024-04-19 16:22:04,334] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/deepdoc/parser/pdf_parser.py", line 42, in __init__
    self.updown_cnt_mdl.load_model(os.path.join(
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/core.py", line 2588, in load_model
    _check_call(_LIB.XGBoosterLoadModel(self.handle, c_str(fname)))
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:22:07] /workspace/dmlc-core/src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "/ragflow/rag/res/deepdoc/updown_concat_xgb.model": No such file or directory
Stack trace:
  [bt] (0) /root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x1ba24e) [0x7f002eec424e]
  [bt] (1) /root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0xcc9637) [0x7f002f9d3637]
  [bt] (2) /root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0xcb54ce) [0x7f002f9bf4ce]
  [bt] (3) /root/miniconda3/envs/py11/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(XGBoosterLoadModel+0x18e) [0x7f002ee78ace]
  [bt] (4) /root/miniconda3/envs/py11/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f0157371052]
  [bt] (5) /root/miniconda3/envs/py11/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f015736f925]
  [bt] (6) /root/miniconda3/envs/py11/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f015737006e]
  [bt] (7) /root/miniconda3/envs/py11/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x92ba) [0x7f01573812ba]
  [bt] (8) /root/miniconda3/envs/py11/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x87e3) [0x7f01573807e3]

'''

**Comment by ben-qiao** [comment]
it is a configuration problem. i pull new version 0.3.0,and run docker with **docker-compose-CN.yml**(before a run docker-compose.yml). then import pdf, the file is parsed successfully.
add new config in docker-compose-CN.yml:
- ./deepdoc:/ragflow/rag/res/deepdoc
