### ISSUE TITLE
[Question]: I want to validate the PDF information extraction scheme of ragflow, but I  can not run the code in /rag/app/presentation.py locally.

### ISSUE THREAD

**Issue by lanbowcn** [infiniflow/ragflow#452]
### Describe your problem

Some dependencies cannot be installed on my machine, and it seems that other service components are needed to start the program. 

Could you give me some guidance on how to run it（”/rag/app/presentation.py“）?

**Comment by KevinHuSh** [comment]
Enter into the container to do your job.
