### ISSUE TITLE
Unnecessary repetition

### ISSUE THREAD

**Issue by waiking1970** [infiniflow/ragflow#456]
Due to length reasons, the answer was truncated. When I continued to answer, the system continued to ask repeatedly whether to continue. The problem is shown in the following figure:
![bug](https://github.com/infiniflow/ragflow/assets/167077064/d4417fee-61c7-43d7-a70d-42ac19baab96)

**Comment by KevinHuSh** [comment]
There's not any good method to solve it except enlarging token length.
