### ISSUE TITLE
[Question]: LookupError('Model(gpt-4-turbo) not authorized')

### ISSUE THREAD

**Issue by wangkaies** [infiniflow/ragflow#457]
### Describe your problem

What does this mean? I have valid open api key that works all good on demo.ragflow.io, but when I try it on my local ragflow, it shows this error. I'm using ragflow-0.2.0 docker, and gpt-3.5 works as well.

**Comment by KevinHuSh** [comment]
Pull the latest version 0.3.0.
Remove all the data using 'compose down -v' if it's possible.
