### ISSUE TITLE
[Question]: Error in "pip.exe install -r requirements.txt"

### ISSUE THREAD

**Issue by sunshine19870316** [infiniflow/ragflow#460]
### Describe your problem

I'm build this repro on windows,
when I run “pip.exe install -r requirements.txt”
failed with different python versions,

If my python is 3.9 version, with below error info：
_ERROR: Ignored the following versions that require a different python version: 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement nvidia-nccl-cu12==2.21.5 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-nccl-cu12==2.19.3_

when I changed to 3.10，with below error info：
_ERROR: Ignored the following versions that require a different python version: 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.4.0 Requires-Python >=3.5,<3.10
ERROR: Could not find a version that satisfies the requirement nvidia-nccl-cu12==2.21.5 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-nccl-cu12==2.19.3_

I'm confused about the python version.

**Comment by KevinHuSh** [comment]
Could you use python 3.11? 
This might easier to make it work.

**Comment by liuhuapiaoyuan** [comment]
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.10.0 Requires-Python >=3.5,<3.11; 22.11.0 Requires-Python >=3.5,<3.11; 22.12.0 Requires-Python >=3.5,<3.11; 22.4.0 Requires-Python >=3.5,<3.10; 22.6.0 Requires-Python >=3.5,<3.11; 22.7.0 Requires-Python >=3.5,<3.11; 22.8.0 Requires-Python >=3.5,<3.11; 22.9.0 Requires-Python >=3.5,<3.11; 23.1.0 Requires-Python >=3.5,<3.11; 23.2.0 Requires-Python >=3.5,<3.11; 23.3.0 Requires-Python >=3.5,<3.11; 23.4.0 Requires-Python >=3.5,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-nccl-cu12==2.19.3 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-nccl-cu12==2.19.3


when i u se 3.11.9 , i get same error

**Comment by liuhuapiaoyuan** [comment]
I know... use aliyun cdn resolve this error...
```
 pip install -i https://mirrors.aliyun.com/pypi/simple/ -r ./requirements.txt
```

**Comment by liguochuan00** [comment]
python version : 3.11.0
i use  pip install -i https://mirrors.aliyun.com/pypi/simple/ -r ./requirements.txt Still this error.

error message:
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.10.0 Requires-Python >=3.5,<3.11; 22.11.0 Requires-Python >=3.5,<3.11; 22.12.0 Requires-Python >=3.5,<3.11; 22.4.0 Requires-Python >=3.5,<3.10; 22.6.0 Requires-Python >=3.5,<3.11; 22.7.0 Requires-Python >=3.5,<3.11; 22.8.0 Requires-Python >=3.5,<3.11; 22.9.0 Requires-Python >=3.5,<3.11; 23.1.0 Requires-Python >=3.5,<3.11; 23.2.0 Requires-Python >=3.5,<3.11; 23.3.0 Requires-Python >=3.5,<3.11; 23.4.0 Requires-Python >=3.5,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==8.9.2.26 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 8.9.6.50, 8.9.7.29, 9.0.0.312, 9.1.0.70)
ERROR: No matching distribution found for nvidia-cudnn-cu12==8.9.2.26
