### ISSUE TITLE
[Question]: Vector Similarity 0.00 in Retrieval test

### ISSUE THREAD

**Issue by Kryto614** [infiniflow/ragflow#464]
### Describe your problem

I'm running a retrieval testing with default parameters, and after entering a query, all the vector similarities of the retrieval chunks are showing up as 0.00. What might be the problem?

**Comment by KevinHuSh** [comment]
The vector similarity weight might be 0,  isn't it?

**Comment by Kryto614** [comment]
> The vector similarity weight might be 0, isn't it?

It retrieves the correct chunk and gives perfect response in chat mode, but fails to retrieve corresponding chunks revant to the same query in the Retrieval test.

Additionally, the background log shows that Elasticsearch appears to have not connected correctly. I'm not sure if there's a connection between the two.

```
elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7cac61f4d950>: Failed to resolve 'es01' ([Errno -3] Temporary failure in name resolution))
[WARNING] [2024-04-21 16:22:45,734] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout
[WARNING] [2024-04-21 16:22:46,741] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-04-21 16:22:46,741] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
```

**Comment by KevinHuSh** [comment]
If you use docker, please check the network part in docker-compose-base.yaml.

**Comment by Defozo** [comment]
I have the same problem. Elasticsearch seems to be connected OK based on what can be seen in the web interface. Vector similarities are always 0.00 for every chunk.

**Comment by Defozo** [comment]
How to debug this?

**Comment by vlianCMU** [comment]
Exactly same problem, how did you solve this?
