### ISSUE TITLE
[Question]: Cannot save the system model setting

### ISSUE THREAD

**Issue by saminbj** [infiniflow/ragflow#468]
### Describe your problem

The following msg appear stop me from saving changes:
```
hint : 101
required argument are missing: img2txt_id;
```
I even could not append /v1/ after ip address, a page appears:
{
    "data": null,
    "retcode": 100,
    "retmsg": "<NotFound '404: Not Found'>"
}

**Comment by KevinHuSh** [comment]
What do you mean by saving system model?

**Comment by saminbj** [comment]
Thank you very much for your concern.  Please kindly see the following capture maybe more self-explanatory:
![capture_20240421202658719](https://github.com/infiniflow/ragflow/assets/35366696/a8afc28d-6080-4f91-aa81-53230658a4fc)

I found from your faq that the ip address should add /v1/, however the following capture found:
![capture_20240421202608926](https://github.com/infiniflow/ragflow/assets/35366696/9c677ee7-42af-4048-ae13-9191ead70f43)

I have also the same problem of warning receive about no redis connection:"[WARNING] [2024-04-21 18:35:06,188] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection." as per other issue post.

It seems to be most of these errors from WSL users???  I had tried so many times and follows your installation guide strictly and very very carefully for over ten times, however this problem persist me to add ollama and xinference whereas others features are functioning properly and very impressive!  Thanks indeed for you contribution and hope to solve this problem soonest so that i could show off to my friend with my ragflow knowledgebot.

**Comment by yurochang** [comment]
same problem........

**Comment by yurochang** [comment]
![image](https://github.com/infiniflow/ragflow/assets/26240758/97192022-fcdd-4a83-958c-53a5cf664616)

**Comment by ifredom** [comment]
The same question

windows 10.
![image](https://github.com/infiniflow/ragflow/assets/13759936/0eb9cc22-0327-411b-8e33-4954a376d795)
![image](https://github.com/infiniflow/ragflow/assets/13759936/dcdf97e1-c613-4550-9ca9-f86d3fd75595)
