### ISSUE TITLE
[Question]: How can I remove myself from https://demo.ragflow.io/ 

### ISSUE THREAD

**Issue by wrfly** [infiniflow/ragflow#473]
### Describe your problem

I have put my OpenAI personal access token to it, but I couldn't find anywhere to delete this token.

Also I found that the token stored in MySQL is plantext which is unsafe.

I want to unregister myself from https://demo.ragflow.io/ (the user name is `please-delete-me`)

**Comment by KevinHuSh** [comment]
Deleted already.
If you have concern about that, could you disable your key in OpenAI website?
