### ISSUE TITLE
[Bug]: the new assitant response "prompt_eval_count"

### ISSUE THREAD

**Issue by ben-qiao** [infiniflow/ragflow#477]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

fsfafu930ir2ri2prk2r2ff

### Other environment information

```Markdown
ragflow 0.3.0
```

### Actual behavior

1. start ragflow
2. create new knowledge base
3. upload and parse file normaly
4. create a new assistant and say hello. the assistang response error. then ask hello again ,the assistant response normally

![image](https://github.com/infiniflow/ragflow/assets/42063239/d42694bb-364a-457c-8a4b-9be7b0f782c4)

### Steps to reproduce

```Markdown
as actual behavior
```

**Comment by KevinHuSh** [comment]
fixed
