### ISSUE TITLE
is it possible, to use this only as a search engine? [Question]: 

### ISSUE THREAD

**Issue by JahnKhan** [infiniflow/ragflow#484]
### Describe your problem

Hi there,

I'm currently exploring the possibility of using Ragflow for implementing a search engine in my project. Specifically, I'm interested in building a search app that can:
1. Accept user queries and return relevant results.
2. Accept a document as a query and return the most relevant information for each section of the document (basically chunk by chunk matching ?)
3. Display search results as a list.

Additionally, I'm curious about the feasibility of uploading a document and matching it with existing documents to receive the most relevant chunks to optimize a document. Is this something that Ragflow supports?

Bg
jahn

**Comment by JinHai-CN** [comment]
Fixed in 0.11.0
