### ISSUE TITLE
[Question]: Why do I have to download pytorch_model.bin twice every time I start。

### ISSUE THREAD

**Issue by Grey-JFB** [infiniflow/ragflow#485]
### Describe your problem

pytorch_model.bin:  60%|█████▉    | 776M/1.30G [13:54<10:11, 860kB/s]
pytorch_model.bin:  61%|██████    | 797M/1.30G [14:18<09:38, 873kB/s]

Is there any way I can optimize it? Downloading is too slow.

**Comment by KevinHuSh** [comment]
Pull the lalest images. I put it in image.

**Comment by mieco** [comment]
what's the latest base image, it still download the pytorch_model.bin twice for me.
