### ISSUE TITLE
[Question]: Document Chunking

### ISSUE THREAD

**Issue by ThanhNguye-n** [infiniflow/ragflow#492]
Hi, how to run chunking pdf code, I don't see any documents included in ReadMe from deepdoc folder. Thanks in advance

**Comment by KevinHuSh** [comment]
You can take these as examples.
https://github.com/infiniflow/ragflow/blob/main/docs/faq.md#411-do-you-offer-examples-of-using-deepdoc-to-parse-pdf-or-other-files

**Comment by ThanhNguye-n** [comment]
> You can take these as examples. https://github.com/infiniflow/ragflow/blob/main/docs/faq.md#411-do-you-offer-examples-of-using-deepdoc-to-parse-pdf-or-other-files

Hi, thanks your reply. But any description of the differences between these approach chunking, i see a lot file py to chunk, which is the best for pdf ?
