### ISSUE TITLE
请问可以不使用api的模式吗，就是加载本地模型可以吗

### ISSUE THREAD

**Issue by Franklinlifangcheng** [infiniflow/ragflow#493]
### Describe your problem

我想在本地部署模型加上RAG优化而不是使用api该如何修改或者部署呀

**Comment by KevinHuSh** [comment]
Sorry, I don't get it, could you be more specific?

**Comment by tianlinzx** [comment]
He wants to call local LLM rather than OPEN AI API ect..

**Comment by KevinHuSh** [comment]
You could use ollama or xinference to call local llm.
