### ISSUE TITLE
[Question]:  Starting a file alone shows that the connection is successful, but when starting it in a project, the following error appears?

### ISSUE THREAD

**Issue by HuaC-Z** [infiniflow/ragflow#494]
### Describe your problem

elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))

**Comment by KevinHuSh** [comment]
Check the configuration of ES port in docker/.env and service_conf.yml

**Comment by HuaC-Z** [comment]
why closed？docker/.env file and service_conf.yml file settings is right.I printed the relevant settings before creating the connection and they were correct.

**Comment by HuaC-Z** [comment]
> Check the configuration of ES port in docker/.env and service_conf.yml

docker/.env file and service_conf.yml file settings is right.I printed the relevant settings before creating the connection and they were correct.
