### ISSUE TITLE
[Bug]: Field "llm_id" of table "dialog" is to short for practical purposes

### ISSUE THREAD

**Issue by 7frank** [infiniflow/ragflow#495]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ecb7d40dcc1e54af70791f45ca85f90a79a9ad12

### Other environment information

```Markdown
I ran the "docker compose up -d" setup on Linux Mint.
```

### Actual behavior

I got an error using a chat configuration "ollama" with model "mixtral:8x7b-instruct-v0.1-q4_K_S" the model name was truncated to length 32 whereas it is 33 characters long. I increased the field size like
> ALTER TABLE dialog MODIFY llm_id VARCHAR(64);
which allowed me to chat with my local llm.

### Expected behavior

For practical purposes please consider increasing the size of "llm_id".

### Steps to reproduce

```Markdown
configure a chat in the UI with ollama and a model with a name longer than 32 characters e.g. 'mixtral:8x7b-instruct-v0.1-q4_K_S'
```

### Additional information

https://github.com/KevinHuSh/ragflow/blob/ecb7d40dcc1e54af70791f45ca85f90a79a9ad12/web_server/db/db_models.py#L508

**Comment by KevinHuSh** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> [ecb7d40](https://github.com/infiniflow/ragflow/commit/ecb7d40dcc1e54af70791f45ca85f90a79a9ad12)
> 
> ### Other environment information
> ```
> I ran the "docker compose up -d" setup on Linux Mint.
> ```
> 
> ### Actual behavior
> I got an error using a chat configuration "ollama" with model "mixtral:8x7b-instruct-v0.1-q4_K_S" the model name was truncated to length 32 whereas it is 33 characters long. I increased the field size like
> 
> > ALTER TABLE dialog MODIFY llm_id VARCHAR(64);
> > which allowed me to chat with my local llm.
> 
> ### Expected behavior
> For practical purposes please consider increasing the size of "llm_id".
> 
> ### Steps to reproduce
> ```
> configure a chat in the UI with ollama and a model with a name longer than 32 characters e.g. 'mixtral:8x7b-instruct-v0.1-q4_K_S'
> ```
> 
> ### Additional information
> https://github.com/KevinHuSh/ragflow/blob/ecb7d40dcc1e54af70791f45ca85f90a79a9ad12/web_server/db/db_models.py#L508

Nice work!
Why don't you submit a pull request to be a contributor? -_^
