### ISSUE TITLE
[Bug]: index out of range when import pdf by paper 

### ISSUE THREAD

**Issue by ben-qiao** [infiniflow/ragflow#502]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

fjejfpweofp2io32r2rk2kelwfk

### Other environment information

```Markdown
ragflow 0.3.0
```

### Actual behavior

1. create a kb with parse method "paper"
2. upload a pdf file and start to parse
3. parse failed and report index out of list error

![89242638ebb898f6c669d783277f9ab](https://github.com/infiniflow/ragflow/assets/42063239/9911f09b-f9b1-4b6e-a007-0542f4709fd6)

### Steps to reproduce

```Markdown
as actual behavior.
ps: not all pdf is failed. i upload two pdf,one is failed
```

**Comment by KevinHuSh** [comment]
fixed.

**Comment by melmathari** [comment]
> fixed.

Mind sharing how, i think it will benefit the communtiy.
