### ISSUE TITLE
[Question]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5/revision/main (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))

### ISSUE THREAD

**Issue by zmm1996** [infiniflow/ragflow#506]
### Describe your problem

Always connecting to huggingface.co？

![image](https://github.com/infiniflow/ragflow/assets/40532959/f4237c51-9724-4618-9014-50adb1b38213)

**Comment by KevinHuSh** [comment]
What about pulling the latest image?

**Comment by zmm1996** [comment]
![image](https://github.com/infiniflow/ragflow/assets/40532959/97e84376-8859-4d64-9644-6a3fabd2aa73)

**Comment by KevinHuSh** [comment]
> > What about pulling the latest image?
> 
> **docker-compose-CN.yml** ![image](https://private-user-images.githubusercontent.com/40532959/325050244-a4ab6860-29ce-4f33-baad-a288476ad812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTEyMzMsIm5iZiI6MTcxMzk1MDkzMywicGF0aCI6Ii80MDUzMjk1OS8zMjUwNTAyNDQtYTRhYjY4NjAtMjljZS00ZjMzLWJhYWQtYTI4ODQ3NmFkODEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA5Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMDAxMTY4ZTliMDA1YzE0ZjI5YmYyNGQxOTlkYzRmYzY3ZDgyZThmMjg5ZWVmZGZmYjVkNmY4Y2U2OWM5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A7H8YfyjC5QQxtXMy3jmy-R4r33-fu_2PggmfhjkEsw)
> 
> **Execute commands** ` docker-compose -f docker-compose-CN.yml up -d`
> 
> **控制台如下信息：**
> 
> [WARNING] [2024-04-24 10:06:54,006] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection. [WARNING] [2024-04-24 10:06:57,271] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection. ^[a[WARNING] Load term.freq FAIL! Traceback (most recent call last): File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql cursor.execute(sql, params or ()) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute result = self._query(query) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result result.read() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read first_packet = self.connection._read_packet() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet packet.raise_for_error() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) pymysql.err.ProgrammingError: (1146, "Table 'rag_flow.document' doesn't exist")
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/ragflow/rag/svr/task_broker.py", line 186, in dispatch() File "/ragflow/rag/svr/task_broker.py", line 65, in dispatch rows = collect(tm) ^^^^^^^^^^^ File "/ragflow/rag/svr/task_broker.py", line 39, in collect docs = DocumentService.get_newly_uploaded(tm) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3128, in inner return fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "/ragflow/api/db/services/document_service.py", line 101, in get_newly_uploaded return list(docs.dicts()) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 7243, in **iter** self.execute() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2011, in inner return method(self, database, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2082, in execute return self._execute(database) ^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2255, in _execute cursor = database.execute(self) ^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3299, in execute return self.execute_sql(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3289, in execute_sql with **exception_wrapper**: File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3059, in **exit** reraise(new_type, new_type(exc_value, *exc_args), traceback) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 192, in reraise raise value.with_traceback(tb) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql cursor.execute(sql, params or ()) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute result = self._query(query) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result result.read() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read first_packet = self.connection._read_packet() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet packet.raise_for_error() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) peewee.ProgrammingError: (1146, "Table 'rag_flow.document' doesn't exist") /root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( /root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( /root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( [WARNING] [2024-04-24 10:07:02,276] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection. [WARNING] Load term.freq FAIL! Traceback (most recent call last): File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql cursor.execute(sql, params or ()) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute result = self._query(query) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result result.read() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read first_packet = self.connection._read_packet() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet packet.raise_for_error() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) pymysql.err.ProgrammingError: (1146, "Table 'rag_flow.task' doesn't exist")
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/ragflow/rag/svr/task_executor.py", line 316, in main(int(sys.argv[2]), int(sys.argv[1])) File "/ragflow/rag/svr/task_executor.py", line 246, in main rows = collect(comm, mod, tm) ^^^^^^^^^^^^^^^^^^^^^^ File "/ragflow/rag/svr/task_executor.py", line 95, in collect tasks = TaskService.get_tasks(tm, mod, comm) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3128, in inner return fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "/ragflow/api/db/services/task_service.py", line 65, in get_tasks docs = list(docs.dicts()) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 7243, in **iter** self.execute() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2011, in inner return method(self, database, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2082, in execute return self._execute(database) ^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2255, in _execute cursor = database.execute(self) ^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3299, in execute return self.execute_sql(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3289, in execute_sql with **exception_wrapper**: File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3059, in **exit** reraise(new_type, new_type(exc_value, *exc_args), traceback) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 192, in reraise raise value.with_traceback(tb) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql cursor.execute(sql, params or ()) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute result = self._query(query) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result result.read() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read first_packet = self.connection._read_packet() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet packet.raise_for_error() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) peewee.ProgrammingError: (1146, "Table 'rag_flow.task' doesn't exist") [WARNING] Load term.freq FAIL! Traceback (most recent call last): File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql cursor.execute(sql, params or ()) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute result = self._query(query) ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query conn.query(q) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result result.read() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read first_packet = self.connection._read_packet() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet packet.raise_for_error() File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) pymysql.err.ProgrammingError: (1146, "Table 'rag_flow.document' doesn't exist")
> 
> During handling of the above exception, another exception occurred:
> 
> ![image](https://private-user-images.githubusercontent.com/40532959/325049871-8a9e1bd1-59ed-4659-88ed-cf9ef1459bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTEyMzMsIm5iZiI6MTcxMzk1MDkzMywicGF0aCI6Ii80MDUzMjk1OS8zMjUwNDk4NzEtOGE5ZTFiZDEtNTllZC00NjU5LTg4ZWQtY2Y5ZWYxNDU5YmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA5Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MWM5ZGEyOTI2MjAzMDk0Y2FmM2UyNWQzZmE3NDJmZWJiZmZiZjRmOTJlMTE2OWQxNTMyNDc0NzU3YmY5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jc60yvMg5T9QiyssSMDNK6_t7ll-0P5Dsz3aioT2YZk)

docker pull infiniflow/ragflow:v0.3.0
docker compose down -v (all data removed)
docker compose up -d
