### ISSUE TITLE
[Bug]: 404 index_not_found_exception

### ISSUE THREAD

**Issue by chengxs1994** [infiniflow/ragflow#507]
### Describe your problem

ES updateByQuery deleteByQuery: NotFoundError(404, 'index_not_found_exception', 'no such index [ragflow_18cb3dde011811efa5100242ac120006]', ragflow_18cb3dde011811efa5100242ac120006, index_or_alias)【Q】：{'match': {'doc_id': '8a79d1ce014b11ef808b0242ac120005'}}

1. docker logs -f ragflow-server (is work)
2. Check if the tast_executor.py process exist. (is work)
3. Check if your RAGFlow server can access hf-mirror.com or huggingface.com. (can access)

but ES index not create and 404

**Comment by KevinHuSh** [comment]
It seems ES not working well.
