### ISSUE TITLE
[Bug]: Failed to parse document,[ERROR]Internal server error: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by zhentouzhanshi** [infiniflow/ragflow#509]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0

### Actual behavior

Embedding model:text-embedding-v2
Chunk method:Book
When I created the knowledge base and configured it as follows, after the configuration was completed, I uploaded a docx file to the knowledge base and encountered the following error message: [ERROR] Internal server error: not enough values to unpack (expected 2, got 1).
<img width="1062" alt="1" src="https://github.com/infiniflow/ragflow/assets/69191054/cccfa4ae-318e-435f-b941-3630b957eeda">
<img width="1255" alt="2" src="https://github.com/infiniflow/ragflow/assets/69191054/82deceee-cf6c-4685-8f39-c6e7eb5d272a">

log info :
Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
File "/ragflow/rag/svr/task_executor.py", line 137, in build
cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/app/book.py", line 139, in chunk
res = tokenize_table(tbls, doc, eng)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/nlp/init.py", line 138, in tokenize_table
for (img, rows), poss in tbls:
^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

### Steps to reproduce

```Markdown
Embedding model:text-embedding-v2
Chunk method:Book

When I created the knowledge base and configured it as follows, after the configuration was completed, I uploaded a docx file to the knowledge base and encountered the following error message: [ERROR] Internal server error: not enough values to unpack (expected 2, got 1).
```

**Comment by zhentouzhanshi** [comment]
log info :
Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 137, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/book.py", line 139, in chunk
    res = tokenize_table(tbls, doc, eng)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/__init__.py", line 138, in tokenize_table
    for (img, rows), poss in tbls:
        ^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by KevinHuSh** [comment]
fixed
