### ISSUE TITLE
[Feature Request]: Could please add Llama 3 model in?

### ISSUE THREAD

**Issue by xiasw81** [infiniflow/ragflow#511]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Few days ago, Meta Llama 3 model was published. It will be more powerful. Hope ragflow team can add this most advanced model in.

**Comment by KevinHuSh** [comment]
You can use Ollama which support Lama3. RAGFlow can use Ollama deploying models.
