### ISSUE TITLE
[Bug]: ERROR: Invalid API-key provided.  Please set LLM API-Key in 'User Setting -> Model Providers -> API-Key'

### ISSUE THREAD

**Issue by juansebashr** [infiniflow/ragflow#513]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

369400c483ee74addb3ef45a5cd539f2c3e69e5d

### Other environment information

```Markdown
Demo Web Page
```

### Actual behavior

When I try to make any request to chat in the web demo appear that error
ERROR: Invalid API-key provided.  Please set LLM API-Key in 'User Setting -> Model Providers -> API-Key'

Im using qwen chat models

### Steps to reproduce

```Markdown
Setup a chat in the web demo with any qwen model selected
```

**Comment by KevinHuSh** [comment]
Please add your own api key that LLM factory provides in setting at the right top corner of the web page.
