### ISSUE TITLE
[Bug]: ERROR: Error code: 400 - {'detail': '[address=0.0.0.0:51672, pid=57224] Model not found, uid: qwen1.5-chat-ieJFufN9-1-0'}

### ISSUE THREAD

**Issue by ipv6next** [infiniflow/ragflow#514]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1234

### Other environment information

```Markdown
LLM : qwen-1.5 本地部署
embe: large-zh 本地

通过 xinference 加载
```

### Actual behavior

正常用LLM，可以聊天。
但是调用知识库时候，报错
ERROR: Error code: 400 - {'detail': '[address=0.0.0.0:51672, pid=57224] Model not found, uid: qwen1.5-chat-ieJFufN9-1-0'}

### Steps to reproduce

```Markdown
正常用LLM，可以聊天。
但是调用知识库时候，报错
ERROR: Error code: 400 - {'detail': '[address=0.0.0.0:51672, pid=57224] Model not found, uid: qwen1.5-chat-ieJFufN9-1-0'}
```

**Comment by KevinHuSh** [comment]
Is this helpful?
https://github.com/infiniflow/ragflow/blob/main/docs/faq.md#414-hint--102--fail-to-access-model--connection-error

**Comment by lawsonX** [comment]
@KevinHuSh I have encountered similar problem in v0.8 ，with xinferece local model.  Model not found, uid: qwen1.5-chat-1-0'

**Comment by lawsonX** [comment]
@KevinHuSh Do we have any conclusions about the issue?
I have encountered similar problem in ragflow v0.8 ，with xinferece local qwen model. 

Error code: 400 - {'detail': '[address=[0.0.0.0:34838](http://0.0.0.0:34838/), pid=2945997] Model not found, uid: qwen1.5-chat-1-0'}

based on the error, the model UID is wrong with the suffix "-1-0", which is not from my configuration,  it should not exists.

This BUG happens occasionally only with API usage, and will return to normal by itself.  So weird

**Comment by SenriAkane1** [comment]
Check the output of xinference; usually, this issue occurs when xinference reports an error (such as out of memory).
