### ISSUE TITLE
[Question]: 有没有不用docker启动的教程？

### ISSUE THREAD

**Issue by cklogic** [infiniflow/ragflow#516]
### Describe your problem

我们环境比较复杂，不想通过docker启动，比如模型目录需要指定，而不是随便下载，minio、es等我们有现成高可用的，不需要再装一遍。有没有不用docker启动的教程，谢谢~

**Comment by KevinHuSh** [comment]
Please refer to Dockfile.scratch which specify the evirement RAGFlow needs.
Then, refer to docker/entrypoint.sh which specify the commands that need to run.

**Comment by Nuclear6** [comment]
嗨 不用docker启动成功了吗？

**Comment by papandadj** [comment]
> 嗨 不用docker启动成功了吗？

我这边是启动成功了，用CPU或者GPU都可以。你用conda虚拟出来环境，然后照着sratch安装环境就可以了。之后启动的时候总共启动四个程序，分别是web前端、api服务、svr/task_broker.py 和 svr/task_excutor.py。但是在启动的时候要修改 conf/service_conf.yaml 文件，改成你的配置。

启动的时候可以通过 export CUDA_VISIBLE_DEVICES=2 来控制使用哪个GPU

executor可以这样启动。 ```python rag/svr/task_executor.py 0 1```  0 1的具体意义你可以看源码

**Comment by Nuclear6** [comment]
我还想请教个问题，如果用cpu启动的话，嵌入模型是怎么在cpu上运行的？我目前按照你这个方法在cpu启动之后，嵌入模型选择是默认的通义千问嵌入模型，我不知道这个嵌入模型在解析文档是怎么生效的？

**Comment by pearlmaop** [comment]
建议给一个详细的教程，谢谢

**Comment by 1907010218** [comment]
> > 嗨 不用docker启动成功了吗？
> 
> 我这边是启动成功了，用CPU或者GPU都可以。你用conda虚拟出来环境，然后照着sratch安装环境就可以了。之后启动的时候总共启动四个程序，分别是web前端、api服务、svr/task_broker.py 和 svr/task_excutor.py。但是在启动的时候要修改 conf/service_conf.yaml 文件，改成你的配置。
> 
> 启动的时候可以通过 export CUDA_VISIBLE_DEVICES=2 来控制使用哪个GPU
> 
> executor可以这样启动。 `python rag/svr/task_executor.py 0 1` 0 1的具体意义你可以看源码

hello，考虑出一个教程吗？我也需要不使用docker在本地部署一下，但是我是第一次接触这方面的东西，你说的步骤我不是太清楚。谢谢

**Comment by 1907010218** [comment]
> 建议给一个详细的教程，谢谢

hello，请问您找到教程了吗？

**Comment by 1907010218** [comment]
hello，你好，请问你成功了吗？

**Comment by KevinHuSh** [comment]
Please refer to [this](https://github.com/infiniflow/ragflow/blob/main/README.md#-launch-service-from-source-for-development).
