### ISSUE TITLE
[Bug]: Failed to parse document,[ERROR]Internal server error: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by zhentouzhanshi** [infiniflow/ragflow#517]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2c57a93a5ffa192eec0e9df2a0aff57c64a4676c

### Actual behavior

#509 
The problem still exists，I have already used the code submitted in #510, but the problem still persists.

log info:
[WARNING] [2024-04-24 10:21:00,330] [redis_conn.set] [line:50]: [EXCEPTION]setf6032c7c01de11ef91a20242ac120005/test.docx||Error -2 connecting to redis:6379. Name or service not known.
[WARNING] [2024-04-24 10:21:00,566] [redis_conn.get] [line:33]: [EXCEPTION]getf6032c7c01de11ef91a20242ac120005/test.docx||Error -2 connecting to redis:6379. Name or service not known.
[INFO] [2024-04-24 10:21:03,226] [_internal._log] [line:96]: 172.18.0.5 - - [24/Apr/2024 10:21:03] "GET /v1/document/list?kb_id=f6032c7c01de11ef91a20242ac120005&page=1&page_size=10 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 137, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/book.py", line 139, in chunk
    res = tokenize_table(tbls, doc, eng)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/nlp/__init__.py", line 138, in tokenize_table
    for (img, rows), poss in tbls:
        ^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

### Steps to reproduce

```Markdown
Embedding model:text-embedding-v2
Chunk method:Book
```

**Comment by KevinHuSh** [comment]
Pull the latest image or latest source code with docker builting.
Obviously, this stack is not from latest code.
https://github.com/infiniflow/ragflow/blob/main/rag/app/book.py#L139
