### ISSUE TITLE
[Question]: Why no date shown in MinIO database?

### ISSUE THREAD

**Issue by yiouyou** [infiniflow/ragflow#521]
### Describe your problem

It's has been successfully running and setting for all dockers, llm, embed, test knowledge pdfs. It's very strang that I can't find any data in MinIO database, even I can chat with the uploaded and processed pdfs.

When studing the code, I assume that the MinIO database should be used for vectoer storage, but it seems that the outcome so far is that everything is storaged in elastic database, since it support both semantic and regular search.

So, my question is:
1) What does MinIO database do?
2) What are the functions of MinIO/Elastic/MySQL three databases in the project?

Thanks a lot,

**Comment by KevinHuSh** [comment]
1. Storing file and chunk image.
2. ES is used for search. Mysql matain the relation of all data.

**Comment by yiouyou** [comment]
@KevinHuSh Thanks for your information. But why there is no any bucket or data in MinIO database with default user/pwd setting? Like mentioned before, the sys has generated chunk image for uploaded file.
