### ISSUE TITLE
How to bypass the login screen?

### ISSUE THREAD

**Issue by ciaoyizhen** [infiniflow/ragflow#522]
### Describe your problem

After a week of hard work, I finally managed to launch the project. The interface after launching is a login screen.
I tried login and Sign up. it says Network anomaly There is an abnormality in your network and you cannot connect to the server.

I don't know if it's because the server can't connect to the network or something else? I tried modifying the login function in `user_app.py` to force a call to `login_user` as well as `cors_response` but it still doesn't work, can you tell me how to fix this?

**Comment by KevinHuSh** [comment]
It says Network anomaly, doesn't it?
OMG, I'm orry, your weekly hard work is probably in vain.
The RAGFLOW displayed at your backend server is a sign of successfully lauching.

**Comment by GaoR311** [comment]
I have the same problem
