### ISSUE TITLE
[Question]: Why is the resolution always 0.00%?

### ISSUE THREAD

**Issue by yuanpneg** [infiniflow/ragflow#527]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/52906027/9dc61a7e-6d29-418f-9d9b-b9660da8aac9)
![image](https://github.com/infiniflow/ragflow/assets/52906027/c17542ef-98b1-4f5a-a5f0-84d46eb75cee)
The issues shown in the picture have also been verified.

**Comment by KevinHuSh** [comment]
As we know, this is usually caused by lack of memory that the processes have been killed if you're using the latest images.
