### ISSUE TITLE
[Bug]: Knowledge Bases

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#530]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

b06d639

### Other environment information

```Markdown
Standard Build using Docker Compose
```

### Actual behavior

When I get over 15 knowledge bases, an old one will disappear.  It would still be available for the chat bot but the name of the base has changed. 

<img width="632" alt="image" src="https://github.com/infiniflow/ragflow/assets/31369642/38482f69-9c38-49b3-bec1-2dd964a0ee69">

### Steps to reproduce

```Markdown
Create 15 knowledge bases
```

**Comment by KevinHuSh** [comment]
fixed.
