### ISSUE TITLE
[Question]: Why does pdf file parsing stay in the near completion stage, lasting for a long time without any reaction? and the log does not report errors

### ISSUE THREAD

**Issue by cxlight** [infiniflow/ragflow#532]
### Describe your problem

As shown in the picture:
<img width="1142" alt="image" src="https://github.com/infiniflow/ragflow/assets/3929361/68b611e5-d8e7-45d2-b1b2-2df608244b23">

And log with no error：
<img width="681" alt="image" src="https://github.com/infiniflow/ragflow/assets/3929361/dd54881d-4454-4128-88ce-30ae7e87241e">

**Comment by KevinHuSh** [comment]
Is it locally deployed?
If it is, the process might be killed since the limitation of RAM.

**Comment by cxlight** [comment]
You're right, I allocated 12G of memory from the adjustment to 20G and the parsing was successful. 
Thank you very much.
