### ISSUE TITLE
[Bug]: Cancel document parsing doesn't stop the task immediately

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

800b5c7aaa6e6cfe8fa889bfc6bb01f6c8267c6a

### Actual behavior

After cancel parsing document, the parsing task seems still run in the backend, not stopped immediately.

### Expected behavior

The parsing document task stopped right after cancel.

### Steps to reproduce

```Markdown
Upload a PDF document, select the general parsing method, after the parsing started, click cancel. Noticed the CPU is still high for quite long, seems the task is still running in the backend
```

**Comment by KevinHuSh** [comment]
Yes, it's a trade-off between task running efficiency and task status transparency.
If the task is going to check being canceled or not every step, it will tear down the speed of task execution.
