### ISSUE TITLE
Post Request Returns 'Conversation not found!' Error[Question]: 

### ISSUE THREAD

**Issue by leoschopen** [infiniflow/ragflow#541]
Hello,

I am encountering an issue when attempting to send a POST request using Python. Every time I send the request, I receive an error message containing `'retmsg': 'Conversation not found!'`. I am unsure if this indicates that the API I am using only supports web-based access or if there is an issue with the `conversationid` I am providing.

Here is a brief outline of what I am trying to accomplish, along with the relevant details:

- **Objective**: I am trying to send a POST request to [API Name] to [describe the action or the expected result].
- **Code Sample**:
  ```python
  # Please include a minimal, reproducible code sample here.
  # For example:
  import requests

  url = 'https://api.example.com/conversations'
  headers = {'Authorization': 'Bearer YOUR_ACCESS_TOKEN'}
  data = {
    "conversation_id": "COPY FROM ONE OLD CONVERSATION'S URL",
    "messages": [
        {
            "role": "user",
            "content": "XXX"
        }
    ]
}

  response = requests.post(url, headers=headers, json=data)
  print(response.json())
  ```
- **Error Message**:
  ```
  {'retmsg': 'Conversation not found!'}
  ```

- **Troubleshooting Steps Taken**:
  - I have verified that my `conversation_id` is correct(old conversation).

Could you please provide some guidance on what might be causing this issue? Is there a limitation that restricts access to web clients only, or could there be a problem with the way I am sending the `conversation_id`?

Thank you for your assistance.

**Comment by KevinHuSh** [comment]
The conversation_id is from calling /api/new_conversation. ^^

**Comment by kaka36** [comment]
请问解决了么 ，怎么解决的？我也遇到这个问题
