### ISSUE TITLE
[Bug]: 无法创建数据集

### ISSUE THREAD

**Issue by lkocok** [infiniflow/ragflow#546]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b201

### Other environment information

```Markdown
i9-9900K
Ununtu18.04
```

### Actual behavior

![无标题](https://github.com/infiniflow/ragflow/assets/6744790/7e582815-4a77-4cf6-b8a0-a8c3eb0b6d3a)
![无标题2](https://github.com/infiniflow/ragflow/assets/6744790/d22dcf63-ba1a-4a91-b318-79793e17369e)

### Steps to reproduce

```Markdown
上传QA知识库，可以分片和embedding，但是无法创建索引。
```

**Comment by KevinHuSh** [comment]
ES connection fail.
By default, the port of ES is 1200.
