### ISSUE TITLE
[Question]: How I can request the flask api?

### ISSUE THREAD

**Issue by jg0014** [infiniflow/ragflow#552]
### Describe your problem

I started the api server, but when I request the api to startting a new conversation, I got an unexpected response.
Could you please to help me to locate the problem?
![image](https://github.com/infiniflow/ragflow/assets/63099132/1597e72d-1f8b-4950-8072-fa542e804de2)

**Comment by KevinHuSh** [comment]
Don't forget 'v1' in the url address.
