### ISSUE TITLE
不会开源就别开源

### ISSUE THREAD

**Issue by LaniakeaS** [infiniflow/ragflow#556]
代码写的这么烂，以至于我怀疑你们是故意拿开源社区打广告还不想让开发人看明白你们代码是吧。
或者是吸开源社区的血，专门把烂成一坨屎的代码让别人帮你们改了？？？
还有一堆压根儿不知道引用在哪里的无用代码
真的牛
就这还部分开源？
这种开源项目烂死算了

**Comment by yuiant** [comment]
我是受过专业训练的，一般看到issue不会笑，除非忍不住。
我对deepdoc的效果比较感兴趣，尝试运行deepdoc下的Readme上t_ocr脚本，指定好输入文件和输出路径。运行后效果我震惊了：竟然给我报es连接错误。
随手翻了下源码，发现各种新奇的命名和模块引用方式，甚至我在一度怀疑作者在创造一门新的语言范式，吾辈愿称之为HuPython。作者打广告的才华，不仅融合到代码的字里行间，甚至从我16寸的Retina屏溢出来了，霎时极具缅甸的异国风情。

希望项目作者能好好整改下项目。

**Comment by LaniakeaS** [comment]
好骂，HuPython属实蚌埠住了

**Comment by papandadj** [comment]
哈哈，项目代码确实写的不咋的，从头到尾没一个注释。我debug都猜不到在干啥

**Comment by HuaC-Z** [comment]
牛皮，现在还没有跑起来的飘过。。。。

**Comment by KevinHuSh** [comment]
> 我是受过专业训练的，一般看到issue不会笑，除非忍不住。 我对deepdoc的效果比较感兴趣，尝试运行deepdoc下的Readme上t_ocr脚本，指定好输入文件和输出路径。运行后效果我震惊了：竟然给我报es连接错误。 随手翻了下源码，发现各种新奇的命名和模块引用方式，甚至我在一度怀疑作者在创造一门新的语言范式，吾辈愿称之为HuPython。作者打广告的才华，不仅融合到代码的字里行间，甚至从我16寸的Retina屏溢出来了，霎时极具缅甸的异国风情。
> 
> 希望项目作者能好好整改下项目。

I tried deepdoc/vision/t_ocr.py and deepdoc/vision/t_recognizer.py and have not discover that ES issue.

**Comment by Yuxiang1995** [comment]
首先肯定你们的贡献，但这个代码风格确实可以再优化一下，模块之间耦合度过高了

**Comment by LaniakeaS** [comment]
这如果是个个人项目也就算了。
你还带者infiniflow的名字呢，招牌不要了？
希望贵公司如果要开源就拿出诚意来，别让开源社区给你擦屁股。
好好把代码整理一下吧！

**Comment by papandadj** [comment]
你们不行把项目关了吧，这样我们公司也不让我看了，我快吐了

**Comment by yuiant** [comment]
> > 我是受过专业训练的，一般看到issue不会笑，除非忍不住。 我对deepdoc的效果比较感兴趣，尝试运行deepdoc下的Readme上t_ocr脚本，指定好输入文件和输出路径。运行后效果我震惊了：竟然给我报es连接错误。 随手翻了下源码，发现各种新奇的命名和模块引用方式，甚至我在一度怀疑作者在创造一门新的语言范式，吾辈愿称之为HuPython。作者打广告的才华，不仅融合到代码的字里行间，甚至从我16寸的Retina屏溢出来了，霎时极具缅甸的异国风情。
> > 希望项目作者能好好整改下项目。
> 
> I tried deepdoc/vision/t_ocr.py and deepdoc/vision/t_recognizer.py and have not discover that ES issue.

I have to comment out the es reference in your rag/utils/__init__.py 19 line to get rid of the ES connection error. Maybe your OS is HuSystem which had an ES already.

**Comment by yuiant** [comment]
by the way, to import deepdoc above the sys.path operation in t_ocr.py will raise error of deepdoc Module cannot be found.

**Comment by yuiant** [comment]
I strongly suggest the repo owner to reopen this issue to listen other advices.还有，能起得Huqie这种命名的就不要在这里用英文回复同胞了，用拼音可能更好。

**Comment by KevinHuSh** [comment]
Since lack of time and man power, the quality of code need to be upgraded.  And we will continually refine it and add new features.
And we also welcome contributors to make this project better.

**Comment by LaniakeaS** [comment]
what the fk is "man power"?
（乐

**Comment by papandadj** [comment]
> what the fk is "man power"? Is there woman power? （乐

non-binary power

**Comment by yuiant** [comment]
> > I strongly suggest the repo owner to reopen this issue to listen other advices.还有，能起得Huqie这种命名的就不要在这里用英文回复同胞了，用拼音可能更好。
> 
> Huqie is especially used for Chinese tokenizing, so it use pinyin like jieba.

same like 「man power」hahahahahah. 心疼jieba 1秒无辜躺枪。

**Comment by LaniakeaS** [comment]
> > I strongly suggest the repo owner to reopen this issue to listen other advices.还有，能起得Huqie这种命名的就不要在这里用英文回复同胞了，用拼音可能更好。
> 
> Huqie is especially used for Chinese tokenizing, so it use pinyin like jieba.

is there "qie" in jieba? jieba is a fking package name.
if you call your project by "ragliu", I wouldn't say anything.

**Comment by LaniakeaS** [comment]
> There is room for improvement in code quality, and the system architecture can also be enhanced. However, due to the small development team, I hope all developers can give more time.

don't make excuses. don't waste developers' time of community. we don't own you anything.
cleanup your code, write your documentation, and then you make it public.
it has nothing to do with whether your team is small or big, even one fking person can make it! (think about linus)
here's some tips with respects.

open-sourced project needs:
- a clear documentation of your package using
- a fine coding style (your code doesn't even to be pythonic, but please don't use strange abbreviation or pinyin)
- write comments in your code!
- take your time

**Comment by papandadj** [comment]
> > There is room for improvement in code quality, and the system architecture can also be enhanced. However, due to the small development team, I hope all developers can give more time.
> 
> don't make excuses. don't waste developers' time of community. we don't own you anything. cleanup your code, write your documentation, and then you make it public. it has nothing to do with whether your team is small or big, even one fking person can make it! (think about linus) here's some tips with respects.
> 
> open-sourced project needs:
> 
> * a clear documentation of your package using
> * a fine coding style (your code doesn't even to be pythonic, but please don't use strange abbreviation or pinyin)
> * write comments in your code!
> * take your time
> 
> if you just want to show off about your code. make it read-only.

haha. bro piqi real boom.

**Comment by DAAworld** [comment]
> 你们不行把项目关了吧，这样我们公司也不让我看了，我快吐了

哈哈，吐血，es耦合太深了，改都改不动

**Comment by KyleWang-Hunter** [comment]
到现在为止，代码质量还是没有改善，而且越来越加一些看不懂的代码O(∩_∩)O
