### ISSUE TITLE
[Question]: SQL Query Conversion Leading to Verbose Error Messages

### ISSUE THREAD

**Issue by leoschopen** [infiniflow/ragflow#559]
### Describe your problem

Hello,

I am encountering a problem where the conversion of specific SQL queries using the language model results in verbose and unhelpful error messages. The issue appears to be related to the way the model handles fields of data type [text] when using the LIKE operator in SQL.

<img width="1055" alt="image" src="https://github.com/infiniflow/ragflow/assets/43008356/32429961-7d69-4139-93ab-80c0693e32e5">

Here is the SQL query that is causing the issue:

```sql
select doc_id, docnm_kwd, "wen_ti_tks" from "xxx" where "hui_da_tks" like '%雪%' and "da_an_tks" like '%门%'
```

The error message returned from the backend is as follows:

```
BadRequestError(400, 'verification_exception', 'Found 2 problems
line 1:93: ["hui_da_tks" like \'雪\'] cannot operate on field of data type [text]: No keyword/multi-field defined exact matches for [hui_da_tks]; define one or use MATCH/QUERY instead
line 1:119: ["da_an_tks" like \'门\'] cannot operate on field of data type [text]: No keyword/multi-field defined exact matches for [da_an_tks]; define one or use MATCH/QUERY instead')
```

From the error message, it seems that the fields "hui_da_tks" and "da_an_tks" are of type [text] and do not have a keyword or multi-field defined that allows for exact matches, which is required for the LIKE operator to function correctly.

Could you please provide guidance on how to avoid this error? Is there a reliable way to use the language model for converting queries that will not result in such verbose error messages?

Thank you for your assistance.

**Comment by KevinHuSh** [comment]
I recommend not to mix 'table' chunking method with other chunking methods since it will use sql to retrieval once one table method is used in the knowledgebase.
