### ISSUE TITLE
[Bug]: Cites Not Rendered Properly

### ISSUE THREAD

**Issue by rhudock** [infiniflow/ragflow#566]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f1c98aad

### Other environment information

```Markdown
Standard Build Using Docker
```

### Actual behavior

When using the API chat feature the cites are not rendered properly.

<img width="838" alt="image" src="https://github.com/infiniflow/ragflow/assets/31369642/d4c2f00e-0dad-4fbf-9248-84ec71fd2c44">

### Expected behavior

Render cite for relied upon document.

### Steps to reproduce

```Markdown
Create a chat bot, create an API key, and then select Preview
```

**Comment by KevinHuSh** [comment]
fixed.

**Comment by KevinHuSh** [comment]
Fixed.

**Comment by HaoGuo98** [comment]
besides，when i upload excel and choose Q&A ，the reference also can not render properly， even in the chat interface。

**Comment by KevinHuSh** [comment]
In the API request, set "quote":false will remove these ##$$.
