### ISSUE TITLE
[Question]: How to update the ragflow to the latest version?

### ISSUE THREAD

**Issue by WilliamCloudQi** [infiniflow/ragflow#571]
### Describe your problem

How to update the ragflow to the latest version?

**Comment by KevinHuSh** [comment]
If you are using `docker compose up -d` to start, use following command.
- `docker pull infiniflow/ragflow:latest`
- `docker compose up ragflow -d`

If you are using `docker compose up -f docker-compose-CN.yml -d` to start, use following command.
- `docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:latest`
- `docker compose up ragflow -d`

**Comment by Alphayellowcat** [comment]
> 为什么我运行这些代码后我的C盘就满了？
Have you set the docker disk image location to C:\ drive by default? I suggest you change it to another drive.
For example, set that in E:\
![image](https://github.com/infiniflow/ragflow/assets/41631274/883dfaa2-b6cd-4b3a-bdf3-e2929e0d637b)
First Step:stop all containers
Second Step: Set a new image location
Third Step: copy old files to new location

**Comment by WilliamCloudQi** [comment]
No, I have done this before. The location is E:\Appdata\DockerDesktopWSL.
