### ISSUE TITLE
[Question]: initial promt for bot

### ISSUE THREAD

**Issue by sensoryfox** [infiniflow/ragflow#573]
### Describe your problem

If you have found where the starting instructions for the bot are in one of the scripts, please provide a link. I've searched the whole database and can't understand where this promt comes from: "You are an intelligent assistant. Please summarize the content of the knowledge base to answer the question."

Thanks

**Comment by Jnmz** [comment]
https://github.com/infiniflow/ragflow/blob/944776f207fb9c5711f3911f31805130c0d70971/web/src/locales/en.ts#L307

**Comment by sensoryfox** [comment]
!!!Thanx
