### ISSUE TITLE
Display the current language directly at the top

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#577]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

944776f207fb9c5711f3911f31805130c0d70971

### Actual behavior

The current language is not displayed directly at the top

### Steps to reproduce

```Markdown
The current language is not displayed directly at the top
```

**Comment by KevinHuSh** [comment]
fixed.
