### ISSUE TITLE
[Bug]: connecting to redis:6379. Name or service not known

### ISSUE THREAD

**Issue by t6am3** [infiniflow/ragflow#580]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ae501c5

### Actual behavior

just upload and parse a pdf

### Steps to reproduce

```Markdown
1. Just follow the quick start steps to luanch a local server.
2. Upload a pdf file and parse it, that's it.
```

### Additional information

I found that there is no redis service in docker-compose-base.yml

**Comment by KevinHuSh** [comment]
You could ignore the warning log.
And in latest code and image, I've already remove the default redis configuration so the message will not show again.
