### ISSUE TITLE
[Feature Request]: Use API to build my application

### ISSUE THREAD

**Issue by charmby** [infiniflow/ragflow#598]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In the documentation, I only found the use of the UI interface to use the entire code base. I had a scenario where I prepared a bunch of document files, and then given a path, I passed the path of the document to the initialization path. Then you can use it directly by passing in the query, and then this interface can return the recall results. I'm not sure where I can find the documentation for this usage?

**Comment by netandreus** [comment]
Up, I'm interesting too.

**Comment by Valdanitooooo** [comment]
I am currently using it well 😉 
https://github.com/infiniflow/ragflow/pull/1763#issuecomment-2262126742

**Comment by JinHai-CN** [comment]
API already provided.
