### ISSUE TITLE
[Bug]: Upload file successfully, but it's empty when clicking to view it.

### ISSUE THREAD

**Issue by tongtongmaneng** [infiniflow/ragflow#600]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

master

### Commit ID

12355

### Actual behavior

![微信图片编辑_20240429092025](https://github.com/infiniflow/ragflow/assets/89182481/81af0dbe-6725-4361-b507-d733e65e4a99)

### Expected behavior

符合预期的正常状态

### Steps to reproduce

```Markdown
数据集-》新增文件-》成功-》点击文件名称-》空白页面
```

**Comment by tongtongmaneng** [comment]
[Uploading 话术1.txt…]()

**Comment by KevinHuSh** [comment]
Please attach a sample of this file.

**Comment by hcf624804** [comment]
需要先解析

**Comment by tongtongmaneng** [comment]
[话术1.txt](https://github.com/infiniflow/ragflow/files/15145814/1.txt)

**Comment by KevinHuSh** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> master
> 
> ### Commit ID
> 12355
> 
> ### Other environment information
> _No response_
> 
> ### Actual behavior
> ![微信图片编辑_20240429092025](https://private-user-images.githubusercontent.com/89182481/326311766-81af0dbe-6725-4361-b507-d733e65e4a99.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Mzk2MTcsIm5iZiI6MTcxNDQzOTMxNywicGF0aCI6Ii84OTE4MjQ4MS8zMjYzMTE3NjYtODFhZjBkYmUtNjcyNS00MzYxLWI1MDctZDczM2U2NWU0YTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYmRjMjEyYTQ1YmI0Y2U4NjcwNWYzN2QwNDMxOTFkNWE1NzY1ZWM2MDBmOWMxOGU3ZmJkMTlhM2ExOGVkODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bLPkoL3qjwZJm0gXrXtIHkVZieNYZDqYINu-YlBihmI)
> 
> ### Expected behavior
> 符合预期的正常状态
> 
> ### Steps to reproduce
> ```
> 数据集-》新增文件-》成功-》点击文件名称-》空白页面
> ```
> 
> ### Additional information
> _No response_

It seems work fine on our demo site. Is it locally deployed? Check the wether you push the 'Go' buttom after successfully uploading the file.
![image](https://github.com/infiniflow/ragflow/assets/12318111/6205edbb-129c-4d17-8bbb-da380fdf76c6)
