### ISSUE TITLE
[Question]: add Ollama model，why model type is image2text

### ISSUE THREAD

**Issue by hcf624804** [infiniflow/ragflow#603]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/22130536/30d978f3-34f1-45e7-bef7-02ae9b80cde3)

**Comment by hcf624804** [comment]
Causing me to be unable to select the model in Ollama when configuring the chat model

**Comment by KevinHuSh** [comment]
While adding model in Ollama, do you toggle the visual button?

**Comment by hcf624804** [comment]
> While adding model in Ollama, do you toggle the visual button?

![image](https://github.com/infiniflow/ragflow/assets/22130536/b36f5180-dab9-4d6f-a886-ef5e907fb047)
Is this the button？

**Comment by KevinHuSh** [comment]
> > While adding model in Ollama, do you toggle the visual button?
> 
> ![image](https://private-user-images.githubusercontent.com/22130536/326627107-b36f5180-dab9-4d6f-a886-ef5e907fb047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDExNjIsIm5iZiI6MTcxNDQ0MDg2MiwicGF0aCI6Ii8yMjEzMDUzNi8zMjY2MjcxMDctYjM2ZjUxODAtZGFiOS00ZDZmLWE4ODYtZWY1ZTkwN2ZiMDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzUxMzUzZWUwZjRjN2UwMDlkMzhlZDRiMWU1YmQyM2Q5YjQ4MjJkZWFlZDMzMDFhZDQyNDA3ZTllMzQ2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9lJTPWdxGvoov21r7p8DZIFdNzbsmO9eRz57SO0aUMw) Is this the button？

Exactly.

**Comment by hcf624804** [comment]
> > > While adding model in Ollama, do you toggle the visual button?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/22130536/326627107-b36f5180-dab9-4d6f-a886-ef5e907fb047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDExNjIsIm5iZiI6MTcxNDQ0MDg2MiwicGF0aCI6Ii8yMjEzMDUzNi8zMjY2MjcxMDctYjM2ZjUxODAtZGFiOS00ZDZmLWE4ODYtZWY1ZTkwN2ZiMDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzUxMzUzZWUwZjRjN2UwMDlkMzhlZDRiMWU1YmQyM2Q5YjQ4MjJkZWFlZDMzMDFhZDQyNDA3ZTllMzQ2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9lJTPWdxGvoov21r7p8DZIFdNzbsmO9eRz57SO0aUMw) Is this the button？
> 
> Exactly.
I have selected it, but the model type is still image2Text

**Comment by KevinHuSh** [comment]
Don't select.
