### ISSUE TITLE
[Question]: how to go login.html

### ISSUE THREAD

**Issue by chuanSir123** [infiniflow/ragflow#604]
### Describe your problem

I have started the docker ,and it return "http://127.0.0.1:9380“，but I can't access it

**Comment by chuanSir123** [comment]
now,it return  {"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"}

**Comment by chuanSir123** [comment]
可以了，windows不能用默认80端口

**Comment by KevinHuSh** [comment]
> ### Describe your problem
> I have started the docker ,and it return "[http://127.0.0.1:9380“，but](http://127.0.0.1:9380%E2%80%9C%EF%BC%8Cbut) I can't access it

No port need to be  specified.

**Comment by chuanSir123** [comment]
> > ### Describe your problem
> > I have started the docker ,and it return "[http://127.0.0.1:9380“，but](http://127.0.0.1:9380%E2%80%9C%EF%BC%8Cbut) I can't access it
> 
> No port need to be specified.

it's ok,windows can;t use 80 port,i have modified
