### ISSUE TITLE
File names that are too long will overflow the text box

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#607]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

2af74cc494fa888da3aa75ba61ae97d466701d17

### Actual behavior

File names that are too long will overflow the text box

### Steps to reproduce

```Markdown
File names that are too long will overflow the text box
```

**Comment by KevinHuSh** [comment]
fixed.
