### ISSUE TITLE
[Bug]: ragflow The requested image's platform (linux/amd64)

### ISSUE THREAD

**Issue by kurtisjuwensx** [infiniflow/ragflow#610]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

no

### Other environment information

```Markdown
Hardware parameters:Mac M1
OS type:13.5
```

### Actual behavior

ragflow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### Expected behavior

normally run

### Steps to reproduce

```Markdown
docker compose -f docker-compose-CN.yml up -d
```

### Additional information

![image](https://github.com/infiniflow/ragflow/assets/120342442/31cb3b55-dfd6-4fc8-b90a-b4196d38fe7f)

_No response_

**Comment by KevinHuSh** [comment]
Your machine is arm64 based which is not supported by our current docker images. We're working on it.

**Comment by 1of13** [comment]
@KevinHuSh  
When do you expect the arm64 update to be released?

**Comment by sprklinginfo** [comment]
+1. I wish the documentation would note that it wouldn't work on Mac M1 at this moment. I spent an entire day setting it up on my mac M1 and finally got the stack running up. tried to parse a plain text file several times and always stuck at around 3%. when searching around why it did not parse, and found it here. I think I know why it wouldn't work now.

**Comment by dorhunova-n-ix** [comment]
@FellowTraveler Same for me.

**Comment by yuzhichang** [comment]
https://github.com/infiniflow/ragflow/blob/main/docs/guides/develop/build_docker_image.md
