### ISSUE TITLE
[Bug]:  Fail to access model(llama3).**ERROR**: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by CreaterZXW** [infiniflow/ragflow#612]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b21a

### Actual behavior

集成ollama出现的错误

### Steps to reproduce

```Markdown
集成ollama出现的错误
```

**Comment by KevinHuSh** [comment]
Make sure the IP address you input the blank is accessible from the ragflow docker container.

**Comment by CreaterZXW** [comment]
Fail to connect to es: Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x717580c45ad0>: Failed to resolve 'es01' ([Errno -3] Temporary failure in name resolution))).新的错误

**Comment by mycarlos26** [comment]
> Use http://host.docker.internal:11434/

I was presenting the same problem in this thread and with your comment I was able to solve the problem, thank you.

**Comment by CreaterZXW** [comment]
提示 : 102
Fail to access model(llama3:instruct).**ERROR**: [Errno 111] Connection refused.还是同样的错误

**Comment by chenshuizhong** [comment]
> 提示：102 无法访问 model（llama3：instruct）。**ERROR**： [Errno 111] Connection refused.还是同样的错误

Make sure that your ollama service is bound to an IP and that the ip:port can be accessed by ragflow-server

**Comment by goldeneave** [comment]
> 提示 : 102 Fail to access model(llama3:instruct).**ERROR**: [Errno 111] Connection refused.还是同样的错误

解决了吗

**Comment by zzlTim** [comment]
http://host.docker.internal:11434/
still error
Fail to access model(llama3).**ERROR**: [Errno -2] Name or service not known
how to solve it

**Comment by Alcibiado** [comment]
需要修改ollama配置
由于默认ollama绑定在127.0.0.1的11434端口，其他IP都拒绝
使用docker只能访问到自己不能访问到宿主机上，所以需要将ollama服务暴露给网络
方法修改如下文件：
   
   > vim /etc/systemd/system/ollama.service

在[Service]下继续添加如下内容，使ollama绑定到0.0.0.0的11434端口

   > Environment="OLLAMA_HOST=0.0.0.0"

填入的基础URL为

  > http://host.docker.internal:11434/

**Comment by ben-8878** [comment]
设置了，Environment="OLLAMA_HOST=0.0.0.0" 也没有用

**Comment by goldeneave** [comment]
> Use http://host.docker.internal:11434/

That also help me solve my problem, thank you!

**Comment by syuuhakuyou103834** [comment]
this might help, works for me
https://community.modelscope.cn/67402ed32db35d11950fd558.html

**Comment by wanyang123** [comment]
Fail to access model(Ollama/llamafamily/llama3-chinese-8b-instruct:latest).**ERROR**: CONNECTION_ERROR - litellm.APIConnectionError: Ollama_chatException - Cannot connect to host host.docker.internal:11434 ssl:default [Connect call failed ('192.168.65.254', 11434)] LiteLLM Retried: 5 times，我这个咋解决呀，朋友们，我试过http://host.docker.internal:11434/这个也不行
