### ISSUE TITLE
[Question]: PyMuPDF dependency

### ISSUE THREAD

**Issue by shedar** [infiniflow/ragflow#613]
### Describe your problem

PyMuPDF is [in the requirements](https://github.com/infiniflow/ragflow/blob/main/requirements.txt#L94), and it's [licensed](https://github.com/pymupdf/PyMuPDF?tab=readme-ov-file#license-and-copyright) as AGPL-3.0 or commerical.
To my knowledge, Apache-2.0 (ragflow's license) is not compatible with AGPL. 
So, unless infiniflow owns a commercial license that allows to use PyMuPDF in ragflow under Apache-2.0, it's better to replace PyMuPDF.

**Comment by KevinHuSh** [comment]
We will replace it with others.

**Comment by KevinHuSh** [comment]
fixed.

**Comment by Arrivederci** [comment]
@KevinHuSh 可以请教下之前使用 PyMuPDF 的原因吗？以前代码的逻辑是 pdfplumber 读取失败的情况下改用 PyMuPDF 读取，请问什么在情况下前者会失败挂掉呢？
