### ISSUE TITLE
[Bug]:  Inconsistent Document Count Displayed in Knowledge Base

### ISSUE THREAD

**Issue by Alphayellowcat** [infiniflow/ragflow#620]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Other environment information

```Markdown
- Operating System: Windows 10
- Browser: Chrome
- ragflow version: latest
```

### Actual behavior

The document count displayed on the main page is inconsistent with the actual number of files in the knowledge base, with fewer numbers being shown.

### Expected behavior

The main page should reflect the actual number of documents present in the knowledge base.

### Steps to reproduce

```Markdown
1. Log in to the ragflow project.
2. Navigate to the knowledge base section.
3. Observe the document count displayed on the main page.
```

### Additional information

![image](https://github.com/infiniflow/ragflow/assets/41631274/a3f740c3-2d66-457d-8ba0-d1c20400cf80)
![image](https://github.com/infiniflow/ragflow/assets/41631274/08d4c985-aa2e-4813-b5c4-b106a8f19a4c)

**Comment by KevinHuSh** [comment]
We are gona fix it.

**Comment by KevinHuSh** [comment]
Upgrade to the latest dev version of the docker image. Problem solved for new knowledgebases.
But the former data is still there.
