### ISSUE TITLE
[Question]: parsing is very slow and basically unavailable, the advantages of the model are hard to perceive

### ISSUE THREAD

**Issue by yawude** [infiniflow/ragflow#623]
### Describe your problem

Document parsing is very slow and basically unavailable, the advantages of the model are hard to perceive

**Comment by KevinHuSh** [comment]
We're working on accelerating parsing speed.
And parsing is slow partly because text embedding is processing at the same time. 
It's gona be realy slow if you're using CPU.

**Comment by empty2enrich** [comment]
> We're working on accelerating parsing speed。 And parsing is slow partly because text embedding is processing at the same time. It's gona be realy slow if you're using CPU.

How do I specify the GPU to use?
