### ISSUE TITLE
[Bug]: [ERROR]Internal server error: Resume parser remote call fail!

### ISSUE THREAD

**Issue by chiangzg** [infiniflow/ragflow#625]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8acc01a227071c00dd452d76d08bc5c934a600fa

### Actual behavior

[ERROR]Internal server error: Resume parser remote call fail!
![msedge_J4TbKfaSpl](https://github.com/infiniflow/ragflow/assets/13807350/d665bbd2-4c98-4d39-9fec-069d4f76e4e4)

where is the server on port 61670 ？

### Steps to reproduce

```Markdown
1.create a knowledge base of resume and parse methods select to resumes.
2.upload a resume.
```

**Comment by KevinHuSh** [comment]
Parsing resume is not source opened yet.

**Comment by kam-st** [comment]
@KevinHuSh 

If you move back to general after selecting resume once. then error persists. And only solution is to delete complete knowledge base and recreate. Can you please look into that?
