### ISSUE TITLE
fix: filter knowledge list by keywords

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#627]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7d3b68bb1e176c236708d60369489df144da36d8

### Actual behavior

fix: filter knowledge list by keywords
fix: clear the selected file list after the file is uploaded successfully
feat: add ellipsis pattern to chunk list

### Steps to reproduce

```Markdown
fix: filter knowledge list by keywords
fix: clear the selected file list after the file is uploaded successfully
feat: add ellipsis pattern to chunk list
```

**Comment by KevinHuSh** [comment]
applied.
