### ISSUE TITLE
解析太慢了！一篇文档还没解析完，我已经读完了。

### ISSUE THREAD

**Issue by running-frog** [infiniflow/ragflow#632]
### Describe your problem

解析一篇80页的文档，需要10分钟！太慢了！
还没解析完，我已经读完了。

**Comment by KevinHuSh** [comment]
We are working on it. 
If it is locally deployed. It depends on the machine very much.

**Comment by miamiamiaccc** [comment]
I used the image `infiniflow/ragflow:dev-slim` and uploaded a 5-page PDF paper. The parsing is stuck at 83% and doesn't progress. How can I resolve this issue? I sincerely seek guidance from experienced individuals.

**Comment by KevinHuSh** [comment]
It's probably on embedding procedure.
Use a SAAS embedding, I guess that will be good enough.
