### ISSUE TITLE
[Question]: cloud storage like s3

### ISSUE THREAD

**Issue by kratorado** [infiniflow/ragflow#638]
### Describe your problem

Minio is good enough for individual use but in business scenario we want a more flexible file storage service like s3 or any other. This may not be the one of the main targets of ragflow, so I want to know where to start to contribute, thanks.
Great job BTW, hope API docs coming soon.

**Comment by KevinHuSh** [comment]
S3 and minio basically share the same api. 
Just add another utility in rag/util instead of using minio.

**Comment by JinHai-CN** [comment]
Minio is compatible with S3 protocol.
