### ISSUE TITLE
[Bug]: pdf file parsing failed

### ISSUE THREAD

**Issue by epicblue** [infiniflow/ragflow#641]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

3050a8c

### Actual behavior

[Split-Split-Apress.Practical.WPF.Charts.and.Graphics.Nov.2009(601-709)(1-54).pdf](https://github.com/infiniflow/ragflow/files/15209983/Split-Split-Apress.Practical.WPF.Charts.and.Graphics.Nov.2009.601-709.1-54.pdf)
无法完成pdf解析，大概所有页面都处理完了，进度百分比就停住了，然后等了一个多小时，进度百分比也没有变化，就这样卡死了。

### Expected behavior

完成pdf文件解析。

### Steps to reproduce

```Markdown
知识库正常上传，点击启动解析按钮。
```

**Comment by KevinHuSh** [comment]
I uploded on the demo website. It works fine.
If you deployed locally, have a look at logs using docker logs -f ragflow-server

**Comment by chuangzhidan** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Branch name
> main
> 
> ### Commit ID
> [3050a8c](https://github.com/infiniflow/ragflow/commit/3050a8cb07fd0de57f3244ba9a4cbfedc064634c)
> 
> ### Other environment information
> _No response_
> 
> ### Actual behavior
> [Split-Split-Apress.Practical.WPF.Charts.and.Graphics.Nov.2009(601-709)(1-54).pdf](https://github.com/infiniflow/ragflow/files/15209983/Split-Split-Apress.Practical.WPF.Charts.and.Graphics.Nov.2009.601-709.1-54.pdf) 无法完成pdf解析，大概所有页面都处理完了，进度百分比就停住了，然后等了一个多小时，进度百分比也没有变化，就这样卡死了。
> 
> ### Expected behavior
> 完成pdf文件解析。
> 
> ### Steps to reproduce
> 知识库正常上传，点击启动解析按钮。
> ### Additional information
> _No response_

现在有遇到这个问题吗，我的是进度到中间，然后解析失败了
