### ISSUE TITLE
[Feature Request]: Print version or commit-id when RAGFlow is started.

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/ragflow#643]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

No version or commit-id is printed when we start RAGFlow server. If there are any issue, we don't know if it is resolved in the latest version or need to be filed with a specific version information.

This feature request proposes to print version or commit-id in log when RAGFlow is started.

**Comment by sipeter** [comment]
agree. Or it can be added somewhere on the project page.

**Comment by JinHai-CN** [comment]
Fixed
