### ISSUE TITLE
[Question]: How to deploy the ragflow project in a seperated local network?

### ISSUE THREAD

**Issue by calchemist** [infiniflow/ragflow#645]
### Describe your problem

I deploy the ragflow project on a server with network (say，server A)  successfully.
And now I try to deploy the ragflow project on a server in a seperated local network(say, server B).
I save the docker images into a ragflow-images.tar.gz from server A.
And then load those images on server B(docker load -i ragflow-images.tar.gz).
Then run the command "docker-compose up -d" to start the ragflow.
But failed.
The ragflow image report error "Get https://registry-1.docker.io/v2 ……dail tcp……on host *****， no such host”
And other images report error "context canceled" and then exit.
What should I do? Help!

**Comment by KevinHuSh** [comment]
I doubt you didn't save and load the image correctly.
