### ISSUE TITLE
You can click the Parse Document button repeatedly

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#648]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

3050a8cb07fd0de57f3244ba9a4cbfedc064634c

### Actual behavior

You can click the Parse Document button repeatedly

### Steps to reproduce

```Markdown
You can click the Parse Document button repeatedly
```

**Comment by KevinHuSh** [comment]
fixed
