### ISSUE TITLE
Chinese txt file[Bug]: 

### ISSUE THREAD

**Issue by Dereklin66** [infiniflow/ragflow#651]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

e,g,main

### Commit ID

123

### Actual behavior

[西游记.txt](https://github.com/infiniflow/ragflow/files/15227698/default.txt)
Insert Chinese txt long text, unable to vectorize

### Steps to reproduce

```Markdown
Chunk method：general.
embedding method:text-embedding-v2
language:chinese
```

**Comment by KevinHuSh** [comment]
fixed.
