### ISSUE TITLE
[Question]: Future Plans for Public Release of OCR/Layout Rec Model Fine-Tuning Solutions

### ISSUE THREAD

**Issue by JudeZzz1997** [infiniflow/ragflow#652]
### Describe your problem

Hi！

I'm reaching out to inquire about any plans your team might have regarding the future release of fine-tuning guidelines. As a developer working on a project that heavily relies on accurate text extraction and document structure understanding, I am particularly interested in the potential for further customization and optimization of your models to suit our unique use cases.

Also I found that the parsing of documents in the online demo and the open source version are not consistent, are they using different models?

**Comment by KevinHuSh** [comment]
Online demo uses private data to fine-tuning the model. We will release source code of training in  the future.
Thanks for following us.

**Comment by vishwast-Kore** [comment]
Hey @KevinHuSh has the source code for training been released?
