### ISSUE TITLE
[Question]: OPENBLAS blas_thread_init: pthread_create failed for thread x of 64: Operation not permitted

### ISSUE THREAD

**Issue by calchemist** [infiniflow/ragflow#654]
### Describe your problem

Help!
On server B，I load docker images which are saved on server A.
And then "docker-compose up -d" to start the ragflow project.
When I try to check the ragflow status with "docker logs -f ragflow-server"
I got a lot of OpenBLAS errors as follows:
![微信图片_20240507103313](https://github.com/infiniflow/ragflow/assets/5035933/662b7252-0ed4-4348-bc80-961d2de543eb)
![微信图片_20240507103322](https://github.com/infiniflow/ragflow/assets/5035933/cc83f933-3369-483e-a9b6-8165552001d8)

**Comment by KevinHuSh** [comment]
May this help.
https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable
