### ISSUE TITLE
[Bug]: ragflow index failed

### ISSUE THREAD

**Issue by jindc** [infiniflow/ragflow#655]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c6b6c748aeada942c10df6c224a3271605f4a9e1

### Other environment information

```Markdown
ubuntu
```

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/5327158/56ad983e-96ab-482f-b236-2fedb97f7762)

页面弹出的错误：
ApiError('search_phase_execution_exception', meta=ApiResponseMeta(status=503, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'content-type': 'application/vnd.elasticsearch+json;compatible-with=8', 'content-length': '365'}, duration=0.004369974136352539, node=NodeConfig(scheme='http', host='es01', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/8.12.1 (Python/3.11.0; elastic-transport/8.12.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'no_shard_available_action_exception', 'reason': None}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'ragflow_304817a205d211efa4de0242ac160005', 'node': None, 'reason': {'type': 'no_shard_available_action_exception', 'reason': None}}]}, 'status': 503})

elastic search 后台报错：
{"@timestamp":"2024-05-07T03:39:11.336Z", "log.level": "WARN", "message":"path: /ragflow_304817a205d211efa4de0242ac160005/_search, params: {index=ragflow_304817a205d211efa4de0242ac160005}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][search_coordination][T#80]","log.logger":"rest.suppressed","elasticsearch.cluster.uuid":"MvZoYIAdTMWhGEX3adXSfw","elasticsearch.node.id":"IczakUhqQ8W-GWb51_3Oew","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"rag_flow","error.type":"org.elasticsearch.action.search.SearchPhaseExecutionException","error.message":"all shards failed","error.stack_trace":"Failed to execute phase [query], all shards failed; shardFailures {[_na_][ragflow_304817a205d211efa4de0242ac160005][0]: org.elasticsearch.action.NoShardAvailableActionException\n}{[_na_][ragflow_304817a205d211efa4de0242ac160005][1]: org.elasticsearch.action.NoShardAvailableActionException\n}\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:731)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:422)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:763)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:516)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:330)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.run(AbstractSearchAsyncAction.java:266)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:473)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:221)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.lambda$newSearchPhase$0(TransportSearchAction.java:1269)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.finishPhase(CanMatchPreFilterSearchPhase.java:374)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.finishRound(CanMatchPreFilterSearchPhase.java:329)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.onOperationFailed(CanMatchPreFilterSearchPhase.java:315)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$Round.doRun(CanMatchPreFilterSearchPhase.java:263)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.runCoordinatorRewritePhase(CanMatchPreFilterSearchPhase.java:189)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.run(CanMatchPreFilterSearchPhase.java:142)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.CanMatchPreFilterSearchPhase$1.doRun(CanMatchPreFilterSearchPhase.java:429)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: org.elasticsearch.action.NoShardAvailableActionException\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.NoShardAvailableActionException.forOnShardFailureWrapper(NoShardAvailableActionException.java:28)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:551)\n\tat org.elasticsearch.server@8.11.3/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:498)\n\t... 21 more\n"}

对文件进行索引时就出现错误

### Expected behavior

期望可以建立索引

### Steps to reproduce

```Markdown
正常部署即可复现
```

**Comment by KevinHuSh** [comment]
Is it possible you're low in disk space?

**Comment by jindc** [comment]
> Is it possible you're low in disk space?

![image](https://github.com/infiniflow/ragflow/assets/5327158/9941e078-fe79-4928-8232-d7cf4169f455)
感觉硬盘空间是够的

**Comment by jindc** [comment]
感觉像是es的内存少导致的问题，修改了es docker的内存大小，然后删除之前的es data volumne ，然后重新创建就可以了

**Comment by dingidng** [comment]
> 感觉像是es的内存少导致的问题，修改了es docker的内存大小，然后删除之前的es data volumne ，然后重新创建就可以了

请问一下es内存参数在那个文件修改
