### ISSUE TITLE
[Bug]: Using Docker deployllama in Windows environment, ragflow after using ragflow API call prompt Token is not valid!

### ISSUE THREAD

**Issue by yoohhwz** [infiniflow/ragflow#661]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

cccc

### Actual behavior

After I deployed Olama and Ragflow using Docker on Windows, when I used Ragflow's API call, it came up with Token is not valid! If I don't use APIs, it's okay to use web conversations
![微信图片_20240507131634](https://github.com/infiniflow/ragflow/assets/45910698/4f82e663-6488-44a0-a7d3-a66443dae20c)

### Steps to reproduce

```Markdown
Firstly, I installed DockerDesktop on Windows, and then I used Docker to install Ollama and Ragflow. After that, using Ragflow's web, I was able to have normal conversations, but when using Ragflow's API, it stopped working and prompted Token is not valid!, Even if I create a new API key, it is not possible
```

**Comment by ChromaticVizier** [comment]
How did you fix this? I found the same question when I run the demo on my own server, but it's ok when I use the web url(demo.ragflow.io) instead of my server ip.
