### ISSUE TITLE
[Bug]: PDF parsing stucked.

### ISSUE THREAD

**Issue by albertimff** [infiniflow/ragflow#673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

i don‘t know

### Commit ID

I don’t know

### Actual behavior

上传pdf文件后，会出现下面的报错。
![image](https://github.com/infiniflow/ragflow/assets/154483517/81bf8d83-9875-46c8-bcfa-14ee7a8cd3fb)
上传word，excel文件不会出现报错，但是parsing一直卡住。
![image](https://github.com/infiniflow/ragflow/assets/154483517/a2d4f464-859a-4ad6-8a8c-90b022be392e)

### Steps to reproduce

```Markdown
None
```

**Comment by KevinHuSh** [comment]
Is it locally deployed?
If it is, upgrade  it.
![image](https://github.com/infiniflow/ragflow/assets/12318111/bbd9b887-71ac-4814-aa68-880807e8fbb2)

docker ps
make sure the Redis is up.
