### ISSUE TITLE
[Bug]: Load term.freq FAIL

### ISSUE THREAD

**Issue by cklogic** [infiniflow/ragflow#677]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

main

### Other environment information

```Markdown
OS:Debian
Python:11
```

### Actual behavior

运行api/ragflow_server.py的时候报
`[WARNING] Load term.freq FAIL!`

```
ls rag/res
1-0.tm  broker.tm  deepdoc  huqie.txt  huqie.txt.trie  ner.json  synonym.json
```
rag/res目录下没有term.freq

请问影响程序运行吗？这个文件是干嘛的？需要怎么做才能有这个文件？

### Steps to reproduce

```Markdown
python api/ragflow_server.py
```

**Comment by KevinHuSh** [comment]
Ignore this warning log.
