### ISSUE TITLE
[Bug]: {"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"}

### ISSUE THREAD

**Issue by sirus20x6** [infiniflow/ragflow#678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7ddb2f1

### Other environment information

```Markdown
-`                    sirus@neuromancer 
                  .o+`                   ----------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MZ32-AR0-00 0100 
               `+oooooo:                 Kernel: 6.8.9-arch1-1 
               -+oooooo+:                Uptime: 2 days, 4 hours, 53 mins 
             `/:-:++oooo+:               Packages: 2350 (pacman), 6 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.2.26 
           `/++++++++++++++:             Resolution: 3840x2160, 3840x2160 
          `/+++ooooooooooooo/`           DE: Xfce 4.18 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-`/ossssss+`         WM Theme: Default 
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
      :osssssss/        osssso+++.       Icons: elementary [GTK2], Adwaita [GTK3] 
     /ossssssss/        +ssssooo/-       Terminal: xfce4-terminal 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Monospace 12 
  `+sso+:-`                 `.-/+oso:    CPU: AMD EPYC 7473X (48) @ 2.800GHz 
 `++:.                           `-/+/   GPU: AMD ATI Radeon RX 7900 XT/7900 XTX/7900M 
 .`                                 `/   Memory: 203891MiB / 515839MiB
```

### Actual behavior

doesn't seem to work. I added my openai api key and started the docker container and connected

### Steps to reproduce

```Markdown
the install steps on the main github page
```

**Comment by KevinHuSh** [comment]
Please specified the scenario.

**Comment by d3vansh36** [comment]
When I try to hit the upload endpoint, I encounter this issue.

Code:
`response = requests.post(
                "http://192.168.1.250:81/v1/api/document/upload/",
                files={"file": open("C:\\Users\\Devansh\\Downloads\\imodoc.pdf",'rb')},
                data=data,
                headers=headers
            )
print(response.json())`

Output:
`{'data': None, 'retcode': 100, 'retmsg': "<NotFound '404: Not Found'>"}`

This occurs even when I hit it on port 9380. Other endpoints are working fine with port 81 as set by me.

**Comment by KevinHuSh** [comment]
9380 is back-end server port which is with a different API protocol.

**Comment by d3vansh36** [comment]
So what should I be doing ideally?

**Comment by timdonovanuk** [comment]
Unhelpful response, misleading documentation and logging but anyway..

@d3vansh36 the web front end runs on port 80, so you don't need to specify a port to access the web front end. Just hit http://<yourserverip>
