### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by andyaqu** [infiniflow/ragflow#679]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

7ddb2f19bee679d72cfc6d6affe4ef4df1f6b3a1

### Other environment information

```Markdown
centos 7.9 64
```

### Actual behavior

[ERROR]Internal server error: Coordinate right is less than left

### Steps to reproduce

```Markdown
[ERROR]Internal server error: Coordinate right is less than left

当我上传一个1.8m的pdf文件时，解析不成功
```

**Comment by KevinHuSh** [comment]
Could you upload a sample of this file?
