### ISSUE TITLE
[Question]: How to run docker ragflow on GPU？ 

### ISSUE THREAD

**Issue by Vicky4AI** [infiniflow/ragflow#681]
### Describe your problem

In current docker-compose.yaml file, it is not specified to run the docker on GPU, how should I change the yaml file? and how to stop current running docker( in yaml it is set to be always restart)

**Comment by KevinHuSh** [comment]
Please refer to: https://docs.docker.com/compose/gpu-support/#example-of-a-compose-file-for-running-a-service-with-access-to-1-gpu-device
