### ISSUE TITLE
[Question]: How RAGFlow compute the keywords similarity?

### ISSUE THREAD

**Issue by chenjl12** [infiniflow/ragflow#682]
### Describe your problem

How RAGFlow compute the similarity between query and chunk? How to get the keywords?

**Comment by KevinHuSh** [comment]
We use weighted similarity of keyword similarity and embedding similarity.
We use a tokenizer to get keywords and their weights.

**Comment by Nuclear6** [comment]
Why is keyword similarity not semantic similarity?
