### ISSUE TITLE
[Bug]: Parsing file error causing server got stuck

### ISSUE THREAD

**Issue by YannSuper** [infiniflow/ragflow#683]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name
main

### Commit ID

c3b2a1

### Actual behavior

1

### Expected behavior

![840371127766af698b28649d8e9ec0a](https://github.com/infiniflow/ragflow/assets/53294632/b6dedde1-6b16-4ea1-9c78-bc7782ab451f)

### Steps to reproduce

```Markdown
I'm reporting an error when parsing a file, and the server get stuck.

Link：https://pan.baidu.com/s/1PZXJrK847yyxcEyja51_ZA 
Code：test
```

**Comment by KevinHuSh** [comment]
fixed.
