### ISSUE TITLE
[Bug]: An error occurred in the backend while parsing a doc file

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#688]
### Is there an existing issue for the same bug?

- [ ] I have checked the existing issues.

### Branch name

v0.5.0

### Commit ID

48607c3cfbc66f79d1bec84ff7a557943b07c1b7

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/1617266/edae46cd-0fab-4165-b5b5-1f5ef44cf71e)

### Steps to reproduce

```Markdown
1.Uploaded a doc file
2.Parsing
3.Parsing failed, backend reported an error
```

**Comment by KevinHuSh** [comment]
Upgrade and use dev version.
https://github.com/infiniflow/ragflow/blob/main/docs/faq.md#9-how-to-upgrade-ragflow
