### ISSUE TITLE
[Feature Request]: 能不能零编码嵌入到企业的第三方系统

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#691]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
no
```

### Describe the feature you'd like

应用能不能像maxkb一样支持零编码嵌入到企业的第三方系统，用户可以复制全屏模式代码或浮窗模式代码嵌入到第三方系统中，嵌入完成后便可在第三方系统中进行用户问答。

**Comment by KevinHuSh** [comment]
Please refer to https://github.com/infiniflow/ragflow/blob/main/docs/conversation_api.md
