### ISSUE TITLE
[Question]: How to improve search quality

### ISSUE THREAD

**Issue by Nuclear6** [infiniflow/ragflow#698]
### Describe your problem

I found that when searching, I searched based on keywords and did not have a good understanding of some semantics. How can I improve the effect of re-ordering?

**Comment by KevinHuSh** [comment]
Suggestion:
1. Beside using keywords similarity, use embedding similarity.
2. Rewrite the query.
3. Add an extra dimension to both query and doc, say, categories.

**Comment by Nuclear6** [comment]
> Suggestion:
> 
> 1. Beside using keywords similarity, use embedding similarity.
> 2. Rewrite the query.
> 3. Add an extra dimension to both query and doc, say, categories.

Is there any specific guidance document here?

**Comment by Galaxy-Ding** [comment]
> Suggestion:
> 
> 1. Beside using keywords similarity, use embedding similarity.
> 2. Rewrite the query.
> 3. Add an extra dimension to both query and doc, say, categories.

Hi author, thanks for your great work, I would like to ask if I can format the document to be more conducive to querying if I follow the third point, or format the document, what are the ideas over here?
