### ISSUE TITLE
[Question]: Docker deployment, how to switch sources

### ISSUE THREAD

**Issue by xxxl123** [infiniflow/ragflow#701]
### Describe your problem

Docker deployed xinreference, replace with domestic download source

**Comment by xxxl123** [comment]
docker run -p 9997:9997 \
  -e HF_ENDPOINT=https://hf-mirror.com \
  -e XINFERENCE_MODEL_SRC=modelscope \
  --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

**Comment by KevinHuSh** [comment]
It's about XInference, you could address this issue to [this](https://github.com/xorbitsai/inference/issues)
