### ISSUE TITLE
[Bug]: The Freedom setting in Model Setting is not working as expected.

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#703]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

v0.5.0

### Commit ID

48607c3cfbc66f79d1bec84ff7a557943b07c1b7

### Actual behavior

1. Modify the Freedom setting in Model Setting for a conversation to "Balance" and save the changes.

2. Reopen the Model Setting for the conversation to check the current Freedom setting. It is observed that the setting is still "Precise" instead of "Balance".
![image](https://github.com/infiniflow/ragflow/assets/1617266/f2fcb01f-9ed5-4d7a-a13b-0f86d093ae26)

### Steps to reproduce

```Markdown
As mentioned above.
```

**Comment by cike8899** [comment]
Fixed

**Comment by cike8899** [comment]
Fixed

**Comment by chminsc** [comment]
I still run across this problem, by most recent version
