### ISSUE TITLE
[Question]: Support for multi-process concurrent document parsing

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#705]
### Describe your problem

The document parsing in ragflow is very slow, especially when parsing files in batches. Is it possible to support multi-process parsing?
![image](https://github.com/infiniflow/ragflow/assets/1617266/e5f05595-1258-4aaf-bd6c-4577175e5b4e)

![image](https://github.com/infiniflow/ragflow/assets/1617266/75c457da-ee1b-4d18-8d05-f45e5fbd6843)

**Comment by KevinHuSh** [comment]
If your machine is good enough, enlarge the WS in docker/entrypoint.sh.
Then docker build it to apply it.
