### ISSUE TITLE
[Bug]: Use ppt file, raise File is not a zip file error

### ISSUE THREAD

**Issue by 23233** [infiniflow/ragflow#706]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

?

### Other environment information

```Markdown
rag 0.5.0版本 
docker compose运行
```

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/12870070/2dacb5fc-8ebc-4b3c-976e-2810a3dfd21b)

### Expected behavior

成功解析

### Steps to reproduce

```Markdown
上传一个.ppt文件
```

### Additional information

[test ppt.zip](https://github.com/infiniflow/ragflow/files/15264145/test.ppt.zip)

**Comment by fire717** [comment]
Maybe not support .ppt but .pptx?

**Comment by KevinHuSh** [comment]
Yes.

**Comment by yuzhichang** [comment]
I've mentioned this at https://github.com/scanny/python-pptx/issues/818

**Comment by yuzhichang** [comment]
No python package work with .ppt file. Perhaps load and save to .pptx in PowerPoint first.
