### ISSUE TITLE
xinference model mount failure

### ISSUE THREAD

**Issue by ciaoyizhen** [infiniflow/ragflow#711]
### Describe your problem

I started chatglm3-32k via xinference, then clicked inside xinference add model inside ragflow and entered
{model category -> chat, model uid -> THUDM/chatglm3-6b-32k, base url -> ip+port of xinference service}
fail to access model(THUDM/chatglm3-6b-32k). **ERROR**; Connection error.

**Comment by KevinHuSh** [comment]
Do not forget add 'v1' to the URL.
And keep that in mind: network in docker container is different from the host. So, make sure the IP you use is accessible in the ragflow container.
