### ISSUE TITLE
Is the Embedding model self-contained?

### ISSUE THREAD

**Issue by ciaoyizhen** [infiniflow/ragflow#713]
### Describe your problem

cuda   11.7

Does this project come with an embedding model?
If it doesn't come with an embedding model, how do I start it?
If it does come with one, and my graphics card doesn't take it up when I start it, is my cuda version too low?
Do I need to use embedding model to parse files? I was successful in parsing the file.

**Comment by KevinHuSh** [comment]
Changing the docker compose yaml will enable the ragflow to use GPU.
Please refer [this](https://docs.docker.com/compose/gpu-support/#example-of-a-compose-file-for-running-a-service-with-access-to-1-gpu-device)
