### ISSUE TITLE
[Bug]: BadRequestError

### ISSUE THREAD

**Issue by Nuclear6** [infiniflow/ragflow#715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

master

### Commit ID

7059ec22987141cc1127fb6808e3bc5a6b466406

### Actual behavior

BadRequestError('search_phase_execution_exception', meta=ApiResponseMeta(status=400, http_version='1.1', headers={'X-elastic-product': 'Elasticsearch', 'content-type': 'application/vnd.elasticsearch+json;compatible-with=8', 'content-length': '783'}, duration=0.010804176330566406, node=NodeConfig(scheme='http', host='es01', port=9200, path_prefix='', headers={'user-agent': 'elasticsearch-py/8.12.1 (Python/3.11.0; elastic-transport/8.12.0)'}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={})), body={'error': {'root_cause': [{'type': 'query_shard_exception', 'reason': 'failed to create query: field [q_1536_vec] does not exist in the mapping', 'index_uuid': 'O6Wa_tGlTsOpCNXw1A0LpQ', 'index': 'ragflow_acac05b806bf11efb78c0242ac120005'}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'dfs', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'ragflow_acac05b806bf11efb78c0242ac120005', 'node': 'jAqn5uNJR7yUw3Yk9ceidw', 'reason': {'type': 'query_shard_exception', 'reason': 'failed to create query: field [q_1536_vec] does not exist in the mapping', 'index_uuid': 'O6Wa_tGlTsOpCNXw1A0LpQ', 'index': 'ragflow_acac05b806bf11efb78c0242ac120005', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field [q_1536_vec] does not exist in the mapping'}}}]}, 'status': 400})

### Steps to reproduce

```Markdown
Using the QA method to create a knowledge assistant, the document prompted me that the parsing was successful, but I encountered the above error during the actual test.
```

**Comment by yuhua01** [comment]
你好 请问你是怎么解决的这个问题

**Comment by yuhua01** [comment]
hello How did you solve this problem

**Comment by sleeprite** [comment]
hello How did you solve this problem
