### ISSUE TITLE
[Bug]: Queries can still retrieve the content when data is disabled in the knowledge base

### ISSUE THREAD

**Issue by trackcc** [infiniflow/ragflow#722]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

648a2ba

### Other environment information

```Markdown
CPU ： Intel(R) Xeon(R) Silver 4210 CPU
MEM ： 512G
GPU ： Nvidia Tesla A100 40G
OS  ： Ubuntu 22.04.4 LTS server
```

### Actual behavior

知识库中数据集被禁用后，查询时依然能够查询出来并关联内容

![image](https://github.com/infiniflow/ragflow/assets/1683641/2942c90a-249d-4dc3-baa4-b3bca18ed3af)

![image](https://github.com/infiniflow/ragflow/assets/1683641/95ab7495-df20-4ff3-a1a7-6e405bdfbe02)

### Steps to reproduce

```Markdown
1、禁用数据集
2、创建聊天助手
3、查询知识
4、回答中携带者禁用数据集中的知识和文件引用
```

**Comment by KevinHuSh** [comment]
It's already been fixed in the dev version.
Please upgrade it. FAQ has the detail about upgrading RAGFlow.
