### ISSUE TITLE
[Bug]: Failed to parsing pptx file and RAGFlow server crashed.

### ISSUE THREAD

**Issue by trackcc** [infiniflow/ragflow#723]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

648a2ba

### Other environment information

```Markdown
CPU ： Intel(R) Xeon(R) Silver 4210 CPU
MEM ： 512G
GPU ： Nvidia Tesla A100 40G
OS  ： Ubuntu 22.04.4 LTS server
```

### Actual behavior

ppt解析组件 aspose 报错  

 No usable version of libssl was found，
![image](https://github.com/infiniflow/ragflow/assets/1683641/f2c94485-8ed4-441c-b929-468661ef39b4)

### Steps to reproduce

```Markdown
上传PPT文件，点击保存

with slides.Presentation(BytesIO(blob)) as presentation:
执行到这里程序就崩溃了
```

**Comment by yingfeng** [comment]
Could you please provide the raw pptx file that leads to the corruption?

**Comment by trackcc** [comment]
我找了几个测试了一下都是程序崩溃，可能是环境兼容的问题
[Uploading 人工智能.pptx…]()

**Comment by trackcc** [comment]
在另一台上传成功了。。。
CPU ： Intel(R) Core(TM) i7-12700
MEM ： 64G
GPU ： Nvidia RTX A4000
OS  ： Ubuntu 18.04  desktop

**Comment by trackcc** [comment]
@yingfeng ubuntu 18之后不提供libssl1.1， 我的环境是ubuntu 22   Aspose.Slides依赖libssl1.1 导致运行到 with slides.Presentation(BytesIO(blob)) as presentation: 崩溃， 安装 libssl1.1 后正常  https://blog.csdn.net/weixin_47156401/article/details/134343800
