### ISSUE TITLE
[Feature Request]: Hope to add rerank models to the project

### ISSUE THREAD

**Issue by xxxl123** [infiniflow/ragflow#724]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

I think RAG+re-rank is a great combination that can improve recall accuracy.

**Comment by Nuclear6** [comment]
I see that there is a rerank module in the project architecture diagram. Does the module they provide fail to meet the requirements? Or some other problem?
<img width="790" alt="image" src="https://github.com/infiniflow/ragflow/assets/49468241/c9224a9f-1b7a-480b-a829-d62765b9364d">
![image](https://github.com/infiniflow/ragflow/assets/49468241/0cf5bd53-2c5f-4453-a6ff-6b7ce33b6a4a)

**Comment by xxxl123** [comment]
> I see that there is a rerank module in the project architecture diagram. Does the module they provide fail to meet the requirements? Or some other problem? <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/49468241/329907078-c9224a9f-1b7a-480b-a829-d62765b9364d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjkzNTEsIm5iZiI6MTcxNTU2OTA1MSwicGF0aCI6Ii80OTQ2ODI0MS8zMjk5MDcwNzgtYzkyMjRhOWYtMWI3YS00ODBiLWE4MjktZDYyNzY1YjkzNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyNTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMWYzM2Y1ODA5ZmQ3ODI1ZDkyYjI2ZWRlMmIxMTc2NGFhNGI0NzgxYmNmODliZDdhZWQyOTAzM2E1NDU3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IfyoVhzx8-UomSZuU2qBRFLuopNBaT1HnZDGQ9iUZBw"> ![image](https://private-user-images.githubusercontent.com/49468241/329907188-0cf5bd53-2c5f-4453-a6ff-6b7ce33b6a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjkzNTEsIm5iZiI6MTcxNTU2OTA1MSwicGF0aCI6Ii80OTQ2ODI0MS8zMjk5MDcxODgtMGNmNWJkNTMtMmM1Zi00NDUzLWE2ZmYtNmI3Y2UzM2I2YTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyNTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjkyN2I2YzAwZmQzNDcyODhiYjQxNmYxNTcyNGMxNTY1YTNmZmI0ZGJmZDJkMmVjZTQzN2Y4ZmI4NTgwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.13u9j4l4NcADnl3_yQxGbUQzsKJCmo4SJVL5cMQWYnQ)

I asked the developers, and they haven't added the rerank model yet.

**Comment by Nuclear6** [comment]
What you mean is that the rerank here is only based on some strategies to achieve the effect of rerank, and does not involve reranking LLM, right?

**Comment by xxxl123** [comment]
![image](https://github.com/infiniflow/ragflow/assets/97745427/2f1bb354-7729-43a9-8489-932cd536132a)
There should be a rearranging strategy, but the rerank model was not used.

**Comment by Nuclear6** [comment]
So I have a question, what rerank models are available here? Have you ever compared the results?

**Comment by KevinHuSh** [comment]
Weighted keywords and embedding similarity is RAGFlow's reranking model right now.
And we're working on replacing the embedding similarity with other so called rerank models like BGE reranker and others.

**Comment by xxxl123** [comment]
I think the accuracy of the recall is already very accurate now, and I hope it can be further improved. It shouldn't be worse after adding it.
