### ISSUE TITLE
[Question]: How do machines without GPU use embedding models to parse documents?

### ISSUE THREAD

**Issue by Nuclear6** [infiniflow/ragflow#727]
### Describe your problem

I built the ragflow project on a machine with only CPU. After running it, I found that the uploaded document could be parsed successfully using Tongyi Qianwen's embedding model. Is the embedding model calculated locally or remotely?

![image](https://github.com/infiniflow/ragflow/assets/49468241/4d7b4767-b6c5-49fa-a5c0-6a3636e87415)

Task has been received.
Start to parse.
Extract Q&A: 642. 38 failure, line: 22,34,53...
Finished slicing files(642). Start to embedding the content.
Finished embedding(366.5834937430918)! Start to build index!
Done!

PS: I haven’t applied for Tongyi Qianwen’s API key either.

**Comment by KevinHuSh** [comment]
It's locally. We add the model to the docker image.

**Comment by Nuclear6** [comment]
You mean, the embedding model can be run in cpu? According to my previous experience, the model needs to make some changes and adaptations to run in the CPU.
