### ISSUE TITLE
[Bug]: Parsing PDF file get stucked after uploading in new deployment

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#736]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

bef1bbdf3e16e5163bc563407bd7fd8f7da97d7a

### Actual behavior

 New deployed system, create a knowledgebase in general parse method, upload a PDF file, then click start.
It's always sth like 0.03% and in status Task is dispatched. Wait for long time with no change.
Cancel the task and restart it again, this time the parsing task will get real started very quickly.

### Expected behavior

Should be able to complete the parsing on the first time.

### Steps to reproduce

```Markdown
1. New deployed system.
2. Create a knowledgebase in general parse method.
3. Upload a PDF file.
4. Click start parsing.
5. Observe the status get stucked in Task is dispatched.
6. Cancel the task and restart it again, the parsing task will complete quickly.
```

**Comment by KevinHuSh** [comment]
We also find this, but we are not sure the reason yet.

**Comment by shaoyie** [comment]
> We also find this, but we are not sure the reason yet.

What I know is the version on Apr 17 works fine. So maybe check the changes related to task executor these days?

**Comment by KevinHuSh** [comment]
Try to upgrade it with the dev version. We fixed this.

**Comment by timdonovanuk** [comment]
This should remain open, as it's still an issue. Thanks.

**Comment by shaoyie** [comment]
Yes, and seems this issue happens sometime, reopen it.

**Comment by jasinliu** [comment]
Cancelling the task and restarting don't work for me. It's terrible

**Comment by jasinliu** [comment]
Maybe relate to #1383 . Hope the cause can be found and fixed as soon as possible.

**Comment by yuzhichang** [comment]
RAGFlow v0.14.0 system page show task-executor status. And the log files are reworked. Please have a try.
