### ISSUE TITLE
[Bug]: vector_similarity backend returns not displayed on frontend

### ISSUE THREAD

**Issue by moyueheng** [infiniflow/ragflow#742]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

33eaf6fa2ecc47c2f7b892ff9dd2110a2ff2cd0a

### Actual behavior

![image.png|700](https://tuchuang-1301374207.cos.ap-nanjing.myqcloud.com/img/20240512212915.png)

### Expected behavior

vector_similarity displayed

### Steps to reproduce

```Markdown
When conducting Retrieval testing, the front end should be able to display vector_similarity
```

### Additional information

When conducting Retrieval testing, the front end should be able to display vector_similarity
![image.png|700](https://tuchuang-1301374207.cos.ap-nanjing.myqcloud.com/img/20240512212915.png)

**Comment by KevinHuSh** [comment]
It's already displayed.  It is 62.37.
