### ISSUE TITLE
[Feature Request]: Model configuration can customize baseurl

### ISSUE THREAD

**Issue by empty2enrich** [infiniflow/ragflow#748]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
no
```

### Describe the feature you'd like

I have a local deployment model and hope to use my own URL instead of the official URL

Currently only the official api key can be configured

### Describe implementation you've considered

Model configuration can customize baseurl

### Documentation, adoption, use case

```Markdown
none
```

### Additional information

none

**Comment by KevinHuSh** [comment]
What kind of local model? Can you use ollama for this purpose?
