### ISSUE TITLE
[Question]: How to view cron_logger logs

### ISSUE THREAD

**Issue by Nuclear6** [infiniflow/ragflow#752]
### Describe your problem

Use this command to view the logs `docker logs -f ragflow-server`. You can only see the GET and POST request information, but cannot view the log information corresponding to cron_logger. How can I configure it to view the logs corresponding to the cron_logger log component?

PS：What I am more doubtful about is why 680 question and answer pairs are split into 473 blocks. I see that even after removing the code, the question and answer pairs are not filtered and merged. Why are some question and answer pairs missing?   

![image](https://github.com/infiniflow/ragflow/assets/49468241/50e836b8-13fe-40e3-86d4-04229d00aafb)

**Comment by KevinHuSh** [comment]
To see cron_logger.log, tail -f docker/ragflow-log/api/cron_logger.log

I guess there're a lot of duplicated questions.

**Comment by Nuclear6** [comment]
What do you mean there are a lot of duplicate questions here? When I searched for cron_logger, I only had this problem. Are you talking about the number of blocks?
![image](https://github.com/infiniflow/ragflow/assets/49468241/bbc67283-1a44-4e6d-8a02-2b58ca8bd37d)

**Comment by KevinHuSh** [comment]
> What do you mean there are a lot of duplicate questions here? When I searched for cron_logger, Only I have this cron_logger problem. Are you talking about the number of blocks? Why does the log show 680 blocks but the interface shows only 473 blocks? <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/49468241/330043282-4588524e-00bd-4cc0-ba49-8b556ae3b301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzQ5NjcsIm5iZiI6MTcxNTczNDY2NywicGF0aCI6Ii80OTQ2ODI0MS8zMzAwNDMyODItNDU4ODUyNGUtMDBiZC00Y2MwLWJhNDktOGI1NTZhZTNiMzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwNTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTFhMmE5MmE4ZDA2OWYzOGNhNWVkZTFlMjg4YWM2N2I5YTk3ZTYxYTQxZGU2Mzk0NTAyNGM5MTIxZmZlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hy1gEPIyiXgBZXHPdehPdFf-PDd7swn_pT27pA0zOQ4">

Sorry, I didn't make myself clear. 
I mean in your data set. there're must be alot of duplicated records.
