### ISSUE TITLE
[Feature Request]: Configurable Authentication Methods in the Backend

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#753]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In the backend service_conf.yml, you can configure to use the authentication method registered by the user or the GitHub OAuth authentication method.

**Comment by cike8899** [comment]
![image](https://github.com/infiniflow/ragflow/assets/8089971/b9765892-0ef1-461e-894e-383e9522ac2c)

Comment out the code in the red box above from the login page and the github button will be displayed.
