### ISSUE TITLE
[Bug]: requirements installing error with python 3.11.9 and aliyun pypi

### ISSUE THREAD

**Issue by CamusGao** [infiniflow/ragflow#756]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

48607c3cfbc66f79d1bec84ff7a557943b07c1b7

### Other environment information

```Markdown
conda 24.1.2
Python 3.11.9
Windows 10 22H2
```

### Actual behavior

Cannot install requirements with the below commands. I use python 3.11.9 installed by `conda create -n ragflow python=3.11 nodejs=14.8`
```bash
pip install -r requirements -i https://pypi.org/simple
pip install -r requirements -i https://mirrors.aliyun.com/pypi/simple
```
And the error is 
```
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.10.0 Requires-Python >=3.5,<3.11; 22.11.0 Requires-Python >=3.5,<3.11; 22.12.0 Requires-Python >=3.5,<3.11; 22.4.0 Requires-Python >=3.5,<3.10; 22.6.0 Requires-Python >=3.5,<3.11; 22.7.0 Requires-Python >=3.5,<3.11; 22.8.0 Requires-Python >=3.5,<3.11; 22.9.0 Requires-Python >=3.5,<3.11; 23.1.0 Requires-Python >=3.5,<3.11; 23.2.0 Requires-Python >=3.5,<3.11; 23.3.0 Requires-Python >=3.5,<3.11; 23.4.0 Requires-Python >=3.5,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu12==8.9.2.26 (from versions: 0.0.1.dev5, 8.9.4.25, 8.9.5.29, 8.9.6.50, 8.9.7.29, 9.0.0.312, 9.1.0.70)
ERROR: No matching distribution found for nvidia-cudnn-cu12==8.9.2.26
```

### Expected behavior

requirements installed successfully.

### Steps to reproduce

```Markdown
1. `conda create -n ragflow python=3.11 nodejs=14.8`
2. `pip install -r .\requirements.txt -i https://mirrors.aliyun.com/pypi/simple/`
```

### Additional information

I found the same problem reported at https://github.com/infiniflow/ragflow/issues/460#issuecomment-2105657281 but not be replied or resolved

**Comment by KevinHuSh** [comment]
Comment out the inconsistent package or remove the version number in requirement.txt.
Or you could use requirements_dev.txt.

**Comment by CamusGao** [comment]
@KevinHuSh The error occurred when installing `nvidia-cuda-runtime-cu12==12.1.105`. All resolutions you mentioned are not ok.
I launched a ubuntu 2204 container via docker desktop and installed requirements in the container successfully... __For windows guys, developing with wsl and vscode is a not too bad solution.__
