### ISSUE TITLE
[Bug]: Reserved keyword are used in the code as identifier.

### ISSUE THREAD

**Issue by yungongzi** [infiniflow/ragflow#757]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

9b21b66

### Actual behavior

在增加对火山引擎的支持时，需要改动llm_app.py，用到了list内置函数，报错。
发现：有些python内置关键字被占用
![关键字被占用](https://github.com/infiniflow/ragflow/assets/19431702/47b5d259-d3ed-42d6-9f7e-db1a962150ee)
以下是搜索发现：
![关键字被占用2](https://github.com/infiniflow/ragflow/assets/19431702/a321a371-5815-4173-8578-3d66cdd9fb35)

### Steps to reproduce

```Markdown
代码路径：ragflow/api/apps/llm_app.py
第 178 行
```

**Comment by KevinHuSh** [comment]
fixed.
