### ISSUE TITLE
[Question]: LookupError('Model(maidalun1020/bce-embedding-base_v1) not authorized')

### ISSUE THREAD

**Issue by HaoGuo98** [infiniflow/ragflow#758]
### Describe your problem

After i update ragflow， i can not use the chatbot which embeding model is QAnything.  And when i create a new kb, the embeding model can not find QAnything.

**Comment by yuhua01** [comment]
Hello. How did you solve it, please?

**Comment by 1940653868** [comment]
same problem, did you solve it?
