### ISSUE TITLE
[Question]: Model(text-embedding-v2) not authorized

### ISSUE THREAD

**Issue by yeungsean** [infiniflow/ragflow#778]
### Describe your problem

<img width="879" alt="image" src="https://github.com/infiniflow/ragflow/assets/115068410/61a50f9c-5d8c-45ac-b2f0-f44734bc6d05">

**Comment by KevinHuSh** [comment]
Did it happend on demo site or locally deployed?

**Comment by Scoutink** [comment]
On the demo site of ragflow it is not working.

**Comment by ndmil** [comment]
![image](https://github.com/infiniflow/ragflow/assets/16062704/a2717883-f613-4e1f-926a-ad1343cc64e8)

same here. locally deployed.

**Comment by jx1100370217** [comment]
The problem hasn't been solved, why do you always like to close it? @KevinHuSh
