### ISSUE TITLE
[Bug]: Can't set assistant avatar

### ISSUE THREAD

**Issue by writinwaters** [infiniflow/ragflow#791]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

6ff63ee

### Actual behavior

![avatar](https://github.com/infiniflow/ragflow/assets/93570324/b39441ac-3be4-4533-a564-78d76c0e646c)

**Comment by yuzhichang** [comment]
Fixed
