### ISSUE TITLE
[Feature Request]: Specify documents for LLM chat with API

### ISSUE THREAD

**Issue by duchangyu** [infiniflow/ragflow#808]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
What I wanted to do is integrating RagFlow with existing project. So API is needed. 

The idea is: 
   1. Create a knowledge base and/or upload some documents from my system with API 
   2. Ask questions and get answers *only* from these specified  documents, not from other documents in the KB.
   3. Get the answer and chuck image(generally part of scanned pdf file)
```

### Describe the feature you'd like

The user case is like: 
  A patient upload a health check report, and ask LLM to retrived the value of parameter from *his* report, not from others.  so only answers from specified documents  make sense. 

### Describe implementation you've considered

provide API to :
1.  specify document ID for chatting 
2. or create/delete knowledge base

**Comment by JinHai-CN** [comment]
Fixed
