### ISSUE TITLE
[Feature Request]: Introduce OpenAI's 'text-embedding-3-small' and 'text-embedding-3-large' as OpenAI embedding models

### ISSUE THREAD

**Issue by ghosthunterk** [infiniflow/ragflow#810]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Introduce OpenAI's 'text-embedding-3-small' and 'text-embedding-3-large' as OpenAI embedding models for their better performance, lower price and especially adaptability in multilingual scenarios

**Comment by KevinHuSh** [comment]
It will upgrade in docker image of dev version and online demo.
