### ISSUE TITLE
[Question]: How to improve parsing and chating speed?

### ISSUE THREAD

**Issue by wjjf** [infiniflow/ragflow#814]
**[Question]:** 您好，我在服务器上部署了一套，使用的是千问大模型，服务器16+200G。现在的问题是解析文档有时候会卡住，提问的话如果有答案通常是20s起步。我想知道我需要调整哪方面的参数能优化这一问题？我的性能瓶颈在哪里？

**Comment by wjjf** [comment]
[Question]: 首先感谢贡献如此优秀开源项目！我在服务器上部署了一套，使用的是千问大模型，服务器16+200G。现在的问题是解析文档有时候会卡住，提问的话如果有答案通常是20s起步。请问我需要做哪些优化？我的性能瓶颈在哪里

**Comment by wjjf** [comment]
Test

**Comment by KevinHuSh** [comment]
-- We use visual model to parsing PDF, so it's slow. We're working on its speed. You can disable layout recognition for PDF in general parsing method. And this can be configured later in knowledgebase configuration.

-- About the chatting speed, we're gona use streamly chat which will bring speedy chating user experience. Today, it's gona release in docker images of dev version.

-- I'm not sure what the 16 refer to. If it's 16GB memory,  I'm afraid it's not enough. 32GB will be better.

![image](https://github.com/infiniflow/ragflow/assets/12318111/cfa1e9e4-cfef-42a9-bfb7-eb17e871f206)

**Comment by wjjf** [comment]
Thanks！

**Comment by wjjf** [comment]
Now I'm using a machine with 32GB of RAM, but the answer speed is still twenty or thirty seconds, what parameters should I adjust to improve it?

**Comment by qiqi0308** [comment]
> 谢谢！



> 谢谢！

请问您解决了么，我也有同样的问题
