### ISSUE TITLE
[Bug]: Failed to build docker image

### ISSUE THREAD

**Issue by shaoyie** [infiniflow/ragflow#828]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

081f922ee61334f2f6895b01d3ed3ff5d3252b8e

### Actual behavior

![image](https://github.com/infiniflow/ragflow/assets/35255629/2e7a01ec-f8ef-4539-bb1e-ce8ad07f4f86)
Build docker failed with the error below:

 => ERROR [internal] load metadata for docker.io/infiniflow/ragflow-base:v2.0                                                                           2.6s
------
 > [internal] load metadata for docker.io/infiniflow/ragflow-base:v2.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/infiniflow/ragflow-base:v2.0: not found

Is there any spelling error the docker image name?

### Expected behavior

Can build docker image successfully

### Steps to reproduce

```Markdown
Download the latest code and try 
docker build -t ragflow/ragflow:dev .
```

**Comment by Alchemistqqqq** [comment]
![image](https://github.com/infiniflow/ragflow/assets/146717415/ec51490b-2b23-4730-b47e-5a9192ac93fe)
Although the error message is different, but the same command error.

**Comment by Domi31tls** [comment]
I have the same error. I checked, and the version infiniflow/ragflow-base:v2.0 does not exist in the repository. I tried modifying the Dockerfile without success.

**Comment by KevinHuSh** [comment]
Fixed. Pull the image infiniflow/ragflow-base:v2.0
