### ISSUE TITLE
This folder cannot be deleted

### ISSUE THREAD

**Issue by liukx362330** [infiniflow/ragflow#833]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

mian

### Commit ID

081f925

### Actual behavior

Knowledge Library files deleted, but file management files are still there, I even preview through file management.

### Expected behavior

Knowledge Library files deleted, but file management files are still there, I even preview through file management.

### Steps to reproduce

```Markdown
1. Delete files in the knowledge base. 2. Check that files are still in file management and are not deleted.
```

**Comment by KevinHuSh** [comment]
If the files uploaded in file manager, they're can't be removed in knowledge base.
