### ISSUE TITLE
[Bug]: Knowledge base not referred to when using local Ollama

### ISSUE THREAD

**Issue by teohhc** [infiniflow/ragflow#834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

673a28e

### Other environment information

```Markdown
vendor_id	: GenuineIntel
cpu family	: 6
model		: 191
model name	: 13th Gen Intel(R) Core(TM) i5-13400F
16GB RAM

Graphics
--------
NVIDIA-SMI 550.67                 
Driver Version: 550.67         
CUDA Version: 12.4
8GB RAM

OS
--
Arch Linux 6.8.5-arch1-1
x86_64
```

### Actual behavior

Ran 2 ollama, one for the embedding (port 11435) and the other for chat (port 11434).
![Screenshot from 2024-05-19 14-25-21](https://github.com/infiniflow/ragflow/assets/7022124/603cd655-dc26-4ecc-9325-7894de9fff2e)

My environment setup
![Screenshot from 2024-05-19 14-30-07](https://github.com/infiniflow/ragflow/assets/7022124/601ed851-7991-46b1-9d2d-b36b2398c88e)

**Testing Steps:**
1. Ollama models configured without problems
![Screenshot from 2024-05-19 14-33-46](https://github.com/infiniflow/ragflow/assets/7022124/63386f30-2e97-48f6-882c-47c66cefbec3)

2. Change the system model settings
![Screenshot from 2024-05-19 14-50-30](https://github.com/infiniflow/ragflow/assets/7022124/5a095215-148e-4591-b321-b854a8853e98)

3. Knowledge base created
![Screenshot from 2024-05-19 14-32-49](https://github.com/infiniflow/ragflow/assets/7022124/63a66b7e-a742-4bec-ad71-ead6a6ce5aa1)

4. Retrieval testing without problems
![Screenshot from 2024-05-19 14-35-38](https://github.com/infiniflow/ragflow/assets/7022124/327e5c34-e7d8-460d-a6ea-45c6e06181c9)

5. Chat configuration
![Screenshot from 2024-05-19 14-38-44](https://github.com/infiniflow/ragflow/assets/7022124/989a96b6-9531-4c91-aa75-ef57ebc71818)
![Screenshot from 2024-05-19 14-40-23](https://github.com/infiniflow/ragflow/assets/7022124/06c67807-6167-412e-97df-1fa1cb03e15b)
![Screenshot from 2024-05-19 14-40-44](https://github.com/infiniflow/ragflow/assets/7022124/ee9d5cc0-ada5-451b-8ba8-ca1baa31cfda)

6. Chat fails to retrieve from knowledge base
![Screenshot from 2024-05-19 14-41-56](https://github.com/infiniflow/ragflow/assets/7022124/2e19e903-f523-440f-985b-1a62427e1ea7)

Checked the ragflow-logs/api/*.log but can't find any useful hints

### Expected behavior

It should refer to the knowledge base for answers similar to the retrieval testing.

### Steps to reproduce

```Markdown
I've added phpmyadmin just to check the database.
1. docker-compose up -d ragflow-mysql ragflow-redis ragflow-phpmyadmin ragflow-es-01 minio
2. docker-compose up -d ragflow
3. Refer to https://hub.docker.com/r/ollama/ollama to run both ollama on different ports, llama3 on 11434 and nomic-embed-text (11435)
4. Follow "Testing Steps" give in the "Actual behavior" section
```

### Additional information

Elastic search is still alive and healthy. There is remaining 1GB of free memory left. Both Ollamas didn't report any errors. Retried by clearing docker volumes and recreating the containers and making sure all other services are running first before starting ragflow main service.

**Comment by fangxingSR** [comment]
The same experience

**Comment by DillionApple** [comment]
+1

**Comment by XiaoCC** [comment]
xinference  +1

**Comment by guoyuhao2330** [comment]
> ### 同一错误是否存在现有问题？
> * [x] 我已经检查了现有问题。
> 
> ### 分行名称
> 主要
> 
> ### 提交 ID
> [673A28E](https://github.com/infiniflow/ragflow/commit/673a28e4927a8970a0c97f0916e1256fdc65b1b8)
> 
> ### 其他环境信息
> ```
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 191
> model name	: 13th Gen Intel(R) Core(TM) i5-13400F
> 16GB RAM
> 
> Graphics
> --------
> NVIDIA-SMI 550.67                 
> Driver Version: 550.67         
> CUDA Version: 12.4
> 8GB RAM
> 
> OS
> --
> Arch Linux 6.8.5-arch1-1
> x86_64
> ```
> 
> ### 实际行为
> 运行了 2 个 ollama，一个用于嵌入（端口 11435），另一个用于聊天（端口 11434）。 ![Screenshot from 2024-05-19 14-25-21](https://private-user-images.githubusercontent.com/7022124/331851903-603cd655-dc26-4ecc-9325-7894de9fff2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MTkwMy02MDNjZDY1NS1kYzI2LTRlY2MtOTMyNS03ODk0ZGU5ZmZmMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2MwNjM3MDU3MmY1MWUxOGJmNTVlMGIwNWMxODQyN2RjN2RjZjZjZGIzODM1YzE0ZDkyYzJkNDA0MzFmZjFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WF3ZW0SvF4u0NA8aO9BfTY-n-_8RnPTIRAKYpxqx6rc)
> 
> 我的环境设置 ![Screenshot from 2024-05-19 14-30-07](https://private-user-images.githubusercontent.com/7022124/331852061-601ed851-7991-46b1-9d2d-b36b2398c88e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjA2MS02MDFlZDg1MS03OTkxLTQ2YjEtOWQyZC1iMzZiMjM5OGM4OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFmYzMyZGFhZGE2NTc0OTNkOWRlMDAxNmNhYTc5ZWU5MTI1NmYxNDdhZWNiNjU5NWZhZjBiOWI4NjQ1YjZlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HzfLRWCYpxEZg8vaQS7SAzb2tFf_i4rxyntiRtPYTzc)
> 
> **测试步骤：**
> 
> 1. Ollama 模型配置没有问题
>    ![Screenshot from 2024-05-19 14-33-46](https://private-user-images.githubusercontent.com/7022124/331852210-63386f30-2e97-48f6-882c-47c66cefbec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjIxMC02MzM4NmYzMC0yZTk3LTQ4ZjYtODgyYy00N2M2NmNlZmJlYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FkNjEyNGExODU0Nzg1MTMyMGU0ZmQ0YjNhOTY5NjJmMzhkODY3ZTRjZjBmNTVjYTRlYTY0MWFmYzM0ZjM4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u_7t-3SvtQF0YtdUzDGHNwjzvPrBTVj5psAa6VnU7Rs)
> 2. Change the system model settings
>    ![Screenshot from 2024-05-19 14-50-30](https://private-user-images.githubusercontent.com/7022124/331853004-5a095215-148e-4591-b321-b854a8853e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MzAwNC01YTA5NTIxNS0xNDhlLTQ1OTEtYjMyMS1iODU0YTg4NTNlOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY1YTJlMDQ0MTBhYWRlZTk3N2UxZTY2YmE3MDE3NWE2ZmZkNzRkZTM4ZTAxNzQxMzQ4Yjc0MmY2ZWM3YWVhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4LTPjLc-xkM9LkLI5LCH1-0f0v-HkL7EKkNttEwTYUE)
> 3. Knowledge base created
>    ![Screenshot from 2024-05-19 14-32-49](https://private-user-images.githubusercontent.com/7022124/331852153-63a66b7e-a742-4bec-ad71-ead6a6ce5aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjE1My02M2E2NmI3ZS1hNzQyLTRiZWMtYWQ3MS1lYWQ2YTZjZTVhYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ5ZGI0ZDBlZjE5YWExYjA2Y2JiOWQxMjUxNDMyOTRhMTkwYmFmZmUxYjkzZGVkNWVhNzYzNjI5YmFkYWU4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8VIb-CBZjuJCehK7Wxzl-bDHZCozglN1oJKl8jhjLdg)
> 4. Retrieval testing without problems
>    ![Screenshot from 2024-05-19 14-35-38](https://private-user-images.githubusercontent.com/7022124/331852283-327e5c34-e7d8-460d-a6ea-45c6e06181c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjI4My0zMjdlNWMzNC1lN2Q4LTQ2MGQtYTZlYS00NWM2ZTA2MTgxYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlZTFiYmQ2M2U1OTZkMjM5ZWVmMDMyOWM3YTE3YTlmODdjOWZlNDgwNzljYjIzYTYwYjRiYTNmYjE5ZGQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4zBwIlOP7rPqmg8UJb473SiB9gKie4s3xCO-1m2dOdY)
> 5. Chat configuration
>    ![Screenshot from 2024-05-19 14-38-44](https://private-user-images.githubusercontent.com/7022124/331852450-989a96b6-9531-4c91-aa75-ef57ebc71818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjQ1MC05ODlhOTZiNi05NTMxLTRjOTEtYWE3NS1lZjU3ZWJjNzE4MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJiYmNhY2MxZmRiOWRiNTJmNDk4ZGRiMGUzZmVkOGRjYmJkYTkyMGMyNWE0OTVmNGQ1YzM0ZTczNWYxNzhhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qv3ct7E7Ejhi18hnPxCtJ-WkMFzoMuuj5EIU5cuxLAg)
>    ![Screenshot from 2024-05-19 14-40-23](https://private-user-images.githubusercontent.com/7022124/331852504-06c67807-6167-412e-97df-1fa1cb03e15b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjUwNC0wNmM2NzgwNy02MTY3LTQxMmUtOTdkZi0xZmExY2IwM2UxNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTcyMjBmMmEyOWNlOTBhZDZjYjg4MGMyMGVmZWE2YzRhYjZhZTM0OWEwNWM0YzgyNmM1NDkyMGJhMDM1MTUyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4gOWhHhIpN5n56NQrIRfEbO0KbxKP6IJaDT2QTJvCUQ)
>    ![Screenshot from 2024-05-19 14-40-44](https://private-user-images.githubusercontent.com/7022124/331852525-ee9d5cc0-ada5-451b-8ba8-ca1baa31cfda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjUyNS1lZTlkNWNjMC1hZGE1LTQ1MWItOGJhOC1jYTFiYWEzMWNmZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQxOGRmOTM4YWU4NjM1ODIwMGQ5ZjM0MzZjYjcyNDdmYzY2YmM1YmNmYWU5ZGVlMjU3M2UzZGIzNzU3ZTY1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eGMpdFfVvTvfFZgeOlbuD0fvwWp9cMxbIpKFUqXFwJQ)
> 6. Chat fails to retrieve from knowledge base
>    ![Screenshot from 2024-05-19 14-41-56](https://private-user-images.githubusercontent.com/7022124/331852613-2e19e903-f523-440f-985b-1a62427e1ea7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk4MDEsIm5iZiI6MTcxNjE3OTUwMSwicGF0aCI6Ii83MDIyMTI0LzMzMTg1MjYxMy0yZTE5ZTkwMy1mNTIzLTQ0MGYtOTg1Yi0xYTYyNDI3ZTFlYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDQzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVhYTEwN2Q0OWZlNDc0ZTBjNzI5ZGRjNDdkYTgwMjhlNzczYTc1YWVjYTkzZGRjYzMyMDIwYjBiMzk5YmNkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9rnO8BvfFZRBSD_KVRBNqRHXRawDoJRKoNHHrtlk_Jg)
> 
> Checked the ragflow-logs/api/*.log but can't find any useful hints
> 
> ### Expected behavior
> It should refer to the knowledge base for answers similar to the retrieval testing.
> 
> ### Steps to reproduce
> ```
> I've added phpmyadmin just to check the database.
> 1. docker-compose up -d ragflow-mysql ragflow-redis ragflow-phpmyadmin ragflow-es-01 minio
> 2. docker-compose up -d ragflow
> 3. Refer to https://hub.docker.com/r/ollama/ollama to run both ollama on different ports, llama3 on 11434 and nomic-embed-text (11435)
> 4. Follow "Testing Steps" give in the "Actual behavior" section
> ```
> 
> ### Additional information
> Elastic search is still alive and healthy. There is remaining 1GB of free memory left. Both Ollamas didn't report any errors. Retried by clearing docker volumes and recreating the containers and making sure all other services are running first before starting ragflow main service.

Bug is fixed，please upgrade the dev version.
