### ISSUE TITLE
[Feature Request]: Does it support non-docker ARM architecture deployment? Or the future

### ISSUE THREAD

**Issue by ticang** [infiniflow/ragflow#842]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Does it support non-docker ARM architecture deployment? Or the future

**Comment by KevinHuSh** [comment]
We didn't try it on the machine of ARM  since we didn't have one.
You can refer to Dockerfile.scratch which includes all the essential steps to install RAGFlow.

**Comment by JinHai-CN** [comment]
#936
