### ISSUE TITLE
[Question]: Streaming reesponse it not working

### ISSUE THREAD

**Issue by maxisvest** [infiniflow/ragflow#857]
### Describe your problem

I have upgrade to v0.6.0, but stream response is not working, It is stuck on 'seaching'， when completion api return, the response appear suddenly. I have check the competion api, it works fine, and I also check the console output, It has a warning log which I suspect the cause.

llm model is zhipu gm-4

completion api output
![image](https://github.com/infiniflow/ragflow/assets/20422618/e7c5f2a4-7fea-4be9-ac39-7f81750e6a86)

chrome console output
![image](https://github.com/infiniflow/ragflow/assets/20422618/264f0f8b-74cb-416e-ba24-9676d247ffae)

**Comment by KevinHuSh** [comment]
It might related to your local WAN envirement.

**Comment by maxisvest** [comment]
> It might related to your local WAN envirement.

I have solve this problem, turn off the nginx config `proxy_buffering`, thx.
