### ISSUE TITLE
How to deploy based on kubernetes？

### ISSUE THREAD

**Issue by tuninger** [infiniflow/ragflow#864]
### Describe your problem

How to deploy based on kubernetes? What I mean is that ragflow is currently supported to be deployed through docker-compose. When will it be supported to deploy ragflow through helm charts or yaml files?

**Comment by Kraego** [comment]
kustomize would be nice too

**Comment by janineguo** [comment]
@KevinHuSh Are there any updates on this feature? I have converted all the Docker Compose files to YAML format. If this feature is still being addressed, I can take care of this task and use Helm to make it easier to install on Kubernetes.

**Comment by steffenboe** [comment]
@janineguo maybe submit a PR for this? would love to have this as well!

**Comment by KevinHuSh** [comment]
Not any updates yet.

**Comment by nakroy** [comment]
> Not any updates yet.

I'm working on creating a helm chart for RAGFlow. I have some questions about the version of dependencies, like MySQL, redis, MinIO and so on. Whether there's a specific version of these dependencies? Or just using the latest version is OK?

**Comment by danialkhatib** [comment]
> > Not any updates yet.
> 
> I'm working on creating a helm chart for RAGFlow. I have some questions about the version of dependencies, like MySQL, redis, MinIO and so on. Whether there's a specific version of these dependencies? Or just using the latest version is OK?

would be nice 👌

**Comment by ayushin** [comment]
It would help to have a docker-compose / containers that run a single process /service per container i.e. server, task manager etc instead of all of them together. Once that is done a helm chart can be generated by claude.ai in minutes.

I think having services segregated in the main repo docker-compose would really help to maintain integrity.

**Comment by yuzhichang** [comment]
@nakroy docker-compose.yml records the version of dependencies(MySQL, redis, MinIO, ElasticSearch)

**Comment by nakroy** [comment]
> @nakroy docker-compose.yml records the version of dependencies(MySQL, redis, MinIO, ElasticSearch)

I get it. Last two weeks I use deployments yaml files to deploy RAGFlow and it works. One little problem would be the `service_conf.yaml`, it needs to be dynamic created in kubernetes environment because the `host` of these services are used with   kubernetes service domains

**Comment by s-khaon** [comment]
I'll provide you with an idea. Use the 'docker compose config' command to export the configuration to a file, and then use the 'kompose convert -f file -o path' command to get the desired deployment, daemonset, service, and pvc. If needed, I can provide a PR after adjusting the Values ​​file.

**Comment by zengqingfu1442** [comment]
m
