### ISSUE TITLE
[Bug]: python dependency conflict occurs when I select Launch service from source

### ISSUE THREAD

**Issue by 0sengseng0** [infiniflow/ragflow#875]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest

### Other environment information

```Markdown
CentOS Linux release 7.9.2009 (Core)
Linux main 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Actual behavior

when i :
pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 21.11 Requires-Python >=3.5,<3.10; 22.1 Requires-Python >=3.5,<3.10; 22.10.0 Requires-Python >=3.5,<3.11; 22.11.0 Requires-Python >=3.5,<3.11; 22.12.0 Requires-Python >=3.5,<3.11; 22.4.0 Requires-Python >=3.5,<3.10; 22.6.0 Requires-Python >=3.5,<3.11; 22.7.0 Requires-Python >=3.5,<3.11; 22.8.0 Requires-Python >=3.5,<3.11; 22.9.0 Requires-Python >=3.5,<3.11; 23.1.0 Requires-Python >=3.5,<3.11; 23.2.0 Requires-Python >=3.5,<3.11; 23.3.0 Requires-Python >=3.5,<3.11; 23.4.0 Requires-Python >=3.5,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.17.1 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime-gpu==1.17.1

### Expected behavior

python dependencies will install normally

### Steps to reproduce

```Markdown
conda create -n ragflow python=3.11.0
conda activate ragflow
pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
```

### Additional information

I started with the default pip source, but there were dependency conflicts. I then tried python3.10 and python3.9 but both had similar dependency conflict issues. In the end, I chose a different pip source, still had dependency conflicts,

**Comment by KevinHuSh** [comment]
Comment out the uninstallable package in requirements.txt.

**Comment by skytodmoon** [comment]
I met the same problem

**Comment by skytodmoon** [comment]
> Comment out the uninstallable package in requirements.txt.

How can I solve the problem, comment out what?
