### ISSUE TITLE
[Bug]: encountered a timeout error when I run "docker logs -f ragflow-server"

### ISSUE THREAD

**Issue by liwan14x** [infiniflow/ragflow#879]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

21453ff

### Actual behavior

I encountered an time out error when run "docker logs -f ragflow-server" 

### Steps to reproduce

```Markdown
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 26, in <module>
    from api.db.db_models import close_connection
  File "/ragflow/api/db/db_models.py", line 32, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 35, in <module>
    from rag.utils.es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 59, in <module>
    encoder = tiktoken.encoding_for_model("gpt-3.5-turbo")
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/model.py", line 101, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/lib/python3.10/dist-packages/tiktoken_ext/openai_public.py", line 72, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/load.py", line 147, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file, expected_hash)
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/load.py", line 64, in read_file_cached
    contents = read_file(blobpath)
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/load.py", line 25, in read_file
    resp = requests.get(blobpath)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe06676baf0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by ye-jeck** [comment]
Are you accessing the internal network

**Comment by liwan14x** [comment]
> Are you accessing the internal network
I can access the external network through a proxy, and I have configured a proxy for the system

error log: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1c5df17a60>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

I tried to use wget command to connect to a website that failed the request, and I was able to download this on my machine.

>>>>> wget https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
正在解析主机***
正在连接 ***已连接。
已发出 Proxy 请求，正在等待回应... 200 OK
长度：1681126 (1.6M) [application/octet-stream]
正在保存至: “cl100k_base.tiktoken”

100%[========================================================================================================>] 1,681,126    223KB/s 用时 6.8s

2024-05-23 09:37:27 (241 KB/s) - 已保存 “cl100k_base.tiktoken” [1681126/1681126])

**Comment by liwan14x** [comment]
issue has been resolved, need to add proxy to the docker yml file.
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://hf-mirror.com
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=

**Comment by wuangqshd** [comment]
> > Are you accessing the internal network
> > I can access the external network through a proxy, and I have configured a proxy for the system
> 
> error log: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1c5df17a60>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
> 
> I tried to use wget command to connect to a website that failed the request, and I was able to download this on my machine.
> 
> > > > > > wget https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
> > > > > > 正在解析主机***
> > > > > > 正在连接 ***已连接。
> > > > > > 已发出 Proxy 请求，正在等待回应... 200 OK
> > > > > > 长度：1681126 (1.6M) [application/octet-stream]
> > > > > > 正在保存至: “cl100k_base.tiktoken”
> 
> 100%[========================================================================================================>] 1,681,126 223KB/s 用时 6.8s
> 
> 2024-05-23 09:37:27 (241 KB/s) - 已保存 “cl100k_base.tiktoken” [1681126/1681126])

So,Where should I put the downloaded files?

**Comment by sixgod-666** [comment]
> > > Are you accessing the internal network
> > > I can access the external network through a proxy, and I have configured a proxy for the system
> > 
> > 
> > error log: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1c5df17a60>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
> > I tried to use wget command to connect to a website that failed the request, and I was able to download this on my machine.
> > > > > > > wget https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
> > > > > > > 正在解析主机***
> > > > > > > 正在连接 ***已连接。
> > > > > > > 已发出 Proxy 请求，正在等待回应... 200 OK
> > > > > > > 长度：1681126 (1.6M) [application/octet-stream]
> > > > > > > 正在保存至: “cl100k_base.tiktoken”
> > 
> > 
> > 100%[========================================================================================================>] 1,681,126 223KB/s 用时 6.8s
> > 2024-05-23 09:37:27 (241 KB/s) - 已保存 “cl100k_base.tiktoken” [1681126/1681126])
> 
> So,Where should I put the downloaded files?

hello,do you know where now?

**Comment by codingstube** [comment]
I also tried to run behind a proxy. I dont know why but in the entrypoint.sh the proxy server will set to null.
I comment it out and it works.

#!/bin/bash

# unset http proxy which maybe set by docker daemon
export http_proxy=""; export https_proxy=""; export no_proxy=""; export HTTP_PROXY=""; export HTTPS_PROXY=""; export NO_PROXY=""

**Comment by tangfei** [comment]
下载cl100k_base.tiktoken重命名为9b5ad71b2ce5302211f9c61530b329a4922fc6a4 放在/tmp/data-gym-cache 下面，把代码中的

# encoder = tiktoken.encoding_for_model("gpt-3.5-turbo")

encoder = tiktoken.get_encoding("cl100k_base")

就可以在本地使用了
