### ISSUE TITLE
[Question]: For the content length reason,it stopped, continue.

### ISSUE THREAD

**Issue by luchenwei9266** [infiniflow/ragflow#889]
### Describe your problem

When I use the API, due to the excessive length of the text, the response in ```data.answer``` always includes the message ```For the content length reason, it stopped, continue.``` Is there a way to adjust this length limit and make it longer?

**Comment by Flyingdusk** [comment]
same question ,how to extent the length or continue...?

**Comment by luchenwei9266** [comment]
> same question ,how to extent the length or continue...?

![image](https://github.com/infiniflow/ragflow/assets/9455826/799a02ff-352c-4559-a50d-dde098a46fe8)

Set Max Tokens
