### ISSUE TITLE
[Question]: Help me ! The chat does not have access to the knowledge base !

### ISSUE THREAD

**Issue by Domi31tls** [infiniflow/ragflow#890]
### Describe your problem

Hello, I am using Ollama with Albert (I have tried with Llama2, Mixtral, etc.). In the chat, when I ask a question, I get the response that it does not have access to the knowledge base and still gives me a reference document, which is always the same. The prompt engine is correct, it is well-written. I am asking it to use the {knowledge} variable. Has anyone experienced this type of problem?

**Comment by KevinHuSh** [comment]
The LLM discovers that there's no relevance between question and the retrieved reference documents, then give "Unable to answer" sort of response. 
The RAGFlow temporary has no method to judge this kind of relevance until it has FLOW which will happpened in the near future version.

**Comment by Domi31tls** [comment]
Thank you for your response, but I don't think that's the issue. Indeed, when I ask what the document is about, or ask for a summary, or inquire about the software's features, I always get the same response: "I don't know".

[Heyhack Recon.pdf](https://github.com/infiniflow/ragflow/files/15415969/Heyhack.Recon.pdf)
