### ISSUE TITLE
[Question]: dependency failed to start: container ragflow-mysql is unhealthy

### ISSUE THREAD

**Issue by caixiongjiang** [infiniflow/ragflow#892]
### Describe your problem

MAC OS：

docker build log：
```shell
docker compose up -d
```
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string. 
[+] Running 4/4
 ✔ Container ragflow-redis  Running                                                                                         0.0s 
 ✔ Container ragflow-minio  Running                                                                                         0.0s 
 ✔ Container ragflow-es-01  Healthy                                                                                         0.5s 
 ✘ Container ragflow-mysql  Error                                                                                           0.5s 
dependency failed to start: container ragflow-mysql is unhealthy

**Comment by KevinHuSh** [comment]
Change mysql to mariadb in docker-compose-base.yml.
