### ISSUE TITLE
[Bug]: redis status is red when first launch ragflow

### ISSUE THREAD

**Issue by CamusGao** [infiniflow/ragflow#893]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

6c32f80bc91715319e9946cef8bc275d18f446b9

### Actual behavior

Redis queue `rag_flow_svr_queue` have not be created when no task have been launched. so the redis status is red.

### Steps to reproduce

```Markdown
1. setup new ragflow env.
2. go to /user-setting/system and see redis status.
```

**Comment by KevinHuSh** [comment]
We've fixed this in the dev version.
