### ISSUE TITLE
[Question]: The knowledge base file recognition effect on the demo website doesn't matched with open source version.

### ISSUE THREAD

**Issue by stefiane** [infiniflow/ragflow#895]
### Describe your problem

本地部署的RAGFlow的知识库文档icr识别效果与demo官网不一致，同一个文件同样的知识库设置，解析出来的chunk数量不一致为什么？demo官网用的模型是闭源的嘛？
![image](https://github.com/infiniflow/ragflow/assets/23471111/6213a919-e6a1-4a32-b216-02e7d2298943)
![image](https://github.com/infiniflow/ragflow/assets/23471111/71b8360a-0eb0-4630-95c6-84be241086e2)

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for the issue, thank you.

For your question, the model of the online demo is slightly different from the open source version.

**Comment by stefiane** [comment]
> We intend to create an international community, so we encourage using English for the issue, thank you.
> 
> For your question, the model of the online demo is slightly different from the open source version.

Do we have a plan to open source this model? for free or for charge?

**Comment by JinHai-CN** [comment]
> > We intend to create an international community, so we encourage using English for the issue, thank you.
> > 
> > For your question, the model of the online demo is slightly different from the open source version.
> 
> Do we have a plan to open source this model? for free or for charge? @JinHai-CN 

Yes, we might open source the model, but not now.
