### ISSUE TITLE
[Question]: docker compose up -d failed

### ISSUE THREAD

**Issue by Alchemistqqqq** [infiniflow/ragflow#898]
### Describe your problem

I'm sorry to bring this up again, but after many, long attempts, I still face the same problem. First I try to start the server as follows
![image](https://github.com/infiniflow/ragflow/assets/146717415/835a70ff-50c4-4e04-98a0-954bd02ad7b7)
But I tried many times and still got the same result
![image](https://github.com/infiniflow/ragflow/assets/146717415/41f319f5-bd8a-4a00-815a-2614e281158b)
Next I build from the source code
![image](https://github.com/infiniflow/ragflow/assets/146717415/da7f2fc1-e575-4e83-b35c-187653b778e8)
Since I am in China, I chose the CN.yml file. ragflow successfully pulled the file after many attempts, and the speed was relatively fast, but minio and redis were slow in pulling and often failed after one hour, as shown in the figure
![image](https://github.com/infiniflow/ragflow/assets/146717415/3c54940a-e220-429b-9ef4-d65ab9687846)
The network I am in is a campus network with no VPN, but the docker source is set up with multiple domestic sources. Is there anything else I can try? Or is the problem just my network? Thank you

**Comment by KevinHuSh** [comment]
Modify docker-compose-base.yaml.
Change the image address to domestic docker hub that you can reach.

**Comment by Alchemistqqqq** [comment]
> Modify docker-compose-base.yaml. Change the image address to domestic docker hub that you can reach.

I try to compose after modifying the docker source. ragflow is now complete, but the progress bar of minio doesn't make any progress (try many times), so I try to modify the image of minio. From the quay. IO/minio minio: RELEASE. The 2023-12-20 T01-00-02 z, with minio/minio, but I don't know whether this is reasonable. After modification, the compose operation is completed, and the terminal output is shown as below.
![image](https://github.com/infiniflow/ragflow/assets/146717415/31778355-9b2d-46da-ad1f-408fe12f230a)
![image](https://github.com/infiniflow/ragflow/assets/146717415/904018c6-4c5e-4cec-ba24-bc8496726b29)
This is not the same as when I was successful before. Do you know where I went wrong? The page on port 80 also failed to load.
