### ISSUE TITLE
[Bug]: The size of PDF chunks is not limited, which can lead to extremely large chunks that exceed the limitations of the LLM in extreme cases.

### ISSUE THREAD

**Issue by chinamerp** [infiniflow/ragflow#907]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

4cda40c

### Actual behavior

chunk limited to 256

### Steps to reproduce

```Markdown
upload and parse a pdf with tabl and picture.
```

**Comment by KevinHuSh** [comment]
What is the chunking method you refer to?
If you're not using 'One', you can control chunk size limitation by task page size here:
![image](https://github.com/infiniflow/ragflow/assets/12318111/5c8d863b-afbc-440f-8bbe-c0b7c5e850b5)

It limits the page size  for one task.

**Comment by chinamerp** [comment]
A PDF file is parsed and splited to chunks, each chunk's size should be limited.

**Comment by KevinHuSh** [comment]
> A PDF file is parsed and splited to chunks, each chunk's size should be limited.

I see and agree.

**Comment by yuzhichang** [comment]
Each chunk of a pdf is limited to 12 pages by default.
