### ISSUE TITLE
[Question]: Different results from local ollama console output and RAG integration

### ISSUE THREAD

**Issue by teldredge** [infiniflow/ragflow#910]
### Describe your problem

I was able to follow this guide to connect RAGflow to a local ollama docker instance.
https://github.com/infiniflow/ragflow/blob/main/docs/guides/deploy_local_llm.md

I have a small (one pdf) knowledgebase and created an assistant for it just for basic testing.

If I start a console on the ollama instance and ask "What is 1+1?" I get a correct response "The sum of 1 and 1 is 2".

But when I ask the same question of the RAGflow assistant using the ollama LLM it gives me the 'empty response' if I have one set, but if I don't it searches forever and never gives a response.

What logs can I check to see what's going on behind the curtain?

**Comment by KevinHuSh** [comment]
To accomplish this, following the steps:
- Set the empty response blank in dialog setting.
- Modify the prompt: If there's no relevent information in the following, please give a correct answer with your own knowledge.
