### ISSUE TITLE
[Question]: since no redis connection.

### ISSUE THREAD

**Issue by gongxiansen** [infiniflow/ragflow#911]
### Describe your problem

ragflow-server  | [WARNING] [2024-05-24 03:43:16,082] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
ragflow-server  | [WARNING] [2024-05-24 03:43:16,301] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
ragflow-server  | [WARNING] Load term.freq FAIL!
ragflow-server  | 
ragflow-server  |     ____                 ______ __               
ragflow-server  |    / __ \ ____ _ ____ _ / ____// /____  _      __
ragflow-server  |   / /_/ // __ `// __ `// /_   / // __ \| | /| / /
ragflow-server  |  / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
ragflow-server  | /_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
ragflow-server  |               /____/                             
ragflow-server  | 
ragflow-server  |     
ragflow-server  | Cannot assign requested address
ragflow-server  | Start to insert 2 OpenAI embedding models...
ragflow-server  | init web data success:0.012183904647827148

**Comment by BFlameSwift** [comment]
same question !

**Comment by KevinHuSh** [comment]
Ignore the warning logs.
