### ISSUE TITLE
[Question]: No raptor switch in v0.6.0 or dev image but in the demo website.

### ISSUE THREAD

**Issue by cauwulixuan** [infiniflow/ragflow#913]
### Describe your problem

Thanks for your work.

It's strange that I can see `raptor` configs in the demo site, but when I setup my local environment by docker-compose with image v0.6.0 or dev, I cannot see the raptor switch.

As we can see, the onnx models in your demo website are much better than the open-source models. Now I see the UI/config is a little bit different. 

My questions is, can you point out what kind of images do you use or anything else you use in the demo website is different from the open-source one?

**Comment by JinHai-CN** [comment]
RAPTOR config should be in DEV docker image.

**Comment by KevinHuSh** [comment]
v0.6.0 doesn't have RAPTOR which dev version of image has.
 Modify the RAGFLOW_VERSION in docker/.env to dev.

**Comment by cauwulixuan** [comment]
Thanks. I pull dev image 2 days ago, and no raptor in it. you mean I need pull it again?
