### ISSUE TITLE
[Bug]: variational max_token when using local deployed model with xinference 

### ISSUE THREAD

**Issue by lawsonX** [infiniflow/ragflow#914]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

6c32f80

### Other environment information

```Markdown
Ubuntu 22.04.1
RTX 4090 * 4 
CUDA:12.4
xinference=0.11.0; vllm=0.4.2 , 
model=qwen1.5 series or yi-chat series
```

### Actual behavior

使用本地llm(qwen1.5, yi-chat) + xinference 作为后端模型服务，ragflow助手回答会出现”中断“的情况，多发于：1.参考文块较多 2.连续对话。
![20240524-145315](https://github.com/infiniflow/ragflow/assets/76583362/d5f2cb31-1eaf-48d1-92aa-6da13cbb8d73)
我检查了xinference的后台日志，发现每次调用xinference模型服务时，sampling_params中的 max_token 参数的值会变化，而非ragflow前端 模型设置里 ”最大token数“ 设置的值。也就是说”最大token数“设置的值并没有成功且持续不变的传入 xinference的API参数里。
![xinf_log_example](https://github.com/infiniflow/ragflow/assets/76583362/9f9f316d-97cd-4e41-9c58-80791126743e)

### Expected behavior

ragflow前端模型设置里 ”最大token数“ 设置的值 应该成功且不变的传入xinference 对话参数中的 max_token

### Steps to reproduce

```Markdown
ragflow v0.6.0 and lower
create a knowledge base arbitrarily and use it to chat arbitrarily with multi rounds, should reproduce the problem.
```

**Comment by KevinHuSh** [comment]
It will be fixed.

**Comment by KevinHuSh** [comment]
XInference applys OpenAI API to call completion. So, is it possible the max_token showing in the log is different from the max_token UI submit to in term of meaning.
