### ISSUE TITLE
[Bug]: elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f6e658f7c50>: Failed to resolve 'es01' ([Errno -2] Name or service not known)).

### ISSUE THREAD

**Issue by waylonli** [infiniflow/ragflow#920]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Other environment information

```Markdown
Windows wsl2
```

### Actual behavior

I followed the instructions of "Launch service from source", but when I run `bash ./entrypoint.sh`, it occurs the error elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f6e658f7c50>: Failed to resolve 'es01' ([Errno -2] Name or service not known)).

However I check `docker ps` and I can see ragflow-es-01 is there, also running `curl http://localhost:1200` gives me the following:
curl http://localhost:1200/
{
  "name" : "es01",
  "cluster_name" : "rag_flow",
  "cluster_uuid" : "IdEP0V3mROyZcaFTE-8VPA",
  "version" : {
    "number" : "8.11.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "64cf052f3b56b1fd4449f5454cb88aca7e739d9a",
    "build_date" : "2023-12-08T11:33:53.634979452Z",
    "build_snapshot" : false,
    "lucene_version" : "9.8.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}

### Steps to reproduce

```Markdown
Follow the steps in "Launch service from source".
```

**Comment by KevinHuSh** [comment]
It seems you run it without docker. You need to modify conf/service_conf.yaml, change the IP of hosts to your machine's IP.
