### ISSUE TITLE
[Bug]: Build index for new document failed

### ISSUE THREAD

**Issue by BFlameSwift** [infiniflow/ragflow#921]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c0d71adaa2c6c8d5b54d2ec5e4fe51ad0ea07c01

### Other environment information

```Markdown
OS type：ubuntu20.04
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


Docker version 26.1.3, build b72abbb

```

### Actual behavior

after config ai model like openai or tongyi-Qianwen. I try to build index for new document.
but after upload a document and build this, I met the error like this:

**TypeError("'<' not supported between instances of 'NoneType' and 'int'")**

the image is as follows:

![1716604339311](https://github.com/infiniflow/ragflow/assets/69407642/6404ff7c-0366-489b-90b2-cbe0ab0eb9de)

### Expected behavior

error and the document can not be build

**the log is as follows:**

[WARNING] [2024-05-25 02:50:21,088] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7ff41c036680>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-05-25 02:50:21,089] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout
[WARNING] [2024-05-25 02:50:22,138] [_node_pool.mark_live] [line:269]: Node <Urllib3HttpNode(http://es01:9200)> has been marked alive after a successful request
[WARNING] [2024-05-25 02:50:22,138] [_node_pool.mark_live] [line:269]: Node <Urllib3HttpNode(http://es01:9200)> has been marked alive after a successful request
[WARNING] [2024-05-25 02:50:23,941] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-05-25 02:50:23,943] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!

### Steps to reproduce

```Markdown
upload a file and build document

```

**Comment by BFlameSwift** [comment]
I fetch latest code and rebased, it‘s ok now. sry for disturbing

**Comment by 576204520** [comment]
我用docker运行的也是这个问题呢

**Comment by fire717** [comment]
我用docker运行的也是这个问题 （dev和0.7.0都是）

**Comment by michliu** [comment]
me too , same error?

**Comment by kaiwenbb** [comment]
got same error after deleting knowledge base in v0.8.0 and v0.9.0
TypeError("'<' not supported between instances of 'NoneType' and 'int'")

**Comment by ZKeeer** [comment]
![图片](https://github.com/user-attachments/assets/6bf982db-d219-4529-b5c5-a9996f74cdf1)
Usually, it is caused by inaccessible minio or unable to obtain content from minio. You can first check the status of minio and whether ragflow has any errors related to minio. @michliu @kaiwenbb @fire717
