### ISSUE TITLE
[Bug]: 240525.0950 dev docker image, fails when running document parsing operations with the RAPTOR feature.

### ISSUE THREAD

**Issue by morler** [infiniflow/ragflow#922]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

ed184ed

### Other environment information

```Markdown
ASUS TUF Gamming F16 laptop
i9-13980HX 64G RTX4060 laptop
Windows11 Home 23H2
Docker v4.30.0
```

### Actual behavior
Bug(two types):
![PixPin_2024-05-25_12-15-19](https://github.com/infiniflow/ragflow/assets/478444/cbcdfdea-7ac2-428f-bda8-eebb738cc0d3)
![PixPin_2024-05-25_09-51-09](https://github.com/infiniflow/ragflow/assets/478444/58c0e32b-119b-492e-bc63-fd08ea68f8e4)

### Steps to reproduce

```Markdown
Create Knowledge Base;
Set Parameters as Follows;
Upload Document;
Start Parsing;
BOOM!
```

### Additional information

Parameters:
![PixPin_2024-05-25_12-14-05](https://github.com/infiniflow/ragflow/assets/478444/7532acc9-f778-4c8b-8ace-b37c4d224acb)
Also the file:
[file.zip](https://github.com/infiniflow/ragflow/files/15441678/file.zip)

**Comment by KevinHuSh** [comment]
fixed the number one scenario, but the number two is not re-producable.

**Comment by morler** [comment]
Thank you for fixing the bugs! 

The current test results show that **BUG1** has been resolved;

**BUG2** might be an issue with some of the LLMs used. After switching to other models, it no longer occurs.
