### ISSUE TITLE
[Question]: Streaming output does not emit one character at a time.

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#923]
### Describe your problem

Why does the stream output of Ragflow appear in chunks rather than having a typewriter effect, outputting one character at a time? Is there a way to adjust it to have a typewriter effect?

**Comment by hpx502766238** [comment]
> In my point of view, different LLMs have different streaming strategies. So you can yield one charactor at a time after LLM's response.

I use the VLLM OpenAI Compatible API. Can you tell me which file I should modify?
