### ISSUE TITLE
[Question]: How to change the python library packages installation location when using docker to start RAGFlow

### ISSUE THREAD

**Issue by ztrong-forever** [infiniflow/ragflow#926]
### Describe your problem

docker compose -f docker-compose.yml up -d 
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string. 
[+] Running 24/1
 ⠸ ragflow [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 9.245GB / 9.265GB Pulling                                                                      151.4s 
failed to register layer: write /usr/local/lib/python3.10/dist-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so: no space left on device

我的机器根目录内存比较小，所以开发中我使用的是python的虚拟环境。我在使用docker安装ragflow时，已经启动了虚拟环境，但是在安装依赖时，还是会安装在根目录的默认的python路径下。请问这个问题怎么解决，谢谢！

**Comment by KevinHuSh** [comment]
Please refer to https://gist.github.com/nileshsimaria/ec2ea6847d494d2a1935c95d7c4b7155
