### ISSUE TITLE
[Bug]: Parsing Status states FAIL despite succesfully analyzing document

### ISSUE THREAD

**Issue by t-rupe** [infiniflow/ragflow#927]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c0d71ad

### Other environment information

```Markdown
Running Docker Desktop on Windows
```

### Actual behavior

UI Outputs Parsing Status as "FAIL" despite successfully analyzing the document. It appears if it encounters the error line message "Page(1~13): [ERROR]Internal server error: list index out of range" then it assigns FAIL to the entire document status, even though I've tested the recall on the analyzed document and its able to pull from the submitted document(s). 
![ParsingFailed](https://github.com/infiniflow/ragflow/assets/111811756/2da4db9d-bef1-4c3d-a41a-dd168303984f)
m/infiniflow/ragflow/assets/111811756/b7922900-7e85-466f-884b-114b42e450d3)

![ErrorMsg](https://github.com/infiniflow/ragflow/assets/111811756/cd1919e1-7265-49c1-ac3b-097dc7980b2e)

### Expected behavior

The Parsing status should update to SUCCESS if the operation is successful despite 1 lone error message. 

### Steps to reproduce

```Markdown
Simply upload a large document. It might be from the Laws preset, but I added two separate documents, both larger than 50 pages, and it reproduced the error.
```

**Comment by KevinHuSh** [comment]
I don't know if it's convenient for you to attach the sample file which is very helpful to debug?

**Comment by t-rupe** [comment]
> I don't know if it's convenient for you to attach the sample file which is very helpful to debug?

Hi, do you mean the sample file that I uploaded? If so, I've attached it below: 

[IndustrialGeneralPermit.pdf](https://github.com/user-attachments/files/15519615/IndustrialGeneralPermit.pdf)

**Comment by yuzhichang** [comment]
The document is searchable if some chunks failed.
