### ISSUE TITLE
[Bug]: UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by PiMaV** [infiniflow/ragflow#932]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

3ae8a87

### Actual behavior

Ran into this issue:

```bash
PS C:\PYTHON\ragflow> python .\deepdoc\vision\t_ocr.py --inputs "C:\TMP\PDF_Test\Old_file.pdf"
[HUQIE]:Build default trie
[HUQIE]:Build trie C:\PYTHON\ragflow\rag/res\huqie.txt
[HUQIE]:Faild to build trie,  C:\PYTHON\ragflow\rag/res\huqie.txt 'charmap' codec can't decode byte 0x9d in position 20: character maps to <undefined>
  File "C:\PYTHON\ragflow\deepdoc\vision\t_ocr.py", line 56, in <module>
    main(args)
  File "C:\PYTHON\ragflow\deepdoc\vision\t_ocr.py", line 45, in main
    f.write("\n".join([o["text"] for o in bxs]))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\uff16' in position 581: character maps to <undefined>
```

when using this old PDF:
[https://doi.org/10.1021/ie00095a027](https://doi.org/10.1021/ie00095a027 "DOI URL")

### Steps to reproduce

```Markdown
adding

encoding='utf-8' to the open function fixed it for me:

with open(outputs\[i] + ".txt", "w+", encoding='utf-8') as f:
```

### Additional information

ragflow is awesome! THX guys!

**Comment by KevinHuSh** [comment]
Thanks for following.

**Comment by pradhyumna85** [comment]
@PiMaV, setting the below environment variables on system level (not inside python) should solve the issue:
PYTHONIOENCODING=utf-8
PYTHONUTF8=1

Like this if you have a windows machine:
![image](https://github.com/user-attachments/assets/b89588c6-3e7f-45c2-83f7-55933498d388)

related issue from another repo: https://github.com/getomni-ai/zerox/issues/47
