### ISSUE TITLE
[Bug]: dependency failed to start: container ragflow-es-01 is unhealthy

### ISSUE THREAD

**Issue by liwan14x** [infiniflow/ragflow#933]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

mian

### Commit ID

3ae8a87986089b

### Actual behavior

I use root account but encountered this error, could please help me to resolve this error?

### Steps to reproduce

```Markdown
>>>sysctl vm.max_map_count
vm.max_map_count = 262144

>>>
[root@localhost docker]# docker compose -f docker-compose-CN.yml up -d
WARN[0000] The "ELASTIC_PASSWORD" variable is not set. Defaulting to a blank string.
[+] Running 4/4
 ✔ Container ragflow-redis  Running                                                                                                           0.0s
 ✔ Container ragflow-minio  Running                                                                                                           0.0s
 ✔ Container ragflow-mysql  Healthy                                                                                                           0.5s
 ✘ Container ragflow-es-01  Error                                                                                                             0.5s
dependency failed to start: container ragflow-es-01 is unhealthy

>>>
[root@localhost docker]# docker logs ragflow-es-01

ERROR: unable to create temporary keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore.tmp], write permissions required for [/usr/share/elasticsearch/config] or run [elasticsearch-keystore upgrade], with exit code 78

ERROR: unable to create temporary keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore.tmp], write permissions required for [/usr/share/elasticsearch/config] or run [elasticsearch-keystore upgrade], with exit code 78

ERROR: unable to create temporary keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore.tmp], write permissions required for [/usr/share/elasticsearch/config] or run [elasticsearch-keystore upgrade], with exit code 78

ERROR: unable to create temporary keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore.tmp], write permissions required for [/usr/share/elasticsearch/config] or run [elasticsearch-keystore upgrade], with exit code 78


>>>
[root@localhost docker]# cd /usr/share/
[root@localhost share]# ll
总用量 116
drwxr-xr-x.   2 root   root    4096 4月  18 12:47 aclocal
drwxr-xr-x.   3 root   root    4096 4月  18 09:21 aclocal-1.13
drwxr-xr-x.   7 root   root      90 4月  18 09:21 alsa
drwxr-xr-x.   4 root   root      33 4月  18 09:21 anaconda
drwxr-xr-x.   2 root   root      85 5月  16 12:55 applications
drwxr-xr-x.   3 root   root      20 4月  18 09:20 augeas
drwxr-xr-x.   2 root   root    4096 4月  18 09:21 authconfig
drwxr-xr-x.   7 root   root     120 4月  18 09:21 autoconf
drwxr-xr-x.   4 root   root    4096 4月  18 09:21 automake-1.13
drwxr-xr-x.   2 root   root    4096 4月  18 09:21 awk
drwxr-xr-x.   2 root   root     161 4月  18 09:21 backgrounds
drwxr-xr-x.   3 root   root      25 6月  10 2021 bash-completion
drwxr-xr-x.   4 root   root    4096 4月  18 09:22 bison
drwxr-xr-x.   2 root   root      67 4月  18 09:21 centos-logos
drwxr-xr-x.   2 root   root      18 4月  18 09:20 centos-release
drwxr-xr-x.   2 root   root     163 4月  18 09:21 cracklib
drwxr-xr-x.   2 root   root      42 4月  18 09:22 cscope
drwxr-xr-x.   5 root   root     102 4月  18 09:21 dbus-1
drwxr-xr-x.   2 root   root       6 4月  11 2018 desktop-directories
drwxr-xr-x.   2 root   root       6 4月  11 2018 dict
drwxr-xr-x. 354 root   root   12288 5月  20 13:46 doc
drwxr-xr-x.   3 root   root      37 5月  16 12:55 egl
drwxr-xr-x.   3 root   root      23 4月  18 09:20 emacs
dr-xr-xr-x.   2 root   root       6 4月  11 2018 empty
drwxr-xr-x.   2 root   root      38 4月  18 12:47 et
drwxr-xr-x.   2 root   root      19 4月  18 09:21 file
drwxr-xr-x.   2 root   root       6 4月  28 2021 firewalld
drwxr-xr-x.   3 root   root      20 4月  18 09:21 firstboot
```

**Comment by liwan14x** [comment]
I have manual create the dir, but still have this error
>>>
[root@localhost AIModel]# mkdir -p /usr/share/elasticsearch/config/
[root@localhost AIModel]# chmod -R 750 /usr/share/elasticsearch/config/

**Comment by symya** [comment]
> I have manual create the dir, but still have this error
> 
> > > >
> 
> [root@localhost AIModel]# mkdir -p /usr/share/elasticsearch/config/ [root@localhost AIModel]# chmod -R 750 /usr/share/elasticsearch/config/

I also encountered the same situation, did you succeed?How to do that?

**Comment by symya** [comment]
> > I have manual create the dir, but still have this error
> > > > >
> > 
> > 
> > [root@localhost AIModel]# mkdir -p /usr/share/elasticsearch/config/ [root@localhost AIModel]# chmod -R 750 /usr/share/elasticsearch/config/
> 
> I also encountered the same situation, did you succeed?How to do that?

I succeeded 
sysctl -w vm.max_map_count=262144
that was the solution

**Comment by iSevenDays** [comment]
What did help me:

Create a new file named elasticsearch-init.sh in your project directory:
nano elasticsearch-init.sh

Add the following content to this file:
#!/bin/bash
set -e

# Set correct permissions for Elasticsearch directories
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
chmod -R 777 /usr/share/elasticsearch

# Run the original entrypoint script
exec /usr/local/bin/docker-entrypoint.sh "$@"

Make the script executable:
chmod +x elasticsearch-init.sh

Create a new Docker Compose override file named docker-compose.override.yml:
nano docker-compose.override.yml

Add the following content to this file:
version: '3'
services:
  es01:
    user: root
    entrypoint: ["/usr/share/elasticsearch/elasticsearch-init.sh"]
    volumes:
      - ./elasticsearch-init.sh:/usr/share/elasticsearch/elasticsearch-init.sh
This override file will:

Run the Elasticsearch container as root
Use our custom initialization script as the entrypoint
Mount our initialization script into the container

Now, try running your Docker Compose setup again:
docker compose down
docker compose up -d

**Comment by iSevenDays** [comment]
Add the following two files to fix the issue

root@docker-r ~/p/r/docker [SIGINT]# cat elasticsearch-init.sh
#!/bin/bash
set -e

# Set correct permissions for Elasticsearch directories
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
chmod -R 775 /usr/share/elasticsearch

# Switch to elasticsearch user and run the original entrypoint script
su elasticsearch -c "export PATH=/usr/share/elasticsearch/bin:\$PATH && /usr/local/bin/docker-entrypoint.sh $*"
root@docker-r ~/p/r/docker# cat docker-compose.override.yml
version: '3'
services:
  es01:
    user: root
    entrypoint: ["/usr/share/elasticsearch/elasticsearch-init.sh"]
    volumes:
      - ./elasticsearch-init.sh:/usr/share/elasticsearch/elasticsearch-init.sh
    environment:
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
root@docker-r ~/p/r/docker#

**Comment by LEOLEMON** [comment]
> Add the following two files to fix the issue
> ``
> ```
> root@docker-r ~/p/r/docker [SIGINT]# cat elasticsearch-init.sh
> #!/bin/bash
> set -e
> 
> # Set correct permissions for Elasticsearch directories
> chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
> chmod -R 775 /usr/share/elasticsearch
> ```
> 
> chmod +x elasticsearch-init.sh
> 
> ```
> # Switch to elasticsearch user and run the original entrypoint script
> su elasticsearch -c "export PATH=/usr/share/elasticsearch/bin:\$PATH && /usr/local/bin/docker-entrypoint.sh $*"
> root@docker-r ~/p/r/docker# cat docker-compose.override.yml
> version: '3'
> services:
>   es01:
>     user: root
>     entrypoint: ["/usr/share/elasticsearch/elasticsearch-init.sh"]
>     volumes:
>       - ./elasticsearch-init.sh:/usr/share/elasticsearch/elasticsearch-init.sh
>     environment:
>       - bootstrap.memory_lock=false
>       - ES_JAVA_OPTS=-Xms512m -Xmx512m
> root@docker-r ~/p/r/docker# 
> ```

it work for me , But for my envirenent ，I need to add another command。
```bash
  #!/bin/bash
  set -e

  # 设置 Elasticsearch 目录的权限
  chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
  chmod -R 775 /usr/share/elasticsearch
  # 不开启下面这个会有 'Exception in thread "main" java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /tmp/elasticsearch-8144570903087612665' 错误
  chown -R elasticsearch:elasticsearch /tmp 
  chmod -R 775 /tmp

  # 切换到 elasticsearch 用户并运行原始入口脚本
  su elasticsearch -c "export PATH=/usr/share/elasticsearch/bin:\$PATH && /usr/local/bin/docker-entrypoint.sh $*"
```
and edit  `docker-compose-base.yml` file 

 ```bash
    services:
      es01:
        container_name: ragflow-es-01
        profiles:
          - elasticsearch
        image: elasticsearch:${STACK_VERSION}
        user: root  # 临时使用 root 用户
        entrypoint: ["/usr/share/elasticsearch/elasticsearch-init.sh"]  # 指定初始化脚本
        volumes:
          - esdata01:/usr/share/elasticsearch/data
          - /folder1/ragflow-config/es-config/elasticsearch-init.sh:/usr/share/elasticsearch/elasticsearch-init.sh  # 挂载脚本
    ```
