### ISSUE TITLE
本地如何添加其他模型 

### ISSUE THREAD

**Issue by gugubird111** [infiniflow/ragflow#937]
### Describe your problem

下载在本地运行后，假如想使用在本地跑的ollma，或者在云服务器上运行的模型。我需要修改哪些代码呢？因为云上的接口有一些额外的鉴权字段填入来访问对应的api，

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for questions and answers.

For local deployment LLM, do you read the document?  https://ragflow.io/docs/dev/deploy_local_llm

For LLM SaaS, you may find lots of LLM SaaS have already been supported. For not-supported LLM SaaS, you can check this PR which is going to integrates Baichuan into RAGFlow.
