### ISSUE TITLE
[Bug]: operands could not be broadcast together with shapes (960,800,4) (1,1,3) 

### ISSUE THREAD

**Issue by HuuHuy227** [infiniflow/ragflow#938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

.

### Other environment information

```Markdown
OS: Linux
```

### Actual behavior

I'm trying ocr feature from deepdoc with an image by cmd "python deepdoc/vision/t_ocr.py --inputs=path_to_images_or_pdfs --output_dir=path_to_store_result". But i encountered the error like the title.  

### Steps to reproduce

```Markdown
I clone only deepdoc feature and install dependencies needed for it. Trying ocr feature and encountered the error above.
```

**Comment by HuuHuy227** [comment]
Fixed: My image is read by 4 channel. Convert to 3 channel could solve the problem

**Comment by HuuHuy227** [comment]
Fixed: My image is read by 4 channel. Convert to 3 channel could solve the problem

**Comment by Lw1244204021** [comment]
> Fixed: My image is read by 4 channel. Convert to 3 channel could solve the problem

hi, can you share the code to fix the bug?

**Comment by HuuHuy227** [comment]
> > Fixed: My image is read by 4 channel. Convert to 3 channel could solve the problem
> 
> hi, can you share the code to fix the bug?

Just read the image and convert to 3 channel:
image = Image.open('path_to_your_image.png')
# Convert the image to RGB, which will drop the alpha channel if present
image = image.convert('RGB')

**Comment by Lw1244204021** [comment]
> > > Fixed: My image is read by 4 channel. Convert to 3 channel could solve the problem
> > 
> > 
> > hi, can you share the code to fix the bug?
> 
> Just read the image and convert to 3 channel: image = Image.open('path_to_your_image.png') image = image.convert('RGB') // Convert the image to RGB, which will drop the alpha channel if present

oh，thx，I solved it this way
