### ISSUE TITLE
reassemble the content into sentences which could be well comprehended by LLM

### ISSUE THREAD

**Issue by Bill-WangJiLong** [infiniflow/ragflow#942]
### Describe your problem

In the readme of deepdoc, it is mentioned that tables will be converted into natural language sentences that are easy to handle by LLM. How is it implemented, or in which parts of the code?

**Comment by KevinHuSh** [comment]
In deepdoc/vision/table_structure_recognizer.py, it's coperated with deepdoc/parser/pdf_parser.py

**Comment by Bill-WangJiLong** [comment]
Where will this part of the effect be output? I saw in the web demo that the table is output in HTML format
