### ISSUE TITLE
[Question]: What model is layout.onnx and where to download it?

### ISSUE THREAD

**Issue by cxiaowen** [infiniflow/ragflow#943]
### Describe your problem

(cxw1) E:\xmg\ragflow-main>python deepdoc/vision/t_recognizer.py --inputs=./house.pdf --threshold=0.2 --mode=layout --output_dir=./
[HUQIE]:Build default trie
[HUQIE]:Build trie E:\xmg\ragflow-main\rag/res\huqie.txt
[HUQIE]:Faild to build trie,  E:\xmg\ragflow-main\rag/res\huqie.txt 'gbk' codec can't decode byte 0xab in position 4: illegal multibyte sequence
Traceback (most recent call last):
  File "E:\xmg\ragflow-main\deepdoc\vision\t_recognizer.py", line 189, in <module>
    main(args)
  File "E:\xmg\ragflow-main\deepdoc\vision\t_recognizer.py", line 34, in main
    detr = Recognizer(
  File "E:\xmg\ragflow-main\deepdoc\vision\recognizer.py", line 52, in __init__
    raise ValueError("not find model file path {}".format(
ValueError: not find model file path E:/xmg/ragflow-main/rag/res/deepdoc/layout.onnx

**Comment by cxiaowen** [comment]
hello，can you tell me What model is layout.onnx and where to download it?,,

**Comment by HuuHuy227** [comment]
> hello，can you tell me What model is layout.onnx and where to download it?,,

They are served on HuggingFace https://huggingface.co/InfiniFlow/deepdoc

**Comment by KevinHuSh** [comment]
For the above exception, it's wired.
You could put [this](https://huggingface.co/InfiniFlow/huqie/blob/main/huqie.txt.trie) to rag/res.
