### ISSUE TITLE
[Feature Request]: Dockerfile that matches docker image infiniflow/ragflow:v0.6.0 in docker hub.

### ISSUE THREAD

**Issue by CamusGao** [infiniflow/ragflow#950]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

As i observed, infiniflow/ragflow:v0.6.0(`sha256:d9d1942cb5caa1564adb0c2543c2d4175ddbdd19422f9c35ab1caab8c003e6a0`) doesnot match any dockerfile in this git repo. Why do you guys not open source dockerfile you actually used.

**Comment by KevinHuSh** [comment]
We put embedding models into the image which is not good to write into Dockerfile.
That's where the difference come from.
