### ISSUE TITLE
[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#952]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

newest

### Other environment information

```Markdown
[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows
```

### Actual behavior

[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows

### Expected behavior

[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows

### Steps to reproduce

```Markdown
[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows
```

### Additional information

[Bug]: when i install datrie==0.8.2 in windows，error，could you tell me how to run in windows

**Comment by CamusGao** [comment]
hi, if you'd like to run ragflow in windows, use WSL. I've got a good dev and debug experience with WSL. PyCharm and vscode have good support to WSL.

**Comment by sanwei111** [comment]
any other better method，sir？

**Comment by Seaver-Zhu** [comment]
> any other better method，sir？
I tried the command below and it worked.

pip3 install git+https://github.com/pytries/datrie.git
