### ISSUE TITLE
[Bug]: Why location information is also involved in naive chunking result ? Why naive text parsing is slower than table paring?

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#953]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

newest

### Other environment information

```Markdown
[Bug]: 为什么naive的结果还有一些坐标信息，请问在哪里对这些信息进行后处理？另外，为什么naive的结果没有表格的块？
```

### Actual behavior

[Bug]: 为什么naive的结果还有一些坐标信息，请问在哪里对这些信息进行后处理？另外，为什么naive的结果没有表格的块？

### Expected behavior

[Bug]: 为什么naive的结果还有一些坐标信息，请问在哪里对这些信息进行后处理？另外，为什么naive的结果没有表格的块？

### Steps to reproduce

```Markdown
[Bug]: 为什么naive的结果还有一些坐标信息，请问在哪里对这些信息进行后处理？另外，为什么naive的结果没有表格的块？
```

### Additional information

[Bug]: 为什么naive的结果还有一些坐标信息，请问在哪里对这些信息进行后处理？另外，为什么naive的结果没有表格的块？

**Comment by KevinHuSh** [comment]
Disabling "Layout recognize" will lose position info.
![image](https://github.com/infiniflow/ragflow/assets/12318111/71210bcf-c051-4be5-89b2-4145f3208095)
'Table' method will not do layout recognize.
