### ISSUE TITLE
[Bug]: Which parameter is used to set 'Task page size' variable?

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#955]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

 er

### Commit ID

efg'

### Other environment information

```Markdown
aedth
```

### Actual behavior

hg

### Expected behavior

th

### Steps to reproduce

```Markdown
dth
```

**Comment by JinHai-CN** [comment]
We intend to create an international community, so we encourage using English for questions and answers.

**Comment by KevinHuSh** [comment]
parser_config.task_page_size
