### ISSUE TITLE
proposal ：insert_citations function update

### ISSUE THREAD

**Issue by worldlanguage** [infiniflow/ragflow#957]
while thr>0.3 and len(cites.keys()) == 0 and pieces_ and chunks_tks:
            for i, a in enumerate(pieces_):
                sim, tksim, vtsim = self.qryr.hybrid_similarity(ans_v[i],
                                                                chunk_v,
                                                                rag_tokenizer.tokenize(
                                                                    self.qryr.rmWWW(pieces_[i])).split(" "),
                                                                chunks_tks,
                                                                tkweight, vtweight)
  
  
To:
        if chunks_tks:
            pieces_tks = [rag_tokenizer.tokenize(self.qryr.rmWWW(pieces_[i])).split(" ") for i in range(len(pieces_))]
        while thr>0.3 and len(cites.keys()) == 0 and pieces_ and chunks_tks:
            for i, a in enumerate(pieces_):
                sim, tksim, vtsim = self.qryr.hybrid_similarity(ans_v[i],
                                                                chunk_v,
                                                                pieces_tks,
                                                                chunks_tks,
                                                                tkweight, vtweight)

**Comment by KevinHuSh** [comment]
How about submitting a PR.
