### ISSUE TITLE
[Feature Request]: Support LM Studio standard OpenAI API

### ISSUE THREAD

**Issue by rickywu** [infiniflow/ragflow#961]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Yes, Can not read embedding model from LM Studio
```

### Describe the feature you'd like

Support LM Studio standard OpenAI compatible API

### Describe implementation you've considered

See lmstudio.ai

**Comment by KevinHuSh** [comment]
Supported.
