### ISSUE TITLE
[Question]: 可以解释下这个代码作用吗

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#970]
### Describe your problem

 for c in Recognizer.sort_X_firstly(chars, self.mean_width[pagenum - 1] // 4):  # 这个函数要干嘛
            ii = Recognizer.find_overlapped(c, bxs)
            if ii is None:
                self.lefted_chars.append(c)
                continue
            ch = c["bottom"] - c["top"]
            bh = bxs[ii]["bottom"] - bxs[ii]["top"]
            if abs(ch - bh) / max(ch, bh) >= 0.7 and c["text"] != ' ':
                self.lefted_chars.append(c)
                continue
            if c["text"] == " " and bxs[ii]["text"]:
                if re.match(r"[0-9a-zA-Z,.?;:!%%]", bxs[ii]["text"][-1]):
                    bxs[ii]["text"] += " "
            else:
                bxs[ii]["text"] += c["text"]
                

代码在pdf_parser.py

**Comment by JinHai-CN** [comment]
We intend to create an international community, would you please re-submit the issue in English, thank you very much ?
