### ISSUE TITLE
[Question]: waht's the prupose of below code

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#975]
### Describe your problem

in pdf_parser.py ,
 if sum([1 if e else 0 for e in self.is_english]) > len(self.page_images) / 2:
            self.is_english = True
        else:
            self.is_english = False

        self.is_english = False

why do u set self.is_english = False finally?

**Comment by KevinHuSh** [comment]
Previously, different approaches were taken for handling languages, but the results were not satisfactory, so it was abandoned.
