### ISSUE TITLE
How to start parsing of a single document, seem to start but not to progress

### ISSUE THREAD

**Issue by joergkoch** [infiniflow/ragflow#979]
### Describe your problem

Hi,

I downloaded and installed RAGFlow 0.0.6 and uploaded a single pdf document. I configured chunking and when I press start the porcess seem to somehow start as I get a initial percentage and the elapsed time is increasing. But after having waited for several hours I still get that screen:
![image](https://github.com/infiniflow/ragflow/assets/37538901/3ef34a41-be01-49fa-a792-597dc079adbe)

Is there a way to get mor information on the parsing process as in the log I also do not see any errors:
![image](https://github.com/infiniflow/ragflow/assets/37538901/adb9b5dd-2313-4621-ac82-59967832dd70)

What am I missing to get it started?

Thanks for ypur help

**Comment by KevinHuSh** [comment]
Cancel it and redo.
It will be fixed in the latest released version.
