### ISSUE TITLE
[Question]: Redis invalid username-password pair or user is disabled.

### ISSUE THREAD

**Issue by Brabalawuka** [infiniflow/ragflow#981]
### Describe your problem

<img width="609" alt="CleanShot 2024-05-29 at 22 53 57@2x" src="https://github.com/infiniflow/ragflow/assets/31028570/e053344e-3576-48af-bf4d-2671bcb80082">

redis has some issue when starting the docker compose.

<img width="1457" alt="CleanShot 2024-05-29 at 22 54 42@2x" src="https://github.com/infiniflow/ragflow/assets/31028570/613202fd-b410-4b27-9e20-b1f7d81f4b3b">

Did not do anything on original script. Just docker compose up. Not sure why 

os: macos ventura 13.5
docker version: 25.0.5
Kernel Version: 6.7.11-orbstack-00143-ge6b82e26cd22
Cimmit: commit 9fdd517af691863d560abdd204b7e444f4026497 (HEAD -> main, origin/main, origin/HEAD)
Version: 0.6.0

**Comment by KevinHuSh** [comment]
Check the docker/.env. Keep it unchanged.
Upload and parse a file. Check if the processing is good.
