### ISSUE TITLE
[Question]: i run the naive.py,what's the meaning of the result

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#983]
### Describe your problem

i run the naive.py,what's the meaning of the result,outputs some result:
-- 数据来源本报告使用数据及资料主要源自公开数据、内部统计报表、第三方调研、行政文件及报告等相关文件。@@1	37.3	409.3	573.3	584.0##报告批准本报告于2024 年3月22日获得董事会审阅确认，批准发布。@@1	37.3	262.0	626.3	637.0##报告获取w.hkexnews.hk）或本公司的官方网站本（报h/文）及获取英。文如三中个英版文本版供本读有者任参何阅不，相报符告之电处子，版应可以在中联文交简所体网版站本（为w准w。@@1	37.3	559.0	678.3	700.3##
-- 意见管治报告01@@1	427.0	559.7	771.7	782.7##

1. where is the table result?
2. how to parse?
3. what's the meaning of every line: -- xxx.
4. what's the meaning of every chunk of each line: such as   数据来源本报告使用数据及资料主要源自公开数据、内部统计报表、第三方调研、行政文件及报告等相关文件。@@1	37.3	409.3	573.3	584.0##

**Comment by KevinHuSh** [comment]
Text like this @@1 37.3 559.0 678.3 700.3## define the position of this chunk.
You could start the project if you don't mind.
