### ISSUE TITLE
[Question]: could you plz help me explain following code？

### ISSUE THREAD

**Issue by sanwei111** [infiniflow/ragflow#989]
### Describe your problem

in pdf_parser.py,
# merge chars in the same rect
        recognize_sort_x_result = Recognizer.sort_X_firstly(chars, self.mean_width[pagenum - 1] // 4)
        for c in recognize_sort_x_result:  # 这个函数要干嘛
            ii = Recognizer.find_overlapped(c, bxs)
            if ii is None:
                self.lefted_chars.append(c)
                continue
            ch = c["bottom"] - c["top"]
            bh = bxs[ii]["bottom"] - bxs[ii]["top"]
            if abs(ch - bh) / max(ch, bh) >= 0.7 and c["text"] != ' ':  # 本来是0.7
                self.lefted_chars.append(c)
                continue
            if c["text"] == " " and bxs[ii]["text"]:
                if re.match(r"[0-9a-zA-Z,.?;:!%%]", bxs[ii]["text"][-1]):
                    bxs[ii]["text"] += " "
            else:
                bxs[ii]["text"] += c["text"]

**Comment by KevinHuSh** [comment]
It is for merging overlapped boxes which are sorted horizontally at the first place.
