### ISSUE TITLE
[Bug]:Fail to access embedding model(embedding-2) using this api key.Error code: 429

### ISSUE THREAD

**Issue by yuanpneg** [infiniflow/ragflow#995]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

#995

### Actual behavior

 I previously used an API for testing, and after the token was used up, I tried to use a new key. However, it keeps showing 'outstanding balance' during configuration.
![1717056668555](https://github.com/infiniflow/ragflow/assets/52906027/feb44ebb-1818-46fd-9eeb-20a46a0560bd)

### Steps to reproduce

```Markdown
Reset the API configuration
```

**Comment by KevinHuSh** [comment]
Out of quota.  It seems you need to top up instead of getting a new key.
